### ISSUE TITLE
onDelete Commands?

### ISSUE THREAD

**Issue by ScottRandallWay** [knex/knex#1065]
the schema onDelete operation takes a command:  column.onDelete(command) 

what are the possible commands that can be used?   what does each command do?  I see people using examples with 'CASCADE'.   Is there any documentation on this?

Scott

**Comment by cbmono** [comment]
Don't know if there are any other options, but `CASCADE` should be the option you need. Probably valid for 99.9% of the cases.

**Comment by Meleeman01** [comment]
it would be nice to have onDelete() methods for timestamp and similar data types. this would make tracking deleted content much easier.

**Comment by elhigu** [comment]
Closing old issue. onDelete() is basic SQL functionality and documented there. Basically CASCADE and SET NULL are the most commonly used behaviors.
