### ISSUE TITLE
Support for arrays and smallint

### ISSUE THREAD

**Issue by JakeDluhy** [knex/knex#1173]
I was wondering if there is any support for arrays of smallints. I couldn't find any documentation about building schema for either of these types separately, and I was curious.

If not, I'd be willing to take a crack at forking and implementing.

**Comment by wubzz** [comment]
I think they were omitted solely because the datatypes aren't present in all supported database types? Don't quote me on that, could be wrong.

A workaround is using `specificType`

```javascript
table.specificType('ColumName', 'smallint');
```

**Comment by JakeDluhy** [comment]
Excellent! It took me a little bit of time to test it out, but I can confirm that `specificType` works.
Thanks!

**Comment by kevbook** [comment]
How can one add length to it?
Example `table.specificType('ColumName', 'tinyint', 1);`

**Comment by kevbook** [comment]
Got it! `table.specificType('ColumName', 'tinyint(1)');`

**Comment by lmedson** [comment]
> I think they were omitted solely because the datatypes aren't present in all supported database types? Don't quote me on that, could be wrong.
> 
> A workaround is using `specificType`
> 
> ```js
> table.specificType('ColumName', 'smallint');
> ```

Thanks

**Comment by Mehran91z** [comment]
Hello

It seems there is a **undocumented** method for `smallint` type:
`table.smallint('columnName');`

**Comment by OlivierCavadenti** [comment]
> Hello
> 
> It seems there is an **undocumented** method for `smallint` type:
> 
> ```
> table.smallint('columnName');
> ```

tinyint and mediumint exists too. PR documentation for them are welcome :D.

**Comment by OlivierCavadenti** [comment]
I reopen this because some types missing in index.d.ts (smallint and mediumint) and need a PR here + doc.

**Comment by kibertoad** [comment]
Released in 1.0.1.
