### ISSUE TITLE
RETURNING * not allowed with current code

### ISSUE THREAD

**Issue by tonyd256** [knex/knex#132]
I'd like to be able to use RETURNING \* at the end of insert and update statements.  However, returning is implemented so you can only receive one column back. This could be fixed by eliminating the double quotes surrounding `qb.flags.returning` on line 43 in clients/server/postgres/grammar.js and by returning rows in the `handleResponse`  function just below for INSERTs and UPDATEs.  I could make these changes and submit a PR if you'd like but these changes might break existing implementations.

**Comment by lancecarlson** [comment]
Can the documentation be updated to reflect this change? Latest docs only show that you can pass one argument.
