### ISSUE TITLE
Subquery not working with withSchema

### ISSUE THREAD

**Issue by dizlexik** [knex/knex#1368]
I ran into this issue today and it's blocking me for now :/

This produces the expected query:
`knex.select(1).from(function() { this.select(1).from('mytable') })`
-> `select 1 from (select 1 from [mytable])`

This does not:
`knex.withSchema('myschema').select(1).from(function() { this.select(1).from('mytable') })`
-> `select 1 from [myschema].[function () { this].[select(1)].[from('mytable'); }]`

**Comment by igor-savin-ht** [comment]
@elhigu Any way to contribute to this issue? Would e. g. test that reproduces the issue help?

**Comment by elhigu** [comment]
@igor-savin-ht PR with test + fix would be really helpful. I don't have fixing this issue in my todo list.

**Comment by devourment77** [comment]
I hit this issue today.  It looks like the schema is prepended to the subquery (EX: `<schema>.select`)

**Comment by kibertoad** [comment]
Released in 0.95.0, please reopen if this still does not work for you.
