### ISSUE TITLE
Clone knex instance

### ISSUE THREAD

**Issue by agmoyano** [knex/knex#141]
Is it possible to clone a knex instance, in order to reuse code?. For example, supose we have:

``` javascript
var query = knex('some-table as t1')
  .select('something')
  .join('other-table as t2', 't1.id', '=', 't2.t1_id');

function where1() {
  //reuse previous joins in query, 
  //but with specific where
  var q = query.clone()
    .where('t1.a', '=', 1);
  q.exec(function(err, response) {
    //do something
  });
}

function where1() {
  //reuse previous joins in query, 
  //but with specific where and join
  var q = query.clone()
    .join('third-table as t3', 't2.id', '=', 't3.t2_id')
    .where('t3.b', '=', 1);
  q.exec(function(err, response) {
    //do something
  });
}
```

Thanks.

**Comment by straube** [comment]
Hello @tgriesser, any news on this topic? I'd be interested in reusing knex objects for multiple queries with small changes, like @agmoyano commented.

If currently there is a way to do that without cloning the object, please let me know.

Thanks!

**Comment by KristjanTammekivi** [comment]
Small bump as this is still something that's a gotcha to new developers and a PITA for experienced ones

**Comment by elhigu** [comment]
@KristjanTammekivi umm... if you mean the fact to make knex builder immutable, that would be a huge change to the way how knex behaves + pretty much everyone would need to rewrite their knex code to support the new way (immutability would be nice though). Also making that happen in an efficient way would require huge changes to internal implementation.

**Comment by nextmat** [comment]
A common case for this is defining an object to run multiple queries against the same table. For example: 

```
const myTable = knex('vehicles');
const cars = myTable.select(['id', 'name']).where('type', 'car')
const bicycles = myTable.select(['id', 'name']).where('type', 'bicycle')
```

In this instance the second query fails because it will select where type equals both values as the state stacks. I've seen a bunch of ways to get around this, but it seems like a common enough case that it might be worth supporting with some kind of immutable stub?

**Comment by elhigu** [comment]
> In this instance the second query fails because it will select where type equals both values as the state stacks. I've seen a bunch of ways to get around this, but it seems like a common enough case that it might be worth supporting with some kind of immutable stub?

There is a `.clone()` method for that... 

```
const vehicles = knex('vehicles').select(['id', 'name']);
const cars = vehicles .clone().where('type', 'car');
const bicycles = vehicles .clone().where('type', 'bicycle');
```

of course immutable query builder would be nicer (even that it would break pretty much everyone's current code. Also to implement immutability efficiently knex internals should be pretty much rewritten.

**Comment by nextmat** [comment]
@elhigu - Thanks for the response. That makes sense and thanks for the pointer to `.clone`.

I totally get what you are saying about breaking the current implementation and a generalized immutable query builder. To be more clear I guess I was wondering if adding a different method for immutable table selection was possible without breaking everything else, treating it as a special case because it seems like a very common case, much more common than building a partial complex query and then running variations of it.

I haven't dug into the internals a lot, but if this was possible and there was interest I would consider working on it.

I could see this implemented something like this to avoid breaking existing implementations:

```js
mytable = knex.table('books', immutable: true)
```

Does this make any sense?

**Comment by elhigu** [comment]
Big problem with allowing immutable + non-immutable query builders at the same time is that we would have to add lots of testing to cover both ways well enough.

Basically if that support would be implemented I would prefer deprecating non-immutable way as soon as possible, but still providing at least one knex version that could be used to migrate projects easily that supports the both ways, but test bench doesn't have to support the both ways (having configuration switch, which enables immutability, change all tests to work with immutable query builders by default etc.) 

So it would be more like:

```
const knex = require('knex')({ client: 'pg', immutableQueryBuilder: true, connection: {...}});
```

Anyways that would mostly require rewrite of knex internals to be performant. Hacky implementation would be to add lots of clone() everywhere and hope that it works, but in my opinion that is a bad idea and I would not support that route.

**Comment by nextmat** [comment]
@elhigu - That makes sense, thanks for the explanation!

**Comment by lorefnon** [comment]
@elhigu Do you think there is value in the following approach: 

1. Knex QueryBuilder supports an intermediate JSON/serializable representation (along with fromJSON and toJSON functions) and internals (Query compiler etc.) depend on this JSON. 

2. Two query builder implementations (mutable and immutable) can target the same representation internally with same (or almost same) APIs. 

3. Over time the mutable one can be deprecated if there are no obvious performance concerns. 

If this is something that can potentially be adopted, I can fiddle around this over the next couple weeks to gauge how much effort and testing will be required.

**Comment by rcrogers** [comment]
Knex is great, but mutability and a fluent/chainable API makes a dangerous and counter-intuitive combination.  Registering interest in a `immutableQueryBuilder: true` option.
