### ISSUE TITLE
defaultTo now() / CURRENT_DATE / CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by tkellen** [knex/knex#146]
First, thanks for the great work on this module!

Second, is this presently possible in the schema builder in some form I'm not aware of?

**Comment by kevin-romens** [comment]
@tgriesser  hi ,I wanna build sql like this :
     select  \`name \` ,\`age\`, year(curDate())-year(birthDate)) as age from \`Student\`.

 the mysql inner function curDate() must use raw,but I don't know how to connect with select , could you please help me ? thanks ~~~

**Comment by rhys-vdw** [comment]
@kevin-romens please open new issues in future, this has been closed for two and a half years.

```js
knex('Student').select('name', 'age', knex.raw('year(curDate()) - year(birthDate)) as age'));
```

**Comment by jurko-gospodnetic** [comment]
Probably just a typo - but this would define two columns with the same name `age`.

**Comment by kevin-romens** [comment]
@rhys-vdw  got it .  thank you !
