### ISSUE TITLE
Add support to remove certain single parts of a query (e.g. offset, limit)

### ISSUE THREAD

**Issue by jgornick** [knex/knex#1476]
Currently, there doesn't seem to be a way to remove a limit from a query. I would expect `.limit(null)` to clear it out, but seems to keep the previously set limit value.

My use case is I have a query where I clone it and remove the limit and offset so that I can capture an entire count row count of the query before sending it back to the client. I clone my original query, then want to remove the limit.

My workaround for now is to set the offset to 0 and a limit of some number greater than all record count.

Thanks!

**Comment by elhigu** [comment]
Sadly Knex doesn't support removing stuff from query builder / asking any metadata about the query (which would be really nice feature).

**Comment by wubzz** [comment]
I would consider this a bug based on implementation comparison of `.limit()` and `.offset()`. From a quick peak I can tell "nullifying" offset after a clone is possible, but trying to do the same for `limit()` will print
>A valid integer must be provided to limit

**Comment by elhigu** [comment]
Can order by be removed too? What does documentation say about these? Is passing null still undefined behavior? 

I'm fine with allowing to remove limit, offset, order by and others (if there are some more) by overriding them wirh null, but I would like to have that kind of functionality to be documented and consistent as well.

(Cant check docs now... Sleeping + answering fron mobile :)

**Comment by wubzz** [comment]
@elhigu `.orderBy()` is even worse, this throws an error when called with null because of a missing safe-guard in the compiler. It trying to `formatter.columnize(null)` which throws `TypeError: Cannot read property 'length' of null`.

At the same time, `.orderBy()` is a bit more tricky. You can call the function multiple times for the same querybuilder and it will append to the sort order, so you get multiple objects. Therefore, resetting by calling with null isn't really valid for this function. That brings us back to your point of removing stuff from the querybuilder, which is something we lack today.

**Comment by arjun-livquik** [comment]
My solution is simple and it works for me.
eg.
```
  var qb = knex.select('*').from('users');
  if(limit){
    qb.limit(limit);
  }
  if(offset){
    qb.offset(offset);
  }
  qb.then(function(res){
    console.log(res);
  }, function(err){
    console.error(err);
  });
```

Similar thing can be done for `.orderBy()` as well I guess.

**Comment by arjunnayak0705** [comment]
My solution is simple and it works for me.
eg.
```
  var qb = knex.select('*').from('users');
  if(limit){
    qb.limit(limit);
  }
  if(offset){
    qb.offset(offset);
  }
  qb.then(function(res){
    console.log(res);
  }, function(err){
    console.error(err);
  });
```

Similar thing can be done for `.orderBy()` as well I guess.

**Comment by demisx** [comment]
Would love to have this also work with `.where`.

**Comment by Fi1osof** [comment]
Still waiting for...

**Comment by kibertoad** [comment]
@Fi1osof Would you consider creating a PR for this?

**Comment by Fi1osof** [comment]
@kibertoad done, but tests shows error https://github.com/tgriesser/knex/pull/2868

**Comment by mdartic** [comment]
Any news on this feature ? 
I think I'm in this use case !
If needed, I could work on it.

**Comment by intech** [comment]
The private method `_clearGrouping` is used for the `ClearClauses` methods
https://github.com/knex/knex/blob/f5835b379eec14dab00aa2193f6dcf598302863a/lib/query/builder.js#L1243-L1245
which we can make public by analogy with the method `clear` from `objection.js`

**Comment by intech** [comment]
@mdartic @elhigu @wubzz @kibertoad please write your opinion about my PR.
After your approval, I will test and update the documentation. Thanks.

**Comment by kibertoad** [comment]
Released in 0.21.9

**Comment by adarshmadrecha** [comment]
anyone who came through google search - the feature is documented here - http://knexjs.org/#Builder-clear

Clears the specified operator from the query. 
Avalilables: 'select' alias 'columns', 'with', 'select', 'columns', 'where', 'union', 'join', 'group', 'order', 'having', 'limit', 'offset', 'counter', 'counters'. Counter(s) alias for method .clearCounter()

`knex.select('email', 'name').from('users').where('id', '<', 10).clear('select').clear('where')`
Outputs:
`select * from `users``

**Comment by KarmaBlackshaw** [comment]
would it be possible to clear only a specific join?
