### ISSUE TITLE
migration config

### ISSUE THREAD

**Issue by tkellen** [knex/knex#150]
it would be nice if you could call migration on a knex instance without passing in additional config.  maybe store the config on the knex instance and allow the directory/tablename to be a part of it

**Comment by reshma-r-p** [comment]
Are all data types available in knex for table migration? As I am tried bigserial in knex migration it shows type not supported error

**Comment by elhigu** [comment]
@reshma-r-p does your DB support bigserial type? With `.specificType()` one can create column of any custom type that DB supports.

**Comment by reshma-r-p** [comment]
yup. I am using pg 9.6 version

**Comment by reshma-r-p** [comment]
Thanks @elhigu Its worked.
