### ISSUE TITLE
Ability to drop foreign key

### ISSUE THREAD

**Issue by fjorgemota** [knex/knex#157]
Hello.

Thanks for the great library!

I am testing Knex in a NodeJS application and found a thing that makes sense for migrations: The hability to drop foreign keys in Schema, without dropping columns.

This make senses to allow a field to be renamed correctly when having a foreign key to another table, for example.

And, if possible, too, allow the renameColumn function to detect correctly when a field is a foreign key, drop it and re-create it after the renaming.

But...these is just suggestions, the community is free to think about.

Thanks and sorry for the poor english.

**Comment by stringbeans** [comment]
Can the maintainer please add this to the documentation?

**Comment by rhys-vdw** [comment]
Hi @stringbeans. There is currently an open issue tracking these missing schema docs #483. Please provide a PR with the missing method documentation you would like added and I'll gladly merge them into our gh-pages branch. Thanks!

**Comment by stringbeans** [comment]
@rhys-vdw thanks! and apologies for not searching for the other issue!

**Comment by rhys-vdw** [comment]
@stringbeans `dropForeign` and `foreign` docs have just been added via #1156
