### ISSUE TITLE
Does Knex support LATERAL joins?

### ISSUE THREAD

**Issue by jeffreybrowning** [knex/knex#1651]
I see that Knex supports `crossJoin` but I was wondering if it also supports `LATERAL` joins? 

I would expect to be able to do something like this:

```
with data(ar) as (
    values (array['73da82a4-ef9e-402e-b817-197cb4966231']::uuid[]),
    (array['dcf3b590-d471-4357-a930-e54ba1e45065','b6fc978f-288d-4cac-9c84-2bdac7a34aa4','b2205297-e8aa-4962-b76e-b2d38558b29c']::uuid[]),
    (array[]::uuid[]),
    (null)
)
select 
    array_agg(foo) as values,
from data, unnest(data.ar) AS foo;
```

Could the `FROM` clause here be done in knex like:

`knex.from([`'<tableName>' as foo`, knex.raw(`unnest('<foo.columnName>') as isThisHard`]))`

**Comment by OlivierCavadenti** [comment]
This issue is more complete and recent : https://github.com/knex/knex/issues/3732. I close this one to avoid duplicates.
