### ISSUE TITLE
Build complex query from object?

### ISSUE THREAD

**Issue by crunchtime-ali** [knex/knex#1653]
Strongloop supports building queries with objects like:

```
{where: {
  input: {
     gt: userInput.min,
     lt: userInput.max
    }
  }
}
```

I've built my own logic to parse such objects to Knex queries but I'm wondering whether someone already did that?

**Comment by atiertant** [comment]
yes, you could have a look at [offshore-sql](https://github.com/Atlantis-Software/offshore-sql)
this is an adapter for [offshore](https://github.com/Atlantis-Software/offshore) orm

**Comment by ravshansbox** [comment]
Would be a great feature.

**Comment by elhigu** [comment]
I wouldn't like to add knex more styles how to create queries. Maybe external library, which uses knex as builder would be better choice.
