### ISSUE TITLE
Adding different types of debug options

### ISSUE THREAD

**Issue by tgriesser** [knex/knex#167]
http://stackoverflow.com/questions/21292677/knex-js-debug-only-sql/21293552#21293552

**Comment by pursual** [comment]
This solution doesn't seem to allow for logging the query with inline bindings, instead of placeholders.

**Comment by pasupulaphani** [comment]
```this.on("start"``` doesn't seem to fire for knex raw queries.

**Comment by Roam-Cooper** [comment]
That's not the correct way to get the time, because what you get is query time + db server latency. It wouldn't be a consistent metric.

**Comment by MarkHerhold** [comment]
You can provide `debug: true` in the options object when initializing knex. See [the knex docs](http://knexjs.org/#Installation-debug) for more information.

This issue ranks highly when googling "knex debug". I hope this helps someone. 👍
