### ISSUE TITLE
Option for "DEFEFFERED INITIALLY DEFERRED" in schemas?

### ISSUE THREAD

**Issue by scf4** [knex/knex#1830]
When I do something like:

`table.integer('user_id').unsigned().index().references('id').inTable('users');`

and then create a reference inside a transaction (a reference to a row created just before it in the same transaction). It fails unless I defer the foreign key with the 'initially deferred' option.

Do I need to alter my schemas manually like:

```
ALTER TABLE table_name
  ADD CONSTRAINT "constraint_name" FOREIGN KEY ("blah_id")
    REFERENCES "blahs"("id")
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE 
    INITIALLY DEFERRED;
```

Or is there an easier way within Knex?

**Comment by derMart** [comment]
+1 have the same problem

**Comment by derMart** [comment]
here is the workaround I use currently: 
https://gist.github.com/derMart/87e75fbd1fdca73d6d3cebf561ca3fc6
automatically alters all foreign key constraints to be deferrable

**Comment by scf4** [comment]
Thank you @derMart 

I'll dig into knex and see if I can create a PR after Christmas if there isn't one by then.

**Comment by 7sempra** [comment]
+1, this is a real issue in sqlite where we can't alter constraints after creating them.

**Comment by scf4** [comment]
In the mean time here's a greatly simplified version of what @derMart posted without lodash and all that nesting:
https://gist.github.com/scf4/03780af508218200a590959d8258f61c

**Comment by mlarcher** [comment]
Is there any chance to have a Knex native way to set "DEFERRABLE INITIALLY DEFERRED" on a table with foreign key constraints ?  
Time flies but this quick feature would still come in handy today...

**Comment by RusinovAnton** [comment]
I need this feature too

**Comment by elhigu** [comment]
Closing old issue with low activity. The feature request doesn't meet current criteria of having API proposal etc.

If someone still would like to design this, please open a new feature request.
