### ISSUE TITLE
Request: enable "indexType" on MySQL dialect.

### ISSUE THREAD

**Issue by musou1500** [knex/knex#1840]
I want to create spatial index to specific column by using this feature.
I know `knex.raw` make it possible to do.

**Comment by douglasjunior** [comment]
This is very important, how can I create an index of type FULLTEXT?

**Comment by elhigu** [comment]
@douglasjunior with `knex.schema.raw()` at least. I cannot remember if passing index type was already fixed.

**Comment by kibertoad** [comment]
@douglasjunior According to documentation, it is supported, see https://knexjs.org/#Schema-index
If you try and it doesn't work, please consider raising a PR with failing test for it, then we could address it rapidly.

**Comment by douglasjunior** [comment]
I'm writing a PR right now. 😆

**Comment by douglasjunior** [comment]
Done #2890.

**Comment by glensc** [comment]
@knex: perhaps close, as indexType was added with #2890.

**Comment by glensc** [comment]
```ts
  await knex.schema.alterTable('article_attribute', (table) => {
    table.index('value_text', 'article_attribute_value_text', 'FULLTEXT');
  });
```
