### ISSUE TITLE
Using :memory: SQLite engine causes DB to be wiped repeatedly

### ISSUE THREAD

**Issue by parkan** [knex/knex#1871]
It appears that knex uses a connection pool with an idle timeout when connecting to SQLite in `:memory:` mode. This causes the database contents to be dropped after ~30s of inactivity (when the connection is closed), making it impossible to use that engine.

This is a particularly bad gotcha because a test suite, or non-interactive usage with something hammering the DB, will work fine.

**Comment by elhigu** [comment]
Yes, connection close with sqlite inmemory database wipes up the DB. 

Looks like there is some connection close/discard timeout in pool for sqlite by default, which shouldn't be applied to databases where pool size is 1.

I was able to reproduce this by:

```js
shell $ DEBUG=knex:* node

> knex = require('knex')({ client: 'sqlite3', connection: ':memory:'})
> knex.raw('select 1').then(() => {})
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid1 +8s
  knex:query select 1 +1ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +5ms
> knex.raw('select 1').then(() => {})
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid1 +9s
  knex:query select 1 +0ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +1ms

> 
> knex.raw('select 1').then(() => {})
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid2 +3m
  knex:query select 1 +1ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid2 +3ms
> knex.raw('select 1').then(() => {})
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>   knex:client acquired connection from pool: __knexUid2 +3s
  knex:query select 1 +0ms
  knex:bindings [] +1ms
  knex:client releasing connection to pool: __knexUid2 +2ms
> knex.raw('select 1').then(() => {})
```

If I wait too long between selects __knexUid of connection changes...

It should be pretty easy to test and fix. I suppose setting some pool timeouts in case if pool size is 1 should be enough.

**Comment by elhigu** [comment]
This could work as a workaround which sets timeouts to 100 hours.

```js
knex = require('knex')({
  client: 'sqlite3', 
  connection: ':memory:', 
  pool: { 
    min: 1, 
    max: 1, 
    disposeTiemout: 360000*1000, 
    idleTimeoutMillis: 360000*1000 
}});
```

**Comment by parkan** [comment]
:+1: for special-casing pool size 1

**Comment by anatoliyklamerdataart** [comment]
Faced same issue but i need poo size more than 1
So my solution is to use shared memory database
`const knex = require('knex')({
  client: 'sqlite3',
  //connection: ':memory:',
  //connection: { filename: "./mydb.sqlite", },
  connection: { 
    filename: "file:memDb1?mode=memory&cache=shared", 
  },
  useNullAsDefault: true,
  pool: {
    min: 1,
    max: 10,
    disposeTimeout: 360000 * 1000,
    idleTimeoutMillis: 360000 * 1000
  }
});`

> If two or more distinct but shareable in-memory databases are needed in a single process, then the mode=memory query parameter can be used with a URI filename to create a named in-memory database:

rc = sqlite3_open("file:memdb1?mode=memory&cache=shared", &db);

**Comment by zxxc** [comment]
Faced same issue but i need pool size more than 1
So my solution is to use shared memory database
```
const knex = require('knex')({
  client: 'sqlite3',
  connection: { 
    filename: "file:memDb1?mode=memory&cache=shared", 
  },
  useNullAsDefault: true,
  pool: {
    min: 1,
    max: 10,
    disposeTimeout: 360000 * 1000,
    idleTimeoutMillis: 360000 * 1000
  }
});
```

> If two or more distinct but shareable in-memory databases are needed in a single process, then the mode=memory query parameter can be used with a URI filename to create a named in-memory database:
> rc = sqlite3_open("file:memdb1?mode=memory&cache=shared", &db);

**Comment by elhigu** [comment]
I had no idea sqlite3 supported that kind of inmemory database. Thats worderful... however when is that kind of named in memory database purged from memory? At the same moment when the process that created it exists? I suppose that works only when one has single process accessing the named in memory database (so I suppose you cannot run for example migrations in a separate process and access the same database in another).

**Comment by alexanderankin** [comment]
Which of these keys are these pool option now? I'm guessing `destroyTimeoutMillis` + `idleTimeoutMillis`?

i see your profile picture in both places @elhigu  :) so i figured wouldnt hurt to ask.

https://github.com/Vincit/tarn.js/blob/master/src/Pool.ts

**Comment by elhigu** [comment]
@alexanderankin I think with tarn you should be safe if you just setup pool.min to be >= 1

**Comment by redamsy** [comment]
> This could work as a workaround which sets timeouts to 100 hours.
> 
> ```js
> knex = require('knex')({
>   client: 'sqlite3', 
>   connection: ':memory:', 
>   pool: { 
>     min: 1, 
>     max: 1, 
>     disposeTimeout: 360000*1000, 
>     idleTimeoutMillis: 360000*1000 
> }});
> ```

this is not working for me:
Type '{ min: number; max: number; disposeTimeout: number; idleTimeoutMillis: number; }' is not assignable to type 'PoolConfig'.
  Object literal may only specify known properties, and 'disposeTimeout' does not exist in type 'PoolConfig'.ts(2322)
index.d.ts(1694, 5): The expected type comes from property 'pool' which is declared here on type 'Config<any>'

**Comment by kibertoad** [comment]
@redamsy See https://github.com/vincit/tarn.js/
I think `destroyTimeoutMillis` is the tarn.js equivalent of `disposeTimeout`

**Comment by elhigu** [comment]
also `idleTimeoutMillis` should not have any effect, because min and max is 1. That single idle connection will not be removed from pool even after that timeont.

**Comment by redamsy** [comment]
thanks everyone i figured it out
