### ISSUE TITLE
Update GitHub project description to mention Oracle

### ISSUE THREAD

**Issue by cjbj** [knex/knex#1876]
Is it time to update the [project description](https://github.com/tgriesser/knex) to mention [Oracle](https://github.com/tgriesser/knex/tree/master/src/dialects/oracledb)? Currently it just says "A query builder for PostgreSQL, MySQL and SQLite3".

**Comment by elhigu** [comment]
@tgriesser or someone else, who has enough control to change project settings is needed for this. Maybe @rhys-vdw has enough rights?

**Comment by kibertoad** [comment]
@tgriesser Can this be done? MSSQL is also missing.
