### ISSUE TITLE
Inner Join with And in the InnerJoin function

### ISSUE THREAD

**Issue by nitish24p** [knex/knex#1919]
Is it possible to execute the following using knex,
Im taking this example from a symfony , doctrine background

```php
$qb->select(
            'some values'
        )
            ->from(Table_Name, 'table1')
            ->innerJoin(
               Second Table,
                'table2',
                'WITH',
                'table1.id = table2.table_1id AND table2.softDeleted = 0'
            )
```
is there a way to have a join and a softDeleted check in the join itself in any way or knex does not support this right now? I know a at the moment a where can be added below the inner join like this

```javascript
let qb = Bookshelf.knex('table_1')
  .select()
  .innerJoin('table_2','table1.id','table_2.table_1id')
 .where('table_2.softDeleted','=',0);
```
Just feel the earlier method provides a cleaner semantic

**Comment by elhigu** [comment]
Could you add desired raw SQL output? I don't know what that first query generates.

**Comment by absolux** [comment]
@nitish24p 
```js
knex('table_1').select().innerJoin('table_2', qb => {
  qb.on('table_1.id = table2_table_1id').andOn('table_2.softDeleted = 0')
}
```
Hope it helps

**Comment by derencel20** [comment]
![image](https://user-images.githubusercontent.com/17394978/87423648-38521780-c60d-11ea-988d-c0b17124354f.png)
What if when you want something like this?

**Comment by elhigu** [comment]
Closing as It is unclear what needs to be done.

**Comment by derencel20** [comment]
What I want to know is if there's a case statement on innerjoin. What query should we use?

**Comment by elhigu** [comment]
You should not hijack threads that are about different issue and AFAIK knex does not have any special way to write case statements. So you need to use knex.raw.
