### ISSUE TITLE
Implement SKIP LOCKED

### ISSUE THREAD

**Issue by marianomerlo** [knex/knex#1937]
Since POSTGRESQL 9.5, there is an `SKIP LOCKED` option for `SELECT FOR SHARE/FOR UPDATE` that is extremely helpful.

It would be useful to support this.

Thanks

**Comment by honestserpent** [comment]
Would be really useful

**Comment by kukiric** [comment]
I'll take this one. I have already implemented the functionality for PostgreSQL with some unit + integration tests, but I'll also try to get MySQL/MariaDB support in the PR as well for completeness.

**Comment by marianomerlo** [comment]
Thank you so much for this! Closing issue since you all rock!
