### ISSUE TITLE
Migration quietly fails to create table

### ISSUE THREAD

**Issue by epoberezkin** [knex/knex#196]
Actually, it worked only once for me.
Rollback also worked.
Since then, only the record is added/removed to migrations table and nothing else happens.
No errors. -v, debug:true do not change anything - same one line message is printed.

Also when it worked the first time, no indexes apart from primary were created.
What can I be doing wrong?

I am using MySQL.
Update: dropping database didn't help...

**Comment by mpuncel** [comment]
I'm using knex for the first time tonight, and I ran into this same issue. It wasn't obvious that I need to return a promise from the docs at http://knexjs.org/#Migrations. Luckily this issue was a quick google search away!
