### ISSUE TITLE
Query comment

### ISSUE THREAD

**Issue by bernardmo** [knex/knex#1982]
Hello,

Is there a way to add _sql comment_ to select query without using _raw queries_? I tried to look for docs on http://knexjs.org/ but can see comment support only for table manipulation. 

Query comments are useful for routing hints on maxscale router (https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale-14/maxscale-hint-syntax/).

**Comment by VMBindraban** [comment]
I also would like to see this as a feature.

**Comment by rfink** [comment]
Also support

**Comment by kibertoad** [comment]
@rfink Typically it's better to use emoticons on original request to voice support for the feature rather than making "+1" comments, as these spam everyone subscribed to the issue.

**Comment by rfink** [comment]
First attempt at adding this: https://github.com/tgriesser/knex/pull/2815

**Comment by elhigu** [comment]
Which databases actually supports this?

**Comment by elhigu** [comment]
> you are referring to query routing by comments

I'm referring any kind of comment with the query. I understand it is really useful for that proxy.

**Comment by bernardmo** [comment]
> I'm referring any kind of comment with the query. I understand it is really useful for that proxy.

Well I know that mysql/mariadb, postgresql and sqlite support query comments. I'm not sure for other DBs which are supported by knex (I didn't worked with them)

**Comment by elhigu** [comment]
Yea, looks like `/* comment */` are standard SQL stuff, I had always seen just line comments earlier :) Other thing to check about this is to see if Node's DB drivers supports them.

**Comment by KristjanTammekivi** [comment]
Can confirm that PG supports them. We've hacked the client & querybuilder prototypes so that you can specify a comment with .options(). Works nicely but a proper support would be nicer.

**Comment by kibertoad** [comment]
@KristjanTammekivi Maybe you would be interested in finishing https://github.com/tgriesser/knex/pull/2815?

**Comment by lindakung** [comment]
Very excited to use this feature. Is there an ETA for when it might be released? Thanks!

**Comment by GeneBuchite** [comment]
I am still deciding on which tools to use. I might not even use Vercel. Right now I am working on the backend.
Thank you for your interest

**Comment by OlivierCavadenti** [comment]
Released in [2.5.0](https://github.com/knex/knex/releases/tag/2.5.0)
