### ISSUE TITLE
How do I use knex with a pre-existing mysql connection pool?

### ISSUE THREAD

**Issue by Twipped** [knex/knex#201]
I'm interested in trying out knex and bookshelf in our application, but we already have a node-mysql connection pool and I don't want to have two pools running in the same application. I don't see a way to pass in a premade mysql pool on the connection settings.  Is it there and I'm just not seeing it?

**Comment by spathon** [comment]
Hi @tgriesser 
Is there any official way now?

**Comment by egarcia777** [comment]
Hi @tgriesser is there something for postgresql existing connection? I'am using PG module

**Comment by nabilnathani10** [comment]
hi is there an official way to do this in version 0.12.6?

**Comment by elhigu** [comment]
@spathon @nabilnathani10 no

**Comment by nabilnathani10** [comment]
what is the best way to do this in 0.12.6 using postgres

**Comment by thomasdavis** [comment]
Any updates on this one? (postgres)

**Comment by malykhin** [comment]
You can try this:

```javascript
const knex = require('knex')
const PgClient = require('knex/lib/dialects/postgres')

class CustomPg extends PgClient {
  constructor(config) {
    super({ client: 'pg' })
    this.pool = config.pool
  }

  acquireConnection() {
    return this.pool.connect()
  }

  releaseConnection(connection) {
    return connection.release()
  }

  initializePool() {}
}

const initKnex = (pool) => knex({ client: CustomPg, pool })

db.getPool().then((pool) => {
  const knex = initKnex(pool)
  knex
    .select('*')
    .from('table')
    .then(console.log)
})
```

**Comment by elhigu** [comment]
in 0.16.1 there will be https://knexjs.org/#Builder-connection which can be used to explicitly give connection to the query builder, where to send the query.
