### ISSUE TITLE
Named constraints

### ISSUE THREAD

**Issue by carragom** [knex/knex#2051]
Hi there,

According to the [docs](http://knexjs.org/#Schema-primary), it possible to name you `primary key` and hopefully your `unique` and `foreign key`. But this does not seem to be true at least for **Sqlite**. Is this just lacking on the SQLite implementation?. I could work on a PR to allow this in SQLite.

**Comment by elhigu** [comment]
It should be supported. If the sqlite implementation is missing, PR would be really welcome!

**Comment by carragom** [comment]
Hi,

I'm working on a PR for this but would like to clarify something first. What should be the correct API for naming keys and indexes?. This is how I think the API works

# Indexes
## Fluent API
Only single column indexes can be created like this and the index name is optional. The next example will add the column `colA` to the table and an index named `optional-name`
```
table.string('colA').index('optional-name');
```
## Normal API
### Single column
Single column indexes can be created and the name is optional like the next example that will add an index named `optional-name` with one column `colA`
```
table.index('colA', 'optional-name')
```
### Multiple columns
Multi-column indexes are allowed and the name is optional but if multiple columns are needed **they must be specified in an array as the first parameter** like the next example that will add an index named `optional-name` with two columns `colA` and `colB`
```
table.index(['colA', 'colB'], 'optional-name')
```
Assuming the previous is correct, I think I can do the same for `primary` and `unique` indexes in SQLite. Waiting for your comments to proceed with the PR.
