### ISSUE TITLE
postgresql extensions using knexjs

### ISSUE THREAD

**Issue by ghost** [knex/knex#208]
i'd like to use postgresql extension using the command "create extension <extn-name>" Has anybody tried this with knex? I need this to be able to programmatically create tables. Thanks
-sr

**Comment by moudy** [comment]
@bendrucker once the extension is enabled, where point does the `uuid_generate_v4()` function get called?

**Comment by austingray** [comment]
@moudy Was just looking up this same thing, I'm assuming he's just running it like so: `table.uuid("uuid").defaultTo(knex.raw('uuid_generate_v4()'))`

**Comment by Burtonium** [comment]
I get the following error when I do this

`error: CREATE EXTENSION IF NOT EXISTS "uuid-ossp" - could not open extension control file "/usr/share/postgresql/9.3/extension/uuid-ossp.control": No such file or directory`

Anyone know why?

**Comment by trueillum** [comment]
You need to install `sudo yum install postgresql93-contrib` to get things working

**Comment by JefferyHus** [comment]
If anyone is still running in this problem please use this solution
```javascript
knex.schema.raw('CREATE EXTENSION IF NOT EXISTS "your_extension"')
.createTable('table_name', function (table) {
  // create your table
})```

**Comment by JefferyHus** [comment]
> Sure — I use uuids as the primary key in my APIs. So my first migration looks like this:
> 
> ```js
> exports.up = function (knex, Promise) {
>   return knex.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
>     .then(function () {
>       // set up tables
>     });
> };
> ```
> 
> `knex.raw` returns a thenable so you can use it like any other query. Probably makes sense to use it in migrations but you can use it anywhere you'd like.

Somehow the `knex.raw()` didn't work and throws no error so I had to write the solution above that works for me.

**Comment by madoBaker** [comment]
> If anyone is still running in this problem please use this solution
> 
> ```js
> knex.schema.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
> .createTable('table_name', function (table) {
>   table.uuid('id').primary().notNullable().defaultTo(knex.raw('uuid_generate_v4()'))
>   // continue your creation...
> })
> ```

This actually doesnt work, it ends up trying to set `uuid_generate_v4()` as a string not calling the extension with that name.

It would pass table creation stage but would throw error trying to insert any document
