### ISSUE TITLE
migrate tool

### ISSUE THREAD

**Issue by eshell** [knex/knex#218]
I was just trying to use the migration tool for the first time. I started running into trouble when adding foreign keys while trying to set up my database the first time. 

How would I run foreign_key_checks=0 before each migration? I think this should be in the docs.

In order to get everything running successfully, I had to first create migrations without FKs and then create a new migration for each table to add them. I don't feel this is a good way to do migrations.

Do you have to create a separate migration for each table in the database? If so it's not a big deal. Probably better that way.

ps: this is my first attempt ever at doing migrations without directly working in mysql.

**Comment by armenr** [comment]
Any way to apply this to the seed file? 

I can't seem to insert seed data when I migrate a schema that has foreign key relations. Any way to address this?

**Comment by jcrawford** [comment]
Same here, I cannot seem to get the seed to work due to FK constraints.
