### ISSUE TITLE
Specifying multiple directories for seeds

### ISSUE THREAD

**Issue by GodefroyClair** [knex/knex#2193]
For categorical variables tables that serves as foreign key in other table (e.g. a "user_types" table with "admin", "employee", "visitor" categories that serves as foreign key in a "user" table), I feel there is something missing in the way it is done today with the migration/seeding process.
You have two possibilities:
- either you do the insert in the migrations but it could be considered as a mispractice (and you get a warning at each migration: "Transaction was implicitly committed, do not mix transactions and DDL with MySQL"),
- or you insert during the seeding process but then you have to copy the same seeding file in all your different environments (in the seed directory of your test, development & production env) but that a bad practice for sure...

A solution would be to be able to include multiple directories for the seeds parameter in our knexfile? We could then provide a common directory for all the seeding of "fixed" categorical variables and another one for the seeding related to the particular env:
 
```
 ,development: {
    ...
    ,seeds: {
      directory: [__dirname + "/db/seeds/common_seeding", 
                        __dirname + "/db/seeds/development"
                      ]
    }
  }
```
Tell me if you think this could be a good idea or if anything else exist to solve the pb.
Thx !

PS: this could actually help in even more cases - anytime there is a need for both common and particular seedings in the different environments...

**Comment by elhigu** [comment]
Could it work to just do schema modifying DDL operations and migrations that inserts stuff in separate migration files? Its common problem in many databases that scema changes actually do implicit commit and they cannot be done in transaction properly.

**Comment by stephenhuh** [comment]
I'm having a similar issue, where I'd specifically like certain seed files to be shared across environments. @elhigu I've seen you post before about specifically putting in seed data into migrations. Is this the approach you recommend when using knex?  i.e. treating DDLs + (data that always exists for processing) together in migrations.

**Comment by kibertoad** [comment]
@stephenhuh This is correct. Recommended approach for data that you only seed once is to put it into migrations. If you want to do it in a clean way, it is recommended to put them in separate folders (e. g. /db/seeds and /db/migrations) and specify multiple migration directories for the Migrator (supported in 0.16.x+)

**Comment by kibertoad** [comment]
@GodefroyClair I think this is a good idea, we already support that for migrations, I don't see why we couldn't support that for seeds as well.

**Comment by candyapplecorn** [comment]
### As a developer writing and running tests I want the option to run seed files from multiple directories

e.g. With a directory like so:

![image](https://user-images.githubusercontent.com/5856981/60466816-93cf8400-9c09-11e9-9e9e-eb1ca0b8808f.png)

I should be able to pass this list of paths to `directory`:

`
directory: ["seeds/development", "seeds/production"],
`

The seeds should be executed in alphabetical order; for this example, `01_seed_employee`, `02_seed_employee_data` and then `03_seed_manager`.


## Acceptance Criteria:
* Modify the knex config's seed's "directory" option such that it may take a list of paths
* The seeds should still be run in alphabetical order, as the current _npx knex seed:run_ does

**Comment by candyapplecorn** [comment]
@kibertoad Can you tell me if anyone is currently working on this feature? I don't know if this Knex project has a Kanban board (or other tool) listening who's actively working on what.

**Comment by kibertoad** [comment]
@candyapplecorn Unfortunately, we are not that well-organized, nor there is constant development time budget for anyone on this team 😂. If anyone would volunteer to pick up this feature, that would be grand!

**Comment by candyapplecorn** [comment]
@kibertoad Thanks for your quick response. I am trying to find out if anyone else is working on this, because if they were, it'd be a waste of _my_ time to pick it up. Duplicate work = **sad!** If nobody is working on it I'd like to find some time to do it.

**Comment by kibertoad** [comment]
Yay!

**Comment by elhigu** [comment]
Yep, usually me or kibertoad knows if some feature is being worked on by someone, since people tend to tell about their efforts in these issues and at least I read all of them :) And there are not so many people working on stuff so its really easy to keep track.

**Comment by candyapplecorn** [comment]
I'd like to change the feature request a little bit. Originally I thought it'd be good if we just took all the seed files from all the directories, put them into a flattened list, sorted them alphabetically (how knex seed currently works?) and then ran them. However after speaking with my coworker we think it makes to execute all the seed files in one directory (in alphabetical order) before moving on to the next directory. 

Given my screenshot of a directory tree from above, the old execution order from my idea of globbing them all together would be 01, 02 and 03. With this new per-directory behavior, if the list of directories provided was ["...production...", "...development..."] then ALL the files in production would be run, and _then_ all the files in development. This would result in an order of 01, 03, 02 (using my examples above). This also means that the order of directories provided to the directory option matters; the 1st file path (directory) gets executed before the 2nd file path, and so on.

Would like to double-check with you guys to see if you agree that this is sensible behavior.

**Comment by kibertoad** [comment]
@candyapplecorn There's definitely an opportunity for improvement :).
However, note that knexfile already supports multiple environments:
```
module.exports = {
  development: {
    client: 'pg',
    connection: { user: 'me', database: 'my_app' }
  },
  production: { client: 'pg', connection: process.env.DATABASE_URL }
};
```
You can probably use that to achieve what you are trying to do already. If you want something more flexible, might make sense to discuss it upfront. If I understand correctly your original proposal, idea is to pass array of strings, and then parse directory names to figure out which one to run based on environment? Not sure that provides significant benefits over parametrized knexfile, especially since you can actually write conditional JS logic inside of it.

**Comment by kibertoad** [comment]
@candyapplecorn Ah, so the idea is to move control over which directories to run over to whoever is doing the call, so that you can build array conditionally before calling seed API? Yeah, that definitely makes sense.
I would suggest to do it in a way that would be consistent with how migrations handle multiple directories - by default all seeds from all directories are sorted among themselves alphabetically and executed regardless of their directory, but you can set option `sortDirsSeparately` to true, and that would sort them within their folder and execute folders alphabetically.

**Comment by candyapplecorn** [comment]
@kibertoad 

If receiving a list of strings (paths to directories full of seed files), execute **all** the files in **all** the directories.

So my test environment's knex config would pass a list of directories to the directory option, whereas my production environment's knex config would only pass a single directory

I want the ability to run all of the seed files for our "production" environment, and _then_ run some more seed files just for our "test" environment.

**Comment by kibertoad** [comment]
Yup, makes sense! And just to clarify why seemingly less convenient behaviour is the default one - it allows more seamless transition for existing seeds/migrations: one might split them across multiple directories however he likes without being forced to rename anything to avoid disrupting original sequence of execution. This, admittedly, is more important for migrations than seeds (as you really don't want to rename migrations after they were executed, while you don't care about previously executed seeds), but consistency for similar features results in less suprises for users :).

**Comment by candyapplecorn** [comment]
Pull request is up: https://github.com/tgriesser/knex/pull/3357

**Comment by mdartic** [comment]
Seems related to #3786 ?

**Comment by candyapplecorn** [comment]
Forgot to update. I abandoned working on my PR #3357 after a few days. I got all the tests to pass and when I went to test it with the command line, it completely broke. I'm not planning on working on it again so thanks @mdartic

**Comment by mdartic** [comment]
The MR https://github.com/knex/knex/pull/3967 is merged.
Don't know if it's enough for closing this issue @GodefroyClair ?

**Comment by GodefroyClair** [comment]
yes I think so. Thx!
