### ISSUE TITLE
Latest version broke postgres array operations

### ISSUE THREAD

**Issue by ericeslinger** [knex/knex#226]
I used to be able to do a `.where{'array_col', '&&', array_vals}`-style query. This is no longer the case.

**Comment by chrisjhoughton** [comment]
Sorry to bring this up here, but I haven't found another related thread.

When I run:

```js
query.where('tags', '&&', value);
```

It translates to the following query:

```
select from "users" 
where "client" = '55773883aaf6b3df7996dc89' 
and "tags" && '{\"volusion\",\"sauce-facebook\",\"wholesale\"}') 
```

The tags in the `value` are getting escaped, which is causing the Postgres array overlap query not to work. Am I doing something silly? 

Many thanks!
