### ISSUE TITLE
transactions with knex.raw

### ISSUE THREAD

**Issue by colmaengus** [knex/knex#232]
Hi,

I'm implementing a schema patch mechanism where each schema patch is wrapped in a transaction.
My problem is that some schema patches might require knex.raw and I can't figure out how to perform these commands inside the transaction created by knex.transaction

Regards

Colm A

**Comment by Znarkus** [comment]
There is no reference to `raw` on #148. How do you use raw() with a transaction?

**Comment by tgriesser** [comment]
@Znarkus Just do:

```js
knex.transaction(trx => {
  trx.raw(...)
})
```

**Comment by Znarkus** [comment]
Thank you! I tried `knex.transacting(options.transacting).raw()` which didn't work.
Final solution:
```
(options.transacting || knex).raw()
```
