### ISSUE TITLE
truncate with options

### ISSUE THREAD

**Issue by eav** [knex/knex#237]
I need to execute the following sql in pg: TRUNCATE tableName CASCADE;

I tried knex('tableName').options('CASCADE').truncate() but it generates: 'truncate "tableName" restart identity'

I know there is also raw method but I don't find it useful for this use case, is it possible to do somehow?

**Comment by jdrake** [comment]
@eav what was your solution?

**Comment by eav** [comment]
knex.raw('TRUNCATE account CASCADE');
