### ISSUE TITLE
Heroku PostgreSQL connection problem

### ISSUE THREAD

**Issue by tybenz** [knex/knex#239]
Trying to do something similar to #47 (connect to postgres database on heroku). I tried to set up my connection config with the host, user, password, and database name from the $DATABASE_URL environment variable.

I've tried both the EC2 url and the IP address as the host.

When I set up the model node and call save, the record should be saved to the database. When I connect to `psql` via `heroku pg` and query the users table it's empty.

The example uses Bookshelf. Let me know if I should file the issue under that repo. Although my understanding is that the connection config just gets passed to Knex.

``` js
var Bookshelf = require( 'bookshelf' );

Bookshelf.PG = Bookshelf.initialize({
  client: 'pg',
  debug: true,
  connection: {
    host     : process.env.PG_HOST || 'localhost',
    user     : process.env.PG_USER || 'postgres',
    password : process.env.PG_PASSWORD || 'postgres',
    database : process.env.PG_DB || 'db',
    charset  : 'utf8'
  }
});

var User = Bookshelf.PG.Model.extend({
  tableName: 'users',
  idAttribute: 'id'
});

var u = User.forge({email: 'test@fake.com', password: 'test'});
u.save();
```

**Comment by liamhession** [comment]
If anyone like me ends up here, if you're using `connection` and a full `postgres://user:pass@host...` to specify where to connect to, and are throwing `sslmode=require` and/or `ssl=true` onto the end and it's not working: you have to split the connection string into its components, so that your connection configuration object has `host: 'host'` etc. and then the `sslmode: 'require'` option will work

**Comment by liamhession** [comment]
And also it was necessary to set `PGSSLMODE=require` in the environment where the knex connection was started

**Comment by olso** [comment]
```ts
import knex, { Config } from "knex";
// @ts-ignore
import knexStringcase from "knex-stringcase";

import { db, isDev } from "../config";

const config = knexStringcase({
  debug: isDev,
  client: "pg",
  connection: {
    connectionString: db,
    ssl: {
      rejectUnauthorized: false,
    },
  },
  searchPath: ["public"],
  // pool: isDev ? { max: 4 } : { min: 4 },
  asyncStackTraces: true,
} as Config) as Config;

export default knex(config);
```
