### ISSUE TITLE
Foreign Key

### ISSUE THREAD

**Issue by firmstepgit** [knex/knex#24]
Thanks for a really nicely implemented project. Annotated source code is always a deity-send. I have a few questions:

Is there a way to create foreign keys to other tables? The source code has a function `foreign` with the comment "Specify a foreign key for the table." within the `SchemaBuilder`, but there doesn't seem to be a way to specify a table and column for the foreign key, and the documentation doesn't mention anything.

Is there a way to specify that two or more columns must be unique together?

Is there a way to define indexes on non-integer columns?

Thanks!

**Comment by alextaujenis** [comment]
This is now officially documented here: http://bookshelfjs.org/#Associations
