### ISSUE TITLE
Dropping MSSQL column with default constraint does not work

### ISSUE THREAD

**Issue by zswanson17** [knex/knex#2492]
# Environment

Knex version: 0.14.4
Database + version: MSSQL

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When attempting to drop a column (via a migration) with a MSSQL db, an error is returned.  After digging into this, the error is that the column cannot be dropped because it has a default constraint.  The default constraint has to be dropped first, which does not seem to be currently supported.

2. Error message (in Node.js): TransactionError: Transaction has been aborted.

When running the generated SQL (ALTER TABLE [Accounts] DROP COLUMN [IsAccountDisabled]) manually in SQL server, this error is shown:

Msg 5074, Level 16, State 1, Line 12
The object 'DF__Accounts__IsAcco__56E8E7AB' is dependent on column 'IsAccountDisabled'.
Msg 4922, Level 16, State 9, Line 12
ALTER TABLE DROP COLUMN IsAccountDisabled failed because one or more objects access this column

Here is the migration raising the error (fails when running the rollback; default constraint created in up migration):

const TABLE_NAME = 'Accounts';
const COLUMN_NAME = 'IsAccountDisabled';

exports.up = function(knex, Promise) {
    return knex.schema.alterTable(TABLE_NAME, t => {
        t.boolean(COLUMN_NAME).notNullable().default(false);
      });
};

exports.down = function(knex, Promise) {
    return knex.schema.hasColumn(TABLE_NAME, COLUMN_NAME).then(exists => {
        console.log(`Exists: ${exists}`);
    
        if (exists) {
            return knex.schema.table(TABLE_NAME, t => {
              t.dropColumn(COLUMN_NAME);
            });
        } else {
          return;
        }
      })
};

**Comment by nycoag92** [comment]
Any update for this?

**Comment by tetsupanda** [comment]
My fix works, however I just haven't gotten around to fixing the test cases for this. I just added my own custom dropColumn function in our data layer repo, with the code I wrote in the linked PR. 

One day I'll address the testing aspect of this.

**Comment by wsjwa** [comment]
Any chance this will be fixed?

**Comment by wsjwa** [comment]
Is there a workaround for this bug?

**Comment by elhigu** [comment]
@wsjwa Yep, there are workarounds. Drop the constraint first and then drop the column. Also with knex.schema.raw you can run any query you like during the migrations, so you can always use it to get anything done that is not supported by knex directly.
