### ISSUE TITLE
How to do multiple inserts

### ISSUE THREAD

**Issue by luiscvega** [knex/knex#251]
This is kind of a noob question, I'm used to using ORMs and decided to go closer to the metal with Knex.

I'm trying to do multiple inserts where the 2nd insert relies on the `id` of the 1st insert.

Something like this:

``` javascript
    knex("users")
        .insert({ first_name: "John", last_name: "Doe" })
        .exec(function (err, id) {
            knex("groups")
                .insert({ name: "Cool Group" })
                .exec(function (err, id) {
                    // handle results
                });
        });
```

I might be missing something by not knowing how to use Promises or Transactions properly, but I'd appreciate some help on this very simple problem.

Thanks!

**Comment by mouhannad-sh** [comment]
For anyone on the internet who comes across this issue like I did

you can read this [SO](https://stackoverflow.com/questions/35089571/knex-js-create-table-and-insert-data) answer.

Basically in your `up` or `down` handler you need to return a `promise` so technically you could do something like:

```javascript
exports.up = function(knex) {
  const columns = ['column_1', 'column_2', 'column_3'];
  const tables = ['table_1', 'table_2'];
  return Promise.all(
    tables
      .map(table =>
        columns.map(col =>
          knex(table)
            .where(col, '=', 'Wrong value')
            .update({ [col]: 'Corrected value' })
        )
      )
      .flat()
  );
};
```
