### ISSUE TITLE
how easy is it to extend knex via a plugin?

### ISSUE THREAD

**Issue by cultofmetatron** [knex/knex#254]
I need to be able to extend some of our existing infrastructure to support geospatial queries. We're migrating over to postgresql to do so. That said, we've already switched over to using knex. since knex itself doesnt support postgis, we are making our mvp using knex.raw. Eventually I would like to add the functionality into knex. However, since its a very potsgres specific feature, I was wondering how easy it is to extend knex with plugins so that it could be maintained separately.

**Comment by mnpenner** [comment]
If I want to extend the query builder, should I be adding on to `Knex.Client.prototype.QueryBuilder.prototype` or `Knex.Client.fn` or what?

**Comment by mnpenner** [comment]
It's getting tedious to define everything twice,

```js
Object.assign(Knex.Client.prototype.QueryBuilder.prototype, {
    whereJoin: function(col1, col2) {
        return this.where(col1, this.id(col2));
    },
    whereContains: function(column, term) {
        return this.where(column,'like',`%${escapeLike(term)}%`);
    },
    orWhereContains: function(column, term) {
        return this.orWhere(column,'like',`%${escapeLike(term)}%`);
    },
    whereStartsWith: function(column, term) {
        return this.where(column,'like',`${escapeLike(term)}%`);
    },
    orWhereStartsWith: function(column, term) {
        return this.orWhere(column,'like',`${escapeLike(term)}%`);
    },
    whereEndsWith: function(column, term) {
        return this.where(column,'like',`%${escapeLike(term)}`);
    },
    orWhereEndsWith: function(column, term) {
        return this.orWhere(column,'like',`%${escapeLike(term)}`);
    },
});
```

Is there a way to extend Knex properly or no?

**Comment by fennecbutt** [comment]
We've used knex extensively in our project and are very grateful for it, but as far as I know there's no way to extend knex "properly" yet. We've been using the same method you are to extend knex up to this point, but we're looking to add proper plugins/extensions somehow for our project, so I will PR it if we come up with something that might be useful to others.

**Comment by mnpenner** [comment]
@fennecbutt That would be great. Knex is still the best ORM I've found, but its lack of extensibility makes it difficult for me to write the kinds of queries I'd like.

**Comment by rickyk586** [comment]
Here's how I was able to monkey patch it for v0.12.7

```javascript
var Knex = require('Knex');
var KnexQueryBuilder = require('knex/lib/query/builder');

var knexClient = Knex(config);

KnexQueryBuilder.prototype.newMethod = function(){
	console.log('in new method');
	return this;
};
knexClient.queryBuilder = function(){
	return new KnexQueryBuilder(knexClient.client);
};
```

**Comment by andremsantos** [comment]
Thanks @rickyk586 , your example helped me add pagination to knex. Cheers!

**Comment by Islomkhodja** [comment]
gap yo lekin

**Comment by elhigu** [comment]
There is now kind of official way to extend query builder. Docs are just after this chapter https://knexjs.org/#Builder-queryContext

**Comment by KarmaBlackshaw** [comment]
Hi! I've trying to extend a function but it seems that `raw` is not a function.

**Comment by elhigu** [comment]
@KarmaBlackshaw please open a bug report with reproduction code if that seems to be a bug.
