### ISSUE TITLE
Question around a simple join...

### ISSUE THREAD

**Issue by srmelody** [knex/knex#260]
Hi there,

I'm sure this is something simple that I'm missing as I was able to get Bookshelf to perform the join and nest the data correctly.  I have two tables, p and c.  c has a foreign key to p.  

CREATE TABLE c
(
  name text,
  id uuid NOT NULL,
  p_id uuid,
  CONSTRAINT uid PRIMARY KEY (id),
  CONSTRAINT "pFK" FOREIGN KEY (p_id)
      REFERENCES p (uid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE p
(
  id uuid NOT NULL,
  name text,
  description text,
  CONSTRAINT pk_p PRIMARY KEY (id)
)
pg is an initialized knex connection to postgres.  This line will give me all of my c's.
  new pg('c').select().then( callback )
but when I to join to p, I end up getting the p's and the c's p_id.
  new pg('c').join('p', 'c.p_id', '=', 'p.id').select().then( callback )

[

```
{
    "name": "changed to new p",
    "id": "34a73090-cfd6-11e3-9c1a-0800200c9a66",
    "p_id": "34a73090-cfd6-11e3-9c1a-0800200c9a66",
    "description": "this is a test p in postgres"
},
{
    "name": "another p",
    "id": "34a73090-cfd6-11e3-9c1a-0800200c9a67",
    "p_id": "34a73090-cfd6-11e3-9c1a-0800200c9a67",
    "description": "second p from postgres"
}
```

]
I would expect to get all of the p's under each c to appear as an array.

**Comment by mercmobily** [comment]
Hi there!

Knex is a SQL query builder, not an ORM. It deliberately does not transform flat SQL result sets into nested objects. This is a design decision that will not change.

As stated by maintainer @tgriesser in https://github.com/knex/knex/issues/61#issuecomment-61946622: "this is a limitation of sql... and not something knex will try to handle for you provide out of the box".

For detailed solutions (using ORMs like Objection.js, database-specific JSON functions, manual transformation, or separate queries), please see the master documentation issue: #6289

This issue will be closed as a duplicate of #6289.
