### ISSUE TITLE
Rolling back a transaction without an error

### ISSUE THREAD

**Issue by trustmaster** [knex/knex#263]
I'm using `transacting` with knex and I want to rollback the transaction during normal execution. But whenever `transaction.rollback()` is called it throws an unhandled exception. Providing a custom error object and trying to catch it doesn't help since it is inside a callback.

Is there a way to rollback a transaction without throwing an error? Or is there a way to handle that error without littering the output?

Sample code:

``` js
// some previous inserts using `trans` done by now
db('actions')
.transacting(trans)
.select()
.where('id', data)
.then(function(rows) {
  // do some stuff with rows
  // we don't need the data anymore and want to roll back the transaction
  trans.rollback();
});
```

**Comment by marshals** [comment]
This may not be the correct place for this question as it pertains to bookshelf.  But...should an approach similar to this work for a bookshelf transaction?  I want to set up a transaction in a global beforeEach, then refer to it later in a test.  `ClassName.forge(id: 1, description: 'Test1').save(null, { method: 'insert', transacting: global.trans })`.  With this I get a "Invalid transaction object provided" error.

**Comment by bendrucker** [comment]
Please open a new issue with a more detailed code example

**Comment by aj0strow** [comment]
It's actually really hard to get unit tests with rollback working. I expected this to work:

```js
beforeEach(function () {
  this.tx = knex.transaction()
})

afterEach(function () {
  this.tx.rollback()
})
```

What i actually had to do was ..

#### Prevent connection pooling

```js
var knex = require("knex")

var config = {
  client: "pg",
  connection: process.env["DATABASE_URL"]
}

var env = process.env["NODE_ENV"]

if (env == "test") {
  config.pool = {
    min: 1,
    max: 1,
  }
}

module.exports = knex(config)
```

#### Raw transaction in tests

```js
beforeEach(function () {
  return knex.raw("BEGIN")
})

afterEach(function () {
  return knex.raw("ROLLBACK")
})

it("should do whatever", function () {
  var tx = knex
  return CallAction(tx, { options: true })
  .then(function (result) {
    assert(result)
  })
})
```

**Comment by aj0strow** [comment]
The reason you can't just call `tx.rollback()` and then catch, is you swallow `assert` errors. Otherwise you have to do a fancy error handling match on assert errors vs pg errors.

It's not very straight-forward. Hopefully the above helps people who find this.

**Comment by rapodaca** [comment]
@aj0strow's suggestion worked for me on mysql using knex 0.14.6.

**Comment by elhigu** [comment]
@rapodaca rolling back changes like that is really limited way to do testing and prevent you from testing many real world use-cases. Of course some specific cases that approach is legit. Just for your information :)

**Comment by rapodaca** [comment]
@elhigu, I think you're right.

Not 10 minutes later I discovered that a transaction performed within code under test (a nested transaction) was committed, leaving the database with stray data.

The following avoids that problem:

    let db = knex(config);
    let tx;

    beforeEach(function (done) {
      return db.transaction((t) => {
        tx = t;
        done();
      }).catch((error) => { });
    });

    afterEach(function () {
      tx.rollback('cleaning up');
    });

    it('does something', function () {
      return expect(tx.insert({
        foo: 'foo',
        bar: 'bar'
      }).into('foo')).not.to.be.rejected;
    });

**Comment by elhigu** [comment]
@rapodaca that way has pretty much all the same limitations. My point was that generally one should not limit test setup to be able to use only single db connection and single transaction. 

ps. I've explained that in quite many times during last few years in different places in much greater detail and explained also better ways for resetting test data after each test case. I'll write blog post or something about it to be able to always refer that later on 😅

**Comment by tristangbn** [comment]
@elhigu did you manage to write a blog post somewhere where you would give more info / examples on how to better reset test data ? I am curious to see how we can manage this without transactions
