### ISSUE TITLE
`dropForeign` throw error: `Error: Method implemented in the dialect driver`

### ISSUE THREAD

**Issue by Jeff-Tian** [knex/knex#2753]
# Environment

Knex version:   Knex CLI version:  0.15.0, Local Knex version:  0.14.6
Database + version:  Sqlite3, 3.1.13
OS: Windows 10 

# Bug

1. After done with the command `knex migrate:make <a table>`, I wrote code similar to the following:
```
exports.up = function (knex, Promise) {
    return knex.schema.table('tablename', table => {
        table.bigInteger('by').unsigned()

        table.foreign('by').references('users.user_id').onDelete('CASCADE').onUpdate('CASCADE')
    })
};

exports.down = function (knex, Promise) {
    return knex.schema.table('tablename', table => {
        table.dropForeign('by')

        table.dropColumn('by')
    })
};
```
The `up` method works as expected, but the `down` method fails. It should drop foreign key.

2. Error message
```
 Error: Method implemented in the dialect driver
```

3. The minimal testing code would be like as: https://runkit.com/jeff-tian/5b680f5ca7eeb20012b1b5d5
```
require('sqlite3');
const Knex = require('knex');

const knexSqlite = Knex({
  client: 'sqlite',
  connection: ':memory:',
});

(async function run() {
  await knexSqlite.schema.createTable('test', (t) => {
    t.increments('id').primary();
    t.string('data');
  });

    await knexSqlite.schema.createTable('test2', t => {
        t.bigInteger('testId')
        
        t.foreign('testId').references('test.id')
    });
    
    await knexSqlite.schema.table('test2', t=>{
        t.dropForeign('testId');
    });
})();
```

**Comment by morungos** [comment]
I'm facing this problem too, and it's a bit of a blocker, because it's necessary. 

For example, here's part of one of my migrations:

      return knex.schema.table('messages', function (table) {
        table.dropColumn('user_id');
      });

If `user_id` is a foreign key, in SQLite, you get:

    CREATE TABLE `messages` (
      `id` integer not null primary key autoincrement, 
      `time` bigint not null, ...
      foreign key() references `users`(`id`)) - SQLITE_ERROR: near ")": syntax error

In effect, the column is dropped, but the foreign key still exists refers to it. I'd add `dropForeign`, except that this breaks that too. I'm not sure there's a simple workaround because of all the special magic. 

Of course, I'm only using SQLite in testing. 

Maybe dropping a column should automagically drop foreign keys using it.

**Comment by morungos** [comment]
OMG, my memory: I'd already reported this exact issue in 2017: https://github.com/knex/knex/issues/1598#issuecomment-304703644

**Comment by morungos** [comment]
And there's a change in 20bd04b59 which might even address the problem, but it's not made it to an npm release yet.

**Comment by Kupstas** [comment]
Any news?

**Comment by rijkvanzanten** [comment]
@Kupstas I'm trying to pick this up as a PR, waiting for some info from Knex's maintainers, keep an eye on #1598
