### ISSUE TITLE
Plugin support? Would like to add caching and batching

### ISSUE THREAD

**Issue by cvburgess** [knex/knex#2787]
# Environment

Knex version: 0.15.2
Database + version: Postgres 9.6
OS: Mac OS X

# Feature discussion / request

1. Explain what is your use case

In building a GraphQL server there are a lot of duplicate requests to the database, I would like to reduce those without changing the developer experience.

2. Explain what kind of feature would support this

Extending Knex with plugins or first-party batching and caching support would do the trick.

3. Give some API proposal, how the feature should work

I think there are a _lot_ of ways this could be done and I would be thrilled with any of them. The first one that comes to mind is something like this:

Add a key/value store and enable/disable batching when creating an instance of Knex:

```js
Knex({
  client: "pg",
  connection: { ... },
  cache: new InMemoryLRUCache(),
  batch: true
});
```
You could go as far as to allow enabling or disabling on an individual request:

```js
return knex
  .select()
  .from("things")
  .where({ id })
  .cache(false)
  .batch(false);
```

# Reference implementation

Here's how I've hacked it together for now ( using the DataSources pattern from Apollo Server 2.0 ): 

Caching only: https://gist.github.com/cvburgess/a47910d095b8f26872fc7c77535e6e03
Caching and Batching: https://gist.github.com/cvburgess/1f9c26df3f3d4615abf46f8d42a8ef6e

This approach is based on other strategies I've seen here in the issues and is not the best, but it allowed me to get the job done for now.

**Comment by elhigu** [comment]
IMO this kind of functionality is too opinionated and should not be implemented in knex. 

It is really hard to implement and test properly and probably will create big burden for maintainers and tons of bug reports and additional feature requests when cache is not working for people in a way they would like it to behave.

If you have repetitive queries, those results should be cached outside or you might like to use for example objection or some other ORM which has better support for hooks for implementing it.

One thing that could be added in knex level would be to add some hooks, which would make it easier to implement outside of knex.

**Comment by taybin** [comment]
@cvburgess Just wanted to make sure that you're using https://github.com/facebook/dataloader, if you're having N+1 query issues.  Otherwise, I'm curious about how graphql is adding more duplicate queries than a different request protocol (REST or whatever).

**Comment by cvburgess** [comment]
@elhigu Sorry, I was trying to be as open as possible but I may have missed the mark. This does not need to be a core feature of Knex but it would be nice if there were hooks so i could do this without overwriting the internals as I am currently doing. Hooks or a plugin system would allow for extending Knex without adding to the core. I would love to see some ability to extend Knex!

@taybin [my example](https://gist.github.com/cvburgess/1f9c26df3f3d4615abf46f8d42a8ef6e) actually does use dataloader under the hood. I ccould move the logic outside of Knex but then it changes the code pretty significantly and i have to add special logic for batching anything that might wrap Knex or functions that use Knex in any way. It would be nice to be able to simple add a plugin or hook where i have the change to batch duplicate incoming requests. This doesn't need to be part of the core, but again, some way to extend Knex and add this would make the code a lot less hacky/brittle.

**Comment by taybin** [comment]
@cvburgess I'm sorry, I missed that the first time.  This is a neat idea.  We have a bunch of functions returning `BatchLoadFn<ID,Object>` that wrap the knex query.  This seems like less code, but maybe that's because of the simplicity of the example.

**Comment by cvburgess** [comment]
@taybin yeah i guess it works well if you only have a few functions or you are working strictly with IDs but as the application gets more complex and the same function accepts more than just IDs the loaders get more complex. It would be nice if I could take the SQL query ( like I did in the Gist ) and use that as the key for data loader to batch off of. It moves the complexity of the batching out of the app code and into a plugin or utility that is easier to debug and test.

**Comment by baer** [comment]
Thanks for sharing that implementation! I love the idea of a pre-request hook since it opens the door to clean implementations of logging, query optimization and data-loader style batching. 

For the caching case, however, why not just manage that in your model?

```
const cache = require('my-favorite-cache')
const TTL = 1000;

class Branch {
  constructor() {
    this.branchById = new DataLoader(ids =>
      getBaseBranch().whereIn("Branch", ids)
    );
  }

  getById(id) {
    const cachedValue = cache.get(id);
    if (cachedValue) {
      return cachedValue;
    }

    return this.branchById.load(id)
      .then(value => {
        cache.set(id, value, TTL)
        return value;
      })
  }
}
```

I love the idea of Knex hooks but it's going to be tricky to define a single global cache that has an appropriate TTL for all queries so short of a per-query hook, you'll need to do something like this anyway.

**Comment by cvburgess** [comment]
@baer In the case of a simple `id` lookup i absolutely agree, but as the parameters and joins and such get more complicated the construction of a cache-key becomes more complex. It would be nice to be able to use the knex-genereated query as the key but that might not be the best way to go

**Comment by cvburgess** [comment]
Yeah that might be the way to go here. Its a bit less "magical" but it gets the job done for caching.

Still would be nice to have the hook for batching which i don't think can be solved as easily but I'll keep diving into the DataLoader internals and see what I can come up with.

**Comment by baer** [comment]
I'm working on the exact same problem and, if I figure out anything nice, I'll try to post here. You should do the same.

**Comment by cvburgess** [comment]
Absolutely will do 👍

**Comment by olinoles** [comment]
Hi, just wanted to chip-in and say I turned this into an npm package based on @Axxxx0n's comment. I added a couple extras like invalidation and cache clearing.

https://github.com/olinoles/knex-cache
