### ISSUE TITLE
defaultTo() doesn't JSON.stringify json columns

### ISSUE THREAD

**Issue by coolaj86** [knex/knex#280]
I'm on PostgreSQL 9.3.4 and ran

``` javascript
knex.schema.table('user', function(t) {
  t.json('preferences').defaultTo({}).notNullable();
}).then(function () {
  console.log('modified columns');
});
```

and got the result

``` bash
             Column             |         Type          |                Modifiers
--------------------------------+-----------------------+------------------------------------------
 preferences                    | text                  | not null default '[object Object]'::text
```

It seems that `defaultTo()` should call `JSON.stringify()`.

P.S. I would think that table column type would be `json`, but I didn't set up this server, so it's possible that the `json` extensions are not enabled.

**Comment by JetFault** [comment]
I'm also getting `error: syntax error at or near "{"` when doing: `t.json('data').defaultTo({});`

**Comment by JetFault** [comment]
Doing `t.json('data').defaultTo('{}');` works and checking PG returns as a default of `'{}'::json` so all good.
