### ISSUE TITLE
Knex migrations refresh

### ISSUE THREAD

**Issue by theprobugmaker** [knex/knex#2907]
I was wondering if it's possible to refresh the migrations from the database, cleaning everything and calling migrations again.

Things that would be nice:

- `refresh` - rollback everything and call migrations again
- `reset` - rollback all the migrations

Also if it had a `--seed` so it would call `seed` automatically as well, like `knex migrate:refresh --seed`

**Comment by kibertoad** [comment]
@zefexdeveloper This is similar to https://github.com/tgriesser/knex/issues/2844
After that one is implemented, one can have this functionality by simply chaining rollback + migrations + seeds, why have redundant operations for that?

**Comment by zefexdeveloper** [comment]
@kibertoad It was just a suggestion, it was nice that the similar issue mentioned Laravel because that was the main reason I suggested `--seed` and the other functionalities, but chaining would work as well.

**Comment by bentesha** [comment]
Anyone working on this? Will have some free time next week.

**Comment by ffxsam** [comment]
Just started using knex and realized `migration:reset` does not exist like it does in Adonis. Seems like a pretty major thing to not include.

**Comment by elhigu** [comment]
@ffxsam pretty major or pretty trivial and rarely needed. It is usually faster to drop old db and re-create from ground up.

**Comment by ffxsam** [comment]
@elhigu "rarely needed" - not during the development phase, when one is still working on the schema. With Adonis, we've run `migration:reset` several times in the beginning.

**Comment by elhigu** [comment]
@ffxsam if you really run migrations down for resetting your DB I suppose that for you it would be frequently needed operation. Still trivial to to implement in your own npm scripts.

I could never recommend resetting DB like that. It is slow as hell and if there is single poorly written down script it can leave state to database so that next time when you run migrations initial state is different than when running migrations on clean database. 

That being said, I'm totally fine if you like to implement it to knex. I never use knex's command line client to anything anyways.

**Comment by MrToxy** [comment]
Any news on this?

**Comment by kibertoad** [comment]
@MrToxy Is this https://github.com/knex/knex/pull/3187 what you are looking for?

**Comment by MrToxy** [comment]
> @MrToxy Is this #3187 what you are looking for?

Not really, I don't think  #3187  is actually correct in the "refresh" context.
Taking a look at laravel's artisan, running `php artisan migrate:refresh` will re-run all of the migrations creating fresh tables with no data, that's exactly what I'm looking for.

**Comment by kibertoad** [comment]
@MrToxy Wouldn't you get same thing if you run first rollback:all, and then migrate:all?

**Comment by MrToxy** [comment]
@kibertoad can't find any references to migrate:all

**Comment by kibertoad** [comment]
@MrToxy Sorry, should actually be `migrate:latest`

**Comment by MrToxy** [comment]
> @MrToxy Sorry, should actually be `migrate:latest`

Alright that did the trick, thanks.
I have another question, let me know if I should open a new issue for this but here it goes.

I'm using strapi which has some issues, mainly it doesnt create migrations and when you delete/rename a table field it doesnt actually delete it from the table, and if you rename it'll just create a new field with the new name but keep the other.
This could be easily fixed if I had a way to create migrations programatically, something like const migration = knex.migratation.make(table_name, schema/options)

knex.migration.run(migration)

This way I could keep my database clean while maintaining a record of the Changes

**Comment by lorefnon** [comment]
@MrToxy You can use the [knex.mgirate](http://knexjs.org/#Migrations-API) API along with a [custom migration source](http://knexjs.org/#custom-migration-sources).

**Comment by MrToxy** [comment]
> @MrToxy You can use the [knex.mgirate](http://knexjs.org/#Migrations-API) API along with a [custom migration source](http://knexjs.org/#custom-migration-sources).

Could you link me an actual working example of a custom migration source?

**Comment by VsemP2** [comment]
package.json =>
```
{
  ...
  "scripts": {
    ...
    "refresh": "npx knex migrate:rollback & npx knex migrate:latest & npx knex seed:run"
    ...
  },
  ...
}
```
console => npm run refresh

**Comment by ffxsam** [comment]
@VsemP2 That should be `&&`, not `&`.

**Comment by VsemP2** [comment]
> @VsemP2 That should be `&&`, not `&`.

NP bro, but it works the same for npm

**Comment by Zauberbutter** [comment]
@VsemP2 Additionally you don't need the `npx` in your scripts.

**Comment by zanechua** [comment]
Posting the script that I wrote to handle this case as I need fresh tables for test etc and just way easier to run a command to drop and migrate. This probably won't work for all databases but should be fine for MySQL based databases.

I've been using this for months now so now that it's somewhat battle tested, should work fine.


```javascript
import knex from 'knex';
import knexFile from 'root/knexfile';

const freshMigrations = async () => {
  const config = knexFile;
  const database = config.connection.database;
  const charset = config.connection.charset;
  config.connection.database = null;
  const knexConnection = knex(config);

  knexConnection.raw(`DROP DATABASE IF EXISTS ${database}`).finally(() => {
    knexConnection
      .raw(`CREATE DATABASE IF NOT EXISTS ${database} CHARACTER SET ${charset}`)
      .finally(() => {
        config.connection.database = database;
        const migrationKnexConnection = knex(config);
        migrationKnexConnection.migrate.latest().finally(() => {
          knexConnection.destroy();
          migrationKnexConnection.destroy();
          process.exit(0);
        });
      });
  });
};

export default freshMigrations();
```

`package.json`
```javascript
"scripts": {
    "migrate:fresh": "node freshMigrations.js",
}
```
