### ISSUE TITLE
docs: parameters missing for distinct()

### ISSUE THREAD

**Issue by capaj** [knex/knex#3029]
![image](https://user-images.githubusercontent.com/1305378/52227250-48f64e00-28af-11e9-94d5-59b8e03ae025.png)

I believe it should be:
```
.distinct([*columns])
```

It would also be nice if it mentioned that it falls back to `*` when no parameters are supplied.

**Comment by HurSungYun** [comment]
there's a repo for documentation of Knex.

https://github.com/knex/documentation

maybe you can open issue there.

**Comment by kibertoad** [comment]
@capaj Would you consider contributing a PR for this?

**Comment by capaj** [comment]
opened as https://github.com/knex/documentation/pull/183
