### ISSUE TITLE
missing type definition for withRecursive

### ISSUE THREAD

**Issue by jrr** [knex/knex#3077]
# Environment

Knex version: 0.16.3
Database + version: postgres 10.5
OS: Mac OS

# Bug

The following [example](https://knexjs.org/#Builder-withRecursive) from the docs:

```js
knex.withRecursive('ancestors', (qb) => {
  qb.select('*').from('people').where('people.id', 1).union((qb) => {
    qb.select('*').from('people').join('ancestors', 'ancestors.parentId', 'people.id')
  })
}).select('*').from('ancestors')
```

Doesn't type check 😟

Indeed, it doesn't appear in this file at all: https://github.com/tgriesser/knex/blob/master/types/knex.d.ts

**Comment by kibertoad** [comment]
@jrr Would you consider contributing a PR for this?

**Comment by lorefnon** [comment]
This was taken care of as a part of https://github.com/tgriesser/knex/pull/3209
