### ISSUE TITLE
abstraction for now() / date('now')

### ISSUE THREAD

**Issue by coolaj86** [knex/knex#310]
I just pulled requested doc updates as #309, but it seems that `now` is a concept that is important and common enough to abstract into knex so that migration files are portable from one database to another.

What do you think?

Are there similar abstracted values that I could use as an example and add this feature as a pull request?

**Comment by ricardograca** [comment]
This `knex.fn.now()` thing should be documented [here](http://knexjs.org/#Schema-timestamp). Somehow it seems that the documented solution for SQLite there doesn't work anymore. Using `knex.raw("date('now')")` produces a syntax error with the latest version of the npm sqlite3 package, which ships libsqlite 3.8.x.

**Comment by bendrucker** [comment]
PR would be much appreciated @ricardograca

**Comment by ricardograca** [comment]
Right now I'm struggling with another potential issue with Bookshelf. Actually I'm still trying to figure out if it's my code's fault first, and that is keeping me quite busy, but I'll open a new issue so I don't forget about this.
