### ISSUE TITLE
json array becomes key of json object (and fails to parse)

### ISSUE THREAD

**Issue by coolaj86** [knex/knex#315]
There is a json field `cards` that contains an array. When the model serializes it serializes the array as the key to an object with no value and causes a parse error:

```
{ [error: invalid input syntax for type json]
  name: 'error',
  length: 192,
  severity: 'ERROR',
  code: '22P02',
  detail: 'Expected ":", but found "}".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: ...kR1PAJ\\",\\"customerId\\":\\"cus_4D10fjjmkR1PAJ\\"}"}',
  file: 'json.c',
  line: '1075',
  routine: 'report_parse_error' }
```

This error is actually from the `pg` library, so maybe the problem is actually there. How would I see the SQL right before it's handed off to `pg`?

**Comment by CaptainJojo** [comment]
It's close but does'nt work, is in my model I send array of json , I have 'error syntax'

**Comment by rhys-vdw** [comment]
Hi @CaptainJojo. Can you please open this as a new issue including code that generates the error, and pass `debug()` to log the generated query.

**Comment by sielay** [comment]
Any updates on this one? My case
```
{
 name: 'my page',
     path: 'page/template',
     javascripts: [ 'js1', 'js2' ],
     stylesheets: [ 'css1', 'css2' ] } }
```
does
```
insert into "template" ("javascripts", "name", "path", "stylesheets") values ('{"js1","js2"}', 'my page', 'page/template', '{"css1","css2"}') 
```
that ends up as
```
insert into "template" ("javascripts", "name", "path", "stylesheets") values ($1, $2, $3, $4) returning "id" - invalid input syntax for type json 
``

**Comment by sielay** [comment]
Anyhow stringify before save does the trick.
