### ISSUE TITLE
Crossdb support for INSERT ... ON CONFLICT / MERGE upsert

### ISSUE THREAD

**Issue by elhigu** [knex/knex#3186]
# Environment

# Feature discussion / request

1. Explain what is your use case

To support MERGE / ON CONFLICT features of databses.

2. Explain what kind of feature would support this

Full discussion about the feature is in https://github.com/tgriesser/knex/pull/2197#issuecomment-325934623

Conclusion by @jordansexton  was:

Okay. I'll finish the implementation for `DO NOTHING/UPDATE` on Postgres and `INSERT IGNORE/ON DUPLICATE KEY UPDATE` on MySQL in this PR, probably using two methods:
```javascript
insert({ ...inserts }).ignore([columns]?)
insert({ ...inserts }).merge({ ...updates }, [columns]?)
```

My reasoning is:

1. `replace` implies full replacement, whereas `merge` implies partial replacement (essentially, the semantics for a generic "object merge" are equivalent to what actually happens in the operation)
2. Only SQLite uses `REPLACE`. Since this PR won't support SQLite, and "replace" is a semantically different operation, it's probably better to have a different `replace` method (if supported at all).
3. The SQL standard uses `MERGE`. In the event that other RDBMS's converge upon the standard, `merge` is likely more future-proof than an ad-hoc alternative.
4. A followup PR to support MS SQL and Oracle will be able to use the same method and just work. I don't use either, but I'll take a stab at supporting both when this is settled. The second `columns` argument could be used to provide aliases for those instead.
3. Give some API proposal, how the feature should work

**Comment by SherloxFR** [comment]
I think this feature is really important to implement, currently it seems I'm only able to do it this way:
```javascript
knex.raw(
  await knex
  .insert({
    a: 1,
    b: 2,
    c: 3,
    d: 4
  })
  .into('my_table')
  .toQuery() +
  await knex
  .raw(`
    ON DUPLICATE KEY UPDATE
      a = :a,
      b = :b,
      d = :d
  `, {
    a: 1,
    b: 2,
    d: 4,
  })
  .toQuery()
)
```

Surely we can all agree this is really an awful way to write SQL.

**Comment by elhigu** [comment]
Removed a lengthy comment that basically said +1 and didnt add any value to the thread.

**Comment by codeclown** [comment]
After taking a stab at implementing this, here's some more things to consider I unfortunately found out:

|          | can support ignore() | merge({ ... }, ['foo']) works | merge({ ... }, []) works |
| --- | --- | --- | --- |
| Mysql    | No* | No** | Yes |
| Postgres | Yes | Yes | [No](https://stackoverflow.com/a/39134240/239527) |
| Oracle   | [Yes](https://stackoverflow.com/a/17946783/239527) | Yes | No*** |

\* Technically can, but with a work-around which requires knowledge of schema: `ON DUPLICATE KEY UPDATE id=id`
\** Cannot specify constraints, only generic `ON DUPLICATE KEY UPDATE`
\*** Pretty sure that you can't just omit `ON t1.key = t2.key` -> need to specify constraints

So, MySQL can't implement `ignore()`, and Postgres and Oracle require constraints to be specified when using `merge()`. How should knex resolve this? Throw an error from query builder based on current driver?

**Comment by SherloxFR** [comment]
Hey @codeclown, just trying to understand here.

For the `ignore()` part, the Postgres version is `ON CONFLICT DO NOTHING` right ?
If so, why would you need to have a workaround with schema knowledge in MySQL if you can just `INSERT IGNORE INTO` ?

Am I missing something here ?

**Comment by elhigu** [comment]
@codeclown Thank you for further investigation! I think we can work around those limitations to still have crossdb compatible functionality in addition to more DB specific variations (which can be used if there is no need to support multiple DBs).

To give more schema knowledge for method, we can give one more options parameter to the API where user can provide necessary information to make some calls to work the same on every DB engine.

1. If I understood correctly the `.ignore([columns])` was already supported on every platform, so ignore can be used as long as column list is given (and even `.ignore()` could be used if @SherloxFR is right). 

2. For merge `.merge({ ...updates... }, listOfAllColumnNames, { allColumns: true })`  would work for mysql, posgres and oracle the same way... And mysql just will throw an error if column list is given, but the extra option is not passed to method.

So everything still looks pretty promising 👍

**Comment by nicoburns** [comment]
I've put in a pull request for this feature here: https://github.com/knex/knex/pull/3763

Notes:
- MySQL, Postgres, and Sqlite are supported.
- MySQL is using `INSERT IGNORE`/`ON DUPLICATE KEY UPDATE`.
- Postgres and Sqlite are both using `ON CONFLICT DO IGNORE/UPDATE`. Sqlite introduced support for this syntax in version 3.24.0 (2018-06-04).
- Syntax is *slightly* different: Instead of `ignore(columns)` we have `.onConflict(columns).ignore()`. Instead of `.merge(updates, columns)` we have `.onConflict(columns).merge(updates)`.
- The reasoning behind this change is that I've made `updates` optional. If `updates` is not specified then the values from `insert` is used for updating too. This is a very common use case "I want this row in the database with exactly these values, whether it was there before or not", and also enables `.merge()` to work with batch inserts. However it required the awkward `.merge(null, columns)` with the suggested syntax.
- `onConflict()` is currently optional (a noop) for MySQL. It's not needed because MySQL doesn't allow you to specify the columns anyway.
- Relatedly specifying both `ignore()` and `merge()` in the same query is not valid, but there is currently no check to prevent you from doing this. It will simply compile invalid SQL. It wouldn't be hard to add a check.

**Comment by elhigu** [comment]
Looks really good. Having that separate`.onConflict()` column list indeed makes some calls nicer. 

> onConflict() is currently optional (a noop) for MySQL. It's not needed because MySQL doesn't allow you to specify the columns anyway.

As I mentioned in earlier comment https://github.com/knex/knex/issues/3186#issuecomment-555934323 if columns are declared, it should throw an error on mysql unless an extra option telling that list actually contains all the columns is of the table.  

That verifies that the user is not accidentally trying to do something that is not supported on mysql and still allows to write cross database compatible code which works the same way on pg, mysql and sqlite (mysql being the lowest common denominator).

**Comment by KristjanTammekivi** [comment]
Something to also consider is that you can have partial unique indexes in postgres and when you do an upsert you must specify the where

ie.
```sql
CREATE UNIQUE INDEX ON button_toggles (button_id) WHERE disabled_at IS NULL;
INSERT INTO button_toggles (button_id) VALUES (1) ON CONFLICT (button_id) WHERE disabled_at IS NULL DO NOTHING;
```

Note that we can't use .where to specify the conflict since the merge part can also have a WHERE to conditionally update

**Comment by elhigu** [comment]
@KristjanTammekivi how does that feature work on other dialects or is it completely postgres specific? Especially if that is not a general feature I would say that it should be implemented as a separate feature request that needs to be implemented on top of this first version. I mean having proper where conditions support may makes this a lot more complex.

**Comment by KristjanTammekivi** [comment]
Sadly, according to a quick google, it seems this is Postgres specific :/

**Comment by kibertoad** [comment]
@elhigu Does #3763 fully cover your original intention?

**Comment by elhigu** [comment]
It was actually @jordansexton who figured out what was needed for having this implemented as cross db compatible way as posible. But yeah #3763 does it, except for mssql and oracle support 👍
