### ISSUE TITLE
Knex.Schema: How to create composite unique key?

### ISSUE THREAD

**Issue by amitava82** [knex/knex#32]
For example,

```
ALTER TABLE users ADD UNIQUE KEY(LoginID, Email);
ALTER TABLE users ADD UNIQUE KEY(Email);
ALTER TABLE users ADD UNIQUE KEY(LoginID);
```

How do I do it with `Knex.Schema.createTable`

**Comment by tkrotoff** [comment]
@bendrucker when you link to a source file please use a tag/commit instead of master:
Your link that does not work anymore: https://github.com/tgriesser/knex/blob/master/test/integration/schema/index.js#L92
VS what you meant: https://github.com/tgriesser/knex/blob/0.5.11/test/integration/schema/index.js#L92
And using latest version (0.8.6): https://github.com/tgriesser/knex/blob/0.8.6/test/integration/schema/index.js#L157

**Comment by tgriesser** [comment]
Protip: if you press the "y" key while browsing on github it switches to the current sha url for the current file you're viewing. Super convenient, I wish github would just automatically do that when you paste in a gh url in a comment

**Comment by RichardSimko** [comment]
Has this feature been deprecated since it's not in the documentation?

**Comment by maxtruxa** [comment]
@RichardSimko [According to the test suite](https://github.com/tgriesser/knex/blob/2e1a459a9e740f24b9a4647bd4da427854e551dd/test/integration/schema/index.js#L194) the `table.unique([...])` syntax for compound keys is still supported, so it looks like a bug with the documentation.

**Comment by RichardSimko** [comment]
Yeah, I realized that it still worked, I was just worried that it's about to be removed due to it not being in the docs.

**Comment by PierBover** [comment]
So what's the difference between `table.unique([...])` and `table.primary([...])` ?

As per the docs  it seems using `primary([...])` is the proper way of doing composite primary keys:

> When called on a single column it will set that column as the primary key for a table. To create a compound primary key, pass an array of column names: `table.primary(['column1', 'column2'])`. Constraint name defaults to `tablename_pkey` unless `constraintName` is specified.

http://knexjs.org/#Schema-primary
