### ISSUE TITLE
How to add indexes if they do not already exist

### ISSUE THREAD

**Issue by kmalakoff** [knex/knex#322]
Hi Tim,

I've been trying to add indexes to existing columns in postgres database.

I think I found a way to add them using (I found this documented in the knex source):

```
table.index('column_name')
```

The problem is that the indexes may already exist in which case I get the following error:

```
Error: model ensureSchema { [error: relation "models_column_name_index" already exists]
  name: 'error',
  length: 104,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'index.c',
  line: '777',
  routine: 'index_create' }
```

I've been working at trying to do this for around 6 hours using the `Knex.schema.table(table_name, (table) -> ).exec(callback)` inner block and feel like I must be missing something. I originally tried to find a way to get access to a column builder, but I couldn't use the `table.type(column_name).index()` syntax because the column already existed and even if it did, I assume that I would get the same index already existing error.

Is there a lower level way to check for indexes existing? Ideally, it would be general purpose enough that you could check if a column was indexed, primary, nullable, unique, etc.

Thank you in advance for any advice and pseudo code.

**Comment by Kagami** [comment]
The same problem appears for automatically created unique indexes. I use SQLite backend and multicolumn UNIQUE index:

```js
knex.schema.createTableIfNotExists("known_nodes", function(table) {
  table.string("host", 39).notNullable(); // IPv4/IPv6 address
  table.integer("port").notNullable();
  table.integer("stream").notNullable();
  table.binary("services").notNullable();
  table.timestamp("last_active").notNullable().defaultTo(knex.fn.now());
  table.unique(["host", "port", "stream"]);
});
```

At the second run I got this error:
```
SQLITE_ERROR: index known_nodes_host_port_stream_unique already exists
```

@tgriesser, @bendrucker Is there any better method for this than `hasTable`/`createTable`? I'm wondering why callback of `createTableIfNotExists` got run even if the table already exists.

**Comment by chill117** [comment]
@Kagami I ran into this issue as well. I think it is by design that the callback is always called. Internally the table is only created by `createTableIfNotExists` the first time. And for every following call the table is not created, but the callback is still called with the table object. The following worked for me:
```js
db.knex.schema.hasTable('some_table', function(exists) {

	if (!exists) {

		return knex.schema.createTable('some_table', function(table) {

			table.increments('id').primary();
			table.string('some_column').unique().notNullable();
		});
	}

});
```

**Comment by yamikuronue** [comment]
I agree, this is highly unintuitive. The docs seem to imply that the callback is only being called if the table did not exist, so it can be created; otherwise, why would you need to call the table creation API anyway?

**Comment by bennyn** [comment]
I also expected that `knex.schema.createTableIfNotExists` **doesn't** run the callback if the table already exists. So the official workaround is to check with `hasTable` beforehand?

**Comment by tylerjwatson** [comment]
I've also bumped up against this.  There is no point in a `createTableIfNotExists` function when the callback gets executed regardless.  It's not such a big deal for statements inside the `CREATE TABLE` expression, but it'll break completely for indices and other constraints which are executed outside it.

Can we please either get some clarification on its intended behaviour?

Cheers

**Comment by elhigu** [comment]
@tylerjwatson Clarifications are found in https://github.com/tgriesser/knex/issues/1303
