### ISSUE TITLE
CLI --connection option is difficult to use

### ISSUE THREAD

**Issue by realazthat** [knex/knex#3305]
# Environment

Knex version: 0.17.3
Database + version: All (but using postgres)
OS: All (but using Ubuntu 18.x)

# Bug

> 1. Explain what kind of behaviour you are getting and how you think it should do

Conditions:

- There exists a knexfile
- And while running `npx knex  --client pg --connection <dsn> migrate:latest`

Result:

- DSN is ignored; even if no connection is specified in knexfile

Expected:

- An option to ignore a knexfile.js if it happens to be in the same path.
- And Either:
  - An error/warning that `connection` option is being ignored
  - Or the --connection argument should override the knexfile

[Here](https://github.com/tgriesser/knex/blob/858c7b6f1e1591075d7f51b647e0083731c2471e/bin/cli.js#L69) is the codepath that shows how hard it is to get --connection argument to work:

<a href="https://github.com/tgriesser/knex/blob/858c7b6f1e1591075d7f51b647e0083731c2471e/bin/cli.js#L69">![Illustration of codepath](https://i.imgur.com/TtkNCbB.png)</a>

> 2. Error message

- In the case that the knexfile leaves out the connection: `Error: Unable to acquire a connection`
- In the case that the knexfile has a connection string/object, and/or tries to connect to the db instance specified and fails with a connection error; or worse, it silently fails and connects to the wrong db instance.

> 3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

N/A

**Comment by kibertoad** [comment]
@realazthat Would you consider submitting PR for this, with test?

**Comment by kibertoad** [comment]
There are good examples of CLI tests already: https://github.com/tgriesser/knex/blob/master/test/cli/knexfile-test.spec.js

**Comment by kibertoad** [comment]
Released in 1.0.5
