### ISSUE TITLE
PostgreSQL GROUP BY prepared statement/bindings/raw error

### ISSUE THREAD

**Issue by Redirts** [knex/knex#3323]
# Environment

Knex version: 0.18.0
Database + version: PostgreSQL 11.2
OS: Windows 10

# Bug

1. **behaviour** 
We built a raw query that will produce a prepared statement with bind variables that has a GROUP BY clause and when it is executed via Knex/PG driver it produces an error. 

2. Error message

2019-06-27T15:37:57.660Z error: {
  "message": 
"select date_trunc($1, ora12_sysmetric.timest) as "t0", "ora12_sysmetric"."db" as "d0", avg(ora12_sysmetric.value) as "m0" 
from "facts"."ora12_sysmetric" 
where "ora12_sysmetric"."timest"> $2 and "ora12_sysmetric"."timest" <= $3 
group by date_trunc($4, ora12_sysmetric.timest), "ora12_sysmetric"."db" 
order by date_trunc($5, ora12_sysmetric.timest) 
asc limit $6 - column "ora12_sysmetric.timest" must appear in the GROUP BY clause or be used in an aggregate function",

Just before I see that the query that will be executed with non-native binds is:

2019-06-27T15:37:53.627Z info: 
sql: select date_trunc(?, ora12_sysmetric.timest) as "t0", "ora12_sysmetric"."db" as "d0", avg(ora12_sysmetric.value) as "m0" 
from "facts"."ora12_sysmetric" 
where "ora12_sysmetric"."timest" > ? and "ora12_sysmetric"."timest" <= ? 
group by date_trunc(?, ora12_sysmetric.timest), "ora12_sysmetric"."db" 
order by date_trunc(?, ora12_sysmetric.timest) 
asc limit ? bindings: minutes,Tue Oct 02 2018 10:33:07 GMT+0100 (Western European Summer Time),Tue Oct 02 2018 10:34:07 GMT+0100 (Western European Summer Time),minutes,minutes,50000

What seems to be happening is that either Knex or pg package are validating the strings 

Select:
date_trunc($1, ora12_sysmetric.timest)

and group by:
group by date_trunc($4, ora12_sysmetric.timest)

and they don't match and hence it produces an error.
It should not produce an error as this is a valid query once bindings are resolved.

**Comment by jxm262** [comment]
FWIW, I'm confirming the same issue on my end as well.  Exactly as you described, the `date_trunc` in the group by is throwing that same error.  

As a workaround, I'm going to try and just move this all to the query builder, but it would be nice if we could get some clarity on how to fix this in rawsql

**Comment by elhigu** [comment]
> What seems to be happening is that either Knex or pg package are validating the strings

It is the database server which does that validation. 

>  it would be nice if we could get some clarity on how to fix this in rawsql

Let's reopen if working SQL that knex could generate is provided.
