### ISSUE TITLE
Support Oracle driver 4.0.0

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#3396]
Currently tests are failing when latest Oracle driver is used.

**Comment by elhigu** [comment]
I should take a look what causes it. Previously there has been bugs in new versions of oracle drivers.

**Comment by PeterMerkert** [comment]
Maybe we should write down the errors which are happening? That would help to find this issue.

I have now the following one popping up: `Error: ORA-12519: TNS:no appropriate service handler found`. That seems to create a timeout my Ava test can not handle properly.

**Comment by kibertoad** [comment]
@PeterMerkert Are you using blob functionality? I think that's the part that is failing.

**Comment by PeterMerkert** [comment]
@kibertoad Nope, I am not using any blob functionality. I use select, several joins join, update, delete and raw statements.

**Comment by elhigu** [comment]
Was this fixed by #3480 ?

**Comment by kibertoad** [comment]
Should have been, yes.
@PeterMerkert Could you please try using 0.20.0 and report back?

**Comment by PeterMerkert** [comment]
I got the upgrade and for me all my features are still working. The new version is in my code.

But remember, I have reported before that I did maybe not use the functionality which was broken in the first place.

Thanks a lot for the new version though anyways!

**Comment by kibertoad** [comment]
@PeterMerkert Awesome, I was wondering if we broke something while fixing something :D
