### ISSUE TITLE
Sqlite3 hasColumn should be case insensitive

### ISSUE THREAD

**Issue by alexandrebodin** [knex/knex#3434]
# Environment

Knex version: 0.16.5
Database + version: sqlite3
OS: mac

# Bug

When runing the function `hasColumn` on sqlite the answer is case sensitive. Meaning that `test` and `Test` are considered as two different columns. 
In reality sqlite3 names are case insensitive. If you use `hasColumn` to check if a column exist and then create it this will cause a `duplicate column error` when you just change the case of one char. 

Happy to make a PR if this makes sense to you guys.

**Comment by kibertoad** [comment]
Can you please explain how names are both case-insensitive but also case-sensitive during check? Does the same logic apply when using sqlite directly? We mess something up on knex side?

**Comment by alexandrebodin** [comment]
Sorry I wasn't clear:

The knex function  `hasColumn(table, 'test')` where the table has a column named `Test` returns false but when creating a new column with the name `test` sqlite complains that the `test`column exists. 

This means that sqlite is case-insensitive but the knex implementation of the `hasColumn` function isn't.


https://github.com/tgriesser/knex/blob/master/lib/dialects/sqlite3/schema/compiler.js#L26-L38 this implementation should lowercase both names to compare for example

**Comment by kibertoad** [comment]
@alexandrebodin But if sqlite is case-insensitive by itself, shouldn't it be irrelevant whether you are lowercasing passed parameters?

**Comment by kibertoad** [comment]
ah, ok, I see now, sorry, it's not done via SQL. PR would be most appreciated!

**Comment by alexandrebodin** [comment]
Exactly :) Ok will do.

**Comment by kibertoad** [comment]
Released in 0.20.2
