### ISSUE TITLE
Property '...' does not exist on type QueryBuilder (extended)

### ISSUE THREAD

**Issue by iki** [knex/knex#3458]
# Environment

Knex version: 0.19.4

Select applicable template from below.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

  - Used https://github.com/cvburgess/SQLDataSource, which wraps Knex and [extends QueryBuilder with cache](https://github.com/cvburgess/SQLDataSource/blob/master/index.js#L20).
  - Added module typings:
    ```
    declare module 'datasource-sql' {
      import { KeyValueCache } from 'apollo-server-caching'
      import { DataSource, DataSourceConfig } from 'apollo-datasource'
      import Knex from 'knex'

      export declare abstract class SQLDataSource<TContext = any> extends DataSource<TContext> {
        db: Knex
        cache: KeyValueCache
        context: TContext

        constructor(knexConfig: Knex.Config)
        initialize(config: DataSourceConfig<TContext>): void
        cacheQuery(ttl: number, query: Knex): Knex.QueryBuilder
      }
    }
    ```
  - Tried the [example](https://github.com/cvburgess/SQLDataSource#usage).

2. Error message

```Property 'cache' does not exist on type 'QueryBuilder<unknown, DeferredKeySelection<unknown, string, false, {}, false, {}, never>[]>'.```

**Comment by iki** [comment]
What is the proper solution to using types with extended QueryBuilder?

I can create extended custom QueryBuilder interface, but do I have to retype all methods then?

Is it similar to https://github.com/Vincit/objection.js/issues/319?

**Comment by lorefnon** [comment]
You can use take advantage of TypeScript's [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) feature. An example of this can be found [here](https://github.com/knex/knex/blob/master/types/test.ts#L7-L11).

**Comment by iki** [comment]
@lorefnon thanks, it works perfectly

```ts
declare module 'datasource-sql' {
  import Knex from 'knex'
  import { KeyValueCache } from 'apollo-server-caching'
  import { DataSource, DataSourceConfig } from 'apollo-datasource'

  declare module 'knex' {
    interface QueryBuilder {
      cache<TRecord, TResult>(ttl: number): QueryBuilder<TRecord, TResult>
    }
  }

  export type SQLDataSourceConfig = Knex.Config
  export type SQLDataSourceQuery = Knex.QueryBuilder

  export declare abstract class SQLDataSource<TContext = any> extends DataSource<TContext> {
    protected db: Knex
    private cache: KeyValueCache
    protected context: TContext

    constructor(knexConfig: Knex.Config)
    initialize(config: DataSourceConfig<TContext>): void
    protected cacheQuery(ttl: number, query: Knex): Knex.QueryBuilder
  }
}
```

**Comment by KarmaBlackshaw** [comment]
Help. I can't seem to make it work

```js
declare module 'knex' {
  interface QueryBuilder {
    metaDate<TRecord, TResult>(query: any): KnexOriginal.QueryBuilder<TRecord, TResult>
  }
}

test('Adds startOf day and endOf day if time is not present', () => {
  const dictionary = {
    birthdate: 'users.birthdate'
  }

  const result = knex('users')
    .metaDate({
      dateBy: 'birthdate',
      dateFrom: '1998-07-29',
      dateTo: '1998-07-29',
      dictionary
    })
    .toString()

  const expected = "select * from `users` where `users`.`birthdate` >= '1998-07-29 00:00:00' and `users`.`birthdate` <= '1998-07-29 23:59:59'"

  expect(result).toBe(expected)
})
```
![image](https://user-images.githubusercontent.com/40014179/221826646-a94560ce-ad43-40c0-a814-06c7fb0ba5a1.png)
