### ISSUE TITLE
Issue retrieving BLOB from database (oracle) - iLob attribute undefined

### ISSUE THREAD

**Issue by matthieu-1989** [knex/knex#3467]
Knex version: 0.19.5
Objection version: 1.6.0
Database + version: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
OS: Windows 10 Professional

@atiertant 

While retrieving data from database, if at least one of the result column type is BLOB, the query fails.
Error message:
  Cannot read property 'type' of undefined",
  "stack":"TypeError: Cannot read property 'type' of undefined
  at readStream (my_node_modules\\knex\\lib\\dialects\\oracledb\\index.js:355:19

Checking "knex\\lib\\dialects\\oracledb\\index.js" code. The "stream" input attribute passed to the readStream function (line 355) doesn't have a "iLob" attribute.

Regards,
Matthieu

**Comment by kibertoad** [comment]
What version of Oracle driver (nodejs dependency) are you using? There was a major update lately that knex is not compatible with yet.
Does it work better with older knex?

**Comment by matthieu-1989** [comment]
We are now using the 4.0.1 version of oracledb. That's true there was no issue with the old 1.13.1 version of oracledb and the 0.13.0 version of knex.

**Comment by kibertoad** [comment]
I think it is #3396

**Comment by kibertoad** [comment]
@matthieu-1989 Could you please try with 0.20.0?

**Comment by lpillai** [comment]
Fix doesn't seem to work with BLOB data type.

Checked with knex v0.20.1: CLOB data can be retrieved successfully but knex hangs when retrieving data from a BLOB column. Debugging shows the execution waiting forever at line #353 when trying to concatenate two buffers:
        data = Buffer.concat([data, chunk]);
in knex\lib\dialects\oracledb\index.js"

I have oracledb v4.0.1 installed with 'Oracle Database 19c Enterprise Edition Release 19.0.0.0.0'. And I have node running on mac.

**Comment by robmcguinness** [comment]
I'm seeing the same results as @lpillai

- **knex** `v0.20.2`
- **instant client** `v19.3.0`
- **oracledb** `v4.0.1`

investigating 🤔

**Comment by robmcguinness** [comment]
Modifying the `readStream` function at https://github.com/knex/knex/blob/f4099af3fbf416975b44295ca3af1ac8a3a878ed/lib/dialects/oracledb/index.js#L342 to

```js
function readStream(stream, type) {
  return new Promise((resolve, reject) => {
    let data;

    if (type === 'string') {
      data = '';
    } else {
      data = Buffer.alloc(0); // allocate to empty Buffer when not string
    }

    stream.on('error', function(err) {
      reject(err);
    });
    stream.on('data', function(chunk) {
      if (type === 'string') {
        data += chunk;
      } else {
        // handle non-string chunking 
        const blobLength = data.length + chunk.length;
        data = Buffer.concat([data, chunk], blobLength);
      }
    });
    stream.on('end', function() {
      resolve(data);
    });
  });
}
```
resolves the issue. This essentially splits the code to handle streams of type `string` differently from non-strings.

I'll try and submit a PR possible.

**Comment by kibertoad** [comment]
@robmcguinness Is is the same as https://github.com/knex/knex/pull/3545/files?

If you can confirm that fix is sufficient, I can release a new version with fix.

**Comment by robmcguinness** [comment]
@kibertoad it does appear to be the same and more concisely written 😄

**Comment by kibertoad** [comment]
Released in 0.20.3

**Comment by kibertoad** [comment]
@robmcguinness Please let me know if new version fixes the issue for you!

**Comment by robmcguinness** [comment]
the fix appears to work. much appreciated @kibertoad! 🙏
