### ISSUE TITLE
ReferenceError: name is not defined

### ISSUE THREAD

**Issue by sam-jg** [knex/knex#3468]
# Environment

Knex version: 0.19.3
OS: macOS Mojave

# Bug

I am trying to use the following stub file for creating knex migration files and receive the error shown below.

```
// Update table name below
const name = 'TEMPTABLENAME';

exports.up = knex => {
    return knex.schema.createTable(name, table => {
        table.uuid(`${name}_id`).primary();
        table.timestamps(true, true);
    });
};

exports.down = knex => {
    return knex.schema.dropTableIfExists(name);
};
```

I believe this is cause by the string interpolation on line 6. Changing just line 6 to
```table.uuid('id').primary();``` makes the error go away but obviously doesn't really achieve what I am trying to do.

Error message
```
ReferenceError: name is not defined
    at eval (lodash.templateSources[0]:7:10)
    at MigrationGenerator._writeNewMigration (XXXX/server/node_modules/knex/lib/migrate/MigrationGenerator.js:66:9)
    at _ensureFolder.then.then (XXXX/server/node_modules/knex/lib/migrate/MigrationGenerator.js:24:27)
```

**Comment by ricardograca** [comment]
Clearly the variable `name` is not defined. Check the documentation on how to use `createTable()`: https://knexjs.org/#Schema-createTable

**Comment by ricardograca** [comment]
Sorry about my previous rushed response.

I don't know what's wrong, but this is almost certainly not a knex bug. Can you explain why you're not simply using a string value with the table name in the `up` and `down` methods?

**Comment by sam-jg** [comment]
Mostly just for the convenience. So that when I make a new migration file I don't have to go and change the file name in multiple places and potentially make a typo.

I would think that using a variable for the table name would be a pretty common pattern and don't think the issue is with the variable anyway. It is the string interpolation that looks to be causing the issue.

**Comment by lorefnon** [comment]
Knex [treats](https://github.com/knex/knex/blob/9aa7085b052938dc5252d10b2b418a475637eda5/lib/migrate/MigrationGenerator.js#L50) migration stubs as lodash templates which tries to substitute the interpolated expression (`${ ... }`) when the template function is invoked.

I'd consider this to be a bug in Knex, but until we fix this, a simple workaround for you is to use simple string concatenation: `name + '_id'`.

**Comment by sam-jg** [comment]
Makes sense. Workaround works.
