### ISSUE TITLE
I created a ✨ TypeScript GraphQL Starter Template ✨

### ISSUE THREAD

**Issue by vladinator1000** [knex/knex#3475]
Hey y'all, I've been working on some TypeScript + GraphQL apps with Knex lately and wanted to share my setup with everyone. Hope you like it ✨🔭

https://github.com/vladinator1000/ts-gql-knex

**Comment by lorefnon** [comment]
While this issue is likely to get closed soon because of it not being an actionable task at our end, perhaps we can collaborate on [GRelDAL](https://github.com/gql-dal/greldal).
