### ISSUE TITLE
Normilize string with knex

### ISSUE THREAD

**Issue by Duarte007** [knex/knex#3484]
Can I format strings for Unicode Normalization Form with knex?
I want to replace accented characters to save without accentuation.

Ex:
I hoped that "José" would substitute for "Jose", and "Cajú" to "Caju", etc...

Thanks

**Comment by Duarte007** [comment]
> Can I format strings for Unicode Normalization Form with knex?
> I want to replace accented characters to save without accentuation.
> 
> Ex:
> I hoped that "José" would substitute for "Jose", and "Cajú" to "Caju", etc...
> 
> Thanks

In js exist the method string.normilize()
I want a method in knex, or mysql that do the same thing.

**Comment by elhigu** [comment]
You should normalize those values before passing them to knex to insert / update values in DB. With objection,js ORM you could also provide before insert / before update hooks etc. where certain column values could be set to be normalized automatically. With knex that kind of functionality is a bit inconvenient to implement.
