### ISSUE TITLE
How can I make an insert for nested resources?

### ISSUE THREAD

**Issue by emanuelcasco** [knex/knex#3488]
# Environment

Knex version: `0.19.2`.
Database: `postgres`.

# Question

How can I make an insert for nested resources? For example, given the following models in my db:
> products => HaveMany => variants => HaveMany => attributes.

First I create my product, then I use product id to create variants, and finally I have to create variant attributes. My doubt is, how do I map attributes with their corresponding variant? Id is autogenerated by DB.

I would like to call db just one time per model (3 times in this case).

Thank you very much for your time.

**Comment by kibertoad** [comment]
You need an ORM. Try objection.js or bookshelf.

**Comment by emanuelcasco** [comment]
Yeah but project owners don't want to use an ORM, so we need to implement this in pure Knex.

**Comment by kibertoad** [comment]
You'll need to use .returning() to retrieve id and do follow-up insert then.

**Comment by kibertoad** [comment]
I would still recommend giving objection a chance. As far as orms go, it's very non-intrusive and lightweight.

**Comment by emanuelcasco** [comment]
I agree with you, I will try to convince them to use Objection or any other ORM. Thank you very much for your time. I'll close the issue

**Comment by elhigu** [comment]
Answer is what @kibertoad said. If you like to do it without an ORM you have to write manually multiple queries every time...

That being said, this is something that everyone who intends to use plain knex should read first https://www.jakso.me/blog/objection-to-orm-hatred. 

Basically when you have implemented that nested insert feature in a general way you have just re-invented orm.

**Comment by elhigu** [comment]
And looks like I was too slow with mobile commenting 😄
