### ISSUE TITLE
Include Postgres transaction id in database connection 

### ISSUE THREAD

**Issue by hudy7** [knex/knex#3493]
# Environment

Knex version: v0.19.5
Database + version: postgres v11.1

# Feature discussion / request

1. Explain what is your use case

We would like to have the postgres transaction id (`txid`) returned as apart of the query data or a mapping from `__knexTxId` to the postgres `txid`. This would allow us to determine which transactions are causing our locks.

Currently, the response just begins at 1 and increments on every query to the db, giving no real data about the current postgres txid:

```
{ __knexUid: '__knexUid1',
  __knexTxId: 'trx3',
  sql: 'COMMIT;',
  bindings: undefined }
```

2. Explain what kind of feature would support this

Including the postgres txid or a mapping from the `__knexTxId` to the `txid` would support this.

3. Give some API proposal, how the feature should work

```
{ __knexUid: '__knexUid1',
  __knexTxId: <actual postgres txid>,
  sql: 'COMMIT;',
  bindings: undefined }
```

**Comment by elhigu** [comment]
You can query it by your self with `knex.select(knex.raw('txid_current()'))`. 

If this can be easily implemented for all of the drivers without need to create implicit queries, then I suppose we could always use database's native transaction id also inside knex.

Can be reopened if you can show me how to get transaction id from `node-postgres` driver without need for an additional query (`begin` query doesn't return the transaction id).

**Comment by elhigu** [comment]
You can also extend knex with your own transaction methods, which does that query automatically after creating transaction and then stores it to connection.
