### ISSUE TITLE
Promise undefined when running migrations

### ISSUE THREAD

**Issue by SentientClee** [knex/knex#3494]
Our knex dependency recently got upgraded from `^0.13.0` to `^0.19.5` and some of our migrations no longer run because `Promise` is no longer defined when the exported `up` function is called. The screenshot shows the error received. Is the `Promise` parameter no longer supported in exported migration functions? These migrations run perfectly fine when using the older version `^0.13.0`.
```JavaScript
exports.up = function(knex, Promise) {
    return Promise.all([
    // do stuff
    ]);
};
```
<img width="1062" alt="Screenshot 2019-10-23 01 58 07" src="https://user-images.githubusercontent.com/42755149/67376975-d828bc00-f539-11e9-8067-b6161ed17a9b.png">

**Comment by ricardograca** [comment]
You can fix this by changing your migration files to:

```js
exports.up = function(knex) {
    return Promise.all([
    // do stuff
    ]);
};
```

**Comment by SentientClee** [comment]
Thanks @ricardograca, I noticed that new migration files generated on version `0.19.5` don't include the `Promise` parameter. Is there a changelog or specific commit you can point me to that includes this change? That way when we do upgrade to/past that version, we can be sure to modify our migration files accordingly.

**Comment by kibertoad** [comment]
See UPGRADING.md

**Comment by danielo515** [comment]
> Thanks @ricardograca, I now notice that new migration files generated on version `0.19.5` don't include the `Promise` parameter. Is there a changelog or specific commit you can point me to that includes this change? That way when we do upgrade to/past that version, we can be sure to modify our migration files accordingly.

The answer is NO. I checked the changelog and there is no reference to the Promise object not being provided anymore. That is an important breaking change that should be notified. Too bad
