### ISSUE TITLE
update ignores limit 1

### ISSUE THREAD

**Issue by mibi-r** [knex/knex#350]
All concerned:

I have an update query that I had to rewrite as a raw query, because the knex query builder ignored .limit(1).  "LIMIT 1" is a valid portion of an update command, at least for MySQL, as my raw query has proven. 

Very respectfully,
Rich

PS: I saw knex added a raw order by; great job!  Wish I had it a month ago.

**Comment by moll** [comment]
Is it me or does this, that is, ignoring `LIMIT`, still happen with PostgreSQL?

**Comment by tgriesser** [comment]
@moll afaik `LIMIT` isn't supported in update commands https://www.postgresql.org/docs/9.1/static/sql-update.html

**Comment by moll** [comment]
You're right. I didn't even humor the idea that this isn't supported on PostgreSQL. 😇 Thanks!
