### ISSUE TITLE
db migration file naming conventions

### ISSUE THREAD

**Issue by mrdulin** [knex/knex#3504]
This question is primarily opinion-based so that I can't ask on stackoverflow. It confuses me a long time. Here are the naming conventions I had tried.

### `datetime_[action]-[tableName]`

E.g.

`20190116143040_update-CAMPAIGN_RESULT`
`20190225151200_createTable-google_account`
`20190227190440_alterTable-LOCATION`

Cons: If you look at the file name, you don't know what operations this migration file does. Does it add a column, or alter a column, you don't know it.

### `datetime_[action]_[column]-to-[tableName]`

E.g.

`20190318100751_add_user_id_to_subscriptions_table`
`20190506155452_add_notifycation_type_enum_value_to_NOTIFICATION`

Cons: What about the migration is related with multiple columns and tables? The file name will become very long if I describe each migrate operations.

### `datetime_[jira task id]`

E.g.

`20191029135426_task-2745`

Cons: It's same with the first way. You don't know what migrate operations this file does. You need open this file and check the code.

For now, the file names of my knex db migration files are totally messed up.
Please give me some advices about the naming conventions of knex migration file. Is there any best practise for this? Thanks a lot!

**Comment by ricardograca** [comment]
You're always going to have to open the file to check the details, so go with whatever you prefer. I would never go with `datetime_[jira task id]` though, because then you have absolutely no idea what it does, whereas with the other options it's easy to know at least what table it touches.

**Comment by lorefnon** [comment]
I usually prefer [datetime]_[data/schema]_[tables] where tables is alphabetically sorted dunder separated names of tables affected.

**Comment by elhigu** [comment]
Knex does not have any opinion how you should name these. Except that it will run them in alphabetical order. I personally do `<datetimestamp>_feature-name-to-which-migration-relates` or `<datetimestamp>_tell-what-migration-does`.

Anyways I usually just use search to see all actions done to a table...
