### ISSUE TITLE
RequestError: Connection lost - read ECONNRESET

### ISSUE THREAD

**Issue by sonalirhcl** [knex/knex#3508]
# Environment

Knex version: 0.15.2
Database + version:  Microsoft SQL + 12.0
OS: ubuntu 16.04

Select applicable template from below.
@ smorey2 , @ lorefnon

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
unpredictable works at windows 10 system fine that is on my local not on dev environment which is at azure with ubuntu 16.04

2. Error message
RequestError: Connection lost - read ECONNRESET
   at handleError (/src/node_modules/mssql/lib/tedious.js:519:15) 
   at Connection.emit (events.js:203:15)
   at Connection.socketError (/src/node_modules/tedious/lib/connection.js:1028:14)
   at Socket.<anonymous> (/src/node_modules/tedious/lib/connection.js:878:18)
   at Socket.emit (events.js:203:15) 

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

# Feature discussion / request

1. Explain what is your use case
I have 4 tables Order,LineItem,Shipment,ShipmentQuantity having some relationship between them which are mention below

ShipmentQuantity table and its relationship
// order table column 
static get jsonSchema() {
return {
  type: 'object',
  required: ['shipmentId', 'lineItemId', 'quantity'],
  properties: {
    id: { type: 'number' },
    shipmentId: { type: 'number' },
    lineItemId: { type: 'number' },
    quantity: { type: 'number' },
   },
  };
 }
 // table relation-ship 
 static get relationMappings() {
     return {
     lineItem: {
      relation: Model.BelongsToOneRelation,
       modelClass: __dirname + '/LineItem',
      join: {
         from: 'ShipmentQuantity.lineItemId',
         to: 'LineItem.id',
       },
      },
    shipment: {
      relation: Model.BelongsToOneRelation,
      modelClass: __dirname + '/Shipment',
      join: {
        from: 'ShipmentQuantity.shipmentId',
        to: 'Shipment.id',
      },
     },
    };
   }
  }
Shipment table and its relationship
// Shipment table column 
 static get jsonSchema() {
 return {
   type: 'object',
   required: ['orderId', 'status'],
   properties: {
    id: { type: 'number' },
    orderId: { type: 'number' },
   },
 };
}
 // table relation-ship 
 static get relationMappings() {
   return {
    shipmentQuantities: {
    relation: Model.HasManyRelation,
    modelClass: __dirname + '/ShipmentQuantity',
     join: {
        from: 'Shipment.id',
        to: 'ShipmentQuantity.shipmentId',
      },
     },
   };
  }

LineItem table and its relationship

static get jsonSchema() {
    return {
      type: 'object',
       properties: {
           id: { type: 'number' },
           orderId: { type: 'number' },    
           quantitySupplied: { type: 'number' },
           name: { type: 'string' },
           amount: { type: 'number' },
           currency: { type: 'string' },
         },
       };
       }

    static get relationMappings() {
     return {
       order: {
       relation: Model.BelongsToOneRelation,
       modelClass: __dirname + '/Order',
        join: {
          from: 'LineItem.orderId',
          to: 'Order.id',
         },
        },
       shipmentQuantities: {
        relation: Model.HasManyRelation,
        modelClass: __dirname + '/ShipmentQuantity',
        join: {
         from: 'LineItem.id',
         to: 'ShipmentQuantity.lineItemId',
      },
     },
    };
   }

Order table and its relationship

static get jsonSchema() {
    return {
      type: 'object',
      properties: {
      id: { type: 'number' },
      supplierId: { type: 'number' },
      siteId: { type: 'number' },
      supplierName: { type: 'string' },
      comment: { type: 'string' },
      orderRef: { type: 'string' },
      total: { type: 'number' },   
      purchaseOrderNumber: { type: 'string' }
     },
    };
   }

  static get relationMappings() {
   return {
    lineItems: {
    relation: Model.HasManyRelation,
    modelClass: __dirname + '/LineItem',
    join: {
      from: 'Order.id',
      to: 'LineItem.orderId',
    },
   },
  shipments: {
    relation: Model.HasManyRelation,
    modelClass: __dirname + '/Shipment',
    join: {
      from: 'Order.id',
      to: 'Shipment.orderId',
    },
  },
  orderShipments: {
    relation: Model.HasManyRelation,
    modelClass: __dirname + '/OrderShipments',
    join: {
      from: 'Order.id',
      to: 'OrderShipments.orderId',
    },
   },
  };
 } 

According to above relation I am trying to fetching some data for a particular order with a specific order id and the query is given as below

Order.query()
.joinEager('[shipments.shipmentQuantities.lineItem, lineItems.shipmentQuantities]')
.findById(id);
It gives me error at dev environment connection lost while similar query if I replace joinEager with eager then it would works perfectly at dev environment can anyone tell me that is because of joinEager and eager then what's the difference between it or somthing else that i missed

# Missing / erroneus documentation
Did not get the exact error message why connection lost on joinEager and what eager actually do
what happens that in this case eager works easily at dev environment no worked with joinEager

**Comment by elhigu** [comment]
Sorry. Cannot reproduce, nor understand this report. 

Please try to reduce the reproduction code of your problem to be runnable single file test code (without objection). Can be reopened if someone understands what is this about...
