### ISSUE TITLE
Dialect Firebird

### ISSUE THREAD

**Issue by Level0r0s** [knex/knex#3511]
please .Firebird support must be included in the official distribution.

Look
https://github.com/igorklopov/firebird-knex

https://github.com/FraGoTe/knex/tree/master/lib/dialects/firebird

**Comment by kibertoad** [comment]
Please check out https://github.com/knex/knex/blob/master/CONTRIBUTING.md:
```
Currently there are already way too many dialects supported in knex and instead of adding new dialect to central codebase, all the dialects should be moved to separate npm packages out from knex core library with their respective maintainers and test suites.
```

Please let us know if there are any issues with maintaining these dialect modules due to some Knex implementation details, maybe we can provide some additional flexibility if needed.
