### ISSUE TITLE
Build - Warning messages about missing mysql and sqlite peer

### ISSUE THREAD

**Issue by jeremychone** [knex/knex#3512]
# Environment

Knex version: 0.20.1
Database + version: Postgresql
OS: Mac, Linux

# Feature discussion / request

1. Explain what is your use case

We are using knex with Postgresql, but somehow on "npm install knex" we get the following messages: 

```
npm WARN knex@0.20.1 requires a peer of mssql@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of mysql@^2.17.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of mysql2@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of sqlite3@^4.1.0 but none is installed. You must install peer dependencies yourself.
```

This seems to have been there since 0.20, but not sure. 

We are using postgres and those are warning messages for the developers or the DevOps on the projects. Also, not sure why I am not getting similar messages for all other databases supported by Knex that I am am not using (and do not have the peer driver installed). 

2. Suggestion

I can see the value of those types of warning, but the confusion and extra noise it creates for everybody not using mysql or sqlite might not make it worthwhile. 

If the decision is to keep those messages, we will have to make a documentation note for our dev / devops and hope they read or find it when they get confused about these messages. Not the end of the world, but another thing to educate dev and devops. Also, in this case, I would love to understand why we get those messages only for mysql and sqlite, and not Oracle for example, which I assume knex needs a "driver / peer package" as well. 

Side Note: We are a big fan of Knex.js, so, we will respect whatever decision but just wanted to voice our point of view.

**Comment by kibertoad** [comment]
@jeremychone Which version of yarn/npm are you using? I think this is related to https://github.com/knex/knex/pull/3081 and should be resolved by upgrading your package manager.

**Comment by jeremychone** [comment]
@kibertoad npm 6.12.1, seems to be the latest. 


```
.../ (master *)$ npm install knex
...
npm WARN knex@0.20.1 requires a peer of mssql@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of mysql@^2.17.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of mysql2@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of sqlite3@^4.1.0 but none is installed. You must install peer dependencies yourself.
...

+ knex@0.20.1
added 39 packages from 55 contributors and audited 3393 packages in 3.174s
found 0 vulnerabilities

.../ (master *)$ npm -v
6.12.1
```

**Comment by kibertoad** [comment]
@jeremychone Fixed upstream: https://github.com/npm/pacote/commit/7a400d3b4172d04d90d1699958c14b137bf93411

**Comment by jeremychone** [comment]
@kibertoad Thank you very much for this amazing responsiveness. Will check it out in next release.

**Comment by kibertoad** [comment]
@jeremychone You are welcome! I've submitted PR to npm project, hopefully they'll pick it up for the next release.

**Comment by kibertoad** [comment]
@jeremychone Can you try again with npm 6.13.0?

**Comment by mastermatt** [comment]
I am still seeing this output on npm 6.13.0

**Comment by jeremychone** [comment]
@kibertoad Sorry for the delay. As the comment above, still see it: 

```sh
$ npm -v
6.13.0

$ npm install knex
npm WARN knex@0.20.1 requires a peer of mssql@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of mysql@^2.17.1 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of mysql2@^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN knex@0.20.1 requires a peer of sqlite3@^4.1.0 but none is installed. You must install peer dependencies yourself.


+ knex@0.20.1
added 39 packages from 55 contributors and audited 3426 packages in 3.231s
```

**Comment by kibertoad** [comment]
@jeremychone @mastermatt  OK, it could be that it needed to be published with newer npm. Can you please try 0.20.2 and see if you still get it?

**Comment by mastermatt** [comment]
0.20.2 no longer prints the warning for me with npm 6.13.0. Thanks

**Comment by kibertoad** [comment]
Thank you for reporting back!

**Comment by jeremychone** [comment]
Yep, same here, knex 0.20.2 with npm 6.13.0 does not print the warnings.

**Comment by kibertoad** [comment]
You are welcome!

**Comment by oteroleonardo** [comment]
knex 0.21.1 still prints the warning.

**Comment by alasdairhurst** [comment]
Still seeing this on npm 6.14.8 using knex 0.21.12

**Comment by kibertoad** [comment]
@alasdairhurst can you check if 0.20.2 prints warnings for you?

**Comment by alasdairhurst** [comment]
0.20.2 and 0.20.15 both don't print out the warnings with the same version of npm.

**Comment by kibertoad** [comment]
@alasdairhurst Thanks, I'll take a look at what changed since then.

**Comment by kibertoad** [comment]
@alasdairhurst There shouldn't be a meaningful differences. Here are relevant sections from package.json of 0.20.15 vs 0.21.12:

```
  "peerDependencies": {
    "mssql": "^6.1.0",
    "mysql": "^2.18.1",
    "mysql2": "^2.1.0",
    "pg": "^7.18.2",
    "sqlite3": "^4.1.1"
  },
  "peerDependenciesMeta": {
    "mssql": {
      "optional": true
    },
    "mysql": {
      "optional": true
    },
    "mysql2": {
      "optional": true
    },
    "pg": {
      "optional": true
    },
    "sqlite3": {
      "optional": true
    }
  },
```

```
  "peerDependencies": {
    "mssql": "^6.2.1",
    "mysql": "^2.18.1",
    "mysql2": "^2.1.0",
    "pg": "^8.3.0",
    "sqlite3": "^5.0.0"
  },
  "peerDependenciesMeta": {
    "mssql": {
      "optional": true
    },
    "mysql": {
      "optional": true
    },
    "mysql2": {
      "optional": true
    },
    "pg": {
      "optional": true
    },
    "sqlite3": {
      "optional": true
    }
  },
```

As you can see, only versions are different, but metadata is pretty much the same. Can you share list of dependencies in your `package.json` and exact warning that you are getting?

**Comment by kibertoad** [comment]
Note the https://github.com/npm/cli/pull/1822/files -> I believe `peerDependenciesMeta` should suffice as per `npm` documentation.
