### ISSUE TITLE
Type Definitions: QueryBuilder type

### ISSUE THREAD

**Issue by EdwardSo-GBI** [knex/knex#3519]
# Environment

Knex version: 0.20.1
Database + version: postgreSQL 11

@lorefnon 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When using `knex(table).delete().where(column, 0)`, it returns a `QueryBuilder<Resource, number>` object. However, `number` doesn't seems to be an acceptable generic on `QueryBuilder`

2. Error message

 `Type '(resourceId: string) => QueryBuilder<Resource, number>' is not assignable to type '(resourceId: string) => QueryBuilder<any, any[]>'.`

**Comment by kibertoad** [comment]
Released in 0.20.2
