### ISSUE TITLE
Wrong data retrieving information from different tables together

### ISSUE THREAD

**Issue by amendezcabrera** [knex/knex#3522]
# Environment

Knex version: 0.20.1
Database + version: PostgreSQL 12.0.
OS: Debian 12 (DB) and Linux 4.14.148 (Boot2Docker) for the app

I'm retrieving data from two `many to many` related tables. I created a [sample project](https://github.com/amendezcabrera/knex-data-error) where I add three tables to the database, `dog`, `person` and `dog_person` which handles the relationship between both.
The `dog` table has an `integer array` (called `scores`) holding the dog scores individually and the `dog_person` table has the same column in order to keep the score of a dog and its owner. The use case is a fake one so it doesn't matter.
The problem cames when retrieving some data querying this scenario. if I try to fetch the dogs with an individual score of 5 and a score of 2 with his owner:

```
knex('dog_person')
        .join('dog', 'dog_person.id_dog', '=', 'dog.id')
        .join('person', 'dog_person.id_person', '=', 'person.id')
        .select('*')
        .whereRaw('2 = any(dog_person.scores) and 5 = any(dog.scores)')
```
This runs the next query:

> select * from "dog_person" inner join "dog" on "dog_person"."id_dog" = "dog"."id" inner join "person" on "dog_person"."id_person" = "person"."id" where 2 = any(dog_person.scores) and 5 = any(dog.scores)

The result of loading it right in the DB returns the next data:

| id | id\_dog | id\_person | scores | id | name | eye\_color | scores | id | name | surname |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | 1 | 1 | {2,3} | 1 | Charlie | Blue | {1,5,7} | 1 | Lucas | Jackson |

But when looking at the result returned by `knex` I get:
```
[ { id: 1,
    id_dog: 1,
    id_person: 1,
    scores: [ 1, 5, 7 ],
    name: 'Lucas',
    eye_color: 'Blue',
    surname: 'Jackson' } ]
```
As you can see the `ìd` is wrong and the `scores` field is missing some information. I think it could be a bug or I'm misunderstanding something.

I created a [repository ](https://github.com/amendezcabrera/knex-data-error)with a sample project right to load from Docker, just clone it and run `docker-compose up`, run the migrations and seeders and after hitting `http://localhost:8181/test` you will see the info in the logs.

I am facing no error just receiving what I consider the wrong data.
Thank you very much

**Comment by elhigu** [comment]
Sounds like you are hitting pg-driver functionality, where same column name from joined rows overrides original table's data.

You need to list manually fields that you like to get from joined tables:

```
.select('dog_person.*', 'dog.col1'. , 'dog.col2', 'person.col1', 'person.col2', ...)
```

**Comment by amendezcabrera** [comment]
Yes, I have been trying to do the same but using only the `pg` driver directly and it has the same behaviour, it seems that the JSON design is the guilty so we are going to manually require and alias the needed fields.
Thank you

**Comment by elhigu** [comment]
IIRC there is  actually some option which can be used to make driver to return row as an array of columns instead of an object, but it has not been tested how it works with knex. It actually might work anyways (though I wouldn't use it, since sounds like it would cause more inconvenience than it just having to list selected fields when joining).

**Comment by amendezcabrera** [comment]
> 
> 
> IIRC there is actually some option which can be used to make driver to return row as an array of columns instead of an object, but it has not been tested how it works with knex. It actually might work anyways (though I wouldn't use it, since sounds like it would cause more inconvenience than it just having to list selected fields when joining).

I gave it a try and the access to the data seems to be hardest than manually retrieving the required fields
