### ISSUE TITLE
Invalid types in 0.20.1

### ISSUE THREAD

**Issue by wtrocki** [knex/knex#3525]
# Environment

Knex version: 0.20.1
Database + version: Postgress 
OS: Macos

# Bug

 Migrating to 0.20.1 causing type error: 
`
Type '"then" | "catch" | "finally"' does not satisfy the constraint '"then" | "catch"'.
  Type '"finally"' is not assignable to type '"then" | "catch"'.
`
https://app.circleci.com/jobs/github/aerogear/graphback/1295

**Comment by wtrocki** [comment]
Upon investigation. Types from 0.20.1 will clash if the project uses @types/knex. 
Removing them will resolve problem.

**Comment by wtrocki** [comment]
Still happening

**Comment by elhigu** [comment]
That page is not found... sounds like you have invalid typings somewhere? For example if you are passing QueryBuilder's around pretending them to be promises. 

Can be opened if reproduction provided.

**Comment by lorefnon** [comment]
@wtrocki Is this happening only in Node 8 ?

**Comment by wtrocki** [comment]
@lorefnon Using node 10

**Comment by citycide** [comment]
This is also likely due to the TypeScript `target` or `lib` array in your tsconfig. You'll need to target `es2018` or newer, or include `es2018.promise` as a lib. `Promise.prototype.finally` is an ES2018 feature that only Node 10+ supports.

**Comment by lorefnon** [comment]
This should get fixed (by https://github.com/knex/knex/commit/af129408ca7173bfa0f4a777fb5d3206339cd634) once master is released.

**Comment by wtrocki** [comment]
@citycide Thank you so much! This was the issue. I have cleaned up types but only when I have added promise lib it started working.
