### ISSUE TITLE
Running tests within a transaction

### ISSUE THREAD

**Issue by JonAbrams** [knex/knex#353]
A common pattern for testing code in the Ruby world (using RSpec) is to run each of your app's tests within a transaction, and then rollback the transaction once the test is done. That way each test is run in an isolated environment and isn't filling up a db with junk.

Is there a way to do this with Knex? I've spent a few hours trying to make it work with mocha. The following don't seem to work:

``` javascript
beforeEach(function (done) {
  knex.raw("start transaction").then(function () {
    done();
  });
});

afterEach(function (done) {
  knex.raw("rollback").then(function () {
    done();
  });
});
```

or

``` javascript
var trx;
beforeEach(function (done) {
  knex.transaction(function (newTrx) {
    trx = newTrx;
    done();
  });
});

afterEach(function (done) {
  trx.rollback().then(function () {
    done();
  });
});
```

I apologize if this question is naïve but I'm new to knex.

**Comment by StephanHoyer** [comment]
you don't event have to rollback since not commiting is an automated rollback.

What I learned today after hours of debugging is that mysql does not rollback `auto_increment` columns :(

**Comment by StephanHoyer** [comment]
@JonAbrams you have to take care that all queries that are executed during the test are run within this transaction.
```javascript
describe('stuff', () => {
  var trx = knex;
  beforeEach(function (done) {
    knex.transaction(function (newTrx) {
      trx = newTrx;
      done();
    });
  });

  it('should work', function () {
    return trx('table_name').insert(data);
  });
});
```

**Comment by flushentitypacket** [comment]
@JonAbrams Thanks!

The problem is when you need to test code that opens its own transaction. (Transactions within transactions are not allowed in postgresql 😢 )

**Comment by JonAbrams** [comment]
@flushentitypacket See the [above comment](https://github.com/tgriesser/knex/issues/353#issuecomment-47854969) maybe it can help you?

**Comment by elhigu** [comment]
@flushentitypacket knex has implemented nested transactions with save points (should work also with postgres)

**Comment by soubhikchatterjee** [comment]
I have switched to Sequelize after having so much issues with knexjs. I am now a happy Sequelize user :)

**Comment by elhigu** [comment]
@soubhikchatterjee good for you, I hope it suits well for your needs 🙂 In my opinion knex is way too low level library to be used directly in app development anyways.

**Comment by gjstreicher** [comment]
@flushentitypacket I figured out a way to do this with similar code as shown by @JonAbrams

```JavaScript
describe('Test suite', async () => {
  let trx;

  beforeEach(async () => {
    trx = await knex.transaction();
  });

  afterEach(() => {
    trx.rollback();
  });
  
  it('Individual test', async () => {
    const bar = trx('sometable').insert({ non_default_property: 'foo' }).returning('*');
    console.log('bar:', bar);
  });
```

You can pass the transaction (`trx`) to functions that need to make use of it.
