### ISSUE TITLE
MSSQL database with json query doesn't work

### ISSUE THREAD

**Issue by galkatz373** [knex/knex#3530]
I'm trying to query json with knex and it doesn't work,
It does work with regular sql query.
I'm using MSSQL

Example to query that doesn't work:
`knex("versions").select("JSON_QUERY([Data], '$')")`

**Comment by elhigu** [comment]
You need to use knex.raw like when calling functions.

```
knex("versions").select(knex.raw("JSON_QUERY([Data], '$')"))
```
