### ISSUE TITLE
Update if it exists, otherwise insert

### ISSUE THREAD

**Issue by RayZoey** [knex/knex#3533]
Knex version:
0.19.5
Database + version:
Postgre

Hi there,i have some question,when i use knex 'insert' or 'batchinsert',i don't know how to create or update
1.if the record is exist, i want to update them or ignore
2.if the record is not exist, i want to insert them

Does anyone have a simple plan? Thanks.

**Comment by RayZoey** [comment]
i don't want use raw

**Comment by elhigu** [comment]
You need to first select row for update in transaction, if no results do insert with .insert(...) if it did exist update needed columns with .update(...). There is no support for on conflict feature of postgres.


Related feature request: https://github.com/knex/knex/issues/3186
