### ISSUE TITLE
Migration doesn't rollback after failed on OracleDB

### ISSUE THREAD

**Issue by vukhoa30** [knex/knex#3534]
Knex version: 0.20.1
Database + version: OracleDB 18.3.0
OS: Ubuntu
The issue is about oracledb support, tagging @atiertant

Hello knex team, my app is supporting Postgresql and already using several migration files. Now I'd like it to support OracleDB as well, and see an issue when trying to do the migrations.
When I executed a migration file, it failed midway but the scripts executed before that didn't rollback, as I can see it does with Postgres. For example, the migration file creates 5 tables but it fails at the 3rd table, then the two first table should be dropped.
Is there anything I can do to make it behaves like with Postgres?

Thanks for your support and sorry for my bad English.

**Comment by elhigu** [comment]
Oracle DB like mysql does auto commit after each query that changes schema https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_1001.htm#SQLRF30001 . So schema updates cannot be rolled back automatically with those databases. You need to add error handling manually.

If you want a generic way to be able to rollback failed migration on oracle/mysql/sqlite you will need to take backup dump of the DB before running migration and if migration fails to restore that backup.
