### ISSUE TITLE
knexfile migration path not working properly when in subfolder

### ISSUE THREAD

**Issue by pepsivontwist** [knex/knex#3535]
# Environment

Knex version: 0.19.5
Database + version: SQLITE3 
OS: OSX 10.14.6

Knexfile:

```
// Update with your config settings.
require('dotenv').config();

module.exports = {
  development: {
    client: 'sqlite3',
    useNullAsDefault: true,
    connection: {
      filename: './dev.sqlite3'
    },
    migrations: {
      directory: "./migrations"
    }
  },
  production: {
    client: 'mysql2',
    connection: {
      host: process.env.DB_HOST,
      database: process.env.DB_NAME,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'migrations'
    }
  }
};
```

# Bug
Knexfile is in `config/knexfile.js`

When running knex migrate from CLI in the root folder with a path to the knexfile, it uses the migration path relative to the knexfile, which is incorrect.

When running the application and passing the knexfile contents to knex when initializing, it uses the migration path relative to the project root folder, which is correct.

Tried using the `cwd` parameter to change this when running it from CLI , it seems to be working relative to the actual process cwd; However the migration path is again always relative to the knexfile location.

Expecting it to always use the path relative to the current working directory.

**Comment by lorefnon** [comment]
> Expecting it to always use the path relative to the current working directory.

I don't think this is desirable. This will always require people to run knex cli from the project root where as currently I can run a run knex commands wherever I am in the directory tree.

In general having relative paths behave same as require is a reasonable choice IMHO.

**Comment by pepsivontwist** [comment]
The issue here is that it's not behaving in a consistent way.

**Comment by tsheaff** [comment]
@pepsivontwist Why was this closed?

I run into this issue, because my `.env` with my local environment variables, are in the project root, and they only get recognized when I run a command like `knex migrate:make create_waitlist_users --knexfile=./src/libs/db.ts` if I copy the `/.env` to `/src/libs/.env`. This is frustrating and not expected behavior.

**Comment by EliasInfnet** [comment]
I solved this problem by placing knexfile where it would normally be used in the application ( `src/config/knexfile.js` ) and using an auxiliary file at the root ( also `knexfile.js` ) , just importing `import knexConfig from src/config/knexfile.js` and directly exporting. This way, when I run `npx knex migrate:make initial`, migrations directory is placed in the right spot. And I can still use the same config in the application `knex(knexfile.development).migrate...` using knexfile from subfolder `src/config/knexfile.js`
