### ISSUE TITLE
How to get multiple error happening records from a btach insert?

### ISSUE THREAD

**Issue by z3us94** [knex/knex#3540]
Environment

Knex version: 0.20.2
Database + version: postgres 9.6
OS: Ubuntu 18.4

# Questions about how to use knex

Hey guys, 
My problem is that im doing batch insert to a table where it has a composite key. What i want is when there is an instance where one record is in the DB and duplicate records getting entered, get the duplicate records that fails from the error. But all im getting is the first record that error being thrown. Is it possible to get all the failing records from the error ? or is there a workaround ?

Below is a code snipped of my query

`await Bookshelf.knex.batchInsert('invites', mapped, 1000);`

and below is what im getting. Im just getting one record as an error.
![Screenshot from 2019-11-18 10-51-35](https://user-images.githubusercontent.com/17064184/69026571-73a23500-09f1-11ea-8422-a787ac7c30e5.png)

**Comment by elhigu** [comment]
No, there is no way to get all errors. I'm not even sure if it is possible in SQL to do since multiple rows are added with single query and on first error all rows in the query are rolled back. batchInsert is meant to either successfully insert everything or insert nothing.
