### ISSUE TITLE
Use leftJoin with condition in inside on;

### ISSUE THREAD

**Issue by jsilveira2** [knex/knex#3543]
# Environment

Knex version: ^0.16.3
Database + version: postgres 
OS: Windows 10

# Doubt

1. I need make a select using left join with multiple conditions inside on;
2. One of this conditions needs to be: column in array;

My sql: **SELECT * FROM table1 LEFT JOIN table2 ON(table1.columnA in (1, 2, 3, 4, 5));**

My attempt at: **knex.select('*').from('table1').leftJoin('table2', function({
  this.on('table1.columnA', 'in', [1, 2, 3, 4, 5]);
});**

Result of knex executation: **The operator "in" is not permitted at Formatter.operator (/app/node_modules/knex/lib/formatter.js:179:13);**

I tryed the find a solution for this in documentation but i not found; If someone can help me 
I appreciate it;

Obs: Sorry for any english error;

**Comment by elhigu** [comment]
http://knexjs.org/#Builder-onIn
