### ISSUE TITLE
oracledb transaction

### ISSUE THREAD

**Issue by maximelkin** [knex/knex#3555]
# Environment

Knex version: 20.3 and older
Database + version: oracle
OS: any

Select applicable template from below.
@atiertant 

# Bug

1. Incorrect behavior for failed to commit transaction
commit error will trigger unhandled rejection
https://github.com/knex/knex/blob/1ca7bc2f2b1e683d60bb906cf182d3010c3ecde3/lib/dialects/oracledb/transaction.js#L70

**Comment by maximelkin** [comment]
Also not sure this._rejecter(err) call is needed, because disposer will be called only after executionPromise (see lib/transaction.js) fulfilling

**Comment by atiertant** [comment]
@maximelkin do you have some code to reproduce a bug?

**Comment by maximelkin** [comment]
Nope, I found it by just looking at code

**Comment by maximelkin** [comment]
commitAsync always resolved with undefined (see https://github.com/knex/knex/blob/1ca7bc2f2b1e683d60bb906cf182d3010c3ecde3/lib/dialects/oracledb/index.js#L109)

and commitAsync rejection not handled

**Comment by kibertoad** [comment]
@maximelkin I think https://github.com/knex/knex/pull/3606 addresses specifically that. Is that correct?

**Comment by maximelkin** [comment]
@kibertoad yes, this can be closed
