### ISSUE TITLE
Knex 0.20.3 knexFactory type is a non-promise value

### ISSUE THREAD

**Issue by jpike88** [knex/knex#3559]
# Environment

Knex version: 0.20.3

I'm getting errors all over the place like this:

```
Invalid 'await' of a non-Promise value.
```

The knexFactory variable type seems to be broken.

**Comment by jpike88** [comment]
Would be nice to add some type tests to the test suite as this is a pretty fundamental way to break

**Comment by elhigu** [comment]
Policy is that each fix actually should have regression test included.

**Comment by hansnull** [comment]
BTW: Knex version 0.20.1 and 0.20.2 have the same problem.

**Comment by kibertoad** [comment]
@jpike88 Can you provide some example code that fails to build for you?

**Comment by jpike88** [comment]
Typescript 3.6.3

```
import knexFactory from 'knex';

let knex: knexFactory;

const knexConfig = {
		client: 'mysql',
		connection: 'wat',
		asyncStackTraces: true,
		longStackTraces: true
	};
knex = knexFactory(knexConfig);

const baseQuery = knex('plant_make')
			.join('plant_model', 'plant_make.id', 'plant_model.makeID')
			.where('plant_make.category', this.params.plantCategory)
			.where('plant_make.category', 'plant')
			.where('plant_model.active', 1)
			.where('plant_make.active', 1)
			.where('plant_model.pending', 0)
			.where('plant_make.pending', 0);

		const makeModelsJoined = await baseQuery
			.select(
				'plant_model.label as modelLabel', 'plant_model.id as modelID',
				'plant_make.label as makeLabel', 'plant_make.id as makeID'
			)
			.orderBy('plant_make.label')
			.orderBy('plant_make.id')
			.orderBy('plant_model.label')
			.orderBy('plant_model.id');

```


![Screen Shot 2019-12-06 at 10 21 33 am](https://user-images.githubusercontent.com/9585787/70292930-3374ec00-1812-11ea-9e5f-5a8c43874e42.png)

**Comment by lorefnon** [comment]
TSlint can be configured to allow thenables other than Promise. 

From their docs: 

> Note that this rule doesn’t check for type assignability or compatibility; it just checks type reference names.

So something like: 

```
"await-promise": [true, "QueryInterface", "QueryBuilder"]
```

should fix this.

**Comment by jpike88** [comment]
I already account for type “thenable” in my tslint, wasn’t this how it’s supposed to work

**Comment by lorefnon** [comment]
As the quoted part of the docs states, the tslint rule just compares by name. So specifying `Thenable` wouldn't work unless we use a type named `Thenable` which we currently don't. 

We recently stopped using the Promise type (https://github.com/knex/knex/issues/3422) so this would have started failing for you after that. Technically though, what knex query builder returned was never a promise.

**Comment by hansnull** [comment]
> Technically though, what knex query builder returned was never a promise.
This seems to be confusing, as a developer I would expect a promise.

**Comment by lorefnon** [comment]
> This seems to be confusing, as a developer I would expect a promise.

You you write `knex('foo')` you can either await on it directly, or continue building the chain further down `knex('foo').select(['col'])`. This makes APIs much more convenient. 

If you really want a promise, you can call `chain.then()` when you are done.
