### ISSUE TITLE
Preload dotenv with commandline argument

### ISSUE THREAD

**Issue by a2937** [knex/knex#3560]
# Environment

Knex version: 0.20.3
Database + version: Postgres Sql 
OS: Windows

# Feature discussion / request

1. Explain what is your use case
Recently I found out that I am able to preload my dotenv file via the require argument when running my node application. It has actually been preferred to do this according to the dotenv development team. 
`"node -r dotenv/config your_script.js"`

Unfortunately I cannot have pass that sort of thing as an argument to the knex command-line utility. Nor can I try to pass it in through the npx runner and have it preload that way. No values are loaded.  

2. Explain what kind of feature would support this
My feature request would affect only the command-line utility rather than the main codebase and offer some form of convenience for developers. 

3. Give some API proposal, how the feature should work
I suggest adding a commandline flag option of "--dotenv" or "-de" to be passed in as an option into Knex and adding dotenv as a dependency of Knex but it would make development way more convenient.

**Comment by kibertoad** [comment]
Sounds good! Would you be open to submitting a PR for this?
