### ISSUE TITLE
Debugging is turned on by default and can not be turned off.

### ISSUE THREAD

**Issue by poliha** [knex/knex#3570]
# Environment

Knex version: 0.20.3
Database + version: postgresql 11.5
OS: mac

I am not sure if this a bug or by design, but it seems that debugging is always on and you can't turn it off.  The documentation says
>Passing a debug: true flag on your initialization object will turn on debugging for all queries.

So I expect that if this flag is not passed, I should not get debug messages. But this is not the case.  These messages can be overwhelming. Its hard to keep up when running migrations for tests.

Is there any other way to turn this off? Thanks

**Comment by elhigu** [comment]
Please add your reproduction code / output prints. I have never seen debug prints if I haven't asked for them. Closing until more info is provided.
