### ISSUE TITLE
knex_migrations already exists

### ISSUE THREAD

**Issue by jerinseba** [knex/knex#3575]
# Environment

Knex version: 0.16.3
Database + version: PostgreSQL 10.6
OS: alpine (docker)

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I have added a new migration file to create a new table in the existing Database which was previously migrated using Knex. But the migration (**knex.migrate.latest()**) is throwing an error as given below.
Deployment: Blue-Green Deployment

2. Error message

Unhandled rejection error: relation \"knex_migrations\" already exists

**Comment by elhigu** [comment]
This needs information about your knex config and existing DB schema (where is that knex_migration table that knex doesn't notice, but which prevents from re-creating it).

**Comment by kibertoad** [comment]
@jerinseba What could be happening is that you used schema name as a part of tableName parameter for migrations. This is no longer valid. Instead, use explicit schemaName parameter. See https://github.com/knex/knex/pull/2559/files

**Comment by jerinseba** [comment]
@elhigu, @kibertoad Thanks for the quick reply. Please find the configuration below.

migrations: {
    directory: __dirname + "/migrations",
    schemaName: "public",
    tableName: "knex_migrations"
  },

The application is using a different schema.

**Comment by jerinseba** [comment]
config/knexfile.js
```
const constants = require("./database_constants.js");

module.exports = {
  client: "postgresql",
  connection: {
    database: constants.DATABASE.database,
    host: constants.DATABASE.host,
    password: constants.DATABASE.password,
    user: constants.DATABASE.user
  },
  migrations: {
    directory: __dirname + "/migrations",
    schemaName: "public",
    tableName: "knex_migrations"
  },
  pool: {
    max: 10,
    min: 2
  },
  seeds: {
    directory: __dirname + "/seeds"
  }
};
```

app.ts
```
import * as knexConfig from "../config/knexfile";

const knex = require("knex")(knexConfig);

knex.migrate
.latest()
.then(() => {
  return knex.seed.run();
})
```

**Comment by elhigu** [comment]
Thanks! When you look your database in which schema that `knex_migrations` table is?

**Comment by jerinseba** [comment]
It is there in public schema.

**Comment by kalianto** [comment]
This is still an issue, especially where the client is `mssql` 
knexfile,js
```
module.exports = {
  sqldev: {
    client: 'mssql',
    connection: {
      host: process.env.SQL_HOST,
      user: process.env.SQL_USER,
      password: process.env.SQL_PSWD,
      database: process.env.SQL_DB,
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      directory: `${__dirname}/sql-migrations`,
      tableName: `${process.env.SQL_SCHEMA}.knex_migrations`,
      schemaName: process.env.SQL_SCHEMA,
    },
    seeds: {
      directory: `${__dirname}/seeds`,
    },
    debug: true,
  },
};
```

When running `knex migrate:latest --env sqldev` for the first time,
knex will check for the table `schema.knex_migrations`, using `hasTable()` function, and it will return false, and then it will proceed with creating the `knex_migrations` table in the schema defined in `SQL_SCHEMA`

However, when executing the migration file in the directory specified in the `migrations` config,
knex will check if the migration files are already in the knex_migrations table, but it uses
`schema.schema.knex_migrations` instead of `schema.knex_migrations`

So the `schemaName` and `tableName` (prepended with schemaName) will not work.
However, if we remove the schema prefix in the `tableName`, knex will not create knex_migrations table. 

So it won't work.

**Comment by kibertoad** [comment]
@kalianto This sounds like it is working the way it should, though.

```
    migrations: {
      directory: `${__dirname}/sql-migrations`,
      tableName: `schema1.knex_migrations`,
      schemaName: 'schema1',
    },
```
is wrong, `tableName` should not include `schema1`. And `schemaName` for this configuration only defines where `knex_migrations` is stored, nothing else, as you might want to modify different schemas within same migrations file, and `knex.schema.withSchema('schema1').createTable('users', ...``` is correct way to do that.

**Comment by kalianto** [comment]
@kibertoad Thank you for your reply.
Apparently, my knex version is 0.14, and after upgrading to version 0.20, I use this configuration
```
migrations: {
  directory: `${__dirname}/sql-migrations`,
  tableName: 'knex_migrations',
  schemaName: 'schema1',
}
```
knex correctly adds the `schema1` schema to `knex_migrations` table and successfully creating `knex_migrations` and `knex_migration_lock`. It works on `rollback` too.

> And schemaName for this configuration only defines where knex_migrations is stored, nothing else, as you might want to modify different schemas within same migrations file,

Yes, I understand this now. Thank you. 

Do you know if there is any way I can avoid doing this
```
knex.schema.withSchema('schema1').createTable('users', ...
```
and I can just do
```
knex.schema.createTable('users', ...
```
and it will automatically set to `schema1`. Is there a config option to set default schema? or maybe in knexfile.js? or after instantiating the knex object as below ?
```
const knex = require('knex')(config);
```

Thanks

**Comment by kibertoad** [comment]
@kalianto Not at this point. However, I see value in being able to specify default schema for knex instance; if you would be up to implement support for that, I would accept such PR.

**Comment by jerinseba** [comment]
Sorry for being late. Let me close this ticket. The issue was due to multiple containers trying to run the migration parallel.

**Comment by premsgr** [comment]
I am using mysql as client and stuck ion this error. Can you please share the solution @jerinseba

**Comment by Shahzad9722** [comment]
I am facing same problem . As my migrations are already created in code now I want to creat a new schema and convert migration into database . what should I have to to

**Comment by edgars-sirokovs** [comment]
> Sorry for being late. Let me close this ticket. The issue was due to multiple containers trying to run the migration parallel.

@jerinseba, I am facing the same issue on Postgres with the latest version. Can you please share the solution?

**Comment by diegopatinor** [comment]
I have migrated from Postgres 11 to 16 and I have the same issue.  Does anyone have the fix?
