### ISSUE TITLE
Custom migration source not working

### ISSUE THREAD

**Issue by MrToxy** [knex/knex#3576]
# Environment

Knex version: 0.20.4
Database + version: MySQL, latest
OS: MacOs Mojave

I'm using strapi alongside knex, however strapi doesn't create any migrations and when you edit a content type (Model) by deleting a property or renaming it, it doesn't delete the targeted property, it just creates a new one, and when you delete a model it doesn't actually delete the table on the database. 
This is really annoying because you'll end up with a lot of redundancies and unused tables and fields while developing.

What I'm doing is overriding the Strapi controllers that are responsible for creating, removing or updating a model and I want to be able to create a migration with the new schema on those controllers and then run it so I keep my database clean and up-to-date with strapi's models.

I know about the existence of `knex.migrate.make` however it doesn't seem to address my issue and the docs don't really tell you how to provide the migration fields to that function.

I was able to also find this http://knexjs.org/#custom-migration-sources however once again the docs are not very clear on what options I can provide and how to solve my issue.

So far this is what I have:

```javascript
class MyMigrationSource {
  // Must return a Promise containing a list of migrations.
  // Migrations can be whatever you want, they will be passed as
  // arguments to getMigrationName and getMigration
  constructor(name, attributes) {
    this.name = name
    this.attributes = attributes
  }
  getMigrations() {
    // In this example we are just returning migration names
    return Promise.resolve(['migration1'])
  }

  getMigrationName(migration) {
    return migration
  }

  getMigration() {
    return {
      up(knex) {
        return migrate.createTable(knex, this.name, this.attributes)
      },
      down(knex) {
        return knex.schema.dropTableIfExists(this.name)
      }
    }
  }
}
```
and then I create the migration:

```javascript
const migration = new MyMigrationSource(name, formatedAttributes)
 knex.migrate.make(`update_${name}_table`, {
          migrationSource: migration
    })
```

It creates a new migration file but the  content are simply empty functions:

```javascript

exports.up = function(knex) {
  
};

exports.down = function(knex) {
  
};
```

So my question is, isn't the source supposed to provide the configuration for knex to create the new migration? why is knex ignoring my configuration

**Comment by lorefnon** [comment]
My familiarity with Strapi is limited, so I may be somewhat wrong in inferring your use case. 

Also, what I don't have clarity is whether these changes to schema happen at development time or in the deployed application. 

At a high level, you have basically two options: 

1. Generate the source code that uses knex APIs for migrating tables using a template engine like liquid and invoke them through the CLI.

2. Populate some intermediate data source (like a json file, or a database table) which contains what changes have occurred (in a structured format that easy to generate) and then use a custom migration source that reads this json and translates it to Knex API.

This would look something like below (I haven't tested this): 

**changelog.json:**

```json
[{
   migrationId: 'add-col-bar-in-foo'
    tableName: 'foo',
    operation: 'addColumn',
    columnName: 'bar'
    columnType: 'varchar(max)'
}]
```

**migration-source.js:**

```
const fs = require('fs-extra');
const knex = require('knex');

class MyMigrationSource {
  // Must return a Promise containing a list of migrations. 
  // Migrations can be whatever you want, they will be passed as
  // arguments to getMigrationName and getMigration
  async getMigrations() {
    return fs.readJSON('changelog.json');
    return migrations.map(m => m.migrationId);
  }

  getMigrationName(migration) {
    return migration;
  }

  async getMigration(migration) {
      const migrations = await fs.readJSON('changelog.json');
      const migrationConfig = migrations.find(m => m.migrationId === migration);
      switch (migrationConfig.operation) {
          case ''addColumn":
              knex.schema.alterTable(migrationConfig.tableName, (t) => {
                  t.specificType(migrationConfig.columnName, migrationConfig.columnType)
              })
          // TODO Handle other operations here:
      }
  },
}
```


Also, I'd like to point out that some of the more advanced migration solutions like [liquibase](https://www.liquibase.org/) have a schema diffing feature, where you can point it to two databases and it can automatically identify the full set of changes to be made. Knex migration system is a very simple implementation and doesn't have similar features. You can of course use liquibase as a change management tool alongside knex.

**Comment by cronin4392** [comment]
@MrToxy did you find a solution for this? I want to do pretty much the exact same thing and cannot find any other resources on this. Thanks!

**Comment by RayanMM** [comment]
@MrToxy  did you come up with any solution? I'm struggling with the exact same issue. Thanks!

**Comment by MrToxy** [comment]
@cronin4392 @RayanMM Hi there, unfortunately I didn't find any solutions, after some time of opening this issue Strapi proved to be lacking some features we needed for the project at hand so we ended up dropping Strapi in favor of Adonis.
