### ISSUE TITLE
Time zone configuration is not used for insert causing dates to be inserted improperly

### ISSUE THREAD

**Issue by jordansoltman** [knex/knex#3577]
# Environment

Knex version: 0.16.3
Database + version: mysql 5.7
OS: MacOS 15.1

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When inserting into the database, knex ignores the timezone configuration and dates/times are always assumed to be local.

2. Error message

N/A

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
var knex = require('knex')({
        client: "mysql",
        connection: {
            ...,
            timezone: "UTC"
        },
);

const date = new Date(2019, 11, 10, 10)

await knex('table').insert([
    { date, name: "Pete" },
    { date, name: "Jeff" },
]);
```

If this code runs on a computer that is not in the UTC timezone, the inserted time is incorrect. The date string that should be in the insert query should be `'2019-12-10 18:00:00'` for a computer that is in the -08:00 offset, however, knex instead inserts the date as `'2019-12-10 10:00:00'`. 

I took a quick look through the source and it appears that in most/all? of the toQuery/toSQL calls (which do take a timezone as a parameter), the timezone from the configuration is not passed.

**Comment by elhigu** [comment]
Your problem is that when you create `new Date(...)` it is a local time.

```
// it is 09:53:24 AM here right now
> new Date()
2019-12-11T07:53:24.898Z
> a = new Date()
2019-12-11T07:53:27.323Z
> a.getTimezoneOffset()
-120
> 
```

So it doesn't matter what timezone you configure to your database driver. It affects only how data is returned from database and (maybe) how timestamps without timezone are inserted. Date object always has timezone info so by inserting `new Date(2019, 11, 10, 10)` you are telling DB that it should store '2019-11-10T10:00:00-08:00'. Generally `Date` objects are horrible to work with, you will be better off using for example Luxon for those.

**Comment by jordansoltman** [comment]
Thanks for the quick reply, but I still think it's a problem. I am creating a date intentionally in local time as an example. 

The knex implementation of dateToString (in the lib/query/strings.js file) which seems to be based off of the sql string library adds a line `const timeZone = ctx.timeZone || 'local';`. The problem is, that the timeZone is never passed down here so dates are **always** assumed to be local. This means that if I create a date in my local time zone (such as new Date()), it will get the hour, day, minute, for my local time. However, if I want the date to be stored in UTC, it should respect that. As the code is written there is no path to the `else` clause of the dateToString method.

```
function dateToString(date, finalEscape, ctx) {
  const timeZone = ctx.timeZone || 'local';


if (timeZone === 'local') {
    year = dt.getFullYear();
    month = dt.getMonth() + 1;
    day = dt.getDate();
    hour = dt.getHours();
    minute = dt.getMinutes();
    second = dt.getSeconds();
    millisecond = dt.getMilliseconds();
  } else {
    const tz = convertTimezone(timeZone);

    if (tz !== false && tz !== 0) {
      dt.setTime(dt.getTime() + tz * 60000);
    }

    year = dt.getUTCFullYear();
    month = dt.getUTCMonth() + 1;
    day = dt.getUTCDate();
    hour = dt.getUTCHours();
    minute = dt.getUTCMinutes();
    second = dt.getUTCSeconds();
    millisecond = dt.getUTCMilliseconds();
  }
```

**Comment by elhigu** [comment]
Could you add complete (runnable single file) reproduction code to show your problem exactly. Code shown in original post does work as it should. So you should add also the code for example schema creation to see complete picture what are you doing.

**Comment by elhigu** [comment]
Also I thing knex should not do any handling to date objects... it has been confusing for years that everything else is passed directly to the driver, but dates are handled differently... 😕

**Comment by jordansoltman** [comment]
Yes, it is quite confusing! But dates are a pain, so I'm not surprised it's a bit messy.

  I'll work on a fully executable example, but in the meantime will leave this for consideration.

With both mysql and knex using the exact same config, `{ connection: {   ..., timezone: "UTC" }, client: "mysql" }`

```
        const knexString = knexInstance('users').insert({
            date: new Date()
        }).toString();

        const connection = mysql.createConnection((config as any).connection);
        connection.connect(() => {
            connection.query('INSERT INTO `users` (`date`) values (?)', [new Date()], (err) => {
                console.log();
            })
        })
```

`knexString` is equal to `"insert into `users` (`date`) values ('2019-12-11 01:25:33.313')"` and the query that is run by the direct msyql driver call is `"INSERT INTO `users` (`date`) values ('2019-12-11 09:25:33.313')"`. You can see how mysql made the necessary conversion, and knex didn't. It seems to me that knex should mimic mysql's behavior. 

Like I said, I'll work on an executable example.

**Comment by jordansoltman** [comment]
Alright, I've put together some fully working code that reproduces the issue:

```
        const config = {
            client: 'mysql',
            connection: {
                host: '127.0.0.1',
                user: 'user',
                password: 'password',
                database: 'test',
                timezone: 'utc'
            }
        }

        const knex = require('knex')(config);

        const knexQuery = knex('users').insert({
            date: new Date()
        }).toString();

        const connection = mysql.createConnection(config.connection);
        connection.connect(() => {
            const query = connection.query('insert into `users` (`date`) values (?)', [new Date()], () => {})
            console.log("MySQL Driver Query", query.sql);
            console.log("Knex Query", knexQuery);
        });
```

If you run this on a computer **not** in the UTC timezone, you'll get something like this:

```MySQL Driver Query insert into `users` (`date`) values ('2019-12-11 16:25:34.552')```
```Knex Query insert into `users` (`date`) values ('2019-12-11 08:25:34.499')```

The dates being inserted are completely different with node mysql adjusting for the utc offset. If you remove the `timezone: utc` from the configuration, both dates come out exactly the same.

**Comment by elhigu** [comment]
Thanks! Opening this until I have time to check if that is expected or not.

**Comment by elhigu** [comment]
Looks like mysql driver does modify Date() objects according to timezone configurations 👍 So I would say that there is a bug in knex that it touches Date objects before passing them to the driver.

Here is also runkit which calls .toSQL().toNative() which is more close to the actual query that is ran https://runkit.com/mikaelle/5df12776671025001a63d3e2

Knex messes up Date object to string before passing it to the driver.  @wubzz @kibertoad any objections in changing this behaviour to leave also Date objects untouched? It might be quite significant breaking change for the people who has been using Date objects and had worked around this.

**Comment by kibertoad** [comment]
@elhigu I am fine with releasing this as a breaking change in next major version.

**Comment by jordansoltman** [comment]
Upon further review, knex is **not** modifying the dates before they go to the DB. It appears that the toString() method is what is incorrectly showing the dates.

**Comment by elhigu** [comment]
@jordansoltman Looks like you are right. 

> Here is also runkit which calls .toSQL().toNative() which is more close to the actual query that is ran https://runkit.com/mikaelle/5df12776671025001a63d3e2

I checked out again the bindings in that example and yup that date actually is an objects, I was also confused about how runkit printed out those date objects :)
