### ISSUE TITLE
error: "error running transaction query" is not throwing exception

### ISSUE THREAD

**Issue by Speedkore** [knex/knex#3583]
# Environment

Knex version:     "knex": "^0.20.4", "pg": "^7.14.0"
Database + version: PostgreSQL 11.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
OS: debian testing

This code below should return an exception while inserting a FK id that doesn't exists, instead executes trx.commit() and returns a silent debug error "trx1 error running transaction query". In the other hand, if one tries to insert duplicate in "test" table it performs as expected.

Seems that the DEFERRABLE INITIALLY DEFERRED is causing problems when using transactions, in any case the database log shows the error, and knex even tries to execute the commit without throwing exception. 

Am i'm missing something to avoid this silent error? Does the way i implemented the transaction with awaits is wrong?

**sql:**
```
CREATE TABLE test (
   id serial PRIMARY KEY,
   address VARCHAR (50) UNIQUE
);

CREATE TABLE test2 (
   id serial PRIMARY KEY,
   test_id INTEGER 
);

ALTER TABLE "test2" ADD CONSTRAINT "fk_test_constraint" 
FOREIGN KEY ("test_id") REFERENCES "test" ("id") DEFERRABLE INITIALLY DEFERRED;
```

**index.js:**
```
const Knex = require("knex");
const pg = require('pg');
const knex = Knex({
    client: "pg",
    dialect: 'postgres',
    connection: {
        host: '127.0.0.1',
        port: '5433',
        database: 'test',
        user: 'test',
        password: 'test',
    },
});


const knexTransaction = () => {
    return new Promise((resolve, reject) => knex.transaction(resolve).catch(reject))
};



const z = async() => {
    const trx = await knexTransaction();
    try {
        // const c = await trx("test").insert({
        //     address: "xxx",
        // });


        const p = await trx("test2").insert({
            test_id: 222222,
        });


        await trx.commit();
        console.log("bad, no exception thrown")
    } catch (e) {
        // console.log(e)
        await trx.rollback();
        console.log("good, exception thrown, rollback applied")
    }
}

(async () => {
    try {
        await z();
    } catch (e) {
        console.log(e)
    }
})();

```

**result:**
```
/data/knexbug$ DEBUG=* node index.js
  knex:tx trx1: Starting top level transaction +0ms
  knex:client acquired connection from pool: __knexUid2 +0ms
  knex:query BEGIN; trx1 +0ms
  knex:bindings undefined trx1 +0ms
  knex:query insert into "test2" ("test_id") values (?) trx1 +4ms
  knex:bindings [ 222222 ] trx1 +4ms
  knex:query COMMIT; trx1 +2ms
  knex:bindings undefined trx1 +2ms
  knex:tx trx1 error running transaction query +22ms
  knex:tx trx1: releasing connection +0ms
  knex:client releasing connection to pool: __knexUid2 +8ms
bad, no exception thrown
^C
```

**Comment by elhigu** [comment]
This might be a bug... but you are using knex transaction in a wrong way. You should also keep reference to the Promise returned by knex.transaction(...) call. 

Try this:

```
const z = async() => {
    try {
      await knex.transaction(async trx => {
          const p = await trx("test2").insert({
              test_id: 222222,
          });
      });
      console.log("bad, no exception thrown")
    } catch (e) {
      console.log("good, exception thrown, rollback applied")
    }
}

(async () => {
    try {
        await z();
    } catch (e) {
        console.log(e)
    }
})();
```

Also checkout `knex.transactionProvider` example from documentation. We should checkout from code, how trx.commit() and trx.rollback() actually works and clarify it in documentation. It might be that calling `await trx.commit()` should never throw an exception (for some complicated reasons).

**Comment by Speedkore** [comment]
Indeed your way works correctly and it would save me from missing to put a commit or a rollback. I will change my code everywhere with this way. And you are right again, a clear example as you showed me would be great in documentation, thanks a lot!

**Comment by elhigu** [comment]
Added issue about documentation to documentation repository.

**Comment by Louis-Tian** [comment]
While the transaction handler pattern can be used like above to avoid the error being swallow, but the transaction handler pattern is not universially applicable, like in the situationsof #5710 #3874. I think this is legit bug, can we please reopen this issue.
