### ISSUE TITLE
Lost bind messages while seeding large datasets

### ISSUE THREAD

**Issue by Lowhearth** [knex/knex#3584]
Bind message supplies less parameteres than required while seeding large datasets:

  `  bind message supplies 54542 parameters, but prepared statement "" requires 185614 `

I imagine this is a problem with the length of the query executed since the seeding data contains 18 000 ish rows,

Just wanted to know if my assumptions are correct and which will be the correct aproach for seeding such a large file.

Thanks

**Comment by elhigu** [comment]
Try to insert them in smaller batches. Databases has limitations how many bindings / how big statements can be sent to them in single query.
