### ISSUE TITLE
EDGE SCRIPT1028: SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by madeinspace** [knex/knex#3586]
# Environment

Knex version: 0.20.4
Database + version:
OS: windows 10

# Bug

1. Errors on Edge trying to run my Nextjs application

2.SCRIPT1028: SCRIPT1028: Expected identifier, string or number (client.js)

3.  initializePool(config = this.config) {
    if (this.pool) {
      this.logger.warn('The pool has already been initialized');
      return;
    }

    const tarnPoolConfig = {
      **...this.getPoolSettings(config.pool),** <-- on this line
    };
    // afterCreate is an internal knex param, tarn.js does not support it
    if (tarnPoolConfig.afterCreate) {
      delete tarnPoolConfig.afterCreate;
    }

    this.pool = new Pool(tarnPoolConfig);
  },

**Comment by elhigu** [comment]
Please add steps to reproduce the error. Doesn't sound like a knex problem. Can be re-opened if there are any reason to believe that this is a bug in knex.
