### ISSUE TITLE
Error: ORA-12154, could execute oracle database query

### ISSUE THREAD

**Issue by helxsz** [knex/knex#3587]
# Environment

Knex version: latest version
Database + version: oracle 11
OS: mac os

@atiertant 

i am using knex to work on an oracle database.here is my code to execute a sql query.

```
const knex = require('knex')({
  client: 'oracledb',
  connection: {
    host: 'c##xxx',
    user: 'xxxx',
    password: '120.79.238.xxx',
    database: 'orcl'
  }
});

executeRawQuery = function (SQL_QUERY) {

  return new Promise((resolve, reject) => {
    var data;
    try{
      console.log('executeRawQuery',SQL_QUERY);
      data = knex.select().from(knex.raw('(' + SQL_QUERY + ')'));
      resolve(data);
    }catch(err){
      console.log('fuck err ',err);
      reject(err);
    }
  });

};

var data = await executeRawQuery('SELECT x.ROWID,x.* FROM C##SCOTT120.XYC_SSO_ACCOUNT_STUDENT x WHERE rownum <= 300');
```

The code throws out an error saying

> { Error: ORA-12154: TNS:could not resolve the connect identifier specified
>     at Client_Oracledb.acquireRawConnection (/Users/abc/Documents/projects/game/server/node_modules/knex/lib/dialects/oracledb/index.js:79:27)
>     at create (/Users/abc/Documents/projects/game/server/node_modules/knex/lib/client.js:258:21)
>     at utils_1.tryPromise (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:389:34)
>     at Object.tryPromise (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/utils.js:53:24)
>     at Promise (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:389:17)
>     at new Promise (<anonymous>)
>     at callbackOrPromise (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:380:12)
>     at Pool._create (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:290:9)
>     at Pool._doCreate (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:260:36)
>     at Pool._tryAcquireOrCreate (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:211:18)
>     at Pool.acquire (/Users/abc/Documents/projects/game/server/node_modules/tarn/lib/Pool.js:117:14)
>     at Bluebird.try (/Users/abc/Documents/projects/game/server/node_modules/knex/lib/

any idea how to solve it? 

P.S. as i am using oracledb library, it is working very well. The code is shown below

```
async function initialize() {
  await oracledb.createPool({
       user : 'xxxx',
       password : 'oraclexxx',
       connectString : '120.79.xxx.xxx/orcl'
  });
}

function execute(statement, binds = [], opts = {}) {
  return new Promise(async (resolve, reject) => {
    let conn;
    opts.outFormat = oracledb.OBJECT;
    opts.autoCommit = true;
    try {
      conn = await oracledb.getConnection();
      const result = await conn.execute(statement, binds, opts);
      //console.log(result);
      resolve(result);
    } catch (err) {
      reject(err);
    } finally {
      if (conn) {
        // conn assignment worked, need to close
        try {
          await conn.close();
        } catch (err) {
          console.log(err);
        }
      }
    }
  });
}
```

**Comment by elhigu** [comment]
You can check what kind of query is sent to DB by setting DEBUG=knex:* environment variable to shell, before executing the code.  Also your direct oracledb code doesn't show which query is working.

However from exception it actually seems that your oracledb connection parameters are wrong somehow, since pool is not able to get connection from your database. You doesn't seem to have 
`connectString ` attribute at all in your knex config.
