### ISSUE TITLE
No colors in debug mode after 0.20.4 update

### ISSUE THREAD

**Issue by lynxtaa** [knex/knex#3588]
# Environment

Knex version: 0.20.4
Database + version: Postgres 
OS: Windows

# Bug

After 0.20.4 update there are no colors in debug mode.

Version 0.20.3:
<img width="336" alt="Screenshot 2019-12-19 16 52 26" src="https://user-images.githubusercontent.com/22496946/71179040-6b534900-2280-11ea-9056-0438ad43c9af.png">

Version 0.20.4:
<img width="337" alt="Screenshot 2019-12-19 16 53 07" src="https://user-images.githubusercontent.com/22496946/71179049-7017fd00-2280-11ea-9c01-94480c2b04fe.png">

**Comment by elhigu** [comment]
https://github.com/knex/knex/commit/65e1a3a3d0fd2107059d22736ec8c7379c3095a9

Maybe that commit could mess them if color codes does use % char for something... I suppose with debug mode you mean the debug attribute in knex config (there is also environment variable DEBUG=knex:*  which adds debug prints).

**Comment by kibertoad** [comment]
Released in 0.20.5
