### ISSUE TITLE
Question: Using .raw in a transaction

### ISSUE THREAD

**Issue by chelliwell** [knex/knex#3589]
MySQL + knex 0.20.2, Windows OS

I have a complex raw query, as part of a transaction. 
I tried .trx.raw(), but that "is not a function". I got it working with a .select because the first item in the raw query is a SELECT. 
So far I have 

```
            let queryResult
            const trxResult = await dbConn.transaction(async (trx) => {

                queryResult = await trx().timeout(2000, { cancel: true })
                    .transacting(trx)
                    .select(dbConn.raw(MyRawQueryString))
```

But I find I need to ensure a USE on the correct database.
So really, I need to 'raw' the whole thing. Or else some other way to get the transaction performed on the correct database. Is this possible?
Even when the USE isn't needed, I get "calling knex without a tableName is deprecated. Use knex.queryBuilder() instead" - so perhaps there's a better way overall?
Thanks

**Comment by kibertoad** [comment]
@chelliwell This sounds strange, Knex.Transaction interface extends Knex, so it should have .raw method on it. Can you share exact code that is not working for you?

**Comment by chelliwell** [comment]
That's pretty much an accurate precis of the code as I have it now.
A simple/dumb example that shows the .raw error is:

```
        try { 

            let queryResult

            const trxResult = await dbConn.transaction(async (trx) => {

                queryResult = await trx().timeout(2000, { cancel: true })
                    .transacting(trx)
                    .raw(`USE RecordsDb;`)

            return (queryResult)
        }

        catch (e) {
            console.log(`readEvents() transaction was rolled back:\n'${e}'`);
        }


```
dbConn is the standard _require('knex')({  })_  object.

It throws "trx(...).timeout(...).transacting(...).raw is not a function"

But even if/when that is fixed, I'll still get the deprecated warning for no tableName. It doesn't seem to flood my log file, but it might not work one day on a later version?

I guess I could not use a transaction, and encode the BEGIN/COMMIT/ROLLBACK within a try/catch, but it would be nice to use the built-in knex transaction mechanism, if possible.

**Comment by wubzz** [comment]
I believe it's because you're calling `trx()` and then `.raw`. The first call returns a `queryBuilder` which if I'm not mistaken does not contain a `.raw` function.

`trx.raw` exists but not `trx().raw`

**Comment by elhigu** [comment]
also when you are using trx.something etc. you don't need to add `. transacting(trx)`. It is needed only if you start building query directly from knex instance.

**Comment by elhigu** [comment]
Closing as user error if no more broken examples (where knex is used correctly) are given.

**Comment by amroczeK** [comment]
Hey @elhigu I am facing a similar issue. Here is a sample of my code simplified.

I get the following error: TypeError: trx.raw(...).timeout(...).transaction is not a function.

The RAW SQL queries we are doing are just SELECT queries with joins, functions, unions etc. The reason I am trying to implement transactions if because we sometimes experience this error **'KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?'** when running a task which does a lot of SQL queries to multiple databases concurrently.

Do transactions even need to be used for queries using SELECT and not inserting/modifying data?

The code below will create a knex connection or use an existing connection

```
const _knex = require("knex");
const querySQL = async (datasource, sql, format, modifier, chartType) => {
  const knex = findOrCreateConnection(datasource);
  
  try {
        await knex.transaction(async trx => {
          const result = await trx
            .raw(sql)
            .timeout(60000)
            .transaction(trx);
          result = postProcessResults(result, format);
          result = resultHandler(datasource.databaseType, result);
          return result;
        });
      } catch (error) {
        console.log(error);
        return error;
      }
}

const findOrCreateConnection = datasource => {
  // If the connection already exists
  if (connections[datasource.name]) return connections[datasource.name];
  // Establish a new connection
  else {
    const connObj = getConnectionObj(datasource);
    const newConnection = _knex(connObj);
    connections[datasource.name] = newConnection;
    return newConnection;
  }
};

```

This is the current working implementation without transactions and async/await:

```
const _knex = require("knex");
const querySQL = (datasource, sql, format, modifier, chartType) => {
 return new Promise((resolve, reject) => {
    const knex = findOrCreateConnection(datasource);
    sql = knex
             .raw(sql)
             .timeout(60000)
             .then((result) => {
             result = postProcessResults(result, format);
             resolve(resultHandler(datasource.databaseType, result));
             })
             .catch((error) => {
                reject(error);
             });
 });
}

const findOrCreateConnection = datasource => {
  // If the connection already exists
  if (connections[datasource.name]) return connections[datasource.name];
  // Establish a new connection
  else {
    const connObj = getConnectionObj(datasource);
    const newConnection = _knex(connObj);
    connections[datasource.name] = newConnection;
    return newConnection;
  }
};
```

**Comment by elhigu** [comment]
also if you do 

```
          const result = await trx
            .raw(sql)
            .timeout(60000)
            .transacting(trx);
```

the last part is redundand. Creating query through `trx` instance already binds the transaction correctly (and is the preferred way, `.transacting` is pretty much obsolete and probably should be deprecated)
