### ISSUE TITLE
0.20.5 has DOS line terminators, breaking knex seed:run

### ISSUE THREAD

**Issue by shanestillwell** [knex/knex#3598]
# Environment

Knex version: 0.20.5
Database + version: pg: 7.16.0 (postgres 11.6)
OS: macOs Catalina

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
When running `knex seed:run`, get an error.
```
$ knex seed:run
env: node\r: No such file or directory
error Command failed with exit code 127.
```

2. Error message
```
$ knex seed:run
env: node\r: No such file or directory
error Command failed with exit code 127.
```

`find . -name "*.js" | xargs file -k {} \;`

```
./lib/constants.js:                                                ASCII text, with CRLF line terminators
./lib/interface.js:                                                ASCII text, with CRLF line terminators
./lib/client.js:                                                   ASCII text, with CRLF line terminators
./lib/transaction.js:                                              ASCII text, with CRLF line terminators
./lib/seed/Seeder.js:                                              ASCII text, with CRLF line terminators
./lib/seed/seed-stub.js:                                           ASCII text, with CRLF line terminators
./lib/logger.js:                                                   ASCII text, with CRLF line terminators
./lib/util/save-async-stack.js:                                    ASCII text, with CRLF line terminators
./lib/util/fake-client.js:                                         ASCII text, with CRLF line terminators
...
```

All files have **dos** style line endings. Changing them to unix fixes the problem.

```
cd node_modules/knex/;
find . -name "*.js" | xargs dos2unix;
```

Reference:
https://stackoverflow.com/q/18492897/179335

**Comment by egorovli** [comment]
Having the same issue. This temporarily fixes it, as @shanestillwell mentioned:

```bash
$ brew install dos2unix
$ find ./node_modules/knex/ -name "*.js" | xargs dos2unix
```

**Comment by kibertoad** [comment]
I wonder at what stage it got messed up, if git or npm is to be blamed. Can you check if line endings are correct in repo itself?

**Comment by kibertoad** [comment]
OK, I think I know what happened - autocrlf for git only works when committing stuff back, but not on npm publish, so I published wrong terminators from my local machine. will try to fix it now

**Comment by egorovli** [comment]
@kibertoad, in `master` with latest commit a2a66605a3 all line endings are fine.

**Comment by elhigu** [comment]
> OK, I think I know what happened - autocrlf for git only works when committing stuff back, but not on npm publish, so I published wrong terminators from my local machine. will try to fix it now

I always configure git to preserve original line endings also on windows... Is prettier configured to also use linux line endings? Or were those broken only for some files? I think we could also use .gitattributes to force line endings.

**Comment by kibertoad** [comment]
@elhigu Sources in git are fine, and my git client was actually converting back to unix endings on commit correctly. Problem was with publishing from my new machine since that doesn't convert anything pre-publish 😅 . Reconfigured now, and will unpublish and republish.

**Comment by kibertoad** [comment]
@shanestillwell @egorovli Could you please try 0.20.6?

**Comment by shanestillwell** [comment]
@kibertoad 0.20.6 works as expected. Thanks for the quick turn around.

**Comment by stefan-girlich** [comment]
Experiencing the original error using version 0.21.20 on MacOS 10.14, Node 15.4.0.
Workaround from the original post works.
