### ISSUE TITLE
RFC: Add a `.asSubQuery()` or `.asNonExecutable()` and `.asExecutable()`

### ISSUE THREAD

**Issue by fer22f** [knex/knex#3600]
# Feature discussion / request

1. Explain what is your use case

Take a code that builds a subquery:

```javascript
async function mySubQueryBuilder() {
  const myFancyValue = await myFancyFunction();
  return knex.from("table")
    .select("id")
    .where("column", myFancyValue)
}

async function myQuery() {
  return knex.from("table2")
    .whereIn("id_table", await mySubQueryBuilder())
}
```

Now, because we are dealing with `async` functions, `myQuery` will work, but for the wrong reasons: `mySubQueryBuilder` will start fetching right away and return results, and won't be embedded into the query. A code that would work is as follows:

```javascript
function mySubQueryBuilder() {
  const myFancyValue = myLessFancyFunction();
  return knex.from("table")
    .select("id")
    .where("column", myFancyValue)
}

async function myQuery() {
  return knex.from("table2")
    .whereIn("id_table", mySubQueryBuilder())
}
```

But now we can't do anything fancy in the sub query builder. My current approach is something like this: 

```javascript
function mySubQueryBuilder(myFancyValue) {
  return knex.from("table")
    .select("id")
    .where("column", myFancyValue)
}

async function myQuery() {
  return knex.from("table2")
    .whereIn("id_table", mySubQueryBuilder(await myFancyFunction()))
}
```

Which is less than ideal in some cases.

2. Explain what kind of feature would support this

We could have QueryBuilders that don't coerce into Promises. So no `thenable`s. An API to transform regular query builders into those would be available, and perhaps also back into `thenable` QueryBuilders.

We can currently do this by using `toString()`, but that is a horrible idea.

3. Give some API proposal, how the feature should work

```javascript
async function mySubQueryBuilder() {
  const myFancyValue = await myFancyFunction();
  return knex.from("table")
    .select("id")
    .where("column", myFancyValue)
    .asSubQuery();
}

async function myQuery() {
  return kenx.from("table2")
    .whereIn("id_table", await mySubQueryBuilder())
}
```

So now the value returned by `mySubQueryBuilder` won't ever resolve and can be used as a subquery. We could have a subquery starter like `knex.nonExecutable.from()` or something like that, or better names than those in general.

**Comment by elhigu** [comment]
This has been popping up every now and then. I still don't think it is a good idea to add this to knex. 

This is common problem when coding javascript and it doesn't make any sense for knex to have some specific way how to treat this when one can easily solve the problem by wrapping the asynchronously built query builder to an object like this:

```
async function mySubQueryBuilder() {
  const myFancyValue = await myFancyFunction();
  return { 
    query: knex.from("table").select("id").where("column", myFancyValue)
  };
}

async function myQuery() {
  return knex.from("table2")
    .whereIn("id_table", (await mySubQueryBuilder()).query)
}
```

Having dedicated way for knex to do it doesn't add any value and only makes knex more confusing.

**Comment by elhigu** [comment]
Old discussion about the subject found here: https://github.com/knex/knex/issues/2940

**Comment by fer22f** [comment]
Seems reasonable. Thanks.
