### ISSUE TITLE
SQLITE_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by TillDeathCoder** [knex/knex#3608]
# Environment

Knex version: 0.20.3
Database + version: SQLite3
OS: Windows 10

# Bug

1. Explain what kind of behavior you are getting and how you think it should do:

I develop the desktop application using Electron, Angular, SQLite3, and Knes. I faced the issue during inserting more than ~180 elements.

2. Error message
`[Error: SQLITE_ERROR: too many SQL variables] {
    errno: 1,
    code: 'SQLITE_ERROR'
  }
`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

The code I use:

```javascript
    const trx = await this.connection.transaction();
    try {
      const account = event.company;
      const conditions = event.conditions;
      // some work with variables

      await trx('events').insert(event);
      await trx('accounts').insert(account);
      await trx('conditions').insert(conditions);
      trx.commit();

    } catch (e) {
      trx.rollback();
    }
```

# Feature discussion / request

1. Explain what is your use case

I have the conditions array and its length might be more than 100 elements. I expected according to the Knex documentation that it would be easy to save the array using one insert operation.
As I know there is a limit for SQLlite3 for max numbers of host parameters and it is [999](https://www.sqlite.org/limits.html#max_variable_number) but I got the error when I had only 189 conditions.
Is that issue of Knex?

**Comment by kibertoad** [comment]
@TillDeathCoder Could you please try performing same query using SQLite3 driver directly, without Knex? If it works correctly, that would indeed confirm that problem is on Knex side. However, considering the error message that you are getting, that seems unlikely.

**Comment by elhigu** [comment]
Doesn't seem to have anything to do with knex. Number of parameters in query is around `conditionRows * columnsInConditionsTable` also you can check number of bindings by calling `trx('conditions').insert(conditions).toSQL()`.

**Comment by cybertouchllc** [comment]
So, I came into this issue when trying to insert more than 100k items using `knex.batchInsert`:

```
knexClient
			.batchInsert('files', files, 500)
			.then(trace('inserted'))
			.then(resolve)
			.catch((e) => {
				console.error({ e })
				console.log('INSERTING', files.length)

				reject(e)
			})
```
