### ISSUE TITLE
MultiSubnetFailover settings in Knex package

### ISSUE THREAD

**Issue by Jindam** [knex/knex#3620]
# Development

Knex version: 0.20.1
MSSql Database + Version 15.0
OS: macOS 10.14.6
@smorey2 

**How can we add settings in the connection config for connecting it to MSSQL Server Multi-Subnet Failover Clusters, right now it can't connect ?**

**Comment by elhigu** [comment]
It should be done in mssql driver's configuration... at least tedious seems support it https://github.com/tediousjs/tedious/issues/387 I don't know if node-mssql does.

Anyways knex should not care about it. Closing as this should be inmplemented in driver level.

**Comment by IanChokS** [comment]
Yes Tedious supports multiSubnetFailover. 
[Tedious Docs](https://tediousjs.github.io/tedious/api-connection.html)
