### ISSUE TITLE
warming message

### ISSUE THREAD

**Issue by royalcala** [knex/knex#3622]
# Environment

Knex version:"knex": "^0.20.6"
Database + version:"sqlite3": "^4.1.1"
OS:ubuntu 18

1. Explain what kind of behaviour you are getting and how you think it should do
Running this funcion trx.del({_id}).into(tableName).where({ _id }), I have in console this  warming:
   .returning() is not supported by sqlite3 and will not have any effect.
Im not using the chain returning and appears the message for each row where I use the function del 
node_modules/knex/lib/logger.js:44

regards

**Comment by royalcala** [comment]
adding .returning() is resolved.

**Comment by elhigu** [comment]
Probably you had added earlier .returning(‘something’) and by adding .returning() that earlier statement was “canceled”... so you seemed to find a workaround to your problem. Underlyin issue why .returning was there in the first place is probably still there.

With sqlite you should never use .returning() method.
