### ISSUE TITLE
Prefix seeds with timestamp like migrations

### ISSUE THREAD

**Issue by JaneJeon** [knex/knex#3623]
# Feature discussion / request

When using the knex cli, you can run `knex migrate:make $name` and it'll generate a `$timestamp_$name.js` in the migrations directory. Is it possible to do the same for the seeds? Because when I run `knex seed:make $name` it generates a `$name.js` _without_ the timestamp and I have to add it in manually :/

**Comment by ricardograca** [comment]
Why do you think you need a timestamp for seeds?

**Comment by JaneJeon** [comment]
The same reason we'd want timestamp for migrations - to order them (prefixing with a number doesn't work out, since after seed number 9, 10 wraps around and gets run before seed number 2).

**Comment by ricardograca** [comment]
Use `01-99` then, or `001-999` if you really need that many. Timestamps won't guarantee that the correct insertion order is followed anyway, so it's not the correct solution to that problem.

**Comment by JaneJeon** [comment]
Then why do we have that feature with migrations?

**Comment by JaneJeon** [comment]
Not to mention our company had to do a rolling “01-99” to “001-999” for its migrations just recently so I know it can be annoying to “upgrade” your migration versions when you hit that cap.

**Comment by ricardograca** [comment]
Because migrations should indeed be run in a specific order and they always build on the previous ones. Seeds do not. You may have to add seed data for a table that is depended upon by other seed data that already exists. If you use timestamps that dependency is broken.

If you were using `01-99` for migrations that was also a bad design decision.

**Comment by JaneJeon** [comment]
> and they always build on the previous ones. Seeds do not.

They do, when you have one table that depends on the rows from another. Just like migrations, using timestamps allows me to control the exact order that the seeds run in. In fact, by controlling the order in which I create the seeds (when it's prepended by a timestamp), it allows me to get over the thing you're saying: "If you use timestamps that dependency is broken." Timestamps is the _solution_, not the _problem_.

Seriously, we use this for migrations and I don't see you talking about how timestamps break dependencies for migrations.

> If you were using `01-99` for migrations that was also a bad design decision.
Well, we were already using this way of writing migrations when I came into the company. The point is that whenever you're using `$n-$name` (for seeds _or_ migrations), you're bound to have to update all migrations whenever `$n` overflows a new digit. Timestamps prevent me from ever having to do that.

**Comment by JaneJeon** [comment]
@kibertoad thoughts?

**Comment by kibertoad** [comment]
I have no strong opinion on this matter. I can see value behind executing seeds in order, especially when they are incremental and depend on each other, but since the introduction of named seed execution, I can also see how it can be inconvenient for people who don't run seeds in batches.
I am open to merge a PR that would introduce an optional CLI switch (and/or knexfile config option) that would enable timestamp prefixing.

**Comment by christianodejesus** [comment]
> I can see value behind executing seeds in order, especially when they are incremental and depend on each other

I think exactly about this, like Sequelize does by default.

> I am open to merge a PR that would introduce an optional CLI switch (and/or knexfile config option) that would enable timestamp prefixing.

I'm working on this now, but the config option defaults to disable, to not cause problem to anyone already uses seeds with no order

**Comment by christianodejesus** [comment]
@kibertoad / @JaneJeon  
I've created the config option and CLI flag that allows to create seeds with a timestamp prefix, see in the PR.

**Comment by christianodejesus** [comment]
@kibertoad I made new changes on my PR #3873 for its latest revision. It would be great if you could review these new changes. Thanks!
