### ISSUE TITLE
toNative is not implemented for Raw

### ISSUE THREAD

**Issue by ThomWright** [knex/knex#3628]
# Environment

Knex version: 0.20.8
Database + version: pg 9.6
OS: Linux

@lorefnon 

# Bug

This should work according to the TypeScript types, but it throws:

` knex.raw("id = ?", ["hello"]).toSQL().toNative()`

The error is:

`TypeError: knex.raw(...).toSQL(...).toNative is not a function`

The relevant TypeScript types are:

```typescript
interface Raw<TResult = any>
  extends events.EventEmitter,
    ChainableInterface<ResolveResult<TResult>> {
  toSQL(): Sql;
  // ...
}

interface Sql {
  method: string;
  options: any;
  bindings: Value[];
  sql: string;
  toNative(): SqlNative; // <--
}
```

Code to reproduce:

```typescript
import * as knex from "knex"
const kpg = knex({client: "pg"})
knex.raw("id = ?", ["hello"]).toSQL().toNative()
```

**Comment by josiahjohnston** [comment]
I'm seeing the same thing on OS X. 

It appears like the relevant SQL is accessible like so:
```
import * as knex from "knex";
const kpg = knex({client: "pg"});
kpg.raw("id = ?", ["hello"]).toSQL().sql;
```
But I haven't seen documentation for `sql` being a supported method.
In a [related issue](https://github.com/knex/knex/issues/2519), @elhigu (a major contributor) noted the recommended method was exactly what you used: `kbg.raw(...).toSQL().toNative()`.

**Comment by elhigu** [comment]
> But I haven't seen documentation for sql being a supported method. In a related issue, @elhigu (a major contributor) noted the recommended method was exactly what you used: kbg.raw(...).toSQL().toNative().

I actually showed a workaround how to print out native SQL also for knex.raw for certain cases couple of comments below it https://github.com/knex/knex/issues/2519#issuecomment-384689291 Though adding toNative() for knex.raw is more than welcome 👍

**Comment by josiahjohnston** [comment]
Thanks for the tip!

FTR, it amounts to embedding the raw snippet into a larger non-raw knex statement, then calling the native function on that. Ex:

```
let raw_fragment = kpg.raw("id=?", ['value']);
kpg.select('*').from('foo').where(raw_fragment).toSQL().toNative();
```

This required refactoring for my use case of escaping table, column, etc names - a bit awkward but workable for now. I wanted to use knex because it was an indirect dependency in our stack, and authors seem to stay on top of SQL injection security concerns
