### ISSUE TITLE
Knex Should Include the Query String in Error Messages

### ISSUE THREAD

**Issue by machineghost** [knex/knex#3633]
# Environment

Knex version: ^0.20.8
Database + version: psql (PostgreSQL) 9.5.19
OS: Linux

# Feature discussion / request

1. Explain what is your use case

I am a Knex user who gets an error

2. Explain what kind of feature would support this

A slight improvement to Knex's error handling code.

3. Give some API proposal, how the feature should work

I recently got the following, oh so helpful (:wink:) stack trace:

```
(node:10502) UnhandledPromiseRejectionWarning: error: syntax error at or near "["
    at Connection.parseE (/home/some_path/node_modules/pg/lib/connection.js:605:13)
    at Connection.parseMessage (/home/some_path/node_modules/pg/lib/connection.js:404:19)
    at Socket.<anonymous> (/home/some_path/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:193:13)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
```

When I finally tracked it down, it turned out that I had an object being serialized into a string, so the "[" was from ` [object Object]`.  But the thing is, it took forever to figure that out, because Knex queries are promise-based, which means their stack (as you can see above) loses its origin/context.

As soon as I found the problem, all I had to do was log the query to see the issue.  Surely there's some way Knex can do this, and save everyone who gets errors tons of debugging time?  I know that the error handling is somewhat separate from the processing code, but is it truly impossible to connect the string of the query that causes the error, with the error itself?

**Comment by elhigu** [comment]
>  I know that the error handling is somewhat separate from the processing code, but is it truly impossible to connect the string of the query that causes the error, with the error itself?

Yeah, since knex is not going to start wrapping errors thrown by db-drivers / other libraries etc.  it is pretty much impossible. How ever you write for example knex.on('query-error', ...) handler to print out query that failed. 

I have always lots of event handlers registered to log long query times / long transactions ++ to help debugging when something goes wrong.
