### ISSUE TITLE
How to convert sql query joine with multiple table to knex ORM?

### ISSUE THREAD

**Issue by avinashsingh2222** [knex/knex#3637]
`'select ag.id answer_group_id, ag.name answer_group_name, ag.client_id, ag.status answer_group_status, ' +
    ' ag.created_on answer_group_created_on, ag.updated_on answer_group_updated_on, ' +
    ' ag.effective_from  answer_group_effective_from, ag.effective_till answer_group_effective_till, ' +
    ' aga.sequence_number, ans.id answer_id, ans.answer, ' +
    ' ans.created_on as answer_created_on, ans.updated_on as answer_updated_on, ans.locale_code as answer_locale_code, ' +
    ' ans.mutex as answer_mutex, ans.reportingKey as answer_reporting_key, ' +
    ' ag.keywords answer_group_keywords, ' +
    ' apm.metadata as answer_phrase_metadata, apm.status as answer_phrase_status ' +
    ' from answer_groups ag ' +
    ' left join answer_group_answers aga on ag.id = aga.answer_group_id and aga.status = :status' +
    ' left join answers ans on ans.id = aga.answer_id  and ans.status = "active" ' +
    ' left join phrase_metadata as apm on apm.id = ans.phrase_metadata_id' +
    ' where ag.status = :status and ' +
    '           (ag.client_id is null or ag.client_id = :clientId) and ' +
    '               (ans.client_id is null or ans.client_id = :clientId) '

  const ORDER_BY_CLAUSE = ' order by ag.id, aga.sequence_number '`

**Comment by elhigu** [comment]
Closing as issue is not following template / issue guidelines,
