### ISSUE TITLE
useNullAsDefault: true property still throws Undefined binding error 

### ISSUE THREAD

**Issue by waleedahmed3045** [knex/knex#3643]
# Environment

Knex version: 0.20.8
Database + version: Oracle 12c, MySQL 8.0.18
OS: Windows 10

 @atiertant @smorey2 .

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Knex is throwing undefined binding error, where as per documentation if i use property "  useNullAsDefault: true" knex should ignore it

2. Error message
Undefined binding(s) detected when compiling SELECT. Undefined column(s)

3. in https://npm.runkit.com/knex  run the following code

```
require('sqlite3');
const Knex = require('knex');

const knexSqlite = Knex({
  client: 'sqlite',
  connection: ':memory:',
  useNullAsDefault: true
});

(async function run() {
  await knexSqlite.schema.createTable('test', (t) => {
    t.increments('id').primary();
    t.string('data');
  });

knexSqlite('test')
  .where('data', undefined)
  .select()
  .toSQL()
 
 
})();
```

**Comment by elhigu** [comment]
`useNullAsDefault` has nothing to do with that error you are occuring. It only affects to some code that inserts multiple rows with single query.

There is no option that allows knex to pass undefined bindings to driver.

**Comment by waleedahmed3045** [comment]
@elhigu  is there a way to ignore undefined binding and not throw an error?

**Comment by elhigu** [comment]
> @elhigu is there a way to ignore undefined binding and not throw an error?

No. You should not pass undefined bindings to knex. That was removed, because it was a huge security risk (and that risk had actually been realized many times, like allowing access to admin user rights without giving password etc.).

**Comment by waleedahmed3045** [comment]
@elhigu Thank you, would you be able to tell the last version before this feature was removed?

**Comment by elhigu** [comment]
I think it was this PR https://github.com/knex/knex/pull/1459 ages ago around 0.11.5. You should not be using that version on knex....
