### ISSUE TITLE
postgres: table.timestamp('tn', { precision: 0 }) doesn't give 'timestamp(0)'

### ISSUE THREAD

**Issue by mike-robison** [knex/knex#3644]
# Environment

Knex version: 0.20.8
Database + version: N/A
OS: N/A

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
when calling `table.timestamp('column_name' { precision: 0 })`, since 0 is falsy, the precision isn't applied.
see [here](https://github.com/knex/knex/blob/c14252d907855cee310db7b57fe37a776fd4424a/lib/dialects/postgres/schema/columncompiler.js#L83)
2. Error message
N/A
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.
```javascript
const Knex = require('knex');

const knexPg = Knex({
  client: 'pg',
});

const [ { sql } ] = knexPg.schema.createTable('table_name', table => {
  table.timestamp('column_name', { precision: 0 })
}).toSQL()
  
console.log(sql)
// outputs: "create table \"table_name\" (\"column_name\" timestamp)"
```
# Feature discussion / request

1. Explain what is your use case
create timestamp(0) instead of timestamp with unlimited precision.
2. Explain what kind of feature would support this
N/A
3. Give some API proposal, how the feature should work

```javascript
return `${useTz ? 'timestamptz' : 'timestamp'}${
  precision !== undefined ? '(' + precision + ')' : ''
}`;
```

**Comment by OlivierCavadenti** [comment]
Fix by https://github.com/knex/knex/commit/a431485aa6308aa2e9046f89b9216e7057caaa29

**Comment by kibertoad** [comment]
I'll release new 0.95 today
