### ISSUE TITLE
Gracefully handle inserts that exceed the max allowed amount of bindings

### ISSUE THREAD

**Issue by JReinhold** [knex/knex#3646]
# Environment

Knex version: ^0.20.7
Database + version: PostgreSQL 10.7
OS: MacOS 10.14.6

# Feature discussion / request

1. Explain what is your use case

Most database engines have a max number of bindings per statement. My research tells me, that for PostgreSQL, the max number of bindings per statement is 65.535. (see https://github.com/brianc/node-postgres/issues/1091)

It is not totally unheard of, to batch insert that large amount of items, especially since inserting a single row can have many bindings. So I propose that knex handles this gracefully.

2. Explain what kind of feature would support this

Whenever a user tries to batch insert multiple rows at once (using `knex.insert([...some array])`, we check if the insert would result in more than the maximum allowed bindings. If it does, we split up the insert statements into multiple calls, and concatenate the result to the user.

3. Give some API proposal, how the feature should work

It could work in the "background", so no API have to happen. But it could be a breaking change, or too much magic happening in the background (it would result in multiple calls to the database, where the user might only expect one call), so we could also hide it behind a config flag, eg:
`knex.insert([...data], { splitLargeStatements: true })`

**Comment by elhigu** [comment]
There is batch insert for this particular case... It is intended behavior that knex is not going to split inserts to multiple queries (knex can create only single query from builder).

There are various reasons why knex doesn't want to start generating multiple queries from single builder. You could also use objection instead, which can automatically handle this case (and much more).

Having knex throwing an error in case where there are too many bingings would not be any better that allowing to DB error pass through. It would only add unnecessary logic to knex which also should be maintained for all drivers. Also it is possible that some databases allow to configure maximum number of bindings, where having it constant in knex would cause problems.

**Comment by JReinhold** [comment]
Those are valid points, I agree!
I haven't seen the `batchInsert` function, it is exactly what I'm looking for!

For anyone else ending up here, Objection.js only handles this issue automatically if you are using `insertGraph`, and **not** when using plain ´insert´.
