### ISSUE TITLE
Postgres native array parsing issue

### ISSUE THREAD

**Issue by sleewoo** [knex/knex#3648]
Wonder why knex is not parsing string arrays as is it parsing integer ones.

for `t.specificType('tags', 'int[]')`
result is an array: `[ 1937, 1938, 1941 ]`

for `t.specificType('tags', 'varchar(50)[]')`
result is a string: `'{a,b,c}'`
should be an array too?

thanks.

**Comment by sleewoo** [comment]
sorry, it works well for `varchar`

the troubling column is actually a `citext` array: `t.specificType('tags', 'citext[]')`

any chance to parse this into an array as well?

thanks.

**Comment by elhigu** [comment]
I suppose you need to override that columnt type in pg-types. AFAIK knex is not doing that parsing.... maybe openin issue in node-pg repo will help.

**Comment by sleewoo** [comment]
thanks for directions.
as `citext` is an extension it has no permanent `oid` so can not be added to `pg-types`.
rather it's `oid` should be queried on connection.
here is a solution i came up with:

```ts
import { types as pgTypes } from "pg";
import { parse as parseArray } from "postgres-array";

Knex({
  //...
  pool: {
    async afterCreate(conn, done) {

      const { rows: [ row ] } = await conn.query(`select typarray from pg_type where typname ilike 'citext'`)

      if (row) {
        pgTypes.setTypeParser(row.typarray, function(val) {
          return val
            ? parseArray(val)
            : val
        })
      }

      done(null, conn)
    }
  }
})
```
