### ISSUE TITLE
Typescript readonly structures in where and update

### ISSUE THREAD

**Issue by maximelkin** [knex/knex#3653]
# Environment

Knex version: latest
Database + version: any
OS: any

@lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

```typescript
interface User {
   prop1: string
   prop2: string | null
}
const a  = [['a', '2'], ['b', null]] as const

// error at whereIn: ...
await knex<User>('users').whereIn(['prop1', 'prop2'], a);
```

2. Error message

TS2769: No overload matches this call.   The last overload gave the following error.     Argument of type 'readonly (readonly [string, string | null])[]' is not assignable to parameter of type 'QueryBuilder<unknown, unknown>'.       Type 'readonly (readonly [string, string | null])[]' is missing the following properties from type 'QueryBuilder<unknown, unknown>': client, or, not, and, and 115 more.

**Comment by lorefnon** [comment]
Knex typings currently don't contain information about what properties and arguments are only read and never mutated. But I do think appropriately marking inputs are readonly is the right thing to do. 

I'll take this up within next 3-4 days.
