### ISSUE TITLE
Got an error while compiling version >= 0.20.2, as well as the latest(0.20.9)

### ISSUE THREAD

**Issue by Silas-Yang** [knex/knex#3656]
# Environment

Knex version: ^0.20.9
Database + version:
OS: MacOS

Select applicable template from below.
@lorefnon 
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Compilation error in version 0.20.9.
Version 0.20.1 works well.

2. Error message
```
node_modules/knex/types/index.d.ts:1436:13 - error TS2430: Interface 'ChainableInterface<T>' incorrectly extends interface 'Pick<Promise<T>, "map" | "get" | "catch" | "finally" | "asCallback" | "bind" | "delay" | "reflect" | "return" | "thenReturn" | "reduce" | "then" | "mapSeries" | "spread">'.
  The types returned by 'asCallback(...)' are incompatible between these types.
    Type 'this' is not assignable to type 'Bluebird<T>'.
      Type 'ChainableInterface<T>' is missing the following properties from type 'Bluebird<T>': [Symbol.toStringTag], caught, error, lastly, and 28 more.
```

**Comment by lorefnon** [comment]
Can you please also: 

1. Share one usage (source code snippet) that is failing. 
2. Check if you have `@types/knex` and/or `bluebird-global` installed.

**Comment by Silas-Yang** [comment]
1. Share one usage (source code snippet) that is failing.
```
import * as Knex from 'knex'

let knex: Knex = null

export default (options: Knex.ConnectionConfig) => {
    if (knex != null)
        return knex
    knex = Knex({
        client: 'mysql2',
        connection: options,
        pool: { min: 1, max: 7 },
    })
    return knex
}
```

2. Check if you have @types/knex and/or bluebird-global installed.

Checked and re-installed both packages. The error still occurred.

**Comment by lorefnon** [comment]
> Checked and re-installed both packages. 

Did you already have both of them installed ? Can you remove `@types/knex`. That package is no longer required.

**Comment by Silas-Yang** [comment]
> > Checked and re-installed both packages.
> 
> Did you already have both of them installed ? Can you remove `@types/knex`. That package is no longer required.

Yes. After removed `@types/knex`, It is still the same error.

**Comment by Silas-Yang** [comment]
It is Ok now. I removed both `@types/knex` and `bluebird-global`. It works!
Thank you so much!
