### ISSUE TITLE
MariaDB JSON_VALUE is not working when creating views

### ISSUE THREAD

**Issue by igasparetto** [knex/knex#3664]
# Environment

Knex version: 0.20
Database + version: 10.3.18-MariaDB
OS: Any

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
CREATE VIEW myView AS SELECT json_value(jsonColumn, '$.key') as myKey FROM myTable

2. Error message
er_sp_does_not_exist: function json_value

**Comment by elhigu** [comment]
Not knex bug and cannot reproduce
