### ISSUE TITLE
knex on brower: Uncaught TypeError: promisify is not a function

### ISSUE THREAD

**Issue by cirotarini** [knex/knex#3669]
# Environment

Knex version: knex@0.20.10 + + mysql@2.18.1
Database + version: 10.3.22-MariaDB-0+deb10u1

OS: Linux debian - browser chrome
I serve the static page with apache
I packed the knex npm module with browserify.

# Bug
I woud like to try a query in my broswer (serving the html static page with apache).
I know this is insane but I want to try.

2. Error message

bundle.js:21075 Uncaught TypeError: promisify is not a function
    at Object.79.util (bundle.js:21075)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.85../delay (bundle.js:21458)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.69../util/timeout (bundle.js:19205)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.52../constants (bundle.js:15042)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.59../client (bundle.js:16031)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.57../knex (bundle.js:15912)
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

This is my javascript:
const  knex = require('knex')   ({
        client: 'mysql',
        connection: {
          host : 'localhost',
          user : 'demouser',
          password : **omitted**
          database : 'PROVA'
        }
      });

	knex.from('article').select("*")
    .then((rows) => {
        for (row of rows) {
            console.log(row);
        }
    }).catch((err) => { console.log( err); throw err })
    .finally(() => {
        knex.destroy();
    });

**Comment by elhigu** [comment]
so... are you trying to query your database directly from chrome? It will not work. You should be able to build queries though (like knex documentation page is doing). But you will not be able to execute them, because db drivers cannot work in browser.

**Comment by elhigu** [comment]
definitely not a bug :)
