### ISSUE TITLE
Configuring SQL Server timeout

### ISSUE THREAD

**Issue by juicetin** [knex/knex#3670]
# Environment

Knex version: 0.19.5
Database + version: SQL Server 2018
OS: Windows (AWS RDS)

@smorey2.

# Bug

This may not strictly be a bug and more of a bug/feature request hybrid (I'd lean towards the former).
When setting the `connectionTimeout` option for SQL Server, it doesn't seem to actually apply - i.e., the default is `15000ms`, and after setting the value to `30000`, it still times out at `15000`. Is changing the request timeout possible with SQL Server?

**Comment by elhigu** [comment]
There is no such config as `connectionTimeout` in knex. Did you try setting `acquireConnectionTimeout` of knex to be bigger than SQL server's timeout? 

For knex pool http://knexjs.org/#Installation-pooling there are various other timeouts that can be passed https://github.com/vincit/tarn.js/ . 

If you are talking about node-mssql driver's attributes, those connection attributes should be passed directly to the driver.

**Comment by elhigu** [comment]
Closing issue until it is clear what it is about exactly.

**Comment by juicetin** [comment]
Hi @elhigu 

```
    client: "mssql",
    connection: {
      host: STG_HOST,
      user: STG_USER,
      password: STG_PASSWORD,
      port: Number(STG_PORT),
      database: STG_DB,
      connectionTimeout: 20000,
    }
```

This is where the `connectionTimeout` option was set, as you pointed out in a past issue
https://github.com/knex/knex/issues/2699

However, this option didn't take effect, as the default timeout of 15000ms was still being enforced (as stated in the error when knex killed the request at 15000ms).

**Comment by elhigu** [comment]
Ok, that looks valid. Please check if the `connectionTimeout` option is respected if you use node-mssql directly.

Also please be clear what error you are getting? Currently from this issue I cannot see what kind of problem you are experiencing nor how to reproduce it exactly.

**Comment by woodchuck** [comment]
For the benefit of future travelers, I believe this should be specified as follows. Note `connectTimeout` vs. `connectionTimeout`.

```
client: "mssql",
  connection: {
    host: STG_HOST,
    user: STG_USER,
    password: STG_PASSWORD,
    port: Number(STG_PORT),
    database: STG_DB,
    options: {
      connectTimeout: 20000,
    }
}
```

https://github.com/tediousjs/tedious/issues/778
https://tediousjs.github.io/tedious/api-connection.html#function_newConnection
