### ISSUE TITLE
INSERT doesn't work

### ISSUE THREAD

**Issue by RFlintstone** [knex/knex#3693]
# Environment

**Knex version:**
mysql: ^2.18.1
knex: ^0.20.10:
OS: Windows 10 (DB is hosted with Laragon and application is hosted via express.js)

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**
No data is being inserted into the database. It should put the data in the database on POST
**2. Error message**
None
**3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.**
It needs a connection with a (MySQL) database

# Code
app.js (where the POST method is called - _app.post('/api')_ ):
https://hastebin.com/amihopasej.php
api.js (this is the file with knex):
https://hastebin.com/axuhutitoj.js
config.json (config file which has the credentials for knex stored in it):
https://hastebin.com/oqijeruwim.json

**Comment by elhigu** [comment]
There are tests that insert actually does work. Please add minimal single file reproduction code here that is not using any webframeworks, but just knex.

**Comment by RFlintstone** [comment]
> There are tests that insert actually does work. Please add minimal single file reproduction code here that is not using any webframeworks, but just knex.

This doesn't work:
```
//============================================================
// SQL: http://knexjs.org/#Installation-node                ||
//============================================================
const knex = require('knex')({
    client: "mysql",
    connection: {
        host: "localhost:3306",
        user: "root",
        password: "",
        database: "projectsincluded_node"
    }
});
const DBSettings = JSON.stringify(knex.client.connectionSettings);
console.log(`\nDB Settings:\n${DBSettings}\n`);
knex('users').insert({user:'Test'});
```

**Comment by ricardograca** [comment]
I agree that it's probably not very obvious to newcomers that `knex('users').insert({user:'Test'})` will return a Promise and that the query is only actually run when you call `.then()` on it (or use `await`). So, of course the code in that example will do nothing.

Try the following:

```js
knex('users').insert({user:'Test'}).then(() => console.log('inserted row'))
```
or
```js
await knex('users').insert({user:'Test'})
console.log('inserted row')
```

More information in the docs: https://knexjs.org/#Interfaces

**Comment by RFlintstone** [comment]
> I agree that it's probably not very obvious to newcomers that `knex('users').insert({user:'Test'})` will return a Promise and that the query is only actually run when you call `.then()` on it (or use `await`). So, of course the code in that example will do nothing.
> 
> Try the following:
> 
> ```js
> knex('users').insert({user:'Test'}).then(() => console.log('inserted row'))
> ```
> 
> or
> 
> ```js
> await knex('users').insert({user:'Test'})
> console.log('inserted row')
> ```
> 
> More information in the docs: https://knexjs.org/#Interfaces

await worked! 😄 Currently trying to get the following code working:
POST (body):
```
{ 
	"id":"users",
	"item":["user", "email"],
	"value":["Hi4", "testemail"]
}
```
JS:
```
module.exports = {
    create: async function (oTable, oItem, oValue) {
        const oField = [{ [oItem]:[oValue] }];
        const insert = await knex(oTable).insert(oField);
        return insert;
    }
}
```
The body already posts with the right variables but knex doesn't seem to like arrays (unless there is something I'm overlooking).
