### ISSUE TITLE
INSERT doesn't work

### ISSUE THREAD

**Issue by RFlintstone** [knex/knex#3694]
# Environment

**Knex version:**
mysql: ^2.18.1
knex: ^0.20.10:
OS: Windows 10 (DB is hosted with Laragon and application is hosted via express.js)

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**
No data is being inserted into the database. It should put the data in the database on POST
**2. Error message**
None
**3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.**
It needs a connection with a (MySQL) database

# Code
```
//============================================================
// SQL: http://knexjs.org/#Installation-node                ||
//============================================================
const knex = require('knex')({
    client: "mysql",
    connection: {
        host: "localhost:3306",
        user: "root",
        password: "",
        database: "projectsincluded_node"
    }
});
const DBSettings = JSON.stringify(knex.client.connectionSettings);
console.log(`\nDB Settings:\n${DBSettings}\n`);
knex('users').insert({user:'Test'});
```

**Comment by maximelkin** [comment]
Hello!
You need to await or .then your insert, so knex can understand what you what to execute it

**Comment by RFlintstone** [comment]
> Hello!
> You need to await or .then your insert, so knex can understand what you what to execute it

Await worked perfectly! Currently figuring out how I can insert multiple data with something like this:

POST (body):
```
{ 
	"id":"users",
	"item":["user", "email"],
	"value":["Hi4", "testemail"]
}
```
JS:
```
module.exports = {
    create: async function (oTable, oItem, oValue) {
        const oField = [{ [oItem]:[oValue] }];
        const insert = await knex(oTable).insert(oField);
        return insert;
    }
}
```

**Comment by elhigu** [comment]
Not a bug. Usage questions should be sent to stackoverflow.
