### ISSUE TITLE
Connection timeout for every request after hour(s) of idle time

### ISSUE THREAD

**Issue by derencel20** [knex/knex#3696]
# Environment

Knex version: ^0.20.10,
Database + version: MSSQL ^6.1.0
OS: Windows 10 Server 2016
@smorey2 

So I get this error everytime I leave the app running idle for an hour or more, and run some queries to db.
![image](https://user-images.githubusercontent.com/17394978/75655137-31e58380-5c9c-11ea-8f79-8a6fdde5ca51.png)

This is a multi-tenant app. So I had to provide a knex instance every time the user makes a query. Is this related?
![image](https://user-images.githubusercontent.com/17394978/75655268-74a75b80-5c9c-11ea-823a-31b05576f756.png)

This is also the same for the basic queries including ```select * from rooms```. And rooms only contain 3 - 10 items with 5-6 columns.

This is my ```knex``` config:
![image](https://user-images.githubusercontent.com/17394978/75655826-a4a32e80-5c9d-11ea-91b5-7abc1aa7d64f.png)

**Comment by derencel20** [comment]
Maybe [this](https://stackoverflow.com/questions/55839673/prevent-knex-database-connection-pool-from-closing-when-idle) one is related?

**Comment by derencel20** [comment]
I think [this](https://gitmemory.com/issue/tgriesser/knex/3049/463303578) is more relevant.

**Comment by derencel20** [comment]
Even adjusting the timeout doesn't take effect
![image](https://user-images.githubusercontent.com/17394978/75657791-ef26aa00-5ca1-11ea-8c7c-72b59b11bde1.png)

**Comment by derencel20** [comment]
![image](https://user-images.githubusercontent.com/17394978/75658809-e1722400-5ca3-11ea-9e8c-86a10c8b63c7.png)
It's the same even here. Is the transaction locking the table?

**Comment by derencel20** [comment]
I'll close this. I got and error 'transaction tried to rollback but transaction is still ongoing'(non-verbatim) earlier. So that must've locked the db.

**Comment by briandamaged** [comment]
@derencel20 : Howdy!  So, it looks like that timeout is coming from the `mssql` library itself (as opposed to the `knex` pooling).  I _think_ you can adjust that timeout by specifying it as part of the `connection:` section of your `knexfile.js`.  For ex:

```
{
  connection: {
    user: "blah",
    password: "blahblah",
    timeout: 30000,
  }
}
```

Based upon skimming the code, it looks like it will forward this value to the underlying `mssql` library.
