### ISSUE TITLE
postProcessResponse & wrapIdentifier break usage of internal tables / columns

### ISSUE THREAD

**Issue by felixmosh** [knex/knex#3700]
# Environment

Knex version: 0.20.6
Database + version: Mysql 8
OS: MacOS

# Bug
Running migration with `renameColumn` fails on dropping foreign keys. 
 
### Steps to reproduce
https://github.com/Kequc/knex-stringcase/issues/20#issuecomment-593820623

From my debugging, I saw that those mapping are applied on internal tables (such as `information_schema`) & the code trying to [access the column](https://github.com/knex/knex/blob/master/lib/dialects/mysql/schema/tablecompiler.js#L161) by its "old" name.

Maybe a better approach will be to apply the same functions on the name of the column in these internal queries.

Related to https://github.com/Kequc/knex-stringcase/issues/20

**Comment by felixmosh** [comment]
Apparently there is a test for [this case](https://github.com/knex/knex/blob/9aa7085b052938dc5252d10b2b418a475637eda5/test/unit/migrate/Migrator.js#L8), but it is probably fails

**Comment by kibertoad** [comment]
@felixmosh Considering that our current CI is green, I would be very surprised if existing test actually fails.
How does knex-stringcase work? Does it just use `postProcessResponse` and `wrapIdentifier` fields? because these should be disabled and reenabled correctly when doing internal queries.

**Comment by kibertoad** [comment]
Could be that there is something special about dropping foreign keys that gets it executed on a separate knexbuilder instance.

**Comment by felixmosh** [comment]
> @felixmosh Considering that our current CI is green, I would be very surprised if existing test actually fails.
> How does knex-stringcase work? Does it just use `postProcessResponse` and `wrapIdentifier` fields? because these should be disabled and reenabled correctly when doing internal queries.

Yeap, it uses these functions only.

**Comment by elhigu** [comment]
@felixmosh please add reproduction code for that does not use stringcase, then this will be easy to debug. Link you pasted requieres too much investigation of non-knex related code.

**Comment by elhigu** [comment]
It should be clear from the example that problem is actually with knex. Does it fail also if you run that rename column modification programmatically directly through `await knex.schema.renameColumn(...)`?

**Comment by felixmosh** [comment]
The issue is that Knex runs these provided transforms on it's internal queries.
without `knex-stringcase` there is no transforms => no error.

There is any online service that will provide me a mysql8 db?

**Comment by kibertoad** [comment]
@felixmosh My point is that knex attempts to disable transforms on internal queries, see https://github.com/knex/knex/blob/master/lib/migrate/Migrator.js#L61. If it's not happening for some reason, that's a bug.
Do you think there is anything MySQL 8-specific for this problem?
Also docker-compose is probably the most convenient option if you need one.

**Comment by elhigu** [comment]
> The issue is that Knex runs these provided transforms on it's internal queries.
without knex-stringcase there is no transforms => no error.

That was very clear already in issue description.

The problem is that you have not provided any reproduction code, which would make investigating this issue easy for knex maintainers. Please check https://github.com/knex/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

**Comment by felixmosh** [comment]
I think that it is a bug, I want to use the exact same env as mine (which is using MySql 8).

**Comment by felixmosh** [comment]
I've tried to reproduce in a separate project, and it not reproduces :\

I will close for now, sorry for the trouble.
