### ISSUE TITLE
Serverless Plugin Optimize issue 

### ISSUE THREAD

**Issue by suryacaprice** [knex/knex#3701]
https://github.com/FidelLimited/serverless-plugin-optimize/issues/79 

as mentioned in the issue we have to tweak the plugin to make knex work with Serverless Plugin Optimize can anyone raise a PR to make it as a part of the knex stable build ?

**Comment by elhigu** [comment]
I didn't see anything in that issue that should go to knex repo... it wasn't even PR nor there was any code. Please open PR with changes to knex if you need some internal changes to be applied. If they are reasonable they can be merged to the project. 

Closing as this doesn't follow issue template and its not clear what needs to be done and there is no idea with which knex version in what environment issue manifests.
