### ISSUE TITLE
Huge result set memory/overhead, solution

### ISSUE THREAD

**Issue by swlemp** [knex/knex#3711]
# Environment

Knex version: 0.20.11
Database + version: MariaDB 10.4
OS: Alpine

# Bug

1. I have a result set that is 5,000,000 rows and `BINARY(16)`.
In memory, this should be 80 MB plus overhead.  With knex, it's _800 MB_!
For some reason, streams do not fix this problem in any way.
Something was said about knex using 'fake' streams, whatever that means, not sure if true.

# Feature discussion / request

__Explain what is your use case__

Sequential row access at memory at <= 1x of total result set instead of >= 10x.

__Explain what kind of feature would support this__

`JOIN`-less `SELECT` performs superbly with big result sets so I perform joins in-code.
I incrementally reduce the size of results in the right table using the primary key of the left table.

__Give some API proposal, how the feature should work__

1. Mount a ramdisk and prepare a `random` file name
2. `SELECT INTO OUTFILE '/tmp/ramdisk/(random).csv'`
3. Use `csv-parser` to read `(random).csv` row-by-row
4. Cast columns into proper objects or primitives
5. Use `finally` and `process.on('exit')` to recover memory

In step 1, we can make a ram block device and mount it with ZFS for automatic compression.
CSV files seem to compress extremely well, so RAMDISK can be under the result set size.
(If) compression works better with binary columns in hex form, we should convert it.

In step 3, we shouldn't map fields to column names to avoid the associated overhead.
We can know the schema ahead of time, and array destructuring can be used.

**Comment by kibertoad** [comment]
Are you sure this is something that should be implemented on knex level? Sounds like you need a DB driver that properly supports streaming, and consume data that way. Or build a specific util on top of knex.

**Comment by swlemp** [comment]
Good question; I just saw https://github.com/mysqljs/mysql/issues/1370#issuecomment-196877692

Since knex says it implements streams, I think that should be implemented at the knex level since the default functionality does not work out of the box.

**Comment by briandamaged** [comment]
Yeah -- streams can be tricky sometimes.  On various occasions, I've discovered that the consumer was trying to pull all of the data from the stream at once rather than pausing / unpausing the stream.  This can cause memory to spike very quickly.

Do you happen to have a sample of the code you're using to consume the data?  We might be able to figure out a way to make sure it's processing the data in smaller chunks.

**Comment by swlemp** [comment]
```JS
readable = connection.select().from('table').where('a', 'b').stream()
	.on('data', (chunk) => console.log(chunk)) // apparently this loads everything into memory
	.on('error', console.error.bind(this));
```

I switched to the code below and it went from 800MB to 5MB.

```JS
readable = connection.select().from('table').where('a', 'b')
	.pipe(new stream.Transform({
		transform: function (chunk, encoding, callback) {
			console.log(chunk);
			callback();
		},

		objectMode: true
	}))
	.on('end', resolve)
	.on('error', reject);
```

**Comment by swlemp** [comment]
```JS
readable = connection.select().from('table').where('key', 'value').stream()
	.on('data', (chunk) => console.log(chunk)) // apparently this loads everything into memory
	.on('error', console.error.bind(this));
```

I switched to the code below and it went from 800MB to 5MB.

```JS
return new Promise((resolve, reject) => {
	let chunks = [],
		reader;

	try {
		reader = connection.select().from('table').where('key', 'value')
			.stream()
			.on('finish', () => {
				if (builder.options.stream)
					return;

				let value;

				if (builder.options.type !== 'count')
					value = chunks.length ? this.hydrate(chunks, def) : false;
				else
					value = [chunks[0][`count(*)`]];

				resolve(value);
			})
			.on('error', reject);
	} catch (error) {
		reject(error);
	}

	if (!builder.options.stream)
		reader.on('data', (chunk) => {
			reader.pause();
			chunks.push(Object.setPrototypeOf(chunk, Object.prototype), def);
			reader.resume();
		});
	else
		resolve(reader);
});
```

**Comment by swlemp** [comment]
```JS
return new Promise((resolve, reject) => {
	try {
		reader = connection.select().from('table').where('key', 'value').stream()
			.on('error', reject);

		resolve(reader);
	} catch (error) {
		reject(error);
	}
});

reader.on('data', (chunk) => console.log(chunk));
```

I switched to the code below and it went from 800MB to 5MB.

```JS
return new Promise((resolve, reject) => {
	let chunks = [],
		reader;

	try {
		reader = connection.select().from('table').where('key', 'value')
			.stream()
			.on('finish', () => {
				if (builder.options.stream)
					return;

				let value;

				if (builder.options.type !== 'count')
					value = chunks.length ? chunks : false;
				else
					value = [chunks[0][`count(*)`]];

				resolve(value);
			})
			.on('error', reject);
	} catch (error) {
		reject(error);
	}

	if (!builder.options.stream)
		reader.on('data', (chunk) => chunks.push(Object.setPrototypeOf(chunk, Object.prototype), def));
	else
		resolve(reader);
});

var reader = await Posts.find({
	conditions: [
		['active', true]
	],

	stream: true
});

reader.on('data', (chunk) => {
	reader.pause();
	// Object.setPrototypeOf(chunk, Object.prototype)
	reader.resume();
});
```

**Comment by swlemp** [comment]
I made exactly that mistake; no pause/resume wrapping the .on('data') -- thank you @briandamaged.

**Comment by briandamaged** [comment]
@swlemp : Sounds good -- I'm glad to hear the issue is resolved!

**Comment by kibertoad** [comment]
@swlemp Can you provide fixed example of a code you are using so that I could add it to the cookbook?

**Comment by swlemp** [comment]
@kibertoad We have to use a Transform stream to read the data row-by-row.

```JS
// Before (800 MB RAM)

let reader = connection.select()
	.on('data', (data) => console.log('do something'))
	.on('error', reject);

// After (5 MB RAM)

let transform = new stream.Transform({
	transform: function (chunk, encoding, callback) {
		this.push(Object.setPrototypeOf(chunk, Object.prototype));
		callback();
	},

	objectMode: true
});

let reader = connection.select()
	.on('data', (data) => console.log('do something'))
	.on('error', reject)
	.pipe(transform);

transform.on('finish', () => console.log('done'));
```
