### ISSUE TITLE
.asCallback is not a function

### ISSUE THREAD

**Issue by jehy** [knex/knex#3720]
# Environment

Knex version: 0.20.11, was not present in 0.20.10
Database + version: mariadb
OS: ubuntu16

# Bug

(node:1505) UnhandledPromiseRejectionWarning: TypeError: self.knex.select(...).from(...).where(...).andWhereRaw(...).then(...).asCallback is not a function
    at /home/shodan/shodan/node_modules/connect-session-knex/index.js:264:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Seems like bluebird was replaced with native promises somewhere, and `asCallback` was lost.

**Comment by jehy** [comment]
That's a bug in connect-session-knex:  https://github.com/llambda/connect-session-knex/issues/61
I suppose, this dependency update should be rolled back.

**Comment by kibertoad** [comment]
@jehy Bluebird was completely removed from knex codebase and we are not supporting its custom methods anymore. Still need to update parts of documentation, but there are no plans to support these functions going forward.

**Comment by kibertoad** [comment]
Bluebird was not part of an official knex api since 0.18.0: https://github.com/knex/knex/blob/master/UPGRADING.md

**Comment by elhigu** [comment]
I think we should add link to that document near to changelogs to documentation page. I didn't see any mentions about it there.

**Comment by kibertoad** [comment]
@elhigu Good idea, will do.
