### ISSUE TITLE
The "config.server" property is required and must be of type string

### ISSUE THREAD

**Issue by derencel20** [knex/knex#3725]
I have this folder structure right now.
![image](https://user-images.githubusercontent.com/17394978/76598937-e013e780-653e-11ea-8ae9-36a784dd7abd.png)

The structure is multitenant like [this](https://blog.lftechnology.com/designing-a-secure-and-scalable-multi-tenant-application-on-node-js-15ae13dda778#5989).

I put all the cached db in index.js. And when I put it as a paramter of a function which is like this:
![image](https://user-images.githubusercontent.com/17394978/76597983-c2458300-653c-11ea-8204-9276cde0f48c.png)

It yields to this error:
![image](https://user-images.githubusercontent.com/17394978/76598715-67ad2680-653e-11ea-8f0e-f83a43fd5eca.png)

**Comment by elhigu** [comment]
Please add minimized single file reproduction for the case. Doesn't look like a knex bug.

**Comment by derencel20** [comment]
We have the `/common` folder which contains the common codes for each microservice.

The error occurred when I added the code for supporting multi-tenants.

connectionResolver.js
`import { createNamespace } from 'continuation-local-storage';
import { getConnectionByURL } from '../connectionManager';

const nameSpace = createNamespace('subscribers');

export function resolve(req, res, next) {
  const { user = {} } = res;

  if (!user) {
    throw new Error('User doesn\t exist');
  }

  const { SiteSubscriber = {} } =  user;
  const { subscriberUrl } = SiteSubscriber;

  if (!subscriberUrl) {
    throw new Error('User isn\'t subscribed');
  }
  
  nameSpace.run(() => {    
    nameSpace.set('connection', getConnectionByURL(subscriberUrl));
    next();
  });
}`

connectionManager.js
`import knex from 'knex';
import { getNamespace } from 'continuation-local-storage';
import { controlDb, getUserDbConfig } from 'common';

let connection = {};

export async function cacheDb () {
  try {
    const subscribers = await controlDb('subscribers').select('*');
    connection = subscribers.map(subscriber => (
      { [subscriber.url]: knex(createKnexConfig(subscriber)) } // return value
    )).reduce((mem, subscriber) => {
      return Object.assign({ ...mem }, subscriber);
    }, {});    
  } catch (error) {
    console.log('cacheDb Error:', error);
  }
}

function createKnexConfig(subscriber) {
  const { database, host } = subscriber;
  return getUserDbConfig({ database, host });
} 

export function getConnectionByURL(url) {
  if (connection) {
    return connection[url];
  }
}

export function getConnection() {
  const nameSpace = getNamespace('subscribers');
  const conn = nameSpace.get('connection');

  if (!conn) {
    throw new Error('Connection is not set for any tenant database.');
  }

  return conn;
}`

attachRepo.js
`import { getConnection } from '../connectionManager';

export default function (repo) {
  return function (req, res, next) {
    try {
      req.repo = repo.connect({ db: getConnection() });
      next();
    } catch (error) {
      next(error);
    }
  };
}
`

**Comment by derencel20** [comment]
It is then passed to middleware of every MS.

```
import express from 'express';
import morgan from 'morgan';
import helmet from 'helmet';
import bodyParser from 'body-parser';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import { configure, corsConfig } from 'common';
import { getPort } from 'common/constants/ports';
import * as connectionResolver from 'common/multi-tenant/middleware/connectionResolver';
import attachRepo from 'common/multi-tenant/middleware/attachRepo';
import { cacheDb, } from 'common/multi-tenant/connectionManager';
import { CASE_PATH } from 'common/paths/case.path';
import { ms as msErrorHandler } from 'common/errorHandler';
import tokenAuthentication from 'common/middleware/tokenAuthentication';
import repository from '../repository';
import dateUtils from 'common/dateUtils';
import caseServices from '../api';

const app = express();

const start = async ({ logger }) => {
  const middlewares = [];
  // const middlewares = [dateUtils];
  await cacheDb();
  
  app.configure = configure;
  app.set('etag', false);
  app.use(cors(corsConfig));
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({ extended: true }));
  app.use(cookieParser());
  app.use(morgan('dev'));
  app.use(helmet());
  app.use(tokenAuthentication);
  app.use(connectionResolver.resolve);
  app.use(attachRepo(repository));
  app.use(CASE_PATH, ...middlewares, caseServices);
  app.use(msErrorHandler);
  app.listen(getPort('CASE'));
  logger.info(`App running in http://localhost:${getPort('CASE')}`);
};

module.exports = Object.assign({}, { start, app });
```

**Comment by derencel20** [comment]
please note that the `common` absolute path points to `common/dist`.

**Comment by derencel20** [comment]
![image](https://user-images.githubusercontent.com/17394978/76607915-bb743b80-654f-11ea-8e89-21935fda7d70.png)
![image](https://user-images.githubusercontent.com/17394978/76607945-c75ffd80-654f-11ea-8387-76fb32835025.png)

**Comment by elhigu** [comment]
Thats very nice! Also looks like you completely ignored my earlier comment. Good luck 👍 I'm unsubscribing from the issue to not get any more emails about it. You could try stackoverflow or some other media to find if someone likes to debug your app.

**Comment by kibertoad** [comment]
@derencel20 The only relevant part is config you pass to knex, and error tells you everything you need to know about what you are doing wrong.

**Comment by derencel20** [comment]
> @derencel20 The only relevant part is config you pass to knex, and error tells you everything you need to know about what you are doing wrong.

I've passed the same config and run it to the microservice itself instead of common, it works without problem, but if it's passed to the knex instance of  common(transpiled), the error occurs.

**Comment by kibertoad** [comment]
do console.log of config just before you pass it and get error, and share it here
