### ISSUE TITLE
These dependencies were not found where using knex with sqlite client

### ISSUE THREAD

**Issue by Dahkenangnon** [knex/knex#3727]
# Environment

Knex version:  "knex": "^0.20.11"
Database + version: "sqlite3": "^4.1.1"
OS: Winows 10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I initialize a new Knex with client: "sqlite" but i get an error specifying that other dialect are missing:

_My code_
```
class Database  {
  constructor( pathToDbFile ) {
    this.knex = require('knex')({
      client: 'sqlite3',
      connection: {
        filename: pathToDbFile
      }
    }); 
  }
}
module.exports =  Database;
```

2. Error message

These dependencies were not found:

* mssql in ./node_modules/knex/lib/dialects/mssql/index.js
* mssql/lib/base in ./node_modules/knex/lib/dialects/mssql/index.js
* mssql/package.json in ./node_modules/knex/lib/dialects/mssql/index.js
* mysql in ./node_modules/knex/lib/dialects/mysql/index.js
* mysql2 in ./node_modules/knex/lib/dialects/mysql2/index.js
* oracledb in ./node_modules/knex/lib/dialects/oracledb/index.js
* pg in ./node_modules/knex/lib/dialects/postgres/index.js, ./node_modules/knex/lib/dialects/redshift/index.js
* pg-query-stream in ./node_modules/knex/lib/dialects/postgres/index.js
* tedious in ./node_modules/knex/lib/dialects/mssql/index.js

To install them, you can run: npm install --save mssql mssql/lib/base mssql/package.json mysql mysql2 oracledb pg pg-query-stream tedious       
 ERROR  Build failed with errors.
error Command failed with exit code 1.

**Comment by maximelkin** [comment]
Which version of npm and node are you using?

**Comment by Dahkenangnon** [comment]
- npm : V 6.14.2
- node: v13.6.0

**Comment by elhigu** [comment]
Are you using webpack or something like that? Please add complete reproduction code with installation and running the test app.

**Comment by Dahkenangnon** [comment]
1. Yes i'm using Vue Js (Vue-Cli 3) with Vue CLI Plugin Electron Builder
Vue cli from https://cli.vuejs.org
And Vue CLI Plugin Electron Builder from https://github.com/nklayman/vue-cli-plugin-electron-builder


## 2. My Package.json:

```
{
  "name": "appname",
  "productName": "AppName",
  "description": "Build something for my village",
  "author": {
    "name": "Justin Dah-kenangnon",
    "email": "dah.kenangnon@gmail.com"
  },
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "electron:generate-icons": "electron-icon-builder --input=./public/icon.png --output=build --flatten"
  },
  "main": "background.js",
  "dependencies": {
    "@vue/composition-api": "^0.4.0",
    "bluebird": "^3.7.2",
    "core-js": "^3.6.4",
    "electron-log": "^4.0.7",
    "electron-store": "^5.1.1",
    "feathers-vuex": "^3.7.0",
    "knex": "^0.20.11",
    "socket.io-client": "^2.3.0",
    "sqlite3": "^4.1.1",
    "vue": "^2.6.11",
    "vue-router": "^3.1.5",
    "vuetify": "^2.1.0",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@mdi/font": "^4.9.95",
    "@vue/cli-plugin-babel": "~4.2.0",
    "@vue/cli-plugin-eslint": "~4.2.0",
    "@vue/cli-service": "~4.2.0",
    "babel-eslint": "^10.0.3",
    "electron": "^6.0.0",
    "electron-icon-builder": "^1.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.1.2",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-electron-builder": "~1.4.5",
    "vue-cli-plugin-vuetify": "~2.0.4",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.3.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
````

## 3. My vue.config.js:
```
//vue.config.js
module.exports = {
  transpileDependencies: ["vuetify", "feathers-vuex"],
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        extraResources: ['src/res/'] 
      },
    }
  }
};

``` 

## 4. The code i've tried:


* Note: I've comment the previent code in the first comment above and try this but i continue to get the same error

```


const knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: './data.db',
  },
});

// Create a table
knex.schema
  .createTableIfNotExists('users', function(table) {
    table.increments('id');
    table.string('user_name');
  })

  // ...and another
  .createTableIfNotExists('accounts', function(table) {
    table.increments('id');
    table.string('account_name');
    table
      .integer('user_id')
      .unsigned()
      .references('users.id');
  })

  // Then query the table...
  .then(function() {
    return knex('users').insert({ user_name: 'Tim' });
  })

  // ...and using the insert id, insert into the other table.
  .then(function(rows) {
    return knex('accounts').insert({ account_name: 'knex', user_id: rows[0] });
  })

  // Query both of the rows.
  .then(function() {
    return knex('users')
      .join('accounts', 'users.id', 'accounts.user_id')
      .select('users.user_name as user', 'accounts.account_name as account');
  })
 
  // .map over the results
  .then(function(row) {
    console.log(row);
  }) 

  // Finally, add a .catch handler for the promise chain
  .catch(function(e) {
    console.error(e);
  });
```
## 5. The error i got:

```
 ERROR  Failed to compile with 10 errors                                                                                              3:11:18 PM

These dependencies were not found:

* mssql in ./node_modules/knex/lib/dialects/mssql/index.js
* mssql/lib/base in ./node_modules/knex/lib/dialects/mssql/index.js
* mssql/package.json in ./node_modules/knex/lib/dialects/mssql/index.js
* mysql in ./node_modules/knex/lib/dialects/mysql/index.js
* mysql2 in ./node_modules/knex/lib/dialects/mysql2/index.js
* oracledb in ./node_modules/knex/lib/dialects/oracledb/index.js
* pg in ./node_modules/knex/lib/dialects/postgres/index.js, ./node_modules/knex/lib/dialects/redshift/index.js
* pg-query-stream in ./node_modules/knex/lib/dialects/postgres/index.js
* tedious in ./node_modules/knex/lib/dialects/mssql/index.js

To install them, you can run: npm install --save mssql mssql/lib/base mssql/package.json mysql mysql2 oracledb pg pg-query-stream tedious       
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by elhigu** [comment]
Ok, this not not really a knex bug. You need to setup packer somehow to replace missing/unneeded requires with stubs. Closing as not knex bug, you can keep on resolving issues here though if someone is able to help you. Probably people in vue electron builder community knows more about how this should be handled.

**Comment by Dahkenangnon** [comment]
# If someone goes through here, here is the solution


```
module.exports = {
  transpileDependencies: ["vuetify"],
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
//Add also your database location
        extraResources: ['src/res/'] 
      },
 //This line: add knex and sqlite3
      externals: ['knex','sqlite3'],
    }
  }
};
```

**Comment by beamodd** [comment]
> # 如果有人经过这里，这是解决方案
> ```
> //vue.config.js
> 
> module.exports = {
>   transpileDependencies: ["vuetify"],
>   pluginOptions: {
>     electronBuilder: {
>       builderOptions: {
> //Add also your database location
>         extraResources: ['src/res/'] 
>       },
>  //This line: add knex and sqlite3
>       externals: ['knex','sqlite3'],
>     }
>   }
> };
> ```

感谢老铁

**Comment by maximran800** [comment]
> # If someone goes through here, here is the solution
> ```
> //vue.config.js
> 
> module.exports = {
>   transpileDependencies: ["vuetify"],
>   pluginOptions: {
>     electronBuilder: {
>       builderOptions: {
> //Add also your database location
>         extraResources: ['src/res/'] 
>       },
>  //This line: add knex and sqlite3
>       externals: ['knex','sqlite3'],
>     }
>   }
> };
> ```

Thank you very much!! 
I also face similiar problem. I only installed knexjs and sqlite3, but it ask for all other DB installation. 
installing them leads to different problem.

**Comment by BroJenuel** [comment]
> # If someone goes through here, here is the solution
> ```
> //vue.config.js
> 
> module.exports = {
>   transpileDependencies: ["vuetify"],
>   pluginOptions: {
>     electronBuilder: {
>       builderOptions: {
> //Add also your database location
>         extraResources: ['src/res/'] 
>       },
>  //This line: add knex and sqlite3
>       externals: ['knex','sqlite3'],
>     }
>   }
> };
> ```

How to configure this in build, or in production mode. It seems that I cant make it work in production.
