### ISSUE TITLE
Feature: alias to table names

### ISSUE THREAD

**Issue by calebeaires** [knex/knex#3733]
# Environment

Knex version: 0.20.10
Database + version: MYSQL
OS: MacOS

# Feature discussion / request

1. Explain what is your use case

Some times we need to build complex querys. To do so, we make use of table alias names like above:

```sql
SELECT t1.houses, t2.name, t3.baName 
FROM homes t1
LEFT JOIN countries t2 ON t2.co = t1.co
LEFT JOIN countries t3 ON t3.ba = t1.ba
```

2. Explain what kind of feature would support this
On this case, we need to call join twice even if we do it on the same table. This use of case is very common in some data warehouses

**Comment by lorefnon** [comment]
Does [aliasing support](http://knexjs.org/#Builder-as) in knex solve your use case ?

**Comment by calebeaires** [comment]
I spent some time on documentation. I figure it out. Thanks

**Comment by taybin** [comment]
@calebeaires What was the solution though?  The `as()` function documentation says it only works on subqueries.

**Comment by elhigu** [comment]
```
knex('homes as t1')...

or

knex({t1: 'homes '})...
