### ISSUE TITLE
Hide errors message for production?

### ISSUE THREAD

**Issue by alnorris** [knex/knex#3734]
Is there any way to hide errors messages( information shows my stuff about my schema.) from knex throws? I'm using apollo graphql server, in which errors are naturally thrown when responding errors. I can always wrap it in a catch or try, but it would be safer is this option is turned off automatically.

**Comment by kibertoad** [comment]
@alnorris Do you mean literal errors or just warnings? Ignoring errors is not really a good idea, but in either case: http://knexjs.org/#Installation-log

**Comment by elhigu** [comment]
> Is there any way to hide errors messages( information shows my stuff about my schema.) from knex throws? I'm using apollo graphql server, in which errors are naturally thrown when responding errors. I can always wrap it in a catch or try, but it would be safer is this option is turned off automatically.

Knex doesn't touch errorss returned from database driver so you really should not return errors with message info from API directly if you want that no information about the schema is exposed.

Pretty much the same way, that one would do with rest api, so that 500 error in production mode should not contain stacktrace etc.

**Comment by alnorris** [comment]
Is there no way to transform the error I get back before it throws from knex? (without having to wrap every knex query).

**Comment by elhigu** [comment]
no, as far as I can think of. Maybe extending / overriding querybuilder `.then` method could work... at least mostly.

**Comment by wubzz** [comment]
For a global approach mutating the error objects by using event listeners could possibly work, but might also be race conditions, not 100% sure. Also not something to recommend. Would be a lot better to just handle them internally in your App rather than sending them as a response.

```javascript
knex.on('query-error', (error) => {
    //Mutate error
});
knex.on('error', (error) => {
    //Mutate error
});
```
