### ISSUE TITLE
How to Find matching string in array

### ISSUE THREAD

**Issue by AhmadRaza786** [knex/knex#3735]
Knex has the ability to find records by matching string in the target column. just like [issue 2009](https://github.com/knex/knex/issues/2009). But i have nested schema like
```
{
profiles: [
    {name: 'test 1' },
    {name: 'test 2'}
  ]
}
```
And i want to find the records where search text is like name. How to do that ?

**Comment by elhigu** [comment]
Knex usage questions should go to stackoverflow. Issues are for development / bugs reports.

`await knex('profiles').where('name', 'test 1')`should work. check documentation page too.
