### ISSUE TITLE
Fail to acquire connection after knex upgrade

### ISSUE THREAD

**Issue by PradeepaSoundar** [knex/knex#3739]
# Environment

Knex version: 0.2.11
Database + version: pg - 9.6
OS: node 8.2.1

# Bug

Update my knex version from 0.14.0 to 0.20.11, after that application fail to acquire DB connection. Below shows error log and knex config 

```
C:\Padda\Work\Source\inj-service\node_modules\knex\lib\client.js:292
      ...this.getPoolSettings(config.pool),
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Padda\Work\Source\inj-service\node_modules\knex\lib\knex.js:2:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

knex-config.js

```
'use strict';

const knex = require('knex')({
	client: 'postgres', // Changed to postgresql and tried didn't work
	connection: process.env.DATABASE_URL,
	debug: false,
	pool: {
		min: +process.env.DB_CONNECTION_POOL_MIN || 2,
		max: +process.env.DB_CONNECTION_POOL_MAX || 100
	}
});

module.exports = knex;
```

Changed knex-config.js to .ts file got error which is mentioned here #https://github.com/knex/knex/issues/2998 I tried all possible solution given here, didn't work. Am i doing something wrong?
Same knex config file was working before update the version

**Comment by elhigu** [comment]
Are you sure you are using node 8.2.1? Sounds like  node is not parsing `async () => {}` syntax correctly.

```
Mikaels-MacBook-Pro:Projects mikaelle$ echo 'Promise.resolve().then(async (foo) => {})' > test.js
Mikaels-MacBook-Pro:Projects mikaelle$ nvm use 8
^[[A^[[ANow using node v8.10.0 (npm v6.4.1)
Mikaels-MacBook-Pro:Projects mikaelle$ node test.js 
Mikaels-MacBook-Pro:Projects mikaelle$ nvm use 6
Now using node v6.14.4 (npm v3.10.10)
Mikaels-MacBook-Pro:Projects mikaelle$ node test.js 
/Users/mikaelle/Projects/test.js:1
(function (exports, require, module, __filename, __dirname) { Promise.resolve().then(async (foo) => {})
                                                                                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
Mikaels-MacBook-Pro:Projects mikaelle$ 
```

**Comment by PradeepaSoundar** [comment]
> Are you sure you are using node 8.2.1? Sounds like node is not parsing `async () => {}` syntax correctly.
> 
> ```
> Mikaels-MacBook-Pro:Projects mikaelle$ echo 'Promise.resolve().then(async (foo) => {})' > test.js
> Mikaels-MacBook-Pro:Projects mikaelle$ nvm use 8
> ^[[A^[[ANow using node v8.10.0 (npm v6.4.1)
> Mikaels-MacBook-Pro:Projects mikaelle$ node test.js 
> Mikaels-MacBook-Pro:Projects mikaelle$ nvm use 6
> Now using node v6.14.4 (npm v3.10.10)
> Mikaels-MacBook-Pro:Projects mikaelle$ node test.js 
> /Users/mikaelle/Projects/test.js:1
> (function (exports, require, module, __filename, __dirname) { Promise.resolve().then(async (foo) => {})
>                                                                                            ^
> 
> SyntaxError: Unexpected token (
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.runMain (module.js:611:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:160:9)
> Mikaels-MacBook-Pro:Projects mikaelle$ 
> ```

Yes i'm using right version of node
 
![image](https://user-images.githubusercontent.com/3932825/77076549-faa40000-6a19-11ea-9aad-991abe98ed92.png)

**Comment by kibertoad** [comment]
@PradeepaSoundar Is switching to a newer version of Node 8 an option for you? Looks like destructuring is not present in older version that you use.

**Comment by PradeepaSoundar** [comment]
> @PradeepaSoundar Is switching to a newer version of Node 8 an option for you? Looks like destructuring is not present in older version that you use.

Node 8.2.1 is the maximum node version i can use, due to some limitations in our deployment environment and also i need to upgrade knex version (0.19.5+). Is there any way i can achieve this?

**Comment by kibertoad** [comment]
@PradeepaSoundar Well. If updating Node is completely out of the question, you could submit a PR that would replace all usages of ... operator that are incompatible with Node 8 in offending file against branch 0.20, I'm fine with using older syntax in maintenance branch, as long as it doesn't make it to master (which is dropping Node 8 support soon anyway).
First I would recommend modifying client.js file in node_modules locally to see it if that helps.

**Comment by PradeepaSoundar** [comment]
@kibertoad Thank you for suggestion. Finally we decide to remove ... operator from knex package and maintain local copy within our project and I'm closing this issue.

**Comment by kibertoad** [comment]
@PradeepaSoundar I'm not sure that's a good long-term solution. If you would raise a PR with this change, it could be incorporated within official 0.20 branch.
