### ISSUE TITLE
Update with .update().where().orderBy().limit() issues incomplete query

### ISSUE THREAD

**Issue by danielzurawski** [knex/knex#374]
Hello,

I possibly found a bug with issuing chained update queries, but before I start investigating a fix I wanted to verify whether this behaviour is desired or not.

As in the title, issuing an .update() with the following query in the sequence in title:

return knex(TABLE_NAME)
        .update(record)
        .where('articleId', articleId)
        .orderBy('id', 'DESC')
        .limit(1)

issues this SQL query: 
sql: 'update `articles` set `wpsData` = ? where `articleId` = ?',
  bindings: ...

My current workaround: 

knex(TABLE_NAME)
        .update(record)
        .where(knex.raw('articleId = ' + articleId + ' ORDER BY id DESC LIMIT 1'))

this seems to be correctly issuing the following query: 

sql: 'update `articles` set `wpsData` = ? where articleId = 2640556 ORDER BY id DESC LIMIT 1',
  bindings: ...

**Comment by sq-ashkan** [comment]
I did this with Knex + psql : 
```
if (w[0]) {
    db.from('cards')
    .where(
        'cards.box_id', req.body.box_id
    ).limit(5).orderBy('cards.id')
    .then(data => {
        const Ids = data.map(x => x.id );
        const preId = Ids.map(a => ashkan(a) );
        function ashkan(c) {
        db.from('cards')
        .where(
            'cards.id', c
        )
        .update({ position: 2 })
        .returning('email').then(r => {
            console.log('executed');
        })
    }
        res.status(200).json('done');
    })
} 
```
