### ISSUE TITLE
Upgrade dependency mkdirp - it is using an outdated version adding an unnecessary package for the users

### ISSUE THREAD

**Issue by kabirbaidhya** [knex/knex#3740]
Knex uses an outdated version of `mkdirp` package in it's `dependencies`.
https://github.com/knex/knex/blob/998c92ca97c323c7e7c1cb8788dd4c5e4ac3e6bd/package.json#L40

Can we update this to use the latest version offered by the package [1.0.3](https://www.npmjs.com/package/mkdirp/v/1.0.3)?

Please confirm and I can do a PR for this. It won't be a big [change](https://github.com/knex/knex/search?q=mkdirp&unscoped_q=mkdirp).

**Why upgrade?**
1. The current version `0.5.1` is deprecated and not on their supported list of versions. Emits this message:
   ```
   warning mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
   ```
2. It requires a dependency `minimist` which has a vulnerability. The new version `1.0.3` has [zero dependencies](https://www.npmjs.com/package/mkdirp/v/1.0.3), so it's an unnecessary package for us and it will be removed. See this:
   ![image](https://user-images.githubusercontent.com/3315763/77171813-188a6700-6ae5-11ea-9d34-58a5fe4f029c.png)

**Comment by kibertoad** [comment]
@kabirbaidhya It can be done in master, but that'll go in next major release (likely 1.0.0), since it dropped compatibility with Node 8.

**Comment by kabirbaidhya** [comment]
Sure, will do  a PR.
