### ISSUE TITLE
MSSQL - TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full

### ISSUE THREAD

**Issue by hardysabs2** [knex/knex#3750]
Knex version: 0.19.5
Database: mssql
OS: Win 10 Pro

I have two nodejs processes running - one with

```
const knexLogging = Knex({
  client: "mssql",
  connection: {
    host: process.env.LOGGING_MSSQL_DB_SERVER,
    user: process.env.LOGGING_MSSQL_DB_USER,
    password: process.env.LOGGING_MSSQL_DB_PASSWORD,
    port: Number.parseInt(process.env.LOGGING_MSSQL_PORT, 10),
    database: process.env.LOGGING_DATABASE,
    encrypt: true,
    stream: true,
    connectionTimeout: 30000,
    requestTimeout: 30000
  }
});

```

which is running insertions to a table at about 2/s

Another with

```
const knexLogging = Knex({
  client: "mssql",
  connection: {
    host: process.env.LOGGING_MSSQL_DB_SERVER,
    user: process.env.LOGGING_MSSQL_DB_USER,
    password: process.env.LOGGING_MSSQL_DB_PASSWORD,
    port: Number.parseInt(process.env.LOGGING_MSSQL_PORT, 10),
    database: process.env.LOGGING_DATABASE,
    encrypt: true,
    stream: true,
    connectionTimeout: 300000,
    requestTimeout: Infinity
  }
});

```
which runs every 5 minutes and makes about 6 or 7 calls to a stored procedure
which executes a deletion and an insertion with a try catch, SP called like this.

...
```
let query = "EXEC ... ?, ?, ? "; // attribute value hours
          knexLogging
            .raw(query, [...])
            .then(null);
```
...

From time to time this second process throws this.

Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call

I don't understand how having a transaction anywhere would make any difference to a connection timeout.

Any ideas what I am doing wrong?

**Comment by elhigu** [comment]
Sounds like you are running too many parallel transactions.  I suppose that `requestTimeout: Infinity` may cause that some long running queries will run minutes or hours and in that case the transaction where those slow queries are reserving connection from pool for the whole time. 

If you think this is a bug, please add minimal reproduction code for the problem.

**Comment by hardysabs2** [comment]
Thank you so much.  I appreciate your response.

I think you are probably right in your description.  The stored procedure executes a potentially long running deletion.  I understand this deletion will run in an implicit transaction.  Every few hours, the stored procedure is executed from knex several times without waiting.  It is necessary I do not await because if I await, the framework from which it is called (which I have no choice about) will kill it and fail itself.  Also I set Infinity because I must have these deletions complete and it is difficult to estimate how long they may last.

Do you happen to know how I might be able find out how many parallel transactions is too many and if there is any way to increase this number?

**Comment by elhigu** [comment]
Actually the case you described doesn't sound anything specific to transactions.... It just seems that your pool runs out of connections. You can check pool status from `knex.client.pool` object. By default there is only 10 connections reserved in pool so you can increase that for example to be 100 or so.

Connection pool docs are found here for more information: https://github.com/vincit/tarn.js/
