### ISSUE TITLE
Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by tiodospc** [knex/knex#3759]
every time the command is run:  `npx knex migrate:latest` to create a table this error happens:

**Error: SQLITE_CANTOPEN: cannot open the database file**

my code is like this:

**knexfile.js**
```
 development: {
    client: 'sqlite3',
    connection: {
      filename: './src/database/db.sqlite'
    },
    migrations: {
      directory: './scr/database/migrations'
    },
    useNullAsDefault: true,
  },

```
20200324203555_create_ongs.js

```
exports.up = function(knex) {
  return  knex.schema.createTable('ongs', function(table){
        table.string('id').primary();
        table.string('nome').notNullable();
        table.string('email').notNullable();
        table.string('whatsapp').notNullable();
        table.string('city').notNullable();
        table.string('uf', 2).notNullable();

    });
};

exports.down = function(knex) {
  return knex.schema.dropTable('ongs')
};


```
what do i need to do to fix this error?

**Comment by ricardograca** [comment]
There could be any number of reasons. You can start here: http://letmegooglethat.com/?q=SQLITE_CANTOPEN%3A+cannot+open+the+database+file

**Comment by tiodospc** [comment]
if I had found something that would help me this issue would not exist!

**Comment by tiodospc** [comment]
> There could be any number of reasons. You can start here: http://letmegooglethat.com/?q=SQLITE_CANTOPEN%3A+cannot+open+the+database+file

if I had found something that would help me this issue would not exist!!

**Comment by elhigu** [comment]
Doesn's seem to be knex bug.
