### ISSUE TITLE
Remove peerDependencies for NPM 7

### ISSUE THREAD

**Issue by analytik** [knex/knex#3761]
NPM v7 will automatically install peerDependencies. While it wouldn't break anything to leave them there, it might be better to just remove them to avoid clients having to install a lot of unneeded packages.

**Comment by elhigu** [comment]
Isn't there any way to tell that they are optional peer deps? If not it indeed sounds like it is better to remove them.

**Comment by maximelkin** [comment]
They marked optional in peerDependenciesMeta

**Comment by analytik** [comment]
Ah, sorry, haven't noticed this landed in npm 6.11. All good then! :)
