### ISSUE TITLE
Support for MSSQL version above 4.1.0

### ISSUE THREAD

**Issue by hiukky** [knex/knex#3762]
Well, have we had any news for that? 

https://github.com/knex/knex/blob/232fe9f1517dba927f6a3a1fb1b8842d7c0a4007/src/dialects/mssql/index.js#L52-L70

**Comment by elhigu** [comment]
check a bit more recent version of source codes... https://github.com/knex/knex/blob/master/lib/dialects/mssql/index.js#L65
