### ISSUE TITLE
I'm trying to use Knex in an electron app, and Webpack is throwing errors.

### ISSUE THREAD

**Issue by Aurailus** [knex/knex#3766]
# Environment

Knex version:
Database + version: 0.20.13
OS: Ubuntu 16.04

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
When trying to build my electron app, I get errors in the console relating to webpack and Knex. Specifically it tries to run a command to install sqlite3, which is already installed.

2. Error message
```
(node:8413) UnhandledPromiseRejectionWarning: Error: Cannot find module './sqlite3/index.js'
    at webpackContextResolve (/home/aurailus/Documents/Projects/Aether/Aether/dist/main.js:10183:11)
    at webpackContext (/home/aurailus/Documents/Projects/Aether/Aether/dist/main.js:10178:11)
    at Knex (/home/aurailus/Documents/Projects/Aether/Aether/dist/main.js:12267:109)
    at new LocalStore (/home/aurailus/Documents/Projects/Aether/Aether/dist/main.js:50675:17)
    at new ImapAccount (/home/aurailus/Documents/Projects/Aether/Aether/dist/main.js:50564:23)
    at App.loadAccounts (/home/aurailus/Documents/Projects/Aether/Aether/dist/main.js:50521:20)
(node:8413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8413) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lorefnon** [comment]
You will need to: 

1. Ensure that native modules (in this case sqlite) are compiled against the electron's v8 headers and not node's v8 headers (as they can be different versions). Refer [this guide](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) or if you are using [electron-builder](https://www.electron.build/) the install-app-deps step described in this [Quickstart](https://www.electron.build/#quick-setup-guide) will take care of that for you. 

2. Add sqlite3 as an [external](https://webpack.js.org/configuration/externals) in webpack. If you use [electron-webpack](https://webpack.electron.build/) and have sqlite3 in your dependencies (and not devDependencies) this will be taken care of for you automatically.

**Comment by Aurailus** [comment]
Thank you so much, following the first guide you sent worked.
