### ISSUE TITLE
Switch to v1 uuids since 0.20.5 causes issues when mocking global date

### ISSUE THREAD

**Issue by benwiggins** [knex/knex#3774]
The switch from v4 to v1 uuids for _knexQueryUids in v0.20.5 (https://github.com/knex/knex/pull/3596) actually caused us a few issues.

Long story short, it is trivial to artificially trigger uuidv1's 10M operations/sec limit when running a longish test suite with a mocked date object that does not advance. Our use of knex.raw() was somewhere in the thousands when our integration tests started throwing errors.

Not sure if it's something you want to address and I did work around it, but given that uuidv4's performance was claimed not to be a bottleneck in practice (https://github.com/knex/knex/issues/3595), it is arguable that knex suddenly becoming time-sensitive in a minor release is an order of magnitude worse than the original problem.

**Comment by elhigu** [comment]
Perf was not a reason for that change. If you have better solution for #3596 please share or provide PR. Though this is not really a bug, since it cannot happen unless you clock is stopped :)

**Comment by benwiggins** [comment]
I agree that’s it's not a bug per se, but to play devil’s advocate, what would be the actual implications of reverting to v4?

If performance is not an issue, the fact that v4() was blocking the event loop to gain a measly 16 bytes of entropy synchronously was never really a problem to begin with, other than the desire for a warning message (that has to be explicitly enabled) to disappear. You stated as such in https://github.com/knex/knex/issues/3595.

Despite technically blocking the event loop for a minuscule amount of time, synchronous acquisition of such a small amount of data is generally considered acceptable, is preferred by the uuid devs (https://github.com/uuidjs/uuid/issues/150) and substantially faster than the overhead of running asynchronously (https://www.npmjs.com/package/nanoid#benchmark).

Sure, v1 is faster and non-blocking, and my issue only manifests itself when the global Date is not guaranteed to be ticking, but I would argue that it is not unreasonable to consider that Knex would be used within an integration test suite, and that certain parts of that suite might involve mocking out the global date.

Even when continually mocking and restoring or advancing the date between each test, it takes just 10,000 calls to v1() prior to advancing a date, to trigger the error. That is many orders of magnitude lower than any level of perceived gain from switching to v1 in the first place. At 10,000 iterations, uuidv1 (19ms) vs uuidv4 (34ms) is unimportant, and the v4-like nanoid (21ms) almost as fast.

Again, I accept it is not a bug, but I do believe in challenging a change that has brought questionable actual benefit, but introduced actual challenges in common testing scenarios as well as subtly introduced a reliance on the global Date ticking over within ~19ms.

**Comment by kibertoad** [comment]
nanoid looks great, that would get my vote, and if there is common agreement, I can do the change

**Comment by elhigu** [comment]
Do we even need UUID there or would some random id prefix + counter work just fine? Random prefix would make sure that running multiple processes will have different IDs generated. That way it would be faster and we could inherit some additional information about query order from it and wouldn't need external dependencies.

**Comment by kibertoad** [comment]
That also works. I can implement that as well.

**Comment by cipacda** [comment]
Is ther eany progress expected on this issue?

**Comment by kibertoad** [comment]
thanks for the ping, will work on it tomorrow

**Comment by kibertoad** [comment]
Fix released in 0.21.10
