### ISSUE TITLE
MigrationLocked: Migration table is already locked

### ISSUE THREAD

**Issue by cabral-ricardo** [knex/knex#3780]
# Environment

Knex version: 0.20.13
Database + version: 0.20.13
OS: ubuntu 18.04

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I would like to run my tests using jest with nodejs in sqllite3. When i'm running with npm test my project i got error. I have two migrations that represent creating two tables    

2. Error message
```
 console.log node_modules/knex/lib/logger.js:44
      Can't take lock to run migrations: Migration table is already locked
    console.log node_modules/knex/lib/logger.js:44
      If you are sure migrations are not running you can release the lock manually by deleting all the rows 
= require(migrations lock table: knex_migrations_lock
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
const request = require("supertest");
const app = require("../../src/app");
const connection = require("../../src/dataBase/connection");

describe("test", () => {
  beforeEach(async () => {
    await connection.migrate.rollback();
    await connection.migrate.latest();
  });

  afterAll(async () => {
    await connection.destroy();
  });

  it("Should be able to create a new xxx", async () => {
       const response = await request(app)
      .post("/")
      
    expect(response.body).toHaveProperty("id");
    expect(response.status).toBe(200);
  });

**Comment by elhigu** [comment]
I suppose you have ran migrations and at some point they failed and crashed your process completely which prevented migration lock from being removed.

Btw. running 

```
    await connection.migrate.rollback();
    await connection.migrate.latest();
```

before every test will be horribly slow.

You'll be better of just dropping the DB and recreating it and running migrations only once in `beforeAll` and then just truncate all tables and sequences in `beforeEach`. It will be 1000x faster and actually is significant when you have hundreds of tests.

**Comment by kibertoad** [comment]
Jest is running tests in parallel by default. If there are multiple tests trying to do something with DB, you will get concurrency issues.
try using --runInBand option and see if that helps.

**Comment by cabral-ricardo** [comment]
great tips @elhigu i changed my tests to delete/migrate on beforeAll() e truncate on beforeEach the rows of tables.
And thanks  @kibertoad i put in `test: "jest --runInBand"` and its work. I will close this issue.

:rocket: :rocket: :rocket: :rocket:

**Comment by oyurisousa** [comment]
in vitest can use the flags '--no-file-parallelism ' or '--fileParallelism=false'.

For more:
https://vitest.dev/config/#fileparallelism
