### ISSUE TITLE
NPM latest version mismatch with Github 

### ISSUE THREAD

**Issue by reachmehere89** [knex/knex#3781]
In NPM, latest version of Knex is mentioned as 0.20.13 but in github latest release is 0.20.12.
Also looks like latest master branch code is not published on NPM. Any plan when to do this ?

**Comment by kibertoad** [comment]
Thanks, just created a new tag.

Still need to cherry-pick change from master to 0.20 branch to make a new release. Full-blown release of master with breaking changes will happen later.

**Comment by kibertoad** [comment]
Hopefully we can do release tomorrow or the day after that, we need some kind of working CI to make sure knex still works as expected, and Travis integration broke down :-/

**Comment by kibertoad** [comment]
@reachmehere89 0.20.14 is out now.
