### ISSUE TITLE
Seed data in subfolders of config folder

### ISSUE THREAD

**Issue by lioaslan** [knex/knex#3786]
Hi,
I wonder that I can seed data from many sub-folders of the folder I config to seed?
```
seed/
     user/
          userAccount.js
          userProfile.js
     pagekage/
          pagekage1.js
          pagekage2.js
....
```
I have to put file in sub-folder because my project I'm working is so complicate and sub-folder is required for clarity.

Thanks for any helps.
________
So sorry for my poor English

**Comment by kibertoad** [comment]
Assuming you have configuration like this:
```
development: {
  client: ...,
  connection: { ... },
  seeds: {
      directory: './seed'
  }
}
```

You can use multiple directories:

development: {
  client: ...,
  connection: { ... },
  seeds: {
      directory: ['./seed/user', 'seed/pagekage']
  }
}
```

**Comment by kibertoad** [comment]
@syphuongcuong3 Note that very old knex versions don't support that, so if that fails to work, consider updating knex.

**Comment by kibertoad** [comment]
Actually, I double-checked and it seems that only migrations support multiple folders for now. I'll give it a shot today or tomorrow evening, there's an incomplete PR for this: #3357

**Comment by syphuongcuong3** [comment]
Assume that, I have 10 or 20 sub-folders of user/ and 20 sub-folder of package/
So I have to update 30-40 strings in directory
I hope that seed can run in file inside sub-folder of the directory.
Thanks

**Comment by lioaslan** [comment]
Hope you fix it soon.
Thanks so much

**Comment by mdartic** [comment]
Any news on this @kibertoad ?
I need this feature for a project I currently have, I'm dividing seeds in several folders.
Could I help on the PR #3357 ?

**Comment by kibertoad** [comment]
thank you for the ping, drowning in multiple workstreams. author of that PR claimed that approach ended up not working. if you could investigate, and finish his work with CLI test, I'll make sure to review urgently.

**Comment by mdartic** [comment]
Ok, I'll give it a try.
I don't know the knex codebase, so I'm gonna look on the "migration" side (as you said it was already working).
Any info about why the PR approach wasn't the good one ?
Do you think we have to implement the subfolder drilling too ?
Is this feature already implemented in the migration one ?

**Comment by kibertoad** [comment]
@mdartic I would imagine that quite a bit of code that is currently duplicated between migrations and seeds will have to be synced up. Don't see a reason why it wouldn't work after that.

**Comment by kibertoad** [comment]
And yes, it is implemented for migrations, and you should be able to copy over most of the implementation. bonus points for extracting common code

**Comment by kibertoad** [comment]
Released in 0.21.3

**Comment by broom9** [comment]
Hi,

We found this breaking change when upgrade to 0.21.3.

Our seed folder structure actually uses the assumption that subfolders are not treated as seed files.

```
seeds
├── data
│   ├── users.js
│   └── jobs.js
└── seeds.js
```

The seeds.js requires users.js and jobs.js.

After upgrading to 0.21.3, we saw error like "Invalid seed file: users.js must have a seed function".

Can you suggest how to update seed files or config to deal with this change? Thanks.

**Comment by kibertoad** [comment]
@broom9 Simplest solution would be to introduce one more hierarchical level so that one is not a subgolder of the other. I will try to come up with a solution that makes this change non-breaking tonight.

**Comment by mdartic** [comment]
@kibertoad  I agree

Maybe this could work :
```
seeds
├── data
│   ├── users.js
│   └── jobs.js
├── runs (or another name...)
│   └─ seeds.js
```

If the `seeds.js` file is placed in a directory at the same level, you can specify in your config that the folder seed need to run is `seeds/runs`.
The `require` would still work, but you'll need to update them with a relative path `../data` ?

I don't have any idea for not having this breaking change...

**Comment by kibertoad** [comment]
@mdartic The breaking change here is the recursive scanning of folder, which also makes it inconsistent with how migrations work. It should be a configuration parameter and off by default. If you have some time, would appreciate a PR for that, alternatively I'll get to it myself eventually.

**Comment by mdartic** [comment]
Got it.
You would like a new parameter like a boolean option `recursive` ?
If not set, you have the "old" way of finding files, only at the directory level, if set to `true`, we go deep in the folders ?

**Comment by kibertoad** [comment]
@mdartic Yes, exactly!

**Comment by mdartic** [comment]
Ok, I'm pushing an update in the hour.

**Comment by kibertoad** [comment]
@broom9 If you prefer to keep your original directory structure, you can simply update to 0.21.4. Note that if you choose to restructure your seeds, you'll have to opt-in for new logic and set `recursive` flag to true for seeding.
