### ISSUE TITLE
Jasper report data not faching get a some Error please suggest ..any body

### ISSUE THREAD

**Issue by Rameshwarnathyadav** [knex/knex#3789]
Error Trace
net.sf.jasperreports.engine.JRRuntimeException: net.sf.jasperreports.engine.JRException: Error executing SQL statement for: AgingReport_tableDataset_1586589188340_636721. at net.sf.jasperreports.engine.fill.JRFillSubreport.prepare(JRFillSubreport.java:886) at net.sf.jasperreports.components.table.fill.FillTableSubreport.prepareSubreport(FillTableSubreport.java:172) at net.sf.jasperreports.components.table.fill.FillTable.prepare(FillTable.java:419) at net.sf.jasperreports.engine.fill.JRFillComponentElement.prepare(JRFillComponentElement.java:150) at net.sf.jasperreports.engine.fill.JRFillElementContainer.prepareElements(JRFillElementContainer.java:352) at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:421) at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:396) at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillSummaryNoLastFooterSamePage(JRVerticalFiller.java:1070) at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillSummary(JRVerticalFiller.java:1029) at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportEnd(JRVerticalFiller.java:290) at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:126) at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:558) at net.sf.jasperreports.engine.fill.BaseFillHandle$ReportFill.run(BaseFillHandle.java:119) at com.jaspersoft.jasperserver.api.engine.jasperreports.service.impl.EngineServiceImpl$SynchronousExecutor.execute(EngineServiceImpl.java:922) at net.sf.jasperreports.engine.fill.BaseFillHandle.startFill(BaseFillHandle.java:164) at com.jaspersoft.jasperserver.api.engine.jasperreports.service.impl.EngineServiceImpl$AsynchronousReportFiller.fillReport(EngineServiceImpl.java:878) at com.jaspersoft.jasperserver.api.engine.jasperreports.service.impl.EngineServiceImpl.fillReport(EngineServiceImpl.java:1774) at com.jaspersoft.jasperserver.api.engine.jasperreports.service.impl.EngineServiceImpl$ReportFill.runWithDataSource(EngineServiceImpl.java:1118) at com.jaspersoft.jasperserver.api.engine.jasperreports.service.impl.EngineServiceImpl$ReportFill.runReport(EngineServiceImpl.java:1047) at com.jaspersoft.jasperserver.api.engine.jasperreports.service.impl.EngineServiceImpl$ReportRunnable.run(EngineServiceImpl.java:944) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: net.sf.jasperreports.engine.JRException: Error executing SQL statement for: AgingReport_tableDataset_1586589188340_636721. at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:342) at com.jaspersoft.jasperserver.api.engine.jasperreports.util.JRTimezoneJdbcQueryExecuter.createDatasource(JRTimezoneJdbcQueryExecuter.java:168) at net.sf.jasperreports.engine.fill.JRFillDataset.createQueryDatasource(JRFillDataset.java:1129) at net.sf.jasperreports.engine.fill.JRFillDataset.initDatasource(JRFillDataset.java:696) at net.sf.jasperreports.engine.fill.BaseReportFiller.setParameters(BaseReportFiller.java:437) at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:526) at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:396) at net.sf.jasperreports.engine.fill.JRFillSubreport.fillSubreport(JRFillSubreport.java:742) at net.sf.jasperreports.engine.fill.JRSubreportRunnable.run(JRSubreportRunnable.java:58) at net.sf.jasperreports.engine.fill.AbstractThreadSubreportRunner.run(AbstractThreadSubreportRunner.java:216) ... 3 more Caused by: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command Where: SQL statement "select ledger_account_id,dat::float,sum(amount)::float from ( select ref.amount ,ledger_account_id,v.posted_date, (case when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '1 month' and v.posted_date::date<='Sat Apr 11 00:00:00 EEST 2020' :: date then 1 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '2 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '1 month' then 2 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '3 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '2 month' then 3 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '4 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '3 month' then 4 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '5 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '4 month' then 10 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '6 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '5 month' then 11 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '7 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '6 month' then 12 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '8 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '7 month' then 13 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '9 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '8 month' then 5 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '10 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '9 month' then 14 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '11 month' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '10 month' then 15 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '1 year' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '11 month' then 6 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '2 year' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '1 year' then 7 when v.posted_date::date>='Sat Apr 11 00:00:00 EEST 2020' :: date- interval '3 year' and v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '2 year' then 8 when v.posted_date::date<'Sat Apr 11 00:00:00 EEST 2020' :: date- interval '3 year' then 9 end ) as dat from finance.journal j,finance.voucher as v ,finance.voucher_ref_data ref,finance.voucher as vv where j.voucher_id=v.id and v.posted='t' and vv.id in (select voucher_id from finance.journal where orientation='0') and vv.posted='t' and v.id in (select voucher_id from finance.journal where orientation='1') and vv.id=ref.linked_voucher_id and v.id=ref.refer_voucher_id and ref.voucher_ref_type!=2 ) as a group by ledger_account_id,dat ORDER BY 1,2" at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555) at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417) at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:302) at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:332) ... 12 more

12:55

**Comment by kibertoad** [comment]
This is Java. What does it have to do with knex?

**Comment by Rameshwarnathyadav** [comment]
not a java this is a postgresql query please define what type of issus

**Comment by kibertoad** [comment]
@Rameshwarnathyadav `net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:332` is not java?
