### ISSUE TITLE
Add CI integration with GitHub Actions

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#3792]
Considering how slow Travis CI is for multiple subsequent builds and how unstable integration was lately, it would make sense to explore alternative solutions for having CI integration for the project.

Potential alternatives are CircleCI and GitHub Actions. 

@ksatirli recommended GitHub Actions, so let's proceed with that.

**Comment by ksatirli** [comment]
Sounds good! 

To verify: you want the steps from [.travis.yml](https://github.com/knex/knex/blob/master/.travis.yml) to run in either CircleCI or GH Actions. Is that correct?

**Comment by kibertoad** [comment]
Yes, that is accurate, to an extent we can reuse them. We could potentially also enable running linting in CI, but that would currently break the build due to failures, especially on dtslint size. Newer version of https://www.npmjs.com/package/tarn would have to be released to address at least some of them, @elhigu was planning to do that in nearby future.

**Comment by ksatirli** [comment]
Alright, let me see what I can whip up.

I'll start with Actions first and if that doesn't work, we can check out CircleCI?

**Comment by abskmj** [comment]
@ksatirli You should consider the limits on space on GitHub action runners. IDK which plan you are on but its only 500MB of space under the free plan. The download size of Oracle 18 XE docker image, that is pulled for running the tests, is ~6.3GB.

I tried to set up a GitHub action on my fork and it failed as the job ran out of space. You can refer to the logs [here](https://github.com/abskmj/knex/runs/618292369).

**Comment by ksatirli** [comment]
Hey @abskmj,

Space is definitely an issue, but there's a couple of good ways to work around that.

I've got a branch that works with Oracle, I'll share it tomorrow after some clean-up :)

**Comment by abskmj** [comment]
@ksatirli that's good, wanna have a look some time

**Comment by ksatirli** [comment]
@abskmj I've been working on this with @kibertoad a bit over the weekend and getting Oracle to start isn't the hardest part, but it is time-intensive: roughly 7 mins for every Actions run.

So, let's talk code: my WIP repo (based on the latest `master` from April 26, 2020 is at [ksatirli/knex-test](https://github.com/ksatirli/knex-test).

Feedback is absolutely welcome, but do note that this isn't the final form: once all the DB techs work, I intend to make an actual fork and propose the changes via a PR (as should be done).

**Comment by abskmj** [comment]
Looks great, I was also planning for matrixes and the space reclaim trick is nice! .. good luck with this

**Comment by ksatirli** [comment]
Thanks - yeah, initial runs which were in sequence took _way_ too long.

Splitting it up like this, into matrices _per_ Node version as well as _per_ DB tech seems like the way to go.

Additionally, splitting unit and integration tests (and linting, for that matter) seems like the cleanest approach.
