### ISSUE TITLE
Knex migration status success, but no table created

### ISSUE THREAD

**Issue by force-push-master** [knex/knex#3794]
# Environment:

Knex version: "^0.20.13"
Database + version: "pg": "^8.0.0"
OS: ubuntu 18.04

# Bug:

_knex migrate:latest_ operation for table creation is successful, but there is no any new table in PgAdmin 4 web UI. BUT, when I created table manually in pgAdmin I have an access and can pull data from DB (so that mean I have correct config for DB connection).

# Configuration:

**knex config:**
`const knexStringcase = require('knex-stringcase');
const knex = require('knex');
const knexConfig = {
  client: 'pg',
  connection: 'postgressql://postgres:postgres@localhost:5432/ddavy_db',
  migrations: {
    tableName: 'migrations',
  },
};

const options = knexStringcase(knexConfig);
const db = knex(options);

module.exports = db;
`

**migration:**
`
exports.up = (knex) => {
  return knex.schema
      .hasTable('user_roles')
      .then((exists) => {
        if (!exists) {
          return knex
              .schema
              .createTable('user_roles', (table) => {
                table.increments('id').primary();
                table.integer('user_id')
                    .references('id')
                    .inTable('users')
                    .notNull()
                    .onDelete('cascade');
                table.string('role').notNullable();
                table.timestamp('created_at').defaultTo(knex.fn.now());
                table.timestamp('updated_at').defaultTo(knex.fn.now());
              })
              .then(console.log('user_roles table created'));
        }
      });
};

exports.down = (knex) => {
  return knex.schema.dropTable('user_roles');
};
`

**console output:**
`Using environment: development
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
user_roles table created
Batch 2 run: 1 migrations
`

**Comment by kibertoad** [comment]
`development sqlite does not support inserting default values` -> this strongly implies that you are not using the db configuration that you think you are using, and something overrides it to use sqlite and write to your hdd instead.

**Comment by force-push-master** [comment]
> `development sqlite does not support inserting default values` -> this strongly implies that you are not using the db configuration that you think you are using, and something overrides it to use sqlite and write to your hdd instead.

you right, I initialized knexfile.js and forgot to change fields in it. Sorry for for my dumb question.

Closing this issue.
