### ISSUE TITLE
Feature request: then-able Where clauses

### ISSUE THREAD

**Issue by maxwellgerber** [knex/knex#3797]
# Feature discussion / request

1. Explain what is your use case

Occasionally, we need to pre-compute some conditions before constructing a where clause.

```javascript
const clauseAsObject = await getTheClause();
const clauseAsAsyncFunction = async function () {...}

const result = knex('mytable').select('*')
  .where(clauseAsObject)        // need to await it before constructing statement 
  .where(clauseAsAsyncFunction) // this will never work today
```

It would be awesome if we could do

```javascript
const clauseAsAsyncFunction = async function () {...}

const result = knex('mytable').select('*')
  .where(getTheClause())        // knex awaits it for us
  .where(clauseAsAsyncFunction) // works same as regular function 
```

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

If the argument passed into a where clause is a [thenable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then), invoke its `.then()` method and use the result instead

Similar to https://github.com/knex/knex/issues/2836

**Comment by lorefnon** [comment]
I think the more intuitive thing to do is to ensure that callbacks/thunks received anywhere can be async (basically the opposite).

 For the mentioned use case it is simple enough to just await before passing to `where` ? 

```
knex('mytable').select('*')
  .where(await getTheClause())
```

**Comment by elhigu** [comment]
I don't want knex query builder parts to allow anything async ever. One should resolve data for building outside of knex.
