### ISSUE TITLE
More of a coding question:  How to check if table constraint exists before altering

### ISSUE THREAD

**Issue by HuckleberryCarignan** [knex/knex#3799]
# Environment

Knex version: 0.20.14
OS: Mac OS

This is more of a coding pattern question I need guidance on.   How can we check to see if a constraint exists before removing it?

This is more of a coding methodology question than an issue:

I'm doing some test automation, and I need to remove a constraint in order get around an external limitation, so I hav the following:

    async alterTable_dropConstraint(tableName, constraintDropped) {
        return await knex.schema.raw(`ALTER TABLE ${tableName} DROP CONSTRAINT ${constraintDropped}`);
    }

but the test is failing when the constraint is not there.  I want to check to see if the constraint is there before attempting to drop it.

Any idea how this could be accomplished?

**Comment by elhigu** [comment]
Might be database specific. Maybe in stackoverflow someone knows the answer from top of their head.
