### ISSUE TITLE
JSONB update from raw query fails with bindings but works directly from Postgres

### ISSUE THREAD

**Issue by jbelelieu** [knex/knex#3801]
# Environment

Knex version: ^0.19.5
Database + version: Postgres 11.2
OS: Mac

# Bug
1. A query designed to update a JSONB column works when the raw `.toString()` output is run directly from Postgres, but not when run within the context of Knex.

2. Error message: NONE when the output of `.toString()` is run directly, either from Postgres's CLI or from a second `.raw(...)` query which uses the output of the initial `.toString()`. HOWEVER, if the initial `.toString()` is removed and the query is run as a raw knex query with bindings, it failed with `invalid input syntax for type json`.

# Code Snippet
```
const query = connection.raw(`UPDATE ?? SET metadata = (CASE
            WHEN metadata -> ? IS NOT NULL
            THEN jsonb_set(metadata, '{??}', '?'::jsonb)
            WHEN metadata -> ? IS NULL
            THEN jsonb_insert(metadata, '{??}', '?'::jsonb)
        END) WHERE ?? = ?`, [table, entryKey, entryKey, entryValue, entryKey, entryKey, entryValue, whereColumnName, whereColumnValue]).toString()
```

Example output:
```
UPDATE "question" SET metadata = (CASE
            WHEN metadata -> 'keyHere' IS NOT NULL
            THEN jsonb_set(metadata, '{"keyHere"}', 'false'::jsonb)
            WHEN metadata -> 'keyHere' IS NULL
            THEN jsonb_insert(metadata, '{"keyHere"}', 'false'::jsonb)
        END) WHERE "id" = '1'
```

If you then take that output and run as follows, it works:

```
connection.raw(query) // Success!
```

But if I run that without the toString, it produces the error:

```
    return connection.raw(`UPDATE ?? SET metadata = (CASE
            WHEN metadata -> ? IS NOT NULL
            THEN jsonb_set(metadata, '{??}', '?'::jsonb)
            WHEN metadata -> ? IS NULL
            THEN jsonb_insert(metadata, '{??}', '?'::jsonb)
        END) WHERE ?? = ?`, [table, entryKey, entryKey, entryValue, entryKey, entryKey, entryValue, whereColumnName, whereColumnValue])
       .then((updatedRows: any) => {
            return updatedRows ? true : false;
        })
        .catch((error: any) => {
            console.log(error);

            return false;
        });
```

Perhaps I have a misunderstanding of how knex works, but as a query builder I would expect the output of `.toString()` to run directly, without having to run the query on the post-processed output.

**Comment by elhigu** [comment]
You might need to drop the single quotes from value bindings. `'?'::jsonb -> ?::jsonb`. Having quotes there doesn't make sense...
