### ISSUE TITLE
Broken CLI TypeScript support

### ISSUE THREAD

**Issue by htunnicliff** [knex/knex#3807]
# Environment

Knex version: `0.20.15`
Database + version: `sqlite3`
OS: `macOS 10.14.6 (18G3020)`

@lorefnon 

## Example repository with bugs
https://github.com/htunnicliff/knex-cli-ts-errors

# Bug (1)

### Explain what kind of behaviour you are getting and how you think it should do
Running `knex migrate:make some_migration_name` with a `knexfile.ts` in the current working directory should produce a TypeScript migration file with no errors.

### Error message
```sh
Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module @babel/register
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Created Migration: /knex-cli-ts-errors/migrations/20200416104822_create_example_table.ts
```

# Bug (2)

### Explain what kind of behaviour you are getting and how you think it should do
Running `knex migrate:up` should migrate with no errors.

### Error message
```sh
Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module @babel/register
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
/knex-cli-ts-errors/migrations/20200416104822_create_example_table.ts:1
import * as Knex from "knex";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at FsMigrations.getMigration (/knex-cli-ts-errors/node_modules/knex/lib/migrate/sources/fs-migrations.js:81:12)
    at /knex-cli-ts-errors/node_modules/knex/lib/migrate/Migrator.js:146:69
    at arrayFilter (/knex-cli-ts-errors/node_modules/lodash/lodash.js:582:11)
```

**Comment by kibertoad** [comment]
@htunnicliff What was the last version that this worked for?

**Comment by htunnicliff** [comment]
@kibertoad I've had issues with this since I started using knex, around `0.16`

**Comment by kibertoad** [comment]
@htunnicliff Have you tried using ts-node? This seems like you are trying to import TS file in JS context. After @briandamaged 's fixes liftoff should handle at least some of the TS cases out-of-the-box, but apparently not all of them.

**Comment by kibertoad** [comment]
I think we support knexfile to be TS, but not migration files per se. ts-node should help.

**Comment by htunnicliff** [comment]
I have used this with ts-node in the past, but I wanted to file an issue because the expected behavior here just doesn't work unless you jump through hoops like `require("ts-node/register")`, etc. in your knexfile.

**Comment by htunnicliff** [comment]
If this is truly the desired behavior, I think it is imperative that the docs elaborate on exactly how to get TypeScript working with ts-node. The docs don't make a single mention of ts-node.

**Comment by htunnicliff** [comment]
> I think we support knexfile to be TS, but not migration files per se. ts-node should help.

From the docs (Migrations > CLI > knexfile.js):

**Generated migration extension:**
You can control extension of generated migrations.
```js
module.exports = {
  client: 'pg',
  migrations: {
    extension: 'ts'
  }
};
```

**Comment by kibertoad** [comment]
Yeah, I guess we need to look into what is supported and what is not and update docs.
`Failed to load external module ts-node/register` looks fishy, though.
For curiousity sake, which Node version are you using?

**Comment by kibertoad** [comment]
@htunnicliff But the migration creation case says `Created Migration: /knex-cli-ts-errors/migrations/20200416104822_create_example_table.ts`. Are you sure it doesn't actually get created?

**Comment by htunnicliff** [comment]
I'm using Node 12.16.1.

**Comment by htunnicliff** [comment]
It does create the migration, however, when running `knex migrate:up` you get another error and it is unable to actually do the migrating.

**Comment by htunnicliff** [comment]
If there is a need for ts-node to enable CLI TypeScript support, would it make sense to have it as  a dependency in `knex`?

**Comment by htunnicliff** [comment]
This problem also exists for CLI seed generation and execution

**Comment by lorefnon** [comment]
I think there are two things to be done here: 

1. We need to document what is needed to interpret knexfile (or other files which knex imports) written in typescript  - which is basically one of [these modules](https://github.com/gulpjs/interpret/blob/5e2eb6e0e475bbe353ff33fe4946d11ff39ecb03/index.js#L140-L155).

2. Currently the [utilities](https://github.com/knex/knex/blob/e37aeaa31c8ef9c1b07d2e4d3ec6607e557d800d/bin/utils/cli-config-utils.js#L79-L105) for inferring extension for migrations/seeds to be generated are not aware of knexfile extension where as IMHO they should default to knexfile extension in absense of explicit extension specified somewhere in config.

**Comment by YajJackson** [comment]
What is the recommended workflow for running Typescript migrations? The documentation still suggests that running `knex migrate:latest` is sufficient:

```
Once you have a knexfile.js, you can use the migration tool to create migration files to the specified directory (default migrations). Creating new migration files can be achieved by running:

$ knex migrate:make migration_name 

# or for .ts

$ knex migrate:make migration_name -x ts

...

Once you have finished writing the migrations, you can update the database matching your NODE_ENV by running:

$ knex migrate:latest
```

See:
```
root@1e4d151bd246:/srv/app# node --version
v12.18.2
root@1e4d151bd246:/srv/app# npm run knex -- --version

> backend@0.1.0 knex /srv/app
> knex "--version"

Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module sucrase/register/ts
Failed to load external module @babel/register
Knex CLI version: 0.19.5
Knex Local version: 0.19.5
root@1e4d151bd246:/srv/app#
root@1e4d151bd246:/srv/app#
root@1e4d151bd246:/srv/app#
root@1e4d151bd246:/srv/app# npm run knex -- migrate:make initial_migration -x ts

> backend@0.1.0 knex /srv/app
> knex "migrate:make" "initial_migration" "-x" "ts"

Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module sucrase/register/ts
Failed to load external module @babel/register
Using environment: development
Using environment: development
Using environment: development
Created Migration: /srv/app/migrations/20200722212137_initial_migration.ts
root@1e4d151bd246:/srv/app# npm run knex -- migrate:latest

> backend@0.1.0 knex /srv/app
> knex "migrate:latest"

Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module sucrase/register/ts
Failed to load external module @babel/register
Using environment: development
/srv/app/migrations/20200722212137_initial_migration.ts:1
import * as Knex from "knex";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FsMigrations.getMigration (/srv/app/node_modules/knex/lib/migrate/sources/fs-migrations.js:84:12)
    at /srv/app/node_modules/knex/lib/migrate/Migrator.js:82:69
    at arrayFilter (/srv/app/node_modules/lodash/lodash.js:582:11)
    at filter (/srv/app/node_modules/lodash/lodash.js:9173:14)
    at /srv/app/node_modules/knex/lib/migrate/Migrator.js:81:13
    at tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/srv/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/srv/app/node_modules/bluebird/js/release/promise.js:649:10)
```

**Comment by erwinvil** [comment]
Workaround that worked for me using ts-node:
```
ts-node ./node_modules/.bin/knex migrate:make --knexfile knexfile.ts -x ts <migration_name>
```

This successfully creates the migration file with a `.ts` extension.

As for running the migration, I still run them using the transpiled `.js` files via npm run scripts:

```
"db:migrate:latest": "cd build && env DOTENV_CONFIG_PATH=../.env node --require dotenv/config ../node_modules/.bin/knex migrate:latest",
"db:migrate:rollback": "cd build && env DOTENV_CONFIG_PATH=../.env node --require dotenv/config ../node_modules/.bin/knex migrate:rollback"
```

I tried running the migrations as `.ts` files before but I encountered weird runtime transpilation issues when running on deployed containers (not enough memory?).

**Comment by musahaidari** [comment]
https://stackoverflow.com/questions/40910864/cannot-find-module-ts-node-register

I think this solves the issue

**Comment by jowparks** [comment]
> https://stackoverflow.com/questions/40910864/cannot-find-module-ts-node-register
> 
> I think this solves the issue

No, this does not solve issue. I have ts-node installed locally and the issue still persists.

same error with ts-node:
```
╰─ npx ts-node ../../../../node_modules/knex/bin/cli  migrate:latest
Using environment: development
/Users/jowparks/Projects/reflect/apps/api/src/app/migrations/20200816085511_add_questions.ts:1
import { __awaiter } from "tslib";
^^^^^^

SyntaxError: Cannot use import statement outside a module
...
```

**Comment by jowparks** [comment]
Found a work around here:
https://github.com/knex/knex/issues/3849#issuecomment-643411244

in my `package.json` added this line, then executed whatever command I want:
```
scripts: {
  ...
  "api-knex": "TS_NODE_COMPILER_OPTIONS='{ \"module\": \"commonjs\" }' knex --knexfile=./path/to/knexfile.ts"
...
```
and run a command in command-line like:
```
npm run api-knex migrate:up
```


Note: My problem was that `esnext` is not supported for the knex cli

**Comment by aMoniker** [comment]
@jowparks Thanks, this workaround does work, but for some reason it doesn't allow me to pass the `--all` argument to the `migrate:rollback` command. Adding some console.log statements to `node_modules/.bin/knex` shows that commander.js receives `cmd.all` as undefined. It receives the argument correctly when not using the workaround, but then of course it breaks after it encounters the knexfile written in typescript.

**Comment by jowparks** [comment]
Yea I am not a whiz with npm, guessing the argument is somehow not getting passed. Maybe you can try hardcoding the command in the package.json to see if it works.

**Comment by mormsbee** [comment]
as we were calling the following in our app init:
`knex.migrate.latest(config);`
our solution was to add ts-node to package.json:
`"ts-node": "^8.10.2"`
 and the following near the top of our server.ts file.
`require('ts-node/register');`

**Comment by 41y08h** [comment]
I use `env-cmd` to load env vars from script ` "migrate": "env-cmd knex migrate:make -x ts"`

**Comment by v-yarosh** [comment]
remove "include" from "compilerOptions" in tsconfig.ts

**Comment by PentaMine** [comment]
`npm install ts-node` worked for me
