### ISSUE TITLE
If null replace column by zero

### ISSUE THREAD

**Issue by abdulmalekDery** [knex/knex#3808]
I have query like this
   let query = await knex.column(['devices.id as device_id','devices.device_name','order_details.quantity'
        ,'alarms.alarms_count'])
        .select().from('devices')
        .innerJoin('order_details', 'order_details.id', 'devices.order_detail_id')
        .innerJoin('orders', 'orders.id', 'order_details.order_id')
        .leftOuterJoin('alarms','alarms.device_id','devices.id')
        .where('orders.customer_id',req.params.customerId);

and it return result like that 
"devices": [
            {
                "device_id": 1,
                "device_name": "manager room",
                "quantity": 1,
                "alarms_count": 2
            },
            {
                "device_id": 2,
                "device_name": "employee room",
                "quantity": 2,
                "alarms_count": null
            }]

but I want to set value of alarms_count to zero if it's null how could I do it using knex

**Comment by kibertoad** [comment]
@abdulmalekDery You can do it on DB level by setting default value of the column to be a 0, making it non-nullable and removing value from insert. Null is null.

**Comment by kibertoad** [comment]
Also check out COALESCE sql command, I think you can use it to have some default values in select queries if you don't want to change actual data in DB.
