### ISSUE TITLE
Error: Update called multiple times with objects.

### ISSUE THREAD

**Issue by tackelua** [knex/knex#3813]
Here is my knex code
```
const dbGmail = knex('gmail');
const dbInsert = async data => {
  console.log({ dbInsert: data });
  return await dbGmail.insert(data);
};
const dbUpdate = async (data, where) => {
  console.log({ dbUpdate: data, where });
  return await dbGmail.where(where).update(data);
};
```
When I update data, it's show the error. And sometime data was pushed to db sometime not.
```
{
  dbUpdate: { phone_number: '078xxxxx7', phone_provider: 'simxxxx.net' },
  where: { username: 'hxxxx3' }
}
Update called multiple times with objects.
```
I tried to google **"Update called multiple times with objects."** but can not find any resolve.

**Comment by kibertoad** [comment]
You shouldn't be reusing same query builder for several queries. Move `const dbGmail = knex('gmail');` inside of those functions.

**Comment by elhigu** [comment]
or use dbGmail.clone() to create new query builder for each query instead of always modifying the original one.
