### ISSUE TITLE
migrate:make foo results in "calling knex without a tableName is deprecated. Use knex.queryBuilder() instead.

### ISSUE THREAD

**Issue by boojum** [knex/knex#3815]
# Environment

Knex version: 0.21.0
Database + version: PostgreSQL 12.2 (docker)
OS: Ubuntu 19.10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When trying to create migration with:

`npx knex --knexfile ./src/db/knexfile.js migrate:make foobar`

`knex` complains about:

`calling knex without a tableName is deprecated. Use knex.queryBuilder() instead.`

The same happens when I try `seed:make foobar` _but I'm able to run queries against the db_.

I'm using `node` experimental esm support via `"type": "module"`. To keep `knex` happy I'm employing "a non-module package.json" as described by @D10221 in [this](https://github.com/knex/knex/issues/3571#issuecomment-590911321) comment.

2. Error message
```
Working directory changed to ~/code/playground/moviedb/src/db
calling knex without a tableName is deprecated. Use knex.queryBuilder() instead.
(node:18834) UnhandledPromiseRejectionWarning: error: select * - SELECT * with no tables specified is not valid
    at Connection.parseE (/home/boojum/code/playground/moviedb/node_modules/pg/lib/connection.js:600:48)
    at Connection.parseMessage (/home/boojum/code/playground/moviedb/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/boojum/code/playground/moviedb/node_modules/pg/lib/connection.js:115:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:18834) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18834) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Repo with toy code demonstrating the isse can be found on [gitlab](https://gitlab.com/b00jum/knex-tutorial). I'm betting on issue being with `knexfile` which can be seen below:

```
const dotenv = require("dotenv").config({ path: __dirname + "/../../.env" });
const knex = require("knex");

const config = {
  development: {
    client: "pg",
    connection: {
      host: process.env.POSTGRES_HOST,
      port: process.env.POSTGRES_PORT,
      user: process.env.POSTGRES_USER,
      password: process.env.POSTGRES_PASSWORD,
      database: process.env.POSTGRES_DB,
    },
    migrations: {
      tableName: "knex_migrations",
      directory: "./migrations",
    },
    seeds: { directory: "./seeds" },
  },
};

const db = knex(config[`${process.env.NODE_ENV}`]);
module.exports = knex(config[`${process.env.NODE_ENV}`]);

module.exports = db;
```

**Comment by elhigu** [comment]
https://gitlab.com/b00jum/knex-tutorial/-/blob/master/src/models/movie.js#L4

At least there you are calling `knex` without `tableName` parameter, but it shouldn't be realated to migration creation errors... 

I don't understand why 

```
npx knex --knexfile ./src/db/knexfile.js migrate:make foobar
```

would throw that error even that it should not even build any queries.

**Comment by D10221** [comment]
It seems to me the problem is here
```javascript
const db = knex(config[`${process.env.NODE_ENV}`]); // unused
module.exports = knex(config[`${process.env.NODE_ENV}`]); // exporting Knex instead of Config
```
'module.exports' is 'Knex Function', instead of "Knex's Config"

I think... you should share your 'knex' configuration between the 'migrations' and the app code.
instead of the Knex instance

**Comment by elhigu** [comment]
yep, I missed that :)

**Comment by boojum** [comment]
@elhigu 

About those queries you pointed out: I do have a `.from("tag")` there, isn't that enough to pass a table to knex? I understand that its not applicable here - and the issue was solved by @D10221 - I just want to understand your comment.

@D10221 

Nice one, thanks! This solves my issue. But... If I may, I have a question now. That `const db` you pointed at, it is imported in other parts of the app and used to query the db. Now I'm exporting it from a separate file, like:

```
const dotenv = require("dotenv").config();
const knex = require("knex");
const config = require("./knexfile");

const db = knex(config);
module.exports = db;
```

But you mention that "you could share your 'knex' configuration between the 'migrations' and the app code instead of the Knex instance" - does that mean that I could export it from `knexfile` along with the required `config` somehow?

**Comment by D10221** [comment]
@boojum 
I meant ... Exactly what you did :)

**Comment by elhigu** [comment]
> About those queries you pointed out: I do have a .from("tag") there, isn't that enough to pass a table to knex?

If it works it is enough... might be that the error message is just written without acknowledging that.

**Comment by nexusbr** [comment]
Thanks @D10221 

**knexfile.js**

```
var options = {
    development: {
        client: 'pg',
        connection: {
            host: process.env.SERVIDOR_MAPAS_ENDERECO,
            user: process.env.SERVIDOR_MAPAS_USUARIO,
            password: process.env.SERVIDOR_MAPAS_SENHA,
            database: process.env.SERVIDOR_MAPAS_NOME_BANCO_DADOS,
            port: process.env.SERVIDOR_MAPAS_PORTA
        }
    },
    pool: {
        min: 2,
        max: 10
    },
    migrations: {
        tableName: 'knex_migrations'
    },
    production: {
        ...
        ...
    },
};

var environment = process.env.NODE_ENV || 'development';
var config = options[environment];
module.exports = config;
```

**database.js**

```
var options = require('./config/knexfile');
module.exports = require('knex')(options);
```

and at **file_to_access_data.js**

```
var knex = require('../../database');
knex.raw('insert into ...)
```
