### ISSUE TITLE
inconsistent performance 

### ISSUE THREAD

**Issue by gbkwiatt** [knex/knex#3816]
# Environment

Knex version: 0.21.0
Database + version: mssql
OS: windows 10

@smorey2 

# Bug

1. I have express api, and simple endpoint with simple select query. When I run endpoint first time, it takes around 1 seconds to run, but if I run same or other endpoints straight after, it goes down to below 100ms.  When I wait minute or two, ot goes back to above second again.
I was thinking it's might something with the api but measured  everything and that inconsistency happens on knex query. 
Why is that happening ? I also disabled all caching, but behaviour stays the same. 

```javascript
req.performance.mark('B')
  if (!req.params.dept) return res.status(422).send({ error: 'Missing department' })
  const categories = await req
    .db('categories')
    .select('uID', 'categoryName')
    .where('departmentID', req.params.dept)
    .catch((err) => {
      return next(err)
    })
  req.performance.mark('C')
```
and here is my connection code: 
```javascript 
var configCommon = {
  client: 'mssql',
  connection: {
    host: process.env.DB_HOST_COMMON || 'localhost',
    user: process.env.DB_USER_COMMON || 'username',
    password: process.env.DB_PASSWORD_COMMON || 'password',
    database: process.env.DB_DBNAME_COMMON || 'test'
  },
  pool: { min: 0, max: 7 }
}
const db = require('knex')(config)
```
between mark B and mark C, time oscilates from 900ms to 50ms, longer I wait between requests, longer it takes. ( max 900ms)

Is it maybe because I am passing my knex connection to req  and using it from there ?

**Comment by kibertoad** [comment]
One thing that immediately comes to mind is pooling. Since min amount of connections is 0 for you, there are no readily available connections in your pool until you warm up the pool. Try increase min value a bit and see if it makes a difference.

**Comment by gbkwiatt** [comment]
I think I found the issue 'facepalm' it's me working from home, remotely through vpn and proxy.
When I placed my api directly on server it's all fine. 
However your hint fix my other problem, when on cold  start, query was always long.
