### ISSUE TITLE
Knex-oracle dialect concurrency issue

### ISSUE THREAD

**Issue by msudhayaraj** [knex/knex#3819]
# Environment

Knex version: **0.20.11**
Database + version: ORACLE 11g
OS: Ubuntu 16.04 LTS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am  having a context where multiple users will try to update the same record of a table concurrently.
During this case (with concurrent call testing over 20 threads per sec using jmeter), i observe that **knex hangs.** . No other queries are running after that. Hence it requires a restart of my API service.

Note: 
Pooling : {min:3,max:7}

I tried to simulate this issue by using [oracledb](https://www.npmjs.com/package/oracledb). But it never hangs. It works without any issue for more than 100 threads per sec.

2. Error message
Knex: Timeout acquiring a connection. The pool is probably full.Are you missing a .transacting(trx) call?

Thanks in advance for your support.
@atiertant

**Comment by elhigu** [comment]
Cannot reproduce, error message is suggesting that you are launching transactions but never committing them, thus leaving them open.

**Comment by elhigu** [comment]
Please just create single file test code, which executes those knex queries without express directly connecting DB with knex and running as many parallel queries as you need...

Are you sure you don't have any middlewares there creating transactions?

**Comment by elhigu** [comment]
Also try without knex.raw() your code still doesn't show what kind of updates  you are doing there... At least it is not using parameter bindings as it should.

**Comment by msudhayaraj** [comment]
> Please just create single file test code, which executes those knex queries without express directly connecting DB with knex and running as many parallel queries as you need...
> 
> Are you sure you don't have any middlewares there creating transactions?

Yes, i don't  have any middlewares  to create transactions. I am executing query without transactions.But both transactions and without transactions i am getting same error.

**Comment by msudhayaraj** [comment]
> Also try without knex.raw() your code still doesn't show what kind of updates you are doing there... At least it is not using parameter bindings as it should.

i am using Raw query  **update transaction_set set status='OK' where trn_id = 45041**

And i am getting the same result when i tested with other model (without knex.raw() model) as suggested by you.

**Things are working fine for me when i test with Oracledb  npm directly**. It doesnt hang for concurrent calls. 

My Oracledb npm sample code is 

var reqExpress = require('express');
var router = reqExpress.Router();

var dbConnection = {};
var oracledb = require('oracledb');
var strConnection = {
    user: 'USERNAME',
    password: 'PWD',
    connectString: "DB"
};
oracledb.poolMin = 3;
oracledb.poolMax = 7;
oracledb.poolIncrement = 1;
oracledb.poolPingInterval = 60; // seconds
oracledb.poolTimeout = 60;

oracledb.createPool(strConnection)
    .then(
        function (pool) {
            pool.getConnection()
                .then(function (connection) {
                    dbConnection = connection;
                });
        });


router.post('/oraupdate', function (appRequest, appResponse) {
    try {
        var query = "update transaction_set set status='OK' where trn_id = 45041";
        dbConnection.execute(query, binds)
            .then(function (result) {
                console.log(result);
                appResponse.send("SUCCESS");
            })
            .catch(function (err) {
                console.error(err);
                appResponse.send(err);
            });
    } catch (error) {
         appResponse.send(error);
    }
});
module.exports

Thanks for your quick response to my queries.

**Comment by elhigu** [comment]
Ok looks like your oracle code does something completely different than the knex version

1.  creating a pool when app starts 
2. Taking one connection from there and storing to a global variable
3. running all queries with that single connection

(might be that I guessed wrong how those oracle APIs work, correct me if I'm wrong)

Is that `transaction_set` a system table or created by you?

**Comment by elhigu** [comment]
Try if this **minimal single file test case** works :

```
var knex = require('knex')({
client: 'oracledb',
connection: {
host: 'server',
user: 'dbuser',
password: 'PWD',
database: 'DBName'
},
pool: pool: {
"max": 7,
"min": 3
}
});

let sql = "update transaction_set set status='OK' where trn_id = 45041";

let manyQueries = [];
for (let i = 0; i < 200; i++) {
  manyQueries.push(knex.raw(sql));
}

Promise.all(manyQueries).then(() => {
  console.log('All queries done!');
  knex.destroy();
});
```

**Comment by msudhayaraj** [comment]
> Ok looks like your oracle code does something completely different than the knex version
> 
> 1. creating a pool when app starts
> 2. Taking one connection from there and storing to a global variable
> 3. running all queries with that single connection
> 
> (might be that I guessed wrong how those oracle APIs work, correct me if I'm wrong)
> 
> Is that `transaction_set` a system table or created by you?

yes right,i get the connection when app starts.
using the same connection to execute all queries.
As you guessed my oracle sample works.

**But my Knex sample also works the same way . i got the connection when app starts, use the same connection to execute the queries.**

No, transaction_set table is my own table.

**Comment by elhigu** [comment]
> But my Knex sample also works the same way . i got the connection when app starts, use the same connection to execute the queries.

Nope. In the he code you posted here https://github.com/knex/knex/issues/3819#issuecomment-617775322 you create a knex instance at start and then you get a new connection from pool every time a request is done. 

So with knex you are actually doing parallel queries to the DB with multiple connections and with oracledb example you are using a single connection.

Anyways... try running that testcase I posted if it works.

**Comment by msudhayaraj** [comment]
> > But my Knex sample also works the same way . i got the connection when app starts, use the same connection to execute the queries.
> 
> Nope. In the he code you posted here [#3819 (comment)](https://github.com/knex/knex/issues/3819#issuecomment-617775322) you create a knex instance at start and then you get a new connection from pool every time a request is done.
> 
> So with knex you are actually doing parallel queries to the DB with multiple connections and with oracledb example you are using a single connection.
> 
> Anyways... try running that testcase I posted if it works.

i declared variable knex above the router , it act as global variable [#3819](https://github.com/knex/knex/issues/3819) in my knex sample code 

in oracle sample code also i declared a variable above the router it may act as global variable.i thought both are same . 

I thought  the db connection could be established by `**var knex = require('knex')(connection string)**  .  it called when app start only. But you said my knex sample works like with multiple connection.

pls correct me if i am wrong.

When the connection really established ?

**Comment by elhigu** [comment]
> Anyways... try running that testcase I posted if it works.

** Did you try to run that test case https://github.com/knex/knex/issues/3819#issuecomment-618562745 I wrote for you? If not please do. **

> pls correct me if i am wrong.

with oracle you create a single global connection which is used to run all the queries:

```
oracledb.createPool(strConnection).then(function (pool) {
  pool.getConnection().then(function (connection) {
    dbConnection = connection;
  })
});
```

With knex you create a knex instance with internal connection pool  (not a single connection) and when you run concurrent queries, knex fills up the pool with multiple connections which are used for executing the queries.

**Comment by msudhayaraj** [comment]
> Try if this **minimal single file test case** works :
> 
> ```
> var knex = require('knex')({
> client: 'oracledb',
> connection: {
> host: 'server',
> user: 'dbuser',
> password: 'PWD',
> database: 'DBName'
> },
> pool: pool: {
> "max": 7,
> "min": 3
> }
> });
> 
> let sql = "update transaction_set set status='OK' where trn_id = 45041";
> 
> let manyQueries = [];
> for (let i = 0; i < 200; i++) {
>   manyQueries.push(knex.raw(sql));
> }
> 
> Promise.all(manyQueries).then(() => {
>   console.log('All queries done!');
>   knex.destroy();
> });
> ```

i tried with this code.after the Promise.all() the call is not return back .
 i checked with db that particular table is **locked**. 
 I think this may happened in concurrent call to knex.

The table is  locked , so that other threads try to update but the connection is not released, 
new threads get the new pool but not return back. Finally The pool is probably full error will come.
is this correct what i am thinking? 
pls suggest me how to solve this.

**Comment by elhigu** [comment]
Ok thanks... next try this:

```
var oracledb = require('oracledb');
var strConnection = {
  user: 'USERNAME',
  password: 'PWD',
  connectString: "DB"
};
oracledb.poolMin = 3;
oracledb.poolMax = 7;
oracledb.poolIncrement = 1;
oracledb.poolPingInterval = 60; // seconds
oracledb.poolTimeout = 60;

oracledb.createPool(strConnection).then(pool => {
  oraclePool = pool; 

  let sql = "update transaction_set set status='OK' where trn_id = 45041";
  
  let manyQueries = [];
  for (let i = 0; i < 200; i++) {
    manyQueries.push(
      pool.getConnection().then(conn => {
        return conn.execute(sql);
      })
  }

  Promise.all(manyQueries).then(() => {
    console.log('All queries done!');
  });
});
```

That might use multiple connections also when ran directly with oracledb driver.

**Comment by msudhayaraj** [comment]
> Ok thanks... next try this:
> 
> ```
> var oracledb = require('oracledb');
> var strConnection = {
>   user: 'USERNAME',
>   password: 'PWD',
>   connectString: "DB"
> };
> oracledb.poolMin = 3;
> oracledb.poolMax = 7;
> oracledb.poolIncrement = 1;
> oracledb.poolPingInterval = 60; // seconds
> oracledb.poolTimeout = 60;
> 
> oracledb.createPool(strConnection).then(pool => {
>   oraclePool = pool; 
> 
>   let sql = "update transaction_set set status='OK' where trn_id = 45041";
>   
>   let manyQueries = [];
>   for (let i = 0; i < 200; i++) {
>     manyQueries.push(
>       pool.getConnection().then(conn => {
>         return conn.execute(sql);
>       })
>   }
> 
>   Promise.all(manyQueries).then(() => {
>     console.log('All queries done!');
>   });
> });
> ```
> 
> That might use multiple connections also when ran directly with oracledb driver.

I tried with code.i faced the similar case like knex code sample.
**The table is locked.**
**How can i handle the concurrent call using knex.** 
i am using multiple DB (pg,oracle), knex is perfect match for my code. but i am struggling in concurrency.
i think knex not queue the  process, all the queries going to execute same time  before the connection back to pool. 
pool may drained, knex next thread not able to accrue a connection.
 


.

**Comment by elhigu** [comment]
>  tried with code.i faced the similar case like knex code sample. The table is locked.

This means that the problem is oracle database. For some reason that query locks the table but never returns, which causes other queries to hang too...

You should try to ask from oracledb people why that is happening and if there are some configuration settings that can help you with that.  You can use that same failing example code to ask for help. They should be able to know directly what may be a problem there.

I don't see any reason why that query would be locking the table and not releasing the lock immediately... This is really not related to knex but to actual oracledb and how it works.

**Comment by msudhayaraj** [comment]
> > tried with code.i faced the similar case like knex code sample. The table is locked.
> 
> This means that the problem is oracle database. For some reason that query locks the table but never returns, which causes other queries to hang too...
> 
> You should try to ask from oracledb people why that is happening and if there are some configuration settings that can help you with that. You can use that same failing example code to ask for help. They should be able to know directly what may be a problem there.
> 
> I don't see any reason why that query would be locking the table and not releasing the lock immediately... This is really not related to knex but to actual oracledb and how it works.

I tried the same code with knex postgresql DB. That was working fine.Its may be the oracle issue.
i will raise the issue in oracledb npm.

**Thanks for you great support** :).
