### ISSUE TITLE
Liftoff warnings on installation

### ISSUE THREAD

**Issue by zefexdeveloper** [knex/knex#3827]
# Environment

Knex version: 0.21.0

![image](https://user-images.githubusercontent.com/30276092/80294798-befc0480-8742-11ea-873c-afea2567c878.png)

I'm getting those warnings when installing Knex, are they problematic and any idea on when they are going to be "solved"?

- https://github.com/js-cli/js-liftoff/issues/107
- https://github.com/js-cli/js-liftoff/pull/108

It seems to be a high severity vulnerability

**Comment by zefexdeveloper** [comment]
bump

**Comment by vinicius73** [comment]
Any news about that?

**Comment by kibertoad** [comment]
This is resolved in #4122, will be released as a part of 0.95.0
