### ISSUE TITLE
"TimeoutError: Knex: Timeout acquiring a connection" when using with Node 14

### ISSUE THREAD

**Issue by nicoburns** [knex/knex#3831]
# Environment

**Node: 14.x** <-- pretty sure this is the problem / difference

Knex version: 0.21.0 (also seen in older version)
Database + version: Postgres 12
OS: Observed on macOS and Linux

# Bug

1. Initially, all knex connections/queries failed (timed out). I was able to fix regular connections by upgrading `knex` to `0.21.0` and `node-pg` to version 8.x. However, running migrations using `knex migrate:latest` or `npx knex migrate:latest` is still failing.

2. Error message
```
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /<omitted>/node_modules/knex/lib/client.js:318:17
```

**Comment by kibertoad** [comment]
Interesting. I'm seeing this in CI for Node 12 of all things. Might be some other change in knex causing it. Does switching to older node fix it?

**Comment by kibertoad** [comment]
I'll take a look.

**Comment by nicoburns** [comment]
Update: turns out that our repository containing the migrations has a separate copy of knex/pg. Upgrading `pg` to 8.x in this repository seems to have fixed things for me.

**Comment by iamacup** [comment]
I am getting the same thing using keystoneJS with the knex adapter - moving from

`image: 'node:13.10-alpine'` to `image: 'node:13.10-alpine'` creates an identical error, swapping back fixes.

@nicoburns can you explain your fix in more detail, i have tried removing node_modules and the entire postgres data directory

**Comment by kibertoad** [comment]
@iamacup What version of pg driver are you using? updating `pg` dependency fixed problem for @nicoburns

**Comment by kibertoad** [comment]
@iamacup You can also try using knex@0.21.1, it should complain if your peerDependencies are too old for Node 14.

**Comment by yursha** [comment]
I had the same issue with Node.js 14.0.0 (latest), `knex` 0.21.1 (latest), and `pg` 7.8.12. Upgrading `pg` to 8.0.3 fixed the issue.

**Comment by kibertoad** [comment]
@yursha npm didn't complain after updating to 0.21.1? Considering that knex lists `"pg": "^8.0.3",` as a peerDependency now, I am surprised you got no warning prior to updating.

**Comment by iamacup** [comment]
Hey @kibertoad - pg 8.0.3 did fix it for me - my lock file looks like this:

```
"@keystonejs/adapter-knex@^9.0.0", "@keystonejs/adapter-knex@^9.0.3":
  version "9.0.3"
  resolved "https://registry.yarnpkg.com/@keystonejs/adapter-knex/-/adapter-knex-9.0.3.tgz#e87b8547c3de386b81718904792275f1343f1c4b"
  integrity sha512-qDFOGPBGVC8vemqyrgDBr2WKffp2iMVUyhCu7xciSkaK9+EaJWBtoLr6kUi9si6zOJ9eiOjGr3GjfUQNBmZR8A==
  dependencies:
    "@keystonejs/fields-auto-increment" "^5.1.6"
    "@keystonejs/keystone" "^8.1.2"
    "@keystonejs/logger" "^5.1.1"
    "@keystonejs/utils" "^5.4.0"
    "@sindresorhus/slugify" "^0.11.0"
    knex "^0.20.6"
    p-settle "^3.1.0"
    pg "8.0.3"
```

I will make a ticket with Keystone to get all the deps updated :) thanks for your help!

**Comment by yursha** [comment]
@kibertoad No, I don't remember a warning. However, I might have missed it.

**Comment by Robmcmon** [comment]
I have this same error what is odd is one project on my computer it will run and work for one database.. on another different project same setup just different postgresql database it does the same error. I'm on Node 14 but I've downgraded to 12 and there was no difference. Does anyone please have a solution for this or even to trouble shoot it?

**Comment by nicoburns** [comment]
@Robmcmon Note that you will also get this error if the database is inaccessible for some reason (e.g. if you have a typo in the server address, your database is genuinely down, there's a firewall blocking the connection, or you have no internet on the machine you are connecting from). Given that you are seeing this on Node 12 as well I'd suggest that it's likely unconnected to the issue seen here.

However, you may also wish to check that you definitely have an 8.x version of node-postgres (`pg`) installed (you could delete node modules and reinstall to be sure).

**Comment by Robmcmon** [comment]
Well needless to say I found the issue.. on the second project that didn't work I had a error on my directory link to my env file location. should had been "'./.env'" and i had "../.env" one single "." can always derail your day! 

lol Thank you for your assistance as you got me on the track of thinking that it wasn't related to the actual issue here.

**Comment by Mvrs** [comment]
> I have this same error what is odd is one project on my computer it will run and work for one database.. on another different project same setup just different postgresql database it does the same error. I'm on Node 14 but I've downgraded to 12 and there was no difference. Does anyone please have a solution for this or even to trouble shoot it?

I just resolved my problem. Upgrading your `knex: "^0.21.2"` and `pg: "^8.3.0"` seem to help. Glad someone opened this issue 😄

**Comment by akindo** [comment]
Using Node 12 instead of 14 also fixed it for me.

**Comment by kibertoad** [comment]
@akindo Have you tried upgrading `knex` and `pg` without downgrading Node? That should also work.

**Comment by Mohammad4** [comment]
@kibertoad  I'm facing the same error, my DB is hosted on AWS RDS. the node version is 14.15.5 the pg is 8.3.0 and knex 0.21.2. and the error is the same. `error KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?` any advice ?

**Comment by Marguelgtz** [comment]
Having the same issue connecting to a AWS RDS pg database, I have played around with different versions of node but no success. 

**"pg": "^8.5.1",
"knex": "^0.21.17",
node at v15.8.0**

```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (<omit>/Back/node_modules/knex/lib/client.js:348:26)
    at async listCompleted (<omit>/Back/node_modules/knex/lib/migrate/migration-list-resolver.js:12:3)
    at async Promise.all (index 1)
    at async Migrator.latest (<omit>/Back/node_modules/knex/lib/migrate/Migrator.js:64:29)
    at async Command.<anonymous> (<omit>/.nvm/versions/node/v15.8.0/lib/node_modules/knex/bin/cli.js:171:32)
```

When downgrading to **node v12.16.3**

```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (<omit>/Back/node_modules/knex/lib/client.js:348:26)
```

**Comment by Marguelgtz** [comment]
@Mohammad4 were you able to solve the issue?

**Comment by Marguelgtz** [comment]
I was just able to solve my error, if you are using RDS for the first time like me is very likely that this may solve it

It was an aws issue, the server IP needed to be whitelisted to connect to the database. To do this you need to go into the db security group and add an inbound rule w/ your db port and your CIDR IP (`<your ip>/32`).  You can then tested w/ `telnet <rds webpoint> <port>`

**Comment by david-wb** [comment]
I'm seeing this issue when submitting concurrent requests (2 at a time). I'm not using any transactions and the connection pool max size is 6 connections. I'm using Node 12.

**Comment by Mohammad4** [comment]
@Marguelgtz the issue occurred because the database has its own VPC, I solved the error by connecting to the VPC with a VPN. btw I could solve it using your solution but the issue that I can not add the IP for every device that will work with this db. thank you, dear.

**Comment by wvvinicius** [comment]
Hi devs, i have the same problem with my application.

Today it has a service that crashes the application and I need to restart.

I've tried a lot of things but I wasn't successful.


Here is my error and current configuration.

`import knex from 'knex'

const connection = knex({
    client: 'mysql',
    connection: {
        host: '*****',
        port: *****,
        user: '***',
        password: '*****',
        database: '******',
        timezone: 'UTC',
        dateStrings: true,
        

    },
    pool: {
        min: 2,
        max: 6,
        createTimeoutMillis: 3000,
        acquireTimeoutMillis: 10000,
        idleTimeoutMillis: 30000,
        reapIntervalMillis: 1000,
        createRetryIntervalMillis: 100,
        propagateCreateError: false
    },
    useNullAsDefault: true,
    debug: true,

})


export default connection`


----------------


`    public async listarCompetencias() {
        let qry = "";
        let result = false;

        qry = `
            SELECT *
            FROM competencias
            ORDER BY id DESC
            `

        try {
            const trx = await knex.transaction()
            await knex.raw(qry).then((row) => {
                trx.commit()
                result = row[0]
            })
                      
            
            return result;
               

        } catch (error) {

            throw Error(error)
        }
        
    }`

**Comment by Bazze** [comment]
@wvvinicius not sure you're getting the async stuff or commit/rollback statements right.

You should have something like below, mixing await & .then is a bit confusing and you were missing a rollback in the catch block.

```javascript
async function listarCompetencias() {
  const qry = `
    SELECT *
    FROM competencias
    ORDER BY id DESC
  `;

  try {
    const trx = await knex.transaction();
    const [result] = await knex.raw(qry);

    await trx.commit();

    return result;
  } catch (error) {
    await trx.rollback();
    throw Error(error);
  }
}
```

**Comment by JoaoHamerski** [comment]
I'm stuck on this issue for 3 days, i already tried all possible o solutions of the internet and have no idea what is going on. I send the project for other friends to test and it works normally, but to me this error persist, i have all package on last version, node, yarn and npm on last version, nothing works. 

The error is throw when trying to run a seed, inserting data in a table using Knex.

Already tried to downgrade node, pg, and knex, nothing works. Tried to change postgres config `max_connections` and `shared_buffers`, nothing too.

I don't know what is wrong with this.

**Comment by christhegrand** [comment]
What version of node and pg are you on?

**Comment by JoaoHamerski** [comment]
@christhegrand 
Node v14.17.4 - I tried using v14.16.1, v14.0 (the projects only accepts > 14.2) nothing worked.
pg: "^8.7.1" - I tried downgrade to version 8.3.0 and < 8 but nothing worked too.

**Comment by elhigu** [comment]
@JoaoHamerski  Probably not the same problem though, since this issue was specifically the case with node 14 and pg 7. 

Are you running database locally? I don't believe there is much that anyone can help without seeing the code that causes failing.

Closing this issues, since this is starting to collect many unrelated issues.

**Comment by maddyghayas** [comment]
> I'm stuck on this issue for 3 days, i already tried all possible solutions on the internet and have no idea what is going on. I sent the project for other friends to test and it works normally, but to me this error persist, i have all package on last version, node, yarn and npm on last version, still i get this error.
> 
> The error is throw when trying to run a seed, inserting data in a table using Knex.
> 
> Already tried to downgrade node, pg, and knex, nothing works. Tried to change postgres config `max_connections` and `shared_buffers`, nothing too.
> 
> Tried to change knex `pool` config on database config to a lot of different parameters, nothing...
> 
> I don't know what is wrong with this.

@JoaoHamerski were you able to solve this issue?

**Comment by JoaoHamerski** [comment]
> > I'm stuck on this issue for 3 days, i already tried all possible solutions on the internet and have no idea what is going on. I sent the project for other friends to test and it works normally, but to me this error persist, i have all package on last version, node, yarn and npm on last version, still i get this error.
> > The error is throw when trying to run a seed, inserting data in a table using Knex.
> > Already tried to downgrade node, pg, and knex, nothing works. Tried to change postgres config `max_connections` and `shared_buffers`, nothing too.
> > Tried to change knex `pool` config on database config to a lot of different parameters, nothing...
> > I don't know what is wrong with this.
> 
> @JoaoHamerski were you able to solve this issue?

I found 2 solutions when this happened for me:

1 - Reducing the amount of data the Knex was seeding.
2 - I upgraded from HDD to SSD and the error was gone completely.

**Comment by swami-sanapathi** [comment]
We're encountering the "Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?" error intermittently while using Knex with AWS RDS. We've tried various Knex pool configurations, but the issue persists. Our server is functioning well, but at times, this error arises unexpectedly.

@kibertoad  could you pls help us.
