### ISSUE TITLE
update() with returning("*") is returning 1

### ISSUE THREAD

**Issue by wellyssongodinho** [knex/knex#3837]
# Environment

Knex version: 
    "knex": "^0.21.0",
Database + version:
    "oracledb": "^4.2.0",
OS:
Oracle Linux
NodeJS:
v12.16.3

Issue is about oracledb support, tag @ atiertant. 

# Bug

update() with returning("*") is returning 1

1. When use object bellow with "*":

user = await connection('users').where('user_id', req.params.user_id).update(req.body).returning("*")
or
user = await connection('users').where('user_id', req.params.user_id).update(req.body).returning(["*"])
or
user = await connection('users').where('user_id', req.params.user_id).update(req.body, ["*"])

Results:
{
  "user": 1
}

2. When the columns are specificied works well:

user = await connection('users').where('user_id', req.params.user_id).update(req.body,['user_id','user_name']);
or
user = await connection('users').where('user_id', req.params.user_id).update(req.body).returning(['user_id','user_name'])

results:
{
  "user": [
    {
      "user_id": "1",
      "user_name": "Wellysson Godinho"
    }
  ]
}

3. When use "*" shoud be returning all collumns

I would like know why work well with insert function and not work with update function.

**Comment by elhigu** [comment]
Here is runnable reproduction: https://runkit.com/embed/658sj80v3lox

Looks like oracle has special treatment for returning('*')

**Comment by wellyssongodinho** [comment]
Not working accordingly yet. I need that returning in JSON format. 

1. See the result now (here I put all colluns):

user = await connection('users').where('user_id', req.params.user_id).update(req.body).returning(['*']).toSQL().sql;

Result:
{
  "user": "update \"users\" set \"user_avatar\" = ?, \"user_country\" = ?, \"user_country_cca2\" = ?, \"user_country_calling_code\" = ?, \"user_region\" = ?, \"user_region_cca2\" = ?, \"user_phone\" = ?, \"user_bio\" = ?, \"user_status\" = ?, \"user_verification_code\" = ? where \"user_id\" = ? returning \"ROWID\" into ?"
}

2. When use the same example with insert function, the result the field work well:

const user = await connection('users').insert(req.body).returning('*');

Result:
{
"user": [
{
"user_id": "1",
"user_name": "Wellysson Godinho"
....
}
]
}

I would like know why work well with insert function and not work with update function.

**Comment by wellyssongodinho** [comment]
Thanks for helps, but not working accordingly yet.

I need that returning in JSON format.

See the result now using special treatment for oracle:
user = await connection('users').where('user_id', req.params.user_id).update(req.body).returning(['*']).toSQL().sql;

Result:
{
"user": "update "users" set "user_avatar" = ?, "user_country" = ?, "user_country_cca2" = ?, "user_country_calling_code" = ?, "user_region" = ?, "user_region_cca2" = ?, "user_phone" = ?, "user_bio" = ?, "user_status" = ?, "user_verification_code" = ? where "user_id" = ? returning "ROWID" into ?"
}

When use returning ('*') with insert function, the result work well:
const user = await connection('users').insert(req.body).returning('*');

Result:
{
"user": [
{
"user_id": "1",
"user_name": "Wellysson Godinho"
....
}
]
}

It should was obtain the same result of the insert function exhib for update function with returning('*').

**Comment by elhigu** [comment]
Yes... It is not working. That reproduction I added is just for other to easily see what is the problem if they want to fix it. 

I have no idea why it seems to work for insert...

**Comment by OlivierCavadenti** [comment]
Released in [2.5.0](https://github.com/knex/knex/releases/tag/2.5.0)
