### ISSUE TITLE
Heavy database load and long query execution time

### ISSUE THREAD

**Issue by maxtomczyk** [knex/knex#3842]
# Environment

Knex version: 0.21.1
Database + version: PostgreSQL 12.1 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit
OS: MacOS 10.15.4 (19E287) (tested with same result on Windows 10)
Node.js: 12.16.1

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Running query with knex (without raw) causes very high load of database server and takes long time to execute, while running same query with `.toString()` method inside `knex.raw()` works fine.

2. Error message

No error message is present, just long time of execution and very high load.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

I prepared reproduction based on our project structure where we found this bug. I made a repo for it as it needs some migrations and seeds to reproduce: https://github.com/maxtomczyk/knex-reproduction

Code showing difference between calling query:
```
const knex = require('knex')(require('./knexfile'))

function createQuery () {
  // Simulate variables obtained from other sources in original project
  const startDate = new Date(+new Date() - 2 * 60 * 60 * 1000)
  const ownersIds = [5056, 19495, 6748, 380, 2014, 12624, 4830, 9487, 10434, 7422, 12144, 5220, 10142, 12480, 17521, 14422, 1412, 17132, 14879, 999, 312, 2341, 19713, 16166, 1409, 16217, 8920, 14487, 17455, 1201, 12807, 7416, 5340, 10637, 1745, 1386, 19192, 13178, 4977, 11769, 19946, 2713, 10200, 11909, 13519, 9588, 4528, 19737, 2685, 8429, 7222, 2017, 18114, 13685, 4062, 19409, 18218, 15987, 10496, 3499, 8071, 1516, 14590, 9495, 5458, 6041, 8992, 17768, 15929, 3540, 1685, 7839, 11095, 15432, 8786, 9107, 819, 9250, 5822, 4094, 619, 15520, 2419, 17051, 1208, 12966, 12447, 8591, 6786, 12725]
  const userData = {
    coords: '(3733027.200898386, 1309786.8685408758, 5002998.4321979005)',
    age: 37
  }
  const dist = 49000

  // Create knex query
  return knex('events as e')
    .select('e.id', 'e.uuid', 'e.title', 'e.description', 'e.photo_url as photoUrl', 'e.visibility', 'e.require_confirmation as requireConfirmation', 'e.type', 'e.date', knex.raw('count(p.*)::int as participants'), knex.raw('round((earth_distance(?, e.location) / 1000)::numeric, 1) as distance', [userData.coords]))
    .leftJoin('events_participants as p', 'p.events_id', 'e.id')
    .groupBy('e.id')
    .orderBy('e.date', 'asc')
    .whereRaw('e.date > ?', [startDate])
    .andWhereRaw('?::int <@ e.age_restriction', userData.age)
    .andWhereRaw('earth_box(?, ?) @> e.location', [userData.coords, dist])
    .andWhereRaw('earth_distance(?, e.location) <= ?', [userData.coords, dist])
    .andWhereRaw('owner_id NOT IN (??)', [ownersIds])
}

async function start () {
  try {
    // METHOD 1
    const s1 = +new Date()
    const query1 = createQuery()
    const sql = query1.toString()
    // Run query knex which executes in reasonable time
    await knex.raw(sql)
    console.log(`Method #1 executed in: ${(+new Date() - s1)}ms`)

    // METHOD 2
    const s2 = +new Date()
    const query2 = createQuery()
    // Run knex query in a normal way
    await query2
    console.log(`Method #2 executed in: ${(+new Date() - s2)}ms`)
    process.exit()
  } catch (e) {
    console.error(e)
  }
}

start()

```

Method #1 is taking usually about 1 second to execute, while method #2 takes 60-110 seconds to finish. Sometimes it needs multiple tries to reproduce it as method #2 seems to work normal. I noticed that it can be related to table content, as bug seems to not occur when field description or photo_url (events table) is relatively short (I'm not sure about it, so not trying to reproduce it in my repo)

**Comment by elhigu** [comment]
Probably some query parameter are not the same in stringified query which causes databse to be able to supress result set early. Check out if the returned data si the same for both of the queries.

Doesn't sound like any bug in knex. You can try to compare what kind of query is outputted by result from query.toString() and query.toSQL(). Then you can try instead of knex.raw(query.toString) run knex.raw(query.toSQL().sql, query.toSQL().bindings) and see if that is also slow. 

Then you may also compare query plans of the methods by running knex.raw('explain ?', [query]); and  knex.raw('explain ?', [query.toString()]).

Closing as doesnt seem like a knex bug but just SQL optimization issue where invalid query generated by toString() (which is never meant to be ran) and a query with correctly passed query parameters are compared. Lets reopen if there are something that points to a bug in knex.

**Comment by elhigu** [comment]
Also running code with environment variable DEBUG=knex:* might help (or might not) with debugging.

**Comment by elhigu** [comment]
Also #2: try to drop `.whereRaw('e.date > ?', [startDate])` from the query and see if both are equally slow/fast after that. 

Also `.andWhereRaw('owner_id NOT IN (??)', [ownersIds])` is a hack and wrong... you are using identity replacement instead of passing all the ids as separate bindings. Though it shouldn't cause any difference in this case.

**Comment by maxtomczyk** [comment]
I tried all things you recommended, hope I didn't forget about anything.

### Is the same data returned from both queries?

I modified code to print first element and rows count and it looks like its the same. To be sure I dumped both results to JSON and compared both files and full results are also the same.

```
Method #1 executed in: 1041ms
Method #1 rows: 5131
Method #1 first row:
{
  id: 17532,
  uuid: '5eb219d2-3541-ce52-b3e2-ceb08fc72c2a',
  title: 'Testfest #17532',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  photoUrl: 'https://hiddenurl.com/users/5eb078ee-bd04-d85d-02d5-d78c6e2df5d2/pictures/e24e1e1e-9b49-41e9-a0ef-2028ae4e74ff.jpeg,',
  visibility: 3,
  requireConfirmation: true,
  type: 4,
  date: 2020-05-07T10:04:44.089Z,
  participants: 25,
  distance: '19.8'
}
Method #2 executed in: 70864ms
Method #2 rows: 5131
Method #2 first row:
{
  id: 17532,
  uuid: '5eb219d2-3541-ce52-b3e2-ceb08fc72c2a',
  title: 'Testfest #17532',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  photoUrl: 'https://hiddenurl.com/users/5eb078ee-bd04-d85d-02d5-d78c6e2df5d2/pictures/e24e1e1e-9b49-41e9-a0ef-2028ae4e74ff.jpeg,',
  visibility: 3,
  requireConfirmation: true,
  type: 4,
  date: 2020-05-07T10:04:44.089Z,
  participants: 25,
  distance: '19.8'
}
```

### Queries generated by .toSQL() and .toString()
Outputs cannot be just differed as .toString() returns query with values and .toSQL() returns query with `?`. As values in `bindings` property was the same as those used in .toString() query I manually replaced them with `?` too to compare structure of both queries. Also replaced ids inside NOT IN() to `...`. After those operations both queries structure was the same:
```
select "e"."id", "e"."uuid", "e"."title", "e"."description", "e"."photo_url" as "photoUrl", "e"."visibility", "e"."require_confirmation" as "requireConfirmation", "e"."type", "e"."date", count(p.*)::int as participants, round((earth_distance(?, e.location) / 1000)::numeric, 1) as distance 
from "events" as "e" 
left join "events_participants" as "p" on "p"."events_id" = "e"."id" 
where e.date > ?
and ?::int <@ e.age_restriction 
and earth_box(?, ?) @> e.location 
and earth_distance(?, e.location) <= ? 
and owner_id NOT IN (...) 
group by "e"."id" 
order by "e"."date" asc
```

### Is running queries generated with .toSQL() same slow?
I created another code in test project to run query generated by .toSQL() method.
```
const query3 = createQuery()
const r3 = await knex.raw(query3.toSQL().sql, query3.toSQL().bindings)
```
Results of running this are logged as Method #3. Running query generated by .toSQL() method is slow too. Also it's results are the same:

```
Method #3 executed in: 75800ms
Method #3 rows: 5131
Method #3 first row:
{
  id: 17532,
  uuid: '5eb219d2-3541-ce52-b3e2-ceb08fc72c2a',
  title: 'Testfest #17532',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  photoUrl: 'https://hiddenurl.com/users/5eb078ee-bd04-d85d-02d5-d78c6e2df5d2/pictures/e24e1e1e-9b49-41e9-a0ef-2028ae4e74ff.jpeg,',
  visibility: 3,
  requireConfirmation: true,
  type: 4,
  date: 2020-05-07T10:04:44.089Z,
  participants: 25,
  distance: '19.8'
}
```
### Query plans
I'm not sure if I did it correctly, but the results are different there.
##### `knex.raw('explain ?', [knex.raw(query1.toString())])`:
```
Sort  (cost=18192.35..18192.35 rows=2 width=653)
  Sort Key: e.date
  ->  GroupAggregate  (cost=18191.41..18192.34 rows=2 width=653)
        Group Key: e.id
        ->  Sort  (cost=18191.41..18191.54 rows=50 width=681)
              Sort Key: e.id
              ->  Hash Right Join  (cost=9669.02..18190.00 rows=50 width=681)
                    Hash Cond: (p.events_id = e.id)
                    ->  Seq Scan on events_participants p  (cost=0.00..7208.99 rows=499699 width=36)
                    ->  Hash  (cost=9669.00..9669.00 rows=2 width=649)
                          ->  Seq Scan on events e  (cost=0.00..9669.00 rows=2 width=649)
                                Filter: ((date > '2020-05-07 12:21:15.592+02'::timestamp with time zone) AND (37 <@ age_restriction) AND (cube_enlarge(('(3733027.200898386, 1309786.8685408758, 5002998.4321979005)'::cube)::cube, '48999.87950063193'::double precision, 3) @> (location)::cube) AND (owner_id <> ALL ('{5056,19495,6748,380,2014,12624,4830,9487,10434,7422,12144,5220,10142,12480,17521,14422,1412,17132,14879,999,312,2341,19713,16166,1409,16217,8920,14487,17455,1201,12807,7416,5340,10637,1745,1386,19192,13178,4977,11769,19946,2713,10200,11909,13519,9588,4528,19737,2685,8429,7222,2017,18114,13685,4062,19409,18218,15987,10496,3499,8071,1516,14590,9495,5458,6041,8992,17768,15929,3540,1685,7839,11095,15432,8786,9107,819,9250,5822,4094,619,15520,2419,17051,1208,12966,12447,8591,6786,12725}'::integer[])) AND (sec_to_gc(cube_distance(('(3733027.200898386, 1309786.8685408758, 5002998.4321979005)'::cube)::cube, (location)::cube)) <= '49000'::double precision))
```

##### `knex.raw('explain ?', [query2])`
```
Sort  (cost=14898.82..14898.82 rows=2 width=653)
  Sort Key: e.date
  ->  Finalize GroupAggregate  (cost=14897.79..14898.81 rows=2 width=653)
        Group Key: e.id
        ->  Gather Merge  (cost=14897.79..14898.25 rows=2 width=657)
              Workers Planned: 1
              ->  Partial GroupAggregate  (cost=13897.78..13898.02 rows=2 width=657)
                    Group Key: e.id
                    ->  Sort  (cost=13897.78..13897.85 rows=29 width=681)
                          Sort Key: e.id
                          ->  Nested Loop Left Join  (cost=0.42..13897.08 rows=29 width=681)
                                ->  Parallel Seq Scan on events e  (cost=0.00..6348.41 rows=1 width=649)
                                      Filter: ((date > '2020-05-07 12:21:15.621+02'::timestamp with time zone) AND (37 <@ age_restriction) AND ('(3684027.3213977544, 1260786.989040244, 4953998.552697268),(3782027.080399018, 1358786.7480415078, 5051998.311698533)'::cube @> (location)::cube) AND (owner_id <> ALL ('{5056,19495,6748,380,2014,12624,4830,9487,10434,7422,12144,5220,10142,12480,17521,14422,1412,17132,14879,999,312,2341,19713,16166,1409,16217,8920,14487,17455,1201,12807,7416,5340,10637,1745,1386,19192,13178,4977,11769,19946,2713,10200,11909,13519,9588,4528,19737,2685,8429,7222,2017,18114,13685,4062,19409,18218,15987,10496,3499,8071,1516,14590,9495,5458,6041,8992,17768,15929,3540,1685,7839,11095,15432,8786,9107,819,9250,5822,4094,619,15520,2419,17051,1208,12966,12447,8591,6786,12725}'::integer[])) AND (sec_to_gc(cube_distance('(3733027.200898386, 1309786.8685408758, 5002998.4321979005)'::cube, (location)::cube)) <= '49000'::double precision))
                                ->  Index Scan using events_participants_pkey on events_participants p  (cost=0.42..7548.41 rows=25 width=36)
                                      Index Cond: (events_id = e.id)
```

### Dropping `.whereRaw('e.date > ?', [startDate])`
Looks like dropping `.whereRaw('e.date > ?', [startDate])` resolves the problem. Also dropping any of `earth_box` or `earth_box` and keeping `.whereRaw('e.date > ?', [startDate])` active resolves problem.

**Comment by elhigu** [comment]
Ok. Looks like because parameters are a bit different that postgresql decides to make different execution plan for the query.

**Comment by maxtomczyk** [comment]
Thanks for your answer. Is it desired/correct effect as queries generated by toSQL() and toString() was the same?

**Comment by elhigu** [comment]
No. You should not run queries generated by .toString() they can easily contain SQL injection holes and parameteres might not be rendered correctly to the query's SQL string.

> as queries generated by toSQL() and toString() was the same?

They are not exactly the same, even if you think they are :) Ok, sometimes they are, except that SQL database server has a little bit more type information when kind of parameters were passed to the query compared to the prepared statement with generic parameter bindings.

**Comment by maxtomczyk** [comment]
Okay, so what is the correct way to omit this issue? Should I just write this query in SQL and use knex.raw() to bind parameters and run query, or is there any other (better/cleaner) solution?

**Comment by elhigu** [comment]
What issue? 🤔 that query takes a long time to execute? 

Write the query in a different manner and hope that postgres optimize its query plan better. Query planning also depends on table sizes etc.

**Comment by maxtomczyk** [comment]
Okay, that's what I will do. Thank you for all your replies 😊
