### ISSUE TITLE
Knex timeout with private VPC while using serverless.

### ISSUE THREAD

**Issue by iamaquaman** [knex/knex#3843]
# Environment

Knex version: 0.20.13
Postgre: 11.6
OS: Mac OS Catalina

1. I am using serverless to deploy a Nodejs lambda. I am using node 12.
I am using Knex and I get the error bellow whenever I do not use a VPN because my database is a Postgre Aurora DB that is inside a private VPC. Whenever I do use a VPN, serverless deploys my lambda just fine. Why is Knex trying to establish a connection to the DB locally? Or is that Serverless that is trying to do that?

2. `Knex Timeout Error -------------------------------------
  KnexTimeoutError: Could not connect to database using schwifty knex instance for models: "UserFeedback", "ModelQuestion", "ServiceUser".: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
      at Client_PG.acquireConnection (PATH TO REPO/node_modules/knex/lib/client.js:347:26)`

Schwifty.js is in my /config/ directory:

```
'use strict';

module.exports = {
    knex: {
        client: 'pg',
        useNullAsDefault: true,
        connection: {
            host: process.env.DATABASE_HOST,
            user: process.env.DATABASE_USER,
            password: process.env.DATABASE_PASS,
            database: process.env.DATABASE
        }
    }
};


```

**Comment by elhigu** [comment]
Closing since this doesn't look like a knex bug.  Also you probably should not set `useNullAsDefault` unless you are aiming with SQLite3 compatible code.
