### ISSUE TITLE
Closed connections not being released from pool

### ISSUE THREAD

**Issue by iostreamer-X** [knex/knex#3844]
# Environment

Knex version: 0.21.1
Database + version: Postgres 11.5
OS: macOS

# Bug

### Setup:
I set up min & max as 3 for my pool size. I then start 3 transactions asynchronously. 
Each transaction:
-  sets a local statement and idle timeout as 200 seconds
- queries `pg_backend_pid`
- sleeps for 200 seconds

Except that one of those 3 transactions has 1 second as its statement and idle timeout.

After 5 seconds, I start another transaction and try to query `pg_backend_pid`

### Expectation:
- The transaction which had 1s as timeout should have been evicted from the pool.
- The transaction started after 5 seconds should have been able to acquire a connection

### Result:
- The transaction started after 5 seconds is unable to get a connection and fails with:
```js
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

### Instrumentation:
I have setup a `setInterval` which logs the `querable` status of each connection in pool. Something like this:
```js
setInterval(() => {
        console.log('USED:', knex.client.pool.used.map(poolMember => poolMember.resource._queryable))
}, 200);
```

Here's a slice of these logs:
```js
USED: [ true, true, true ]
USED: [ true, true, true ]
USED: [ true, true, true ]
USED: [ true, true, true ]
USED: [ true, true, true ]
USED: [ false, true, true ]
USED: [ false, true, true ]
USED: [ false, true, true ]
USED: [ false, true, true ]
```

This makes sense because one those transactions crossed the timeout and were terminated by database.

And if we continue logging till we attempt to start a transaction after 5 seconds these are the logs:
```js
USED: [ false, true, true ]
USED: [ false, true, true ]
USED: [ false, true, true ]
(node:10353) UnhandledPromiseRejectionWarning: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/Users/iostreamer/knex-pool-test/node_modules/knex/lib/client.js:349:26)
(node:10353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
USED: [ false, true, true ]
USED: [ false, true, true ]
```

My understanding has been that the pool was never rid of that closed connection and hence that last transaction was unable to acquire a new connection. 

Please correct me if I am wrong or missed something. Also I can provide additional code if wanted.

Thanks!

PS:
I tried a hack where before acquiring a transaction I checked if there were any closed/errored connection in pool, if so, then I cleaned them up. Like this:
```js
for (const poolMember of knex.client.pool.used) {
        const result = knex.client.pool.validate(poolMember.resource);
        if (!result) {
            await knex.client.releaseConnection(poolMember.resource)
        }
        console.log('validate:', result);
    }
```
This seems to work just fine and the transaction started after 5 seconds is able to acquire a connection.

**Comment by kibertoad** [comment]
@iostreamer-X Could you please provide full reproduction code?

**Comment by iostreamer-X** [comment]
Surely! @kibertoad 
Here's the code on runkit: https://runkit.com/iostreamer-x/5eb41789ebd8c60014486a13
Ping if you need anything else.

**Comment by elhigu** [comment]
> My understanding has been that the pool was never rid of that closed connection and hence that last transaction was unable to acquire a new connection.

When connection error comes from DB closing the connection it is not evicted from pool until the next time that resource is tried to be returned from the pool. So When connection is acquired from pool next time the validation will be ran and the validation should notice that connection is not good anymore and discard it.

**Comment by iostreamer-X** [comment]
Oh! In the setup above, where there were 3 resources in pool and one of them was not `quereable` after some time. 

From what you explained, when I tried to acquire a 4th connection knex/tarn should have validated the faulty connection, created a new one and returned that.

But apparently trying a 4th connection results in `Knex: Timeout error`.

Is there something I am missing @elhigu ?

**Comment by iostreamer-X** [comment]
Is the case that tarn perceived that faulty connection as a busy resource?

**Comment by elhigu** [comment]
@iostreamer-X No. Tarn.js just doesn't check any resources that are idling in the pool. They are only validated during creation and when they are about to be acquired by knex.

**Comment by elhigu** [comment]
> From what you explained, when I tried to acquire a 4th connection knex/tarn should have validated the faulty connection, created a new one and returned that.
>
> But apparently trying a 4th connection results in Knex: Timeout error.

If pool size is 3 and you are trying to acquire 4th connection timeout sounds like correct thing to return. In your debug prints you are listing always used resources. Doesn't it just mean that you have never ended those transactions you have opened?

**Comment by elhigu** [comment]
You could try to run your code with DEBUG=knex:* environment variable set to see in which point stuff is fetched and returned to the pool. Also tarn has pretty good amount of events to track down what is happening there internally.

**Comment by iostreamer-X** [comment]
Got it. Essentially if for some reason application is unable to commit or rollback a transaction, knex will still view that as a live resource which is being used. And until we make the transaction to commit/rollback knex won't validate the connection.

So if a transaction was cancelled by server and then we try to commit it we might get and error like `Client is not querable`, and the corresponding connection will be removed from the pool.

It's kinda like when the application has acquired a connection, knex won't intervene in any way till the application lets go of it.

Is that understanding correct @elhigu ?

**Comment by elhigu** [comment]
As far as I know I thought that calling trx.commit() should always return connection to the pool even if commit fails. And when connection is acquired next time from the pool it should be discarded. I'm not sure though if it actually works exactly like that currently.

**Comment by iostreamer-X** [comment]
Thanks a lot for explaining this! @elhigu 
I think I should close this now:

For anyone who stumbles upon this:
knex will evict as per the discussion above and will work normally. If one observes pool hogging, try looking at leaks and missing rollbacks or commits.

**Comment by tomlagier** [comment]
Question: Does this imply that we need 1 connection in the pool per simultaneous transaction we intend to support?

**Comment by elhigu** [comment]
@tomlagier Yes. With knex (and pretty much with all databases also) transaction requires that the related queries are sent to DB through the same connection.
