### ISSUE TITLE
trx.commit() does not throw error when commit fails

### ISSUE THREAD

**Issue by chescos** [knex/knex#3847]
# Environment

Knex version: 0.21.1
Database + version: PostgreSQL 12.2
OS: Ubuntu 18.04

# Bug

When calling the `commit()` method on a transaction and the transaction fails because it was timed out by PostgreSQL through the `idle_in_transaction_session_timeout` setting, then no exception is thrown. Instead, the `commit()` method just returns `undefined` instead of an object.

Here's a code example that shows the issue:

```js
const sleep = async (ms) => new Promise((res) => setTimeout(() => res(), ms));

(async () => {
  // Set `idle_in_transaction_session_timeout` to 1000 ms.
  // Postgres will kill any transactions that are idle for longer than 1000 ms.
  await knex.raw('set idle_in_transaction_session_timeout to 1000;');

  // Create the transaction.
  const trx = await knex.transaction();

  // Execute any queries, doesn't really matter.
  const updated = await trx('users')
    .where('id', 1)
    .update({
      username: 'test1',
    });

  // We have to wait longer than 1000 ms for
  // `idle_in_transaction_session_timeout` to take effect.
  await sleep(1500);

  // Commit the transaction.
  // This will not throw an error. Instead, it will just return `undefined`.
  const commit = await trx.commit();

  // `isCompleted` also returns `true`,
  // even though the transaction was not really committed.
  const isCompleted = trx.isCompleted();

  // Get the previously updated row from the database to verify
  // that the transaction was not committed.
  const result = await knex('users').where('id', 1);

  console.log({
    updated,
    commit,
    result,
    isCompleted,
  });
})();
```

**Comment by elhigu** [comment]
I'm pretty sure that calling `trx.commit()` actually should never throw an error even if it did fail because of connection error. Probably the reason to that is that transaction actually might get committed / rolled back also implicitly at any time, so basically the consistent way to find out if transaction is committed or rolled back is to `await trx.executionPromise` result.

Commit returning undefined also seems correct functionality... Anyways I really can understand why there is confusion about how this works, because current transaction documentation is so messy and still seems to contain also some invalid information. 

Closings as this is intended functionality as far as I know.

**Comment by chescos** [comment]
@elhigu Hey, thanks for clearing that up. So if I want to know whether the transaction was actually commited, I should always check the result of `await trx.commit()`? E.g:
```js
const commit = await trx.commit();

if (!commit) {
  // Commiting the transaction failed, throw an error...
}
```
That's how it's supposed to be used? If so, I really think this should be in the docs. Otherwise, I think most people would assume that `await trx.commit()` not throwing an error means that it succeeded.

**Comment by kibertoad** [comment]
@chescos See documentation (it should work with any transaction, I think, not just with the one you get from transactionProvider, but worth a check):

```
You can access promise that gets resolved after transaction is rolled back explicitly by user or committed, or rejected if it gets rolled back by DB itself, when using either way of creating transaction, from field executionPromise:

const trxProvider = knex.transactionProvider();
const trx = await trxProvider();
const trxPromise = trx.executionPromise;

const trx2 = await knex.transaction();
const trx2Promise = trx2.executionPromise;

const trxInitPromise = new Promise(async (resolve, reject) => {
  knex.transaction((transaction) => {
    resolve(transaction);
  });
});
const trx3 = await trxInitPromise;
const trx3Promise = trx3.executionPromise;
```

**Comment by elhigu** [comment]
```
try {
  trx.commit(); // no need to await this since trx.executionPromise will wait it to finish anyways
  await trx. executionPromise;
  // transaction was success
} catch (err) {
  // transaction failed / was rolled back
}
```

**Comment by elhigu** [comment]
>  most people would assume that await trx.commit() not throwing an error means that it succeeded.

Some does I believe, but AFAIK the documentation doesn't say it works like that... However we really should add better documentation for trx.commit and trx.rollback methods.

**Comment by chescos** [comment]
Thanks, guys! That helps a lot. I have missed that while reading the docs.
