### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [knex/knex#3848]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/knex/knex)](https://www.tickgit.com/browse?repo=github.com/knex/knex)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/knex/knex)](https://www.tickgit.com/browse?repo=github.com/knex/knex)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit` and this is not a bot posting! I'm suggesting the badge for repos that have TODO comments and already have some badges in their README.)

**Comment by kibertoad** [comment]
Thank you for the suggestion, but currently we have no plans to do so :)
