### ISSUE TITLE
[electron] problem to initialize knex 

### ISSUE THREAD

**Issue by paranoid73** [knex/knex#3852]
# Environment

Knex version: Lastest
Database + version: sqlite3
OS: Arch Linux

my database structure :
![2020 05 13-10 17 04 screenshot](https://user-images.githubusercontent.com/34898251/81800815-f6203300-9502-11ea-8265-2226df1bc542.png)
the commands to generate migrations and seeds work without problem , but when I launch the project without using the commands provided by knex:

connection.js
```
const knex = require('knex')
const config = require('./knexfile')
const connection = knex(config.development)
```
knexfile.js
```
module.exports = {
  development: {
    client: 'sqlite3',
    connection: {
      filename: 'db.sqlite'
    },
    migrations: {
      directory: './migrations'
    },
    useNullAsDefault: true
  },
  production: {
    client: 'sqlite3',
    connection: {
      filename: './src/renderer/database/db.sqlite'
    },
    useNullAsDefault: true
  }

}
```

and i try to use knex in my project :
```
this.dataCHF = await connection('chambreFroide').select('*')
console.log(this.dataCHF)
```
There is this error :
``chambreFroide` - SQLITE_ERROR: no such table: chambreFroide`

because it create a new database file ignoring migrations and seeds .
is it possible to initialize knex and start migrations , seeds from my javascript file without using 
` knex migrate:latest` ?

**Comment by kibertoad** [comment]
Yes. Check out the programmatic API for migrations in docs. Ping me again if you can't find it.

**Comment by paranoid73** [comment]
finally i dop .

**Comment by kibertoad** [comment]
@paranoid73 Not sure based on your last post if you found how to do it, in case you didn't: http://knexjs.org/#Migrations-API

Please let me know if you'll still have any questions.

**Comment by cnTrent** [comment]
Sure, I can help you with that. Here's the translation:

"I have a question about Electron. I'm using the SQLite3 database, but during the packaging process, it seems to be looking for other databases due to Knex, and then reports an error that it can't find the module. Have you encountered this issue before?"
