### ISSUE TITLE
Typescript definition missing havingNotIn

### ISSUE THREAD

**Issue by Cellule** [knex/knex#3854]
`havingNotIn` is missing in the typing definition here
https://github.com/knex/knex/blob/4fa6e1f8c27fac59edb88c75e1f26f801fab2aa8/types/index.d.ts#L503-L513

But it is documented here
https://knexjs.org/#Builder-havingNotIn

**Comment by kibertoad** [comment]
@Cellule Would you be open to sending a PR for this?

**Comment by pavanbellamkonda** [comment]
@kibertoad I created a Pull request for these changes.

**Comment by kibertoad** [comment]
Released in 0.95.0
