### ISSUE TITLE
ERROR on create migrations folder MacOs Catalina

### ISSUE THREAD

**Issue by criarte** [knex/knex#3856]
# Environment

Knex version: 0.21.1
Database + version: Postgres 12.3.1
OS: MacOS 10.15.4 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

when I use the command
node_modules/.bin/knex migrate:make create_users --env test

2. Error message
I get:
Using environment: test
Using environment: test
Using environment: test
Error: EROFS: read-only file system, mkdir '/src'

**Comment by kibertoad** [comment]
Sounds like problem is that you are trying to write to a directory that you don't have write access to. Check your knexfile migrations configuration, looks like you have '/src' instead of `src`

**Comment by criarte** [comment]
Hi guys , 

I fix it with:

migrations: {
      directory: `${__dirname}/src/migrations`,
    },

Thks
