### ISSUE TITLE
Table dot asterisk for select/columns methods not working

### ISSUE THREAD

**Issue by Crusader4Christ** [knex/knex#3860]
# Environment
Knex version: knex@0.21
Database + version: MySQL 5.7
OS: Linux

# Bug
`knex('table').select('table.*').join('other_table'...)` 
should give sql:
```select `table`.* from `table` join `other_table` ...```
but knex give me:
```select `table`.`` from `table` join `other_table` ...```

**Comment by elhigu** [comment]
Cannot recproduce: 

```
const Knex = require('knex');

const knex = Knex({
  client: 'mysql',
});

knex('table').select('table.*').toSQL()
```

Outputs:
```
select `table`.* from `table`
```

https://runkit.com/embed/zg0jee0rl6sq

**Comment by soonoo** [comment]
[`wrapIdentifier`](https://knexjs.org/guide/#wrapidentifier) was accidentally removing asterisk from column name in my case.
