### ISSUE TITLE
'bigint' type is a string in query results.

### ISSUE THREAD

**Issue by rhys-vdw** [knex/knex#387]
Following query returns a Postgres `bigint` for the `assigned_client_count` column (results of `COUNT(*)`.

This is a string, rather than a `Number`, in the returned results.

``` JavaScript
{ __cid: '__cid40',
  method: 'select',
  options: undefined,
  bindings: [ 1 ],
  sql: 'select "id", "name", "fluid_account_id", "survey_fid", coalesce(assigned_client_count, 0) as assigned_client_count from (select "survey_id", count(*) as "assigned_client_count" from "client_surveys" group by "survey_id") as "t_counts" right join "fluid_surveys" on "t_counts"."survey_id" = "fluid_surveys"."id" where "fluid_account_id" = $1' }
```

``` JavaScript
 [ { id: 6,
    name: 'some name',
    fluid_account_id: 1,
    survey_fid: 69942,
    assigned_client_count: '1' } ]
```

**Comment by miroslavvojtus** [comment]
Hello guys. I have the very same problem. We are using bigints for some eventually large tables.

Unfortunately, I consider @sidazhang solution as degrading the bigint to int (eventual precission loss).

Do you suggest to rather not use bigint or there exists some workaround which keeps precision?

One which came to my mind is accepting string as bigint representation but knex will reject such a query to table with conditioning bigints with string as value. In case of indexes i do not need to do a math operations on the number.

```
Error: invalid input syntax for integer: "{"1"}"
    at Connection.Object.<anonymous>.Connection.parseE (D:\repos\ImgPoolWebApp\node_modules\pg\lib\connection.js:553:11)
    at Connection.Object.<anonymous>.Connection.parseMessage (D:\repos\ImgPoolWebApp\node_modules\pg\lib\connection.js:378:19)
    at Socket.<anonymous> (D:\repos\ImgPoolWebApp\node_modules\pg\lib\connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20), level=error
```

Would it be possible somehow to accept where condition with string in case the left operand is bigint? 

1. JS:`query.where("bigintkey", "123456")`
2. if the "bigintkey" is of type bigint
3. SQL:`WHERE "bigintkey" = 123456`

The validity of value would need to be handled by consumers.

Right now we must accept the queries returning string and convert to number in conditions => precision lost. 
This seems to me as an API issue regardless the underlying library has some engine level limitations.

The last resort solution would be for us using strings as alternative to bigint in db and generate some uuids in preference to autoincremented primary keys.

**Comment by elhigu** [comment]
@miroslavvojtus I have handler (for pg-types) which converts bigints to javascript numbers and throws an error if value is too big for number to handle. If your values are less that 53 bits you will not lose any precision.

I'm failing to see what is the problem you are actually having there. If you like to use bigints with full precision you can keep them as strings in javascript side.
