### ISSUE TITLE
postProcessResponse not called for streamed queries ?

### ISSUE THREAD

**Issue by mlarcher** [knex/knex#3870]
# Environment

Knex version: 0.21.1
Database + version: postgres 11
OS: node:14.2.0 docker container

# Feature discussion / request

It seems that `postProcessResponse` is not called on the resulting rows when using `.stream()` on a query. Can someone tell me if this is a bug or the intended behavior, and if there is a known workaround by any chance ?

**Comment by elhigu** [comment]
It is not intentional and I don't believe that there is any workaround for it.

**Comment by mlarcher** [comment]
Thank you for the info @elhigu 
I guess it counts as a bug then, as it was quite unexpected.

**Comment by sirfilip** [comment]
I can pick this one up

**Comment by kibertoad** [comment]
Would be awesome!

**Comment by sirfilip** [comment]
Quick question is it ok if i add test coverage and can go with jest or mocha it is all the same to me, please tell me what is the project preference ?

**Comment by kibertoad** [comment]
@sirfilip Test coverage is actually mandatory for PRs with rare exceptions. Take a look at existing integration tests, they use mocha.

**Comment by sirfilip** [comment]
Thanks @kibertoad  looks like i need to get something from my sight :). Now all makes sence. I am on it!

**Comment by sirfilip** [comment]
^^^ it is messy not a real pr just want to make sure that i am going in the right direction. It looks like i will have to wrap each row of the stream inside the client.postProcessResponse with the row and connection as context i think that i am maybe missing someting

**Comment by cubikrichard** [comment]
@sirfilip Did your fork need more work before creating a PR? Is there anything I can help with to keep it moving?

**Comment by sirfilip** [comment]
Sorry for the late response what i submitted was a direction that i took to resolve this issue and it feels a bit messy so not really sure if i should continue with the implementation for the rest of the drivers. But if it looks ok from your side i can continue and implement this for the other drivers quickly, probably in the following days. Please letme know. I dont have any problem with discarding the code cause i really hope there is a cleaner way to implement this.

**Comment by cubikrichard** [comment]
I used your fork as inspiration, but, it was possible to hook into the stream at a higher level, so to avoid having to implement it for each driver. 

`lib/runner.js` https://github.com/knex/knex/pull/3931/files

**Comment by sirfilip** [comment]
That is awesome! I like your approach by far better then the one i took. I vote for your proposal :). Great job !!!

**Comment by andreaspalsson** [comment]
Seems like the `query-response` event has the same issue. If you get the response as a stream it will not emit the event.

**Comment by kibertoad** [comment]
@mlarcher Could you please check if 0.21.3 addresses your issue?

**Comment by mlarcher** [comment]
@kibertoad I'm currently in vacation, I'll test it when I get back

**Comment by mlarcher** [comment]
I tested the patch successfully on our project. Thank you guys, Ioved how everything unrolled smoothly in this issue 👍
