### ISSUE TITLE
manual transaction commit + throwing error

### ISSUE THREAD

**Issue by skarbovskiy** [knex/knex#3874]
Knex version: 0.21.1

code below may seem weird, but actually it has some usecases and currenty not working as exprected
```js
return db.transaction(async (trx) => {
	await db('users').update({ updated_at: 'now' }).where('id', 1).transacting(trx);
	await trx.commit();
	throw new Error('some error');
});
```
Currently this results to an `undefined` promise resolution, not rejecting with `some error`.

Previously this code worked as expected (last working version - `20.11`)

**Comment by elhigu** [comment]
You should not call trx.commit() inside the async handler. It is done implicitly when handler returns a promise.

Try:
```
return db.transaction(async (trx) => {
    await trx('users').update({ updated_at: 'now' }).where('id', 1);
    throw new Error('some error');
  });
```

**Comment by skarbovskiy** [comment]
as i mentioned before, this code can seem weird)
idea is to commit and throw error after successful commit.
Example usecase
```js
async function outer() {
	return db.transaction(async (trx) => {
		await trx('users').update({ updated_at: 'now' }).where('id', 1);
		await inner(trx);
		throw new Error('some error');
	});
}

async function inner(trx) {
	await trx('users').update('updated_at', 'now').where('id', 2);
	await trx.commit();
	throw new Error('some error');
}

outer();
```

Inner function should do some stuff inside transaction, manually commit outer transaction and do some third-party stuff, that can lead to error and without commit - to whole transaction rollback.

**Comment by elhigu** [comment]
If you want to throw an error after successful commit, you cannot use `async trx => {}` handler function, because using that causes knex to do implicit commit / rollback. So you need to do something like (and be careful of not leaving transactions open anywhere): 

```
async function outer() {
	const trx = db.transaction();
        await trx('users').update({ updated_at: 'now' }).where('id', 1);
	await inner(trx);
       // also    	
}

async function inner(trx) {
	await trx('users').update('updated_at', 'now').where('id', 2);
	await trx.commit();
	throw new Error('some error');
}

outer();
```

So that design doesn't look really robust unless there is some other safety measures implemented.

**Comment by elhigu** [comment]
> has some usecases and currenty not working as exprected

To me all this looked that it is failing as expected.

**Comment by skarbovskiy** [comment]
well it actually not failing) `throw new Error('some error');` simply goes to void. 
Usage can obviously be wrong, but muting error is :exploding_head:

**Comment by elhigu** [comment]
I suppose it gets muted because the promise which it should be rejecting is already resolved. I suppose that is just how promises work. If one tries to reject resolved promise it is just a no-operation?
