### ISSUE TITLE
Feature request: Async iterators

### ISSUE THREAD

**Issue by adrianhelvik** [knex/knex#3876]
I would love to be able to iterate over a large collection of items without loading everything in memory at once. I can do that with streams, but it can be a bit cumbersome. Async iterators otoh are exactly what I'd like.

This is especially important for migrations. We sometimes make changes that affect every row in a table and I fear this could cause memory issues in the future.

What do you think about setting `Symbol.asyncIterator` on the query builder?

```javascript
for await (const comment of knex('comments')) {
  await knex('comments')
    .where('id', comment.id)
    .update({ ... })
}
```

I can use stream-to-async-iterator, but it would be a great addition to the core API imo.

**Comment by elhigu** [comment]
I would hate to add additional APIs for accessing results for maintaining knex. Already current stream API implementation's functionality is questionable. 

Using that library for converting streams to async iterator sounds like a way to go and hopefully you can wrap that to a knex extension as a separate npm package.

Having a separate extension will also reduce knex's dependencies (this feature would probably be better to implement with stream wrapper anyways).

If knex's extension API is not suitable for implementing this I would be open to improve extension APIs to make also this kind of extending possible.

**Comment by adrianhelvik** [comment]
I did build an async iterator extension. I didn't manage to assign `Symbol.asyncIterator` to the iterator, so it is assigned to the query builder instance through `builder.asyncIterator()` instead. Not a big deal, and this works well for my use case. But it would be very nice to be able to do `for await (const x of knex('x')) {}`.

**Implementation**
```javascript
export default function knexAsyncIterator() {
  this[Symbol.asyncIterator] = () => {
    return new KnexAsyncIterator(this)
  }
  return this
}

class KnexAsyncIterator {
  constructor(query) {
    this.stream = query.stream()
    this.buffer = []

    this.stream.on('data', this.onData)
    this.stream.on('error', this.onError)
    this.stream.on('end', this.onEnd)
  }

  done = false

  onData = data => {
    this.pause()
    this.push({
      done: false,
      value: data,
    })
  }

  push = payload => {
    if (this.resolve) {
      this.resolve(payload)
      this.resolve = null
      this.reject = null
    } else {
      this.buffer.push(payload)
    }
  }

  onError = error => {
    this.finalCleanup()
    if (this.reject) {
      this.reject(error)
      this.reject = null
      this.resolve = null
    } else {
      throw error
    }
  }

  onEnd = () => {
    this.finalCleanup()
    this.push({
      done: true,
    })
  }

  pause = () => {
    this.stream.pause()
  }

  finalCleanup = () => {
    this.stream.off('data', this.onData)
    this.stream.off('error', this.onError)
    this.stream.off('end', this.onEnd)
    this.done = true
  }

  async next() {
    if (this.buffer.length) {
      return this.buffer.shift()
    }

    if (this.done) {
      return { done: true }
    }

    return new Promise((resolve, reject) => {
      this.resolve = resolve
      this.reject = reject
      this.stream.resume()
    })
  }
}
```

**Usage**
```javascript
for await (const user of knex('users').asyncIterator()) {
  console.log(user)
}
```

**Comment by hash-bang** [comment]
Nice one @adrianhelvik thats a very handy utility.

For anyone wondering how to add it to their project you need to apply the following somewhere:

```javascript
var knexBuilder = require('knex/lib/query/builder');
knexBuilder.extend('asyncIterator', knexAsyncIterator);
```

**Comment by adrianhelvik** [comment]
Thanks! I will try to get around to making an NPM package for it after my vacation.

**Comment by hash-bang** [comment]
I don't suppose its also possible to get a `eachAsync(row => ...)` function added also? Similar to the Mongoose [QueryCursor.eachAsync](https://mongoosejs.com/docs/api.html#querycursor_QueryCursor-eachAsync) function?

This is a little easier to use in functions where a full async / for of / generator pattern is a bit cumbersome.

**Comment by adrianhelvik** [comment]
Something like this should work. **Not tested.**

```
QueryBuilder.extend('eachAsync', async function (callback) {
  for await (const item of this.asyncIterator()) {
    await callback(item)
  }
})
```

**Comment by adrianhelvik** [comment]
Any more suggestions? Could build a "knextra" library. 😄

**Comment by kibertoad** [comment]
@adrianhelvik knex_utils is a thing :)

**Comment by hash-bang** [comment]
@adrianhelvik - well since you're asking the [Mongo equivalent](https://mongoosejs.com/docs/api.html#querycursor_QueryCursor-eachAsync) does support specifying the number of parallel threads to run at once as a second parameter... I do think this is going to be painful to write with generators but I'll admit my knowledge of them is rather limited.

@kibertoad - it would be nice to throw it into that library to keep everything in one place. I do rather like "knextra" better as a name though.

**Comment by aleclarson** [comment]
## This is now supported by default!

No mention of `for await` in the docs, but I discovered through the TypeScript definitions that the stream returned by `.stream` is in fact compatible with `for await`. 🎉 

```ts
for await (const comment of knex('comments').stream()) {
  console.log(comment)
}
```

**Comment by piranna** [comment]
> No mention of `for await` in the docs, but I discovered through the TypeScript definitions that the stream returned by `.stream` is in fact compatible with `for await`. tada

This is a side effect of the fact that now Node.js Stream objects implement the AsyncIterable protocol :-)
