### ISSUE TITLE
oracledb  stream clob check error!

### ISSUE THREAD

**Issue by hyz1840** [knex/knex#3877]
# Environment

Knex version:
oracle  2018:    oracledb 4.2
OS: windows

bug:     oracledb/index.js

readStream function

stream.iLob.type === oracledb.CLOB    error, because there are no iLob prop, type prop is in stream obj.
there is stream obj props image:

![image](https://user-images.githubusercontent.com/64118876/84251044-62f90e00-ab3f-11ea-8d23-80eb466ba6cb.png)

**Comment by kibertoad** [comment]
What is the knex version?

**Comment by hyz1840** [comment]
"knex": "^0.19.5",

**Comment by kibertoad** [comment]
@hyz1840 Should be fixed in 0.20.3+
