### ISSUE TITLE
Preserving execution async resource in events

### ISSUE THREAD

**Issue by amir-s** [knex/knex#3879]
# Environment

Knex version: 0.21.1 
Database + version: sqlite and mysql
OS: MacOS 10.15.5

# Bug
I'm experiencing a weird issue with knex and node's [`async_hooks`](https://nodejs.org/api/async_hooks.html). My usecase for this is to have a universal logger that adds contextual metadata to the logs. The context comes from the parent function that is executing the query and it is shared via the [`executionAsyncResource `](https://nodejs.org/api/async_hooks.html#async_hooks_async_hooks_executionasyncresource).
The parent function stores the context in its execution async resource, and the logger function reads from it.

However the event handlers, such as `knex.on('query', () => { })` do not have access to the parent resource. In fact their parent function is not even what I think should be.

This is a minimal example:

<details>

```
const fs = require('fs');
const util = require('util');
const knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: './mydb.sqlite',
  },
  useNullAsDefault: false,
});
const {
  createHook,
  executionAsyncResource,
  executionAsyncId,
  triggerAsyncId,
} = require('async_hooks');
function debug(...args) {
  fs.writeFileSync(1, `   ---   ${util.format(...args)}\n`, {
    flag: 'a',
  });
}
createHook({
  init(id, type, trig, res) {
    const r = executionAsyncResource();
    if (r['test']) {
      res['test'] = r['test'];
    }
    debug(trig, id, type, res['test']);
  },
}).enable();

knex.on('query', ({ sql }) => {
  console.log(
    'on query event',
    triggerAsyncId(),
    executionAsyncId(),
    executionAsyncResource()['test']
  );
  console.log(sql);
});

async function main() {
  console.log('main', triggerAsyncId(), executionAsyncId());

  executionAsyncResource()['test'] = 'test';

  console.log(await knex.select(knex.raw('1')));
}
main().catch(console.error);
```

</details>

I expect `executionAsyncResource()['test']` to be `"test"` in the event handler, but it's `undefined`.
The trigger async ID is also tracking back to the ID of `0` which explains why it doesn't have access to the resources created by `main` which has the ID of `1`.

I tried isolating this. I thought it's `EventEmitter` that does this and made a simple snippet to test it out, it was working properly. I was wondering if anyone here knows the knex code better and can help me find the issue.

Thank you guys!

**Comment by harish2704** [comment]
This issue is solved in latest ( v15 ) Nodejs ( you can verify this by running any nighly build of Nodejs ).
The discussion can be seen here https://github.com/nodejs/node/pull/33189 and https://github.com/nodejs/node/pull/33560

**Comment by amir-s** [comment]
I tried it again on node v15 and I can confirm it works properly.
Thank you for providing the links to the discussions as well. Very helpful 🥂
