### ISSUE TITLE
Docs for specific version?

### ISSUE THREAD

**Issue by abcd-ca** [knex/knex#3880]
Is there a way to view the docs for a particular version? I'm thinking about when I have to edit my project in a year and don't want to upgrade, where am I going to find the docs? I might make a PDF now just in case, if I can.

**Comment by elhigu** [comment]
Right now you can locally generate any version on documentation by fetching correct tag from documentation repo and building it. Though having an archive of old documentation versions would be nice.

**Comment by abcd-ca** [comment]
Closed but would be cool to put that on the roadmap

**Comment by elhigu** [comment]
PRs are welcome for a script that generates some kind of frozen version of docs to a separate path. Then I could run that script for every tag and publish them (some older versions probably doesn't generate exactly the same way). 

I would do it myself, but currently my open source hours are pretty limited.

**Comment by jjdonov** [comment]
Are there any instructions on how to build the docs?

**Comment by elhigu** [comment]
In the documentation repo knex/documentation there are scripts to do that.
