### ISSUE TITLE
Default float precision on postgres

### ISSUE THREAD

**Issue by Toub** [knex/knex#3884]
# Environment

Knex version: 0.21.1
Database + version: postgres 10
OS: docker/linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

The [documentation](https://knexjs.org/#Schema-float) says that default precision for floats is 8.

So on postgres, I would expect to have `float8` type created.

However, if precision is not set, `float4` type is created.

2. Error message

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```js
exports.up = async function(knex) {
  await knex.schema.createTable("my_table", table => {
    table.increments();
    table.float("some_8_precision_float").nullable();
  });
```

**Comment by Toub** [comment]
Related to https://github.com/knex/knex/issues/2945

**Comment by elhigu** [comment]
Yep, its a bad documentation + defaults. Float is 32bit float by default, unless DB supports those scale / precicion setting. `.double` is double precicion float column.

**Comment by elhigu** [comment]
closing as there is already issue about it in documentation repo + duplicate to already closed issue https://github.com/knex/documentation/pull/250
