### ISSUE TITLE
Add support for checking existence of multiple columns at the same time (schema)

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#3887]
# Feature discussion / request

Add way to check existence of multiple columns at once.

1. Explain what is your use case

I'm working on a headless CMS with a dynamic database schema ([Directus](https://github.com/directus/directus)). This means that I often have to check if columns exist before querying them. However, the only way to do that currently is by looping over the fields, and running `hasColumn` for each of them. This is a bit of a performance downside, as it has to run a query for each column.

2. Explain what kind of feature would support this

Seeing Knex doesn't abstract database errors (like columns that don't exist) when querying them, relying on `hasColumn` is the only way to accurately check if columns exist in a table to prevent errors like that. However, seeing `hasColumn` only works on a single column, this function has to be called multiple times in parallel for this type of functionality to work.

3. Give some API proposal, how the feature should work

Next to `hasColumn`, we can add a `hasColumns` function that accepts an array as second parameter: `hasColumns(tableName, columns)` `hasColumns('articles', ['title', 'author'])`. 

_Alternatively_, we could extend the existing `hasColumn` to support an array for it's second parameter. 

---

In the source code, most dialects already seem to fetch all columns to then check if one of them matches the given parameter. It should be relatively trivial to duplicate `hasColumn` in those dialects to support this feature. I'll happily provide a PR if you accept this feature.

**Comment by elhigu** [comment]
For this case I think you can use https://knexjs.org/#Builder-columnInfo which should be able to return info about all columns in the table among some additional information. 

Though checking existing columns again and again even this way gets a bit slow when it is done all the time so you probably want to cache that information (and invalidate the cache when schema is changing).
