### ISSUE TITLE
OrderByRaw binding values

### ISSUE THREAD

**Issue by AlanHilal** [knex/knex#3888]
# Environment

Knex version: 0.15.2
Database + version: PostgreSQL 
OS: Mac os

# Bug
I am trying to bind direction to orderByRaw like this: orderByRaw('columnName ? NULLS LAST', [direction]).
The value of direction variable is either 'asc' or 'desc'
The binding is not working and shows a syntax error.

**Comment by elhigu** [comment]
Cannot reproduce. Everything is generated as expected:

https://runkit.com/embed/lk4qiuh41dvw

**Comment by AlanHilal** [comment]
I still get this error when I execute the query:
order by columnName $2 NULLS LAST - syntax error at or near "$2"

**Comment by elhigu** [comment]
I suppose that postgresql doesn't support value bindings in that part of query. It has nothing to do with knex.

**Comment by AlanHilal** [comment]
I wrote the same query with string interpolation and it worked. knex value bindings add single quotation around the value, beacues the values asc and desc are sql keywords, postgresql gives an error.
https://runkit.com/alandzday/5ee9f1ed2357f6001a3b562d

**Comment by elhigu** [comment]
Actually knex does not add single quotes (.toString() doesn't tell you the truth about how knex sends queries to the DB), but it sends values as parametrized query with bindings, but yeah that is not the only place where value bindings are not supported.  There is also places, where string literals must be used, but parameter bound strings doesn't work.
