### ISSUE TITLE
Schema building: retrieving indexes

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#3889]
# Feature discussion / request

Knex has a bunch of methods aimed at providing an interface to build out a schema in any of the supported environments (MySQL / PostgreSQL / SQLite / etc). This includes creating new indexes. However, Knex does not currently offer a way to retrieve some of this schema information, including existing indexes.

1. Explain what is your use case
In my exact case, I need to be able to retrieve what the primary key is of a given table. However, this can and probably should be seen as a bigger use case of retrieving all indexes.

2. Explain what kind of feature would support this
By being able to read more existing schema information next to setting it, it would allow users to use Knex for more in-depth applications that work with dynamic database schemas that can be edited at will. It would basically turn Knex into a core engine that can be used to create things like PHPMyAdmin or Sequel Pro, but in JS.

3. Give some API proposal, how the feature should work
We could extend `columnInfo` with information on indexes, we could extend the existing methods for schema building with a way to retrieve some of that information, or provide a whole new interface for reading schema information.

**Comment by elhigu** [comment]
Needs quite a more investigation how this can be implemented with different databases + proper API design. Though I would rather have some separate knex-schema inspector package (I would actually rather have also all migration APIs separated from knex for easier maintenance and since those are breaking knex's basic design principles of creating just single query per builder).

**Comment by rijkvanzanten** [comment]
That's sounds like a great idea. What would be a good place to get such a conversation / design spec started? As I'm planning on using something like that quite extensively starting right away, I'm down to pick that up! I am a little new to the Knex ecosystem though, so I would need some help coming up with a good API design. I'm assuming we can go the Bookshelf route where you can initialize this package using an instance of Knex to power the queries, but other than that, I don't really know where to start..

Would you be willing to help out plan an ideal API for a stand-alone package like this @elhigu?

**Comment by elhigu** [comment]
Here is good place to draft plans and get comments to the ideas.  Sure I will comment if I have any thoughts / ideas about it, but your approach sounds good.

**Comment by kibertoad** [comment]
@rijkvanzanten Personally I'm open to create it as a separate repo under the Knex org umbrella if that works for you.

**Comment by rijkvanzanten** [comment]
@kibertoad Absolutely! I just figured as it's something I would have to build for this project anyway, I might as well try turning it into something that the whole community can enjoy 🙂 

I suppose the rough next steps to get this rolling would be to extract all the Schemabuilder stuff into a separate installable package under a new repo in the Knex org, and start brainstorming on how we can extend the existing / add new methods to support reading as well as writing

**Comment by elhigu** [comment]
I don't think it is necessary to move schema builder there right now. Just having separate knex-schema-inspector should be fine.

**Comment by rijkvanzanten** [comment]
Based on your previous comment I figured it could be a similar effort:

> I would actually rather have also all migration APIs separated from knex for easier maintenance and since those are breaking knex's basic design principles of creating just single query per builder

But it's probably too massive of an undertaking to migrate the userbase from a single package to a split approach like that like that

**Comment by kibertoad** [comment]
https://github.com/knex/knex-schema-inspector

Personally I wouldn't mind if it's written in TypeScript from day one, but whatever works for you :)

**Comment by rijkvanzanten** [comment]
Sweet! Thanks 🙂 

I primarily work in TypeScript these days so that works for me 👍

**Comment by kibertoad** [comment]
@rijkvanzanten I'll add CI pipeline to the repo later this week.

**Comment by rijkvanzanten** [comment]
Closing this feature request in favor of a new project:

https://github.com/knex/knex-schema-inspector
