### ISSUE TITLE
Tedious deprecation warning

### ISSUE THREAD

**Issue by david1602** [knex/knex#3891]
# Environment

Knex version:  0.21.1
Database + version: MSSQL
OS: Ubuntu 18.04.

@smorey2 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Not necessarily a bug, but there's a deprecation warning in the MSSQL driver. Since the driver for knex is a copypasta from the tedious mssql driver, I am not sure if this error actually occurs in the mssql dependency or in the knex driver code.

2. Error message

```
Mon, 22 Jun 2020 13:56:10 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

The test code can very simply be dumbed down to the following, assuming we have a database configuration for an MSSQL connection in the `config` object referenced, and assuming a table `test` existing in the target db.

```js
async function() {
    const knex = require('knex');
    const db = knex(config);

    const rows = await db('test');

    return rows;
}

```

Upon the first query, the warning listed in 2 will be displayed.

**Comment by elhigu** [comment]
Which node-mssql driver version are you using? Your error message is showing that it is indeed coming from dependency, not from knex.

**Comment by elhigu** [comment]
Your reproduction case is not showing the used configuration. It is important in this case (and usually in other cases too)...

**Comment by david1602** [comment]
@elhigu sorry, the config is as simple as it can be.

```json
{
    "database": {
        "client": "mssql",
        "connection": {
            "host": "db",
            "user": "sa",
            "password": "somepassword",
            "database": "somedatabase"
        }
    }
}
```

The database object of that is thje config. I am using `mssql` (not node-mssql, though we might mean the same thing) at 6.2.0

**Comment by elhigu** [comment]
Right driver package name is actually just `mssql`. I suppose knex might set `enableArithAbort` implicitly to driver configuration. Looks like we might need to lock more tightly with knex which driver major versions are supported with each release to prevent need to add compatibility code for multiple differently behaving driver versions.

**Comment by piobrien** [comment]
You can enable it like this:

``` javascript
connection: {
            host: < some hostname >,
            user: < some username >,
            password: < some pasword >,
            database: '< Database >',
            options: {
                enableArithAbort: true,
              }
        }
```

**Comment by david1602** [comment]
@piobrien I have tried that, that doesn't work for me. I have tried updating both mssql and knex, nad that doesn't do anything for me.

**Comment by piobrien** [comment]
@david1602 That is odd, my snippet was from a working deployment with the latest versions of Knex and mssql.

My Knexfile has this and doesn't produce the depreciation message:

``` javascript
module.exports = {

development: {
        client: 'mssql',
        connection: {
            host: 'some hostname',
            user: 'service account',
            password: 'service account password',
            database: 'TestDB',
            options: {
                encrypt: true,
                enableArithAbort: true,
                port: 1433
              }
        }
    }
};
```

**Comment by houldsg** [comment]
@david1602 If you are using a connection string instead of object, tedious won't parse it properly (happened to me)
https://github.com/tediousjs/node-mssql/issues/995

**Comment by david1602** [comment]
That appears to be the issue. Ugh. I guess I'll just live with the warning for now, since it's easier to deal with that than not being able to use a single environment variable.
