### ISSUE TITLE
calling createTable() from inside createTable() callback

### ISSUE THREAD

**Issue by msklvsk** [knex/knex#3902]
# Environment

Knex version: 0.21.1
Database + version: —
OS: macOS 10.15.5
# Bug

1. I’m trying to create an SQL schema from JSON and the algo involves calling `schema.createTable()` from the `schema.createTable()` callback. Naively I thought this should work, but it doesn’t, the nested call gets ignored:
1. –
1.
```typescript
import * as Knex from 'knex'
let knex = Knex({ client: 'pg' })
let schema = knex.schema
schema.createTable('foo', table => {
  schema.createTable('bar', table => {
    table.integer('field')
  })
})
console.log(schema.toString())  // `create table "foo" ()`
```
Is this expected?

**Comment by elhigu** [comment]
You should not call create table inside createTable callback.
