### ISSUE TITLE
enum with useNative is not being destroyed with dropTableIfExists()

### ISSUE THREAD

**Issue by boojum** [knex/knex#3903]
# Environment

Knex version:
Database + version: Postgres 12.3 / Knex 0.21.1
OS: Linux

# Bug

Rolling back a table which uses enum with `useNative: true` does not remove the enum. Upon running migration straight after the rollback (without altering any tables) I get:

`error: create type "role_type" as enum ('arch', 'sup', 'dir', 'pm', 'root') - type "role_type" already exists`

The example migration:

```
exports.up = async knex => {
  return await knex.schema.createTable('members', tbl => {
    tbl.increments('id')
    tbl.uuid('user_id').references('id').inTable('users')
    tbl.uuid('project_id').references('id').inTable('projects')
    tbl.enum('role', ['arch', 'sup', 'dir', 'pm', 'root'], {
      useNative: true,
      enumName: 'role_type',
    })
  })
}

exports.down = async knex => {
  return await knex.schema.dropTableIfExists('members')
}
```
It might be related to bug #3657 but please note that I do not alter the migrations in any way. This is truly annoying during testing, if one have something like:

```
beforeEach(async () => {
  await knex.migrate.latest()
  await knex.seed.run()
})

afterEach(async () => {
  await knex.migrate.rollback()
})
```
With this bug the test setup like the one above will always fail.

**Comment by elhigu** [comment]
Knex does not inspect database schema when it is dropping tables etc. I don't know if that kind of functionality "drop table XXX and all related types that are used only by this table" is possible to implement easily with SQL.

In down script after dropping table you need to explicitly also drop the type that was created while table was created. There might be also some foreign keys or constraints etc. left behind 🤔 

Closing as this seems to work as expected (this kind of issue is also happening when you try to update native enum values).
