### ISSUE TITLE
select UTC datetime value will be UTC two time 

### ISSUE THREAD

**Issue by Marcotsept** [knex/knex#3904]
# Environment

Knex version: 0.20.11
Database: postgres v12.3
OS: Mac

# Bug
I'm local time is gmt+8
I have saved the value is UTC Datetime but when I select that value will be UTC again that means the UTC value reduce 8 hrs again

**Comment by elhigu** [comment]
Not knex issue. Postgresql returns times as per your timezone setting of database session / connection. You may ask help about this from stackoverflow (or search answer there I know that even I have answered various questions about this there).

Closing as this is not a knex bug.
