### ISSUE TITLE
I don't understand why .update not work

### ISSUE THREAD

**Issue by IProudNoob** [knex/knex#3905]
Knex version: 0.21.1
Database + version: sqlite3 4.2.0
OS: Win 10 Pro
Electron: 8.1.1

My small test:
```
var knexCleaner = require('knex-cleaner');

var knex = require("knex")({
    client: "sqlite3",
    connection: {
        filename: path.join(__dirname, 'data.db')
    },
    useNullAsDefault: true
});

knex.schema
    .createTable('messages', table => {
        table.increments('id').unique().primary();
        table.string('from');
        table.text('msg');
        table.timestamp('created_at').defaultTo(knex.fn.now());
    })

 knex('messages').insert({ from: 'Bob', "msg": "Hello, World!" })
```
But when I do update:

```
knex('messages')
    .update({ "msg": "Guide to the Galaxy" })
    .where({ "id": 1 })
```
It's not work.
What am I doing wrong?
THX!!!

**Comment by elhigu** [comment]
You are not executing any queries. You are only building them, but nothing is sent to DB. 

Closing as this issue is clearly about knex usage and has nothing to do with development.

**Comment by IProudNoob** [comment]
When I create:
` knex('messages').insert({ from: 'Bob', "msg": "Hello, World!" })`
I see in data.db save 

```
# | id |  from | msg   | created_at
1 | 1  | Bob    | Hi!!!!! | 2020-06-30 11:37:08
```
I think it's saved data
