### ISSUE TITLE
How create corrected update column?

### ISSUE THREAD

**Issue by IProudNoob** [knex/knex#3906]
[My ask: ](https://github.com/knex/knex/issues/3905)
When I create:
knex('messages').insert({ from: 'Bob', "msg": "Hello, World!" })
I see in data.db save

| id |  from | msg   | created_at
| 1  | Bob    | Hi!!!!! | 2020-06-30 11:37:08

I think it's saved data

**Comment by elhigu** [comment]
Please follow knex issue tracker's rules. Issue template says that this is not place for knex usage questions.

**Comment by IProudNoob** [comment]
Ok)
THX!
