### ISSUE TITLE
Allow config json for migrations

### ISSUE THREAD

**Issue by MimoMoreno** [knex/knex#3907]
# Environment

Knex version: `0.21.1`
Database + version: postgres 9.6.11
OS: WSL (Windows Subsystem for Linux)

# Feature discussion / request

1. Explain what is your use case
I've just installed [node-config](https://github.com/lorenwest/node-config) in my project, and I wanted to add the db configuration in the files `config/default.js`, `config/production.js` and `config/test.js` as their documentation indicates. Using the configuration from these files works for the connection to the db of the server, but not for the migrations, which still use the `knexfile`.

Steps I followed:
a. removed the `knexfile.js`
b. added the configuration in `config/XXX.js` (example):
```
import dotenv from 'dotenv'
dotenv.config()

module.exports = {
  environment: 'development',
  db: {
    client: 'postgres',
    connection: {
      host: 'localhost',
      user: 'user',
      password: 'psw',
      database: 'db-name',
      port: 5432,
    },
  },
}
```

c. changed the import of the config file passed to knex from:
```
import config from '../../knexfile.js'
import knexBuilder from 'knex'
const knex = knexBuilder(config[process.env.NODE_ENV || 'development'])

export knex
```
to:
```
import config from 'config'
import knexBuilder from 'knex'
const knex = knexBuilder(config.get('db'))

export knex
```

d. tried to run `knex --esm migrate:latest [--env test]` but had the following error:
`Error: No configuration file found and no commandline connection parameters passed`

As indicated in your [docs](http://knexjs.org/#Migrations-CLI), migrations always use the `knexfile`, so there's no way I can export db configuration to node-config file. As I understand that for migrations knex reads automatically the `knexfile`, but for db connections reads the configuration sent to the `knex()` function, is this ok? 

2. Explain what kind of feature would support this
Receiving the config json of the db for migrations.

3. Give some API proposal, how the feature should work
It would be great if there was a way to call the `knex()` function for migrations and pass the config json to it.

**Comment by elhigu** [comment]
Create a knexfile.js that reads configuration from node-config. Something like: 

```
const config = require('config');
const dbConfig = config.get('dbConfig');
module.exports = dbConfig;
```
