### ISSUE TITLE
Trying to run migrations when using Node v14.5.0 causes "KnexTimeoutError"

### ISSUE THREAD

**Issue by fdjones** [knex/knex#3912]
# Environment
Node: 14.5.0
npm: 6.14.5

Knex version: 0.21.1
Database + version: PostgresQL 12.3
OSX: Catalina

# Bug

When attempting to run migrations, the following error occurs:

```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/Users/me/Code/project/node_modules/knex/lib/client.js:347:26)
    at async Promise.all (index 1)
```

When I revert my Node version to 12.18.2 the migrations run fine, so the issue is running the migrations while on Node 14.5.0.

**Comment by ShawnStewart** [comment]
I'm running into this same issue with [my docker-compose setup](https://github.com/ShawnStewart/docker-node-tutorial).

## Environment
Node: 14.5.0
Knex: 0.21.1
Node-postgres (pg): 8.2.1

## Issue
Attempting to run migrations or a simple query inside of my node container results in the following error:

`npx knex migrate:latest` or `await db.raw('select 1+1 as result');`

```bash
Using environment: development
Error: connect ECONNREFUSED 198.105.254.64:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

Reverting to Node 12.18.2 does not resolve the issue for me and I'm still unable to even run migrations.

I tried reverting Node-postgres (pg) per [these](https://github.com/brianc/node-postgres/issues/2223) [issues](https://github.com/knex/knex/issues/3831), but still no luck.

Any help is greatly appreciated!

**Comment by fdjones** [comment]
@ShawnStewart Are you still seeing the same error when you try to run migrations after you revert to Node 12.18.2 or is it a different error? I had an issue where I installed the packages using Node 14.xx which caused a load of issues after I reverted and the only way to fix it was to nuke node_modules and re-install while using Node 12.xx.

**Comment by ShawnStewart** [comment]
@fdjones Sorry, I pasted the wrong error in my original comment - fixed it now. I'm getting the exact same error as you. And since I'm running in docker, I can't do a rebuild and a fresh install of dependencies is done.

**Comment by ShawnStewart** [comment]
@fdjones Just tested outside of docker. After reverting to Node 12.18.2 and fresh installing dependencies, still getting the same error. Are you connecting to Postgres running locally?

**Comment by fdjones** [comment]
Hmm, that's odd as reverting to Node 12 fixed the issue for me. Yes I'm running Postgres locally..

**Comment by rbliss** [comment]
Experienced the same issue. Fixed it by upgrading both knex and pg to latest instead of downgrading to Node 12. YMMV

**Comment by ShawnStewart** [comment]
Confirmed upgrading resolved the issue for me as well. It looks like [pg 8.3.0](https://github.com/brianc/node-postgres/pull/2216) fixed the root cause.

@rbliss Thanks for the heads up!

**Comment by gates17** [comment]
having the same issue under wsl. tried with pg 8.3 and knex 0.21.1 switched to mysql2 and throws same error.
tried with node12 node 14.5 and 14.7
any insights?

**Comment by fdjones** [comment]
@gates17 did you try dropping down to node 12, deleting node_modules and then re-installing your dependencies?

**Comment by gates17** [comment]
as i said before tried with the node versions quoted below.
i did however manage to run my current configurations under ubuntu20.04 vmware with mysql2. but i still get the pool connection error on 1st connection try which is awkward.
still i dont remember having made any installation that would mess up the pooling on both dbs under windows or wsl.

> having the same issue under wsl. tried with pg 8.3 and knex 0.21.1 switched to mysql2 and throws same error.
> tried with node12 node 14.5 and 14.7
> any insights?

**Comment by almeidaalex** [comment]
> Confirmed upgrading resolved the issue for me as well. It looks like [pg 8.3.0](https://github.com/brianc/node-postgres/pull/2216) fixed the root cause.
> 
> @rbliss Thanks for the heads up!



> Confirmed upgrading resolved the issue for me as well. It looks like [pg 8.3.0](https://github.com/brianc/node-postgres/pull/2216) fixed the root cause.
> 
> @rbliss Thanks for the heads up!

Thank you a lot! I don't have too much experience with node environment (I'm reading a book that uses node examples). I've just upgraded pg package to 8.4 and the error stopped.
