### ISSUE TITLE
Limit is hard coded when it has changed since oracle 12.2

### ISSUE THREAD

**Issue by drew-royster** [knex/knex#3914]
https://github.com/knex/knex/blob/e37aeaa31c8ef9c1b07d2e4d3ec6607e557d800d/lib/dialects/oracle/utils.js#L3

As of their 12.2 release they now support long identifiers up to 128 bytes.

https://docs.oracle.com/en/database/oracle/oracle-database/12.2/newft/new-features.html#GUID-ACC0E96C-8D2D-468F-92E0-2013C7F13455

The tricky part could be that depending on the language a character may be multiple bytes.

https://docs.oracle.com/cd/E11882_01/server.112/e10729/ch2charset.htm#NLSPG171

Thanks!

**Comment by elhigu** [comment]
Changing this will break support for older oracle databases. For pg and mysql there has been used version configuration attribute for allowing some compatibility for older databases. 

Is there a particular reason why this should be changed now?

**Comment by drew-royster** [comment]
We had been having problems using sha'd Oracle object names and bumping up that limit fixed our issues. Would you be alright doing version compatibility with Oracle as well? It's been 3 years since 12.2 was released and we would love to take advantage of the new limit.

**Comment by kibertoad** [comment]
@drew-royster Maybe we can make that value parametrized instead?

**Comment by drew-royster** [comment]
@kibertoad Pass that limit into the function? Or how would I go about this?

**Comment by elhigu** [comment]
I would rather have this being configured with passing oracle version number in config. 

I would like to avoid arbitrary dialect specific switches (I'm afraid that those stack up and after few years wee have 100 different limits and knobs whose different combinations won't be tested well). 

Though I don't have very strong opinion on this. So whatever is fine for me.

**Comment by Kytech** [comment]
@elhigu The original author of this issue is no longer working at our organization. I will be picking up work on this issue going forward in a new PR. I'll plan to implement an oracle version config option and I'll write a test case for the change. If there were any other items besides those two that were preventing a fix from being accepted, let me know and I'll work to address those as well.

**Comment by kibertoad** [comment]
@drew-royster does it work now?

**Comment by drew-royster** [comment]
no i closed, because I saw the other issue and i'm not actively using knex anymore

**Comment by Kytech** [comment]
> @drew-royster does it work now?

@kibertoad My PR that references this issue has a fix. It's just waiting for another review from project maintainers at the moment.

**Comment by drew-royster** [comment]
leaving this open so that maintainers can close when the PR is accepted.

**Comment by kibertoad** [comment]
Released in 3.1.0
