### ISSUE TITLE
[BUG] Knex - Already up to date

### ISSUE THREAD

**Issue by jablonskipj** [knex/knex#3918]
# Environment

Knex version: 0.16.3
Database + version: postgresql
OS: heroku

# Bug

I am struggling with a problem connected with the migrations in knex on the production environment (heroku). I have made some changes and created 8 new migrations to update the model. After creating new migrations I have reached 47 migration files. After uploading the changes to the Heroku I executed as usual `knex migrate:latest` and there was no effect. I have received the message Already up to date.

I have decided to take a look at the `knex_migrations` table to see if maybe something is wrong there. The result that I can see that the new migrations were not written into that database (please see the picture for reference.

<img width="717" alt="Zrzut ekranu 2020-07-9 o 22 45 12" src="https://user-images.githubusercontent.com/12045510/87133390-88d91600-c297-11ea-9f53-237fb37a2a54.png">

When we take a look at the migrations it looks like this:

<img width="358" alt="Zrzut ekranu 2020-07-9 o 22 45 44" src="https://user-images.githubusercontent.com/12045510/87133434-98585f00-c297-11ea-8b4d-1091e47b785c.png">

Clearly we can see that knex was able to run "20200216191040_receiver_company.js" as lat one.

When I take a look at the knex_migrations_lock table the only entry that is existing over there looks like this:

<img width="151" alt="Zrzut ekranu 2020-07-9 o 22 49 37" src="https://user-images.githubusercontent.com/12045510/87133454-a0b09a00-c297-11ea-8f0a-51c6511582be.png">

**Comment by elhigu** [comment]
Maybe your code has not updated until heroku or you have forgot to git add those migration files from local machine to heroku. Anyways sounds like an user error and not a knex bug. Can be reopened if reproduction is provided.

**Comment by elhigu** [comment]
You could check if knex starts failing when there is around 40-50 migration files though...

**Comment by jablonskipj** [comment]
@elhigu I have checked if the migration files are present on heroku and they are. Additionally, I have run those migrations locally and the were executed.

**Comment by elhigu** [comment]
Right... it works locally. Then the only reason I can think of is that files are not found from heroku. Or knex configuration is wrong and files are not found because of that. Though I suppose that in that case knex would give an error because of mussing migration files (unless db configuration is also so wrong that db looks empty.
