### ISSUE TITLE
`this.knex.client.logger` is not being passed into `getMergedConfig` in all cases

### ISSUE THREAD

**Issue by anandnimkar** [knex/knex#3919]
The second argument here needs to be `undefined`, not `this.knex.client.logger`

_Originally posted by @anandnimkar in https://github.com/knex/knex/pull/3839/review_comment/create_

**Comment by anandnimkar** [comment]
Fixed in PR https://github.com/knex/knex/pull/3920

**Comment by kibertoad** [comment]
Released in 0.21.3
