### ISSUE TITLE
knex_migrations and lock tableName are not part of wrapIdentifier

### ISSUE THREAD

**Issue by piyushchauhan2011** [knex/knex#3924]
@atiertant 

# Environment

Knex version: 0.21.1
Database + version: Oracle + 12.2.0.1
OS: Ubuntu (linux) in WSL2

# Bug

I wanted to remove quoted behavior provided by knex while table creation. After using the `wrapIdentifier`, it successfully worked for tables except the `knex_migrations` and `knex_migrations_lock`. To my understanding, tables for keeping migrations should respect the `wrapIdentifier` function logic.

This can be seen by putting `console.log` in `wrapIdentifier` method as it doesn't output `knex_migrations` or `knex_migrations_lock` table names.

```js
wrapIdentifier: (value, origImpl, queryContext) => {
    console.log(value);
    return value;
},
```

# Feature discussion / request

I'm looking for consistency across table names in database. Though it's not high priority but would be nice to have table names consistent

### Docker Compose file for Oracle
```sh
version: '3.3'

services:
  database:
    restart: always
    environment:
      ORACLE_PWD: <pwd>
      DB_SID: <sid>
    image: store/oracle/database-enterprise:12.2.0.1
    volumes:
      - mydb:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
volumes:
  mydb:
```

Thank You 😃

**Comment by elhigu** [comment]
IIRC it was intentional function that it is not used for knex's internal tables.

**Comment by piyushchauhan2011** [comment]
Hmm, if it was intentional then I guess it's okay to leave internal table names quoted, I'll close the issue 🥰

**Comment by elhigu** [comment]
These I think:
https://github.com/knex/knex/issues/2644
https://github.com/knex/knex/pull/2914

**Comment by piyushchauhan2011** [comment]
Thanks @elhigu 👌
