### ISSUE TITLE
knex 是否支持mysql8.0 版本？

### ISSUE THREAD

**Issue by junbao520** [knex/knex#3925]
![image](https://user-images.githubusercontent.com/20721833/87513406-48203900-c6ab-11ea-8d3d-4c4b4aaaf729.png)

**Comment by elhigu** [comment]
cannot reproduce.

**Comment by bytrix** [comment]
> cannot reproduce.

I have the same problem.

**Comment by bytrix** [comment]
using mysql2 as client.
