### ISSUE TITLE
Is knex Support mysql 8.0 version

### ISSUE THREAD

**Issue by junbao520** [knex/knex#3926]
thank you

**Comment by raijinsetsu** [comment]
Knex supports all versions of the database supported by the underlying MySQL driver.

MySQL 8.0.4 introduced a backwards incompatibility in the authentication protocol and the MySQL driver has not been updated to handle this situation: https://github.com/mysqljs/mysql/issues/1959

You will need to use MySQL 8.0.3 or EARLIER.

**Comment by kibertoad** [comment]
Knex by itself does, but there are certain compatibility issues on a driver level that knex can't do anything about, e. g. see the linked issue above.
