### ISSUE TITLE
Password Security

### ISSUE THREAD

**Issue by PickJBennett** [knex/knex#3928]
Hello, I'm interested in using this library, but I am concerned about the password field being exposed in plain text over JavaScript. How do you secure this so it's never delivered to the browser? Thank you!

**Comment by elhigu** [comment]
Closing as this is not related to knex development.    You can secure that password nor hash is never sent to browser for example by storing password hashes in a separate table and by accessing that table as little as possible. Mostly when checking if pw is correct or wheng changing it. Also not storing password at all is pretty guaranteed way.
