### ISSUE TITLE
knex failure on transactions

### ISSUE THREAD

**Issue by csnarain** [knex/knex#3940]
I'm using knex (0.21.1) on mssql client and the following query results in a failure. The failure is triggering the catch at the bottom and fails with message "undefined of rollback..."

return knex.transaction((t) => {
    return knex('customer')
      .transacting(t)
      .insert(customerObj)
      .returning('custId')
      .then((response) => {
        customerObj.orders.custId = response.toString();
        return knex('orders')
          .transacting(t)
          .insert(customerObj.orders)
          .returning('orderId');
      })
      .then(t.commit)
      .catch(() => {
        t.rollback;
      });
  });

**Comment by Naddiseo** [comment]
One possibility for the error is is that `rollback()` is a function, and in your example, it's not being called.
You could try `.catch(t.rollback)` directly (or `.catch((err) => { return t.rollback(err); }`)

(Also, you can use triple backticks \``` to wrap code to keep the formatting/indentation)

**Comment by csnarain** [comment]
@Naddiseo - My bad. Thanks. I wasn't trying to invoke rollback as a function. It works now.
