### ISSUE TITLE
knex insert json object to multiple tables

### ISSUE THREAD

**Issue by csnarain** [knex/knex#3942]
I have a json object with nested key/value properties that needs to be inserted to multiple tables based on the key name. It's not a straightforward insert as the output of one insert needs to be piped as input to the next insert. How do I do conditional inserts using knex to mssql? Here is the object that I'm trying to insert

```
{
    "activity": {
        "activityType": "Marketing",
        "activityDate": "2020-07-19",
        "activityStartTime": "2020-07-19 03:27:45.000",
        "activityEndTime": "2020-07-19 04:27:45.000",
        "activityUrl": "https://www.sdss.com",
        "isPublished": false,
        "activityDuration": 30,
        "eventId": "03361624-3964-4f2e-9ab0-34ea48027f09",
        "activityName": "Customer Delight"
    },
"marketing": {
        "Name": "sales booster",
        "meetingUrl": "http://www.zzz.com",
        "clientViewName": "sales boost",
        "linkOneName": "test1",
        "linkTwoName": "test2",
        "linkOneNameUrl": "www.gggg.com",
        "linkTwoNameUrl": "www.gggg.com",
        "participants": [
        {
            "email": "bbb@bbb.com"
        },
        {
            "email": "aaa@aaa.com"
        },
        {
            "email": "ccc@ccc.com"
        }
    ]
    }
}
```

In the above, the output of activity insert should be piped to marketing and the output of the same should be piped to participants. Since participants is a separate table, I can't just do a loop as it would involve many db calls. I'd like to club this all
and then do a single write. Do we have a better way to achieve this using knex?

**Comment by elhigu** [comment]
Closing as knex usage questions should go to gitter / stackoverflow.

You need to create a separate insert for each table and setup foreign keys correctly. Most probably you want to use objection.js for that which can insert nested data with correct foreign keys automatically if realation mappings has been set correctly for models.
