### ISSUE TITLE
Inconsistent camelCase use for datetime in schema

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#3944]
# Environment

Knex version: 0.21.2

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

The docs describe creating a `datetime` column by using `table.datetime()`: http://knexjs.org/#Schema-datetime

However, the TypeScript definition and tests seem to indicate it should be `table.dateTime()`:

https://github.com/knex/knex/blob/b59161f9944acf858b149a6c2901b14fcd4ba8aa/types/index.d.ts#L1560

https://github.com/knex/knex/blob/b59161f9944acf858b149a6c2901b14fcd4ba8aa/test/integration/builder/selects.js#L743

as a matter of fact, I was only able to find a single reference that seems to use `datetime` in schema building:

https://github.com/knex/knex/blob/b59161f9944acf858b149a6c2901b14fcd4ba8aa/test/unit/schema/mysql.js#L832

Are the docs wrong, or is there something bigger here I'm missing? (Also, how does that last test pass when using `datetime()` instead of `dateTime()`? Are both valid? @lorefnon

**Comment by lorefnon** [comment]
The same method is [aliased](https://github.com/knex/knex/blob/e37aeaa31c8ef9c1b07d2e4d3ec6607e557d800d/lib/schema/tablebuilder.js#L149) as datetime and dateTime. 

The TS defs should mention both - but currently doesn't.

**Comment by rijkvanzanten** [comment]
Ahh I see. Thanks for the heads up @lorefnon 👍 

Shall I open a PR to extend the `index.d.ts` file? 
Do we want to update the docs to mention these aliases somewhere consistent?

**Comment by lorefnon** [comment]
@rijkvanzanten Sure. That would be cool. The knex docs are maintained in [this repository](https://github.com/knex/documentation), and can be updated there.
