### ISSUE TITLE
Get connection session data

### ISSUE THREAD

**Issue by pazfelipe** [knex/knex#3945]
**Nowadays:**
My company has a software built in `delphi` that every time it connects to the oracle database, namely initializing the software, a procedure is called to save this connection's data. Some functions run inside this procedure to get info about user connected, origin ip, etc. 

**Problem:**
_We are migrating_ from `delphi` to web (`nodejs` + `vuejs`) and this procedure must skill keep running but I don't know how to get this information about knex connection data.

**Expected:**
Is there any way to obtain some information about session connection data when knex connects to the database?

**Comment by elhigu** [comment]
Check afterConnect knex configuration attribute and there you will be able to get oracledb connection where you can check everything that oracledb's APIs provides. Closing as this is not knex development related issue and not following issue guidelines.

**Comment by pazfelipe** [comment]
> Check afterConnect knex configuration attribute and there you will be able to get oracledb connection where you can check everything that oracledb's APIs provides. Closing as this is not knex development related issue and not following issue guidelines.

Could you tell me where I can find this attribute/config? I didn't find it on knex docs.

**Comment by elhigu** [comment]
Sorry. Remebered the name wrong. It is this one http://knexjs.org/#Installation-pooling-afterCreate
