### ISSUE TITLE
MSSQL: Cannot assign to read only property 'originalError'

### ISSUE THREAD

**Issue by hsynlms** [knex/knex#3948]
# Environment

Knex version: 0.21.2
Database + version: SQL Server 2017 Standard
OS: CentOS
Node.js version: v14.5.0

# Bug

Hundreds of select and insert Knex queries are executed in a cron job and sometimes below error is thrown. I think trying to change the original error object would not be a good idea. If this error happens, the connection closes and further select and insert queries won't be run even I put the whole transaction into a try-catch block.

**My workaround?**
I just removed below line from `/lib/dialects/mssql/transaction.js` file (line: 41). I am also wondering why this code line is placed in that file.

```js
if (error) err.originalError = error;
```

**Error message**
```plain
TypeError: Cannot assign to read only property 'originalError' of object 'TransactionError: Requests can only be made in the LoggedIn state, not the Final state'
  File "/var/www/my-project/node_modules/knex/lib/dialects/mssql/transaction.js", line 41, col 38, in null.<anonymous>
    if (error) err.originalError = error;
```

**Comment by elhigu** [comment]
Please add complete reproduction example and node version.  Sounds really weird if that is happening somehow random.

**Comment by hsynlms** [comment]
I faced this in our internal project of the company that I work at. I will try to give you the instructions or an example project to make it reproducable if I can.

Updated the issue with node.js version.

**Comment by hsynlms** [comment]
This issue is totally the same as https://github.com/knex/knex/issues/4128. According to [this PR](https://github.com/knex/knex/pull/4157), the case has been solved.

**Comment by kibertoad** [comment]
@hsynlms Can you confirm that 0.21.13 resolves the issue for you?

**Comment by hsynlms** [comment]
@kibertoad Seems so. No exception was thrown for last 12 hours.

Btw isnt it a workaround, is it?

**Comment by kibertoad** [comment]
@hsynlms Kinda. I could not reproduce the issue locally to try to pinpoint the root cause and resolve it in a more elegant way, so added the code to mitigate the issue. It is likely to have slight performance impact, but considering that this is nowhere near the hot path, I don't think it's going to be meaningful in any way.
