### ISSUE TITLE
Knex with Electron Reload

### ISSUE THREAD

**Issue by Lesnock** [knex/knex#3953]
I'm using Knex inside electron, with electron-reload to refresh the page when I change something.

When the electron window opens, the Knex queries work, but once the electron window is reloaded, knex returns this error:

```
Uncaught (in promise) KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection
```

What could it be?

**Comment by elhigu** [comment]
Closing as doesn't sound like a knex problem. I remember that somewhere there is discussion of something like that...
