### ISSUE TITLE
npm warnings: source-map-resolve 

### ISSUE THREAD

**Issue by tgiardina** [knex/knex#3954]
# Environment

Knex version: 0.21.2
Database + version: MySQL
OS: Ubuntu 18.04

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When installing knex through npm, I get the following warnings:
```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```
Following the given links, I see that knex needs to use a newer version of `source-map-resolve` package to avoid these warnings. 

This is obviously not very important, but it would be nice not to get those warnings.

**Comment by elhigu** [comment]
Will be fixed when deps are updated every now and then. Closing to prevent dangling open issues and since this is so minor issue. Please leave comment here, if after 6 months those warnings still exists and I will reopen this.
