### ISSUE TITLE
Schema creation in transaction doesn't roll back on errors

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#3957]
# Environment

Knex version: 0.21.2
Database + version: mySQL 8.0.19
OS: macOS

# Bug / Feature Request

I'm dynamically creating tables from my app, and would like to rely on transactions to ensure my database doesn't end up in a half-broken state when something fails during the creation of a new table. I expected the following to work (seeing it works amazingly well with "regular" non-schema creation methods):

```ts
await database.transaction(async trx => {  
  await trx.schema.createTable('example', table => {
    table.increments();
  });

  await trx.insert({ action: 'create', table: 'example' }).into('logs');
  //        ^^^^^^
});
```

If the second trx call fails, I expected the first to be rolled back. However, it seems like the table creation still persists. Is this a bug, or something that hasn't been implemented / isn't supposed to work?

**Comment by elhigu** [comment]
It is not supposed to work. MySQL database does not support transactions with schema changing DDL queries.  More info about mysql/mariadb implicit commits here https://stackoverflow.com/questions/54179669/transaction-issue-with-knexjs-typescript-and-mariadb/54180024#54180024
