### ISSUE TITLE
when I use oracledb to binding params, it will throw this error. but if I use raw to query, it will be normal.

### ISSUE THREAD

**Issue by caihaibin1991** [knex/knex#3959]
await knex.raw('select * from JKPT_TEST');

await knex.raw(`insert into "JKPT_TEST" ("CTXT") values (?)`, ['asdf']);
 

(node:20568) UnhandledPromiseRejectionWarning: Error: Unable to acquire a connection
    at Client_Oracledb.acquireConnection

**Comment by elhigu** [comment]
Closing as there is not enough info provided to resolve what is the problem or to even understand exactly what seems to be a problem here. Can be reopened if there seems to be a bug in knex related to this.
