### ISSUE TITLE
when I use oracledb to binding params, it will throw this error. but if I use raw to query, it will be normal.

### ISSUE THREAD

**Issue by caihaibin1991** [knex/knex#3960]
# Environment

Knex version:0.21.2
Database + version: oracle Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
OS:win 10

@ atiertant. 
this script can run
await knex.raw('select * from JKPT_TEST');
but this script will throw error "Unable to acquire a connection at Client_Oracledb.acquireConnection".
await knex.raw(insert into "JKPT_TEST" ("CTXT") values (?), ['asdf']);

and I need to use oracledb to insert clob large field into database. I do not know how to do.

**Comment by elhigu** [comment]
Please add complete runnable test code. Did you try running those queries in reverse order?

**Comment by caihaibin1991** [comment]
this is the table sql
CREATE TABLE "JKPT_TEST" (
  "CTXT" CLOB 
);
complete runnable test code need a database, I do not have a outside database.
you can add this table into a test database. and run 

```
await knex.raw(insert into "JKPT_TEST" ("CTXT") values (?), ['asdf']);
```

**Comment by elhigu** [comment]
do you have anything special in knex configuration? If that issue indeed is that easy to reproduce it might be that oracle dialect somehow gives wrong error for some other problem that is happening there.

**Comment by elhigu** [comment]
If anyone has time please try to reproduce this with knex's docker based oracle setup to have complete reproduction case.

**Comment by caihaibin1991** [comment]
I found the reason now, thank you @elhigu . 
I do the initiation of knex twice, but it is so weir, just only throw this problem. other actions like searching, executing sql, it is normal. only when I bind params to do something.
