### ISSUE TITLE
Wait for insert to complete

### ISSUE THREAD

**Issue by mike20007** [knex/knex#3961]
# Environment

Knex version: 0.19.5
Database + version: oracle 11g 11.2
OS: Linux

# Question:
Hello,

I insert a record to an oracle table using knex. On insert, oracle trigger calls a complex stored procedure. 
On error, the stored procedure returns errors to trigger and trigger to knex.

  return await knex("production_audit")
    .insert(auditRec)
    .then(count => {
      return count;
    })
    .catch(error => {
         console.log(error);
    })
    .finally(knex.release);

But, knex does not wait until the trigger finishes the stored procedure. 
Knex simply returns count as insert is successful.

How do I make it wait till the trigger finishes the stored procedure?

Thanks for your help!

**Comment by elhigu** [comment]
Closing as knex issue tracker is meant for bug / development. Not general SQL / knex usage questions. 

You need to figure out how would you do that waiting with plain SQL, then do the similar kind of thing with knex.

**Comment by mike20007** [comment]
Ok, Thanks!
