### ISSUE TITLE
withUserParams and userParams not listed in TypeScript definitions

### ISSUE THREAD

**Issue by Mossop** [knex/knex#3962]
# Environment

Knex version: 0.21.1
Database + version: Postgres 12
OS: macOS

If issue is about TypeScript definitions, tag @lorefnon.

The [userParams and withUserParams members](http://knexjs.org/#Installation-parametrization) of the knex object are not included in the TypeScript definitions.

At the very least having userParams defined as `any` would stop TypeScript complaining about it not be defined. It could be worth making withUserParams generic and returning a Knex with a new generic argument to specify the shape of userParams.

**Comment by kibertoad** [comment]
@Mossop Would you be open to sending a PR for this issue?

**Comment by Mossop** [comment]
I can do but it might take a couple of days to find the time. @kibertoad would you prefer just a generic solution (just make the userParams property `any`) or something involving an additional generic type on the Knex type?

**Comment by kibertoad** [comment]
@Mossop Record<string, any> would be my oreference

**Comment by kibertoad** [comment]
Released in 0.21.13

**Comment by danielo515** [comment]
With Knex 2.0.0 this is still a problem.
