### ISSUE TITLE
.update unintended change

### ISSUE THREAD

**Issue by Phantom-Wolf** [knex/knex#3965]
# Environment

Knex version: "knex": "^0.21.2"
Database + version: "pg": "^8.3.0"
OS: windows10

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do:

using postgresql. insert works as intended, puts array as text into database. my api call to get the JSON.parse(array text) brings me my array. however, when patching it using .update, it changes my array: [...] into an object: {...} in the database, which stalls my entire web app since my api requests are expecting an array response. I wasn't even specifically patching the array, I was patching a different property in the shared object, but since I assume it redoes everything in the object on .update, it changed my intended patch, but also oddly changed my array into an object. I also tested to make sure that it wasn't user error before sending this.

2. Error message

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by Phantom-Wolf** [comment]
so looking into it more, ".update" doesn't exactly change the array into an object, it just changes the [...] into {...} while the content remains in array format (a comma separated list) which breaks the any web app that tries to interact with that damaged array format. The change also prevents JSON.parse() from work and halts the entire pull until that code is removed.

**Comment by elhigu** [comment]
Please provide complete runnable minimal reproduction code if you think there is a bug in knex. There is more info about it in contributing.md. Closing until reproduction is provided.
