### ISSUE TITLE
OracleDb - Problem while using number on binding param

### ISSUE THREAD

**Issue by flpb** [knex/knex#3968]
Knex version: 0.21.2
Database + version: oracledb 5.0.0
OS: Linux
@atiertant.

# Bug

I was using knex v0.15.0 and  oracledb v2.3.0 - My resources were functional.
Then, recently I noticed a few things that I needed (pretty badly, as you can notice for the lack of updates since..) to update, and I did. So my problem began to appear.

There was no error log to be found... I only noticed this because my cluster workers kept dying after the update and the response were nowhere to be found.

You can try to reproduce by using a Database with a table called P_User with 3 columns. ID, Status and Name: as follows:
-- create table oracledb
```
CREATE TABLE P_USER 
(	"ID" NUMBER(19,0) CONSTRAINT "USER_ID_PK" NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
         CONSTRAINT "USER_ID_PK" PRIMARY KEY ("ID")
);
```
-- insert a few names
```
INSERT INTO P_USER (Id, Name) Values (1, 'Felipe');
INSERT INTO P_USER (Id, Name) Values (1, 'Adrian');
INSERT INTO P_USER (Id, Status, Name) Values (1, 0, 'Newton');
COMMIT;
```

// than you should try this
```
const knex = require('knex')({
  client: 'oracledb',
  connection: {
    host: DB_HOST,
    database: DB_NAME,
    user: DB_USER,
    password: DB_PASSWORD,
  },
  pool: {
    min: 0,
    max: 10,
    afterCreate(conn, done) {
      conn.execute('alter session SET NLS_COMP=LINGUISTIC');
      conn.execute('alter session SET NLS_SORT=BINARY_CI');
      done();
    },
  },
});

const tableName = 'P_User Q';  // 'SCHEMA.TABLE@DBLINK_HERE.DBLINK_NAME Q'
const query = knex.from(knex.raw(tableName)); // PS: I'm using this way because of some code that uses a dblink from another schema like the commented above, but the problem is not in the dblink but the query bellow
query.where('Q.STATUS', 1); // this is the problem
```

I realize that to surpress this problem I could use `.toString` on my values like this `query.where('Q.STATUS', '1');`

This is the solution I got. But i kept thinking.. Why this thing have changed?
So I can't do this kind of query with a number? It has to be a string? really or I'm missing something?

Thanks in advance. (sorry for poor english).

**Comment by elhigu** [comment]
What is the problem there:

```
const tableName = 'P_User Q';  // 'SCHEMA.TABLE@DBLINK_HERE.DBLINK_NAME Q'
const query = knex.from(knex.raw(tableName)); // PS: I'm using this way because of some code that uses a dblink from another schema like the commented above, but the problem is not in the dblink but the query bellow
query.where('Q.STATUS', 1); // this is the problem
```

you are not even executing that query... please add complete reproduction with also an error that you are experiencing.

**Comment by flpb** [comment]
@elhigu

Ok, you are right, the code should be this:

```
// aka model part
const searchForActiveUsers = () {
    const tableName = 'P_User Q';  // 'SCHEMA.TABLE@DBLINK_HERE.DBLINK_NAME Q'
    const query = knex.from(knex.raw(tableName)); // PS: I'm using this way because of some code that uses a dblink from another 
    schema like the commented above, but the problem is not in the dblink but the query bellow
    query.where('Q.STATUS', 1); // this is the problem
    return query;
}
```

```
// aka controller part
searchForActiveUsers().then(response => {
    console.log('fromServer: ', response); // doesn't do anything
}).catch(err => {
   console.log('error: ', err);
});

// or

try {
    const response = await searchForActiveUsers();
    console.log('fromServer: ', response); // doesn't do anything
} catch (err) {
    console.log('error: ', err); // doesn't do anything
}

```

I'm so sorry for not providing this before.. this is not the way that I call knex still.. I'll not bother you guys adding complexity over there.. But our controller part should pass to the model part an object containing Q.STATUS and the value 1 (int) from that part to the model part in an object and we spread the object and use it on the where clause..

```
// whereElements [ [ 'Q.STATUS', '=', 1 ] ]
whereElements.forEach((where) => {
    const operator = Array.isArray(where[2]) ? 'in' : where[1];
    query.where(where[0], operator, where[2]); // where[2].toString()
});

```
I can use `toString` on `where[2]` which is the value.. I just can't figure out why this stopped working.. Still can't use numbers on where clause..

**Comment by flpb** [comment]
The same applies with
```
inactivate() {
    return knex(tableName)
      .where('ID', '1') // I assumed it was on the where function
      .update('STATUS', 0); // this was the reason
  }
```

**Comment by elhigu** [comment]
Provide some single file reproduction code that anyone can run. Sounds like you are doing something wrong. It will help also for you with debugging if you can isolate the actual minimal code where that is happening.

**Comment by flpb** [comment]
HI @elhigu thank you for the support... it was an issue with my docker image.. we changed to a different one and it started working again.. thank you for all the help and time that you spend on this with me. :)
