### ISSUE TITLE
ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by nicolascalev** [knex/knex#3970]
# Environment

Knex version: 0.21.2
Database + version: oracledb 5.0.0
OS: Windows 10

Hi @atiertant , hope you are doing well.

# Bug

### 1. Expected behavior
While creating that query, the expected behavior would be an output like this

```
var knex = require('knex')({ client: 'oracledb' });
var select = 'name,username,email,password,confirmToken,idAdmin,lastSeenAt,createdAt,updatedAt';
console.log(knex.select(select).from('user').where({ name: 'nicolas' }).limit(10).toString());
```

```SQL
select "name,username,email,password,confirmToken,idAdmin,lastSeenAt,createdAt,updatedAt" from "user" where "name" = 'nicolas' and rownum <= 10
```
Instead, I'm getting an output like this (as you can see in the runkit example)
```SQL
select * from (select "name,username,email,password,confirmToken,idAdmin,lastSeenAt,createdAt,updatedAt" from "user" where "name" = 'nicolas') where rownum <= 10
```
This query is outputed like that, just when I add a where. Before that everything seems to work just fine. But I need the where clause of course.

It's probably my problem for not knowing more about the usage of knex, but I'd appreciate some other workaround.

### 2. Error message
```BASH
[Error: select * from (select "name,username,email,password,confirmToken,idAdmin,lastSeenAt,createdAt,updatedAt" from "user" where "name" = 'nicolas') where rownum <= 10 - ORA-00972: identifier is too long] {
  errorNum: 972,
  offset: 22
}
```

### 3. Runkit example
https://runkit.com/nicolascalev/5f2da084ac80d9001b6bfccf#

**Comment by KristjanTammekivi** [comment]
It should be select "name", "username" .... etc
If you split your select fields on a comma then it would work https://runkit.com/kristjantammekivi/5f2e9db0ccc834001a665c73

I don't know why it's wrapping everything in parenthesis and selecting from it though, I assume there's some sort of a oracledb reason for it

**Comment by nicolascalev** [comment]
@KristjanTammekivi 
Thanks man, I tried separating the names in an array and it worked, and yes, I wonder why that is happening.
I'm trying to build a REST api and Knex is going to help with that job a lot.

**Comment by elhigu** [comment]
There was some good oracle reason why the query is wrapped to subquery instead of having just a single query when using .limit(10)
