### ISSUE TITLE
Passing raw string to underlying driver

### ISSUE THREAD

**Issue by chandelabhishek** [knex/knex#3977]
# Environment

Knex version: 0.21.2
Database + version: postgres 11
OS: mac/ubuntu

# Feature discussion / request

> 1. Explain what is your use case:
   
 Requirement is to pass raw connection string without parsing to underlying driver. My use-case is specifically for postgres.

> 2. Explain what kind of feature would support this

Above feature will enable drivers to use raw connection strings, and In case of postgres it can support auto-failover as pg-native driver which is based on libpq supports it. To support autofailover libpq will need a connectionString in form of:
`postgres://<username>:<password>@<host1>,<host2>/<database>`. please check [connection strings supported by libpq](https://www.postgresql.org/docs/9.3/libpq-connect.html#LIBPQ-CONNSTRING)

> 3. Give some API proposal, how the feature should work

To support backward compatibility, we can introduce a new key inside connection object as `rawConnectionString`, which will be passed to the dialect as is, i.e. without converting it into an connection object.

p.s. will you accept a PR for this?

**Comment by elhigu** [comment]
Does this work https://node-postgres.com/features/connecting#connection-uri ?

```
const knex = require('knex')({
  client: 'pg', 
  connection: { 
    connectionString: "postgres://<username>:<password>@<host1>,<host2>/<database>"
  }
});
```

**Comment by chandelabhishek** [comment]
@elhigu `pg` always parses it, so I got confused. thanks, above works.
