### ISSUE TITLE
Update dtslint

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#3983]
There are a couple of errors thrown by dtslint when the latest version is used. We need to resolve them and bump the used dtslint version.

**Comment by kibertoad** [comment]
@lorefnon If you ever have some spare time, would be awesome if you could take a look.

**Comment by lorefnon** [comment]
@kibertoad I tried updating to dtslint 3.6.14 (latest) in master and running `npm run lint:types` does not show me any errors. Can you please confirm on the version that you used ?

**Comment by kibertoad** [comment]
@lorefnon Can you try creating PR for that? If it all just passes, all the better. Maybe I did something wrong.
