### ISSUE TITLE
What's the difference between .table() and .alterTable()?

### ISSUE THREAD

**Issue by tsongas** [knex/knex#3990]
I believe this migration works regardless of whether I use `.table()` or `.alterTable()` is there a difference?
```
exports.up = function (knex) {
  return knex.schema.alterTable('account', (table) => {
    table.timestamp('date_deleted');
  });
};
exports.down = function (knex) {
  return knex.schema.alterTable('account', (table) => {
    table.dropColumn('date_deleted');
  });
};
```

**Comment by tsongas** [comment]
I see `.table()` in the [documentation](http://knexjs.org/#Schema-table) but I don't see `.alterTable` described anywhere.

**Comment by elhigu** [comment]
they are aliases: https://github.com/knex/knex/blob/e37aeaa31c8ef9c1b07d2e4d3ec6607e557d800d/lib/schema/builder.js#L57 this issue should be moved to documentation repo or `.alterTable` could be deprecated to not have so many unnecessary aliases.

**Comment by tsongas** [comment]
Thanks for the clarification it's definitely weird that an alias is in the documentation but not the actual method.

**Comment by KristjanTammekivi** [comment]
> they are aliases:
> 
> https://github.com/knex/knex/blob/e37aeaa31c8ef9c1b07d2e4d3ec6607e557d800d/lib/schema/builder.js#L57
> 
> this issue should be moved to documentation repo or `.alterTable` could be deprecated to not have so many unnecessary aliases.

I'd prefer keeping alterTable if possible, makes it more explicit

**Comment by elhigu** [comment]
> I'd prefer keeping alterTable if possible, makes it more explicit

True and agreed +1

**Comment by OlivierCavadenti** [comment]
I add alterTable in the documentation here: https://github.com/knex/documentation/pull/352
This will be close where the documentation is merged.
