### ISSUE TITLE
Knex merging duplicate column names with no alias

### ISSUE THREAD

**Issue by amroczeK** [knex/knex#3993]
# Environment

Knex version: 0.21.2
Database + version: Oracle 11g / MySQL
OS: Centos 7

@atiertant @smorey2 @elhigu 

# Bug

Not really a bug, just need help with solution/work around for Knex merging duplicate column names with no alias in SELECT statement for data returned from Oracle database. Is there a way I can automatically append an alias, object keys which are the same in javascript get merged, ".options({ rowMode: 'array' })" doesn't work for Oracle database 11g.

Currently ingesting thousands of queries written by other developers for a different application, into a new presentation layer to generate charts etc.

### Issue:
Finding that a lot of the queries are using duplicate column names in the SELECT statement without an alias, which is fine when viewing the data in Oracle SQL Developer because it will append the duplicate column name with "_1, _2 .. etc" in the Query Results table.

But KNEX is merging those duplicate columns and the only way around this is to manually edit the SQL query to include an alias, which is not a viable solution when we have thousands of potential charts with this issue.

### Example:

SQL Query:
```
select
nat.AVG_CQI, nat.OLSM_RANK_1_PC, outliers.OLSM_RANK_1_PC
from
(select
AVG_CQI,
OLSM_RANK_1_PC
from msa.GC_OLSM_V_CQI@MNDB_PROD
) nat,
(
select alll.AVG_CQI,
...
```

Oracle SQL Developer Query Result:
| AVG_CQI  | OLSM_RANK_1_PC | OLSM_RANK_1_PC_1 |
| ------------- | ------------- | ------------- |
| 0.69  | 0  | 0  |
| 0.82  | 53  | 53  |
| 1.1  | 14  | 14  |
| 1.3  | 0  | 0  |

Result returned by KNEX:
```
[
{ AVG_CQI: 0.69, OLSM_RANK_1_PC: 0 },
{ AVG_CQI: 0.82, OLSM_RANK_1_PC: 53 },
{ AVG_CQI: 1.1, OLSM_RANK_1_PC: 14 },
{ AVG_CQI: 1.3, OLSM_RANK_1_PC: 0 }
]
```

The 2nd and 3rd column become merged into one, we need to retain the third column even though it's a duplicate column name, it's not feasible to go through hundreds of charts and manually add an alias.

Does anyone know a good solution? I am thinking about trying wrapIdentifier but not sure. I have tried ".options({ nestTables: true, rowMode: 'array' })", ".options({ rowMode: 'array' })" and the returned data is still the same, they don't work because the particular database this SQL is querying is OracleDB (old version).

Here is the Knex query:
```
knex
        .transaction(trx => {
          return trx
            .raw(modifiedSqlWithAliasDatetime || modifiedOrderedSql || sql)
            .timeout(60000);
        })
        .then(result => {
	 console.log(result)
          result = postProcessResults(result, format, datasource.databaseType);
          resolve(resultHandler(datasource.databaseType, result));
        })
        .catch(error => {
	 reject(error)
	});
```

**Comment by elhigu** [comment]
You should check if oracledb driver has a solution for this (from brief googling I did not find anything about that driver having rowMode option). There is nothing that knex can do for this. It is all about driver behavior and how it return the rows.

**Comment by amroczeK** [comment]
@elhigu 

I am trying to change the underlining function that Knex uses to return the data retrieved from oracledb driver as an array of objects.

I want to rename/append '_1', '_2' etc to the column metaData before Knex parses the response, changing it to an array of objects. I am struggling to find where this is done in the NPM package, can you please advise?

This is the result returned by fetchAsync on line 200 in knex/lib/dialects/oracledb/index.js:

NOTE: options.resultSet = false, therefore the query goes directly into line 188, connection

SQL query has a duplicate column name PMPDCPVOLDLSRB, therefore the array of objects merges the two:
`result: { metaData:
   [ { name: 'DATETIME' },
     { name: 'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)' },
     { name: 'PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLDRBTRANSPLMN0' } ],
  rows:
   [ { DATETIME: 2020-09-16T23:00:00.000Z,
       'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)': 91761993,
       PMPDCPVOLDLSRB: 12688,
       'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB': 91774691,
       PMPDCPVOLDLDRBTRANSPLMN0: 91820603 },
     { DATETIME: 2020-09-16T07:00:00.000Z,
       'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)': 75355836,`

**I want to achieve this:**
`result: { metaData:
   [ { name: 'DATETIME' },
     { name: 'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)' },
     { name: 'PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLSRB_1' },
     { name: 'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB' },
     { name: 'PMPDCPVOLDLDRBTRANSPLMN0' } ],
  rows:
   [ { DATETIME: 2020-09-16T23:00:00.000Z,
       'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)': 91761993,
       PMPDCPVOLDLSRB: 12688,
       PMPDCPVOLDLSRB_1: 12688,
       'PMPDCPVOLDLDRB+PMPDCPVOLDLSRB': 91774691,
       PMPDCPVOLDLDRBTRANSPLMN0: 91820603 },
     { DATETIME: 2020-09-16T07:00:00.000Z,
       'PMPDCPVOLDLDRB-NVL(PMFLEXPDCPVOLDLDRB,0)': 75355836,`

Any help and advice on where Knex is setting the key/values for rows object would be appreciated.

**Comment by cjbj** [comment]
@elhigu node-oracledb's query output can be changed to array format using [oracledb.outFormat](https://oracle.github.io/node-oracledb/doc/api.html#propdboutformat) - is that the same as rowMode you speak about?  Are you saying that Knex understands both object and array formats?

**Comment by elhigu** [comment]
AFAIK in most cases knex doesn't care if the result rows are arrays or objects.

**Comment by cjbj** [comment]
@elhigu thank you

**Comment by amroczeK** [comment]
> AFAIK in most cases knex doesn't care if the result rows are arrays or objects (knex does almost nothing to results returned from db).

Knex is hardcoding oracledb's output format as OBJECT.

```
const fetchAsync = promisify(function (sql, bindParams, options, cb) {
        options = options || {};
        options.outFormat =
          client.driver.OUT_FORMAT_OBJECT || client.driver.OBJECT;
        if (!options.outFormat) {
          throw new Error('not found oracledb.outFormat constants');
        }
.....
```

If I change options.outFormat to OUT_FORMAT_ARRAY, then will only return the result of rows and not the column names. I would have to create a pull request and add the ability to pass in options to set outFormat to either ARRAY or OBJECT and then change the way knex parses the data. I think it would be a fair bit of work.

**Comment by elhigu** [comment]
@amroczeK sometimes to get features one needs requires a fair bit of work. I would happily merge PR that enables allowing to set oracledb outFormat. 

Thought according to this http://oracle.github.io/node-oracledb/doc/api.html#queryoutputformats I don't know if it is possible with oracle to get array format like some other drivers has where results are like:

```
[ 
  [ [columnName1, value1], [columnName2, value2], [columnName3, value3], ... ], // row 1
  [ [columnName1, value1], [columnName2, value2], [columnName3, value3], ... ], // row 2
]
```

**Comment by cjbj** [comment]
node-oracledb 5.1 adds a unique suffix to duplicate column names when using the OUT_FORMAT_OBJECT mode so this issue is resolved.

**Comment by ember-simple-auth-unwrit** [comment]
@amroczeK https://openjs.space/questions/combining-rows-using-a-specific-column-in-javascript
