### ISSUE TITLE
How to parse the string `NOW()-INTERVAL 1 DAY`

### ISSUE THREAD

**Issue by edugrip** [knex/knex#3995]
# Environment

Knex version:
Database: MYSQL 8.0+ ,  KNEX version: 0.21.4
OS:

# Bug

While creating an insert query with  this code: 
```
await knex('results').insert(
        {
          game_id:game_id, 
          result:faker.random.number({min:10,max:99}), 
          date:`(DATE(NOW()) - INTERVAL ${i} DAY)`, 
          result_time:knex.fn.now()
          }  
        )
```

The query generated is like this : 

` insert into `results` (`date`, `game_id`, `result`, `result_time`) values ('(DATE(NOW()) - INTERVAL 1 DAY)', 1, 66, CURRENT_TIMESTAMP)`

The error I receive below is because the date value - 'DATE(NOW()) - INTERVAL 1 DAY)' should NOT BE as a string. 

Error:
And I receive the following error. 
ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '(DATE(NOW()) - INTERVAL 1 DAY)' for column 'date' at row 1

For the query to work correctly, it should be generated as below: 
` insert into `results` (`date`, `game_id`, `result`, `result_time`) values ((DATE(NOW()) - INTERVAL 1 DAY), 1, 66, CURRENT_TIMESTAMP)`

(THE DATE FIELD SHOULD BE WITHOUT STRINGS)

HOW TO ACHIEVE THAT IN KNEX.JS?

**Comment by elhigu** [comment]
Yep, knex.raw can be used in most of the places to pass SQL to queries instead of string literals.
