### ISSUE TITLE
Import migration files during migrate:latest with ESM import

### ISSUE THREAD

**Issue by hydroper** [knex/knex#3996]
# Environment

Knex version: latest
Database + version: PostgreSQL 12.3
OS: Windows 10

# Bug

Running `knex migrate:latest --esm` causes:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: path/to/migrationFile.js
> require() of ES modules is not supported.

**Comment by kibertoad** [comment]
@D10221 thoughts?

**Comment by D10221** [comment]
Assuming knex version 0.21.5 ? 
knexfile extension ? 
Migration/seed extensions ? 
Are you importing something, cjs or esm ? 
Stacktrace? 

Thanks

**Comment by hydroper** [comment]
Knex CLI version: 0.21.5-next2
KnexFile extension: knexfile.js
Migration extensions: .js (I did try running `knex migrate:make table -x cjs --esm`, but there's no CommonJS stub.)
On knexfile.js I import another ESM module.

Here's the stacktrace:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Padrão\Documents\com.recoyx\sitebladejs\starter.api\database\migrations\20200823141930_users.js
require() of ES modules is not supported.
require() of C:\Users\Padrão\Documents\com.recoyx\sitebladejs\starter.api\database\migrations\20200823141930_users.js from C:\Users\Padrão\Documents\com.recoyx\sitebladejs\starter.api\node_modules\knex\lib\migrate\sources\fs-migrations.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename 20200823141930_users.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Padrão\Documents\com.recoyx\sitebladejs\starter.api\package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1154:13)
    at Object.require.extensions..js (C:\Users\Padrão\AppData\Roaming\npm\node_modules\knex\bin\cli.js:59:20)
```

**Comment by kibertoad** [comment]
@hydroper can you try stable 0.21.5 instead?

**Comment by hydroper** [comment]
I get the same error stack with 0.21.5.

**Comment by D10221** [comment]
drop the '--cjs' flag

**Comment by D10221** [comment]
Do you have knex installed globally ?   
Could you try a quick/clean project ? 

Open a git bash terminal. You can do right click on any folder and select 'git bash here'.

```bash
mkdir knex-test
yarn init -y
yarn add knex
yarn add sqlite3
```
Alternatively , use `md knex-test`  on command propmt.
Or use npm if you like.

package.json
```json
{
  "name": "knex-esm",
  "type": "module",
  "dependencies": {
    "knex": "^0.21.5",
    "sqlite3": "^5.0.0"
  },
  "scripts": {
    "knex": "knex"
  }
}
```
knexfile.js
```javascript
export default {
  client: 'sqlite3',
  connection: {
    filename: './test.sqlite3',
  },
  useNullAsDefault: true,
};
```
migrations/one.js
```javascript
/**
 * @param {import("knex")} knex
 */
export function up(knex) {
    return knex.schema.createTable('xyz', (table) => {
        table.string('name');
    });
}
/**
 * @param {import("knex")} knex
 */
export function down(knex) {
    return knex.schema.dropTable('xyz');
}

```
seeds/one.js
```javascript
/** @param {import("knex")} knex */
export function seed(knex) {
  return knex('xyz').del();
}
```
Finally 
```bash
yarn knex migrate:latest --esm
```
Or ...
```bash
./node_modules/.bin/knex migrate:latest --esm
```

**Comment by hydroper** [comment]
Thanks for the example, it looks like --esm doesn't auto generate module files containing `import`/`export`. When these declarations occur, it works.

**Comment by D10221** [comment]
I see, the 'seed/migration' stubs are commonjs .

The `--esm` flag is a runtime feature.
