### ISSUE TITLE
solve the mssql "?"  being replaced to "@p0" problem when using Knex.raw("insert TET values ('?')")

### ISSUE THREAD

**Issue by caihaibin1991** [knex/knex#3997]
# Environment

Knex version: 6.2.0
Database + version: mssql

Description:
when using Knex.raw("insert TET values ('?')")  the mssql "?"  will be replaced to "@p0" and put into the database.

original code:
![image](https://user-images.githubusercontent.com/5326638/91010247-bcd48480-e614-11ea-9a9c-864a36667adf.png)
solve way:
Knex.raw("insert TET values ('\\\\?')") 
![image](https://user-images.githubusercontent.com/5326638/91010230-b0e8c280-e614-11ea-9148-0b60bdec5233.png)

**Comment by elhigu** [comment]
That sound just normal behavior. `?` is knex's binding syntax and it is replaced with real mssql query parameter string.

This should send ? as a parametrizable query to DB. 

```
Knex.raw("insert TET values (?)", ['?']); 
```

and this as a SQL string:

```
Knex.raw("insert TET values (\\?)"); 
```

However looks like escaping is broken with mssql, so I'll report that as a separate bug

https://runkit.com/embed/xt3cgb62kfko

**Comment by caihaibin1991** [comment]
```
Knex.raw("insert TET values (?)", ['?']); 
```
this sql will be replaced to "insert TEST values ('@p0'). you can try

**Comment by elhigu** [comment]
nope. It is replaced with "insert TEST values (@p0)" as you can see here https://runkit.com/embed/xt3cgb62kfko and the `?` is sent to server as a parameter binding @p0

**Comment by caihaibin1991** [comment]
the is the problem . I can use params binding to solve it .
but if I need to execute a sql file. like "insert TEST values('http://xxx?xxxx=xxx');insert .... ", then this sql will be replaced to "insert TEST values('http://xxx@p0xxxx=xxx');insert ....". that is why I need to modify the source code, and change my sql file to be "insert TEST values('http://xxx\\?xxxx=xxx');insert .... ".

**Comment by elhigu** [comment]
Yeah, that will not work with knex even if \\? escaping would be working (I reported that bug already as a separate issue). Knex is not designed to work with sql files. You need to use mssql driver directly to run complete files.

Though there has been discussion about not replacing anything on .raw strings if there is no parameter bindings given to .raw. That could help a bit, but it would require that someone implements that as a new feature to knex.

If you write a feature request for that, maybe someone will implement it some day (unless you are also willing to creata a PR adding that to knex).

**Comment by caihaibin1991** [comment]
> Yeah, that will not work with knex even if \? escaping would be working (I reported that bug already as a separate issue). Knex is not designed to work with sql files. You need to use mssql driver directly to run complete files.
> 
> Though there has been discussion about not replacing anything on .raw strings if there is no parameter bindings given to .raw. That could help a bit, but it would require that someone implements that as a new feature to knex.
> 
> If you write a feature request for that, maybe someone will implement it some day (unless you are also willing to creata a PR adding that to knex).

I got it. Thanks!
