### ISSUE TITLE
Add driver for snowflake

### ISSUE THREAD

**Issue by htunnicliff** [knex/knex#4002]
# Feature discussion / request

### Explain your use case
Using knex with SnowflakeDB.

### Explain what kind of feature would support this
Supporting the [`snowflake-sdk`](https://github.com/snowflakedb/snowflake-connector-nodejs) library as a new knex client driver.

### Give some API proposal, how the feature should work
Knex configuration options would allow `client` to be `snowflake`, as well as providing other options required for the `snowflake-sdk` library.

**Comment by elhigu** [comment]
Check contributing.md how to create plugin implementation as a separate package.

**Comment by htunnicliff** [comment]
@elhigu I'd be willing to contribute to a Snowflake plugin. However, the `CONTRIBUTING.md` docs for how to add a dialect are practically nonexistent:

> So if you like to write your own dialect, you can just inherit own dialect from knex base classes and use it by passing dialect to knex in knex configuration.

For developers to add new dialects, I believe there needs to be richer documentation than just the above sentence. Could creating documentation for dialect development be made a priority for this project?

**Comment by elhigu** [comment]
It is the same process than writing any other dialect. One just has to look how knex's internal dialects has been implemented and override the same methods for external plugin and implement it by trial and error. 

If someone likes to take the task it can be priority. It is up to contributors. For me personally I have lots of higher priorities than that.

**Comment by jdanielmyers** [comment]
@htunnicliff are you still pursuing a Snowflake dialect? I'm happy to help.

**Comment by htunnicliff** [comment]
@jdanielmyers This is what I have so far, but it's barely a first draft: [https://gist.github.com/htunnicliff/a7b90348b4d15634b0bf84ecae7bfeae](https://gist.github.com/htunnicliff/a7b90348b4d15634b0bf84ecae7bfeae)

**Comment by whitelynx** [comment]
Just to follow up here, it looks like the above gist turned into a full project: https://github.com/htunnicliff/knex-snowflake-dialect
