### ISSUE TITLE
Knex seed should notify when a specific seed is not found

### ISSUE THREAD

**Issue by flo-sch** [knex/knex#4005]
# Environment

Knex version: 0.21.5
Database + version: PostgreSQL: 12.4
OS: macOS 10.15.6

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am calling `knex.seed.run({ specific: 'some-seeder.ts' });` to invoke a **specific** seed file that my integration tests **rely** on.
I had renamed that seeder, and the command could not find it, but:

- did not throw an error
- did not show a warning or notice to let me know it was ignored (failed silently)

I figured out what was the problem by debugging and realizing that the seeder was not invoked at all.

2. Error message

There is none, it fails silently, this is my issue.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
// a test in a jest environment
beforeAll(async () => {
  // not finding a **specific** seeder should throw, or at least notice that the seeder cannot be executed
  await knex.seed.run({ specific: 'some-file-that-does-not-exists' });
});
```

# Feature discussion / request

1. Explain what is your use case

I have integration tests relying on a test database which I need to seed with specific data for my tests to work (reflecting the business workflow of the client I work for)

2. Explain what kind of feature would support this

An update to the `seed.run` source code to handle the case when the `specific` option is provided but the seeder cannot be found.

3. Give some API proposal, how the feature should work

I can think of a few options:
- throw an error in such a case (could also be an opt-in flag/option for `seed.run()` to throw an error in such a case)
- log a message stating that one specific seeder cannot be found

I am happy to contribute with a PR after I get some approval on the way forward :)

**Comment by elhigu** [comment]
I think always throwing an error in this case should be fine. PR + test for this would be welcome.

**Comment by flo-sch** [comment]
Perfect, I'll submit that :)
