### ISSUE TITLE
"Date" type converting data to local timezone

### ISSUE THREAD

**Issue by WaleedAshraf** [knex/knex#4008]
# Environment

Knex version: 0.21.5
Database + version: PostgreSQL 9.6.11
OS: macOS 10.15.4

# Bug

I have column with "date" type,
```js
await knex.schema.createTable('entity_shifts', (t) => {
    t.date('next_schedule').notNull() // YYYY-MM-DD format
```

When I create an entry and get it, I see different formats.
Data is stored in DB is in the correct format, but on fetching, it is converted to a different format.

## Data from DB
|next_schedule|
|-------------|
|2020-08-31|

## Data fetched using Knex
```
nextSchedule: 2020-08-30T22:00:00.000Z,
```

As currently, I'm in UTC+2 timezone, Knex is adjusting the "Date" based on my timezone. I want it to return the Date as stored in database.

"Date" type in PG doesn't have TIME or TIMEZONE info. https://www.postgresql.org/docs/9.4/datatype-datetime.html

**Comment by WaleedAshraf** [comment]
Found the solution: https://60devs.com/working-with-postgresql-timestamp-without-timezone-in-node.html

Related: 
- https://node-postgres.com/features/types#date-timestamp-timestamptz
- https://stackoverflow.com/questions/50716120/can-we-always-fetch-date-column-as-string-varchar-with-knex-and-postgres/50717046#50717046

**Comment by henry232323** [comment]
Sorry to temporarily revive this, but I'll share the solution I came to using the above resources.
```ts
require('pg').types.setTypeParser(1114, ((s: string) => new Date(s.replace(" ", "T") + "Z")))
```

This lets you keep the Date object without any external libs
