### ISSUE TITLE
Select * statement sorts columns alphabetically

### ISSUE THREAD

**Issue by omniteq** [knex/knex#4014]
# Environment

Knex version: 0.21.5
Database + version:sqlite3 5.0.0
OS: macOS Catalina 10.15.5 (19F101)

I have a table with fields like `instructor_1`, `instructor_2`, ..., `instructor_11`, and so on. 

Query like:
```javascript
db('myTable').select()
//or
db.raw('SELECT * FROM myTable')
```
returns object with columns sorted alphabetically instead of in order of CREATE TABLE statement. 
So `instructor_1`, `instructor_11`,...

The results are correct and the columns not sorted when I don't use knex.
Is it intentional?

**Comment by elhigu** [comment]
IIRC There might be code in knex that does this sorting. It probably was intentional originally, but I don't think that knex should do that. At least for update statements that sorting was removed (because with inserts order of the updates is significant).

**Comment by OlivierCavadenti** [comment]
I dont reproduce the problem in 1.0.4:

![image](https://user-images.githubusercontent.com/10152806/159091334-43c9f522-e66f-4445-97cf-bdae08f2b0fe.png)

The table : 

![image](https://user-images.githubusercontent.com/10152806/159091364-a176d04f-5eb2-456c-9ae8-addd02320d10.png)
