### ISSUE TITLE
seed.seed is not a function

### ISSUE THREAD

**Issue by CarvalhoBr** [knex/knex#4015]
# Environment

Knex version: 0.21.5
Database + version: postgres 12.4
OS: Ubuntu 20.04

# Bug

When I try to run the command `seed:run` I have an error: 
Error: Error while executing "/home/brandon/dev/ToolShare-API/seeds/01_categories.ts" seed: seed.seed is not a function
    at Seeder._waterfallBatch (/home/brandon/dev/ToolShare-API/node_modules/knex/lib/seed/Seeder.js:136:23)
TypeError: seed.seed is not a function
    at Seeder._waterfallBatch (/home/brandon/dev/ToolShare-API/node_modules/knex/lib/seed/Seeder.js:133:20)

**Comment by kibertoad** [comment]
can you share (potentially scrambled, without any actual sql manipulations) code of your seed file?

**Comment by CarvalhoBr** [comment]
https://github.com/CarvalhoBr/ToolShare-API/blob/master/src/database/seeds/01_categories.ts

**Comment by elhigu** [comment]
knex seems to be trying to find `.seed` function from your module, but you are exporting it as default.  Try 

```
import * as Knex from 'knex';

export async function seed(knex: Knex): Promise<void> {
 // ...
}
```

instead.

**Comment by CarvalhoBr** [comment]
It works, thank you

**Comment by helloworldmic** [comment]
> knex seems to be trying to find `.seed` function from your module, but you are exporting it as default. Try
> 
> ```
> import * as Knex from 'knex';
> 
> export async function seed(knex: Knex): Promise<void> {
>  // ...
> }
> ```
> 
> instead.

could you explain it? I encounter the same error
