### ISSUE TITLE
Inserting resource data with serializable object value fails

### ISSUE THREAD

**Issue by cipacda** [knex/knex#4017]
# Environment

Knex version: latest (0.21.5)
Database + version: Sqlite3
OS: Windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Failure when trying to insert a serialisable object instance. The value is serialised, but seems to be put into double quotes instead of single quotes

`resource = {
  id: "26d288d5-493a-4d17-842b-869851965e1d",
  startDate: LocalDate.parse("2020-09-03")
};
`

`LocalDate.parse` produces a LocalDate instance, that has a .toString() method that will produce "2020-09-03".

2. Error message

insert into `tableA` (`id`, `startDate`) values ('26d288d5-493a-4d17-842b-869851965e1d', \"2020-09-03\") - SQLITE_CONSTRAINT: NOT NULL constraint failed: tableA.startDate

**Comment by elhigu** [comment]
.toString() is not meant to be used for running queries.  It is for debugging purposes only. Missing also complete reproduction. Can be reopened if a there seems to be a knex bug related to this. Right now nothing is showing that there would be one.

**Comment by cipacda** [comment]
I am not referring on the .toString() of the knex instance, but the .toString() of the LocalDate to serialise it's values. Doesn't knex support passing serialisable object instances as values? It works fine with PostgreSQL client.

Full repro is
`knex("tableA").insert({ id: "26d288d5-493a-4d17-842b-869851965e1d", startDate: LocalDate.parse("2020-09-03") })`

**Comment by elhigu** [comment]
Here is complete reproduction https://runkit.com/embed/t6y41wkplxbq knex does not automatically call any toString() serialization for values. It may be done by underlying driver though. Check driver documentation if it supports some way to do it automatically.

**Comment by cipacda** [comment]
Thank you for the reply @elhigu
