### ISSUE TITLE
Missing INTO clause when insert into table with Trigger

### ISSUE THREAD

**Issue by jclabrand** [knex/knex#4019]
Knex version: 0.21.5
Database + version: MS SQL Server 2017
Objection version: 2.2.2

1. Explain what kind of behaviour you are getting and how you think it should do

I am inserting a record into a table using objection with knex connection. The table has a Trigger with DML in it to do some audit log record after its inserted.

2. Error message

The target table of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

3. Reduced test code

```JS
async signin(parent, args, context) {
    const db = context.db.main
    const userData = args.data
    const { payload, directory } = await context.auth.authenticate(userData )
    const session = await db.sessions.query().insert({ ...userData , userDirectory: directory })
    return { authorization: await context.auth.sign({ ...payload, sessionId: session.id }) }
}
```

**Comment by elhigu** [comment]
I don't see anything that should be fixed in knex for this and reproduction is far from complete. 

If you can give an example what kind of SQL you would expect to be generated and what is currently generated maybe we could help.

Closing until more info provided.

**Comment by jclabrand** [comment]
For example
if you have a database like this:

```SQL
CREATE TABLE person (
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	firstName VARCHAR(256) NOT NULL,
	lastName VARCHAR(256) NOT NULL
);
GO

CREATE TABLE log (
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	tableName VARCHAR(256) NOT NULL,
	event VARCHAR(16) NOT NULL,
	data VARCHAR(MAX) NOT NULL
);
GO

CREATE OR ALTER TRIGGER person_inserted ON person AFTER INSERT
AS
BEGIN
	DECLARE @jsonData VARCHAR(MAX);

	SET @jsonData = (SELECT * FROM INSERTED FOR JSON AUTO);
	INSERT INTO log VALUES ('person', 'INSERT', @jsonData);
END
GO

```

And you try to insert data from with knex:

Our example connection
```JS
const knex = require('knex')({
    client: 'mssql',
    connection: {
        host: 'somehostname',
        user: 'sa',
        password: 'thepassword',
        database: 'ourdb',
        options: {
            enableArithAbort: true,
            encrypt: true
	}
  }
})
```

This line works because is not returning data
```JS
const jennifer = await knex('person').insert({ firstName: 'Jennifer', lastName: 'Lawrence' })
// according to knex, must be:
// insert into [person] ([firstName], [lastName]) values ('Jennifer', 'Lawrence')
```

This line throws the mentioned error
```JS
const jennifer = await knex('person').returning('id').insert({ firstName: 'Jennifer', lastName: 'Lawrence' })
// according to knex, must be:
// insert into [person] ([firstName], [lastName]) output inserted.[id] values ('Jennifer', 'Lawrence')
```

This line also fails because must return id field from inserted
```JS
const jennifer = await knex.insert({ firstName: 'Jennifer', lastName: 'Lawrence' }, ['id']).into('person')
```


And so it reads in the SQL doc about OUTPUT Clause:

Columns returned from OUTPUT reflect the data as it is after the INSERT, UPDATE, or DELETE statement has completed but before triggers are executed.

For INSTEAD OF triggers, the returned results are generated as if the INSERT, UPDATE, or DELETE had actually occurred, even if no modifications take place as the result of the trigger operation. If a statement that includes an OUTPUT clause is used inside the body of a trigger, table aliases must be used to reference the trigger inserted and deleted tables to avoid duplicating column references with the INSERTED and DELETED tables associated with OUTPUT.

If the OUTPUT clause is specified without also specifying the INTO keyword, the target of the DML operation cannot have any enabled trigger defined on it for the given DML action. For example, if the OUTPUT clause is defined in an UPDATE statement, the target table cannot have any enabled UPDATE triggers.

If the sp_configure option disallow results from triggers is set, an OUTPUT clause without an INTO clause causes the statement to fail when it is invoked from within a trigger.

https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver15


Perhaps in the documentation of knex it is warned the use of the function `returning` in tables with TRIGGERS that I could not read?

**Comment by elhigu** [comment]
> Perhaps in the documentation of knex it is warned the use of the function returning in tables with TRIGGERS that I could not read?

Knex documentation should not explain obscure details of mssql server behaviour. This is not really common pitfall.

So was there something that knex could do differently to make this case to work? 

I still didn't see from clarification what kind of SQL we could generate to make this work for you.
