### ISSUE TITLE
Clauses are not added to subqueries within WHERE

### ISSUE THREAD

**Issue by Enitoni** [knex/knex#4020]
# Environment

Driver: pg
Knex version: 0.21.5

# Bug

When using `.from` on a subquery within a `.where`, the clauses are missing from the resulting query.
Test code:
```js
const test = db
  .select("foo")
  .from("a")
  .where((q) => {
    q.select("bar").from("b").where("b.id", 1)
  })

console.log(test.toQuery())
```
Output:
`select "foo" from "a" where ("b"."id" = 1)`

Expected output:
`select "foo" from "a" where (select "bar" from "b" where  "b"."id" = 1)`

**Comment by Enitoni** [comment]
It appears I have made a mistake where I thought `where` would behave the same as `whereExists`, if I use `whereExists` with a subquery instead, it works. Is this still a bug? Will leave open just in case.

**Comment by elhigu** [comment]
Yes, this is expected. Builder parameter in `.where((builder) => {})` is actually not complete query builder, but kind of an expression builder.

It is a bit unclear what: this should do

```
const test = db
  .select("foo")
  .from("a")
  .where(db.select("bar").from("b").where("b.id", 1));
```

Should that create a query:

```
select "foo" from "a" where (select "bar" from "b" where "b"."id" = 1)
```

or

```
select "foo" from "a" where select "bar" from "b" where "b"."id" = 1
```

Though currently passing query builder to `.where()` just doesn't work at all. To get the expected query above you can do this:

https://runkit.com/embed/uohomkjqgrh1

```
const test = db
  .select("foo")
  .from("a")
  .whereRaw("?", [db.select("bar").from("b").where("b.id", 1)]);
```
