### ISSUE TITLE
Full raw query is not passed through postProcess/knex-stringcase

### ISSUE THREAD

**Issue by olso** [knex/knex#4026]
# Environment

Knex version: 0.21.5
Database + version: postgres 12.4
OS: Macos (my laptop)/Heroku (postgres)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
```ts
const q = kx.raw(`
    select *, count(*) over() as total_count
    from ${tables.girl}

    order by updated_at desc
    limit ${1}
    offset ${offset}
`);
```

is not getting passed through `postProcessResponse` / `knex-stringcase`, they stay in snake_case instead of camelCase

with query builder it works as expected

**Comment by elhigu** [comment]
This is probably issue of `knex-stringcase` there is a test in knex that postProcess response is called to raw queries https://github.com/knex/knex/blob/378ae796410ac5812faa2a6a5754ab5364031670/test/integration/builder/additional.js#L42
