### ISSUE TITLE
column is of type timestamp but expression is of type character varying

### ISSUE THREAD

**Issue by rameshld6** [knex/knex#4027]
# Environment

Knex version: 0.14.6
Database + version: Redshift
OS: AWS

# Bug
I am selecting rows from `tableA` and inserting the resulting rows into `tableB`, using `knexJS`. Both `tableA` and `tableB` have identical schemas in a `Redshift` database.

**Column names and types**

```
id - int
created_date - timestamp without timezone
```

**Code**  

```

knex(tableB)
  .insert(function() {
      this.select()
          .from(tableA)
          .whereRaw('id=?', ['12345']);
  });
```
**Error**

This code runs into the error below

```
error: column \"created_date\" is of type timestamp without time zone but expression is of type character varying
```

How to fix this in code?

**Comment by elhigu** [comment]
What kind of query are you trying to create?

maybe this one:

```
knex('b')
  .insert(knex.raw("?", [ 
      knex.select().from('a').whereRaw('id=?', ['12345']) 
    ])
  ).toSQL();
```

https://runkit.com/embed/swe24d21lh8g

closing as knex seems to create expected query here.
