### ISSUE TITLE
knex .del() api doesn't run configured cascading deletes 

### ISSUE THREAD

**Issue by danaoxmt** [knex/knex#4029]
# Environment

Knex version: 0.21.4
Database + version: SQLite3 4.2.0
OS: macOS

1. I have 3 tables, TableA, TableB and TableC. TableC is a join table between the IDs of TableA and TableB. They're created via the migrations.

```
exports.up = function(knex) {
    const tableAPromise = knex.schema.hasTable('TableA').then((exists) => {
        if (!exists) {
           return knex.schema.createTable('TableA', (table) => {
                table.increments('id');
            })
        }
    })

    const tableBPromise = knex.schema.hasTable('TableB').then((exists) => {
        if (!exists) {
            return knex.schema.createTable('TableB', (table) => {
                table.increments('id');
            })
        }
    });

    const tableCPromise = knex.schema.hasTable('TableC').then((exists) => {
        if (!exists) {
            return knex.schema.createTable('TableC', (table) => {
                table.integer('tableA_id').references('TableA.id').onDelete('CASCADE').notNullable;
                table.integer('tableB_id').notNullable();
            });
        }
    });

    return Promise.all([tableAPromise, tableBPromise, tableCPromise]);
};
```

this generates the following SQLite3 schema. 

```
CREATE TABLE `TableA` (`id` integer not null primary key autoincrement);
CREATE TABLE `TableB` (`id` integer not null primary key autoincrement);
CREATE TABLE `TableC` (`tableA_id` integer, `tableB_id` integer not null, foreign key(`tableA_id`) references `TableA`(`id`) on delete CASCADE);
```

I have also ran `knex.raw('PRAGMA foreign_keys = ON');` in my client code. So when I manually delete a row in TableA that has a corresponding row in TableC both rows are deleted, happy days! So I know the migration is working correctly. 

However, my issue is that when I run the knex delete api, only the row in TableA gets deleted, the row in TableC still hangs around. I'm running the following in my client code, everything looks like it should be working to me. I'll have a look through the del() api to see if i can find out whats going on. 

```
        return db.transaction((trx) => {
            knex('TableA').where({id: id})
            .del()
            .then(trx.commit)
            .catch(trx.rollback);
        })
        .then(() => {
            logger.info(`Deleted [${id}] from TableA `)
            return true;
        })
        .catch((error) => {
            logger.error(`Failed deleting [${id}]: ${error}`);
            return false;
        });

```
this generates the following SQL 

```
{ 
  method: 'del',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1],
  __knexQueryUid: 'foo',
  sql: 'delete from `TableA` where `id` = ?' 
}
```

**Comment by elhigu** [comment]
Where are you running that `knex.raw('PRAGMA foreign_keys = ON');` ? Sounds like a user problem, since knex doesn't do any magic that would disable foreign key support.

**Comment by danaoxmt** [comment]
@elhigu sorry what I said was a bit misleading, thats ran in a previous migration file. Basically just wanted to point out that foreign keys were switched on for my sqlite3 DB (they're off by default).

**Comment by danaoxmt** [comment]
Yeah the query looks fine, doesnt seem to be a knex issue. Thanks for looking at this @elhigu

**Comment by elhigu** [comment]
> thats ran in a previous migration file.

That is not enough, pragma must be ran on every new connection.

**Comment by danaoxmt** [comment]
@elhigu that was it! Thanks for all your help, I'd assumed it was just a DB wide setting. 🎉
