### ISSUE TITLE
if the port of my oracle and it is not 1521,  it will throw TNS not lisen

### ISSUE THREAD

**Issue by caihaibin1991** [knex/knex#4030]
if the port of my oracle and it is not 1521,  it will throw TNS not listen.
and I found the reason .... the port param have not transfer into the oracledb ....
![image](https://user-images.githubusercontent.com/5326638/92902300-bd15b200-f453-11ea-862f-5dae87a680b2.png)

**Comment by caihaibin1991** [comment]
![image](https://user-images.githubusercontent.com/5326638/92902905-40370800-f454-11ea-86cb-a19207521e40.png)

**Comment by elhigu** [comment]
This is how oracledb test setup creates connection:

https://github.com/knex/knex/blob/master/test/knexfile.js#L81

DB driver's connection parameters are not handled by knex. Is there something that knex should do differently here?
