### ISSUE TITLE
Feature Request:  Build in support for moment.js, or option to manipulate timestamps

### ISSUE THREAD

**Issue by raydlevel5** [knex/knex#4031]
Please be kind, I'm new with Node/KNEX/Express/Editor-Server :)

Please consider building in support for the moment.js libraries, or some sort of datetime cast/conversion option, to include MSSQL (Tedious driver).

I'm not the only one with the question/problem, and I've posted a question to StackOverflow:  https://stackoverflow.com/q/63838192/3772763

Basically, when I try to send date- or time- specific content to the frontend, Node/JavaScricpt/KNEX adds the other half of the timestamp.

The only way I know how to work around this issue is by doing a cast/convert in the actual View or Stored Procedures:

```
	select
		convert(varchar, cast(t.StartTime as date))  as StartDate
		,convert(varchar, cast(t.StartTime as time), 120) as StartTime  -- grouping value
```

I just would really like to have this option in the Server side components (Node/Express/KNEX) -- and if it already exists -- I don't know how to implement it

Thank you for the consideration.

**Comment by elhigu** [comment]
Knex doesn't tell how data is returned from database. If one needs to change the behavior how values parsed from SQL query results to javascript types one has to use DB drivers' feature to do it.

> In a support article, it was recommended that the "dateString" option be set to true, and it is.

Are you sure there is such option in node-mssql driver? From docs  I have seen only something like this how to change parsing:

https://tediousjs.github.io/node-mssql/#input-name-type

```
sql.map.register(String, sql.DateTime)
```

Though I have never tried it myself. Closing as knex is not handling parsing from SQL types to JS.
