### ISSUE TITLE
Which driver does KNEX use with Microsoft SQL?

### ISSUE THREAD

**Issue by raydlevel5** [knex/knex#4036]
# Environment

Knex version:  0.21.5
Database + version:  Microsoft SQL Server 2016 13.0.4466.4
OS:  Windows environment

@smorey2 

If I remove the "mssql" npm package and install "tedious", KNEX will not function.  The mssql package appears to be required.  That's fine... but what specific driver or npm package is KNEX using?

Is KNEX riding on top of "tedious" or "mssql"?

Are any features from Tedious available inside the Node app after "mssql" is installed?

Could I use KNEX and Tedious at the same time?

**Comment by elhigu** [comment]
Currently it uses node-mssql and that uses tedious internally.  In theory mssql can also use also microsoft's native driver, but with knex it is not supported.
