### ISSUE TITLE
columnInfo() requires an Owner User in Oracle

### ISSUE THREAD

**Issue by torres-federico** [knex/knex#4041]
# Environment

Knex version: 0.21.5
Database + version: Oracle 12
OS: Windows

# Feature discussion / request

1. Explain what is your use case
When using **columnInfo()** in a development DB I don´t have any problems because I connect with an Owner User. But for production DB we use Service Users, so everytime columnInfo() is executed, it returns zero rows, that causes problems with  mapping.

2. Explain what kind of feature would support this
Internally, '**oracledb**' dialect uses **"user_tab_columns"** that only works if you use an Owner User, but for others users types it does not work.
Oracle dialect should use "**all_tab_columns**", so any user can retrieve table information

**Comment by elhigu** [comment]
Related issue https://github.com/knex/knex/issues/3992

**Comment by kibertoad** [comment]
Released in 0.21.9
