### ISSUE TITLE
Get information from a database that has already been created

### ISSUE THREAD

**Issue by ashkufaraz** [knex/knex#4042]
Hi

I want work with data base that has already created and has some records.(oracle)

knex.from('analysis').select("*")
    .then((rows) => {console.log(rows)
        for (row of rows) {
            console.log(row);
        }
    }).catch((err) => { console.log( err); throw err })
    .finally(() => {
        knex.destroy();
    });

But with this code say error ORA-00942: table or view does not exist .

Please help me

**Comment by elhigu** [comment]
For usage questions, please use gitter / stackoverflow. Also this doesn't follow issue template and doesn't provide full repro. You can also check out from test suite's code how it connects to the database if that is any helpful.
