### ISSUE TITLE
How to undo .onDelete('CASCADE')?

### ISSUE THREAD

**Issue by arslan-creator** [knex/knex#4044]
How to undo cascade in this migration?
`table.uuid('actionId').references('id').inTable('action').onUpdate('CASCADE').onDelete('CASCADE');`

I want it to be:
`table.uuid('actionId').references('id').inTable('action');`

**Comment by elhigu** [comment]
How would you do it with plain SQL?

**Comment by arslan-creator** [comment]
@elhigu so is it impossible?

**Comment by elhigu** [comment]
I didn't say that. Try reading my response again.

**Comment by arslan-creator** [comment]
@elhigu wow, wasn't knex supposed to help by building abstraction for sql? if your response to issues in your product is 'learn sql' it tells enough already. thank you for nothing

**Comment by elhigu** [comment]
Knex indeed is kind of abstraction for building SQL queries from pieces and also meant to abstract differences between DB engines in some cases where it is easily applicable. 

Also my question was sincere. If you can tell me what kind of SQL will do the trick I could help with telling how it can be done with knex.

**Comment by arslan-creator** [comment]
ok so I had this migration:
`table.uuid('actionId').references('id').inTable('action').onUpdate('CASCADE').onDelete('CASCADE');`

But now I want to remove cascading. Do I have to drop the existing foreing key constraint with `dropForeign` then create new one without `onDelete`?

**Comment by elhigu** [comment]
> if your response to issues in your product is 'learn sql' it tells enough already. thank you for nothing

Looks like this was actually accurate after all. Knowing how to write SQL for the database that you are using is prerequisite for being able to use knex. Sorry for not being able to help.

**Comment by arslan-creator** [comment]
no need for insincere sorry.
but now I get how knex managed to score over unresolved 400 issues.
good luck!
