### ISSUE TITLE
Duplicated semicolons on oracle toString() / toQuery()

### ISSUE THREAD

**Issue by guicovred** [knex/knex#4045]
# Environment

Knex version: 0.21.5
Database + version: Oracle
OS: any
@atiertant

# Bug

`toQuery()` & `toSql()` are returning duplicate semicolons for queries that pass through the method `wrapSqlWithCatch()`

Example: 

```
var knex = require('knex')({
    client: 'oracledb',
    connection: {
        host: '127.0.0.1',
        user: 'your_database_user',
        password: 'your_database_password',
        database: 'myapp_test'
    }
});

var builder = knex.schema.dropTableIfExists('book');

console.log(builder.toQuery())
```
outputs: 
```
begin execute immediate 'drop table "book"'; exception when others then if sqlcode != -942 then raise; end if; end;;
begin execute immediate 'drop sequence "book_seq"'; exception when others then if sqlcode != -2289 then raise; end if; end;
```

It happens because both `wrapSqlWithCatch()` and `toQuery()` are appending a semicolon to end of query.
https://github.com/knex/knex/blob/master/lib/dialects/oracle/utils.js#L30
https://github.com/knex/knex/blob/master/lib/interface.js#L14

**Comment by kibertoad** [comment]
Released in 0.21.7
