### ISSUE TITLE
Unexpected behaviour when using async functions in QueryBuilder

### ISSUE THREAD

**Issue by jarethuk** [knex/knex#4048]
# Environment

Knex version: 0.21.5
Database + version: PostgreSQL 11
OS: Mac

# Bug

We have just been tripped up by an async function being used in .with() and the builder object not being updated and want to know if this is expected behaviour or a bug.

In the following example we have a dummy query where a with statement is being used to get data from another table and the function which is being passed in is async.

	const columns = [
		'id',
		'email',
		database.raw('(select linked_user_id from linked_account where user_id = usr.id)')
	];

	const result = await database.with('linked_account', async (builder) => {

		builder.select(['user_id', 'linked_user_id']).from('user_linked_account').whereNotNull('created');

		const theId = await getTheIdAsync();

		builder.where('linked_user_id', '!=', theId);

	}).select(columns).from('usr').where({id: 1});

	/// ...
	
	async function getTheIdAsync(): Promise<number> {
		return new Promise((resolve) => {
			setTimeout(() => {
				resolve(2)
			}, 2000);
		});
	}

The first part of the builder is correctly set but the second where statement `builder.where('linked_user_id', '!=', theId)` is never added due to a async/await function being called.

Is this to be expected and if so, could the documentation/typescript definitions be updated to prevent this in the future?

**Comment by elhigu** [comment]
This is expected. Builder methods are sync only. If you are doing async operations in them, in your case query is probably compiled and executed before the code in

```
async (builder) => {
	builder.select(['user_id', 'linked_user_id']).from('user_linked_account').whereNotNull('created');
	const theId = await getTheIdAsync();
	builder.where('linked_user_id', '!=', theId);
})
``` 

has been executed.

> Is this to be expected and if so, could the documentation/typescript definitions be updated to prevent this in the future?

Nothing in documentation/typings says that one could return a promise from builder callbacks.

**Comment by jarethuk** [comment]
Thanks for the clarification.
