### ISSUE TITLE
Knex reformatting string with multiple quotes

### ISSUE THREAD

**Issue by dtturcotte** [knex/knex#4049]
# Environment

Knex version: 0.20.8
Database + version: PostgreSQL 12.1
OS: Mac OS Mojave

# Bug

I'm trying to dynamically insert timestamps with varying hour intervals into Postgres (12.1), NodeJS 10.15.3, and Knex 0.20.8. 

Inserting directly into Postgres via Postico, the NOW() + INTERVAL 'n hours' format works fine:

```
insert into users (first_name, updated_at) 
values ('Bob', NOW() + INTERVAL '2 hours');
```

When inserting via Knex / Node:

```
row.updated_at = `NOW() + INTERVAL '2 hours'`;
```

I'm getting error:

```
invalid input syntax for type timestamp with time zone: "NOW() + INTERVAL '2 hours'"
```

Outputting the query via query.toString(), I see the interval has been converted to

```
'NOW() + INTERVAL ''2 hours'''
```

How can I insert this in the correct format?

**Comment by elhigu** [comment]
```
knex('users').insert({
    updated_at: knex.raw(`NOW() + INTERVAL '2 hours'`);
})
```
