### ISSUE TITLE
ESM interop tests are failing with Node 14.13

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#4054]
NodeJS 14.13.0 changed how imports in CJS are handled. This caused esm-interop.spec.js#L164 and esm-interop.spec.js#L179 to fail.

**Comment by kibertoad** [comment]
@D10221 Any chance you could take a look?

**Comment by D10221** [comment]
... See https://github.com/knex/knex/pull/4055

**Comment by elhigu** [comment]
Is this  ok to close now?
