### ISSUE TITLE
Pg Native Bindings

### ISSUE THREAD

**Issue by ctaity** [knex/knex#4062]
hi i trying to use pg-native with knex, and i get this error: 

```
knex/lib/dialects/postgres/index.js:116
        connection.on('error', (err) => {
                   ^

```

I check, dialects/postgres/index.js:116, and i saw this 
```

    return new Promise(function (resolver, rejecter) {
      const connection = new client.driver.Client(client.connectionSettings);
      connection.connect(function (err, connection) {
```
In the https://node-postgres.com/api/client, the callback of connect is document as: 

client.connect(callback: (err: Error) => void) => void

The parameter connection donst exists. 

If change the callback from 

`      connection.connect(function (err, connection) {
`
to

`      connection.connect(function (err) {
`
All works. and with the env variable NODE_PG_FORCE_NATIVE=true, knex use native bindings.

**Comment by elhigu** [comment]
Why are you trying to use pg-native? AFAIK it is not anymore even faster that JS version. Also please read issue template before submitting issues. Closing as issue is unclear and there doesn't seem to be anything to do...
