### ISSUE TITLE
Missing support for withKeyName in TypeScript type declarations

### ISSUE THREAD

**Issue by pdemarino** [knex/knex#4063]
# Environment

Knex version: 0.21.6
Database + version: Not relevant
OS: Not relevant

Typescript issue: @lorefnon 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am trying to rename a foreign key. Minimal example:

```ts
import * as Knex from "knex";

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("xyz", (t) => {
    t.increments("id");
    
    t.foreign("id").references("another.table").withKeyName("cg_link");
  });
}
```

2. Error message

`Property 'withKeyName' does not exist on type 'ReferencingColumnBuilder'.ts(2339)`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

See above

**Comment by kibertoad** [comment]
Released in 0.21.13
