### ISSUE TITLE
Connection status

### ISSUE THREAD

**Issue by aduyng** [knex/knex#407]
Anyone knows how to get connection status? I would like to throw an error if the database server is not reachable.

**Comment by farolfo** [comment]
Any update on this? I cannot catch the errors of Knex after not connecting to the DB in the initialize function, I only see the errors logged
```
Knex:Error Pool2 - Error: connect ECONNREFUSED
Knex:Error Pool2 - Error: connect ECONNREFUSED
```
but I'd like a callback function where I can catch this error and be notified that the db connection failed.

**Comment by savovs** [comment]
Hope this helps
```js
import knex from "knex"
import config from "../../knexfile"

export const connectDB = async (retries = 5) => {
	while (retries) {
		try {
			await knex(config[process.env.NODE_ENV]).raw("select 1+1 as result")
		} catch (err) {
			console.error("Couldn't connect to DB: ", err)

			retries -= 1
			console.log(`retries left: ${retries}`)

			// wait 5 seconds
			await new Promise(res => setTimeout(res, 5000))
		}
	}
}
```
