### ISSUE TITLE
Problems With SubQuery 

### ISSUE THREAD

**Issue by callmedavron** [knex/knex#4073]
# Environment

Knex version: 0.21.6
Database + version: Postgres 12
OS: MacOs Catalina

**First, I want to express my gratitude for such a useful library Knex.**

# Bug
### When i call ```knex.raw``` with this ```sql```  i got ``` {..., rows: []}``` empty rows bu result is exist in database

```
const result = await knex.raw(`
    select 
            total, 
            jsonb_agg(name) as organization_list
    from (
            select (count(*) over ())::integer as total,
                    organization.name           as name
            from "org"."organizations" as "organization"
            where "organization"."name" ~* '(?=.*test)(?=.*organization)'
        ) as "c"
    group by "total"
`)
```

**if i call this query with ```Pg``` i got result ```{..., rows: [ { total: 1, list: [Array] } ]}```, result which i want**

```
const { Pool } = require('pg')
const pool = new Pool({
    ...variables
})

pool.query(`
    select 
            total, 
            jsonb_agg(name) as organization_list
    from (
            select (count(*) over ())::integer as total,
                    organization.name           as name
            from "org"."organizations" as "organization"
            where "organization"."name" ~* '(?=.*test)(?=.*organization)'
        ) as "c"
    group by "total"
`, (err, result) => {

    // Result 
    console.log(result)

    // End pool
    pool.end()
})
```

**``` if i call sub query as main query i got result ```{..., rows: [ { total: 1, list: [Array] } ]}```, result which i want**

```
const result = await knex.raw(`
           select 
                   (count(*) over ())::integer as total,
                    organization.name           as name
            from "org"."organizations" as "organization"
            where 
                      "organization"."name" ~* '(?=.*test)(?=.*organization)'
`)
```

To make it work i need do one of two things
**1) Remove ``` ~* '(?=.*test)(?=.*organization)'``` it works fine with Knex and i got the same result like ```Pg```** 
**OR**
**2) Not use subquery. The result will not be what I want**

**Comment by davrontb** [comment]
Our organization has the same problem

**Comment by shahzodgenius** [comment]
I faced this issue today. Please fix it as soon as possible. It will be great! Thanks beforehand.

**Comment by elhigu** [comment]
You are using `?` marks in .raw query which tries to convert them to parameter bindings. You need to escape those if you like to make them work. Though some dialect implementations might have a bug in that escaping (mssql or oracledb). With postgres it works just fine.

**Comment by elhigu** [comment]
Related issues:

https://github.com/knex/knex/issues/3112
https://github.com/knex/knex/issues/3998
