### ISSUE TITLE
Keep track of seed files execute in database

### ISSUE THREAD

**Issue by mittalyashu** [knex/knex#4074]
## 1. Explain what is your use case

After the migrations are complete, I execute all the seed files and populate with initial data inside database.

But to avoid duplication or inserting data again and again, I do something like this

I check for any existing data and based on that insert the initial data.

```js
exports.seed = (knex) => {
  return knex
    .select()
    .from("users")
    .limit(1)
    .then(response => {
      if (!response[0]) {
        return knex("users")
          // insert data
          .insert([])
          .then(() => {
            // success
          })
          .catch(err => {
            // error
          });
      }
    })
    .catch(err => {
      // error
    });
};
```

## 2. Explain what kind of feature would support this

Just like there are records of which migration get execute and stored inside database, something similar for seed files would be helpful.

As it states here

> Seed files allow you to populate your database with test or seed data independent of your migration files.

Seeds files can also be used for testing or insert independent data, in that case there can be option to store executed seeds files in database or not. 

## 3. Give some API proposal, how the feature should work

Just by stating the `tableName` in the seeds object can enable to store data about executed files inside database.

```js
seeds: {
	directory: "./seeds",
	tableName: "seeds"
},
```

**Comment by elhigu** [comment]
This feature has been on the table few times and it is not wanted. 

If you need to populate some static data to database you can do it in migrations and if it is just for development use, then you can easily setup a script that runs necessary seeds once after db has been created and migrations has been ran. 

If you like, you can also easily write couple of helpers which implements this feature for you and use those helpers in your seed files.
