### ISSUE TITLE
How should I configure my webpack to use Knex in browser

### ISSUE THREAD

**Issue by hollax** [knex/knex#4090]
Excerpt from the documentation:

> Knex can be built using a JavaScript build tool such as browserify or webpack. In fact, this documentation uses a webpack build which includes knex. View source on this page to see the browser build in-action (the global knex variable).

However, there is no instruction on how to configure this. I have checked all over the internet and could find a straight forward method. Am trying to use [knex-cordova-sqlite](https://www.npmjs.com/package/knex-cordova-sqlite) so I need Knex to connect with the database.

**Comment by elhigu** [comment]
Not knex issue... if someone likes to write a recipe to knex wiki it is welcome.
