### ISSUE TITLE
onConflict: types are mis-configured

### ISSUE THREAD

**Issue by felixmosh** [knex/knex#4101]
# Environment

Knex version: 0.21.11
Database + version: Mysql 8
OS: linux

There are several bugs related to the new `onConflict` implementation.

# Bug 

1. can't pass a string to `onConflict`
```ts
db
    .insert(insertData)
    .into(tableNames.articleContents)
    .onConflict('article_id')
    .ignore();
```
![image](https://user-images.githubusercontent.com/9304194/97800977-24750480-1c42-11eb-95e3-8e654e862ae6.png)

2. Can't use `debug` at the end of the query
```ts
db
    .insert(insertData)
    .into(tableNames.articleContents)
    .onConflict('article_id' as any)
    .ignore()
    .debug(true)
```
![image](https://user-images.githubusercontent.com/9304194/97801005-4bcbd180-1c42-11eb-8b3f-f4774e48749d.png)

3. In Mysql there is no use of the column in the `onConflict`, so it should be an optional parameter

# Missing / erroneus documentation

Issue #3 may should be documented, cause it doesn't make sense in Mysql

# Feature
If I want to build a query like
```sql
insert into `article_contents` (`article_id`, `body`, `title`) values (?, ?, ?) on duplicate key update `title` = values(`title`),`body` = values(`body`);
```

I need make an ugly map and usage of raw,
```ts
db
    .insert(insertData)
    .into(tableNames.articleContents)
    .onConflict('xxx' as any)
    .merge(
      ['title', 'body'].reduce((result, col) => {
        result[col] = db.raw('values(??)', col);
        return result;
      }, {})
    );
```

I think that Api a such will be more powerfull:

```ts
db
    .insert(insertData)
    .into(tableNames.articleContents)
    .onConflict('xxx' as any)
    .merge('title', {body: 'other custom value'});
```
Which will generate
```sql
insert into `article_contents` (`article_id`, `body`, `title`) values (?, ?, ?) on duplicate key update `title` = values(`title`),`body` = ?;
```

@lorefnon, @nicoburns

**Comment by nicoburns** [comment]
I think (1) and (2) are issues with the TypeScript definitions. In plain JavaScript you can pass a string to `onConflict` (there's a test that covers this) and it will work but TypeScript won't let you. (2) seems to be an issue with passing through the builder type. I'll take a look into these.

Regarding (3), I think you should just be able to do:

```javascript
db
    .insert(insertData)
    .into(tableNames.articleContents)
    .onConflict('xxx' as any)
    .merge({body: 'other custom value'});
```

which will generate:

```sql
insert into `article_contents` (`article_id`, `body`, `title`) values (?, ?, ?) on duplicate key update `body` = ?;
```

You don't need to update every field. Fields that aren't updated will keep their original value.

**Comment by nicoburns** [comment]
Update on (1). Not sure if this is correct, but if you have a type on your query, then it allows you to use properties from that type. The following compiles:

```typescript
interface User {
  id: number;
  age: number;
  name: string;
  active: boolean;
  departmentId: number;
}

await knex
  .table<User>('users')
  .insert({ id: 10, active: true })
  .onConflict('id')
  .merge({ active: true })
  .returning('*');
```

**Comment by felixmosh** [comment]
@nicoburns, 
Regarding 
```ts
db
    .insert(insertData)
    .into(tableNames.articleContents)
    .onConflict('xxx' as any) <--- why should i specify it at all (in MySql)?
    .merge({body: 'other custom value'});
```

Regarding the feature suggestion, you've missed the point, if I want to mix & match between using `values` & custom value in the  update part I'm not able to without the `reduce` code that I've added.

**Comment by nicoburns** [comment]
> why should i specify it at all (in MySql)?

There's definitely a case to be made that this parameter should be optional (because it's not required MySQL).

> Regarding the feature suggestion, you've missed the point, if I want to mix & match between using values & custom value in the update part I'm not able to without the reduce code that I've added.

I don't understand why you would want to iterate over the source properties like you have suggested. The
```sql
`title` = values(`title`),
```
in your example is redundant and can be omitted without changing the result of the query.

**Comment by nicoburns** [comment]
I've put in a PR to fix issue 2 (lack of debug method in type definitions) https://github.com/knex/knex/pull/4102

**Comment by felixmosh** [comment]
@nicoburns, 
In the example I've mentioned all of the `insert` columns are in the `merge` (it doesn't make sense as you've mentioned).
But think that I want update only a **subset** of the insert columns using `values()` way, I can't without that `reduce`.

Another example for the idea,

Thing that I want to make a query:
```sql
insert into `article_contents` (`article_id`, `body`, `title`) values (?, ?, ?) on duplicate key update `title` = values(`title`),`body` = values(`body`), update_date=?;
```

You will need to write it as:
```ts
db.insert(insertData)
  .into(tableNames.articleContents)
  .onConflict('xxx' as any)
  .merge({
    title: db.raw('values(??)', ['title']), // <- this is ugly
    body: db.raw('values(??)', ['body']), 
    update_date: new Date(),
  });
```

It is better to allow passing `string` & `objects` (as multi arg function) to indicate what should be used with `values` and what should be overridden.

Similar to what I've done in [`knex-on-duplicate-update`](https://github.com/felixmosh/knex-on-duplicate-update#example)

**Comment by nicoburns** [comment]
@felixmosh Ah, I think I understand now. Thanks for the new example. I've been writing that as:

```javascript
db.insert(insertData)
  .into(tableNames.articleContents)
  .onConflict('xxx' as any)
  .merge({
    title: insertData.title,
    body: insertData.body,
    update_date: new Date(),
  });
```
Which is slightly less ugly. But that does indeed involved some repetition, and I think the API you propose looks quite nice.

**Comment by nicoburns** [comment]
@artursvonda Regarding issue (1) in the issue description above. The following works:

```typescript
interface User {
  id: number;
  age: number;
  name: string;
  active: boolean;
  departmentId: number;
}

await knex
  .table<User>('users')
  .insert({ id: 10, active: true })
  .onConflict('id')
  .merge({ active: true })
  .returning('*');
```

But the following (without the explicit type parameter) doesn't:

```typescript
await knex
  .table('users')
  .insert({ id: 10, active: true })
  .onConflict('id')
  .merge({ active: true })
  .returning('*');
```

Do you know of a way that we could get the allowable parameters for `onConflict` to be inferred from the keys passed to `insert`?

**Comment by artursvonda** [comment]
Inferring keys from insert wouldn't be easy as we'd either have to add new attribute to the DeferredKeySelection or assume all fields of result are present in the insert (not a safe assumption). We could for now add  generic `string` type as fallback and, from what I understand, allow version without any arguments to `onConflict`. So appending this types should do
```
    onConflict(
      columns: string[]
    ): OnConflictQueryBuilder<TRecord, TResult>;
    onConflict(): OnConflictQueryBuilder<TRecord, TResult>;
```

**Comment by kibertoad** [comment]
@felixmosh Is there anything left to be fixed in the latest knex version?

**Comment by felixmosh** [comment]
It is not resolved, 
Only the issue with `debug` type is resolved.

The value that `onConflict` gets is redundant in Mysql, and it still can't be a string
![image](https://user-images.githubusercontent.com/9304194/103209958-01e32d00-490d-11eb-90d8-809f4bd4f4de.png)

**Comment by kibertoad** [comment]
@lorefnon @artursvonda Any ideas how to approach this?

**Comment by kibertoad** [comment]
@felixmosh I assume now it is resolved fully and can be closed?
