### ISSUE TITLE
(Question) Handling multiple Knex DB connections and Errors

### ISSUE THREAD

**Issue by amroczeK** [knex/knex#4104]
# Environment

Knex version: 0.21.2
Database + version: Oracle 11g / MySQL
OS: Centos 7

@elhigu 

# Question 1

What is the most appropriate way to handle cached connections created my Knex when an error occurs that might break the connection?

My application does SQL queries to multiple datasources (MySQL/Oracle) creating a new knex connection to the datasource IF an existing connection doesn't already exists, and caches it and every subsequent SQL query will re-use the existing knex connection object stored in 'cachedConnections' if available.

Recently after running the redux action has 100 SQL queries (ALL SELECT QUERIES) with a concurrency of 3, to perform Network performance checks against the databases it connects to, I experienced this error when connecting to Oracle.

After this error occurred, the remaining queued SQL queries would timeout because the following error must have broken the connection to the database. This is the first time I've seen this error while using transactions, has been working fine before.

Should I be doing something like this to catch knex errors after a query and manually remove/flush the knex connection in cachedConnections? Or is there a better way?

Also am I handling trx.commit / trx.rollback properly? I have read documentation and knex developers stating that you don't need to explicitly do trx.commit/rollback if you are using .then/.catch because knex does it automatically [#1346](https://github.com/knex/knex/issues/1346). If that's the case, I'm not sure why I got the error below. Unless I've implemented transactions incorrectly.

```
knex
      .transaction((trx) => {
        return trx
          .raw(sql)
          .limit(modifier.limit || 10000)
          .timeout(60000)
          .on('query-error', (error, obj) => {
            if(cachedConnections[datasource.name]) delete cachedConnections[datasource.name]
          });
      })
      .then((result) => {
        result = postProcessResults(result, format, datasource.databaseType);
        resolve(resultHandler(datasource.databaseType, result));
      })
      .catch((error) => reject(error));
```

## For example I have experienced the following error:
```
(node:1) UnhandledPromiseRejectionWarning: Error: NJS-003: invalid connection
at Connection.rollback (/home/node/server/node_modules/oracledb/lib/connection.js:159:14)
at Connection.rollback (/home/node/server/node_modules/oracledb/lib/util.js:181:10)
at /home/node/server/node_modules/knex/lib/dialects/oracledb/index.js:130:16
at new Promise (<anonymous>)
at Connection.connection.rollbackAsync (/home/node/server/node_modules/knex/lib/dialects/oracledb/index.js:129:16)
at Oracle_Transaction.rollback (/home/node/server/node_modules/knex/lib/dialects/oracledb/transaction.js:28:25)
at Function.transactor.rollback (/home/node/server/node_modules/knex/lib/transaction.js:278:42)
at /home/node/server/node_modules/knex/lib/transaction.js:194:35
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# Example code
```
// db-connector.js
const _knex = require("knex");

let cachedConnections = {};

const query = (datasource, sql, format, modifier, chartType) => {
  return new Promise((resolve, reject) => {
    const knex = findOrCreateConnection(datasource);

    knex
      .transaction((trx) => {
        return trx
          .raw(sql)
          .limit(modifier.limit || 10000)
          .timeout(60000);
      })
      .then((result) => {
        result = postProcessResults(result, format, datasource.databaseType);
        resolve(resultHandler(datasource.databaseType, result));
      })
      .catch((error) => reject(error));
  });
};

const getConnectionObj = (databaseType) => {
  switch (databaseType) {
    case "oracledb":
      return {
        client: datasource.databaseType,
        connection: {
          host: datasource.host,
          user: datasource.user,
          password: datasource.password,
          database: datasource.database,
        },
        pool: { min: 0, max: 33 },
      };
    case "sqlite3":
      if (datasource.filename && datasource.filename.length > 0) {
        return {
          client: "sqlite3",
          connection: {
            filename: "./packages/" + datasource.filename,
          },
          useNullAsDefault: true /* Supress sqlite3 warning*/,
        };
      } else {
        return false;
      }
    case "impala":
      return {
        host: datasource.host,
        port: 21050,
        resultType: "json-array",
      };
    default:
      return {
        client: datasource.databaseType,
        connection: {
          host: datasource.host,
          user: datasource.user,
          password: datasource.password,
          database: datasource.database,
        },
      };
  }
};

const findOrCreateConnection = (datasource) => {
  // If the connection already exists
  try {
    if (cachedConnections[datasource.name]) {
      return cachedConnections[datasource.name];
    }
    // Establish a new connection
    else {
      const connObj = getConnectionObj(datasource.databaseType);
      const newConnection = _knex(connObj);
      cachedConnections[datasource.name] = newConnection;
      return newConnection;
    }
  } catch (error) {
    console.log(error);
  }
};

```

# Question 2
In regards to the connection pool, I am connecting to OracleDB using a single user account which is configured be allowed to use 100 sessions on the DB. To improve performance for users,  SQL queries run in parallel up to 4 sessions at a time.

Each user that fires off the Network performance which action will send off 100 queued SQL queries which gets sent to the database concurrently 3 at a time, then next 3 after the first 3 resolved. So 3 SQL queries would utilize 12 sessions assigned to that oracle db user.

Does knex handle the session pool for connections to Oracle DB the same way as connection pool? Currently experiencing the session pool for my user easily reaching 100 causing "ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit" if multiple users are running the network performance check action.

**Comment by elhigu** [comment]
Usage questions should go to gitter / stackoverflow (as mentioned in the issue template). Though if anyone likes to discuss about this here, feel free to continue even that the issue is closed.
