### ISSUE TITLE
Overriding only some merge fields

### ISSUE THREAD

**Issue by Naddiseo** [knex/knex#4106]
# Environment

Knex version: 0.21.12
Database + version: pg@latest
OS: Ubuntu 20.04

tagging @nicoburns (thanks for implementing upsert!!)

# Feature discussion / request

1. Explain what is your use case
I'm trying to use the `.onConflict().merge()` but allow partial overrides of the fields. The sql I'm trying to achieve is this:
```sql
INSERT INTO mytable
    (key_field, use_update_field)
    VALUES
    (?, ?)
ON CONFLICT (key_field) DO
UPDATE SET
    use_update_field = EXCLUDED.use_update_field,
    another_constant_field = 'some constant string'
RETURNING *
```
As you can see, in the update part, I'm mixing the `EXCLUDED` fields with a non-excluded field; I tried:
```javascript
knex('mytable')
.insert({key_field: 1, use_update_field: "VALUE"})
.onConflict('key_field')
.merge({ another_constant_field: "some constant string" });
```
However, this will prevent the `use_update_field = EXCLUDED.use_update_field,` from being present.

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work
I think the `.merge()` method could take a second parameter for overrides, eg:
```javascript
.merge(updates, overrides)
```
where the `updates` field could be null/undefined such that:
```javascript
insert({k:1, field: 2}).onConflict('k').merge(null, { some_field: "value" })
///->
// ... UPDATE SET field = EXCLUDED.field, some_field = "value"
```

*edit:
My current workaround (assuming I'm not missing something obvious) is to repeat all the fields in the `.merge()` and use `knex.raw('EXCLUDED.??', 'field_name')`, eg:
```javascript
insert({k:1, field: 2}).onConflict('k').merge({
    field: knex.raw('EXCLUDED.??' ,'field'),
    some_field: "value" 
})
```

* edit2:
I think this is the (3) feature request from #4101

**Comment by elhigu** [comment]
Maybe if also other database engines support that kind of syntax for using EXCLUDED  values to populate some of the update this could be potential improvement, but I'm not completely sure... 

Currently the "work around" sounds like the correct way to do it. It also reflects very well the final outputted SQL that is generated. There is nothing wrong to use `knex.raw` or `knex.ref` (not sure if that works with EXCLUDED "table") in this kind of cases.

**Comment by elhigu** [comment]
Also it is not given that people actually want to update all listed / excluded fields by default in case of conflict. I'm inclining more to the side that the:

```
insert({k:1, field: 2}).onConflict('k').merge({
    field: knex.ref('EXCLUDED.field'),
    some_field: "value" 
})
```

actually is the correct way to achieve this functionality. It doesn't make any expectations that the inserted and updated fields should be shared in any ways and keeps the `knex` builder close to created SQL.

**Comment by Naddiseo** [comment]
(Maybe I'm misunderstanding how upsert works)

> Also it is not given that people actually want to update all listed / excluded fields by default in case of conflict

Isn't that what a plain `.merge()` already does though? (update all the fields included in the insert?)

My main issue is that I don't want to be duplicating (thrice) the fields in the `insert()` and the `merge()` just because I want to add/override one field.
As a useability/foot-gun issue: using `knex.ref('EXCLUDED.field')` introduces a possible source of typo that wont get seen until runtime, but could be avoided if it didn't need to be written a third time. As a crossdb thing, maybe something like the following could work?:
```javascript
insert({k:1, field: 2}).onConflict('k').merge({
    field: knex.InsertedValue(), // InsertedValue would change to `EXCLUDED.field` on pg, and the equivalent on other db-engines
    some_field: "value" 
})
```

**Comment by nicoburns** [comment]
> Maybe if also other database engines support that kind of syntax for using EXCLUDED values to populate some of the update this could be potential improvement, but I'm not completely sure...

They do. Postgres and SQLite both support the `excluded.` syntax and MySQL supports the same functionality using `VALUES()`. We are already using this syntax for plain `.merge()` with no arguments. The "backend" for the functionality is thus quite simple. The potentially tricky bit would be deciding on the best syntax to expose it at the knex builder level.

I could also imagine something like the `knex.InsertedValue()` syntax working. As an alternative @felixmosh has suggested the following syntax in https://github.com/knex/knex/issues/4101 (with prior art in his [knex-on-duplicate-update](https://github.com/felixmosh/knex-on-duplicate-update#example) library):
```javascript
knex
    .insert({ title: 'foo', body: 'bar' })
    .into('tableName')
    .onConflict('id')
    .merge('title', {body: 'other custom value'});
```

**Comment by elhigu** [comment]
I thing something like ` knex.InsertedValue()` would be better way to do it (maybe with some other naming convention though). It would also allow defining the order in which values are updated since `SET a = a + 1, b = a` is not the same that `SET b = a, a = a + 1`.

``

**Comment by RayZoey** [comment]
CONFLICTCONSTRAINT

**Comment by RayZoey** [comment]
> > Maybe if also other database engines support that kind of syntax for using EXCLUDED values to populate some of the update this could be potential improvement, but I'm not completely sure...
> 
> They do. Postgres and SQLite both support the `excluded.` syntax and MySQL supports the same functionality using `VALUES()`. We are already using this syntax for plain `.merge()` with no arguments. The "backend" for the functionality is thus quite simple. The potentially tricky bit would be deciding on the best syntax to expose it at the knex builder level.
> 
> I could also imagine something like the `knex.InsertedValue()` syntax working. As an alternative @felixmosh has suggested the following syntax in #4101 (with prior art in his [knex-on-duplicate-update](https://github.com/felixmosh/knex-on-duplicate-update#example) library):
> 
> ```js
> knex
>     .insert({ title: 'foo', body: 'bar' })
>     .into('tableName')
>     .onConflict('id')
>     .merge('title', {body: 'other custom value'});
> ```
> 
> where a string value in merge corresponds to using the inserted/excluded value.


it dose not support `constraint`?🧐
