### ISSUE TITLE
Setting { transaction: false } on one migration disables transactions in all migrations

### ISSUE THREAD

**Issue by mshibl** [knex/knex#4112]
# Environment

Knex version: 0.21.3
Database + version: Postgres 9.6
OS: macOS Mojave

# Bug

Expected: Any migration that does not have `exports.config = { transaction: false }` should be subscribed to a migration

Actual: Setting `exports.config = { transaction: false }` in one migration results in the transaction being disabled for all following migrations

**Comment by elhigu** [comment]
Please add reproduction. How are you selecting different config for different migrations?

**Comment by jeff-permiso** [comment]
I'm still running into this issue.

Knex: 0.95.6
Postgres: 11
OS: osx 10.15.7


```
exports.config = { transaction: false };

exports.up = async function (knex) {
  await knex.raw(`
    CREATE INDEX CONCURRENTLY IF NOT EXISTS foo on bar;
  `);
};

exports.down = async function (knex) {
  await knex.raw(`
    DROP INDEX IF EXISTS foo;
  `);
};
```
