### ISSUE TITLE
Custom Directory Path not Working

### ISSUE THREAD

**Issue by MarkoMlakar** [knex/knex#4114]
# Environment

Knex version: 0.21.12
Database + version: PostgreSQL 13.0
OS: MacOS Catalina 10.15.7

# Bug

- My knexfile.js is sitting in the root directory.
- I've created an extra directory to store my knex migrations and seeds called "knex"
- I added a custom directory path to **knexfile.js** as shown below:

```
const dotenv = require("dotenv");
dotenv.config();

module.exports = {
  development: {
    client: process.env.KNEX_CLIENT,
    connection: {
      host: process.env.KNEX_HOST,
      user: process.env.KNEX_USER,
      password: process.env.KNEX_PASSWORD,
      database: process.env.KNEX_DATABASE,
      charset: process.env.KNEX_CHARSET,
    },
  },
  /* TODO: Why is this not working? */
  migrations: {
    directory: __dirname + "/knex/migrations",
  },
  seeds: {
    directory: __dirname + "/knex/seeds",
  },
};
```

- When I run `knex migrate:make ... ` or `knex seed:make ... ` the migration and seed folder is created in the root directory instead of in the /knex directory.

**Comment by elhigu** [comment]
`migrations` attribute should be in the same level in the config with `client` and `connection`
