### ISSUE TITLE
Knex-oracledb Number Data type precision shows more number

### ISSUE THREAD

**Issue by msudhayaraj** [knex/knex#4115]
# Environment

Knex version: 0.20.11
Database + version: ORACLE 11g
OS: Ubuntu 16.04 LTS

 @ atiertant.

# Bug

**Knex-oracledb Number Data type precision shows more number**

I had a column in oracledb with number data type (**NUMBER(19,2)**) only, When execute the query in plsql developer i got the result correctly.But execute the same via knex the precision goes wrongly.

Actual table value is : **457444.47**
Got the Result from knex is : **457444.47000000003**

Help me to resolve this, Thanks in advance

**Comment by elhigu** [comment]
Knex is not doing the serialization from database types to javascript types. Please check how that works when you use node-oracledb driver directly without knex. If it works correctly when driver is used directly, we can open this again.

**Comment by msudhayaraj** [comment]
> Knex is not doing the serialization from database types to javascript types. Please check how that works when you use node-oracledb driver directly without knex. If it works correctly when driver is used directly, we can open this again.

i am checked in direct oracledb , here also works same.I will raise the issue on oracledb. Thanks @elhigu
