### ISSUE TITLE
Incorrect type on table.text()

### ISSUE THREAD

**Issue by muametgrooby** [knex/knex#4116]
# Environment

Knex version: 0.21.12
Database + version: psql (PostgreSQL) 12.4
OS: Manjaro Linux x86_64

@lorefnon 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
When I'm using table.text() its asking for a string instead of string[]
http://knexjs.org/#Schema-text

2. Error message
error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string'.
![image](https://user-images.githubusercontent.com/42146933/98988098-6eee5f00-2527-11eb-9b6c-f6831c76a6e9.png)

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

`table.text("description", ["longtext"]).notNullable();`

**Comment by alexanderankin** [comment]
I believe that `[]` is just standard notation for optional parameter.

**Comment by kibertoad** [comment]
@alexanderankin Not in TypeScript. There it means an array.

**Comment by lorefnon** [comment]
I don't think there is any issue here. 

I think @alexanderankin was referring to this text in documentation: 

```
text — table.text(name, [textType])
```

where it is used to indicate that textType is optional. 

That method does not actually accept an array.

**Comment by kibertoad** [comment]
@lorefnon Thank you!
