### ISSUE TITLE
When acquiring a connection, run a 'SET' command

### ISSUE THREAD

**Issue by NelsonFrancisco** [knex/knex#4121]
# Environment

Knex version: 0.21.1
Database + version: postgres 12.1
OS: linux
Application: nodejs with koa

# Feature discussion / request

1. Explain what is your use case

I have a policy in each of the databases tables that filters the returned content on 'SELECT' queries, depending on the domain of the connection. I use a variable for this. The variable is set on the connection's session. 

Here's the query I run: 'SET session.domain_id=<some_integer>'

You can see that the variable name is 'domain_id'. The requirement is that EVERY query made to the database, must have 'domain_id' set.

I know that 'afterCreate' method can help here: after the pool creates a NEW connection, I can set the 'domain_id' variable. No problem here.

The limitation is that 'afterCreate' is not enough.

Picture this: two http requests hit the app at the same time. These two requests make queries to the db. If these requests share the same DB connection, the same 'domain_id' will be set for both requests, and that's the problem. For every request (ctx in koa) I need a different 'domain_id' for every query.

2. Explain what kind of feature would support this

Connection customization

3. Give some API proposal, how the feature should work

The ideal solution, would be something like, when creating knex instance:
```js
const conf
knex({
    client: 'pg',
    connection: {
        database:'postgres',
        user: 'postgres',
        host: 'postgres_host',
        port: 5432
    },
    pool: {
      afterAcquire: function (conn, ctx) {
        conn.query(`SET session.domain_id = ${ctx.domain_id}`, (err) => done(err, conn))
      },
    },
  })
```

As you can see, I would need a callback that got as an argument the request context.

This is just a proposal. If you know of any different solution for this problem, please let me know. I searched, and found nothing.

**Comment by elhigu** [comment]
I don't think knex should introduce this kind of hooks at least unless it is planned carefully what kind of hooks exactly are wanted and if they really are necessary. Async hooks are not always so simple when unexpected errors / other corner cases are happening. I'd rather leave implementing that kind of stuff for plugins / higher level libraries.

Effectively you need a feature, which allows one to first lease connection from pool and then allow passing multiple queries to the same connection (this feature has been requested multiple times).

Here is how currently one can request a connection with knex and send many queries to it: https://stackoverflow.com/a/59966900/360060

That should be enough to implement some framework to work with it. For example writing knex plugin, which implements suitable helpers, for executing query builder in with correct context. It will need some tuning to take account if that SET is already ran, when dealing with transactions, but generally it should be doable with knex extension APIs and with use of `.connection()`.
