### ISSUE TITLE
Distinct From support

### ISSUE THREAD

**Issue by t1a2l** [knex/knex#4133]
# Environment

Knex version: 0.20.10
Database + version: postgres 13.1
OS: ubuntu 20.04

# Feature request/Support

support for "distnict from" to deal with null values
where a is distinct from b 
I want to check if two column are different from each other, some columns may be null.
currnetly using db.raw, wanted to know if there was any feature/planned feature for that.
 
maybe use the opreator methid - Where(a, "distinct from', b).

**Comment by elhigu** [comment]
Please add complete example SQL that you are trying to generate?

**Comment by t1a2l** [comment]
example:
 "select count(id) 
  from imports, lines
  where imports.id = lines_imports_id
  and imports.first_row is distinct from lines.id"

first_row can sometimes be null and sometimes a number

**Comment by elhigu** [comment]
Looks like the postgresql is the only DB supporting "is distinct from" operator so this sounds like a case for `.whereRaw()`.

`.whereRaw('?? is distinct from ??', ['imports.first_row', 'lines.id'])`

**Comment by elhigu** [comment]
You can easily also extend knex to provide `.whereIsDistinctFrom()` method for your project.

**Comment by t1a2l** [comment]
Ok thank you

**Comment by vladshcherbin** [comment]
I'd second this feature.

My use case is to select rows where boolean is `null` or `true` (not `false`). Using `whereNot('column', false)` will produce `where not "column" = false` which won't return rows with a null value.

To overcome this issue, query has to be `where "column" IS NOT FALSE` or `where "column" IS DISTINCT FROM FALSE`.

I believe currently there is no method for this except `whereRaw` 😢
