### ISSUE TITLE
".returning() is not supported by mysql and will not have any effect." into migrations

### ISSUE THREAD

**Issue by williamdes** [knex/knex#4134]
Posted as https://github.com/knex/knex/issues/3158#issuecomment-732110110

https://github.com/knex/knex/search?q=.returning%28%29+is+not+supported+by+mysql+and+will+not+have+any+effect.

Here is my migration, I want it to run silently.
```ts
'use strict';

import * as Knex from 'knex';

exports.up = function (knex: Knex) {
  return knex
    .insert([
      {
        idType: 1,
        nomType: 'Midi',
      },
      {
        idType: 2,
        nomType: 'Soir',
      },
    ])
    .into('Types');
};

exports.down = function (knex: Knex) {
  return knex.delete('*').from('Types');
};
```

```
Using environment: test
  knex:tx trx2: Starting top level transaction +0ms
  knex:tx trx2: releasing connection +104ms
  knex:tx trx3: Starting top level transaction +139ms
.returning() is not supported by mysql and will not have any effect.
  knex:tx trx3: releasing connection +149ms
Batch 2 rolled back the following migrations:
20181110160827-data-types.ts
```

### The patch/hack

```ts
  development: {
    [...]
    log: {
      warn: (message) => {
        // Shut up https://github.com/knex/knex/issues/3158
        if (message === '.returning() is not supported by mysql and will not have any effect.') {
          return;
        }
        console.warn(message);
      },
    },
  },
```

**Comment by williamdes** [comment]
Done @elhigu 
https://github.com/knex/knex/issues/3158#issuecomment-732715095

**Comment by maximelkin** [comment]
unfortunately, the documentation does not describe the arguments of the .delete().
.delete accepts optional parameter `returning`, with behavior for `.delete(returning)` equivalent to `.delete().returning(returning)`

**Comment by elhigu** [comment]
Ah right... so the message was coming from migration code and not from knex's internals. Closing as it doesn't seem to be bug in migration system after all.
