### ISSUE TITLE
MIgrations and backup

### ISSUE THREAD

**Issue by skhekare** [knex/knex#4140]
# Environment

Knex version:0.19.5
Database + version: Postgres 12
OS: windows 10

# Bug

We want to backup and restore our postgres database. But our migration scripts or data might change. In that case is there any way to manage new changes in migration while keeping the old data in some tables or modifying the data from some tables to take care of new changes in migrations scripts.

**Comment by elhigu** [comment]
If you backup / restore DB, the state of migrations that has been ran to DB is also backed up. So when yo restore backup and run migrations, only the migrations that were created after backing up are ran.
