### ISSUE TITLE
Table creation fails when using sql_require_primary_key on MySQL

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#4141]
# Environment

Knex version: 0.21.12
Database + version: MySQL 8.0.20
OS: n/a (DigitalOcean Managed Database)

# Bug

When using a MySQL database with `sql_require_primary_key` enabled (as is the default on DigitalOcean's Managed Database service), the following fails:

```js
await knex.schema.createTable('example', (tableBuilder) => {
  tableBuilder.string('id', 64).primary();
});
```

with error:

```
Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
```

On further inspection, it seems like it's because of the fact that knex performs two queries for the above example:

```js
[
  {
    sql: "create table `example` (`id` varchar(64))",
    bindings: []
  },
  {
    sql: 'alter table `example` add primary key `example_pkey`(`id`)',
    bindings: []
  }
]
```

which explains the error, as we're trying to create the table without a primary key first, only to add it in a secondary query.

Knex should to generate 

```
create table `example` (`id` varchar(64) primary key)
```

instead of this 2-step setup in order to fix this issue I thinkg🤔 

(FWIW, the same issue applies when using `tableBuilder.primary()` instead of `columnBuilder.primary()`)

**Comment by rijkvanzanten** [comment]
Seems like Laravel ran into the exact same issue!

https://github.com/laravel/framework/issues/33238

**Comment by Paratron** [comment]
I just noticed the same problem when trying to connect a project to a MySQL 8 cluster when using sqlite locally before.

Like you noted above, the table is created without a key at first and the key is being added in a later command. The server refuses this.

By reading a bit of knex' source code I found out that there seem to be inconsistencies in the schema builder. If you call the `increments()` method  while creating a table, the primary key will be created upon table creation just fine. Only calling `primary` on your own will cause the error.

I found out you can work around this limitation for now by modifying your primary creation like this:

```
await knex.schema.createTable('example', (tableBuilder) => {
  tableBuilder.specificType('id', 'char(64) primary key');
});
```

**Comment by douglasjunior** [comment]
This is a very critical situation for us, as Digital Ocean's managed databases do not allow tables without a primary key. 

Our workaround is also: 

```js
tableBuilder.specificType('id', 'char(64) primary key');
```

**Comment by codestrong** [comment]
Same issue here. Using Directus.io (which uses knex) on DigitalOcean and MySQL 8. I hope this gets fixed soon.

**Comment by arladmin** [comment]
I've run into this issue as well.

Trying to access my DigitalOcean managed database, MYSQL 8, from a docker based Directus (v9.0.0-rc.86) instance.
Note: 
- I've edited DO's password encryption to ```Legacy – MySQL 5.x```
- Am passing the downloaded certificate via the ```DB_SSL__CA``` env parameter

Error received:
```
05:51:30 ✨ Initializing bootstrap...

05:51:30 ✨ Installing Directus system tables...


Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)

at Query.ErrorPacket (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)

at Protocol._parsePacket (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)

at Parser._parsePacket (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)

at Parser.write (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)

at Protocol.write (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)

at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:88:28)

at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:526:10)

at Socket.emit (node:events:394:28)

at addChunk (node:internal/streams/readable:312:12)

--------------------

at Protocol._enqueue (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)

at Connection.query (/directus/node_modules/mysql/lib/Connection.js:198:25)

at /directus/node_modules/directus/node_modules/knex/lib/dialects/mysql/index.js:126:18

at new Promise (<anonymous>)

at Client_MySQL._query (/directus/node_modules/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)

at executeQuery (/directus/node_modules/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)

at Client_MySQL.query (/directus/node_modules/directus/node_modules/knex/lib/client.js:134:12)

at Runner.query (/directus/node_modules/directus/node_modules/knex/lib/execution/runner.js:130:36)

at Runner.queryArray (/directus/node_modules/directus/node_modules/knex/lib/execution/runner.js:241:31)

at ensureConnectionCallback (/directus/node_modules/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19) {

code: 'UNKNOWN_CODE_PLEASE_REPORT',

errno: 3750,

sqlMessage: "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.",

sqlState: 'HY000',

index: 0,

sql: "create table `directus_collections` (`collection` varchar(64), `icon` varchar(30), `note` text, `display_template` varchar(255), `hidden` boolean not null default '0', `singleton` boolean not null default '0', `translations` json, `archive_field` varchar(64), `archive_app_filter` boolean not null default '1', `archive_value` varchar(255), `unarchive_value` varchar(255), `sort_field` varchar(64))"

}
```

How to resolve this?

**Comment by daniellockyer** [comment]
Heads up, I believe I have a solution for this - I hope to push a PR soon 🙂

**Comment by daniellockyer** [comment]
This issue should now be resolved, awaiting release 🙂

I'll be backporting it to 0.21 tomorrow for those of us stuck on old versions 😅

**Comment by kibertoad** [comment]
@daniellockyer I would suggest giving a shot to upgrading version used in bookshelf first. old knex is old.
will publish version shortly

**Comment by kibertoad** [comment]
Released in 1.0.3

**Comment by jonahweissman** [comment]
Should this documentation also be updated? https://docs.directus.io/getting-started/installation/digitalocean-app-platform/#_3-create-a-managed-database-instance

**Comment by jonahweissman** [comment]
Apologies, please disregard. I got confused about which repository this was in
