### ISSUE TITLE
Como resolver o erro NJS-044: bind object must contain one of the following keys: \"dir\", \"type\", \"maxSize\", or \"val\"

### ISSUE THREAD

**Issue by leomangueira** [knex/knex#4142]
# Environment

Knex version:
Knex CLI version: 0.21.6
Knex Local version: 0.21.6
Database + version: Oracle 11g
OS: Windows 10

Speak masters, I'm trying to do an InnerJoin relating two tables, but it is giving error NJS-044: link object must contain one of the following keys: "dir", "type", "maxSize", or "val"
This selection filters user 9's sales orders, in my IDE the SQL script generated by knex works normally.

# My connection to the BD:

```
const { O_DIRECTORY } = require("constants")

module.exports = {

  development: {
    client: 'oracledb',
    connection: {
      host: 'IP_SERVER',
      database: 'WINT',
      user:     'USERNAME',
      password: 'PASSWORD'  
    },
    pool: {
      min: 2,
      max: 10
    },
    migrations: {
      tableName: 'knex_migrations',
      directory: `${__dirname}/src/database/migrations`
    },
    seeds: {
      directory: `${__dirname}/src/database/seeds`
    }
  }
};
```

# Script Knex SQL Inner Join

```
const knex = require('../database')

module.exports = {
  async index(req, res, next) {
    try {
        const { CODUSUR } = req.query
        const query = knex('PCPEDC')

        if (CODUSUR) {
            query
            .where('PCPEDC.CODUSUR', { CODUSUR })
            .join('PCEMPR', //on
                  'PCPEDC.CODUSUR', '=', 'PCEMPR.CODUSUR')
            .select('PCPEDC.NUMPED', 'PCEMPR.MATRICULA')
        }
        const results = await query

        return res.query(results)
    } catch (error) {
        next(error)      
    }
    
  }
```
# Error to give in insomnia:

```
{
  "error": "select \"PCPEDC\".\"NUMPED\", \"PCEMPR\".\"MATRICULA\" from \"PCPEDC\" inner join \"PCEMPR\" on \"PCPEDC\".\"CODUSUR\" = \"PCEMPR\".\"CODUSUR\" where \"PCPEDC\".\"CODUSUR\" = :1 - NJS-044: bind object must contain one of the following keys: \"dir\", \"type\", \"maxSize\", or \"val\""
}
```

# Change in where

```
.where('PCPEDC.CODUSUR', {type: knex.DB_TYPE_NUMBER, CODUSUR })
```

# Console.log error

```
Builder [object] {
  client: Client_Oracledb {
    config: {
      client: 'oracledb',
      connection: [Object],
      pool: [Object],
      migrations: [Object],
      seeds: [Object]
    },
    logger: Logger {
      _inspectionDepth: 5,
      _enableColors: true,
      _debug: undefined,
      _warn: undefined,
      _error: undefined,
      _deprecate: undefined
    },
    connectionSettings: {
      host: 'IP_SERVER',
      database: 'WINT',
      user: 'USER',
      password: 'PASSWORD',
      fetchAsString: [Array]
    },
    connectionConfigExpirationChecker: null,
    fetchAsString: [],
    driver: OracleDb { queueTimeout: 60000, queueMax: 500 },
    pool: Pool {
      destroyed: false,
      emitter: [EventEmitter],
      creator: [AsyncFunction: create],
      destroyer: [Function: destroy],
      validate: [Function: validate],
      log: [Function],
      acquireTimeoutMillis: 60000,
      createTimeoutMillis: 30000,
      destroyTimeoutMillis: 5000,
      idleTimeoutMillis: 30000,
      reapIntervalMillis: 1000,
      createRetryIntervalMillis: 200,
      propagateCreateError: true,
      min: 2,
      max: 10,
      used: [],
      free: [],
      pendingCreates: [],
      pendingAcquires: [],
      pendingDestroys: [],
      pendingValidations: [],
      interval: null,
      eventId: 1
    },
    valueForUndefined: Raw [object] {
      client: [Circular],
      sql: 'DEFAULT',
      bindings: undefined,
      _wrappedBefore: undefined,
      _wrappedAfter: undefined,
      _debug: undefined
    },
    makeKnex: [Function: makeKnex],
    _events: [Object: null prototype] {
      start: [Function],
      query: [Function],
      'query-error': [Function],
      'query-response': [Function]
    },
    _eventsCount: 4
  },
  and: [Circular],
  _single: { table: 'PCPEDC', only: false },
  _statements: [
    {
      grouping: 'where',
      type: 'whereBasic',
      column: 'PCPEDC.CODUSUR',
      operator: '=',
      value: [Object],
      not: false,
      bool: 'and',
      asColumn: false
    },
    JoinClause {
      schema: undefined,
      table: 'PCEMPR',
      joinType: 'inner',
      and: [Circular],
      clauses: [Array],
      _boolFlag: 'and'
    },
    { grouping: 'columns', value: [Array] }
  ],
  _method: 'select',
  _debug: undefined,
  _joinFlag: 'inner',
  _boolFlag: 'and',
  _notFlag: false,
  _asColumnFlag: false
}
```

# Url used in insomnia to make the select:

http://localhost:3333/Pedidos?CODUSUR=9

Note: all help is welcome, I sought help on the stackoverflow but they were very arrogant with me, people there are not humble, since already I thank you for the help you may give me.

**Comment by leomangueira** [comment]
#Console.log 
Builder [object] {
  client: Client_Oracledb {
    config: {
      client: 'oracledb',
      connection: [Object],
      pool: [Object],
      migrations: [Object],
      seeds: [Object]
    },
    logger: Logger {
      _inspectionDepth: 5,
      _enableColors: true,
      _debug: undefined,
      _warn: undefined,
      _error: undefined,
      _deprecate: undefined
    },
    connectionSettings: {
      host: 'IP_SERVER',
      database: 'WINT',
      user: 'USER',
      password: 'PASSWORD',
      fetchAsString: [Array]
    },
    connectionConfigExpirationChecker: null,
    fetchAsString: [],
    driver: OracleDb { queueTimeout: 60000, queueMax: 500 },
    pool: Pool {
      destroyed: false,
      emitter: [EventEmitter],
      creator: [AsyncFunction: create],
      destroyer: [Function: destroy],
      validate: [Function: validate],
      log: [Function],
      acquireTimeoutMillis: 60000,
      createTimeoutMillis: 30000,
      destroyTimeoutMillis: 5000,
      idleTimeoutMillis: 30000,
      reapIntervalMillis: 1000,
      createRetryIntervalMillis: 200,
      propagateCreateError: true,
      min: 2,
      max: 10,
      used: [],
      free: [],
      pendingCreates: [],
      pendingAcquires: [],
      pendingDestroys: [],
      pendingValidations: [],
      interval: null,
      eventId: 1
    },
    valueForUndefined: Raw [object] {
      client: [Circular],
      sql: 'DEFAULT',
      bindings: undefined,
      _wrappedBefore: undefined,
      _wrappedAfter: undefined,
      _debug: undefined
    },
    makeKnex: [Function: makeKnex],
    _events: [Object: null prototype] {
      start: [Function],
      query: [Function],
      'query-error': [Function],
      'query-response': [Function]
    },
    _eventsCount: 4
  },
  and: [Circular],
  _single: { table: 'PCPEDC', only: false },
  _statements: [
    {
      grouping: 'where',
      type: 'whereBasic',
      column: 'PCPEDC.CODUSUR',
      operator: '=',
      value: [Object],
      not: false,
      bool: 'and',
      asColumn: false
    },
    JoinClause {
      schema: undefined,
      table: 'PCEMPR',
      joinType: 'inner',
      and: [Circular],
      clauses: [Array],
      _boolFlag: 'and'
    },
    { grouping: 'columns', value: [Array] }
  ],
  _method: 'select',
  _debug: undefined,
  _joinFlag: 'inner',
  _boolFlag: 'and',
  _notFlag: false,
  _asColumnFlag: false
}

**Comment by kibertoad** [comment]
Unfortunately, I don't speak Spanish. Could you please explain in English what the problem is?

**Comment by leomangueira** [comment]
> Infelizmente, eu não falo espanhol. Poderia explicar em inglês qual é o problema?

yes

**Comment by elhigu** [comment]
At least this part looks wrong:  `.where('PCPEDC.CODUSUR', { CODUSUR })`. You are trying to compare column to a javascript object there...

For future debugging try to simplify your queries and app so that you are able to pinpoint the exact part of the query that causes your problem. When you are able to figure out, which part of the query fails it is usually obvious to see what is the problem there.

**Comment by leomangueira** [comment]
Thanks, I found the problem, the correct one was: .whereIn ('PCPEDC.CODUSUR', CODUSUR)
