### ISSUE TITLE
Add support for WHERE clause to upsert 

### ISSUE THREAD

**Issue by markdboyd** [knex/knex#4145]
# Environment

Knex version: 0.12.12
Database + version: Postgres 10.7
OS: MacOS Catalina 10.15.7

# Feature discussion / request

1. Explain what is your use case

I am using the new "upsert" feature added in #3763, which works great! But using PostgreSQL, I need to add a WHERE clause to an "upsert" statement (ON CONFLICT ...), so that I can conditionally "upsert" only certain rows. 

I looked through the Github issues and through the #3763 PR which added support for "upsert" and it doesn't seem like this feature is currently supported.

The PostgreSQL documentation shows the syntax for using a WHERE clause in INSERT ... ON CONFLICT queries: https://www.postgresql.org/docs/10/sql-insert.html.

An example of how this feature is used: https://stackoverflow.com/questions/44571870/postgresql-on-conflict-with-a-where-clause

2. Explain what kind of feature would support this

Adding support for a WHERE clause to "upsert" statements (ON CONFLICT ...) in DB engines that support it would meet my needs.

3. Give some API proposal, how the feature should work

The PostgreSQL compiler (and perhaps MySQL/SQLite compilers?) needs to be updated to support a `.where` method after an `onConflict().merge()` chain.

For PostgreSQL at least, I think the changes would go somewhere around here:
https://github.com/knex/knex/blob/master/lib/dialects/postgres/query/compiler.js#L29

**Comment by kibertoad** [comment]
PR for this would be most appreciated!

**Comment by markdboyd** [comment]
OK, I will take a crack at implementing this. But I will definitely need guidance around the tests

**Comment by kibertoad** [comment]
@markdboyd Sure, would be my pleasure! If you have Docker set up, you can use `npm run db:start:postgres` to prep DB, then you can run `cross-env DB=postgres npm run test:db` to execute them just on Postgre. In order to run specific test or suite, use `describe.only`/`it.only`. Let me know if you'll have any questions :)

**Comment by markdboyd** [comment]
@kibertoad I created PR #4148 to add this functionality for PostgreSQL. Let me know if it looks like I'm on the right track and if so I'll add the same functionality for SQLite.
