### ISSUE TITLE
Can't connect to OracleDB using host+port combo

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#4146]
# Environment

Knex version: 0.21.12
Database + version: OracleDB (any)
OS: any

# Bug

When connecting to an OracleDB database using a combination of host+port, Knex isn't able to acquire the connection (fails with `ORA-12170: TNS:Connect timeout occurred`) This is most likely because of:

https://github.com/knex/knex/blob/073df48cc6f31ba0ea1f732341d15b631fe1d386/lib/dialects/oracledb/index.js#L99-L101

I believe changing `client.connectionSettings.host + '/' + client.connectionSettings.database` to `client.connectionSettings.host + ':' + client.connectionSettings.port + '/' + client.connectionSettings.database` might do the trick 

Ref https://github.com/directus/directus/issues/3266

**Comment by kibertoad** [comment]
Can you add (failing) reproduction test for this?

**Comment by rijkvanzanten** [comment]
Connecting using 

```
const knex = require('knex');

const database = knex({
  client: 'oracledb',
  connection: {
    host: 'your-oracle-host',
    port: 12345,
    (user creds + db)
  }
});
```

should cause this to show up

@yapnel could you confirm the connection settings you were using?
