### ISSUE TITLE
Add New Dynamic Join Method

### ISSUE THREAD

**Issue by callmedavron** [knex/knex#4150]
# Environment

Knex version: 0.21.6
Database + version: Postgres 12
OS: MacOs Catalina

**First, I want to express my gratitude for such a useful library Knex.**

# Feature discussion / request

1. Explain what is your use case

Hi i am using knex a lot, in my cases i need use leftJoin or innerJoin in same query, by some case i need use leftJoin by another case i need use innerJoin. I mean something like for dynamic join

For example

```
  let query = knex.select(['u.username', knex.raw("array_agg('b.name') as books")])
                              .from('users as u')

  if(ignoreBooksExist) {
    query = query.leftJoin('books as b', 'b.uploaded_by', 'u.id')
  } else {
    query = query.join('books as b', 'b.uploaded_by', 'u.id')
  }

  const result = await query; // my books list
```

2. Explain what kind of feature would support this
Adding new **joinMethod** with feature for setting join type by property

3. Give some API proposal, how the feature should work
**For example .joinByType('join type e.g. left, inner', ...)**

```
const query = knex.select(['u.username', knex.raw("array_agg('b.name') as books")])
                                  .from('users as u')
                                  .joinByType(ignoreBooksExist ? 'left' : 'inner', // Condition for use inner or left join
                                                      'books as b', 'b.uploaded_by', 'u.id')

const result = await query; // my books list
```

**Comment by caseywebdev** [comment]
You can actually do this with JS alone!

```js
if (ignoreBooksExist) {
  query = query.leftJoin('books as b', 'b.uploaded_by', 'u.id')
} else {
  query = query.join('books as b', 'b.uploaded_by', 'u.id')
}
```

is equivalent to

```js
query[ignoreBooksExist ? 'leftJoin' : 'join']('books as b', 'b.uploaded_by', 'u.id');
```

Since `queryBuilder` objects are mutable, there's no need to reassign `query`.

**Comment by callmedavron** [comment]
@caseywebdev Great. Thank you.

**Comment by callmedavron** [comment]
By the way if someone need this you can use this trip.

```
return knex.select(..)
           .from(...)
           ['leftJoin'](...all join conditions)
           // the same thing
           // .leftJoin(...all join conditions)
```
