### ISSUE TITLE
Bug: programmatic migrate does not support ESM

### ISSUE THREAD

**Issue by SnirShechter** [knex/knex#4159]
# Environment

Knex version: **0.21.13**
Database + version: **postgres:latest**
OS: **Windows**

# Bug

The migrations cli works great with ESM: `npx knex migrate:up --esm`

However, when running the migration programmatically, there is no option to pass --esm, which results in an error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\...\20201213230932_migration.ts
require() of ES modules is not supported.
```

### index.js
```
import knex from 'knex'

const pg = knex({
	client: 'pg',
	connection: {
		host: 'localhost',
		port: 5432,
		user: 'postgres',
		password: 'postgres',
		database: 'postgres',
	},
})
await pg.migrate.latest()
```

### migrations/20201213230932_migration.js
```
import Knex from 'knex'

export async function up(knex: Knex): Promise<void> {
}

export async function down(knex: Knex): Promise<void> {
}

```

### package.json
```
{
  "type": "module"
}
```

Run node index.js

**Comment by kibertoad** [comment]
Released in 0.21.14
