### ISSUE TITLE
Knex without await doesn't execute query

### ISSUE THREAD

**Issue by GeraldHost** [knex/knex#4163]
# Questions about knex

I'm trying to understand how the await keyword works in KNEX. Take the following example:
```
knex.schema.createTable( ... );
```
It will not execute the create table query in the database. However if I stick and await in front of it.
```
await knex.schema.createTable( ... );
```
This will now execute the create query in the database.

My understanding is that await is used to wait for a promise resolution but in this case it feels like something else is going on because not awaiting the function doesn't return a promise. 

Should the code that isn't using `await` still be executing the query?

PS: sorry if this is not the most appropriate to ask here but I've have no luck asking anywhere else 😇

**Comment by TrySound** [comment]
knex chain returns thenable. `then` method call starts query. `await` is just a syntax sugar on top of promises/thenables.
```
knex.schema.createTable( ... ).then(() => {})
```

**Comment by kibertoad** [comment]
@TrySound is correct. `knex.schema.createTable( ... );` returns a Promise-like, that can be either await'ed or consumed within `then` chain.

**Comment by GeraldHost** [comment]
Thanks for your replies. Hmm that makes sense. I guess it's the implementation that I can get my head around. Is there a place in the code you could link me to to see this in more detail? I've looked at the createTable method for the MySQL dialect and it just seems to push items into sequence and doesn't actually return anything? 

When we use the `await` keyword is it calling the `then` method defined in interface.js?

This is what has confused me 😂😇

**Comment by kibertoad** [comment]
`Is there a place in the code you could link me to to see this in more detail?`

Sure, for an example: https://github.com/knex/knex/blob/master/test/integration/schema/foreign-keys.js

`When we use the await keyword is it calling the then method defined in interface.js?`

This is correct.
