### ISSUE TITLE
Typings of aggregate functions (count, max etc.) are missing options object ("as" alias)

### ISSUE THREAD

**Issue by tkalliom** [knex/knex#4165]
# Environment

Knex version: 0.21.13
Database + version: N/A
OS: N/A

Issue is about TypeScript definitions, @lorefnon 

# Bug

As stated in the documentation, `count`, `min` etc. take an optional options object, with the key `as` specifying an alias for the aggregate value. However, the types `AsymmetricAggregation` and `TypePreservingAggregation` only have the `...columnNames` parameter; the options object is missing from the typings.

**Comment by kibertoad** [comment]
@tkalliom Would you be open to sending a PR for this?

**Comment by kibertoad** [comment]
Released in 0.95.7
