### ISSUE TITLE
Problem with onConflict + merge

### ISSUE THREAD

**Issue by ncsft** [knex/knex#4174]
# Environment

Knex version: 0.21.12
Database + version: postgesql 12
OS: all

# Bug
Error when 33k+ parameters

```
error: insert into "bug_table" ("id", "value") values ($1, $2), (...) on conflict ("id") do update set "id" = excluded."id", "value" = excluded."value" - bind message has 464 parameter formats but 0 parameters
```

```
    const rows = [];
    for (let i = 0; i < 33000; i++) {
      rows.push({ id: i, value: i });
    }
    await knex.table('bug_table')
      .insert(rows)
      .onConflict('id')
      .merge();
```
Table definition
```
CREATE TABLE "public"."bug_table" (
    "id" int4 NOT NULL,
    "value" int4 NOT NULL,
    PRIMARY KEY ("id")
);
```

**Comment by kibertoad** [comment]
@ncsft Are you sure this is not a driver limitation? Can you try running same statement directly using `pg` library in Node.js?

**Comment by ncsft** [comment]
> @ncsft Are you sure this is not a driver limitation? Can you try running same statement directly using `pg` library in Node.js?

No. Thats works fine
```
knex.raw(
      knex.table('bug_table').insert(rows).toQuery() + ' ON CONFLICT (id) DO UPDATE SET ' +
      Object.keys(rows[0]).map(field => `${field}=EXCLUDED.${field}`).join(', ')
    );
```

**Comment by kibertoad** [comment]
@ncsft Thanks, I'll take a look. Appreciate the repro!

**Comment by kibertoad** [comment]
It stops working at 32768 elements, so it really looks like a 16-bit integer overflow somewhere, but I am yet to find where.

**Comment by kibertoad** [comment]
@ncsft 
Having investigated further, I believe this is not an issue on knex's behalf. There is a difference between the two queries that you have provided - native knex one in the end passes two params to `pg`:

*  `text` with the value `insert into "merge_table" ("id", "value") values ($1, $2), ($3, $4), ($5, $6), ($7, $8), ($9, $10), ($11, $12), ($13, $14), ($15, $16), ($17, $18), ($19, $20), ($21, $22), ($23, $24) <...>on conflict ("id") do update set "id" = excluded."id", "value" = excluded."value"` 
* `values` with the value `Array(65536) [0,0,1,1,2,2 <...>]`,

while `knex.raw` that you used inlines everything:
* `text` = `insert into "merge_table" ("id", "value") values (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9) ON CONFLICT (id) DO UPDATE SET id=EXCLUDED.id, value=EXCLUDED.value`

Second one works, first one does not, and it really looks like https://github.com/brianc/node-postgres/issues/581
This should be fixed on `pg` end (if at all possible), the recommended course of action would be to raise an issue in https://github.com/brianc/node-postgres and provide a full pg-only repro for it.

**Comment by charmander** [comment]
The 16-bit parameter count is a PostgreSQL limit, not a pg one. I recommend static queries with [array parameters + `UNNEST`](https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050) or [JSON parameters + `jsonb_to_recordset`](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-PROCESSING-TABLE), but other workarounds like preformatted queries are also listed in the linked issue.

**Comment by kibertoad** [comment]
@charmander Thanks a lot for the clarification!

**Comment by elhigu** [comment]
> The 16-bit parameter count is a PostgreSQL limit, not a pg one. I recommend static queries with [array parameters + `UNNEST`](https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050) or [JSON parameters + `jsonb_to_recordset`](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-PROCESSING-TABLE), but workarounds like preformatted queries are also listed in the linked issue.

Typings is a problem with both of the workarounds, so there is no generic way to apply them.
