### ISSUE TITLE
where clause character issue

### ISSUE THREAD

**Issue by bny64** [knex/knex#4184]
# Environment

Knex version:
oracle + 0.21.15:
OS: window

Select applicable template from below.
If issue is about oracledb support, tag @dweinand dweinan

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

A bug was detected when querying the Oracle database using knex.
When I typed characters in a where clause, there is no problem when I typed over two characters, but type just one character, it doesn't work normally.

My code is as follows.

const db2 = require('knex')(my options);
db2.transaction(async trx => {
    try {
        const result = await trx.raw('SELECT a.name, a.age, b.clsname FROM TEST1 a JOIN TEST2 b ON a.name = b.name WHERE b.clsname = ?', 'A');
    } catch (e) {
        console.error(e);
    }
})

Even though There is data that is A with clsname column, but The knex module does not find the data.
Please, check the issue.
Thanks.

**Comment by kibertoad** [comment]
@bny64 I think this is an Oracle, not a knex limitation. You can try running same query directly on the Oracle driver, it should work the same. If it does not, please reopen the issue and we'll look into it further.
