### ISSUE TITLE
Support for MSI for MSSQL/Tedious

### ISSUE THREAD

**Issue by wjohnsto** [knex/knex#4198]
@smorey2 

1. Explain what is your use case

  node-mssql/tedious support MSI through an "authentication" option. It doesn't look like that is possible using the MSSQL client with knex.

2. Explain what kind of feature would support this

  I believe the only thing necessary to make this work is adding the ability to send the authentication configuration parameter in with your database config. Happy to submit a PR if necessary.

**Comment by kibertoad** [comment]
@wjohnsto Doesn't knex pass-through everything in `connection` parameter directly to the driver? What is missing currently? That said, would be happy to accept a PR that would amend the situation and update typings as well.

**Comment by wjohnsto** [comment]
Hmm, nevermind you are absolutely correct. I was having an issue, turns out it is not related to this. Closing, thanks!
