### ISSUE TITLE
Sqlite drop composite foreign keys

### ISSUE THREAD

**Issue by schmetzyannick** [knex/knex#4201]
# Environment

Knex version: 0.21.15
Database: Sqlite3
OS: Win10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do:

   When calling the dropForgin key method an error is throw. The problem seems to be located in the dropForeign function of 
   the following file: lib/dialects/sqlite3/schema/ddl.js.
   In the method the statement is splitted by coma which results in problems for composite foreign keys.
   
2. Error message:
  `TypeError: Cannot read property '1' of null`

**Comment by kibertoad** [comment]
@schmetzyannick Could you please share reproduction code?

**Comment by schmetzyannick** [comment]
This should help

            const db = knex({
                useNullAsDefault: true,
                client: 'sqlite3',
                connection: {
                    filename: "./mydb.sqlite"
                },
                pool: {
                    afterCreate: (conn, cb) => conn.run("PRAGMA foreign_keys = ON", cb),
                },
                acquireConnectionTimeout: 900000,
            });
            db.schema.createTable("first", (table) => {
                table.string("col1");
                table.string("col2");
            }).then(() => {
                db.schema.createTable("second", (table) => {
                    table.string("col1");
                    table.string("col2");
                    table.foreign(["col1", "col2"]).references(["col1", "col2"]).inTable("first");
                }).then(() => {
                    db.schema.alterTable("second", (table) => {
                        table.dropForeign(["col1", "col2"]);
                    }).then(() => {
                        console.log("ok!");
                    }).catch((e) => {
                        console.log(e);
                    });
                });
            });

**Comment by kibertoad** [comment]
Thanks, I'll take a look.

**Comment by schmetzyannick** [comment]
I already started to fix the issue by writing a test. Now I will have a closer look to the dropForeign function.
