### ISSUE TITLE
Add support for subqueries in the join clause

### ISSUE THREAD

**Issue by mgummelt** [knex/knex#4206]
# Environment

Knex version: 0.21.12
Database + version: mysql 8.0
OS: ubuntu 20.04

# Feature discussion / request

1. Explain what is your use case

I would like to construct this query:

```
SELECT years.id AS year
   FROM companies
   LEFT JOIN years ON years.id == (
     SELECT years.id
     FROM years
     WHERE years.company_id == companies.id AND years.year == 2019
     LIMIT 1)
```

2. Explain what kind of feature would support this

A `join` interface that supports either a `QueryBuilder` or a `QueryCallback` in the join clause.

As far as I can tell, no existing interface does so, making the above query impossible to write without resorting to raw strings.

**Comment by elhigu** [comment]
Can be done with usual tricks of passing query builder instead of string literal to join... Had to add `knex.raw()` to make query builder to be interpolated inside parenthesis. 

```
knex('companies')
  .select('years.id as year')
  .leftJoin(
    'years',
    'years.id',
    knex.raw('(??)', [knex('years').select('years.id')
      .where('years.company_id', knex.ref('companies.id'))
      .where('years.year', 2019)
      .limit(1)])
  ).toSQL()
```

https://runkit.com/embed/cru2twc56ue8
