### ISSUE TITLE
Feature request:  Added functionality for onConflict / upsert query building (PostgresSQL) 

### ISSUE THREAD

**Issue by dgurr** [knex/knex#4209]
# Environment

Knex version: 0.21.12
Database + version: PostgresSQL

# Feature discussion / request

1. I am running into what I think is a limitation of the `onConflict`.  In PostgresSQL I want to do an batch upsert like ...
```
knex('tableName')
  .insert(
    { email: "john@example.com", name: "John Doe", occupation: "dev" },
    { email: "jane@example.com", name: "Jane Doe", occupation: "doctor" },
    { email: "alex@example.com", name: "Alex Doe", occupation: "dentist" },
  )
  .onConflict('email')
  .merge(['email', 'name'])
``` 

and have the generated sql be like: 

```
'insert into "tableName" ("email", "name", "occupation", "relationships") values (?, ?, ?) on conflict ("email") do update set "email" = excluded."email", "name" = excluded."name"
```

Right now this is not possible AFAICT, and it's frustrating because the only option is a full merge, but I just want to trim off the extra clause that would be included `"occupation" = excluded."occupation"`.  The optional data param that can be passed to merge works if its a upsert of a single row, but is insufficient for this batch scenario 

2. Explain what kind of feature would support this

For PostgresDB at least, support passing in an array to merge.  Or have a method like `mergeFields` that accepts an array and is only available for certain dbs, similar to how chaining the WHERE clause after merge is itself specific to certain dbs. 

3. Give some API proposal, how the feature should work
```
knex('tableName')
  .insert(
    { email: "john@example.com", name: "John Doe", occupation: "dev" },
    { email: "jane@example.com", name: "Jane Doe", occupation: "doctor" },
    { email: "alex@example.com", name: "Alex Doe", occupation: "dentist" },
  )
  .onConflict('email')
  .mergeFields(['email', 'name'])
``` 

generates: 

```
'insert into "tableName" ("email", "name", "occupation", "relationships") values (?, ?, ?) on conflict ("email") do update set "email" = excluded."email", "name" = excluded."name"
```

**Comment by kibertoad** [comment]
Would you like to send a PR for this?

**Comment by dgurr** [comment]
> Would you like to send a PR for this?

Sure, I'll see if I can create something this week.

**Comment by elhigu** [comment]
Would :

```
  .onConflict('email').merge([ 'email', 'name' ])
```

be basically just syntactic sugar for:

```
  .onConflict('email').merge({ email: knex.ref('excluded.email') , name: knex.ref('excluded.name') })
```

?

**Comment by MattGson** [comment]
@elhigu In some ways yes, in others, not really.

` .onConflict('email').merge([ 'email', 'name' ])` is database agnostic.
` .onConflict('email').merge({ email: knex.ref('excluded.email') , name: knex.ref('excluded.name') })` works for pg and sqlite but not for MySQL.

For MySQL, we would have to change it to:
`.onConflict('email').merge({ email: knex.ref('values(email)') , name: knex.ref('values(name)') })`

So in a sense, it is syntactic sugar but by that logic, so is all of knex other than `knex.raw`
