### ISSUE TITLE
Salvar em mais de uma tabela em uma mesma requisição

### ISSUE THREAD

**Issue by luismanoel12** [knex/knex#4226]
`const bcrypt = require('bcrypt-nodejs')

module.exports = app => {
    const { existsOrError, notExistsOrError, equalsOrError } = app.api.validation

    const ecryptPassword = password => {
        const salt = bcrypt.genSaltSync(10)
        return bcrypt.hashSync(password, salt)
    }

    const save = async (req, res) => {
        const user = { ...req.body }           // Posso criar duas variaveis para 
        const endereco = { ...req.body }  // receber a requisição ou não precisa 
        if(req.params.id) user.id = req.params.id

        if(!req.originalUrl.startsWith('/users')) user.admin = false
        if(!req.user || !req.user.admin) user.admin = false

        try {
            existsOrError(user.name, 'Nome não informado')
            existsOrError(user.email, 'E-mail não informado')
            existsOrError(user.telefone, 'Telefone não informado')
            // existsOrError(user.cpf, 'CPF não informado')
            existsOrError(user.password, 'Senha não informada')
            existsOrError(user.confirmPassword, 'Confirmação da senha inválida')
            equalsOrError(user.password, user.confirmPassword, 
               'Senhas não conferem')

            existsOrError(endereco.endereco, 'Endereço não informado')
            existsOrError(endereco.numero, 'Número não informado')
            existsOrError(endereco.complemento, 'Complemento não informado')
            existsOrError(endereco.bairro, 'Bairro não informado')
            existsOrError(endereco.estado, 'Estado não informado')
            existsOrError(endereco.cidade, 'Cidade não informado')
            existsOrError(endereco.cep, 'CEP não informado')

               const userFromDB = await app.db('users')
                    .where({ email: user.email }).orWhere({ cpf: user.cpf }).orWhere({ cnpj: user.cnpj }).first()
                if(!user.id){
                    notExistsOrError(userFromDB, 'E-mail, CPF ou CNPJ já cadastrados')
                }

        }catch(msg){
            return res.status(400).send(msg)
        }

        user.password = ecryptPassword(user.password)
        delete user.confirmPassword

        if(user.id){
            app.db('users')
                .update(user)
                .where({ id: user.id })
                .whereNull('deletedAt')
                .then(_ => res.status(204).send())
                .catch(err => res.status(500).send(err))
        }else{

              app.db("users")
                .insert({ name: user.name, email: user.email, telefone: user.telefone, cpf: user.cpf, cnpj: user.cnpj, password: user.password, ong: user.ong, admin: user.admin, enderecoSaved: user.enderecoSaved })
                .returning('id')
                .then(function (response) {
                app.db('endereco')
                    .insert({endereco: endereco.endereco, numero: endereco.numero, complemento: endereco.complemento, bairro: endereco.bairro, estado: endereco.bairro, cidade: endereco.cidade, cep: endereco.cep, userId: user.id })
            });

        }
    }`

**Comment by elhigu** [comment]
Knexiä koskevan käyttökysymykset tulisi tehdä gitter chatissa tai stackoverflowssa. Myöskaan issue templatea ei ole noudatettu. Suljen foorumisääntöjen vastaisena postauksena.
