### ISSUE TITLE
Liftoff in dependency

### ISSUE THREAD

**Issue by anupvarghese** [knex/knex#4227]
# Environment

Knex version: 0.21.15

# Issue

I saw this [PR](https://github.com/knex/knex/pull/4122) for dropping liftoff as a dependency from knex. I tried adding the new version in my project and I can see `liftoff` is still listed as a dependency. 

![image](https://user-images.githubusercontent.com/4844577/104530951-3242ff00-5661-11eb-9085-05f7a08026d8.png)

**Comment by kibertoad** [comment]
@anupvarghese It is currently only available in master. Version 0.95.0 is likely to come out somewhere in February, but if it is crucial for you, I can publish a preview version on npm.

**Comment by anupvarghese** [comment]
@kibertoad Liftoff exposes a [vulnerability](https://github.com/npm/ini/commit/56d2805e07ccd94e2ba0984ac9240ff02d44b6f1) from an old version of `ini` package used under the hood. It was fixed in ini but never updated in liftoff. 

I can still add a resolution to fix this problem and wait till the major release. 

thank you

**Comment by Vaclovas** [comment]
Why this issue is closed?

**Comment by TrySound** [comment]
@Vaclovas Not an issue. Just wait until next release.

**Comment by Vaclovas** [comment]
Why this is not an issue if knex uses dependency with critical vulnerability and there is no proper release currently? The solution to adjust package-lock.json is more like a hack.

**Comment by anupvarghese** [comment]
@Vaclovas the vulnerability is in `ini` package, which has been fixed already.
If you add a resolution block in `package.json` it will refer the patched version in package.lock or yarn.lock

This is what I have done.
```
 "resolutions": {
    "ini": "1.3.8"
 },
```
Specific to this version, it is not going to break anything as it only avoids prototype pollution. 
It would be a better solution than patching in `package.lock` directly.

**Comment by kibertoad** [comment]
@Vaclovas master is not yet ready for a full public release. As I've mentioned before, I can do a preview release if there is demand for it.

**Comment by Vaclovas** [comment]
Sorry, for being picky, but I don't understand, why close an issue if it is not fixed. I totally understand, that this is a dependency issue, but it would be good to see, that issue is still not resolved and the fix is on the go because now the situation is misleading, people can think, that issue is fixed and they have a problem elsewhere, but this is not the case.

**Comment by kibertoad** [comment]
Fix was released in 0.95.0
