### ISSUE TITLE
Where clause kept across chained query promises

### ISSUE THREAD

**Issue by lmmattr** [knex/knex#4242]
# Environment

Knex version: 0.21.16
Database + version: postgres 10
OS: Debian stretch

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Where clause appears to be retained after execution into the following query

2. Error message

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
  const knex = Knex.connection(await db.connect())

  return getUser(db, guid)
  .then(user => {
    return knex
    .select()
    .from("roles")
    .where("id", user.role_id)
    // .then((...args) => console.log(1, ...args))
  })
  .then(userRole => {
    console.log(2, userRole)
    console.log(3, knex.select().table("users").whereNot("id", "17"))
  })
```
Gives me
```
2 [
  {
    id: 3,
    label: 'Admin'
  }
]
3 Builder [object] {
  client: Client_PG {
    ...
  },
  ...
  _statements: [
    {
      grouping: 'where',
      type: 'whereBasic',
      column: 'id',
      operator: '=',
      value: 3,
      not: false,
      bool: 'and',
      asColumn: false
    },
    {
      grouping: 'where',
      type: 'whereBasic',
      column: 'id',
      operator: '=',
      value: '17',
      not: true,
      bool: 'and',
      asColumn: false
    }
  ],
  ...
}
```

**Comment by elhigu** [comment]
Seems to work as expected.

**Comment by lmmattr** [comment]
@elhigu, thank you for your concise response. It appears we have different expectations. 

If I've executed the query, why are the parameters retained? 
Do I have to clear the class somehow to reuse it?
Do I have to create multiple Knex instances to run multiple queries?

**Comment by elhigu** [comment]
This is your problem I suppose:

```
const knex = Knex.connection(await db.connect())
```

You are expecting that it creates a knex instance with single connection, but  seems like you just create a query builder instance.

`.connection` method is designed to be used for single knex query builder instances... not for creating new knex query builder factory (like const knex = require('knex')({ client: 'pg' }))

Basically you are doing this:

```
const knex = require('knex')({ client: 'pg' });

const query = knex.connection(await db.connect());

const firstResult = await query.select().from("roles").where("id", user.role_id);
const secondQuery = await query.select().table("users").whereNot("id", "17");

```

**Comment by lmmattr** [comment]
Ah ok. That makes some sense. Thank you for your help.
