### ISSUE TITLE
knex.raw returns promise

### ISSUE THREAD

**Issue by tarunsinghh** [knex/knex#4262]
# Environment

Knex version:0.20.13
Database + version: pg 12
OS: ubuntu

can i use the below code 0.20.13
        promises.push( db.raw('SELECT 1'));
then using await Promise.all(promises) where promises is an array 
in the webstorm debugger it is showing it as an raw object not promise also i tried below its not going inside then nor inside catch

 db.raw('SELECT * from school_event_mapping limit 1').then((row)=>{
         console.log('koknnoko',row.rows);
         }
     ).catch((e)=>{
         console.error('error--catc',e);
     });

so does knex.raw() returns promise here db = require('nex')({config})

**Comment by kibertoad** [comment]
@tarunsinghh Check the documentation for `raw`, you would typically use it as a parameter inside more typical query-building structure: https://knexjs.org/#Raw

**Comment by tarunsinghh** [comment]
@kibertoad  iam making a healthcheck api,how do i then write select 1 in knex that will return promise

**Comment by tarunsinghh** [comment]
also @kibertoad  The knex.raw may also be used to build a full query and execute it, as a standard query builder query would be executed. The benefit of this is that it uses the connection pool and provides a standard interface for the different client libraries.

knex.raw('select * from users where id = ?', [1]).then(function(resp) { ... });,   so what Iam doing wrong

**Comment by kibertoad** [comment]
@tarunsinghh Probably you are not awaiting your promise or something along these lines. I just tried 
```
    const x = knex.raw('SELECT * from school_event_mapping limit 1').then((row)=>{
        console.log('koknnoko',row.rows);
      }
    ).catch((e)=>{
      console.error('error--catc',e);
    });
```

and `x` is definitely a Promise there. Do you instantiate `db` correctly?

**Comment by kibertoad** [comment]
@tarunsinghh You can use heartbeat util from here, if you want: https://github.com/kibertoad/knex-utils/blob/master/lib/heartbeat.utils.js

**Comment by tarunsinghh** [comment]
@kibertoad 

My problem is :-
I am writing a healthcheck api , i have a function

function check() {
try {
info = await healthCheck()
} catch (error) {
logger('healthcheck failed', error)
return sendFailure(res, { error: error.causes })
}
return sendSuccess(res, { info, verbatim: healthChecks.verbatim })
}
}

and in healthcheck function Iam performing certain checks like pinging mongo, postgres, redis and it looks like

function healthcheck() {

let promises = [];

 promises.push(mongoConnection.command({ping: 1})); // this is a promise,working fine 
 promises.push(db.raw('select 1'));  // have doubt on this whether db.raw('select 1') is promise or not
 promises.push(redis.client.ready === true ? Promise.resolve('redis connected') : Promise.reject(new Error('not ready'))); //working fine

 return Promise.all(promises);
}

so my whole doubt is on the line promises.push(db.raw('select 1')); whether db.raw('select 1') is a promise or not, if not what change i will have to do in the above code to make it work ?
