### ISSUE TITLE
knex.raw('select 1') doesnt return promise

### ISSUE THREAD

**Issue by tarunsinghh** [knex/knex#4263]
Knex version:0.20.13
Database + version: pg 12
OS: ubuntu

can i use the below code 0.20.13
promises.push( db.raw('SELECT 1'));
then using await Promise.all(promises) where promises is an array
in the webstorm debugger it is showing it as an raw object not promise also i tried below its not going inside then nor inside catch

db.raw('SELECT 1').then((row)=>{
console.log('koknnoko',row.rows);
}
).catch((e)=>{
console.error('error--catc',e);
});

so does knex.raw() returns promise here db = require('knex')({config})

according to @kibertoad   raw is used inside more typical query building strcuture but in same documentation we can write full query also using raw, so what iam doing wrong if iam executing a querry, houldnt it return a promise? please dont close the issue without solving @kibertoad

**Comment by elhigu** [comment]
It doesn't return a Promise. It does return a query buider that is thenable. 

You can return promise by executing the raw query builder for example by calling it' s `.then()` method, which returns a promise.

**Comment by tarunsinghh** [comment]
@elhigu  

My problem is :-
I am writing a healthcheck api , i have a function 

function check() {
 try {
          info = await healthCheck()
        } catch (error) {
          logger('healthcheck failed', error)
          return sendFailure(res, { error: error.causes })
        }
        return sendSuccess(res, { info, verbatim: healthChecks.verbatim })
      }
}


and in healthcheck function Iam performing certain checks like pinging mongo, postgres, redis and it looks like

function healthcheck() {

let promises = [];

     promises.push(mongoConnection.command({ping: 1})); // this is a promise,working fine 
     promises.push(db.raw('select 1'));  // have doubt on this whether db.raw('select 1') is promise or not
     promises.push(redis.client.ready === true ? Promise.resolve('redis connected') : Promise.reject(new Error('not ready'))); //working fine

     return Promise.all(promises);


}

so my whole doubt is on the line promises.push(db.raw('select 1'));  whether db.raw('select 1') is a promise or not, if not what change i will have to do in the above code to make it work ?

**Comment by elhigu** [comment]
Problem in your code is not knex.  If you want to be sure that you are waiting for promise, just do:

```
promises.push(db.raw('select 1').then());
```

also duplicate issue...
