### ISSUE TITLE
TypeScript example in readme doesn't work

### ISSUE THREAD

**Issue by bluenote10** [knex/knex#4264]
This is a super tiny issue, and most likely highly trivial to fix. But since I only had a few seconds look into knex, I can't fix it myself and thought I can at least leave a short report: The example fails at the `import { Knex, knex } from 'knex'`, apparently because the library has changed to default exports.

**Comment by kibertoad** [comment]
@bluenote10 This is accurate for master; we just need to release next semver major soon :)
