### ISSUE TITLE
build INSERT INTO table SELECT ...

### ISSUE THREAD

**Issue by bblack** [knex/knex#427]
Is there a way to build such a query in knex? I think this syntax is postgres-specific, but the operation isn't. For example, duplicating one or more rows of a table:

```
INSERT INTO votes SELECT * FROM votes WHERE id = 99;
```

**Comment by koistya** [comment]
@tgriesser how to execute a query similar to:
```sql
INSERT INTO table (col1)
SELECT (:col1)
WHERE NOT EXISTS (SELECT 1 FROM table WHERE col1 = :col1)
```
Knex binds only the second `:col1` parameter.

**Comment by elhigu** [comment]
@koistya seems to work with knex.raw

https://runkit.com/mikaelle/58f750ea718530001238757e/branches/master

How are you getting your error?
