### ISSUE TITLE
Pool uses mssqlPoolSettings as opposed to user input

### ISSUE THREAD

**Issue by davidchai717** [knex/knex#4274]
# Environment

Knex version: "knex": "^0.21.16"
Database + version: "mssql": "^6.3.1",
OS: Mac OSX

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
@smorey2 
# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
We have been running into issues with SQL resource overload ever since we updated to newer versions of msSql and Knex. After inspecting the pool event logs, we noticed that both min and max are set to 1, and idleTimeoutMillis is set to an astonishingly high value. We then realized that these values are both taken from "this.mssqlPoolSettings" in the source code instead of the options we had put into the "pool" property in the Knex config.

2. Error message
Not an actual error, but here's the config outputted by the Tarn event:
```
{
  database: 'XXX',
  server: 'XXX',
  password: 'XXX',
  user: 'XXX',
  pool: { min: 1, max: 1, idleTimeoutMillis: 9007199254740991 },
  port: 000,
  options: {},
  stream: false,
  parseJSON: false,
  arrayRowMode: false
}
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.
```
{
  const config =  {
    client: 'mssql',
    connection: {
      database: 'XXX',
      user: 'XXX',
      password: 'XXX,
      server: 'XXX'
    },
    pool: {
      min: 0,
      max: 10,
      idleTimeoutMillis: 5000,
      acquireTimeoutMillis: 30000,
      createTimeoutMillis: 30000,
      reapIntervalMillis: 1000,
      createRetryIntervalMillis: 500,
    },
    acquireConnectionTimeout: 10000,
  };
 const testVal = await knex(config)
.select('XXX')
.from('XXX');
```

**Comment by kibertoad** [comment]
@davidchai717 We plan to release a first preview version of 0.95.0 that completely reworks the MSSQL driver soon, addressing this issue among many others. It should be fully production-ready, and mostly misses one breaking change for SQLite migrations. Would you be open to testing it to provide early feedback on whether there are any observable issues or gaps with the new driver?

**Comment by kibertoad** [comment]
Anyone willing to help with the testing of the new MSSQL driver (which should be more performant and stable than ever before), please give `0.95.0-next1` a shot! Final 0.95.0 version should be released at some point in February.

**Comment by jeremy-w** [comment]
i'm not seeing an `mssqlPoolSettings` in the codebase any more, so i reckon this one's fixed?
