### ISSUE TITLE
Is Raw type missing in onIn JoinClause ?

### ISSUE THREAD

**Issue by qchapelet** [knex/knex#4285]
# Environment

Knex version: 0.21.6
Knex types version: 0.16.1
Database + version: mssql 6.2.3

# Feature discussion / request

I want to perform a subquery with an `in` operator like so
```sql
SELECT * FROM myTable JOIN myOtherTable on myOtherTable.myField IN ( mySubQuery )
```

Actually, I have found how to do it but it's not clear since i'm forcing `unknow` cast :

```typescript
.leftJoin('myOtherTable ', function (this: Knex.JoinClause) {
      this.onIn(
        'myOtherTable.myField',
        (db.raw(
          '(mySubQuery)',
        ) as unknown) as string[],
      )
    })
```

The expected type of `onIn` values is `any[]`. So I'm wondering why I have to cast it as `unknow` and if i could have done it in another way ? Is `Raw`  type missing in the expected values ?

Thanks

@lorefnon

**Comment by kibertoad** [comment]
Released in 1.0.1.
