### ISSUE TITLE
Timeout on Node 15

### ISSUE THREAD

**Issue by keyserfaty** [knex/knex#4290]
# Environment

Knex version: "knex": "^0.21.17"
Database + version: "pg": "^8.5.1"
Node.js: v15.8.0
OS: macOS Big Sur. (Apple M1/Sillicon).

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Not receiving connections.

2. Error message
`Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.
This is a problem that I have when running Node 15 (working fine on another machine running Node 12). I've read that it was suggested to others that they go back to Node 12 and pg 7 but since I'm in a Macbook with M1 I can't do that (Node 12 won't work).
Any workaround?

**Comment by joseph-naked** [comment]
Hi @keyserfaty 

Why did you close this ticket?

I am also facing the same issue. Did you manage to resolve it?

**Comment by elhigu** [comment]
@joseph-naked It is most probably caused by code that doesn't use transactions correctly. Try to create minimal reproduction code, which still triggers the problem and then it should be easy to see what was wrong,

**Comment by samermurad** [comment]
Just in case some other devs land on this ticket, the problem is actually the `pg` client npm and not `knex`, and has more to do with node versions than the m1 arch, see more here: https://github.com/brianc/node-postgres/issues/2413.

Long story short, Node ≥ 14 requires pg ≥ 8.

I hope this shortens your search, whoever you are 🍻  cheers
