### ISSUE TITLE
Github releases and git tags not in sync with published npm releases.

### ISSUE THREAD

**Issue by markwongsk** [knex/knex#4291]
1. The latest release published on npm is marked 13 days ago at 0.21.17: https://www.npmjs.com/package/knex.
2. The latest release on github and on the website is tagged 0.21.15 on 12/26/2020.
3. When checking out the code, there is no git tag marking 0.21.17.

**Comment by kibertoad** [comment]
Thanks for noticing! Published a new tag.
For curiosity sake, what are you using tags for?

**Comment by markwongsk** [comment]
Was going to checkout code locally based on some version.

**Comment by kibertoad** [comment]
Got it!
