### ISSUE TITLE
Migration files out of order due to using local timezones

### ISSUE THREAD

**Issue by unfinishedteleporter** [knex/knex#4294]
# Environment

Knex version:^0.21.16
Database + version: Postgresql 12
OS: Ubuntu Linux

Experience level: Just starting with knex.

I couldn't find an existing issue on this topic, but I feel like there is a reason this hasn't been implemented / I've missed something.

# Feature discussion / request

1. Explain what is your use case
Working with a team on a repository across multiple timezones, that uses knex migration files.

2. Explain what kind of feature would support this
`knex make` using UTC, rather than local timezone.

3. Give some API proposal, how the feature should work
Add configuration option to knex that allows the `yyyymmddhhmmss()` function in [timestamp.js](https://github.com/knex/knex/blob/master/lib/migrations/util/timestamp.js) to use getUTCDate() etc functions.

## Reasoning
Currently it uses the local timezone to generate the migration file's names. This causes issues when working in a repository across multiple timezones.

Right now I'm the only one of my team in a different timezone, so I'm just creating my filenames to match theirs so the ordering is correct. Would love to hear other solutions from anyone else who has run into same issue.

**Comment by elhigu** [comment]
I think there was a pull request trying to implement this.

**Comment by unfinishedteleporter** [comment]
> I think there was a pull request trying to implement this.

Oh, you are absolutely right: https://github.com/knex/knex/pull/4245

**Comment by kibertoad** [comment]
Will try to write a test for it today, merge and release a new preview version.

**Comment by kibertoad** [comment]
Released in 0.95.0-next2
