### ISSUE TITLE
mssql: schema builder: Enable specifying the name for a column's default constraint

### ISSUE THREAD

**Issue by jeremy-w** [knex/knex#4297]
# Environment

Knex version: knex@0.21.12 
Database + version:
> Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) 
> Sep 23 2020 16:03:08 
> Copyright (C) 2019 Microsoft Corporation
> Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>
OS: Docker under macOS

For MSSql tag @smorey2.

# Feature discussion / request

1. Explain what is your use case

It's much easier to work with a database with predictable constraint names. Since SQL Server has stuck with treating column defaults as constraints, I'd like to be able to easily control the name it assigns those constraints. Example DDL for [creating a column with a named default constraint](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-default-values-for-columns?view=sql-server-ver15#TsqlProcedure) is:

```sql
create table [NamedDefaultConstraint] (
  name varchar(max)
    not null
    constraint [ConstraintNameGoesHere]
      default 'your guess is as good as mine'
)
```

2. Explain what kind of feature would support this

The extension point that jumps out at me is [`column.defaultTo`](https://knexjs.org/#Schema-defaultTo) on the column builder. It could be extended with an optional second argument, making it `column.defaultTo(value, [constraintName])`, to parallel [`primary()`](https://knexjs.org/#Schema-primary).

3. Give some API proposal, how the feature should work

If the optional argument is not provided, the existing behavior would continue.

If provided, then `constraint [UserProvidedName]` should be injected before the `default (value)` bit when creating a table.

**Comment by kibertoad** [comment]
@jeremy-w Considering that we already do that for most constraints, adding that for `defaultTo` should be pretty straightforward. Would you be open to send a PR for this?

**Comment by jeremy-w** [comment]
Glad to hear that's the way to go. I'm open to it; hopefully in the next fortnight. 🤞

**Comment by kibertoad** [comment]
Would be awesome!

**Comment by jeremy-w** [comment]
Trying to get a clean test run to start, but I'm not having much luck. The connection config appears to be getting ignored by some parts of the test suite? Is it expected that the KNEX_TEST config does not work, or should I maybe fix that first?

I already happen to have mssql running in Docker for my own dev purposes, so I wanted to use my existing container when running tests.

## What I'm Seeing
I'm seeing two flavors of test failure. Here are the flavors and an example failure for each class.

Flavor 1: undefined `client`

```
  1) Query Building Tests
       knex
         transaction
           propagates error correctly when all connections are in use:
     TypeError: Cannot read property 'client' of undefined
      at resolveConfig (lib/knex-builder/internal/config-resolver.js:20:20)
      at Knex (lib/knex-builder/Knex.js:10:39)
      at Context.<anonymous> (test/unit/knex.js:388:20)
      at processImmediate (internal/timers.js:461:21)
```

Flavor 2: Wrong connection info used (custom config ignored)

```
  20) Insert
       onConflict merge
         mssql
           "before each" hook for "inserts large amount of entries correctly":
     ConnectionError: Login failed for user 'XXXXX USER XXXXX'.
      at ConnectionError (node_modules/tedious/lib/errors.js:13:12)
      at Parser.<anonymous> (node_modules/tedious/lib/connection.js:1166:51)
      at Parser.<anonymous> (node_modules/tedious/lib/token/token-stream-parser.js:35:14)
    …(eliding the middle - it's all internal to the stream handling stuff, no test functions in stack)…
      at Socket.ondata (internal/streams/readable.js:719:22)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

## Setup
I've provided a config file with my mssql config info in ../knexTestConfig.js:

```js
// Custom test config. Supply abspath as value of KNEX_TEST env var when running knex tests.
const mssql = {
  user: 'sa',
  password: 'REDACTED',
  server: 'localhost',
  port: 1433,
  database: 'knex_test'
}

// Remember to create the knex_test db!
/*
create database knex_test
go
*/

module.exports = {
  mssql
}
```

I then run the test suite using `KNEX_TEST="$PWD/../knexTestConfig" DB=mssql npm t`

## Investigation
After a few failed runs, I went and munged the info around where I was seeing the 21433 port in the connection config:

```diff
diff --git a/scripts/stress-test/knex-stress-test.js b/scripts/stress-test/knex-stress-test.js
index 2b8ff4cd..2dae94a9 100644
--- a/scripts/stress-test/knex-stress-test.js
+++ b/scripts/stress-test/knex-stress-test.js
@@ -31,7 +31,7 @@ const mssql = Knex({
   client: 'mssql',
   connection: {
     port: 21433,
-    user: 'sa',
+    user: 'ARSTARSTASRT',
     password: 'S0meVeryHardPassword',
     server: 'localhost',
     requestTimeout: 500,
diff --git a/test/integration2/util/knex-instance-provider.js b/test/integration2/util/knex-instance-provider.js
index 96b9e01e..947022a8 100644
--- a/test/integration2/util/knex-instance-provider.js
+++ b/test/integration2/util/knex-instance-provider.js
@@ -106,10 +106,10 @@ const testConfigs = {
   mssql: {
     client: 'mssql',
     connection: {
-      user: 'sa',
+      user: 'XXXXX USER XXXXX',
       password: 'S0meVeryHardPassword',
       server: 'localhost',
-      port: 21433,
+      port: 1433,
       database: 'knex_test',
     },
     pool: pool,
diff --git a/test/knexfile.js b/test/knexfile.js
index f085e09c..717b7130 100644
--- a/test/knexfile.js
+++ b/test/knexfile.js
@@ -7,6 +7,8 @@ const testConfig =
   (process.env.KNEX_TEST && require(process.env.KNEX_TEST)) || {};
 const _ = require('lodash');
 
+console.log('TEST CONFIG:', testConfig);
+
 // excluding redshift, oracle, and mssql dialects from default integrations test
 const testIntegrationDialects = (
   process.env.DB || 'sqlite3 postgres mysql mysql2 mssql oracledb'
@@ -139,7 +141,7 @@ const testConfigs = {
       user: 'sa',
       password: 'S0meVeryHardPassword',
       server: 'localhost',
-      port: 21433,
+      port: 1433,
       database: 'knex_test',
     },
     pool: pool,
```

The username strings shown in the test failures indicate that knex-stress-test is not being run, but knex-instance-provider at test/integration2/util is (it has my `XXXXX USER XXXXX` in the connection failed error), and further, that it is using its hardcoded test user rather than the one provided by the file in KNEX_TEST. This is in contrast to connection-config-provider at test/integration/ (no `2`), which _does_ use the test config I've provided.

Fixing integration2 to use the same config logic as integration1 should fix the failed connect calls (what i called flavor 2). I'm not sure what's triggering the "no client" issue.

**Comment by kibertoad** [comment]
@jeremy-w `TypeError: Cannot read property 'client' of undefined` is happening because `parsedConfig` is nil, which is resolved like this.
Most common reason for this is a mismatch between driver name passed and expected, but if you are using `mssql` as a driver name, that should work. If you could push your branch, I could take a look.

**Comment by jeremy-w** [comment]
The errors appeared on a fresh checkout of master - c58794b2ad “Prepare to release 0.95.0-next3”. I did npm install, then tried to run the tests as described. No changes yet outside the config file and patch I shared - I was trying to verify I had a working local test rig before I started changing anything.
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by jeremy-w** [comment]
Other config details: node version v14.15.4 with npm 6.14.10.

**Comment by kibertoad** [comment]
@jeremy-w Considering that CI on master is green, must be some local fluctuation, probably not even worth investigating unless there will be CI failures for the PR.

**Comment by jeremy-w** [comment]
I’ll try running with a more CI-like config then. 👍🏽 I need to start with a clean slate so I can know anything broken is my fault. 😂 
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by jeremy-w** [comment]
Got to green:

- Updated that integration2 file to respect the KNEX_TEST config.
- Updated my mssql knex_test DB config to match that established in the Docker file. The bits I was missing before were `ALTER DATABASE knex_test SET ALLOW_SNAPSHOT_ISOLATION ON; ALTER DATABASE knex_test SET DELAYED_DURABILITY = FORCED`. (I think it's only the "allow snapshot isolation" that was required, but the other probably improved test speed.) (Maybe the relevant tests should skip if snapshot isolation isn't allowed, or flip it on themselves as part of the test run?)
- Set `DB='mssql sqlite3'` rather than just mssql. This is needed because the config file the CLI tests relies on only exports the config for the supplied DBs, but then the CLI test tries to use the sqlite3 config. If you don't include sqlite3 in the DB list, it finds no sqlite3 config. (Probably that config file should always export the sqlite3 config?)

**Comment by jeremy-w** [comment]
@dhensby Thanks for your work on supporting setting the constraint name for `defaultTo`! Looking forward to the next release! 🎉

**Comment by dhensby** [comment]
Ah, I hadn't seen this issue at all, or realised you were working on it. Sorry @jeremy-w if that meant any wasted time for you. Glad we've got it in, though!
