### ISSUE TITLE
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full.

### ISSUE THREAD

**Issue by tsothcott** [knex/knex#4299]
# Environment

Knex version: 0.21.17
Database + version: MySQL 8.0.20
Node Version: 14.15.4
OS: Unsure - Digital Ocean database droplet 1 GB RAM / 1vCPU / 10 GB Disk / Primary only

@atiertant 

Edit: Node 12.13.0 LTS works fine.

# Bug

I am trying to do a basic query against a MySQL database, The code is:

                const db = require("knex")({
                    client: 'mysql',
                    connection: {
                        host : 'XXXXXXXX.db.ondigitalocean.com',
                        port: 25060,
                        user : 'XXXXX',
                        password : 'XXXXXXX',
                        database : 'monitors',
                        pool: {
                            max: 100,
                            min: 0,
                            idle: 200000,
                            acquire: 1000000,
                        },
                        ssl: true
                    }
                });

                var a= db.select("id").from("stores").first().then((data) => {
                    var b = data;
                })

However, I get the following error when trying to run the code:

```
(node:30060) UnhandledPromiseRejectionWarning: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_MySQL.acquireConnection 

```

**Comment by elhigu** [comment]
You should not pass cool parameters to mysql driver. 

Try this instead:

```
            const db = require("knex")({
                client: 'mysql',
                connection: {
                    host : 'XXXXXXXX.db.ondigitalocean.com',
                    port: 25060,
                    user : 'XXXXX',
                    password : 'XXXXXXX',
                    database : 'monitors',
                    ssl: true
                },
                pool: { min: 0, max: 100 }
            });
 ```
