### ISSUE TITLE
How can I user bindings inside a knex.raw with LIKE condition

### ISSUE THREAD

**Issue by ytaborda17** [knex/knex#4303]
# Environment

Knex version: 0.21.17
Database + version: MySql v5.7
OS: Ubuntu 20.04.0 LTS

# Bug

1. Current behiviour Vs. espected:
I'm trying to get an sql query with this syntax:

```
let data = knex.from('tarea')
.select(
  'tarea.*', 
  'tarea_tipo_solicitud.descripcion as tipo_solicitud', 'tarea_tipo_solicitud.id_area', 'tarea_area.descripcion as area'
)
.join('tarea_tipo_solicitud', { 'tarea.id_tipo_solicitud': `tarea_tipo_solicitud.id` })
.join('tarea_area', { 'tarea_tipo_solicitud.id_area': `tarea_area.id` });

...

if (params.conditions) {
  data.where(knex.raw("titulo LIKE '%?%' and id_area = ?", ['daily', 1]));
}
```

2. And as espected, I get the error message
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'daily'%' and id_area = 1  order by `id` desc limit 10' at line 1

error.sql: 
```
select `tarea`.*, `tarea_tipo_solicitud`.`descripcion` as `tipo_solicitud`, `tarea_tipo_solicitud`.`id_area`, `tarea_area`.`descripcion` as `area` 
from `tarea` 
inner join `tarea_tipo_solicitud` on `tarea`.`id_tipo_solicitud` = `tarea_tipo_solicitud`.`id` 
inner join `tarea_area` on `tarea_tipo_solicitud`.`id_area` = `tarea_area`.`id` 
where titulo LIKE '%'daily'%' and id_area = 1  order by `id` desc limit 10
```

What I get from this, is that we can't use bindings with a LIKE condition inside a knex.raw, I'm I correct?

If that's the case, what can I do to acomplish this query? I'm not able to use the normal .like() method, because as you can guess, the complete where clause comes as a string from an external method.

Any help will be welcomed!

**Comment by elhigu** [comment]
```
 data.where(knex.raw("titulo LIKE ? and id_area = ?", ['%daily%', 1]));
 ```
