### ISSUE TITLE
On delete CASCADE - Cannot add foreign key constraint

### ISSUE THREAD

**Issue by cajlonbatista** [knex/knex#4305]
![image](https://user-images.githubusercontent.com/63024734/108594012-29c39f80-7356-11eb-9036-619855480c12.png)

![image](https://user-images.githubusercontent.com/63024734/108593960-a904a380-7355-11eb-84bc-cb247d444b28.png)
Hi
Good Morning
For some reason I am not able to run this migration, with some foreign keys, I already checked and issue #245 , but the problem still persists on the console. If you can help me, thank you in advance :D

**Comment by elhigu** [comment]
That error is coming from database, check your schema why that query fails. maybe there is no `code` column in table `product`
