### ISSUE TITLE
Feature request: `findInBatches`

### ISSUE THREAD

**Issue by jtomaszewski** [knex/knex#4311]
Would you be interested in adding a function like `findInBatches` or something? That would return an `AsyncIterable` that lets one iterate over all the rows, with the knex querying the rows in bulks of `n` rows to avoid the `n+1` query problem. 

We've made some basic implementation of that already here: https://github.com/ailohq/knex-utils/blob/master/src/knex-utils/findInBatches.ts . I could make a PR that would add it directly to knex. (If only there's a green light from you guys on this.)

Inspired by:
- https://hexdocs.pm/ecto/Ecto.Repo.html#c:stream/2
- https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_in_batches

Related:
- https://github.com/typeorm/typeorm/issues/6837

**Comment by elhigu** [comment]
Function will create multiple queries from a single query builder, which is against one of knex's base design principles (we have already broke that rule couple of time, which I regret). 

Also there is no reason why this kind of complicated higher level functionality should be in knex core. I would suggest to implement and keep its development in a separate npm-module and we can mention it in knex plugins / utilities documentation.

It can be even hosted under knex project in github if you are willing to be its maintainer (these things tend to have lots of issue reports even when implementation is seemingly simple and straightforward).

Sounds like a useful thing to have though, just not in the knex core library.

**Comment by jtomaszewski** [comment]
I see, you have good reasons against accepting this. I understand. Thanks for the detailed response.

For now we'll keep it in the library of ours: https://github.com/ailohq/knex-utils/blob/master/src/knex-utils/findInBatches.ts . It's published to npm as `@ailo/knex-utils`, so if anybody wants to use that, or maybe even improve that, feel invited. We use knex quite heavily in our projects, so we'll probably be maintaining it for some time. ;)

**Comment by kibertoad** [comment]
@jtomaszewski If you feel like collaborating upstream, we have started https://github.com/knex/knex-utils a while ago, we could merge the two.
