### ISSUE TITLE
Preventing negative `offset` by default

### ISSUE THREAD

**Issue by aghArdeshir** [knex/knex#4335]
# Environment

Knex version: 0.21.17
Database + version:  `~#: mysql --version -> mysql  Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) using readline 6.3`
OS: Debian

# Bug

1. I mistakenly set a negative offset:
  ```ts
// ...
 page(page: number = 1) {
    const offset = (page - 1) * this.limit;
    this.query.offset(offset);
  }
   ```
I mistakenly passed `0` to this function, and my query became: 
`select * from `` order by `Time` desc limit 20 offset -20`

2. Error message
![Screenshot from 2021-03-03 11-34-10](https://user-images.githubusercontent.com/5755214/109775581-e9e29f00-7c16-11eb-846c-3833ca20a200.png)
(sorry for the blue marks)

3. Reduced test code:

```ts
import Knex from 'knex';

const knexConnection = Knex({
  client: 'mysql',
  connection: {
    host: '', //...
    user: '', //...
    password: '', //...
    database: '', //...
  },
});
const query = knexConnection('test').limit(20).offset(-20);
```

I believe if no negative offset is allowed in mysql query, the knex query-builder should prevent it. (instead of letting the error happen and generated by mysql)

If it is knex that should implement this, and this is known as fix that needs to be done in knex, I'd love to contribute to code.

**Comment by kibertoad** [comment]
@Ardeshir81 Considering that error thrown by driver in this case is pretty confusing, I think throwing an explicit error from Knex would be an improvement. PR would be most appreciated.

**Comment by Ardeshir81** [comment]
That's good news @kibertoad . I'll start working on it. I'll ask your help if I had problem understanding things.

**Comment by Ardeshir81** [comment]
I'm only familiar with `mysql`. Is negative offset invalid for all databases?

**Comment by aghArdeshir** [comment]
I will close this issue as I think it is resolved now @kibertoad
