### ISSUE TITLE
Unable to use most Knex types with my TypeScript code due to their not being exported

### ISSUE THREAD

**Issue by jeremy-w** [knex/knex#4337]
# Environment

Knex version: 0.95.0

Updating from: 0.21.12, where the code shown later did work.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

The types in typings should be exported so they can be used in applying types to code using Knex.

2. Error message

A config builder function declared like so:

```ts
const knexConfig = (
  {
    RDS_DB_NAME,
    RDS_USERNAME,
    RDS_PASSWORD,
    RDS_HOSTNAME,
    RDS_PORT,
    source,
  } = configFromEnv()
): Knex.Config<Knex.MsSqlConnectionConfig> => ({
// …config options here…
})
```

Fails to compile with `tsc` due to Knex.Config and Knex.MsSqlConnectionConfig not being exported:

```
TSError: knexfile.ts:50:9 - error TS2694: Namespace '"/foo/node_modules/knex/types/index".Knex' has no exported member 'Config'.

50 ): Knex.Config<Knex.MsSqlConnectionConfig> => ({
           ~~~~~~
knexfile.ts:50:21 - error TS2694: Namespace '"/foo/node_modules/knex/types/index".Knex' has no exported member 'MsSqlConnectionConfig'.

50 ): Knex.Config<Knex.MsSqlConnectionConfig> => ({
                       ~~~~~~~~~~~~~~~~~~~~~
```

I attempted a workaround, but then run into issue reassuring the `knex` function that the argument is the expected type, since I can't `as Knex.Config` either:

```
TSError: knexfile.ts:91:40 - error TS2694: Namespace '"foo/node_modules/knex/types/index".Knex' has no exported member 'Config'.

91   const knex = knexCtor(config as Knex.Config)
                                          ~~~~~~
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

This should do it. I couldn't find an online runner for TypeScript that'd let me import a module, but drop this in a TS project:

```ts
import knex, { Knex } from 'knex'

const config: Knex.Config = {}
```

It will error with something like:

```
TSError: knexfile.ts:9:20 - error TS2694: Namespace '"foo/node_modules/knex/types/index".Knex' has no exported member 'Config'.

9 const config: Knex.Config = {}
                     ~~~~~~
```

I expect the fix is basically to run through the typings files and stick `export` in front of a lot of `interface` and `type` decls, but the details of TypeScript typings are not my strong suit, so there might be a less verbose way.

I think 177938afeb2abf7d952f4a16b5a7cde213ab0c17 is where the exports changed.

(Ping @lorefnon for typings.)

**Comment by kibertoad** [comment]
Taking a look now!

**Comment by kibertoad** [comment]
@jeremy-w Which TypeScript version are you using?

**Comment by jeremy-w** [comment]
Version 4.0.5

**Comment by kibertoad** [comment]
See UPGRADING.md for migration guide - `TypeScript version 4.1+ is needed`. I think that should resolve your problem!

**Comment by jeremy-w** [comment]
I'll give that a shot and let you know. :)

**Comment by kibertoad** [comment]
Thanks!

**Comment by jeremy-w** [comment]
That seems to have done it. Past the typings issue to the [tedious issue](https://github.com/tediousjs/tedious/issues/377).

**Comment by kibertoad** [comment]
@jeremy-w If it's currently impossible to pass the necessary param to Tedious through knex, please raise an issue for us!

**Comment by jeremy-w** [comment]
Must be something else than that config flag - using `tedious` directly connects fine, but i'm hitting the error as described there - same error, different cause, presumably. If it boils down to a knex issue, i'll let you know. Thanks for your help!

**Comment by kibertoad** [comment]
happy to help! if you manage to resolve the issue, please post here too, most likely other users will encounter same problem.

**Comment by jeremy-w** [comment]
@kibertoad OK, I figured it out. I'll need to file a bug and an enhancement request.

## BUG: duplicate connect: use on('connect') not connect()
First off: The TDS_VERSION was a red herring. The version being used was fine, which my test directly using tedious confirmed.

The issue instead is an illegal state operation. The connection failure is due to knex triggering connect when a connect is already in flight. tedious begins connecting the moment its Connection is constructed. knex then calls connect() again; this doesn't trip a state machine transition, so the event that arrives when the second connection succeeds catches tedious unawares, and it blows up. This is visible in this debug logging; the tell is that "TDS-DEBUG: connected to localhost:1433" shows up twice, the second time being just before everything goes boom:

```
> DEBUG='knex:*' node build/t_knex.js
  knex:mssql connection::connection new connection requested +0ms
  knex:mssql XXX: OK, calling connect now! +11ms
TDS-DEBUG: connected to localhost:1433
TDS-DEBUG:   PreLogin - version:0.0.0.1 1, encryption:0x02(NOT_SUP), instopt:0x00, threadId:0x00000000, mars:0x00(OFF)
TDS-DEBUG: State change: Connecting -> SentPrelogin
TDS-DEBUG: 
TDS-DEBUG: Sent
TDS-DEBUG:   type:0x12(PRELOGIN), status:0x01(EOM), length:0x0035, spid:0x0000, packetId:0x01, window:0x00
TDS-DEBUG:   0000  00001F00 06010025 00010200 26000103 00270004 04002B00 0106002C 0001FF00  .......%....&... .'....+. ...,....
  0020  00000100 01020000 00000000 01  ........ .....
TDS-DEBUG: connected to localhost:1433
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: No event 'socketConnect' in state 'SentPrelogin'
    at Connection.dispatchEvent (REDACTED/node_modules/tedious/lib/connection.js:1282:26)
    at Connection.socketConnect (REDACTED/node_modules/tedious/lib/connection.js:1304:10)
    at REDACTED/node_modules/tedious/lib/connection.js:1146:12
    at Socket.onConnect (REDACTED/node_modules/tedious/lib/connector.js:106:7)
    at Socket.emit (events.js:314:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1131:10)
Emitted 'error' event on Connection instance at:
    at Connection.dispatchEvent (REDACTED/node_modules/tedious/lib/connection.js:1282:12)
    at Connection.socketConnect (REDACTED/node_modules/tedious/lib/connection.js:1304:10)
    [... lines matching original stack trace ...]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1131:10)
```

The anticipated fix is not to call `connection.connect`, but instead to register an `on` listener for the `connect` event, as shown in the first JS sample at https://www.microsoft.com/en-us/sql-server/developer-get-started/node/mac/step/2.html.

## ER: emit tedious debug output when in debug mode
knex already interprets the `debug: true` knex config into tedious's `debug: { turn on all the things }` config option. but it then doesn't actually register an on('debug') handler, so none of the debugging output requested is ever output!

the debug output you see in my logs above came from me dropping this one-liner into acquireRawConnection():

```
      connection.on('debug', (msg) => {console.log('TDS-DEBUG:', msg)})
```

most likely we'd want to use `debug` rather than `console.log`, but you get the idea. ;)

---

All that sorting done, I actually won't be able to adopt the newer tedious-based knex till tedious supports using UTF-8 collations with varchar, as tracked by https://github.com/tediousjs/tedious/issues/1143 With the older driver, I was able to register a mapping from string to varchar rather than nvarchar trivially:

```
knex.client.driver.map.register(String, mssql.VarChar) // Default `string` type to `varchar`
```

apparently, this is not only not trivial with tedious, it's entirely unsupported as of now. >.<

**Comment by kibertoad** [comment]
@tylerjwatson Could you take a look at last comment?

**Comment by tylerjwatson** [comment]
Holy moly, there is a _lot_ of stuff in that comment. 

1) Am I right in assuming there's a connection issue in mssql?  I haven't been able to reproduce anything of that sort.

2) I am not familiar with `driver.map` and haven't implemented anything of that sort in mssql tedious, can I please get some help outlining that mechanism?

3) The debug thing I can do.

**Comment by tylerjwatson** [comment]
@jeremy-w are you able to provide a minimal reproducible sample so I can test what I am fixing is working?

**Comment by tylerjwatson** [comment]
Upon further investigation, Microsoft's own sample at https://www.microsoft.com/en-us/sql-server/developer-get-started/node/mac/step/2.html doesn't work.  It's not possible to avoid calling `.connect()` in tedious, and that pattern is used everywhere in tedious' own samples.

**Comment by jeremy-w** [comment]
Hmm. I ran that first sample, and it connected successfully. Which is a useful tell.

I now suspect I somehow wound up with an older Tedious package: There was a breaking change on 13 January https://github.com/tediousjs/tedious/commit/16b10bf0f01d998de3aadfac2e2794d20aed4775#diff-a6be0583428e46844273df76939f02077073da3075716fc57d291a5f2463eaf5 that moved from autoconnect on construction to waiting for the caller to initiate the connection.

I’m curious how that happened with version constraints, and if they maybe need bumping to prevent that.

I’ll have a look when I next can. (Probably by Wednesday at latest, but I might get a few minutes to nose around this weekend.)

Thanks for your help!
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by jeremy-w** [comment]
Confirmed Knex 0.95.0 has a peer dep constraint of ^11.0.3 https://github.com/knex/knex/blob/0.95.0/package.json#L60 and the Tedious breaking change happened in v10.0.0 https://github.com/tediousjs/tedious/releases/tag/v10.0.0 so I’m at a loss for how I wound up with new Knex and old Tedious installed without npm yelling at me. But that appears to be the root of my issue.

I hope this helps anyone else running into this issue.

**Comment by tylerjwatson** [comment]
@jeremy-w Perfect! I'm glad the fix was a simple one.

**Comment by jeremy-w** [comment]
That’s what’s odd: It was installed (I ran the Microsoft sample code), but it was _old._ Missing would have been obvious; version-incompatible was a total surprise to me!
