### ISSUE TITLE
Strange version number

### ISSUE THREAD

**Issue by opravil-jan** [knex/knex#4340]
Hi,

the new version number 0.95.0 is correct version number or it is mistake and will be changed soon? 

Thanks

**Comment by kibertoad** [comment]
Pretty intentional! It is supposed to be the last major version prior to 1.0.0, and numbering is intended to highlight that.

**Comment by opravil-jan** [comment]
Ok. Thanks for explanation.

**Comment by vladshcherbin** [comment]
Such versioning is just confusing and insane 😕

**Comment by elhigu** [comment]
@vladshcherbin it did get your attention though, so seems like it did what it was meant to do. Insane is pretty strong word to describe it 😕
