### ISSUE TITLE
Auth error with current user

### ISSUE THREAD

**Issue by manbomb** [knex/knex#4342]
# Environment

Knex version: 0.21.2
Database + version: postgres 12.5
pg pakage on node: 4.5.5
OS: ubuntu

# Bug

When I try to run `npx knex migrate:latest` I have this error response:

````
> migrations@1.0.0 start /home/ubuntu/sing-migrations-be
> knex migrate:latest

Using environment: development
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
error: password authentication failed for user "ubuntu"
    at Connection.parseE (/home/ubuntu/sing-migrations-be/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/ubuntu/sing-migrations-be/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/ubuntu/sing-migrations-be/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! migrations@1.0.0 start: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the migrations@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-04T10_16_49_854Z-debug.log

```

This is my knexfile.js:

````
module.exports = {
  development: {
    client: 'pg',
    connection: {
      host: process.env.HOST,
      database: process.env.DB,
      user: process.env.USER,
      password: process.env.PASS
    },
    migrations: {
      tableName: 'knex_migrations',
      directory: `${__dirname}/database/migrations`
    }
  }
};
```

**Comment by kibertoad** [comment]
Judging by the error, password is wrong. Try using debugger or outputting it using console to see if it is what you think it is, likely configuration is wrong.

**Comment by manbomb** [comment]
This is the log saved:

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle migrations@1.0.0~prestart: migrations@1.0.0
6 info lifecycle migrations@1.0.0~start: migrations@1.0.0
7 verbose lifecycle migrations@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle migrations@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/sing-migrations-be/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle migrations@1.0.0~start: CWD: /home/ubuntu/sing-migrations-be
10 silly lifecycle migrations@1.0.0~start: Args: [ '-c', 'knex migrate:latest' ]
11 silly lifecycle migrations@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle migrations@1.0.0~start: Failed to exec start script
13 verbose stack Error: migrations@1.0.0 start: `knex migrate:latest`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid migrations@1.0.0
15 verbose cwd /home/ubuntu/sing-migrations-be
16 verbose Linux 5.4.0-1037-aws
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error migrations@1.0.0 start: `knex migrate:latest`
22 error Exit status 1
23 error Failed at the migrations@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by manbomb** [comment]
I have made a connection  using these user, pass, db and host. It worked fine. The pass is correct.

**Comment by manbomb** [comment]
> Judging by the error, password is wrong. Try using debugger or outputting it using console to see if it is what you think it is, likely configuration is wrong.

I have made a connection using these user, pass, db and host. It worked fine. The pass is correct.

**Comment by kibertoad** [comment]
@manbomb Add `console.log(process.env.PASS)` to confirm that it is what you expect it to be. In 95% cases this error is caused by wrong configuration.

**Comment by manbomb** [comment]
@kibertoad The password showed is correct

**Comment by kibertoad** [comment]
And user "ubuntu" is also correct?

**Comment by kibertoad** [comment]
If all else fails, my recommendation would be to try to invoke knex Migration API programmatically (http://knexjs.org/#Migrations-API) and try to debug what is happening, which exact parameters are being passed to the driver in the end. We don't do any magic on PostgreSQL credentials, they should be passed as-is, so it is unlikely that problem is on knex side specifically, but it is hard to figure out what could be misconfigured without having access to the code.

**Comment by manbomb** [comment]
> And user "ubuntu" is also correct?

ubuntu is the username of my EC2 machine, but my db username is other.

**Comment by manbomb** [comment]
> If all else fails, my recommendation would be to try to invoke knex Migration API programmatically (http://knexjs.org/#Migrations-API) and try to debug what is happening, which exact parameters are being passed to the driver in the end. We don't do any magic on PostgreSQL credentials, they should be passed as-is, so it is unlikely that problem is on knex side specifically, but it is hard to figure out what could be misconfigured without having access to the code.

I have made this connection using psql directly:

`psql --host=database.xxxxxxxxxxx.us-east-2.rds.amazonaws.com --port=5432 --username=postgres --password --dbname=singdb`

Using the same credentials.

**Comment by kibertoad** [comment]
@manbomb Please read the logs that you pasted.
```
error: password authentication failed for user "ubuntu"
    at Connection.parseE (/home/ubuntu/sing-migrations-be/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/ubuntu/sing-migrations-be/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/ubuntu/sing-migrations-be/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

You are passing `ubuntu` as a username. Why and how - I don't know, but this is definitely a wrong configuration issue.

**Comment by manbomb** [comment]
You are right. When I call process.env.USER the returned value is the current user. I have changed the name of the key in env file to USER_DB and it is working. Thanks @kibertoad. Sorry about my english.

**Comment by kibertoad** [comment]
np!
