### ISSUE TITLE
toString formating date to local timestamp

### ISSUE THREAD

**Issue by gustavosizilio** [knex/knex#4349]
Hello guys, I have a table with the last_update value, which is a timestamp with timezone on Postgres 9. 

If I execute the command, everything works fine!

```javascript
knex('my_table')
        .where({id})
        .update({ last_update:  new Date()})
```

But if I store the toString of the command to execute later, which is basically what I need, I have a problem. The toString method is converting the dates before outputting the string... In other words, the command above is not the same as the one below:

```javascript
knex.raw(
         knex('my_table')
        .where({id})
        .update({ last_update:  new Date()}).toString()
)
```

I expect that executing the raw from a toString would be the same, but apparently not... If this is not a bug, how can I make the toString keep the object date and don't convert to any timestamp?

**Comment by elhigu** [comment]
.toString() should be used only for debugging purposes.
