### ISSUE TITLE
On conflict on constraint upsert + postgres

### ISSUE THREAD

**Issue by thousandsofraccoons** [knex/knex#4355]
# Environment

Knex version: 0.95.1
Database + version: PostgreSQL 13.0, compiled by Visual C++ build 1914, 64-bit
OS: Win 10

# Feature discussion / request

https://knexjs.org/#Builder-onConflict

I haven't found in the documentation how to upset rows with unique constraints.

Given following constraint:
```
ALTER TABLE public.assignments_mappings ADD CONSTRAINT assignments_mappings_task_id_user_id_unique UNIQUE (task_id, user_id)
```

I trying to perform upsert with following code: 
```
 return await db("assignments_mappings")
      .insert(
        tasksID.map(id => ({ task_id: id, user_id, company_id: 1 }))
      )
      .onConflict('assignments_mappings_task_id_user_id_unique')
      .merge()
      .returning('id')
```

Which generates 
```
error: insert into "assignments_mappings" ("company_id", "task_id", "user_id") values ($1, $2, $3), ($4, $5, $6), ($7, $8, $9), ($10, $11, $12) on conflict ("assignments_mappings_task_id_user_id_unique") do update set "company_id" = excluded."company_id", "task_id" = excluded."task_id", "user_id" = excluded."user_id" returning "id" - column "assignments_mappings_task_id_user_id_unique" does not exist
```

For successful operation, the output gotta be `on conflict on constraint`. How can I solve it?

**Comment by brandondoran** [comment]
@thousandsofraccoons If I recall correctly, I accomplished this by passing and array of column names that make up unique key instead of the key name.

**Comment by abhi-nestegg** [comment]
Can anyone confirm that this is the way `onConflict` will behave in general?

For eg. I am going to use it for an index that is created like so:
```
CREATE UNIQUE INDEX accounts_unique_account_index ON my_accounts (COALESCE(company_id, user_id), account_id);
```

So, the corresponding onConflict clause, as per above discussion, will be:
```
.onConflict([knex.raw("COALESCE(company_id, user_id)"), 'account_id']).merge()
```
Just want to make sure that it's a feature and not a side effect.
