### ISSUE TITLE
Cannot read property 'QueryBuilder' of undefined

### ISSUE THREAD

**Issue by gudleik** [knex/knex#4357]
Compiling and running a simple typescript example results in `TypeError: Cannot read property 'QueryBuilder' of undefined`.

# Environment

Knex version: 0.95.0
Node version: 14.16.0
Typescript version: 4.2.3

# Steps to reproduce:

```
$ yarn init -y
$ yarn add typescript knex @types/node
$ tsc --init
```

Create a test.ts file with:
```ts
import {Knex} from 'knex'
console.log(Knex.QueryBuilder)
```

Then
```
$ tsc test.ts
$ node test.js
```

This yields the following error:
```
console.log(knex_1.Knex.QueryBuilder);
                        ^

TypeError: Cannot read property 'QueryBuilder' of undefined
    at Object.<anonymous> (/xxx/test.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

The `Knex` variable is not exported from the package, only `knex`.
A simple fix could be to just add `knex.Knex = knex` to knex.js ?

**Comment by kibertoad** [comment]
@gudleik What are you trying to achieve?
`Knex.QueryBuilder` is a compilation-time type, you can't log it.
What is the example that you are trying to follow?

**Comment by gudleik** [comment]
The issue is that I have code like

```ts
import {Knex} from 'knex'
Knex.QueryBuilder.extend('xxx', function (column, values) {})
```

The compiled output of this typically looks like
```js
"use strict";
exports.__esModule = true;
var knex_1 = require("knex");
knex_1.Knex.QueryBuilder.extend('xxx', function (column, values) {
  // ...
})
```

And this won't execute because `Knex` is not exported

**Comment by kibertoad** [comment]
@gudleik try
```
import { knex } from 'knex'
knex.QueryBuilder.extend('xxx', function (column, values) {})
```

**Comment by gudleik** [comment]
But that won't even compile

```
error TS2339: Property 'QueryBuilder' does not exist on type '<TRecord extends {} = any, TResult = unknown[]>(config: string | Config<any>) => Knex<TRecord, TResult>'
```

**Comment by kibertoad** [comment]
That does sounds like a problem with our types. I'll take a look tomorrow. Code itself should work, I think we just miss a type there.

**Comment by kibertoad** [comment]
@gudleik Can you try adding ts-ignore for now and see if code itself works?

**Comment by gudleik** [comment]
Yeah, the code works fine with ts-ignore 👍 

Not sure if there are any undesired side effects, but adding this to knex.js seems to work fine:

```js
knex.Knex = knex;
```

**Comment by kibertoad** [comment]
@gudleik And TypeScript is happy with that too?

**Comment by gudleik** [comment]
Yes

**Comment by kibertoad** [comment]
@gudleik Could you try using version from #4358? I believe it should work correctly with `knex.QueryBuilder`

**Comment by gudleik** [comment]
yes, the pull request version works 👍

**Comment by kibertoad** [comment]
@gudleik 0.95.0 with the fix released!
