### ISSUE TITLE
Error: no pg_hba.conf entry when using postgresql

### ISSUE THREAD

**Issue by fengkx** [knex/knex#4360]
# Environment

Knex version: 0.95.1
Database + version: PostgreSQL 13.2
OS: Ubuntu (Heroku postgres running on Ubuntu)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I can't connect to the database using the `DATABASE_URL` env var provided by heroku. But I can connect to it with postgreSQL cli

2. Error message

```js
DatabaseError: no pg_hba.conf entry for host "34.213.100.152", user "cacnnfxmasqejz", database "dds8bejrv8cpht", SSL off
```

Then I try to add ssl=true query in url. But got
```js
Error: self signed certificate
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Here is a run kit link https://runkit.com/embed/km0bzx27jbhz

**Comment by elhigu** [comment]
Try to connect directly with pg driver. If that works we can re-open. Closing as this doesn't seem like a knex bug.

**Comment by kamikazechaser** [comment]
This is a workaround fix:

```js
    connection: {
      connectionString: process.env.DATABASE_URL,
    },
```

Then in heroku config vars set: `PGSSLMODE=no-verify`

**Comment by vladshcherbin** [comment]
Also having this issue, previous projects used to work on heroku with just `DATABASE_URL`, now there is an ssl error.

@elhigu can you please share how to connect directly for test?

**Comment by vladshcherbin** [comment]
I've managed to solve this by following [example from heroku docs](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js):

```js
client: 'pg',
connection: {
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
}
```

`PGSSLMODE` alternative is also mentioned there at the bottom.

**Comment by axelsomerseth** [comment]
Thank you @vladshcherbin ! Your solution worked for me!

**Comment by growlytics** [comment]
Just disable ssl verification check. It will work.

ssl: { 
    rejectUnauthorized: false
  }
