### ISSUE TITLE
UnionAll + First generates invalid SQL

### ISSUE THREAD

**Issue by ungrim97** [knex/knex#4364]
# Environment

Knex version: 0.95.1
Database + version: Postgresql 9.6
OS: Alpine docker running on Mac BigSur 11.2.1

# Bug

1. The following knex query:

```javascript
knex
  .unionAll(['table1', 'table2'].map((tablename) => knex(tablename).select().where('name', 'test')))
  .first()
  .then((result) => result);
```

generates the following sql

```sql
SELECT * UNION ALL SELECT * FROM "schema"."table1" AS "table1" WHERE "name" = $1 UNION ALL SELECT * FROM "schema"."table2" AS "table2" WHERE "name" = $2 LIMIT $3;
```

2. Error message
```ERROR:  SELECT * with no tables specified is not valid at character 8```

3. Reduced test code

https://runkit.com/ungrim97/6049dd2b75fafb00195923c2

4. Expectation

That code did (in version 0.21.17) generate the SQL:

```sql
SELECT * FROM "schema"."table1" AS "table1" WHERE "name" = $1 UNION ALL SELECT * FROM "schema"."table2" AS "table2" WHERE "name" = $2 LIMIT $3;
```

Which I believe is the correct SQL for this knex query. This appears to be a regression of functionality between version `0.21.17` and `0.95.1` when using `first()`

removing the `first()` and replacing the `then` with ```then(([result]) => result)``` works as expected in either situation as is a suitable work around for me for now

**Comment by kibertoad** [comment]
Released in 1.0.1.
