### ISSUE TITLE
Knex.QueryBuilder.extend and 0.95.x

### ISSUE THREAD

**Issue by santialbo** [knex/knex#4365]
# Environment

Knex version: 0.95.1
Database + version: doesn't matter
OS: doesn't matter

@lorefnon

# Bug
Upgrading to 0.95, I upgraded my knex extensions in TypeScript as follows

```ts
import { Knex, knex } from "knex";

Knex.QueryBuilder.extend("whereLike", ... );
```

This fails with `TypeError: Cannot read property 'QueryBuilder' of undefined` because `Knex` is only a type namespace.
```
❯ node
Welcome to Node.js v15.6.0.
Type ".help" for more information.
> require("knex").Knex
undefined
```

The following does work however but needs the any because the types are incorrect.

```ts
import { knex } from "knex";

(knex as any).QueryBuilder.extend("whereLike", ... );
```

**Comment by kibertoad** [comment]
@santialbo Please update to (just released) 0.95.2, `knex.QueryBuilder.extend("whereLike", ... );` should work there!
