### ISSUE TITLE
[SQLite] Support .returning in the latest SQLite

### ISSUE THREAD

**Issue by umaar** [knex/knex#4370]
[`.returning()`](http://knexjs.org/#Builder-returning) doesn't work on SQLite, however it looks like their latest version does support it now: https://nalgeon.github.io/sqlite-3-35/

Any chance of getting this working in Knex? Thanks

**Comment by kibertoad** [comment]
@umaar We depend on node-sqlite driver for that, which is only on 3.32.3 for now (https://github.com/mapbox/node-sqlite3/releases/tag/v5.0.1).
As soon as update version of driver is released, we'll check if any changes on our end will be needed for `returning` to work correctly with SQLite.

**Comment by umaar** [comment]
Thanks for raising an issue there! https://github.com/mapbox/node-sqlite3/issues/1453

**Comment by tkalliom** [comment]
The aforementioned https://github.com/TryGhost/node-sqlite3/issues/1453 has landed in version 5.0.3 of the driver. Is it now possible to move forward with this? https://github.com/microsoft/vscode-node-sqlite3/issues/15, related to this, was opened with the fork of the driver, but a corresponding issue does not seem to exist in the newly relocated upstream repo of the driver

**Comment by kibertoad** [comment]
yes, that's the plan

**Comment by simonplend** [comment]
@kibertoad As `sqlite3` has bundled SQLite with `RETURNING` support since [v5.0.3](https://github.com/TryGhost/node-sqlite3/releases/tag/v5.0.3), and `better-sqlite3` since [v7.1.4](https://github.com/WiseLibs/better-sqlite3/releases/tag/v7.1.4), would a PR now be welcome to resolve this issue?

I've hacked in the changes locally in my `node_modules` and they seem to be working well.

**Comment by kibertoad** [comment]
@simonplend Would be awesome! Tests should already exist: https://github.com/knex/knex/pull/4934

**Comment by simonplend** [comment]
@kibertoad Great, I'll see what I can throw together tomorrow.

**Comment by kibertoad** [comment]
Released in 2.3.0
