### ISSUE TITLE
READ ONLY User Can't take lock to run migrations

### ISSUE THREAD

**Issue by Sugan-Joe** [knex/knex#4379]
# Environment

Knex version:0.95.2
Database + version: Postgres 
    "pg": "^8.3.0",
    "pg-connection-string": "^2.3.0",

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
2. While using  READ ONLY user to access DB for local development, the application tries to take lock to run migrations but fails because of RO access (below error). Is there a way to avoid this issue without granting RW access ?

2. Error message
```
Can't take lock to run migrations: update "knex_migrations_lock" set "is_locked" = $1 where "is_locked" = $2 - cannot execute UPDATE in a read-only transaction
If you are sure migrations are not running you can release the lock manually by running 'knex migrate:unlock'
```

**Comment by elhigu** [comment]
Sounds like expected behaviour. Migrations by definition does changes to the DB.
