### ISSUE TITLE
MSSQL query is not correct

### ISSUE THREAD

**Issue by vinusorout** [knex/knex#4385]
# Environment

Knex version: 0.95.2
Database + version: MSSQL

# Bug
I am trying to simply select get date in select query, I am using knex to just creating queries,  like 
```sql
Select GETDATE() as date
```
Following is my code:
```typescript
import { knex } from 'knex'
const mssqlKnex = knex({client: 'mssql'});
const query = mssqlKnex.select('GETDATE() as date').toString();
console.log(query);
```

Expected query should be 
```sql
Select GETDATE() as date
```

But I am getting:
```sql
Select [GETDATE()] as [date]
```

Error: '[' with 'GETDATE' function is causing the issue while executing the statement.

```
ErrorMessageToken {
      name: 'ERROR',
      event: 'errorMessage',
      number: 207,
      state: 1,
      class: 16,
      message: "Invalid column name 'GETDATE()'.",
      serverName: 'xxxxxxx',
      procName: '',
      lineNumber: 1
    }
```

**Comment by kibertoad** [comment]
You should use knex.raw instead of just passing string there. See this: https://github.com/knex/knex/issues/146

**Comment by vinusorout** [comment]
> You should use knex.raw instead of just passing string there. See this: #146

Thanks @kibertoad , it is now working
