### ISSUE TITLE
Cannot use namespace 'Knex' as a type

### ISSUE THREAD

**Issue by Duarte007** [knex/knex#4396]
Knex version: 0.95.3
Database + version: MySQL 5.6
OS: Debian GNU/Linux 9 (stretch)

I am having problem with typescript and knex. When I try to type a Knex variable using the Knex interface defined in index.d.ts it seems that the namespace is overwriting the interface and I get the following error: "Cannot use namespace 'Knex' as a type."

This started to happen when I updated the knex to latest version.

I thank the attention

**Comment by kibertoad** [comment]
@Duarte007 Could you please share your code? Also did you check the migration guide?
https://github.com/knex/knex/blob/master/UPGRADING.md

**Comment by Duarte007** [comment]
@kibertoad the migration guide solved my problems !! Sorry about that, I hadn't seen it yet

**Comment by kibertoad** [comment]
np! glad it worked
