### ISSUE TITLE
bug(type): Incorrect typing for stream() method

### ISSUE THREAD

**Issue by monotykamary** [knex/knex#4398]
# Environment

Knex version: 0.95.3
Database + version: Postgres 13
OS: Ubuntu 20.04

Select applicable template from below.
~If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.~
~Rest of dialects don't need tags.~
If issue is about TypeScript definitions, tag @lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Example query `knex.select('*').from('users').stream()` should return type `stream.Passthrough`, without debate. The current typing for `knex.select('*').from('users').stream()` represents a breaking change in type signature from `stream.Passthrough` to `AsyncIterable` despite the fact that no code has been changed for any dialects referring to method `stream()` or `_stream`.

2. Error message
![image](https://user-images.githubusercontent.com/1130103/112630946-dff43a80-8e68-11eb-867d-c4ad96356f1b.png)

3. Reduced test code: N/A

---

At the moment, a workaround to this mistyping is by adding an empty options object into the stream to enforce the type to return `stream.Passthrough`:

```
const stream = knex.select('*').from('users').stream({});
```

The issue stems from this pull request: https://github.com/knex/knex/pull/4377. The mistyping for method `stream()` to allow for-await-of is **not even needed** as the stream `Passthrough` class is already iterable from implementing `AsyncIterableIterator`.

![image](https://user-images.githubusercontent.com/1130103/112631712-cdc6cc00-8e69-11eb-9954-1ab8b9e3895b.png)

EDIT: I've created a pull request to revert the changes: https://github.com/knex/knex/pull/4400

**Comment by kibertoad** [comment]
Released in 0.95.4
