### ISSUE TITLE
`Error: Cannot chain .first() on "insert" query!` for queries with `returning`

### ISSUE THREAD

**Issue by peey** [knex/knex#4403]
# Environment

Knex version: 0.21.19
Database + version: Postgres 13
OS: Linux/Docker

# Bug

1. I cannot issue this query: `await this.knex('table').insert(data).returning('id').first()`
   I should be able to, because knex wraps results of `returning` into an array (whether this is needed or not, I do not know)

2. Error message

```
Error: Cannot chain .first() on "insert" query!
    at Builder.first (/code/node_modules/knex/lib/query/builder.js:1003:13)
```
3. Reduced test code:  https://runkit.com/6050519d497187001acdebbe/60619620af6968001aaed542

**Comment by peey** [comment]
This also happens on "update" queries.

**Comment by maximelkin** [comment]
Knex.js before used Bluebird for promises, which have .first() method. Current version uses native promises.

**Comment by maximelkin** [comment]
I think .first() on update could be confusing, i.e.
`knex('table').update({column: 2}).returning('id').first()` => Should it return random id from updated rows, or limit all updates to only 1 row?

**Comment by peey** [comment]
@maximelkin I think your objection could equally well apply to `select` and `insert`

In the case of `select`, does knex append `limit` to the query or does it execute the original query but doesn't retrieve results beyond the first result from the results cursor?

If it's the former then I'd agree that there can be a confusion, in case of the latter I think it should follow the same semantics as `select` -- execute the original query but of things being returned, only return the first item from the cursor.

**Comment by maximelkin** [comment]
>In the case of select, does knex append limit to the query or does it execute the original query but doesn't retrieve results beyond the first result from the db results cursor?

Yes, knex apply limit 1

**Comment by peey** [comment]
In that case I think I misunderstood it. 

It'd still be nice to have some syntax when you know you're only getting back a single result, e.g.

```
// instead of this
let results = knex.<query>(...)
let result = results[0]

// something like this
let result = knex.<query>(...).single()
```

but I don't know how valid this is as a feature for inclusion in knex, perhaps it's better off as a utility in my own code (e.g. `.then(single)` where `single = rows => rows[0]`)
