### ISSUE TITLE
Tedious option 'trustServerCertificate' missing from types

### ISSUE THREAD

**Issue by oddeirik** [knex/knex#4421]
# Environment

Knex version: 0.95.4
Database + version: SQL Server 2017 and Azure SQL
OS: Windows and Ubuntu

Typescript definitions tag: @lorefnon 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I have an MS SQL server with a self-signed certificate, which means I need to set the trustServerCertificate in mssql/tedious options. However, it seems the options.trustServerCertificate is missing from the type definitions for MsSqlConnectionConfigBase.

2. Error message

```
[ConnectionError: Context creation failed: Failed to connect to <redacted>:1433 - self signed certificate] {
  locations: undefined,
  path: undefined,
  extensions: { code: 'INTERNAL_SERVER_ERROR', exception: { stacktrace: [Array] } }
}
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
const knexInstance = knex({
    debug: false,
    client: 'mssql',
    connection: {
      host: host,
      user: username,
      password: password,
      database: database,
      options: {
        encrypt: true,
        trustServerCertificate: true,
        enableArithAbort: true,
      },
    },
    pool: {
      min: 1,
      max: 4,
    },
  });
```

`error TS2322: Type '{ host: string; user: string; password: string; database: string; options: { encrypt: true; trustServerCertificate: true; enableArithAbort: true; }; }' is not assignable to type 'string | StaticConnectionConfig | ConnectionConfigProvider'.
  Types of property 'options' are incompatible.`
![image](https://user-images.githubusercontent.com/10148/113999703-91787000-985a-11eb-9961-d1a67b64f7c7.png)

Edit: Sorry, I tagged the wrong person initially!

**Comment by jjshinobi** [comment]
Have the same issue

**Comment by kibertoad** [comment]
@jjshinobi Would you be open to submit PR for this?

**Comment by mrdnote** [comment]
I created a pull request for this: https://github.com/knex/knex/pull/4500

**Comment by TroyAlford** [comment]
Given that #4500 is now closed/merged, this can probably also be closed.
