### ISSUE TITLE
How to solve syntax error near a SELECT inside a join

### ISSUE THREAD

**Issue by Jakub41** [knex/knex#4424]
Hello, 

I'm searching help about an issue I got building a Knex query and after asked around and no responses, I hope here I could find the solution which will unblock my work :) 

I hope you will be able to give me the right solution

The query is giving this error:

```bash
syntax error at or near \"select\"
```

The error happens in the `SELECT`inside the `.join()` and the SQL generated from it gives same error and I share also the raw SQL below 

The query

```js
this.builder
      .join(
        this.tx(messageTable)
          .select(messageColumns.conversationId)
          .max(messageColumns.createdAt, 'updated_at')
          .where(messageColumns.conversationId, columns.id)
          .groupBy(messageColumns.conversationId),
        messageColumns.conversationId,
        'updated_at'
      )
```

The SQL 

```sql
SELECT
	*
FROM
	"conversation"
	INNER JOIN
	SELECT
		"conversation_id",
		max("created_at")
	FROM
		"message"
	WHERE
		"conversation_id" = 'id'
	GROUP BY
		"conversation_id" ON "conversation_id" = "updated_at"
```

Thank you for the help :)

**Comment by elhigu** [comment]
Usage question and doesn't follow issue guidelines.
