### ISSUE TITLE
with() doesn't work with update statements?

### ISSUE THREAD

**Issue by Linksku** [knex/knex#4428]
# Environment

Knex version: 0.95.2
Database + version: MySQL 8.0.22
OS: WSL Ubuntu 20

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When using `with()` with `update()`, the `with` statement doesn't appear in the query.

2. Error message

None

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
knex('foo')
  .with('foo2', builder => builder.select('*').from('foo'))
  .update({ col: 1 });
```

Expected query:

```
with `foo2` as (select * from `foo`) update `foo` set `col` = 1
```

Actual query:

```
update `foo` set `col` = 1
```

**Edit:**

It looks like this can be fixed by adding `this.with()` to `QueryCompiler_MySQL.update`

**Comment by kibertoad** [comment]
Released in 1.0.2
