### ISSUE TITLE
How can I use query without from clause

### ISSUE THREAD

**Issue by elluard** [knex/knex#4431]
# Environment

Knex version: 0.21.19
Database + version:
OS: Postgresql 12.6

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Questions about how to use knex

Hello, 

I use knex to develop my service 

I have a question during using this.

The query that I hope to use is without from clause like below.

select nextval('sequenceName')

How can I use? 

Thank you.

**Comment by elhigu** [comment]
knex.select(knex.raw('nextval(??)', ['sequenceName']))
