### ISSUE TITLE
MSSQL connection crash

### ISSUE THREAD

**Issue by muhammetkocyigit0** [knex/knex#4438]
# Environment

Knex version: 0.95.4
Database + version: MSSQL 2016
OS: Windows Server 2016

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I created a basic mssql db connection with knexjs. Its was work great before but i getting this error right now.

2. Error message
Uncaught Error: No event 'socketConnect' in state 'SentPrelogin'

**Comment by elhigu** [comment]
that error is coming from mssql drive so knex cant do much about it. Also cannot reproduce.
