### ISSUE TITLE
Knex failing to compile with Typescript - "Type error: Type expected"

### ISSUE THREAD

**Issue by javonclarke** [knex/knex#4439]
# Environment

Knex version: 0.95.4
Typscript version: 4.0
ts-node: 8.10.2
Database + version: p=PostgreSQL 11
OS: MacOS & Ubuntu

I've been using Knex successfully in development. When I try to build and deploy, I get a typescript compile error. After inspecting the code, I also get bunch of lint errors around the block of code that causing the build issues.

I'm using Nextjs framework in typescript mode and running the following command:
```yarn build = next build && tsc --project tsconfig.server.json```

```./node_modules/knex/types/index.d.ts:1130:16
Type error: Type expected.

  1128 |     >(
  1129 |       tableName: TTable2,
> 1130 |       column1: `${TTable1}.${TKey1}`,
       |                ^
  1131 |       column2: `${TTable2}.${TKey2}`
  1132 |     ): QueryBuilder<TRecord2, TResult2>;
  1133 |     <
```

**Comment by kibertoad** [comment]
0.16.1 is very old. Have you tried using newer Knex? Also which TypeScript version are you using?

**Comment by javonclarke** [comment]
I followed the install instructions - I didn't specifying a version.

**Comment by javonclarke** [comment]
I specified the wrong version in the details -_-

**Comment by kibertoad** [comment]
Which TypeScript version? 0.95.x requires 4.1+

**Comment by javonclarke** [comment]
I'm getting a new error that I'm able to fix. Thank you.

**Comment by mglimmerveen** [comment]
Hi @javonclarke, I have the same issue now.
Can you elaborate a bit on how you solved it? DId you upgrade typescript?

**Comment by javonclarke** [comment]
@mglimmerveen I did upgrade my typescript version to the latest version at that time which was 4.2.4

**Comment by mglimmerveen** [comment]
Thanks!  It turned out to be the same for me; I had done a partial update.
