### ISSUE TITLE
disable oracledb autocommit

### ISSUE THREAD

**Issue by amuammer** [knex/knex#4445]
i have used knex with oracledb client with the next config

```
const database = knex({
  client: "oracledb",
  connection: {
    user: DB_USER,
    password: DB_PASS,
    host: DB_HOST,
    port: DB_PORT,
    database: DB_NAME,
  },
  debug: DEBUG_MODE,
  fetchAsString: ["number", "clob"],
});
```
**when execute any query it's auto committed and i want to disable it !**
```
database("EMPLOYEES")
 .where({ EMPLOYEE_ID: 100 })
 .update({ EMAIL: "hi@example.com" })
```

**Comment by elhigu** [comment]
In general case with multiple connections it cannot be done.

 To prevent autocommit you need to start transaction and run queries that should not be autocommitted there. If you disable autocommit you will not have any idea in what state each db session created by pool  is.

 Though if you don’t care what result you may get or use just a single connection in that special case disabling autocommit could work. In that case it probably can be set with knex.raw().
