### ISSUE TITLE
QueryBuilder.extend undefined

### ISSUE THREAD

**Issue by andrescellini** [knex/knex#4448]
# Environment

Knex version: ^0.21.16
Database + version: Postgres
OS: Ubuntu 21.04

# Questions about how to use knex

trying to extend querybuilder i get undefined. this is my db file.

```const environment = process.env.ENVIRONMENT || "development";
const config = require("../knexfile.js");

const knex = require("knex")(config[environment]);

knex.QueryBuilder.extend("customSelect", function (value) {
  return this.select(this.client.raw(`${value} as value`));
});

const { attachPaginate } = require("knex-paginate");
attachPaginate();

module.exports = knex;
```
with error 

`TypeError: Cannot read property 'extend' of undefined`

**Comment by elhigu** [comment]
Docs says that you should call 

    const Knex = require('knex');
    Knex.QueryBuilder.extend(...);

and then create confugured knex instance.

Now you are trying to extend already created knex instance instead of the Knex class.
