### ISSUE TITLE
How can i use case where

### ISSUE THREAD

**Issue by Erchoc** [knex/knex#4461]
# Environment

Knex version: 0.95.4
Database + version: mysql5.7.27
OS: macos10.12

# Questions about how to use knex

hi，how can I use case where when mysql update? the document doesn't provide related desc，must use mysql query?

**Comment by elhigu** [comment]
knex('table').update('text', 'bar').where('text', 'foo')

**Comment by Erchoc** [comment]
> knex('table').update('text', 'bar').where('text', 'foo')

you are so funny.

**Comment by kibertoad** [comment]
@Erchoc It is the correct syntax, though. What is the problem that you have?

**Comment by kibertoad** [comment]
@elhigu I think what is meant here is this: https://www.w3schools.com/mysql/func_mysql_case.asp

And I don't think there is any built-in support for that, you'd have to use knex.raw
