### ISSUE TITLE
Unable to set a variable in a query.

### ISSUE THREAD

**Issue by AnsaDhedhi** [knex/knex#4467]
# Environment

Knex version:
Database + version: PostgreSQL

I am trying to send some variables in a knex Query and get the data.

I am using this Query. I declared activityone as 'completed_order' and used it in a query but the output I am getting is not correct.

```
const { activityone } = 'completed_order'
router.get("/dataset", function (req, res) {
 db.raw(`WITH
 cohort AS (
   SELECT
     s.activity_id AS "activity_id"
     , timezone('America/New_York', s.ts) AS "timestamp"
     , s.customer AS "customer"
     , s.feature_1 AS "email_type"
     , v.occurrence AS "activity_occurrence"
     , s.customer AS "join_customer"
     , s.ts AS "join_ts"
     , s.activity_id AS "join_cohort_id"
     , v.activity_repeated_at AS "join_cohort_next_ts"
   FROM activity_stream AS s 
   CROSS JOIN viewdemotable as v
   WHERE s.activity = {activityone} and s.activity_id = v.activity_id 
   ORDER BY "timestamp" DESC
 ),
`)
   .then(rows => {
     res.send(rows);
   })
   .catch();
});
```

How to use the variable in a query and get the correct output? What I am trying to do is, If the user selects the option from the front-end then the selected option will be saved in a variable and sent in a query and get the data.

**Comment by elhigu** [comment]
Closing doesn't seem to be a knex bug. Usage questions should go to stackoverflow. 

First bug in the code is on the first line https://runkit.com/embed/qmb80cdlby0a
