### ISSUE TITLE
Changelog on knexjs.org seems broken

### ISSUE THREAD

**Issue by Redirts** [knex/knex#4472]
![image](https://user-images.githubusercontent.com/23477559/117429192-51b6ae00-af16-11eb-9de6-c25d5ed65db6.png)

Also, why can't I find on github's changelog any mention of version 0.21.18 and 0.21.19 which are available on npm?

**Comment by kibertoad** [comment]
I'll take a look, thanks!

You can always check https://github.com/knex/knex/blob/master/CHANGELOG.md for older versions.

**Comment by kibertoad** [comment]
I think we've lost some of 0.21.x changelogs when switching to 0.95.x. Thank you for bringing this up, I'll try to fix.

**Comment by kibertoad** [comment]
This should be fixed now.
