### ISSUE TITLE
MSSQL expose database connection

### ISSUE THREAD

**Issue by joshkay** [knex/knex#4485]
# Environment

Knex version: 0.95.4
Database + version: Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
OS: Windows 10

# Feature discussion / request

1. Explain what is your use case

I am currently looking at integrating `knex` into an existing nodejs application that uses the `mssql` library. 
In order to use `knex` I need to create an additional connection to the database alongside the existing `mssql` connection.

```
export const knex = require('knex')({
  client: 'mssql',
  connection: sqlConfig,
  pool: { min: 0, max: 100 }
});

export const poolPromise = new mssql.ConnectionPool(sqlConfig)
  .connect()
  .then(pool => {
    console.log('Connected to MSSQL')
    return pool
  })
  .catch(err => console.log('Database Connection Failed! Bad Config: ', err));
```

2. Explain what kind of feature would support this

Would it be possible to get the underlying `ConnectionPool` promise from the `knex` connection so that I am able to create requests via:

```
const pool = await poolPromise;
return await pool.request();
```

I currently have a lot of code that is using the above method of creating requests along with the `mssql` syntax for passing parameters to queries.

3. Give some API proposal, how the feature should work

Perhaps it would be possible to access the underlying `mssql.ConnectionPool` connection from the `knex` object after it has been initialized.

**Comment by elhigu** [comment]
There is no plans to expose the connection pool through stable APIs, but it is found from `knex.pool` underlying mssql pool is not really used by knex, since knex uses Tarn.js pool and gets single connctions from db driver.
