### ISSUE TITLE
Feature request: Add opposite of select - EXCLUDE

### ISSUE THREAD

**Issue by rustamsmax** [knex/knex#4490]
# Environment

Knex version: 0.95.1
Database + version:
OS: MAC

# Feature discussion / request

1. I've a table A which has a column Z of type tsvector

2. I want to exclude this column because it is used only for filtering 

3. knex('table_name').select('*').exclude('column_name')

**Comment by kibertoad** [comment]
@rustamsmax Considering that it's impossible to generate SQL out of that (knex doesn't know which columns table has), that would merely be a postprocessing of data already retrieved, which sounds like something that would better be done with something like Ramda or Lodash.

**Comment by rustamsmax** [comment]
Oh. Certainly
Thank you
