### ISSUE TITLE
Add support for better-sqlite3

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#4511]
See https://github.com/JoshuaWise/better-sqlite3

**Comment by jarcodallo** [comment]
Hi @kibertoad any news about this? I can open a PR to add support to better-sqlite3 or replace sqlite3 with this one.

**Comment by kibertoad** [comment]
@jarcodallo PR would be greatly appreciated! Separate dialect would be preferable, similarly to mysql/mysql2 ones.

**Comment by jarcodallo** [comment]
> @jarcodallo PR would be greatly appreciated! Separate dialect would be preferable, similarly to mysql/mysql2 ones.

Awesome @kibertoad. I will start working on this next week 🚀

**Comment by MegaNoam** [comment]
Any news?

**Comment by jarcodallo** [comment]
> Any news?

I'm working on it 😬

**Comment by cekvenich2** [comment]
Ideally with all the extra flags it supports: 
this._db.pragma('cache_size = -' + mem); //
		console.log('cache', this._db.pragma('cache_size', { simple: true }));
		this._db.unsafeMode(true)
		this._db.pragma('busy_timeout=' + 120 * 1000); // 2 minutes
		this._db.pragma('mmap_size=' + mem); // 
		this._db.pragma('synchronous=OFF');

		this._db.pragma('journal_mode=OFF'); // MEMORY or WAL
		this._db.pragma('SQLITE_THREADSAFE=1'); 
		this._db.pragma('SQLITE_OMIT_SHARED_CACHE=true'); 

		this._db.pragma('wal_checkpoint=TRUNCATE'); // release memory used for rollback
		this._db.pragma('temp_store=MEMORY');
		this._db.pragma('automatic_index=false');
		this._db.pragma('foreign_keys=false');
		this._db.pragma('secure_delete=false');
		this._db.pragma('read_uncommitted=true'); // no locking
		this._db.pragma('cache_spill=false');
		this._db.pragma('locking_mode=NORMAL'); // 3rd party connection,  NORMAL or EXCLUSIVE
		console.log('locking', this._db.pragma('locking_mode', { simple: true }));

**Comment by jrj2211** [comment]
Just wanted to throw in my support for this feature. I've had a lot of trouble with sqlite3 (outside of knex) over the years so having another option for those times I need an sqlite database would be great.

**Comment by benjdlambert** [comment]
@jarcodallo how is it going with the PR?

**Comment by kibertoad** [comment]
@jarcodallo I would be happy to help with finishing the PR if you have it half-done already

**Comment by benjdlambert** [comment]
So I've picked up working on some of this in my spare time to kick this back off again. I've duplicated the entire dialect for `sqlite3` so far, as there is some differences, and thought that that extending the `sqlite3` dialect is just going to cause some pain when eventually it's removed as it's no-longer maintained, but if we'd rather extend or replace the driver underneath the `sqlite3` dialect then that option is there too.

I've duplicated the unit test suite from `sqlite3` also, so we get some pretty good coverage, and just working through the failures. About 50% is green right now.

One question I have @kibertoad maybe you know of some utility that can help here - one difference between `node-sqlite3` and other SQL engines and `better-sqlite3` is that in integration tests we might execute some raw SQL which in integration tests might be written like this: `SELECT * FROM table WHERE id="hardcodedvalue"`. This fails with `better-sqlite3` as it should be `='hardcodedvalue'`. Is there some form of utility that already exists that can safely replace the quotes without impacting in the wrong places?

**Comment by benjdlambert** [comment]
Hoping to have a PR realistically by the end of the week.

**Comment by kibertoad** [comment]
@benjdlambert sqlite3 is going to be there for a long time to come for backwards compatibility reasons, I strongly recommend extending and not duplicating it.
Not aware of quote utility, need to check. Probably will need to wtite one ourselves.

**Comment by benjdlambert** [comment]
@kibertoad ok - no probs at all, I can do that pretty easily once I've got things working.

**Comment by jarcodallo** [comment]
@kibertoad @benjdlambert sorry guys this month was pretty busy for me. I couldn't finish my PR, but I was doing something similar as @benjdlambert want it to do. Let me know if you need help with that.

**Comment by benjdlambert** [comment]
I've just thrown a draft PR up with the progress so far. It's coming along, I think there's around 10 tests that are failing right now, some are pretty trivial to fix and are just the error messages, some are a little more tricky to fix which is I think it something to do with the `bindings` not all being supported types. But i'll get as far as I can with it and might need a little help getting it across the line @kibertoad or anyone else that could jump in a help out.

**Comment by kibertoad** [comment]
Released in 1.0.1.
