### ISSUE TITLE
[BUG] Converting circular structure to JSON

### ISSUE THREAD

**Issue by JefferyHus** [knex/knex#4513]
# Environment

Knex version: 0.95.6
Database + version: Mysql 5.7
OS: Linux

# Bug

1. Explain what kind of behavior you are getting and how you think it should do
```javascript
await transaction
  .table('Notification')
  .where('values', 'LIKE', `%${source}%`)
  .update(knexql.raw('REPLACE(values, ?, ?)', [source, args.target]))
```
This should return something of this SQL query string
```sql
update `Notification`
SET `values` = REPLACE(`values`, ?, ?)
WHERE `values` LIKE "%?%";
```
But instead I am getting this
```sql
update `Notification` set `_events` = ?, `_eventsCount` = ?, `client` = ?, `sql` = ?, `bindings` = ?, `_debug` = ? where `values` like ?
```

2. Error message
I am getting this error message `Converting circular structure to JSON` this is thrown because of `knexql.raw('REPLACE(values, ?, ?)', [source, args.target])`

**Comment by kibertoad** [comment]
it appears that some of the params you are passing are complex objects. check them and convert up-front.

**Comment by JefferyHus** [comment]
Not really complex
```javascript
const source = string[]
const target = string
```

**Comment by elhigu** [comment]
@JefferyHus Yep Looks like update doesn't support passing raw directly to it. But the query in your example should actually output 

```
update `Notification`
SET REPLACE(`values`, ?, ?)
WHERE `values` LIKE "%?%";
```

or maybe:
```
update `Notification`
REPLACE(`values`, ?, ?)
WHERE `values` LIKE "%?%";
```

So it is some unspecified functionality and your query has a bug. 


This should create correct query for you:
```
.update('values', knexql.raw('REPLACE(??, ?, ?)', ["values", source, args.target]))
```
