### ISSUE TITLE
Expand withRecursive database support via supporting column name declarations

### ISSUE THREAD

**Issue by code-ape** [knex/knex#4514]
# Environment

**Knex version:** 0.95.5
**Database + version:** Sqlite 3.x, Oracle 18c, Postgres 13.x, SQL Server 2016
**OS:** Ubuntu Linux, Windows Server

# Feature discussion / request

1. Explain what is your use case

I need support for recursive `WITH` syntax on Oracle DB and SQL Server in addition to Sqlite and Postgres. All four databases support recursive CTE `WITH` statements so this is a question of how to best implement this in Knex (assuming it's agreeable to do so).

All four databases support column declaration (`WITH temp_table (column1, column2, ...) AS (...)`) and for two of them column declaration enables CTE `WITH` functionality. Of those four, two support the `RECURSIVE` syntax word and two don't. For Sqlite and Postgres the `RECURSIVE` operator is supported and for Oracle and MSSQL the functionality is enabled by simply declaring the column names. Here is a quick breakdown.

| Database | Supports `RECURSIVE` | Supports column names | Reference |
|----------|-------------------------|--------------------------|-----------|
| Sqlite | Yes | Yes | [Link](https://sqlite.org/lang_with.html) |
| Postgres | Yes | Yes | [Link](https://www.postgresql.org/docs/13/queries-with.html) |
| Oracle | No | Yes | [Link](https://livesql.oracle.com/apex/livesql/file/tutorial_GQMLEEPG5ARVSIFGQRD3SES92.html) |
| MSSQL | No | Yes |  [Link](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15) |

Since all databases support this and support the column names this seems like a reasonable abstraction to provide a recursive with over top of all of them.

2. Explain what kind of feature would support this

Changing `knex.withRecursive` to support column names.

3. Give some API proposal, how the feature should work

```ts
knex.withRecursive('with_alias', ['column1', 'column2'], (qb) => {...}).select('*').from('with_alias')
// On Sqlite and Postgres
//  WITH RECURSIVE `with_alias` (`column1`, `column2`) AS (...) SELECT * FROM `with_alias`
// On Oracle and MSSQL
//  WITH `with_alias` (`column1`, `column2`) AS (...) SELECT * FROM `with_alias`
```

**Comment by jeremy-w** [comment]
You actually already have recursive CTE support under SQL Server, it just doesn't work if you use the `withRecursive` function, because it hasn't been taught to omit the `RECURSIVE` keyword. SQL Server does not require a column list in order to enable recursive queries. It can be omitted unless you have duplicate column names in your query:

> The list of column names is optional only if distinct names for all resulting columns are supplied in the query definition. (https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#arguments)

If you scan through all the examples, you'll eventually find the one where they're demoing a recursive CTE _and_ not providing the column names, [I. Using analytical functions in a recursive CTE](https://docs.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver15#bkmkUsingAnalyticalFunctionsInARecursiveCTE), which includes:

```sql
WITH vw AS  
 (  
    SELECT itmIDComp, itmID  
    FROM @t1  
  
    UNION ALL  
  
    SELECT itmIDComp, itmID  
    FROM @t2  
)   
```

**Comment by jeremy-w** [comment]
Oof, Oracle does require both:

- omitting the RECURSIVE keyword (see [with_clause](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__GUID-7BFCEBF8-6459-4328-8CFC-6FF044E8A147) and [subquery_factoring_clause](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6) productions)
- including column aliases:

  > The column aliases following the query_name and the set operators separating multiple subqueries in the AS clause are valid and required for recursive subquery factoring. The search_clause and cycle_clause are valid only for recursive subquery factoring but are not required. (subquery_factoring_clause, again)

As a workaround, I believe you can include the column aliases as part of the with argument, and the generated SQL will be correct: `knex.with('cteName (id, name)', buildSelect)`.

**Comment by kibertoad** [comment]
@code-ape Could you please check if implementation in 0.95.11 satisfies requirements of this ticket?
