### ISSUE TITLE
Feature request: model definitions and auto-migrations

### ISSUE THREAD

**Issue by douglas-treadwell** [knex/knex#4516]
# Model definitions and auto-migrations

I'm comparing using TypeORM, Sequelize, and Knex.  Knex has the best query builder interface, so I'd like to use Knex.  However, TypeORM and Sequelize conveniently provide a model definition mechanism and auto-migrations, and Knex does not.

1. Explain what is your use case

I'd like to be able to define models because a) it would give me one place where the current design of the DB tables is defined, and b) by defining models it enables auto-migrations.

I realize that a) is in theory handled by TypeScript interfaces, but TypeScript doesn't provide a 1:1 mapping with all the possible varieties of data that can be stored in a DB.  For example, both `varchar` and `text` fields are represented by `string`.  Also, it still doesn't enable b) auto-migrations, without a lot of custom tooling not provided by Knex.

(Also, the TypeScript interfaces usually reflect the objects as they exist after they've been queried, parsed, transformed, etc., rather than how they are stored in the database, but as discussed above they would still be insufficient even if that were resolved.)

2. Explain what kind of feature would support this

In theory, any mechanism that enables defining models would support this.

3. Give some API proposal, how the feature should work

A couple options are: 
* a builder pattern similar to how tables are usually created in Knex, but intended to be used as a "current definition" or "target model" for a table (this would be more compatible with JS users rather than just TS users)
* a class decorator / field decorator definition mechanism similar to TypeORM, which would be better for TS users.

The same options as above restated:

A very good option for TypeScript users would be TypeORM style model definitions and automigrations, but Knex queries.  I would point to the TypeORM API for the details of these.

A slightly less good option, but also usable for JavaScript users, would be the builder pattern.  You could literally reuse your exact same API for creating tables, but in addition to the original table creation migration and multiple alteration migrations, there would be one more "target" query, against which the current database state could be compared for automigration purposes.

I think the query builder pattern is a little bit less readable if I'm trying to quickly understand a table definition.

Note that I'm not looking for an ORM-style "Model.fetchAll()" like Bookshelf or "Model.find()" like TypeORM.  I do prefer the very-nearly-SQL style of Knex.  I am only suggesting model definitions for the purpose of automigrations, self-documenting code (which keeps itself correct due to automigrations), and possibly for initial/base TypeScript interface definitions (which would likely require some Omit/Extend use due to transformations in queries).

**Comment by kibertoad** [comment]
Have you considered MikroORM and/or Objection.js? Both come with models and increased amount of batteries, but also expose knex API you can always hop on when need be.
knex itself will never have neither models, nor schema generation. It is just a SQL builder.

**Comment by douglas-treadwell** [comment]
@kibertoad Thanks for the tip!  Objection doesn't fit the style I'm looking for, but MikroORM is looking good so far!

**Comment by asteinarson** [comment]
I add here a schema management tool [knemm](https://github.com/asteinarson/knemm) I'm working with, running on top of Knex. 

It allows for declaring and manipulating schema in simple YAML. It is also two-way, so one can generate YAML from existing databases.

**Comment by kibertoad** [comment]
@asteinarson Looks cool! Would you consider adding it to knex ecosystem doc? https://github.com/knex/knex/blob/master/ECOSYSTEM.md

**Comment by asteinarson** [comment]
Absolutely! I was searching for something like that.

I will likely come back with comments / issues, as I've used knex schema
functions quite a bit in the tool.

Thanks,
Arne S.
