### ISSUE TITLE
How do i get MySQL connectionId using knex npm package while establishing the connection?

### ISSUE THREAD

**Issue by manjuhubballi02** [knex/knex#4521]
let data = require('knex')({ client: 'mysql', connection: { host: 'localhost', user: 'root', password: 'root', database: 'aaaaaa', charset: 'utf8' }, pool: { min: 1, max: 20, destroyed: true }, })

this is my connection request. how do I find a connection id for this?

**Comment by elhigu** [comment]
You will not get any connection id. There is actually not connections made when knex in initialized. The first connection is created when the first query is done.

When pool creates a new connection afterCreate callback is created, which also provides handle to underlying connection.
