### ISSUE TITLE
How to add FORCE_LEGACY_CARDINALITY_ESTIMATION for MSSQL ?

### ISSUE THREAD

**Issue by joshgo** [knex/knex#4522]
One of the projects I am working has a SQL call that use the OPTIONS statement at the bottom of a complicated query. Without falling back to raw sql mode, how do I specify the OPTIONs using the knexjs QueryBuilder?

For example, suppose I had this SQL statement that I want to write in Knex:

```
SELECT * 
FROM FOO AS F JOIN BAR AS B ON F.ID = B.ID
OPTION (USE HINT('FORCE_LEGACY_CARDINALITY_ESTIMATION'))
```

The select statement would look like:

```
knex('FOO AS F')
  .innerJoin('BAR AS B', 'A.ID', 'B.ID')
  .select()
```

Now, the QueryBuilder has an options() function, but I haven't found documentation on how to use it. I am not even sure if it's the write property to be able to specify **_OPTION (USE HINT('FORCE_LEGACY_CARDINALITY_ESTIMATION'))_**

```
knex('FOO AS F')
  .innerJoin('BAR AS B', 'A.ID', 'B.ID')
  .select()
  .options( ????? )  // What goes in here?
```

**Comment by elhigu** [comment]
IIRC .options() is for passing special options to driver's method that actually executes the query.

I don't think that the query is possible to do without `.raw`. I would create the query above like this:

```
knex.raw(`? OPTION (USE HINT('FORCE_LEGACY_CARDINALITY_ESTIMATION'))`, [
  knex('FOO AS F').innerJoin('BAR AS B', 'A.ID', 'B.ID')
])
```

Downside with that query is that the result is direct result from the mssql driver so the result object is not directly an array of rows.
