### ISSUE TITLE
pool.idleTimeoutMillis not working, idle connections never seem to time out

### ISSUE THREAD

**Issue by timd73** [knex/knex#4525]
# Environment

Knex version: 0.95.6
Database + version: PostgreSQL 13.2 
OS: MacOS

# Bug

I am trying to set a low idle timeout for the connections in the pool.
I am using knex like:

```
const knex = knex({
        client: 'pg',
        connection: {
            host: ...,
            user: ...,
            password: ...,
            database: ...
        },
        pool: {
            idleTimeoutMillis: 10 * 1000
        }
    })
```

No matter what I set for `idleTimeoutMillis`, the idle connections show up in postgres for a long time.  

I am checking those with

`SELECT * FROM pg_stat_activity WHERE datname = 'DATABASE_NAME'`

When I do something similar with the native `Pool` from the `pg` module, the connections disappear as expected.

Seems like a bug, but how do I diagnose further.  can anyone reproduce?

Thanks!

**Comment by elhigu** [comment]
I have no idea if pool (Tarn) is actually set to destroy discarded connections... should be verified from code what is done for them. Pg's pool is not used by knex so it has nothing to do with this issue.

**Comment by timd73** [comment]
@elhigu , I know that Pg's pool is not used by knex. I was giving that information point just for comparison.
If Tarn's pool is not set to destroy idle connections, what's the meaning of the (documented) `idleTimeoutMillis` setting on the pool? 

tarn docs say
```
// free resouces are destroyed after this many milliseconds
  idleTimeoutMillis: 30000,
```
I also tried setting `reapIntervalMillis` but it didn't have an effect.

**Comment by timd73** [comment]
Found the issue.
I need to set `max: 0` on the pool if I want it to destroy all idle connections.  I think this is very unintuitive behavior on Tarn's part but I guess it's according to spec.

**Comment by elhigu** [comment]
`max: 0` is not the config you should be setting... it should be `min: 0` which allows all idle connections to be removed from pool.. 

It would be really unintuitive if all connections would be cleaned up from pool if configuration says that it should keep e.g. minimum of 5 connections there.

**Comment by timd73** [comment]
I meant min, of course.  I see what you mean, on the other hand, timing out idle connections could be done regardless. I guess because I didn’t specify a min, and apparently it defaults to 2, it seemed unintuitive to me. But you’re right that if I specified min, I’d expect idle connections up to the min to persist.  Not sure I understand why the default would be 2.  Seems like it should be 0.

**Comment by elhigu** [comment]
> I meant min, of course.

Roger 👍 makes more sense. 

> I see what you mean, on the other hand, timing out idle connections could be done regardless.

That is basically the only thing where `min: 0` configuration has an effect on. So if they would be timed out regardless of `min` value, the whole setting should be removed, since it would not do anything. 

> Not sure I understand why the default would be 2. Seems like it should be 0.

I agree that 0 would be better default for it. It is 2 because of historical reasons when different pools were used, which also did behave in different manner when initialised for the first time.
