### ISSUE TITLE
set Postgres date/time

### ISSUE THREAD

**Issue by Isaquedias** [knex/knex#4526]
# Environment

Knex version: 0.21.19
Database + version: PostgreSQL 9.6.20 
OS: (Ubuntu 9.6.20-1.pgdg18.04+1)

# Feature discussion / request

I need to pass a configuration to the imported Postgres instance, which is inside the file "node_modules\knex\lib\dialects\postgres\index.js"
on line 49
" var pg = require('pg');
    var types = pg.types;
    types.setTypeParser(1114, function (stringValue) {
      return stringValue+'Z';
    });
    return pg;"

knex does not give me the possibility to do this configuration and if there is a way to do this I would like to know

![image](https://user-images.githubusercontent.com/20850432/122238987-f4a80380-ce96-11eb-9db9-7208f932674d.png)

**Comment by FelipeEmerim** [comment]
If you want to override a type parser, you can do that before initializing knex in your code. 

```javascript
    types.setTypeParser(1114, val => val);
    return knex({
        client: 'pg',
        connection: {
          host : 'localhost',
          user : 'postgres',
          password : '',
          database : 'localDB',
        }
    })
```

**Comment by elhigu** [comment]
This feature is out of scope of knex. Each DB driver has their own methods how to setup parsing values from SQL to javascript values. 

Something like what @FelipeEmerim is suggesting works for postgresql. `pg = require('pg'); pg.types.setTypeParser()`
