### ISSUE TITLE
heap out memory issue.

### ISSUE THREAD

**Issue by manjuhubballi02** [knex/knex#4559]
I was starting my node application and running react application. after 5 min getting a memory issue. can anyone please look over here?
verison:
knex :v0.16.5
node :v12.16.3
<--- Last few GCs --->
5)[13792:0000017CED66F5B0]   115487 ms: Mark-sweep 2046.8 (2051.4) -> 2046.3 (2051.9) MB, 948.3 / 0.0 ms  (+ 75.5 ms in 16 steps since start of marking, biggest step 30.0 ms, walltime since start of marking 1034 ms) (average mu = 0.101, current mu = 0.010) [13792:0000017CED66F5B0]   116884 ms: Mark-sweep 2047.1 (2051.9) -> 2046.6 (2052.1) MB, 1357.6 / 0.0 ms  (+ 34.0 ms in 12 steps since start of marking, biggest step 10.0 ms, walltime since start of marking 1396 ms) (average mu = 0.048, current mu = 0.003)

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7A6BA6C4D]
Security context: 0x027f815008d1 <JSObject>
    1: _parsePacket [000003B2703D1049] [E:\Official Projects\Conti\node_modules\mysql\lib\protocol\Protocol.js:~242] [pc=0000034E10662AB6](this=0x02ddea03c1d1 <Protocol map = 000001AA220BA8B9>)
    2: arguments adaptor frame: 1->0
    3: /* anonymous */ [000002DDEA03C2A1] [E:\Official Projects\Conti\node_modules\mysql\lib\Connection.js:~87] [pc=0000034E105...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7A5F9D1EF napi_wrap+113103
 2: 00007FF7A5F3CA66 v8::base::CPU::has_sse+64982
 3: 00007FF7A5F3D8F3 v8::base::CPU::has_sse+68707
 4: 00007FF7A6759BBE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7A6741C91 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7A660E1EC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7A6619420 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7A6615F44 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7A660B743 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7A6609DB4 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7A662B0FB v8::internal::Factory::NewFixedArrayWithFiller+107
12: 00007FF7A66240C7 v8::internal::Factory::InternalizeString<unsigned short>+471
13: 00007FF7A647DD79 v8::internal::HashTable<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::NewInternal+57
14: 00007FF7A647D55C v8::internal::HashTable<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::New+108
15: 00007FF7A647D276 v8::internal::BaseNameDictionary<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::New+22
16: 00007FF7A64B80BB v8::internal::JSReceiver::HasProperty+10731
17: 00007FF7A64B930F v8::internal::JSObject::MigrateToMap+351
18: 00007FF7A649AE05 v8::internal::LookupIterator::ApplyTransitionToDataProperty+485
19: 00007FF7A646ACF1 v8::internal::PrototypeUsers::Add+2081
20: 00007FF7A6485B0D v8::internal::Object::SetProperty+237
21: 00007FF7A637E94F v8::internal::Runtime::SetObjectProperty+303
22: 00007FF7A637DD15 v8::internal::Runtime::GetObjectProperty+17909
23: 00007FF7A6BA6C4D v8::internal::SetupIsolateDelegate::SetupHeap+546637

**Comment by elhigu** [comment]
can be re-opened if some information sis provided that suggests this being bug in knex.
