### ISSUE TITLE
rowNumber does not exist

### ISSUE THREAD

**Issue by yuchi518** [knex/knex#4561]
# Environment

Knex version: 0.95.6
Database + version: PostgreSQL 13
OS: Linux

@lorefnon

# Bug

1. I got an error in following code.
`knex
        .select('*')
        .rowNumber('row_number', orderByString)
        .from(tableName)`

2. Error message
TS2339: Property 'rowNumber' does not exist on type 'QueryBuilder  []>'.

Thanks.
Yuchi

**Comment by nguymin4** [comment]
@yuchi518 @elhigu This was fixed in #4544 and released with Knex version 0.95.7

**Comment by elhigu** [comment]
Ok, closing 👍
