### ISSUE TITLE
Knex Seed: Keep track of ran seed files so that on subsequent run command runs only the newly added seeds

### ISSUE THREAD

**Issue by sandeepjadhav** [knex/knex#4562]
# Environment

Knex version: 0.21.1
Database + version: Postgres 12.7
OS: Windows 10

I am new to the knex. 

# Feature discussion / request

While working with migrations and seeds I am not table to run the seeds for the multiple times as it throws foreign key error.

Do the knex has feature keep track of the ran seed files like migrations so that only newly added seeds files can run for the subsequent runs.?

I used this feature while using sequelize ORM in other project.

As there will be huge data in other tables reference to the master data. When we want add only few records to the existing table delete old one and add new is not possible because of foreign key issue.

**Comment by elhigu** [comment]
This has been discussed already few times. Seed files with tracking is effectively the same thing that migrations. 

Some related issues... 

https://github.com/knex/knex/issues/4074
https://github.com/knex/knex/issues/3456
https://github.com/knex/knex/issues/2010
https://github.com/knex/knex/issues/579

though I was not able to find anything that had the most elaborate discussions about this
