### ISSUE TITLE
Rollback does not work as expected

### ISSUE THREAD

**Issue by mdomasevicius** [knex/knex#4570]
# Environment

Knex version:  0.95.6,
Database + version: MYSQL 8.0.25
OS: Manjaro

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Config:
```typescript
const config: Knex.Config = {
    client: 'mysql',
    connection: {
        host: process.env.DB_HOST,
        port: process.env.DB_PORT ? parseInt(process.env.DB_PORT) : undefined,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_DATABASE,
    },
    migrations: {
        tableName: 'migrations',
        directory: 'src/db/migrations',
        schemaName: 'test',
    },
};

const db = knexLib(config)
db.migrate.latest()
    .then(() => logger.info("DB Migration success"))
    .catch(ex => {
        logger.error(`DB Migration error:\n${ex}`)
        db.migrate.rollback()
            .then(() => logger.warn("DB migration rolled back"))
            .catch(ex => logger.error(`DB migration rolled back failed: ${ex}`))
            .finally(() => process.exit(1))
    })
```

Two migration files

```typescript
export async function up(knex: Knex): Promise<void> {
    return knex.schema
        .createTable('users', t => {
            t.bigIncrements('id').primary().unsigned()
        })
}


export async function down(knex: Knex): Promise<void> {
    return knex.schema.dropTable('users')
}
```

```typescript
export async function up(knex: Knex): Promise<void> {
    return knex.schema
        .createTable('orders', t => {
            t.bigIncrements('id').primary().unsigned()
            t.bigInteger('user_id').references('id').inTable('users').index('idx_user_orders_user_id')

        })
}


export async function down(knex: Knex): Promise<void> {
        return knex.schema.dropTable('orders')
}

```

![image](https://user-images.githubusercontent.com/20511486/125280186-73b91c00-e31d-11eb-8100-81b6d4b0ef32.png)

`t.bigInteger('user_id').references('id').inTable('users').index('idx_user_orders_user_id')` - is a bug, `user_id` is signed while `users.id` is not. This will fail migration.

**Expected** - rollback is executed  for failed migration file (the one that creates `orders` table)
**Actual** - rollback is executed on the `users` migration script, users table is deleted and `orders` table remains. Even If I run users migration first, and only afterwards I run `orders` on a second run.

2. Error message

```
Error: alter table `orders` add constraint `orders_user_id_foreign` foreign key (`user_id`) references `users` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'orders_user_id_foreign' are incompatible.
```

EDIT (1):

The confusion comes from the fact that `orders.user_id` foreign constraint creation fails, but for whatever reason, the table is created. My understanding is that every migration file is suppose to run in transaction and if it fails it is rolled back. It does not happen. It seems that Table `orders` and foreign key constraint are executed in separate transactions.

**Comment by elhigu** [comment]
If running migration fails, then its down script is implicitly called and migration is not written to database. So you should not call .rollback() on migration fail.
