### ISSUE TITLE
Why am I unable to rollback my migrations?

### ISSUE THREAD

**Issue by lilfrootyloops** [knex/knex#4575]
# Environment

Knex version: 0.95.7
Database + version: PostgreSQL, 13.2
OS: macOS 10.15.7 (19H1217)

# Bug

After my tech lead implemented a new role permissions system in our application, I've been unable to clear the database via rolling back migrations. The command I usually run is `knex --env local migrate:rollback --all`. It seems as though the new migration file (i.e., 12345_updatePermissions.js) my tech lead created is what's causing the issue, since in my terminal I get returned the following error:

```
migration file "12345_updatePermissions.js" failed
migration failed with error: alter table "User" alter column "role" type text check ("role" in ('Admin', 'SuperUser', 'User')) using ("role"::text check ("role" in ('Admin', 'SuperUser', 'User'))) - syntax error at or near "check"
error: alter table "User" alter column role" type text check ("role" in ('Admin', 'SuperUser', 'User')) using ("role"::text check ("role" in ('Admin', 'SuperUser', 'User'))) - syntax error at or near "check"
```

I tried looking for a "check" in 12345_updatePermissions.js; however, I was not able to find it. The following is the contents of 12345_updatePermissions.js:

```
const tableName = 'User';

exports.up = async (knex) => {
  await knex.schema.alterTable(tableName, (table) => {
    table.dropColumn('role');
  });
  await knex.schema.alterTable(tableName, (table) => {
    table.enu('role', ['Owner', 'Admin', 'Researcher', 'AdvancedResearcher', 'User']).defaultTo('User');
  });
};

exports.down = async (knex) => {
  await knex.schema.alterTable(tableName, (table) => {
    table.enu('role', ['Admin', 'SuperUser', 'User']).defaultTo('User').alter();
  });
};
```

I've tried removing the alter() method at the end of the exports.down function, but to no avail (I really didn't think this would help, but I was desperate to try something). I don't know what else I should change to resolve this. I'd really appreciate it if someone could help me make sense of the error, especially the "check", and explain how I could go about fixing it.

**Comment by elhigu** [comment]
Documentation probably should list types which are supported by .alter(). With enums it doesn't seem to make very reasonable queries.

**Comment by elhigu** [comment]
To alter check constraint type of your enum you first need to drop the old constraint and then create a new one. Also with down script you would need to decide what to do with rows, which has `AdvancedResearcher` role set.

**Comment by lilfrootyloops** [comment]
Hi @elhigu, thanks for helping me out! Could you please explain what you mean by "drop the old constraint." What is the "old constraint" and how would I go about dropping it?

**Comment by elhigu** [comment]
If you have created enum, it is usually done as a string column that has `CHECK` constraint, with values that are allowed to be set to that column. So you can drop that constraint with `knex.schema.raw()` and probably you will also need `.raw` for creating a new constraint with updated enum values.

**Comment by lilfrootyloops** [comment]
I appreciate your taking the time to help me, but I still don't understand how to apply what you've explained. Furthermore, my issue isn't resolved yet, so I'm a bit confused as to why you closed this issue.

**Comment by elhigu** [comment]
The issue was closed , because it doesn't seem to be a bug rather than missing documentation that does not mention about limitations of the .alter(). 

The rest of the question is about general  SQL knowledge which should be asked about in knex gitter or stackoverflow. Also if someone has time to explain further about enums that are implemented as string columns that has check constraint for making sure that invalid strings are not set to column it can be still be discussed here further.

**Comment by PhakornKiong** [comment]
@lilfrootyloops 

I think the `Drop the old constaint` is something like this (Not exactly for ur case, but could be similar)

Just quick info, what I was doing is that I'm `incrementally` adding column to the table, and I wanted to have a default value for the column since it can't be `null`. Yet I do not want the `constraint` of the table to be there after the migration, hence I remove it using `.raw()`

```Javascript
exports.up = function(knex) {
  return (
    knex.schema
      .table('someTable', function(table) {
        table
          .string('user', 50)
          .notNull()
          // This creates the constraint
          .defaultTo('1', { constraintName: 'df_template_user_migrate' });
      })
      // To drop the default value constaint while updating table
      .raw(`ALTER TABLE someTable DROP CONSTRAINT IF EXISTS df_template_user_migrate;`)
  );
};

exports.down = function(knex) {
  return knex.schema.table('someTable', function(table) {
    table.dropColumn('user');
  });
};

```

To visualize what is the roadblock, you should try to look at the schema from ur DB and figure out which `constraint` you need to remove.

**Comment by lilfrootyloops** [comment]
I ended up solving my issue after playing around with the script for a bit. All I had to do was swap out table.enu('role', ['Admin', 'SuperUser', 'User']).defaultTo('User').alter() in favor of table.dropColumn('role') in line 14. The following is the contents of the updated 12345_updatePermissions.js:

```
const tableName = 'User';

exports.up = async (knex) => {
  await knex.schema.alterTable(tableName, (table) => {
    table.dropColumn('role');
  });
  await knex.schema.alterTable(tableName, (table) => {
    table.enu('role', ['Owner', 'Admin', 'Researcher', 'AdvancedResearcher', 'User']).defaultTo('User');
  });
};

exports.down = async (knex) => {
  await knex.schema.alterTable(tableName, (table) => {
    table.dropColumn('role');
  });
};
```
