### ISSUE TITLE
Not passing useTz in datetime column creation results in "datetime without timezone

### ISSUE THREAD

**Issue by armandAkop** [knex/knex#4577]
# Environment

Knex version: ^0.21.17
Database + version: postgres 13
OS: MAC OS Catalina 10.15.7
Additional Info: Running this with docker-compose using the latest postgres image (v13), node 14-alpine

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I'm not sure if this is a bug with knex, or just a [documentation bug](https://knexjs.org/#Schema-datetime). I created a datetime column and did not provide a "useTz". According to the documentation above, it should default to true (and by my understanding, column data type should be `datetime with timezone`

> Adds a datetime column. By default PostgreSQL creates column with timezone (timestamptz type). This behaviour can be overriden by passing the useTz option (which is by default true for PostgreSQL).

I expected to get a column with type `datetime with timezone` but instead I received `datetime without timezone`.

2. Error message

N/A

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Here is the migration file
```node
exports.up = async (knex) => {
  await knex.schema
    .createTable('my_table', function (table) {
      table.datetime('modified_date_useTz_not_provided', { precision: 6 }).defaultTo(knex.fn.now(6));
      table.datetime('modified_date_useTz_true', { precision: 6, useTz: true }).defaultTo(knex.fn.now(6));
      table.datetime('modified_date_useTz_false', { precision: 6, useTz: false }).defaultTo(knex.fn.now(6));
    });

};

exports.down = async (knex) => {
  await knex.schema.dropTable('my_table');
};

  
exports.config = { transaction: false };

```

When I query my table schema + type
```sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'my_table';
```

I see this
![Screen Shot 2021-07-16 at 3 47 52 PM](https://user-images.githubusercontent.com/3230752/126015447-97486594-d203-478a-88d2-ccb8f09d660a.png)

**Comment by elhigu** [comment]
Looks like a bug, PR welcome.

**Comment by zeotuan** [comment]
Hi i want to work on this. Do i need to get assigned or i can just work and create a PR?

**Comment by kibertoad** [comment]
@zeotuan Go ahead!

**Comment by zeotuan** [comment]
After some poking around i found out that only when datetime or timestamp is created using option providing both useTz and precision is created with the correct type.

Easiest way to recreate the problem no database required (look abit ugly though)
![image](https://user-images.githubusercontent.com/48720253/126055863-4763fb03-c0db-446b-975b-c38633607ea3.png)
result:
![image](https://user-images.githubusercontent.com/48720253/126055877-f582bbb6-7379-4fff-af9c-6701069cd2d0.png)

I have made a Pull Request for this.

**Comment by zeotuan** [comment]
@kibertoad Hi i think this issue should be closed.
