### ISSUE TITLE
knex js snippet (auto complete) doesn't work?

### ISSUE THREAD

**Issue by tishko18** [knex/knex#4583]
in previous version I hadn't problem in knex.js, but in latest version when I wanna write code snippet(auto complete) doesn't work?

thanks

**Comment by kibertoad** [comment]
I think it is same problem as described here: https://github.com/knex/knex/issues/4346
Best solution would be to use TypeScript, that would provide perfect autocomplete.
Other than that, if you can come up with a way that preserves current typing structure, and also is friendly with JS autocompletion, please send in a PR!

**Comment by kibertoad** [comment]
Also https://github.com/knex/knex/issues/4392

**Comment by kibertoad** [comment]
Released in 1.0.1.
