### ISSUE TITLE
Incorrect version 0.21.20 registered with npmjs.com registry (rather than current 0.95.8)

### ISSUE THREAD

**Issue by EntropyAu** [knex/knex#4610]
It appears an old version of knex may have been accidentally published to npmjs.com (https://www.npmjs.com/package/knex) - we're seeing version 0.21.20 rather than the latest 0.95.8 version (per the repository change log).

**Comment by kibertoad** [comment]
Interesting that it would pick it up as latest. It was no mistake, there was a hotfix in older branch. I'll publish a new 0.95 to set versions properly, though.

**Comment by kibertoad** [comment]
Fixed
