### ISSUE TITLE
0.21.20 has DOS line terminators

### ISSUE THREAD

**Issue by ParallelUniv3rse** [knex/knex#4611]
# Environment

Knex version: 0.21.20
Database + version: PostgreSQL 13
OS: MacOS 11.2.1

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

knex migrate:latest fails with error 
`env: node\r: No such file or directory`
The same issue has been observed before in https://github.com/knex/knex/issues/3598.

**Comment by kibertoad** [comment]
thanks, will try to fix today, but probably we also need a test for this :-/

**Comment by TiagoGouvea** [comment]
You owe me one day of life because today I just debugged.
😅

**Comment by elhigu** [comment]
@TiagoGouvea Luckily we have countless days already in our "time invested to knex bank", so feel free to take one of those 👍

**Comment by TiagoGouvea** [comment]
I love you guys! Thanks for everything you have done! 😁

**Comment by kibertoad** [comment]
Could you please test 0.21.21 and report back?

**Comment by jrohland** [comment]
0.21.21 fixed this issue for me.
