### ISSUE TITLE
Knex breaking on migrate: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by netogerbi** [knex/knex#4614]
# Environment

Knex version: 0.21.20
Database + version: Postgres 12.4
OS: Debian Buster

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I'm using NodeJS 12.18.3 and yarn. I was using knex version 0.21.17. When I updated the yarn package to 0.21.20 and ran test command, when knex started the migrations, it breaks with the following:

2. Error message (logs for command "yarn test")
```bash
$ NODE_ENV=test yarn knex migrate:rollback --all && NODE_ENV=test yarn knex migrate:latest
$ /home/neto/workspace/epayment/EEJS/epayments-v4/api/node_modules/.bin/knex migrate:rollback --all
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
```

"yarn test" command in package.json: 
```bash
yarn lint && yarn style:check && NODE_ENV=test yarn test:unit && NODE_ENV=test yarn test:functional
```
But even with "yarn knex --help" it breakes.

When I set up the previous version again, it fixed.

**Comment by kibertoad** [comment]
Could you please try 0.21.21 and report back?

**Comment by netogerbi** [comment]
> Could you please try 0.21.21 and report back?

solved! thank you very much!
