### ISSUE TITLE
Version 0.21.21 published as "latest"

### ISSUE THREAD

**Issue by leedm777** [knex/knex#4617]
When 0.21.21 was published the other day, it was published as `latest` in npm.

```
❯ npm info knex
<snip/>

dist-tags:
beta: 0.21.5-next1             next: 0.95.0-next3             
latest: 0.21.21                oracle-fix: 0.16.6-oracle-fix  

published 2 days ago by kibertoad <iselwin@gmail.com>
```

Given that the past several releases have been 0.95.x releases, and the version listed on https://knexjs.org is 0.95.x, I'm assuming that this is a mistake.

Please update the `latest` dist-tag to 0.95.9.

**Comment by moshen** [comment]
This made for a very confusing project setup for me

**Comment by abdulrahman-khankan** [comment]
@elhigu do you have author permissions for the npm package so that you can fix the `latest` tag?

**Comment by kibertoad** [comment]
@abdulrahman-khankan I'll fix it today, sorry, was a bit of a hectic time.

**Comment by kibertoad** [comment]
Fixed.
