### ISSUE TITLE
[Feature Request] - Allow use of aliased column names in where clause.

### ISSUE THREAD

**Issue by Collin3** [knex/knex#4627]
# Environment

Knex version: 0.95.9
Database + version: MSSQL version 14
OS: Linux

# Feature discussion / request

### Use Case
Enable use of aliased column names within where, order by, group by, etc. methods.

### Example
What (I believe) is required by knex today:
```js 
knex.column('title', {by: 'author'}, 'year').select().from('books').where({author: 'J.R.R. Tolkien'});
```
What could make for a better developer experience: 
```js
knex.column('title', {by: 'author'}, 'year').select().from('books').where({by: 'J.R.R. Tolkien'});
```
Just pulling that example from the knex docs, but might not make for the greatest argument for that use case. Something more realistic might be where your API model surfaces attributes in camel case, but database columns are snake case, or you're working with a legacy database that has poorly named columns that you have aliased in API models to be more descriptive. Being able to use the where clause with those aliases would prevent some mapping that would otherwise need to happen in those situations.

A better visualization might be 
```js
knex.select({
  title: 'title',
  author: 'author',
  publishDate: 'publish_date',
  publishingCompany: 'publishing_company'
}).select().from('books').where({publishingCompany: 'the best publishing company ever'});
```

### API Proposal/How it would work
Could probably be done entirely behind the scenes where you just persist the aliased columns, then when building the query statement(s) that will actually be run you would reference the aliased columns and flip the aliased names over to the database column name for potential where clauses, order by or group by statements.

Alternatively, if we wanted to expose it via the Knex API you could do something like this
```js
knex
.withColumnMap({
  title: 'title', 
  by: 'author', 
  year: 'year'
}).select().from('books').where({by: 'J.R.R. Tolkien'});
```
And then if, and only if, the `withColumnMap` is used, you would do that extra lookup/mapping when producing the where/group by/order by statements that will be run.

**Comment by elhigu** [comment]
Aliases already work the way you described.

The last query can be written like:

```
knex
.select({
  title: 'title', 
  by: 'author', 
  year: 'year'
}).from('books').where({by: 'J.R.R. Tolkien'})
```

and it generated valid SQL with correct aliases and uses them when filtering rows. It is plain SQL feature, knex doesn't have to do anything special to make it work.

**Comment by Collin3** [comment]
Oh weird 🤔  when I use that syntax using knex on Microsoft SQL Server I get
```
RequestError: select [title] as [title], [author] as [by] from [books] where [by] = @p0 - Invalid column name 'by'.
```
I feel like I must be missing something

**Comment by elhigu** [comment]
Strange... according to https://www.sqlservertutorial.net/sql-server-basics/sql-server-alias/ they should work just fine also with SQL Server.
