### ISSUE TITLE
Inserting an empty array into a JSONB column

### ISSUE THREAD

**Issue by exoRift** [knex/knex#4635]
# Environment

Knex version: 0.95.3
Database + version: PostgreSQL 11.12
OS: Debain 10

# Bug

Inserting an empty array (unstringified) into a Postgres JSONB column ends up being an empty object

**Comment by kibertoad** [comment]
Does it work correctly when using `pg` driver directly?

**Comment by exoRift** [comment]
Using `toString()` on the query confirms that it's Knex's doing

![image](https://user-images.githubusercontent.com/20345400/130375410-7206a0a6-5f49-4db6-a01b-b915261393e4.png)

**Comment by elhigu** [comment]
Actually that doesn't prove anything, since knex is not using `.toString()` when executing queries. Most accurate result what is sent to DB driver can be get by calling `.toSQL().toNative()` which returns template SQL string + bindings.

Though when you are writing JSON to jsonb column you need first convert the input data to json. In this case: `JSON.stringify([])` should do.

**Comment by exoRift** [comment]
Regardless of the fact of whether `toString` is used, it's still a Knex-isolated method that's converting an empty array to an object which seemingly implies that the other methods do the same.

Also, how come Knex doesn't auto-stringify, if you don't mind me asking?

**Comment by kibertoad** [comment]
@exoRift @elhigu They way knex handles json fields is by simply calling `toString()` on them, and not JSON.stringify. I'm not sure why it's done that way and whether there are any downsides to doing stringifying on our end already. @elhigu Any thoughts? Existing behaviour doesn't seem very helpful, I can't imagine anyone depending on it. We might want to throw an error if we get an object there, to make behaviour less surprising.

**Comment by elhigu** [comment]
> Regardless of the fact of whether toString is used, it's still a Knex-isolated method that's converting an empty array to an object which seemingly implies that the other methods do the same.

@exoRift I have no idea what do you mean by that?

@kibertoad  I don't think that knex even calls `.toString()` in this case https://runkit.com/embed/s9zq3a5rblem 

As I said, knex cannot possibly decide how array should be stringified in every case. Knex does not know to which kind of query the value is passed to. Historically postgres `{}` array format was used when outputting arrays in debug `query.toString()` calls. 

I drafted helpers to allow to tell which kind of array format is passed to query around the same time, when I implemented ref/lit support to objection... I did find here some old discussions about the subject :

https://github.com/knex/knex/issues/791#issuecomment-384375606
https://github.com/knex/knex/issues/2229
https://github.com/knex/knex/issues/3805

Anyways basically at least JSON.stringify(), `{}`, `()` and `[]` formats should be supported with helpers I suppose.
