### ISSUE TITLE
In postgres array is being converted to JSON in JSONB type column

### ISSUE THREAD

**Issue by mistercorea** [knex/knex#4642]
# Environment

Knex version: "0.95.10"
Database + version: postgres 13.3
OS: OSX

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Inserting an array to a JSONB typed column.

table create
```
CREATE TABLE cost.budgets (
    id uuid NOT NULL,
    locations jsonb
);
```

json data
```
[
  {
    "id": "0bad78ee-06d2-4e1f-bfad-0934681d6ebc",
    "locations": ["664fa3e0-bcf3-49c0-b034-fd8db98e4903"]
  }
]
```
the original location value is in an array  like
```
[ '664fa3e0-bcf3-49c0-b034-fd8db98e4903' ]
```
but it converts to `{ '664fa3e0-bcf3-49c0-b034-fd8db98e4903' }`

```
knex(`budgets`).insert(rows)
```
raw query looks like
```
insert into "budgets" (
    "id",
    "locations"
  )
values (
    '0bad78ee-06d2-4e1f-bfad-0934681d6ebc',
    '{"664fa3e0-bcf3-49c0-b034-fd8db98e4903"}',
  )
```
It is not the problem with the validation but somehow it is trying to convert array to INVALID JSON.

2. Error message
```
severity: 'ERROR',
  code: '22P02',
  detail: 'Expected ":", but found ",".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: {"6038bb4e-9bcf-4828-b96c-b8f4cfa73273",...',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'jsonfuncs.c',
  line: '621',
  routine: 'json_ereport_error'
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by mistercorea** [comment]
https://github.com/knex/knex/blob/e469766689712e46744a71511614541d7e809f5e/lib/dialects/postgres/index.js#L306
This is causing the problem but I am not sure why it is converting array to wrapped with`{}`

**Comment by elhigu** [comment]
duplicate https://github.com/knex/knex/issues/4635

**Comment by mistercorea** [comment]
OK. 

basically, the value needs to be converted to stringify before it can be inserted.

```
[
  {
    "id": "0bad78ee-06d2-4e1f-bfad-0934681d6ebc",
    "locations": JSON.stringify(["664fa3e0-bcf3-49c0-b034-fd8db98e4903"])
  }
]

```

that worked. it's a bit awkward but it will do the job.
