### ISSUE TITLE
Sqlite JSON is string

### ISSUE THREAD

**Issue by ald890** [knex/knex#4655]
# Environment

Knex version: 0.95.10
Database Sqlite3 5.0.0
OS: Linux

# Bug

A column with a json type, does not return json, but a string.
I have schema with:
`
table.json('stack')
`

But knex returns this represenation:
`
stack: "[\"Javascript\",\"NodeJs\",\"React\",\"PHP\",\"Ruby\"]"
`

**Comment by KristjanTammekivi** [comment]
The parsing is done inside the client you're using.
I guess in your case you can use postProcessResponse https://knexjs.org/#Installation-post-process-response

**Comment by ald890** [comment]
The problem exists only in Sqlite3, I checked the same project and database in Postgres and JSON parsing works.

**Comment by kibertoad** [comment]
@ald890 Then it should be fixed on SQLite driver level.

**Comment by elhigu** [comment]
This is out of scope of knex.
