### ISSUE TITLE
InnerJoin with andWhere doesn't work correctly

### ISSUE THREAD

**Issue by emmesbef** [knex/knex#4660]
# Environment

Knex version: 0.95.9
Database + version: MS-SQL 12.0.6433.1
OS: Windows 10

@smorey2 

# Bug
when Using andWhere with InnerJoin leads to undefined result. The resulting SQL-Statement which is build does work on the Server without any Problems.
code example:
```javascript
await knex
    .select('column_name')
    .from('tableA')
    .innerJoin('tableB', 'tableB.column', 'tableA.column')
    .where('tableA.column', '=','value')
    .andWhere('tableB.column', '=' ,'value');
```
This results in the following SQL build by knex:

```sql
select [column_name] from [tableA] 
inner join [tableB] on [tableA].[column] = [tableB].[column] 
where [tableA].[column] = @p0 
and [tableB].[column] = @p1
```

where the binding p0 and p1 have the correct values.

is there any known bug or did i called something wrong? I appreciate any help

**Comment by KristjanTammekivi** [comment]
Not sure what you mean but this seems to work just fine https://runkit.com/kristjantammekivi/614370c214eb660008432880

**Comment by emmesbef** [comment]
> Not sure what you mean but this seems to work just fine https://runkit.com/kristjantammekivi/614370c214eb660008432880

your example is working with sqlite - my issue is with mssql

**Comment by elhigu** [comment]
I cannnot see anything wrong in that query. What kind of query are you expecting? 

Can be reopened if this end up to look like a bug in knex.

All looks good here as well https://runkit.com/embed/fpeyz1vdbl1x

**Comment by emmesbef** [comment]
> I cannnot see anything wrong in that query. What kind of query are you expecting?
> 
> Can be reopened if this end up to look like a bug in knex.
> 
> All looks good here as well https://runkit.com/embed/fpeyz1vdbl1x

The Statement(query) is correct but the return result is empty. Statement which I get from the Debug( .toSQL().toNative()) message with the same values(bindings) directly fired on the Server is returning a result.

**Comment by elhigu** [comment]
What queries and parameters exactly are you running in knex and in mssql commandline? Might be problem with invalid types?

Can you try executing that query with mssql db driver directly? What result that returns? (remember to use parameter bingings)

**Comment by elhigu** [comment]
Also checking out server logs might help to see what is the difference between a query that did not return anything and with the correct query.
