### ISSUE TITLE
maybe the documentation needs to be updated

### ISSUE THREAD

**Issue by WankkoRee** [knex/knex#4662]
[https://knexjs.org/#Builder-onConflict](https://knexjs.org/#Builder-onConflict)

![image](https://user-images.githubusercontent.com/21287731/132127342-8ea70eb0-acbb-4db0-b3e9-761039e56f1c.png)

As far as I know, it uses the table's PRIMARY KEY or a UNIQUE index, right?

**Comment by maximelkin** [comment]
Yes, but knex still ignore passed columns and  build SQL without them
