### ISSUE TITLE
Knex 0.95.11 using vulnerable version 1.0.6 of path parse 

### ISSUE THREAD

**Issue by praveenphoenix42** [knex/knex#4663]
Latest version of Knex 0.95.11 is using vulnerable version 1.0.6 of path parse. Path parse 1.0.6 is vulnerable to Regular Expression Denial of Service (ReDoS) via splitDeviceRe, splitTailRe, and splitPathRe regular expressions. ReDoS exhibits polynomial worst-case time complexity. Path parse version 1.0.7 is available. 
Knex should use updated path parse version 1.0.7

**Comment by kibertoad** [comment]
Doesn't "npm update" help?

**Comment by elhigu** [comment]
Should this be closed?
