### ISSUE TITLE
Parameter 'trx' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by glensc** [knex/knex#4675]
# Environment

Knex version: 0.95.11
Database + version: MySQL 8.0
OS: macOS/Linux

# Problem

Trying to update to 0.95.x and getting type error which is not mentioned in UPGRADE documentation:
- https://github.com/knex/knex/blob/0.95.11/UPGRADING.md

```
src/MysqlClient.ts:88:33 - error TS7006: Parameter 'trx' implicitly has an 'any' type.
       import { knex, Knex } from "knex";

       const knexInstance = knex({ client: "mysql", connection: options });
88     await knexInstance.transaction(trx => {
                                      ~~~
```

I can't find any typing in examples for `trx` from https://knexjs.org/

So, how to resolve the error, and this problem should have at least a line in UPGRADING.md

**Comment by KristjanTammekivi** [comment]
Can you show a bigger example? What's the type of this.knex?

**Comment by KristjanTammekivi** [comment]
I suspect your error is originating from the first point in the upgrading guide 
![image](https://user-images.githubusercontent.com/8754356/133617003-c7a0cf87-ba5e-4fa0-8571-fe9101636f7f.png)

**Comment by glensc** [comment]
@KristjanTammekivi updated example, it's just an object created from `knex()` function. and the error is on `trx` not on `knex` instance. If I used wrong import, the error would be different (This expression is not callable, Type 'typeof Knex' has no call signatures).

**Comment by glensc** [comment]
Found tye symbol, it should be typed as `trx: Knex.Transaction`.

**Comment by glensc** [comment]
So, the question is, can somehow type inference be improved so that don't need to add type hint in a callback:
- https://www.typescriptlang.org/docs/handbook/type-inference.html

...or the upgrade document updated that the type hint is now required if `noImplicitAny` is enabled in tsconfig.
- https://www.typescriptlang.org/tsconfig#noImplicitAny

I hope for the former!

**Comment by KristjanTammekivi** [comment]
The thing is...this already works fine for me 
![image](https://user-images.githubusercontent.com/8754356/133620502-dd980ef7-dbc8-4931-8d6a-1a52381f8379.png)

**Comment by glensc** [comment]
@KristjanTammekivi try `tsc --noImplicitAny true`

**Comment by glensc** [comment]
very odd. I can not reproduce myself anymore either. I even tried to downgrade to 0.95.10, which I might had used initially.

```
➔ tsc --noImplicitAny tests/test-trx.ts
➔ ts-node tests/test-trx.ts
[ 9301 ]
➔
```

```ts
import { knex } from "knex";
import { MYSQL_DATABASE, MYSQL_HOST, MYSQL_PASSWORD, MYSQL_PORT, MYSQL_USER } from "./config";

(async () => {
  const db = knex({
    client: "mysql",
    connection: {
      host: MYSQL_HOST,
      user: MYSQL_USER,
      password: MYSQL_PASSWORD,
      database: MYSQL_DATABASE,
      port: MYSQL_PORT,
    },
  });

  const res = await db.transaction((trx) => {
    return db('articles')
      .select('id')
      .limit(1)
      .pluck('id')
      .transacting(trx);
  });
  console.log(res);
  await db.destroy();
})();

```

**Comment by kaitlynreese** [comment]
I'm getting the same errors as @glensc here on Knex `0.95.11`:

This declaration:

```javascript
import { knex, Knex } from 'knex';

const trx: Knex.Transaction;
```
yields the error `Namespace '"/node_modules/knex/types/index".Knex' has no exported member 'Transaction'.ts(2694)`.

As well as:
``` javascript
knex.transaction((trx) => ...
```

gives `Parameter 'trx' implicitly has an 'any' type.ts(7006)`.

Downgrading to `0.95.10` also did not help. Thanks all!

**Comment by KristjanTammekivi** [comment]
Are you getting this error inside your editor or also when compiling? The only thing I can think of is that your editor might need a restart after installing the newest knex....

**Comment by kaitlynreese** [comment]
@KristjanTammekivi I get both error in the editor as well as on compilation. Thanks for your help!

```
/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
```

**Comment by kaitlynreese** [comment]
I'm on TypeScript v3.8, could this be causing issues?

**Comment by kibertoad** [comment]
@kaitlynreese Yes. Knex 0.95+ requires TS 4.1.
See https://github.com/knex/knex/blob/master/UPGRADING.md

**Comment by glensc** [comment]
@kaitlynreese different error, different problem. please create a new issue instead. closed issues are likely not monitored by maintainers.
