### ISSUE TITLE
[Oracle] Cannot make text column "notNullable"

### ISSUE THREAD

**Issue by aidenfoxx** [knex/knex#4681]
# Environment

Knex version: 0.95.11
Database + version: OracleDB 18
OS: Ubuntu

# Bug

When trying to alter a text field to be "notNullable" Oracle throws the error:

```
Error: alter table "test_table" modify "test_column" clob not null - ORA-22296: invalid ALTER TABLE option for conversion of LONG datatype to LOB
```

This can be reproduced with the following test case:

```
    await knex.schema.createTable('test_table', function (table) {
      table.text('test_column');
    });

    await knex.schema.table('test_table', function (table) {
      table.text('test_column').notNullable().alter();
    })
```

There is no data in the table, so it's not an issue of existing data containing null values.

@atiertant

**Comment by aidenfoxx** [comment]
This isn't the first time I've had similar issues with knex. This would be easily solved if we had some way to communicate that we don't want to update the underlying column type; just the constraints. For example, the following query works correctly:

`ALTER TABLE "test_table" MODIFY "test_column" DEFAULT NULL;`

It would be nice to have some kind of way to only target constraints with a syntax like:

```
table('test_column').notNullable().alter();

OR

table.column('test_column').notNullable().alter();
```

**Comment by kibertoad** [comment]
@aidenfoxx Funny that you mention that. 0.95.11 introduced exactly that, `table.setNullable()`. Can you give it a try?

**Comment by aidenfoxx** [comment]
Good timing! Yes, that absolutely works. Sorry for creating the unnecessary issue!

**Comment by kibertoad** [comment]
No worries!

**Comment by aidenfoxx** [comment]
@kibertoad Is there any particular reason why `dropNullable` isn't supported for SQLite?

**Comment by kibertoad** [comment]
@aidenfoxx Because SQLite itself doesn't support that operation, I think, when using `.alter()` approach the whole table gets rebuilt.
If you could implement a working approach for SQLite, would be more than happy to accept PR for that.

**Comment by aidenfoxx** [comment]
If I get a moment this weekend I'll look into adding it. I think the `dropNullable` function is great for overall compatibility, so it would be nice to have it working for all vendors. 😄

**Comment by kibertoad** [comment]
@aidenfoxx That would be amazing, thank you!
