### ISSUE TITLE
Key columns "role_id" and "id" are of incompatible types: integer and uuid.

### ISSUE THREAD

**Issue by slim-hmidi** [knex/knex#4682]
# Environment

Knex version: 0.95.11
Database + version: Postgresql 13.4
OS: Mac OS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

roles.ts:
```
import { Knex } from 'knex'

export async function up (knex: Knex): Promise<void> {
  // eslint-disable-next-line consistent-return
  return knex.schema.hasTable('roles').then((exists) => {
    if (!exists) {
      return knex.schema.createTable('roles', (table) => {
        table.uuid('id').primary().notNullable()
        table.string('name', 255).notNullable()
        table.boolean('deleted')
      })
    }
  })
}

export async function down (knex: Knex): Promise<void> {
  return knex.schema.raw('DROP TABLE IF EXISTS roles CASCADE;')
}
``` 
users.ts:
```
import { Knex } from 'knex'

export async function up (knex: Knex): Promise<void> {
  // eslint-disable-next-line consistent-return
  return knex.schema.hasTable('users').then((exists) => {
    if (!exists) {
      return knex.schema.createTable('users', (table) => {
        table.increments('id').primary().notNullable()
        table.string('first_name', 255).notNullable()
        table.string('last_name', 255).notNullable()
        table.string('email').notNullable().unique()
        table
          .uuid('role_id')
          .references('id')
          .inTable('roles')
          .onDelete('CASCADE')
          .onUpdate('CASCADE')
          .index()
      })
    }
  })
}

export async function down (knex: Knex): Promise<void> {
  return knex.schema.raw('DROP TABLE IF EXISTS users CASCADE;')
}
``` 

2. Error message
I got this error:
```
alter table "users" add constraint "users_role_id_foreign" foreign key ("role_id") references "roles" ("id") on update CASCADE on delete CASCADE - foreign key constraint "users_role_id_foreign" cannot be implemented
Key columns "role_id" and "id" are of incompatible types: integer and uuid.
```

**Comment by kibertoad** [comment]
`Key columns "role_id" and "id" are of incompatible types: integer and uuid.`

This is an error in your schema.

**Comment by slim-hmidi** [comment]
But ` id` in roles table is not `uuid` according to `table.uuid('id').primary().notNullable()` and I mentioned `uuid` as type to reference `role_id` in `table
          .uuid('role_id')
          .references('id')
          .inTable('roles')
          .onDelete('CASCADE')
          .onUpdate('CASCADE')
          .index()`
         
Is it wrong like that?

**Comment by kibertoad** [comment]
`        table.increments('id').primary().notNullable()` this is integer
`        table
          .uuid('role_id')
          .references('id')` this is uuid

Yes, it is wrong.

**Comment by kibertoad** [comment]
OK, I see what you are saying, you are referencing a column on another table which is allegedly also a uuid.

Can you try running SQL generated from those operations by hand in DB and see what happens? I wonder if it's knex generating wrong SQL or DB reacting in a weird way.

**Comment by kibertoad** [comment]
Before going very deep, can you check that there is no leftover old table with the wrong type? Since you are doing (a very strongly advised against) conditional schema creation, it may very well be that first migration is not executed and you have some old table structure in place.

**Comment by slim-hmidi** [comment]
I updated them:
```
return knex.schema.createTable('roles', (table) => {
        table.increments('id').primary()
        table.string('name', 255).notNullable()
        table.boolean('deleted')
      })
```
``` 
return knex.schema.createTable('users', (table) => {
        table.increments('id').primary()
        table.string('first_name', 255).notNullable()
        table.string('last_name', 255).notNullable()
        table.string('email').notNullable().unique()
        table
          .integer('role_id')
          .unsigned()
          .references('id')
          .inTable('roles')
          .onDelete('CASCADE')
          .onUpdate('CASCADE')
          .index()
      })
      ```
      And it works fine, it was due to old migrations and config.
