### ISSUE TITLE
Update set on conflict merge

### ISSUE THREAD

**Issue by Zyles** [knex/knex#4696]
# Environment

Knex version: 0.95.9
Database + version: PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
OS: Ubuntu 18.04

# Feature discussion / request

I seem to be unable to do a custom UPDATE SET when ON CONFLICT. Unless I am missing something in the docs.

How can I execute the following upsert query:

```
INSERT INTO "inventory" ("product_id", "stock_qty") VALUES (123, 10) ON CONFLICT (product_id) DO UPDATE SET "stock_qty" = 10 where inventory.product_id = '123' AND inventory.stock_qty != 10 RETURNING *;
```

Should return affected rows 1.

And when I run it a second time, it should return affected rows 0. Unless the stock_qty is changed.

I want, in my code to see if the stock_qty was updated or not and only return an affected row if it has been changed in the DB. Not on every single update.

```
const queryResult = await knex.insert({ stock_qty: 10, product_id: 123 }).into('inventory').onConflict('product_id').merge(['stock_qty']).returning('*')
```
Will always return affected rows 1, because it always merges.

**Comment by maximelkin** [comment]
```js
knex.insert({ stock_qty: 10, product_id: 123 }).into('inventory').onConflict('product_id').merge(['stock_qty']).where('stock_quantity', '!=', 10).returning('*')
```
https://knexjs.org/#Builder-onConflict
>For PostgreSQL/SQLite databases only, it is also possible to add a WHERE clause to conditionally update only the matching rows

**Comment by Zyles** [comment]
Great. That works.
