### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by tjwebb** [knex/knex#47]
I get this error when trying to do anything:

```
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

I have confirmed that I am passing the correct connection values, and I am not behind a proxy. OSX 10.8, using "pg"

**Comment by timhuff** [comment]
Might be a good policy to leave a comment on old issues, linking to the new one. I'm currently wrestling with this problem and would love to read the issue that (I assume) @tgriesser created.

**Comment by timhuff** [comment]
For future readers: My issue was running too many concurrent selects.
