### ISSUE TITLE
error: "cannot insert multiple commands into a prepared statement" when deleting from 3 tables

### ISSUE THREAD

**Issue by SharpBCD** [knex/knex#4739]
# Environment

Knex version: 0.95.6
Database + version: postgresql 12
OS: windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
```
knex.raw('
DELETE from X where some_id = :id;
DELETE from Y where some_id = :id;
DELETE from Z where some_id = :id;'
, {id: 1})
```

2. Error message
`cannot insert multiple commands into a prepared statement`

# Feature discussion / request
I need to process multiple commands, not to await each one just to use prepared statement.

**Comment by elhigu** [comment]
Try to do those queries without using parameter bindings, but hardcode ids to SQL string. 

node-pg driver doesn't seem to support  prepared statements with multiple statements packed to one query (most of the drivers actually does not support that).
