### ISSUE TITLE
Knex: autocomplete does not work in vscode v.0.95... later

### ISSUE THREAD

**Issue by mrffilipe** [knex/knex#4743]
# Environment

Knex version: v0.95.x later
Database + version: MySQL (recommended version) 
OS: windows 10

# Bug

Hello, I would like to report a bug: The bug is in the Knex.js library, the autocomplete in VSCode is not working.
NOTE* I noticed that in version 0.95... the autocomplete does not work, but in versions like 0.21.21 it works normally.

I'm using vanilla javascript (with NodeJS), files with .js extension. But like I said, in versions like 0.21.21 it's working correctly. But above version 0.95.x autocomplete does not work.

The problem with using version 0.21.21 is that I get an error from npm (message I get "found 4 high severity vulnerabilities").

NOTE* queries work normally on 0.95.x and also 0.21.21. The bug being reported by me only refers to autocomplete.

**Comment by kibertoad** [comment]
Does that work with proper autocomplete?

**Comment by FilipeMrFerracioli** [comment]
> Does that work with proper autocomplete?

Yes, it's working fine for me, I even exported: module.exports = knex(), and imported it into another file, and I get the methods correctly through autocomplete!

But why the question? do you believe this can cause any errors? is the way I did it inappropriate (if so, what would be the most appropriate way?) ?

**Comment by kibertoad** [comment]
@FilipeMrFerracioli So it works correctly, right?
