### ISSUE TITLE
[Feature] ActiveRecord like print

### ISSUE THREAD

**Issue by sidazhang** [knex/knex#475]
Is there a way to turn on query time on knex?

e.g. 
"query=SELECT \* FROM table elapsed=200ms"

If not, is there a way to override the logger in knex and add in custom logging?

**Comment by pasupulaphani** [comment]
```
knex.on("query", function (query) {
    this.on("start", function (builder) {
        const hrstart = process.hrtime();
        builder.on("end", function () {
          const hrend = process.hrtime(hrstart);
          console.log("Execution time (hr): %ds %dms", hrend[0], hrend[1]/1000000);
        });
      });
  });
```

```this.on("start"``` above only works for knex model queries but not for raw ones.
