### ISSUE TITLE
typescript: unable to import QueryBuilder interface

### ISSUE THREAD

**Issue by leshy** [knex/knex#4751]
# Environment

Knex version: 0.95.11
Typescript version: 4.4.3

@lorefnon
 
# Bug

Hi,

I'm unsure how to import a QueryBuilder generic interface? (or anything from Knex namespace defined in `index.d.ts`?)

as far as I understand the typing:

```ts
import { Knex } from 'knex'
```
will import an interface representing an active connection, knex instance.

```ts
import { knex } from 'knex'
```
imports an initialization function that returns an object conforming to a Knex interface mentioned above

yet I'm trying to get to a `QueryBuilder<TRecord, TResult>` :) 

I'm writing chainable query modifying functions used for pagination, universal filtering etc. of type:
```ts
(QueryBuilder) => QueryBuilder
```

Knex interface is quite similar to QueryBuilder so I suppose that most people use this? But I need an actual QueryBuilder for generic typing of my returns, and clone() etc calls that are not available on Knex

Thanks!

edit, my tsconfig if relevant
```json
{
  "include": ["src", "test"],
  "compilerOptions": {
    "lib": ["es2020"],
    "module": "ESNext",
    "target": "es2020",
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./src",
    "strict": true,
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "*": ["src/*", "node_modules/*"]
    },
    "esModuleInterop": true
  }
}
```

**Comment by maximelkin** [comment]
You can do it like this

```typescript
import {knex, Knex} from "knex";

const x: Knex.QueryBuilder = knex({}).where('a', 2);
```

**Comment by leshy** [comment]
> @leshy It is entirely possible that this particular interface is not exported now. Would you consider sending a PR to address that?

Yes happy to do that, I'm not sure if somehow exporting the whole Knex namespace (different name?) would be a more appropriate approach? since nothing from it seems importable atm 

> You can do it like this
> 
> ```ts
> import {knex, Knex} from "knex";
> 
> const x: Knex.QueryBuilder = knex({}).where('a', 2);
> ```

Yeah I tried this but the above doesn't compile (yet my IDE LSP doesn't complain)
```
(typescript) Error: TS2694: Namespace '"...".Knex' has no exported member 'QueryBuilder'.
```

When I import `Knex` I import an interface of the same name that represents Knex instance, and not a namespace `Knex` that contains a QueryBuilder interface definition. 

I'm not sure if this used to work as above with some other ts version or some other ts flags? (I'll update my original post to show my tsconfig)

**Comment by maximelkin** [comment]
I've tried with exactly your version of typescript and your tsconfig.json, and its working. (idk maybe i miss something)

>Namespace '"...".Knex' has no exported member 'QueryBuilder'.
It definetely imported namespace here
