### ISSUE TITLE
SELECT .. FOR NO KEY UPDATE locking clause in Postgres

### ISSUE THREAD

**Issue by domkck** [knex/knex#4754]
# Environment

Knex version: all
Database + version: Postgres 9.3 and above

# Feature discussion / request

Knex currently supports the `FOR UPDATE` and `FOR SHARE` locking clauses on select queries. Postgres has two additional lock strengths, `FOR NO KEY UPDATE` and `FOR KEY SHARE`, see https://www.postgresql.org/docs/9.6/sql-select.html#SQL-FOR-UPDATE-SHARE. Could support be added for those as e.g. `.forNoKeyUpdate()` and `forKeyShare()`?

Not sure if other DBs have an equivalent feature, or if the support would be Postgres-specific. I can contribute a PR for Postgres if needed.

**Comment by kibertoad** [comment]
PR would be appreciated!
