### ISSUE TITLE
Conditional warning for sqlite about usage of RETURNING clause (available as of sqlite >= 3.36)

### ISSUE THREAD

**Issue by joelalejandro** [knex/knex#4766]
# Environment

Knex version: v0.95.11
Database + version: sqlite 3.36 (node driver [here](/mapbox/node-sqlite3/commit/bc5d794cd7407a1aa55321fbeec3b3cf77fdc2eb))
OS: Any

# Feature discussion / request

Since commit `bc5d794cd7407a1aa55321fbeec3b3cf77fdc2eb` in mapbox/node-sqlite3, which upgrades binary sqlite to 3.36, it is now possible to use the RETURNING clause.

Knex should no longer issue a warning when using it, if the sqlite binary version is >= 3.36.

**Comment by eikaramba** [comment]
now with knex 2.0 this should be removed right?

**Comment by joelalejandro** [comment]
Closing as fixed with `2.0`.
