### ISSUE TITLE
Use REPLACE to implement Upsert operation for MySQL

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#4769]
Currently we only support Upsert for CockroachDB. Implementing same for MySQL should be pretty straightforward as well.

Wonder if we can also use INSERT ON CONFLICT UPDATE for PostgreSQL to ensure operation with same signature also works.

**Comment by Dasylum** [comment]
Can I work on this issue?

**Comment by kibertoad** [comment]
sure!

**Comment by kibertoad** [comment]
Released in 3.1.0
