### ISSUE TITLE
How to get result of knex delete operation inside a for loop

### ISSUE THREAD

**Issue by naml3i** [knex/knex#4795]
# Environment

Knex version: 0.95.11
Database + version: postgres, pg version 8.6.0
OS: Windows

# Bug (?)

The code is simple, however it involves getting Promises resolved after each step in a for loop.

```js
async function customDelete ( tableList) { 
//tableList is an object, keys = tables, values corresponding row_ids to delete in each table
  const deleted = { };
  for (const table of tableList) {
    if (table in aCheckList) {
      console.log(">> table:", table, "-- ids to delete: ", tableList[table]);

      deleted[table] = knex(table).whereIn('id', tableList[table]).del()
      .returning('id').
      .then( result => {
         deleted[table] = result;
         notDeleted = tableList[table].filter(x => !result.includes(x));
         console.log("***deleted | notDeleted:", result, notDeleted);
         if(notDeleted.length){
           console.warn('deleting', table, 'no such object(s)', notDeleted);
         }
         return result;
       });
    }
  }
  return deleted;
}
```

and the part that call `customDelete (tableList)` : 

```js
if (req.body && req.body.sync && req.body.sync.delete) {
      sync.deleted = await customDelete (req.body.sync.delete);
      console.log("deleted rows:", sync.deleted)
    }
```

Expected result: a `deleted` object: `deleted = { "table1": [1, 2, 4, 5, 6], "table2": [2,3,4,5]}` etc.
Without `await`, for `knex(table).del( )` the return object is `Promise <pending>`, with `await`, the script hangs forever.

The question is, how can I obtain the final report of the deleted rows in each table in the `deleted` object by that loop? 
I tried all methods such as `Promise.all`, `reduce( )` but still facing the same problem (deleted object not resolved).

**Comment by ggallovalle** [comment]
Try this, is working for me locally.

In the test database I only have ids 5 that is why it only prints 5.

I write in a functional style hope that is not a turn off, if it is I can help you understandint such piece.
You can derived the non deleted easilly, I did not write the code but you only need to compare the return value of the custom delete with the original argument.

![image](https://user-images.githubusercontent.com/25666813/140089663-3a666990-749d-496c-9e85-3a1fff9519be.png)


```javascript
const knex = require("knex");
// import { knex } from "knex";

const conn = knex({
  client: "pg",
  connection: "postgresql://postgres:password@localhost:5432/tempo"
});

const customDelete = (tableList) => {
  const promises = Object.entries(tableList)
    .map(([table, ids]) =>
      conn(table)
        .whereIn("id", ids)
        .del()
        .returning("id")
    );
  return Promise.all(promises)
    .then(res =>
      Object.keys(tableList)
        .reduce(([index, acc], curr) => 
          [index + 1, {...acc, [curr]: res[index]}]
          , [0, {}])[1]
    );
}


const sut = {
  a: [1, 2, 3, 4, 5],
  b: [1, 2, 3, 4, 5],
};

customDelete(sut)
  .then(res => {
    const pretty = JSON.stringify(res, null, 2);
    console.log(pretty);
  });



```

**Comment by naml3i** [comment]
@ggallovalle Thank you, it works! 
But so it turns out that my other attempts to get the batch result in an object worked too. I just found out the reason the script hanged was that there's a query to LOCK one of the table somewhere above! 😭 My bad.
