### ISSUE TITLE
0.95.13 missing from git repository

### ISSUE THREAD

**Issue by jbergstroem** [knex/knex#4797]
It seems that `0.95.13` was released on npm, but only seems to contain parts of a fix for #4784 (?).

Perhaps push a `0.95.14` with visible git history to avoid any questions with regards to the release.

**Comment by bennettp123** [comment]
0.95.14 is missing too

are these legit releases, or should we be avoiding them?

**Comment by kibertoad** [comment]
They are legit, will put up release notes tomorrow. sorry, pretty swamped

**Comment by jbergstroem** [comment]
@kibertoad is there anything contributors (like people in this issue) can contribute with in terms of helping with automation of releases?

**Comment by kibertoad** [comment]
https://github.com/knex/knex/releases/tag/0.95.14

**Comment by kibertoad** [comment]
@jbergstroem I'm not a huge fan of automating such things, they require putting in place structures that are too rigid for my tastes.
What would helped if we synced our 0.95 branch changelog with the master one, I guess, then that could be a single source of truth.
