### ISSUE TITLE
[CI] Coverage job always fails

### ISSUE THREAD

**Issue by OlivierCavadenti** [knex/knex#4814]
At this time, coverage CI job always fail in master:
https://github.com/knex/knex/actions/workflows/coverage.yml

First fail job is https://github.com/knex/knex/actions/runs/1107515551

**Comment by kibertoad** [comment]
I think something is broken in a way DB configs are resolved when we are passing a list of dbs from the commandline, judging by the errors in the console.

**Comment by intech** [comment]
@kibertoad you are right!

**Comment by intech** [comment]
@kibertoad only cockroach had problems. Most of the tests fail because the database isn't specified, most likely because the default name for the defaultdb database is used in cockroach.

I will take care of it.

**Comment by OlivierCavadenti** [comment]
@intech it seems a `knex.raw('set database = ""');` can resolve the issue but I always search where to put it in integration tests.
