### ISSUE TITLE
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by reynaldysaputra** [knex/knex#4816]
# Environment

Knex version: "^0.95.12"
Database + version: Mysql V8.0.23
OS: Mac OS Mojave 10.14.6
Next: "^10.0.3"

# Bug

I'm working on a project. Today I started getting this error: "KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?".

I've seen other posts here, that this is a problem with NODE14 and knex < 8.0.3. I'm not using this version, so I don't understand where this error is coming from? Here's some relevant info:

"dependencies": { "knex": "^0.95.13", "mysql": "^2.18.1", "next": "12.0.3", "react": "17.0.2", "react-dom": "17.0.2" }

Here is some relevant code:

**knexFile.js**

![Screen Shot 2021-11-10 at 00 17 40](https://user-images.githubusercontent.com/43536639/140972877-6f021369-ee02-4e97-a27f-c5456c3d436f.png)

Can someone help me with this issue? The error comes and goes and I don't know how to solve this. Thanks!

**Comment by BertBR** [comment]
@reynaldysaputra 

"I've seen other posts here, that this is a problem with NODE14 and knex < 8.0.3. "

I think this version is from "pg" lib. But you are using mysql database, right ? So have you tried to upgrade your mysql and knex libs to latest version according npm ?

I solved my issue updating `knex` and `pg` in my package.json to latest version and add node version in engine tag.

Check this out my package.json:

![image](https://user-images.githubusercontent.com/29619309/141199033-f3da0d97-403d-4e56-933b-465c2a4f6336.png)

I hope this may help you. Good Luck!

**Comment by reynaldysaputra** [comment]
Thanks @BertBR, this really solved my problem, cheers to you

**Comment by yudiz-bhoomit** [comment]
> @reynaldysaputra
> 
> "I've seen other posts here, that this is a problem with NODE14 and knex < 8.0.3. "
> 
> I think this version is from "pg" lib. But you are using mysql database, right ? So have you tried to upgrade your mysql and knex libs to latest version according npm ?
> 
> I solved my issue updating `knex` and `pg` in my package.json to latest version and add node version in engine tag.
> 
> Check this out my package.json:
> 
> ![image](https://user-images.githubusercontent.com/29619309/141199033-f3da0d97-403d-4e56-933b-465c2a4f6336.png)
> 
> I hope this may help you. Good Luck!

Hello @BertBR  I am still facing this issue

I have node v16.14.0, knex ^2.3.0 and pg v^8.8.0

please can you guide me how to solve this ?
]
