### ISSUE TITLE
Addition of standard sql dialect from BigQuery

### ISSUE THREAD

**Issue by cwkang1998** [knex/knex#4847]
Right now I am using BigQuery quite frequently in my day job, writing out query manually to get some analytics via firebase functions. Thought about making some helpers to help me generate some SQL code I frequently use, and thought about knex. 

A few questions regarding the addition of BigQuery support to knex:
1. Is it appropriate for it to be added as a supported dialect in knex? Considering it is not really a sql database, rather it just uses a sql dialect. 
2. Given the amount of differences in its working mechanism and functions, does it make sense to have it in knex? For example, you can create javascript user defined  function in BigQuery.

Just want some opinion regarding this, if it does make sense for knex to support this, I'll love to contribute myself, but if it does not, then maybe I'll just make it another project.

Thanks!

**Comment by OlivierCavadenti** [comment]
Seems BigQuery sql syntax have a lot of features.
I assume to add a dialect, a large part of "classic" sql features need to be in the dialect.

>Given the amount of differences in its working mechanism and functions, does it make sense to have it in knex? For example, you can create javascript user defined function in BigQuery.

The role of Knex is to abstract differences between dialects. As I see,  specific feature for 1 dialect is not really good, you lose the principal goal. So I imagine BigQuery dialect if it have enough functions of classic SQL. It seems bad if you need to implement only 1 dialect specific functions.

**Comment by cwkang1998** [comment]
I see, it does make sense. I think I'll make another project separately to deal with BigQuery (maybe I can extend knex since it has a nice API), since its quite a specific and different use case.

Thanks a lot though !

**Comment by OlivierCavadenti** [comment]
> I see, it does make sense. I think I'll make another project separately to deal with BigQuery (maybe I can extend knex since it has a nice API), since its quite a specific and different use case.
> 
> Thanks a lot though !

You can ping us when you have something, maybe the project could be alive as a side-project, plugins or whatever.

**Comment by buzzware** [comment]
This one has worked well enough for me for simple things https://github.com/lchemy/knex-bigquery-client

**Comment by kibertoad** [comment]
There are precedents of external knex dialects, e. g. https://github.com/Tomas2D/knex-firebird-dialect
