### ISSUE TITLE
t.integer('name', 8) doesnt set to int8 on postgres

### ISSUE THREAD

**Issue by mandaputtra** [knex/knex#4849]
# Environment

Knex version: 0.21.17
Database + version: postgres 13
OS: Linux, Ubuntu - Nodejs 14.x

# Bug

1. When creating migration using knex use the `t.integer('name', 8)`

2. Them migration complete but it doesnt set the integer to `int8`

```js
export async function up(knex: Knex): Promise<void> {
  return knex.schema.createTable(TableName.USERS, (t) => {
    t.integer('id', 8).notNullable().unique().primary();
....
```

# Missing / erroneus documentation

Also on docs it is missing an example too

**Comment by OlivierCavadenti** [comment]
PostgreSQL dont have length for integer (its only for Oracle and Mysql as I can see).
https://www.postgresql.org/docs/9.1/datatype-numeric.html

**Comment by mandaputtra** [comment]
Thanks I'll update the docs

**Comment by OlivierCavadenti** [comment]
> Thanks I'll update the docs

Thanks, can you update/add docs for smallint, mediumint, tinyint too ?

**Comment by mandaputtra** [comment]
yeah of course.
