### ISSUE TITLE
Support @vscode/sqlite3

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#4858]
See https://github.com/mapbox/node-sqlite3/issues/1493 for full context. If vscode version is installed, it should be picked up instead of mapbox one.
We should also consider making it a recommended default in 1.0.0

**Comment by kibertoad** [comment]
@OlivierCavadenti Thoughts?

**Comment by OlivierCavadenti** [comment]
Due to the severity (and lack of patch in mapbox version), it's seems really more safe to switch to vscode version. Maybe can we make a complete audit like this for all of dependencies for 1.0.0 ? Dont know if you have similar problems in other dependencies.

**Comment by tsondergaard** [comment]
@vscode/sqlite3 does not seem to have very clear intentions. Are they just serving the needs of @vscode or are they a new maintained fork? If it is the first they could at least in theory start adding @vscode specific stuff

**Comment by kibertoad** [comment]
@tsondergaard How do you imagine vscode-specific SQLite driver :)?

**Comment by gms1** [comment]
e.g will they fix issues or accept PRs not related to vscode? will they drop support for features not in use by vscode ( e.g SQLCipher extension)... we probably don't know
or will they have pre-built binaries available, so it has not be compiled everywhere

**Comment by kibertoad** [comment]
Released in 1.0.1.

**Comment by alexp1917** [comment]
I've mentioned a docs fix here - https://github.com/knex/documentation/pull/381 but since they are not doing a good job of maintaining the library (e.g. check this out - https://www.npmjs.com/package/@vscode/sqlite3 - it links to the mapbox git repo, so where is the actual source code? wtf?), i suggest making it optional (search for both this and the "better-sqlite" whatever its called).

also prints this amusing notice:
```
Knex: run
$ npm install sqlite3 --save
Cannot find module '@vscode/sqlite3'
Require stack: ...
```

**Comment by guoh27** [comment]
npm install sqlite3 --save
Cannot find module '@vscode/sqlite3'

knex 1.0.3

**Comment by hodgef** [comment]
> npm install sqlite3 --save Cannot find module '@vscode/sqlite3'
> 
> knex 1.0.3

Workaround to make the error go away, but obviously results in double deps.
```
"dependencies": {
    "sqlite3": "npm:@vscode/sqlite3@5.0.7",
    "@vscode/sqlite3": "^5.0.7",
    ...
}
```

**Comment by OlivierCavadenti** [comment]
I take it as soon as possible
