### ISSUE TITLE
Knex wrongly assumes that comments should have less than 60 characters on MySQL Dialect. 

### ISSUE THREAD

**Issue by rubenferreira97** [knex/knex#4863]
# Environment

Knex version: 0.95.14
Database + version: 10.4.22-MariaDB
OS: Windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When running a migration that have a column/table comment with more than 60 characters the following message appears:
`"The max length for a table comment is 60 characters"`
This message shows multiple times since we have some columns with long comments.  It shouldn't trigger any warning since mysql and mariaDB maximum length is 1024 characters (a long time ago was 60).

**MySQL Documentation**

> COMMENT
> 
> A comment for a column can be specified with the COMMENT option, up to 1024 characters long. The comment is displayed by the SHOW CREATE TABLE and SHOW FULL COLUMNS statements.

**MariaDB Documentation**
https://mariadb.com/kb/en/create-table/#comment-column-option
> COMMENT Column Option
> You can provide a comment for each column using the COMMENT clause. The maximum length is 1024 characters. Use the SHOW FULL COLUMNS statement to see column comments.

This warning appears because of the following code:
https://github.com/knex/knex/blob/27ade6f8814a5601916489a96474b55649e15462/lib/dialects/mysql/schema/mysql-tablecompiler.js#L45-L48

2. Error message
No error message, only a warning every time that a comment with >60 characters appear.
"The max length for a table comment is 60 characters"

3. Reduced test code
```
  return knex.schema
    .createTable('table', (table) => {
      table.comment('A big comment. If we write more than 60 characters here it shouldn't trigger any warning since mysql and mariaDB maximum length is 1024 characters. Please fix this warning, it's annoying when a migration is taking place with multiple long comments.');
    })
```

**Comment by kibertoad** [comment]
Released in 1.0.1.
