### ISSUE TITLE
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by joaogabrielmp** [knex/knex#4877]
# Environment

Knex version: 0.95.11/0.95.14
Database + version:  Postgres 11.9
OS: Ubuntu 20.04.3
Node version: 14.18.1 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
In production, after using routes that connect to the database, the error below is thrown and the system lags or hangs for a few minutes.
I'm using raw query.
I checked and at first I didn't find any transaction without commit or rollback.

2. Error message
at Client_PG.acquireConnection (/home/ubuntu/app/node_modules/knex/lib/client.js:305:26)
    at async Transaction_PG.acquireConnection (/home/ubuntu/app/node_modules/knex/lib/execution/transaction.js:250:28)
(node:277451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11999)
(node:277451) UnhandledPromiseRejectionWarning: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
![WhatsApp Image 2021-12-06 at 5 39 40 PM](https://user-images.githubusercontent.com/17069826/144919058-11a97020-ecc0-4468-bcc9-9defc09e5c29.jpeg)

**Comment by eyan** [comment]
I'm getting the same error. What did you do to solve the problem?

**Comment by eyan** [comment]
Found related ticket here: https://github.com/knex/knex/issues/4816

**Comment by joaogabrielmp** [comment]
@eyan In my case, there was a part of my code with an error without try/catch.
Then, after the launch error, the transaction was not closed.
