### ISSUE TITLE
typeError for pluck() with objection version 3.0.0

### ISSUE THREAD

**Issue by ilyanemtsov** [knex/knex#4892]
Knex version: "0.95.12"
Objection version: "3.0.0
node: node:16-alpine

Once Objection version was updated to latest(3.0.0), queries started to fail on `pluck()` and few other methods failed as well.
example of error is `TypeError: Person.query(...).orderBy(...).pluck is not a function`
does the knex still support `pluck()` ?

**Comment by kibertoad** [comment]
@ilyanemtsov If you are invoking it on a query builder, yes, if you are trying to execute it on a promise you get, no.
`orderBy` returns `QueryBuilder`, which has `pluck` method on it, so your given example should be fine. Can you share a larger fragment of your code?

**Comment by ilyanemtsov** [comment]
@kibertoad 
example: 
this doesn't work anymore
`const ids = await Person.query().orderBy('id').pluck('id')`

i tried to look for some help in objection github repo and found  https://github.com/Vincit/objection.js/issues/1588 
it works  after removing pluck and substituting to this 
` const ids = await Person.query().orderBy('id').then(members => members.map(member => member.id))`

**Comment by kibertoad** [comment]
Need to check if it's on knex side or Objection is not exposing something properly

**Comment by kibertoad** [comment]
#1588 make it seem that it was a choice on Objection side. Knex still supports it.

**Comment by ilyanemtsov** [comment]
@kibertoad got it, thanks

**Comment by ilyanemtsov** [comment]
@kibertoad just confirmed with objection 
`pluck was deprecated in 1.x and removed in 3.0.`
