### ISSUE TITLE
npx knex migrate:list doesn't print a readable list of completed migrations files

### ISSUE THREAD

**Issue by axelo** [knex/knex#4951]
# Environment

Knex version: 1.0.1
Database + version: PostgreSQL 12.7
OS: macOS 11.6.2

# Bug

1.

```shell
npx knex migrate:list
```

produces 

```shell
[object Object]
[object Object]
[object Object]
No Pending Migration files Found.
```

Previous version (0.95) listed the filenames of completed migrations:

```shell
20220119154150_x.ts 
20220119155840_y.ts 
20220120081602_z.ts 
No Pending Migration files Found.
```

2. Error message

No error message, just a bit inconvenient to read :) 

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Run `npx knex migrate:list` with at least one completed migration.

I think the fix is to say `completed[i].name` here https://github.com/knex/knex/blob/1744c8c2655a8362260ba987d706ec3473681a78/bin/utils/migrationsLister.js#L16

**Comment by kibertoad** [comment]
Will be fixed in 1.0.2, sorry!

**Comment by axelo** [comment]
> Will be fixed in 1.0.2, sorry!

No worries, thanks for doing this!

**Comment by SteveDeWald** [comment]
I'm on version 1.0.3 and am still encountering the issue.

```bash
> npx knex migrate:list
Requiring external module ts-node/register
Found 3 Completed Migration file/files.
[object Object] 
[object Object] 
[object Object] 
No Pending Migration files Found.
```

Thanks.

**Comment by marianorodriguez** [comment]
v1.0.4 still has this issue :/

**Comment by kibertoad** [comment]
Released in 1.0.5

**Comment by rmarmitt** [comment]
Currently in 1.0.7 and still having this issue

**Comment by nooraldarraji** [comment]
Same issue here i'm using next 13.4 

```Using environment: development
Found 1 Completed Migration file/files.
[object Object] 
Found 8 Pending Migration file/files.
[object Object] 
Found 8 Pending Migration file/files.```
