### ISSUE TITLE
Unsupported driver used: Client_BetterSQLite3

### ISSUE THREAD

**Issue by ozziest** [knex/knex#4961]
# Environment

Knex version: 1.0.1
Database + version: better-sqlite3,  ^7.5.0,
OS: ubuntu 20.04

# Bug

1. I can't start a connection with the `better-sqlite3`.

2. Error message

```
/home/ozzy/Desktop/my-api/node_modules/knex-schema-inspector/dist/index.js:26
            throw Error('Unsupported driver used: ' + knex.client.constructor.name);
                  ^

Error: Unsupported driver used: Client_BetterSQLite3
```

3. Example

```js
const knex = require('knex')({
  client: 'better-sqlite3',
  connection: {
    filename: "./mydb.sqlite"
  }
});
```

**Comment by kibertoad** [comment]
@ozziest It should work. See https://github.com/knex/knex/blob/master/test/integration2/util/knex-instance-provider.js

Wonder if you are using older knex version in your CLI (e. g. globally installed one)

**Comment by kibertoad** [comment]
@ozziest Ah, wait, you are using knex-schema-inspector.
@rijkvanzanten I assume explicit support for better-sqlite3 needs to be added to knex-schema-inspector?

**Comment by ikinciel-dev** [comment]
@kibertoad , thank you a lot for your quick response. Yeah, I am using `knex-schema-inspector` and the version is `1.7.1`.

**Comment by ozziest** [comment]
@kibertoad , thanks a lot for your quick response. Yeah, I am using `knex-schema-inspector` and its version is `1.7.1`.

**Comment by kibertoad** [comment]
I've opened an issue at https://github.com/knex/knex-schema-inspector/issues/94
Would you be open to sending a PR to the project adding better-sqlite support? Should be fairly straightforward, you could just extend https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/sqlite.ts

**Comment by rijkvanzanten** [comment]
@kibertoad I don't think we're doing anything that's specific to `node-sqlite` in there, so adding support might be as easy as extending:

https://github.com/knex/knex-schema-inspector/blob/b0af557df44a77abdbda7137253b512b79b5cacb/lib/index.ts#L17-L19

to 

```js
    case 'Client_SQLite3':
    case 'Client_BetterSQLite3':
      constructor = require('./dialects/sqlite').default;
      break;
```

**Comment by kibertoad** [comment]
@ozziest Could you do the proposed change with test?

**Comment by ozziest** [comment]
@kibertoad yeah, I can handle it.

**Comment by OlivierCavadenti** [comment]
It's an knex-schema-inspector issue : https://github.com/knex/knex-schema-inspector/issues/94
with a corresponding issue : https://github.com/knex/knex-schema-inspector/pull/95
