### ISSUE TITLE
TableBuilder missing char method on ts definition

### ISSUE THREAD

**Issue by pablor21** [knex/knex#4962]
Just as the title says, the char method of tablebuilder is not in the ts definition file
@lorefnon

**Comment by OlivierCavadenti** [comment]
I dont see 'char' in documentation, and nothing implemented in columncompiler. I have undefined in create table code when I try to build table with char type. Do you have example of working code ?

(I find 'char' only in tablebuilder file: 
![image](https://user-images.githubusercontent.com/10152806/150674552-006cafb9-2a51-4637-becc-e20957fa95fa.png)
)

**Comment by pablor21** [comment]
I don't have any working example, I've just tried to use with vanilla js, and the method is there, but it doesn't work (at least for mysql), so I think we better close this issue since It doesn’t seem to be a good idea to add a typing for something that doesn't work... Thank you
