### ISSUE TITLE
Invalid input syntax for type integer after upgrade from version 0.95.15 to 1.0.1

### ISSUE THREAD

**Issue by nexusbr** [knex/knex#4977]
# Environment

Knex version: 1.0.1
Database + version: PostgreSQL 12.9  
OS: (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

# Bug

1. After in nodejs I upgrade knex from version 0.95.15 to 1.0.1

2. Error message: insert into "geosan"."redesagua" ("comprimento", "diametro_interno", "geom", "material_id", "material_nome", "no_final", "no_inicial", "texto_abaixo_diametro", "texto_abaixo_material", "texto_abaixo_material_e_diametro", "texto_acima", "tipo_tubulacao_id", "tipo_tubulacao_nome") values ($1, $2, ST_geomFromGeoJSON($3), DEFAULT, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning "id" - invalid input syntax for type integer: "{"id":6324}"

My table has an incremental primary key named *id*.

3. Reduced test code

```
return knex("geosan.redesagua")
	.transacting(trx)
	.returning("id")
	.insert({
		geom: funcaoPostGis.geomFromGeoJSON(trechoRedeSomenteComGeometria),
		no_inicial: trechoRedeComGeometriaEatributosObj.properties.noInicial,
		no_final: trechoRedeComGeometriaEatributosObj.properties.noFinal,
		comprimento: trechoRedeComGeometriaEatributosObj.properties.comprimento,
		diametro_interno: atributo.diametro_interno,
		material_id: atributo.material_id,
		material_nome: atributo.material_nome,
		tipo_tubulacao_id: atributo.tipo_tubulacao_id,
		tipo_tubulacao_nome: atributo.tipo_tubulacao_nome,
		texto_acima: trechoRedeComGeometriaEatributosObj.properties.comprimento,
		texto_abaixo_material: (atributo.material_nome == null) ? "" : atributo.material_nome,
		texto_abaixo_diametro: (atributo.diametro_interno == null) ? "" : "Ø".concat(atributo.diametro_interno),
		texto_abaixo_material_e_diametro: material_e_diametro(atributo.material_nome, atributo.diametro_interno)
	})
	.then(resultado => { console.log("Resultado", resultado) })
	.catch (erro =>{console.log ("Erro ao inserir: ", erro.message)})
```

In version 0.95.15 it was working, after I upgrade to 1.0.1 it started to appear this error. Then I returned to version 0.95.15 and it worked again.

**Comment by kibertoad** [comment]
See UPGRADING.md:
```
RETURNING operations now always return an object with column names;
```

so it's an object with id field, not a number now.

**Comment by nexusbr** [comment]
Thanks
