### ISSUE TITLE
Wrong return type for Date column in sqlite3

### ISSUE THREAD

**Issue by noam-honig** [knex/knex#4981]
# Environment

Knex version:1.0.1
Database + version: better-sqlite3@7.5.0
OS:Windows

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
The return type should be of type date (as it is with postgres or sql server.

2. Error message - none - just wrong return type

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```ts
const k = Knex.default({
    client: 'better-sqlite3', // or 'better-sqlite3'
    connection: {
        filename: ":memory:"
    },
});
k.schema.dropTableIfExists('test').then(async () => {
    await k.schema.createTable('test', async tb => {
        tb.integer('a');
        tb.date('d');
    })
    await k('test').insert({ a: 1, d: new Date() });
    const rows = await k('test').select();
    console.table(rows);
    console.log(typeof rows[0].d);

});
```

The error result:
```
┌─────────┬───┬───────────────┐
│ (index) │ a │       d       │
├─────────┼───┼───────────────┤
│    0    │ 1 │ 1643549761892 │
└─────────┴───┴───────────────┘
number
```

In SQL Server the result is a date:
```
┌─────────┬───┬──────────────────────────┐
│ (index) │ a │            d             │
├─────────┼───┼──────────────────────────┤
│    0    │ 1 │ 2022-01-30T00:00:00.000Z │
└─────────┴───┴──────────────────────────┘
object
```

**Comment by OlivierCavadenti** [comment]
I will take a look, it's in all drivers sqlite3 drivers (sqlite3 and better-sqlite3) ?

**Comment by OlivierCavadenti** [comment]
I checked, but SQLite seems to store date only with number, see this article :
https://www.grouparoo.com/blog/understanding-types-sqlite-node#sqlite-type-quirks

So you need to typecast rows at the end with : 
![image](https://user-images.githubusercontent.com/10152806/154758358-75f7cc0f-215f-4b92-a911-88ca6d5b7a3f.png)

Result (before/after):
![image](https://user-images.githubusercontent.com/10152806/154758405-dd30eb9e-aeea-4e5b-8889-8542b610ebd5.png)
