### ISSUE TITLE
Allow passing experimental-specifier-resolution=node for type=module projects

### ISSUE THREAD

**Issue by atlanteh** [knex/knex#4983]
# Environment

Knex version: 1.0.1
Database + version: pg 13
OS: windows 10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
knex migrate doesn't support passing experimental-specifier-resolution=node to allow for imports without extensions inside the migrations
Trying to use --esm just hangs in there forever
2. Error message
```Cannot find module 'XXX' imported from XXX```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
//package.json
{
    "name": "test",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "type": "module",
    "scripts": {
      "migrate:dev": "knex migrate:latest",
      "rollback:dev": "knex migrate:rollback"
    },
    "dependencies": {  
      "knex": "^1.0.1",
      "pg": "^8.7.1"
    },
    "engines": {
      "node": ">=14"
    }
}
 
```

```
//migrations/20201030091600_initial.js
import config from '../config/config';

exports.up = async function(knex) {

};


export const down = async function(knex) {

};
```

```
//config/config.js
export default {}
```

**Comment by Naddiseo** [comment]
As a workaround for anyone running into this, you can use absolute file imports, so the test case would be importing:
```javascript
import config from "../config/config.js"; //<-- you need the ".js", and if it's an index file, you need to specify "/index.js"
export async function up(knex) {}
export async function down(knex) {}
```

**Comment by atlanteh** [comment]
@Naddiseo Yep, that solves the first level, but if your config has another references on more files, the whole resolution chain should be converted to full names.

**Comment by Naddiseo** [comment]
@atlanteh , I haven't tried this, but is it possible to pass "experimental-specifier-resolution=node" via `NODE_OPTIONS` ? 
Something like:
```json
//package.json
{
    "name": "test",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "type": "module",
    "scripts": {
      "migrate:dev": "NODE_OPTIONS=--experimental-specifier-resolution=node knex migrate:latest",
      "rollback:dev": "knex migrate:rollback"
    },
    "dependencies": {  
      "knex": "^1.0.1",
      "pg": "^8.7.1"
    },
    "engines": {
      "node": ">=14"
    }
}
```

**Comment by atlanteh** [comment]
@Naddiseo that actually works! Thank you so much!
