### ISSUE TITLE
[TS] `alter()` requires 1 argument

### ISSUE THREAD

**Issue by rafaelalmeidatk** [knex/knex#4995]
# Environment

Knex version: 1.0.2

If issue is about TypeScript definitions, tag @lorefnon.

# Bug

Since #4967, `alter()` requires 1 argument. I believe the type of the function should mark the options object as optional, since the function signature sets it as an empty object if no argument is provided:

https://github.com/knex/knex/blob/8fd1f22d2e9ccdd1d98d874d64a255858906d854/lib/schema/columnbuilder.js#L113-L116

Reproduction of the bug (using the code examples from the docs):

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgaQHYFMAecC+cBmUEIcA5ANYaakBQNAJugMYA2AhlOnExKgM7xKWAFwoqAbjpDMAOj5MAFuhBsZbFjHRQAKmwBGLdAApSAVz5bSAGgKnUTGMF5GYASkQ04cGDOD3OIOioMHxGrjJgUKAcAJ5h4nAA9IlwbPT0nkkp9ERgfHCR6ABuTuZwjPhsphpwReqmXITE3BAspiCoNopsqADmXDAxYAMQcAJRfamo9KnpcKgQ8KjV7AZcPPwwUGx+MJk+4369JuZaqGyB1nAAzACs4QswAHIr+oZhahpa8ZnJ5bn5PSLBTzRbzFYtTbbXZTGYwJTldCVarwOptdD7XzBdD9KAmNj9UjhdSaPGuSReP7AfCpL5QF4sVaGODAfKVFgWGw5CB5OC8FgxbwIipVGpohqY3Y476kAnoImfUlGBAkrQMplcUTsiw4cm-FLU2mk7RDLisgjqTneU18mk8NodFn5R5GrToegySXY3H4wnEunK1U6G1ay3oXWSCNAA

**Comment by kibertoad** [comment]
Released in 1.0.3
