### ISSUE TITLE
withMaterialized and withNotMaterialized are not present on knex object

### ISSUE THREAD

**Issue by jhiesey** [knex/knex#5008]
# Environment

Knex version: 1.0.2
Database + version: postgres 12 and 13
OS: macOS and Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
The new `.withMaterialized` and `.withNotMaterialized` functions added in #4470 are not present on the `knex` object, despite the example in the docs showing them used this way.

The [docs page](https://knexjs.org/#Builder-withMaterialized) shows an error for these methods as well

2. Error message
`knex.withMaterialized is not a function`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

See [the example on the docs page](https://knexjs.org/#Builder-withMaterialized):
```
knex.withMaterialized('with_alias', knex.raw('select * from "books" where "author" = ?', 'Test')).select('*').from('with_alias')
Error:
knex.withMaterialized is not a function
```

The solution is to add `withMaterialized` and `withNotMaterialized` to method-constants in https://github.com/knex/knex/blob/master/lib/query/method-constants.js

**Comment by kibertoad** [comment]
Released in 1.0.3
