### ISSUE TITLE
How to join two tables from different Database using knex ?

### ISSUE THREAD

**Issue by TonioloF** [knex/knex#5014]
# Feature discussion / request

Is it possible join two tables from different databases using knex ? 

Ex. 

Server 1 - db1
Server 2 - db2

SQL Statement Example:
 Select user_db1.*,user_db2.*  from db1.user as user_db1 inner join db2.User as user_db2 on user_db1.id = user_db2.id

**Comment by OlivierCavadenti** [comment]
I dont think it's possible (in Knex and in SQL).
Maybe you can create a foreign table if your sgbd accept that (https://www.postgresql.org/docs/13/sql-createforeigntable.html) and make joins in Knex like another two tables in the same database.

**Comment by manusiakemos** [comment]
```javascript
app.get('/', async (req, res) => {
  let data = await db1.table('table1 as t1')
    .join('table2 as t2' , 't2.idx', '=', 't1.idx')
    .first();
  res.json({ data });
})
```
