### ISSUE TITLE
[feature request] clone knex query

### ISSUE THREAD

**Issue by bblack** [knex/knex#502]
It would be nice to have an API for cloning a knex query to e.g. have a query, and a modification of the query, simultaneously in separate variables.

**Comment by leebenson** [comment]
I know this is closed, but this is a really useful feature and I think it deserves a place in the docs.

It came in handy this morning for a query builder I wrote, that allows me to pass in a query and run a separate count against it, as well as apply additional filters, without mutating the original query:

```js
export async function qb(ctx, query) {
  // Copy queries
  const total = query.clone();
  const data = query.clone();

  const res = {
    total: (await total.count('id as total').first() || {}).total || 0,
    offset: parseInt(ctx.query.offset, 10) || 0,
    limit: 25,
    data: [],
  };

  // Only fetch data if total > 0
  if (res.total) {
    res.data = await data
      .offset(res.offset)
      .limit(res.limit);
  }

  return res;
}
```

It was only happening across this closed issue that I realised the above was possible. Thanks!

**Comment by leebenson** [comment]
actually my bad, it _was_ added...  I just missed it. Ignore!
