### ISSUE TITLE
Does Knex blocks when it finds a Deadlock due to forUpdate?

### ISSUE THREAD

**Issue by jvalrog** [knex/knex#5025]
I'm using transactions (promise aware) and forUpdate. I'm currently issuing several parallel transactions and I'm getting this error:

    "select * from `central_data` where `id` = 4381 for update - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction`

This usually happens when I delete the table data manually and start the process again. (I think I'm missing something here?)

I supposed that knex will just wait for the deadlock to clear and then continue? But it's throwing an error instead?

I'm new to knex btw.

**Comment by RobIsHere** [comment]
A lock can "clear", a deadlock by definition is never able to clear magically by itself. Therefore it's named "dead"lock.

To help you out of this desperate situation, the database kills one of your at least two conflicting transactions. Get yourself a good book about databases. It's no knex issue.

**Comment by OlivierCavadenti** [comment]
Article on that problem : https://karbachinsky.medium.com/deadlock-found-when-trying-to-get-lock-try-restarting-transaction-54a3ed118068

**Comment by jvalrog** [comment]
Oh, thanks guys, it was my first time dealing with deadlocks.
