### ISSUE TITLE
Schema Builder when to use text or string?

### ISSUE THREAD

**Issue by KrisLau** [knex/knex#5026]
So I have one id that is a firebase uid that I have been using .text for but when I swapped over my client to mssql, it errored out. So now I'm trying to figure out if I need to create it with a .text or a .string? Also for first name, last name, etc which one works better?

**Comment by kibertoad** [comment]
text is for long texts, e. g. descriptions or blog entries. 
string is generally for something couple of hundreds of symbols long.
