### ISSUE TITLE
Enum Arrays Do Not Return An Array Type

### ISSUE THREAD

**Issue by enchorb** [knex/knex#5038]
# Environment

Knex: 1.0.3
Database: Postgres 14
OS: Windows 10

# Bug

When creating an enum array the return value is not an array from queries

Case 1) 
`table.specificType('roles', 'text[]').defaultTo('{admin, viewer}');` --> Correctly Returns `roles: ['admin', 'viewer'] `

Case 2) 
`table.specificType('roles', 'role_type[]').defaultTo('{admin, viewer}');` --> Returns `roles: '{admin, viewer}' `

Is this a bug or is there a way to correctly return an array for enum arrays?

**Comment by KristjanTammekivi** [comment]
I guess this is because you need to set type parsing for pg
https://github.com/brianc/node-pg-types
You can get the types you need to add parsers like this:
```postgres=# create type mood as enum ('sad', 'ok', 'happy');
CREATE TYPE
postgres=# select oid, typarray from pg_type where typname = 'mood';
-[ RECORD 1 ]-----
oid      | 8798926
typarray | 8798925

```

**Comment by suonto** [comment]
@enchorb if I may ask, how did you actually solve this issue?
