### ISSUE TITLE
Example fails silently with PG on 0.6.22

### ISSUE THREAD

**Issue by scottpersinger** [knex/knex#505]
Seems like if I provide an invalid connection string to the constructor, using PG, I get nothing back. No errors, just completely silent.

**Comment by thehydroimpulse** [comment]
This is certainly a continuing problem with pg. Connection issues are simply ignored with knex, which is a massive problem.

**Comment by tgriesser** [comment]
@thehydroimpulse can you try against master and see if it's still an issue - will be cutting a new minor version bump with the latest soon.
