### ISSUE TITLE
BUG - returning method returns wrong type returning value

### ISSUE THREAD

**Issue by hshine1226** [knex/knex#5054]
# Environment

Knex version:0.95.15
Database + version: Postgresql 14.2
OS: Mac

Select applicable template from below.
@lorefnon 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
```typescript
export const upsertPreAppraiser = (updateValue: TAddPreAppraisalValue) =>
    knex<IPreAppraisalTable>('inapp.pre_appraisal as pa')
        .insert(updateValue)
        .whereRaw(`pa.dashboard_detail_id = ${updateValue.dashboard_detail_id}`)
        .onConflict(['dashboard_detail_id'])
        .merge()
        .returning('dashboard_detail_id')
```

when I run above code, I expect that returning value is number type because I have number type dashboard_detail_id column.
But I got string type returning value. 
And also typescript says me that returning value is number array type.

2. Error message
![image](https://user-images.githubusercontent.com/31975706/157786816-92d180b3-73c6-45fb-933a-f9e1f8298d57.png)

![image](https://user-images.githubusercontent.com/31975706/157787010-8d081eac-ebe6-4086-897f-8306f41dc842.png)

**Comment by santialbo** [comment]
Is your column a bigint? If that's the case bigints don't fit into javascript numbers, that's why you get a string representation of the number. https://github.com/brianc/node-postgres/pull/353

**Comment by hshine1226** [comment]
> Is your column a bigint? If that's the case bigints don't fit into javascript numbers, that's why you get a string representation of the number. [brianc/node-postgres#353](https://github.com/brianc/node-postgres/pull/353)

 @santialbo 
 Yes, I have a column a bigint. I understand thanks
