### ISSUE TITLE
knexjs.org has expired or otherwise inaccessible 

### ISSUE THREAD

**Issue by thehydrogen** [knex/knex#5057]
knexjs.org currently just shows the default Namecheap parking page?

**Comment by allenben746** [comment]
Seeing that too.

https://www.isitdownrightnow.com/knexjs.org.html

**Comment by MRNafisiA** [comment]
Is the website source on github? Any suggestion to use the docs offline?

**Comment by strarsis** [comment]
You can access the domain `knexjs.org` [over HTTP](http://knexjs.org/) (instead of HTTPS where connection times out).
> This domain was recently registered at [Namecheap.com](https://www.namecheap.com/). Please check back later!
Let's hope the domain hadn't expired and is squatted now...

**Comment by satazor** [comment]
cc @kibertoad

**Comment by kibertoad** [comment]
I'll look into this, thank you.

**Comment by didimitrie** [comment]
while this gets sorted out, for anyone else landing here: https://web.archive.org/web/20220307202010/http://knexjs.org/

PS: thanks for a wonderful library!

**Comment by kibertoad** [comment]
@tgriesser Do you have any visibility into what happened? I would be happy to pay for knex domain, but it doesn't seem to be available.

**Comment by kibertoad** [comment]
@elhigu @OlivierCavadenti I'm considering moving our webpage to GitHub pages, similarly to https://vincit.github.io/objection.js/
what do you think?

**Comment by kibertoad** [comment]
As a quick fix, I've updated package.json and and README to point to GitHub URL, and also registered knexjs.net just in case. Waiting to hear from the rest of Knex org before making any further steps.

**Comment by tgriesser** [comment]
Ah sorry about this, it was supposed to be on autorenew with the registrar but something seems to have broken there. Just renewed it & figuring out getting it back online, not sure how long that change takes to propagate

**Comment by tgriesser** [comment]
Ok this is fixed now, sorry for the trouble - will make sure this doesn't happen again

**Comment by kibertoad** [comment]
Thank you!
