### ISSUE TITLE
Coverage workflow is broken

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#5074]
Something seems to be off, coverage is suspiciously low: https://github.com/knex/knex/runs/5611141558?check_suite_focus=true

Looks like we are not executing majority of tests for some reason.

**Comment by kibertoad** [comment]
Fixed in https://github.com/knex/knex/commit/9d62cbfdb154950e868ca6fb59fd3ab785b20252

**Comment by OlivierCavadenti** [comment]
@kibertoad are you ok if I try to integrate Coveralls in Github action ?
https://github.com/marketplace/actions/coveralls-github-action

**Comment by kibertoad** [comment]
That would be great!
