### ISSUE TITLE
[TypeError: table.point is not a function]

### ISSUE THREAD

**Issue by naveen1337** [knex/knex#5076]
# Environment

 knex: "^0.95.11",
MariaDb:
OS: manjaro linux

# Bug

1.In documentation it shows up the point data type supported in knex, but when I use it throws a error as points not exists

2.  [TypeError: table.point is not a function]

# Missing / erroneus documentation

[https://knexjs.org/#Schema-point](https://knexjs.org/#Schema-point)

**Comment by santialbo** [comment]
Try upgrading knex. Geometry schema helpers were released in 0.95.12 or 0.95.13
