### ISSUE TITLE
Transaction is being commited automatically even if it fails

### ISSUE THREAD

**Issue by CristianCojocari** [knex/knex#5077]
# Environment

Knex version: 0.95.15
Database + version: Mysql 
OS: Windows

```
  for (var i = 0; i < migrationFiles.length; i++) {
    const fileContent = fs.readFileSync(
      path.join(__dirname, path.sep, migrationFiles[i], path.sep, 'up.sql'),
      {
        encoding: 'utf8',
      }
    )
    await conn.transaction(async trx => {
      const statementArray = fileContent
        .split('\r\n')
        .map(v => v.trim())
        .join('')
        .split(';')
        .filter(t => t)
      for (var j = 0; j < statementArray.length; j++) {
        await trx.raw(`${statementArray[j]};`)
      }
    })
    console.log(`File ${migrationFiles[i]} migrated successfully`)
  }
```

I've also tried this:

```
await conn.transaction(async trx => {
      const promiseArray = []
      for (var j = 0; j < statementArray.length; j++) {
        promiseArray.push(conn.raw(`${statementArray[j]};`).transacting(trx))
      }
      return Promise.all(promiseArray)
    })
```

The above code runs an sql file, with create table commands.
Inside the transaction I'm splitting the statements and trying to run every one separately.
The idea is, if a single statement fails inside the file, transaction should rollback.

The sql has 2 CREATE TABLE statements. One is correct, one has an sql error (specifically to test this).

Current output: The first table gets commited to the database, the second fails.
Expected: Both to fail, since trx.raw throws an sql error and should rollback the transaction.

I've tried everything, from return Promise.all to trx.commit and trx.rollback, but it looks like knex totally ignores the transaction and commit the statements as soon as they are called.

**Comment by santialbo** [comment]
In Mysql DDL statements that create or modify tables have an implicit commit.
https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

**Comment by CristianCojocari** [comment]
> In Mysql DDL statements that create or modify tables have an implicit commit. https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

Thanks for the response. Apparently yes, Mysql doesn't allow for alter table, create or drop table transactions, which is pretty weird.
