### ISSUE TITLE
Azure Authentication not handled correctly

### ISSUE THREAD

**Issue by jamesderrick** [knex/knex#5083]
# Environment

Knex version: 1.0.4
Database + version: Azure SQL (mssql) @smorey2 
OS: Windows 10

# Bug

I'm trying to use knex with an azure sql database. I'm using Tedious (v14.3) as my client package.
I have been able to use Tedious with Azure SQL previously by using the token authentication type and the connection works fine.
However, with knex I just get the error `"config.authentication.options.token" property must be of type string.`
I have checked and the token is fetched and it is definitely passed to the config as a string. 
So I can only assume something is going wrong between knex and tedious.
My config looks like this
```
{
  client: 'mssql',
  connection: {
    host: <azure sql url>,
    type: 'azure-active-directory-access-token',
    authentication: {
      type: 'azure-active-directory-access-token',
      options: {
        token: <token goes here>
      }
    }
    options: {
      database: <azure sql db name>,
      encrypt: true
    }
  }
}
```

I have to define type inside and outside of authentication, which is different to Tedious, because knex just defaults to a user login without it.
It could easily be an issue with my config file, I couldn't find many examples of connecting to Azure SQL and couldn't find any using the access token method

**Comment by jamesderrick** [comment]
Might have figured it out. Although Tedious has an authentication object. Knex doesn't seem to use that.
If I put `token` outside of it, it connects.
My config looks like this now...
```
{
  client: 'mssql',
  connection: {
    host: <azure sql url>,
    type: 'azure-active-directory-access-token',
    token: <token goes here>,
    options: {
      database: <azure sql db name>,
      encrypt: true
    }
  }
}
```

**Comment by kibertoad** [comment]
@jamesderrick Can you check knex TypeScript types for MSSQL connection object? I think it should be fairly in sync with Tedious
