### ISSUE TITLE
Date in BC is not getting updated properly to postgres

### ISSUE THREAD

**Issue by newmonksh** [knex/knex#5093]
Knex version: ^0.95.11 
Database + version: PostgreSQL 12.7 64 Bit
OS: Any 

Date object can be set in JS with a negative number to represent BC.
https://scholarslab.lib.virginia.edu/blog/parsing-bc-dates-with-javascript/

Date with negative years are stored as date with BC in postgres.
but when updating the table via Knex though JS date object is passed after the update ,postgres reflects wrong date.

eg:  Date passed = -001200-03-29T04:17:11.000Z
Date updated in DB = 1201-03-28 23:21:09 BC

would have expected DB date  to be 1200-03-29 
Note : Column is declared as timestamp without time zone.

Thanks

**Comment by santialbo** [comment]
About the year it's how negative years work (because there's no year 0, when representing into a human readable format they shift by one). Check the following on your console.
> new Date("-001200-03-29T04:17:11.000Z").toLocaleString()
About the time / day shift it's probably because of your timezone.
