### ISSUE TITLE
Union wrap argument broken in 1.0.4

### ISSUE THREAD

**Issue by wodlo** [knex/knex#5094]
# Environment

Knex version: 1.0.4
Database + version: Mysql 8.0.18
OS: Fedora 35

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**

Prior to version 1.0.4 you could use the last argument in a union function call to flag if you wanted to wrap the union statement in parentheses. This no longer works and results in an erroneous pair of extra parentheses on the end of the query resulting in an SQL syntax error. 

**2. Error message**
It will be a SQL syntax error related to the erroneous extra set of parentheses added to the query, such as 
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '())' at line 1
```

**3. Reduced test code**
Here is a small snippet that simple does a select * from a union subquery.
```javascript
knex.from(function () {
    this.union([
        function () {
            this.select('*')
                .from('companies')
                .where('id', 1);
        },
        function () {
            this.select('*')
                .from('companies')
                .where('id', 2);
        }
    ], true);
})
```
In version 1.0.3 this results in the following correct sql query
```
select * from ((select * from `companies` where `id` = 1) union (select * from `companies` where `id` = 2))
```
However in version 1.0.4 this now results in the following broken sql query resulting in an SQL syntax error (see the extra empty brackets on the end)
```
select * from ((select * from `companies` where `id` = 1) union (select * from `companies` where `id` = 2) ())
```

**Comment by OlivierCavadenti** [comment]
Yeah, the issue that rework union wrapping is here : https://github.com/knex/knex/pull/5072
