### ISSUE TITLE
switch to better-sqlite3

### ISSUE THREAD

**Issue by eikaramba** [knex/knex#5097]
currently the default sqlite driver is @vscode/sqlite3, however that does not provide prebuilt binaries and will possible vanish see https://github.com/microsoft/vscode-node-sqlite3/issues/16#issuecomment-1046059712

a better alterantive is to switch to better-sqlite3 as the default driver, which is already supported by knex.

alternatively if i am correct one could wait for the mapbox to fix the vulnerabilites, however that does not seem to happen soon https://github.com/mapbox/node-sqlite3/issues/1493

original pull request for using @vscode/sqlite3 https://github.com/knex/knex/pull/4866

**Comment by kibertoad** [comment]
We definitely should consider that for 2.0.0

**Comment by NilsBaumgartner1994** [comment]
push, we also face this problem

**Comment by carlosfaria94** [comment]
Ghost have taken the development of node-sqlite3! All the problems are fixe in their recent version! 

https://github.com/TryGhost/node-sqlite3
