### ISSUE TITLE
Untyped function calls may not accept type arguments

### ISSUE THREAD

**Issue by bycop** [knex/knex#5098]
# Environment

Knex version: Latest (1.0.4)
Database + version: Postgres (Latest on docker)
OS: Windows 10

@lorefnon

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I'm trying to use knex on typescript with User Interface for better auto complete, I tried to implement in my own code the User interface and the call (like the example below) and also the same example as the documentation and I get the same error message.
Thanks for your help

2. Error message
Untyped function calls may not accept type arguments.ts(2347) on "knex<User>"

3. Code
```ts
interface User {
  id: number;
  username: string;
}

export async function getUsersFromUsername(username: string[]) : Promise<User[]> {
  return await knex<User>('user').whereIn('username', username).then((rows) => {
    return rows;
  }).catch((err) => {
    return { error: err };
  });
}
```

**Comment by ryubal-sh** [comment]
If anyone else is having this issue, I solved it by casting my `knex` instance when exporting it.

**config/db.ts**
From
`const knex = require('knex')({ client: 'mysql2', ... })`

To
`const knex: Knex = require('knex')({ client: 'mysql2', ... })`
