### ISSUE TITLE
Adding a distinctOn method for cross database distinct values

### ISSUE THREAD

**Issue by tgriesser** [knex/knex#51]
PostgreSQL - `DISTINCT ON (column)`

MySQL / SQLite3 - `GROUP BY column`

**Comment by npow** [comment]
Hi, I see this issue is marked as wontfix. What is currently the best way to perform a DISTINCT ON?

**Comment by StephanHoyer** [comment]
This works for me

```
knex('tablename').distinct(knex.raw('ON (column) column'))
  .orderBy('column')
  .orderBy('another_column');
```

**Comment by Znarkus** [comment]
Why wontfix? :)

**Comment by teckays** [comment]
Bump

**Comment by omeid** [comment]
A `distinctOn` method would be very helpful specially with `clearSelect()`, for example to reuse the same query for `count()` and select!

**Comment by zjr** [comment]
Could this be reopened? I also have a considerable issue w/o `distinctOn` because it creates issues reusing the query.

**Comment by elhigu** [comment]
> Could this be reopened? I also have a considerable problem w/o distinctOn because it creates issues reusing the query.

Open a feature request or bug report with proper description and reproduction of your problems.
