### ISSUE TITLE
Knex imports sqlite in migrate:make when told to use pg

### ISSUE THREAD

**Issue by IlyaSemenov** [knex/knex#5102]
# Environment

Knex version: 1.0.5
Database + version: Postgres 14
OS: macOS 12.3

# Bug

`knex migrate:make foo` wants (and fails) to load `@vscode/sqlite3` even though the client is set to `pg`:

```
❯ yarn knex migrate:make foo
yarn run v1.22.17
$ /Users/semenov/tmp/p1/node_modules/.bin/knex migrate:make foo
Knex: run
$ npm install @vscode/sqlite3 --save
Cannot find module '@vscode/sqlite3'
Require stack:
- /Users/semenov/tmp/p1/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/Knex.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/index.js
- /Users/semenov/tmp/p1/node_modules/knex/knex.js
- /Users/semenov/tmp/p1/node_modules/knex/bin/cli.js
Error: Cannot find module '@vscode/sqlite3'
Require stack:
- /Users/semenov/tmp/p1/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/Knex.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/index.js
- /Users/semenov/tmp/p1/node_modules/knex/knex.js
- /Users/semenov/tmp/p1/node_modules/knex/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Client_SQLite3._driver (/Users/semenov/tmp/p1/node_modules/knex/lib/dialects/sqlite3/index.js:33:12)
    at Client_SQLite3.initializeDriver (/Users/semenov/tmp/p1/node_modules/knex/lib/client.js:190:26)
    at new Client (/Users/semenov/tmp/p1/node_modules/knex/lib/client.js:75:12)
    at new Client_SQLite3 (/Users/semenov/tmp/p1/node_modules/knex/lib/dialects/sqlite3/index.js:22:5)
    at knex (/Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at initKnex (/Users/semenov/tmp/p1/node_modules/knex/bin/cli.js:74:10)
/Users/semenov/tmp/p1/node_modules/knex/lib/client.js:197
      throw new Error(`${message}\n${e.message}`);
            ^

Error: Knex: run
$ npm install @vscode/sqlite3 --save
Cannot find module '@vscode/sqlite3'
Require stack:
- /Users/semenov/tmp/p1/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/Knex.js
- /Users/semenov/tmp/p1/node_modules/knex/lib/index.js
- /Users/semenov/tmp/p1/node_modules/knex/knex.js
- /Users/semenov/tmp/p1/node_modules/knex/bin/cli.js
    at Client_SQLite3.initializeDriver (/Users/semenov/tmp/p1/node_modules/knex/lib/client.js:197:13)
    at new Client (/Users/semenov/tmp/p1/node_modules/knex/lib/client.js:75:12)
    at new Client_SQLite3 (/Users/semenov/tmp/p1/node_modules/knex/lib/dialects/sqlite3/index.js:22:5)
    at knex (/Users/semenov/tmp/p1/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at initKnex (/Users/semenov/tmp/p1/node_modules/knex/bin/cli.js:74:10)
    at async Command.<anonymous> (/Users/semenov/tmp/p1/node_modules/knex/bin/cli.js:213:24)
```

## Reduced test code

In an empty directory:

```
yarn add knex
```

create `knexfile.js`:

```js
module.exports = {
  client: 'pg',
  connection: 'postgres://localhost/test'
}
```

run:

```
pnpm knex migrate:make foo
```

## Cause

This is caused by: https://github.com/knex/knex/blob/f380e48e30663d6ae571f15237fac7fe7d08cb73/bin/cli.js#L212

This fake client option which user never provided overrides whatever `client` is set in config.

The [upgrade guide](https://github.com/knex/knex/blob/master/UPGRADING.md) (referenced [here](https://github.com/knex/knex/issues/5001#issuecomment-1030430724)) says:

> * If you are using `sqlite3` driver dependency, please replace it with `@vscode/sqlite3` in your `package.json`;

Note that it doesn't say that `@vscode/sqlite3` is now obligatory peer dependency when using migrations. This is a bug, there is no point in having `@vscode/sqlite3`, it's not being imported for any reasonable purpose.

**Comment by dhensby** [comment]
Yep, I'm experiencing this too.

The problem is that `lodash/merge` (used [here](https://github.com/knex/knex/blob/1.0.5/bin/cli.js#L66)) is replacing the original `client` value from the provided config with the "default" value that is set [here](https://github.com/knex/knex/blob/1.0.5/bin/cli.js#L212).

I don't think `lodash/merge` works as assumed here, it will try to deep merge all configs and for non-mergable items (like string values) the last seen value is the one that is used. Locally, swapping the arguments works as expected, but that may also not be desired behaviour, it may be better just to remove the default client value completely.

**Comment by dstarke** [comment]
Until this is fixed, you can work around the issue by specifying your client on the command line, for example:
`knex migrate:make --client pg foo`

**Comment by dhensby** [comment]
An easier workaround is using 1.0.4 ;)

**Comment by matusekma** [comment]
> Until this is fixed, you can work around the issue by specifying your client on the command line, for example: `knex migrate:make --client pg foo`

This does not help unfortunately, because the cli does not pick up the client option.
So you either have to install the @vscode/sqlite3 package or remove [this](https://github.com/knex/knex/blob/1.0.5/bin/cli.js#L212) line locally.

**Comment by dstarke** [comment]
> This does not help unfortunately, because the cli does not pick up the client option.

It did for me, and I don't have sqlite installed in the project where I tried it. However, I agree that the real solution is to remove the referenced line of code. It looks like it is supposed to be enforcing a default value for the configuration, but what it is actually doing is creating a default command line argument value, and the command line argument values override the values specified in the configuration file.

**Comment by fuzzysaj** [comment]
Same.  Had to downgrade to 1.0.4.

**Comment by JakeTompkins** [comment]
> Until this is fixed, you can work around the issue by specifying your client on the command line, for example: `knex migrate:make --client pg foo`

This worked for me, thank you. I was banging my head against the problem for a couple of hours thinking my knexfile was wrong.

**Comment by slier81** [comment]
thx god i found this issues.. it wasted me 2 hours already.. how come patch version introduce breaking changes?

**Comment by kibertoad** [comment]
@OlivierCavadenti we need to hotfix this

**Comment by OlivierCavadenti** [comment]
I will check this evening and dig into it. Is PR is enough to solve the problem ? https://github.com/knex/knex/pull/5106

**Comment by dhensby** [comment]
@kibertoad / @OlivierCavadenti the regression is from the use of `lodash/merge` introduced in this PR: https://github.com/knex/knex/pull/4047

merge is not working in the way assumed by the usage and so the value from the second object is taking precedent over the first whereas the implementation implies the expectation that it is the other way round.

**Comment by OlivierCavadenti** [comment]
> @kibertoad / @OlivierCavadenti the regression is from the use of `lodash/merge` introduced in this PR: #4047
> 
> merge is not working in the way assumed by the usage and so the value from the second object is taking precedent over the first whereas the implementation implies the expectation that it is the other way round.

Ok thanks for the analysis ! I will fix that this evening as soon as possible.

**Comment by dstarke** [comment]
> merge is not working in the way assumed by the usage and so the value from the second object is taking precedent over the first

@OlivierCavadenti I don't think this is correct. That merge causes the command line arguments to override the settings from the configuration file, which I think is what you want. The problem is that a default client is assigned early as a command line argument if none is supplied there, so it acts like a command line argument and overrides the configuration file value.

**Comment by IlyaSemenov** [comment]
Yep, I confirm that it worked.

**Comment by mohito12** [comment]
I'm still facing the same issue even though I've updated to 1.0.6 🤔

**Comment by dstarke** [comment]
The problem is not fixed for me either.

**Comment by dhensby** [comment]
not fixed for me

**Comment by OlivierCavadenti** [comment]
Fixed here : https://github.com/knex/knex/pull/5106

**Comment by kibertoad** [comment]
@dhensby Can you try 1.0.7?

**Comment by dhensby** [comment]
FYI - just [removing this line](https://github.com/knex/knex/blob/f35f7d4972f47a0a1790b13a555471fe4df0e595/bin/cli.js#L213) fixed it locally for me

Also, you have not pushed the tags into github for 1.0.6 or 1.0.7

I'll test 1.0.7 locally too

**Comment by dhensby** [comment]
1.0.7 appears to work locally for me now

**Comment by kibertoad** [comment]
@dhensby Thank you, published tags and documentation now
