### ISSUE TITLE
Restore node-sqlite3 support

### ISSUE THREAD

**Issue by jgoz** [knex/knex#5117]
# Environment

Knex version: 1.0.5
Database + version: sqlite

# Feature discussion / request

The `sqlite3` package has [new maintainers](https://github.com/TryGhost/node-sqlite3/issues/1292#issuecomment-1095337163) and is [once again receiving updates](https://github.com/TryGhost/node-sqlite3/releases/tag/v5.0.3). 

Based on [this comment](https://github.com/microsoft/vscode-node-sqlite3/issues/11#issuecomment-1096665165) it looks like restoring support for the `sqlite3` package is already being considered, but I didn't see an issue tracking it specifically, which is why I opened this.

**Comment by kibertoad** [comment]
Thanks for the heads-up about it being released, we'll restore support in upcoming release.

**Comment by OlivierCavadenti** [comment]
Thanks for the tracking

**Comment by kibertoad** [comment]
Released in 2.0.0
