### ISSUE TITLE
Postgres connection definitions out of date

### ISSUE THREAD

**Issue by JoelVenable** [knex/knex#5124]
# Environment

Knex version: running ^0.95.14 in production, issue still appears in latest `main` however.
Database + version:  Postgres 12
OS:  darwin/arm64

@lorefnon 

# Feature discussion / request

Typescript interface `PgConnectionConfig` is out of date from the linked DefinitelyTyped file.  I noticed this when trying to set the `idle_in_transaction_session_timeout` property.

**Comment by kibertoad** [comment]
Would you like to send a PR for this?

**Comment by kibertoad** [comment]
Released in 2.1.0
