### ISSUE TITLE
`dropNullable` gives incorrect SQL on MariaDB 10.2.7+

### ISSUE THREAD

**Issue by daniellockyer** [knex/knex#5154]
# Environment

Knex version: 2.0.0
Database + version: `10.5.15-MariaDB-0+deb11u1`
OS: Linux

# Bug

refs https://github.com/TryGhost/Ghost/issues/14634

We've ran into a problem in Ghost where we're unable to drop nullable from a column. It specifically seems to be an issue on MariaDB and after investigation, it seems MariaDB 10.2.7+ returns the default value as a string (`COLUMN_DEFAULT` in https://mariadb.com/kb/en/information-schema-columns-table/), which Knex uses for the column info and appends to the column modify query.

[This](https://github.com/knex/knex/blob/2670c2f8b563bb2ddcbf292172af0c57ed02c16f/lib/schema/tablecompiler.js#L328-L337) block of code seems to append `default: 'NULL'`.

My column was created by Knex and the SQL was:

```sql
alter table `newsletters` add `created_at` datetime null
```

after we populate it, we try and drop the nullable using `.dropNullable()`:

```sql
alter table `newsletters` modify  `created_at` datetime not null default 'NULL'
```

Note: `default 'NULL'` is incorrect and causing the issue.

To test, I printed out `val` here: https://github.com/knex/knex/blob/2670c2f8b563bb2ddcbf292172af0c57ed02c16f/lib/dialects/mysql/query/mysql-querycompiler.js#L132

```
{
  TABLE_CATALOG: 'def',
  TABLE_SCHEMA: 'ghost',
  TABLE_NAME: 'newsletters',
  COLUMN_NAME: 'created_at',
  ORDINAL_POSITION: 21,
  COLUMN_DEFAULT: 'NULL',
...
}
```

I would expect the SQL to be:

```sql
alter table `newsletters` modify  `created_at` datetime not null
```

**Comment by iBotPeaches** [comment]
Took a stab at this. Fixed my Maria install and will attempt to get it upstream and solve whatever I need to get it merged.

https://github.com/knex/knex/pull/5181
