### ISSUE TITLE
hasTable with Schema in mssql

### ISSUE THREAD

**Issue by xJonahS** [knex/knex#5170]
# Environment

Knex version: 2.0.0
Database + version: mssql
OS: windows 10

@smorey2 

# Bug

1. hasTable does not work with schema (withSchema("NAME")) in mssql. You get an error. The issue seems to be caused by this commit:   https://github.com/knex/knex/commit/c4a3abc42d34f47c3306abadc93d09c3ed0480b5

The SQL Statement does not filter for the schema anymore and only for the name of the table. 
![image](https://user-images.githubusercontent.com/58333113/167437740-dda2c4b4-c5cd-4b3b-a0da-92b39f8f7fcb.png)

This part seems to be missing:
![image](https://user-images.githubusercontent.com/58333113/167438175-8fa072c4-ab7d-45b3-bd7c-598f3f3e86d2.png)
(taken from the mysql compiler)

2. Error message
Returns false, when it should return true.

3. Config

`const config: Knex.Config = {
            client: "mssql",
            connection: {
                user: process.env.DATABASE_USER,
                password: process.env.DATABASE_PASSWORD,
                server: process.env.DATABASE_HOST,
                port: Number(process.env.DATABASE_PORT),
                database: process.env.DATABASE_NAME,
                connectionTimeout: 60000,
                options: {
                    trustServerCertificate: true,
                    encrypt: true,
                },
            },
        };`

![image](https://user-images.githubusercontent.com/58333113/167437312-753c7c85-dc3e-4009-8fc9-3b93baea843b.png)
![image](https://user-images.githubusercontent.com/58333113/167437355-305e54e5-0758-4a63-9f0f-4d836ef3d581.png)
![image](https://user-images.githubusercontent.com/58333113/167437414-1793c057-7d8a-4818-aee1-87d066675475.png)

**Comment by kibertoad** [comment]
Released in 2.1.0
