### ISSUE TITLE
Postgres: `indexType` is mistook for `storageEngineIndexType`

### ISSUE THREAD

**Issue by spencerwilson** [knex/knex#5217]
# Environment

Knex version: knex@0.95.14
Database + version: PostgreSQL 12.11
OS: macOS 12.3

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

tl;dr
- Expectation: `indexType` can be `'UNIQUE'` (per [docs](https://www.postgresql.org/docs/14/sql-createindex.html)). `storageEngineIndexType` can be any of `btree`, `hash`, `gist`, `spgist`, `gin`, `brin` (per same docs)
- Actual: Postgres dialect: `indexType` is treated the way MySQL dialect treats `storageEngineIndexType`
- Actual: Postgres dialect: Specifying `storageEngineIndexType` has no effect

The following step in a migration:
```ts
  knex.schema.alterTable('clients', (t) => {
    t.index(['cmsid'], 'some_index_name', {
      indexType: 'UNIQUE',
    });
  });
```

fails with SQL error:
```
error: create index "some_index_name" on "clients" using UNIQUE ("cmsid") - syntax error at or near "UNIQUE"
```

The compiled command should be
```
CREATE UNIQUE INDEX "some_index_name" ON "clients" ("cmsid")
```

Relevant source:
- Knex's msysql dialect uses the `storageEngineIndexType` index option for the `USING` clause, and `indexType` for the keyword between `CREATE` and `INDEX`: https://github.com/knex/knex/blob/8bb9e830ffd2713f87bb672310afae6255f09190/lib/dialects/mysql/schema/mysql-tablecompiler.js#L267-L269
- Knex's postgres dialect uses the `indexType` index option for the `USING` clause, and has no support for compiling a `CREATE UNIQUE INDEX` command: https://github.com/knex/knex/blob/8bb9e830ffd2713f87bb672310afae6255f09190/lib/dialects/postgres/schema/pg-tablecompiler.js#L199-L201

Apologies, I don't have time to create an independent repro repo.

This is the same bug as reported here, https://github.com/knex/knex/issues/4870#issuecomment-1053767311, but broken out into a separate issue.

**Comment by OlivierCavadenti** [comment]
Released in [2.5.0](https://github.com/knex/knex/releases/tag/2.5.0)
