### ISSUE TITLE
How to config database.js: connect remote database (eg: mysql)

### ISSUE THREAD

**Issue by eyea** [knex/knex#5224]
# Environment

Knex version: 1.0.4
Database + version: mysql 5.7.8
OS: centos7.4 nodejs 14,  strapi v4

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Feature discussion / request

1. Explain what is your use case
The project want to connect remote database (MySQL) not local, but knex will install run `npm install mysql`, The Container is not support currently。 
So, knex should support this kind of situalation. 

2. Explain what kind of feature would support this
```code
// database.js
connection: {
    client: 'mysql',
    connection: {
      host: 'remote mysql address',
      port: '3306',
      user: 'user',
      password: 'password',
      database: 'dababase_name',
    },
  },
```

**Comment by JakeHamix** [comment]
Hi eyea. I am not sure what you are referring to.
Knex is very much able to connect to a remote database, as well as a container, by including the remote address in the host field, as you have.
If you are running your **MySql** database instance in a Docker, perhaps you forgot to map the ports?

**Comment by eyea** [comment]
Thanks for your reply. It's the problem of remote container, now has been solved~
I'll close this issue.
Thanks again :)

**Comment by eyea** [comment]
Thanks for your reply. It's the problem of remote container, now has been solved~
I'll close this issue.
Thanks again :)
