### ISSUE TITLE
Using Knex in browser

### ISSUE THREAD

**Issue by mueees** [knex/knex#523]
Hi,
I try to use Knex in browser,
As I understand, I can only generate sql query, but I can not execute them with Knex, is right ?

Thanks for answer.

**Comment by capaj** [comment]
@mueees just a heads up- I have been experimenting with sending knex queries over the wire via socket.io and executing them there.
If you would like to try as well, I have published my work so far as npm module [nexridge](https://github.com/capaj/nexridge) and [nexridge-client](https://github.com/capaj/nexridge-client)

**Comment by araa47** [comment]
Would be great if Knex could use something like IDB, abstracting away the complexity of IDB in browser. Im having to either build a separate client for browser, or look into moving away from knex to something else to keep my NodeJs and Browser client the same. (I need local persistent storage) 

Or does anyone have any better suggestions?

**Comment by elhigu** [comment]
In contributing docs is simple example how to write new dialect support as a separate npm package. Supporting querying in browser is currently not a goal for knex to implement.
