### ISSUE TITLE
Conditional Migration in a database

### ISSUE THREAD

**Issue by sanjaybharti-consort** [knex/knex#5281]
# Environment

Knex version: 2.0.0
Database + version: mysql:8.0.21
OS: Ubuntu:bionic

 @ smorey2.

# Feature discussion / request

How can we set condition on any migration file.
If condition is true then all migrations will run else only specific migration work

**Comment by hemantachhami19** [comment]
One can use [hascolumn](http://knexjs.org/guide/schema-builder.html#hascolumn) or [hastable](http://knexjs.org/guide/schema-builder.html#hastable)  migrations.

**Comment by kibertoad** [comment]
http://knexjs.org/guide/#withuserparams exists for this purpose.
