### ISSUE TITLE
Async/await with mysql2 not disposing of db connection after querying

### ISSUE THREAD

**Issue by azivkovi** [knex/knex#5293]
# Environment

Knex version: 2.2.0
Database + version: Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
OS: Ubuntu 20.04
Node verson: 18.7.0

# Bug

Explain what kind of behaviour you are getting and how you think it should do

If I use promise version (either async/await or .then()) of knex query, the node script hangs and does not dispose of mysql connection resulting in max_connection number reaching the limit in mysql if there are many concurrent user running and rerunning the script. Checking `show processlist;` in mysql show all the connections made by the script in sleep state while the script hangs. After I kill the script, the connection is closed, as well.
This is a problem in my Nextjs app which queries the database and also does not close connections after. If i stop the app and run `npm start` again, the open connections to the db are closed.

 I would expect the connections to clear after query is made so that max connections limit number in mysql is not reached.

Error message

There is no error message, my script just hangs. In Nextjs app, the error appears only after max_connections limit is reached and API returns status 500.

This is a simplified example, but I have the same problem on Nextjs API.

```
const knex = require('knex');

const db = knex({
  client: 'mysql2',
  connection: {
    host: 'localhost',
    user: 'user',
    password: 'password',
    database: 'database',
  },
});

(async () => {
  try {
    await db.from('table').select('*');
  } catch (e) {
    console.log(e);
  } finally {
    console.log('done');
  }
})();
```

**Comment by why-el** [comment]
@azivkovi what was your solution here or was it user error? I am interested to know as I think I might be seeing similar behavior.

**Comment by azivkovi** [comment]
@why-el `knex.destroy();` after script is done executing and you don't need the db connection anymore. In my example above, you would put it in the finally block.
