### ISSUE TITLE
Sqlite3 adding primary key on existing table

### ISSUE THREAD

**Issue by alexandrebodin** [knex/knex#5299]
# Environment

Knex version: 1.0.7
Database + version: sqlite3
OS: mac

# Feature discussion / request

I would love to get the sqlite dialect to run a query to add a primary key to an existing table as it does with column renaming. (e.g creating a tmp table with the new schema and transferring data over).

We need to run a major scale change in our schema to add a primary key in join tables (across multiple dialects so we can run raw queries) Hi from @Strapi :D 

And when doing this add it works fine with Postgres & Mysql but won't work with sqlite3. I think this should be doable with the same approach as rename in theory. 

Would love to get your thoughts.

**Comment by kibertoad** [comment]
Yup, that should work. Would you be open to submit a PR for that? Can help with pointers around our codebase.

**Comment by alexandrebodin** [comment]
I won't be able to tackle this for now. If you don't mind keeping it alive I hope to come back to it eventually.

**Comment by alexandrebodin** [comment]
So after doing some research. It is not necessary per say as you can do the following with sqlite 
```
table.interger('id').unsigned()
table.primary()
```

I think it would be nice to allow table.increments() in the alter that would in the background run the example above. 

@kibertoad what do you think?

**Comment by alexandrebodin** [comment]
Closing for now let's see what the maintainers think :)
