### ISSUE TITLE
Support indexing order by

### ISSUE THREAD

**Issue by daniel-j-h** [knex/knex#5327]
# Environment

Knex version: 2.2
Database + version: Postgres 14
OS: Ubuntu 20.04

# Feature discussion / request

1. Explain what is your use case

With a query like

```sql
SELECT DISTINCT ON (location) location, time, report
  FROM weather_reports
  ORDER BY location, time DESC;
```

to retrieve the most recent weather report for each location, it's beneficial to create an index on `(location, time DESC)`.

```sql
CREATE INDEX weather_reports_idx
ON weather_reports (location, time DESC);
```

At the moment the index features in knex do not allow for indexing order by.

I have tried `table.index(["location", "time DESC"])`, `table.index(["location", "time", "DESC"])` and `table.index([{ column: "location" },{ column: "time", order: "desc" }])`.

3. Explain what kind of feature would support this

Ideally indexing order by would be possible with the index features in knex.

5. Give some API proposal, how the feature should work

The API could look similar to the existing order by APIs, for example

```typescript
table.index([
  { column: "location" },
  { column: "time", order: "DESC" },
]);
```

**Comment by JakeHamix** [comment]
Hi @daniel-j-h,

There are some very specific cases for each dialect that cannot be generalized for creating various index options.
You can cover these as well as order direction in a `knex.raw` query.

```javascript
knex.raw(`CREATE INDEX idx_user_name_desc ON users (user_id, user_name DESC)`)
```

**Comment by daniel-j-h** [comment]
Ah, I see! I didn't think indexing with order by was specific to postgres and that knex wants to stay generic.

Fine with me if you want users to write raw sql queries in these cases :raised_hands: 

I'll close here then, thanks again for taking a look :bow:

**Comment by JakeHamix** [comment]
Sorry for the confusion, I am not a Knex contributor. Specifying column order during index creation is, of course, a generic operation present in the supported dialects - and I can see why it would be useful to have this implemented in the API. I was merely trying to provide you with a way to create this index with the `raw` clause, as you made it seem it was impossible to create it at all given our tools.

There is also the thing, as I mentioned, that I'd imagine most developers use other custom options while creating an index, so this feature wouldn't be much of use unless we also had a way to pass in other options. For example, this is how I might create an index in MSSQL.

```sql
CREATE NONCLUSTERED INDEX [IDX_ITASK_DUE_DATE_FINISH] ON [TAS].[INSTANCE_TASKS]
 ([ITASK_DUE_DATE_FINISH] ASC,
 [ITASK_DURATION] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILL_FACTOR = 80) ON [PRIMARY]
```
