### ISSUE TITLE
Prepend "EXPLAIN" to query

### ISSUE THREAD

**Issue by Turbotailz** [knex/knex#5347]
This is more of a question on usage. I am wanting to run an `EXPLAIN` query in postgres on a query that is built by the query builder but I am not sure on the best method to prepend this raw statement to the query builder.

**Comment by Turbotailz** [comment]
I was able to do the following. Keen to know if there is a better method.

```js
const { sql, bindings } = query.toSQL();
const raw = knex.raw(`EXPLAIN (FORMAT JSON) ${sql}`, bindings);
```

**Comment by peisenmann** [comment]
It does seem like there should be some kind of thing built in for that, but I couldn't find one either
