### ISSUE TITLE
knex.mjs is missing in the package

### ISSUE THREAD

**Issue by vyobukhov** [knex/knex#5354]
# Environment

Knex version: 2.3.0
OS: MacOS

# Bug

Hi guys, there is an issue with using knex with mts/mjs files (Node 18 + TS 4.8)

Documentation says:
> If you are launching your Node application with --experimental-modules, knex.mjs should be picked up automatically and named ESM import should work out-of-the-box. Otherwise, if you want to use named imports, you'll have to import knex like this:
> `import { knex } from 'knex/knex.mjs'`

But package installed from npm / git does not contain `knex.mjs` file. It's presented in the repo but not in the final package / build.

**Comment by OlivierCavadenti** [comment]
Released in [2.5.0](https://github.com/knex/knex/releases/tag/2.5.0)
