### ISSUE TITLE
Inserting into PostgreSQL array columns are broken on master branch

### ISSUE THREAD

**Issue by cjmaio** [knex/knex#5365]
# Environment

Knex version: master
Database + version: PostgreSQL 12.6
OS: Ubuntu 18.04

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Using `knex` to insert an array into a PostgreSQL array column causes the array to be stringified, whereas `node-pg` expects it to be an array type. This looks to be introduced by https://github.com/knex/knex/pull/5321

2. Error message

```
 "error": "malformed array literal: \"[\"78a50219-9262-4d6f-86ab-b14734440679\"]\"",
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Given a table with the structure:

```sql
CREATE TABLE foo (
  foo_id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  numbers integer[]
);
```

```javascript
knex(.insert({
  numbers: [1, 2, 3]
}).into('foo').toSQL().toNative();
```

**Comment by kibertoad** [comment]
Released in 2.4.1
