### ISSUE TITLE
Knex.js has a limited SQL injection vulnerability

### ISSUE THREAD

**Issue by saunish-bytap** [knex/knex#5420]
# Environment

Knex version:
MYSQL2 + 2.3.0:
OS: Kubuntu

# Bug

npm install --save knex gives warring 
`knex  *
Severity: high
Knex.js has a limited SQL injection vulnerability - https://github.com/advisories/GHSA-4jv9-3563-23j3
No fix available
node_modules/knex`

Need to have clean install without warrning......

**Comment by OlivierCavadenti** [comment]
Related to https://github.com/knex/knex/issues/1227
