### ISSUE TITLE
Unknown file extension ".ts" for /home/[user]/stock_analysis_app/knexfile.ts

### ISSUE THREAD

**Issue by gatlace** [knex/knex#5425]
# Environment

Knex version: 2.3.0
Database + version: Postgres 12
OS: Ubuntu(WSL2)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I can't make migrations with typescript. `yarn knex init -x ts` then `yarn knex migrate:make test_migration -x ts` gives me an error. I've tried removing package_lock and node_modules, installing globally, installing ts-node, and recloning the whole repo.

3. Error message
```
Unknown file extension ".ts" for /home/zii/stock-analysis-app/knexfile.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/[user]/stock-analysis-app/knexfile.ts
    at new NodeError (node:internal/errors:400:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:74:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:114:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:161:28)
    at ESMLoader.load (node:internal/modules/esm/loader:596:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:448:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:471:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:425:34)
```

5. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

[the repo with the problem, knexfile included](https://github.com/gatlace/stock-analysis-app)
I'm sorry, I don't think a minimal code representation would help.

**Comment by gatlace** [comment]
I think the problem is that I'm using sveltekit, which runs on the browser. The whole project might be configured to run on the browser, and getting knex to work with it might just not be something I'm equipped to do.

**Comment by swznd** [comment]
I don't think it's relate with sveltekit and browser, because it runs on terminal, not in browser, and sveltekit can run on server too.

**Comment by gatlace** [comment]
> I don't think it's relate with sveltekit and browser, because it runs on terminal, not in browser, and sveltekit can run on server too.

It's the way sveltekit sets up the project, I forgot what it is exactly but I think it's because sveltekit needs `"type": "module"` to run, but you can't have it in the project where you run knex (I think it's because you need "module": "Node" and that kinda clashes). Idk. I just have two separate projects, one for svelte and one to manage the db on localhost. It does the job well enough.

to reproduce:
create a sveltekit project, install knex, make the knexfile(works), and try making migrations(doesn't work).
then create a new project with node, install knex, and make the migrations(works)
