### ISSUE TITLE
Way to test db connection

### ISSUE THREAD

**Issue by tgriesser** [knex/knex#545]
Would be useful...

**Comment by kibertoad** [comment]
There is also a library that provides this functionality (with preset test queries for different dbs) out of the box: https://www.npmjs.com/package/knex-utils

**Comment by KaKi87** [comment]
Hello,

This issue should be reopened and a connection method should be implemented.

Thanks

**Comment by elhigu** [comment]
@KaKi87 nope. This should not be reopened and I have no idea what you mean by connection method 🤷‍♂ Please open a feature request if there is a new feature that you would like knex to have.

**Comment by yumindeckard** [comment]
The connection status should be logged in the console.  Query some dummy data from database is a workaround, not the solution.

**Comment by KaKi87** [comment]
@elhigu A connection method can be a method called `db.connect()` for example.

**Comment by elhigu** [comment]
@yumindeckard you can add event handlers to tarn to log that kind of stuff. There are events telling if connection acquire fails for example and many other. Also if you need to log connection status on knex side you can add `knex.on('query-success', ...)` and  `knex.on('query-error', ...)`event handler to print if query was success or if it failed for some reason and you can even choose to print error only if it was connection error (btw. it is also ambiguous if for example bad credentials as connection error or invalid SQL db user rights for some table / db or is it strictly the case where network or database is down).

@KaKi87  Making query is the only way to check if you are able to access your DB and having `db.connect()` would just wrap that dummy query to pretty much useless wrapper method which might give you false sense of security that there is stable connection... Next time you call `db.connect()` 10ms after it was fine the connection might be already broken. 

If you need that kind of method knex nowadays offers API to add extensions so you can write separate knex-plugin for that method.
