### ISSUE TITLE
How to access userParams from within queryBuilder?

### ISSUE THREAD

**Issue by sleewoo** [knex/knex#5463]
# Environment

Knex version: any
Database + version: any
OS: any

# Feature discussion / request

using `withUserParams`  to get specialty flavors of `knex` and it works great:

```ts
const db = knex.withUserParams({ tableName: "table_name" });
```

now i can get `tableName` from anywhere by `db.userParams.tableName`.
well, almost, from anywhere where `db` is accessible.

but seems `userParams` not accessible inside query builder instance:

having a file with queries (maybe even as 3rd party lib): `some-path-or-lib/queries.ts`

```ts
export function someQueryThatNeedUserParams() {
  this.userParams // is undefined here
}
```

another file - making use of queries:

```ts
import { someQueryThatNeedUserParams } from "some-path-or-lib/queries";

db("table").where(someQueryThatNeedUserParams)

```

Seems `KNEX_PROPERTY_DEFINITIONS` and `CONTEXT_METHODS` only applied to knex instance.
What if `userParams` getter also added to query builder?
Ready to experiment and submit a PR.

Thanks.

**Comment by dmtkpv** [comment]
As for version 3.1.0, the only way is to patch the package.
Pass `userParams` to the `client`:
```js
// lib/knex-builder/make-knex.js:223
knexClone.userParams = knexClone.client.userParams = params;
```

Now you can get `userParams` from `queryBuilder`
```
knex.QueryBuilder.extend('me', function () {
    return this.where('id', this.client.userParams.user)
});

const db = knex.withUserParams({ user: 1 });
const me = await db('users').me();
```

If you are using transaction, pass `userParams` to `trxClient`
```js
// /lib/execution/transaction.js:338 add:
trxClient.userParams = client.userParams;
```

**Comment by sleewoo** [comment]
thanks @dmtkpv
