### ISSUE TITLE
[PR] add fetchAsString props to Knex.Config interface

### ISSUE THREAD

**Issue by muhammad-syaifudin** [knex/knex#5485]
# Environment

Knex version: 2.3.0
Database + version: Oracle Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit 
OS: macOS Ventura 13.2

# Missing fetchAsString props on Knex.Config interface

PR was sent [here](https://github.com/knex/knex/pull/5484)

**Comment by OlivierCavadenti** [comment]
Merged as completed in https://github.com/knex/knex/pull/5484
