### ISSUE TITLE
Knex fails on module load/import.

### ISSUE THREAD

**Issue by codelocksdev** [knex/knex#5493]
# Environment

Knex version: 2.4.2
Database + version: sqlite3
OS: both windows and mac

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
`import Knex from 'knex';` causes app to crash as the module loads. 

2. Error message
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/knex/lib/execution/transaction.js (transaction.js:43:1)
    at __require2 (chunk-TFWDKVI3.js?v=2a9dbd5b:18:50)
    at node_modules/knex/lib/client.js (client.js:10:21)
    at __require2 (chunk-TFWDKVI3.js?v=2a9dbd5b:18:50)
    at node_modules/knex/lib/knex-builder/Knex.js (Knex.js:1:16)
    at __require2 (chunk-TFWDKVI3.js?v=2a9dbd5b:18:50)
    at node_modules/knex/lib/index.js (index.js:1:14)
    at __require2 (chunk-TFWDKVI3.js?v=2a9dbd5b:18:50)
    at node_modules/knex/knex.js (knex.js:8:14)
    at __require2 (chunk-TFWDKVI3.js?v=2a9dbd5b:18:50)
```

I'm running a basic nrwl-nx repo, and the error occurs whether the import takes place in a library or in the frontend app. As I understand it this error usually comes from some kind of circular dependency where the class being extended is not initialized when the subclass is getting loaded with the module. This is the only file where I'm importing the knex module so I don't see how it could be a circular dep on my side, and anyway it's happening during the dependency loading stage before runtime. For other context I'm also trying to set this up with objectionjs, however even when I remove all objection imports, and only import knex, the error persists.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by VandalPaulius** [comment]
@codelocksdev  How did you solve it? I have exact same issue, but it happens even with `import Knex from 'knex'` and nothing else

**Comment by JackMostert** [comment]
This error was caused by knex extending the EventEmitter class which is a nodejs module; I managed to solve that error by using a pollyfill for nodes EventEmitter;

```ts
import { defineConfig } from "vite";
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
  plugins: [ nodePolyfills({ include: ["events"] }) ],
});
```

Hope this helps.
