### ISSUE TITLE
V2.4.0 malformed array literal saving array into postgres

### ISSUE THREAD

**Issue by stevenwang-oohmedia** [knex/knex#5494]
# Environment

Knex version: 2.4.0
Database + version: postgres 14.6
OS: MacOS

# Bug

1. After upgraded to v2.4.0, knex converted array into string though the database field is text[]. The issue cannot be reproduced on knex v2.3.0. 

2. Error message: `malformed array literal`

3. I assume the issue is caused by this commit https://github.com/knex/knex/pull/5321

**Comment by OlivierCavadenti** [comment]
Fixed with https://github.com/knex/knex/commit/1f2de49fbe2553a1f8ab44598380d506f6b73474
