### ISSUE TITLE
Disconnecting and shutting down database connection

### ISSUE THREAD

**Issue by moll** [knex/knex#55]
Hey,

I'm writing a cluster manager and zero downtime restart library and had a need to shut down the database connection pool that Knex set up. How would I do that?

I do see `poolInstance.drain` and `destroyAllNow` used in the `base.js` file. Are those meant to form the public interface for shutting down Knex?

**Comment by gregbty** [comment]
This works fine with the migrations API but the seed API doesn't seem to adhere to the destroy call. If I try knex.migration.latest alone with knex.destroy it works fine, but knex.seed.run does not.

```js

var instance = knex(db);

return instance.migrate.latest()
  .finally(function () {
      return instance.destroy(); //works
    });

...

return instance.seed.run()
  .finally(function () {
      return instance.destroy(); //does not work
    });
```

**Comment by alechirsch** [comment]
+1 for @gregbty 

The knex instance is not destroyed after running seed. Any ideas?

**Comment by thebrodmann** [comment]
The issue exists as mentioned in https://github.com/tgriesser/knex/issues/55#issuecomment-85361904. Are there any workarounds?

**Comment by elhigu** [comment]
@thebrodmann Please open bug report, this issue was closed, because it was about different thing.
