### ISSUE TITLE
Update Multiple Unique Rows in Single Query

### ISSUE THREAD

**Issue by 58bits** [knex/knex#556]
I'd like to do the following, via knex, against a PostgreSQL DB:

```
update test as t set
    column_a = c.column_a
from (values
    ('123', 1),
    ('345', 2)  
) as c(column_b, column_a) 
where c.column_b = t.column_b;
```

My values will come from an array, of indeterminate size. Apart from string building the query (in a loop), and using knex.raw, is there anything knex can do to lend a hand?

**Comment by alexc101** [comment]
@58bits @bendrucker I'm trying to do something similar, but don't understand how to build the values statement.

Here is what I have -

````
let string = knex
        .into('test t')
        .update('auth, c.auth')
        .values('(1, 1, false), (2, 1, false)')
        .where(knex.raw('c.id1 = t.id1 AND c.id2 = t.id2'))
        .toString()

        knex.raw(string)
````
Here is an sql fiddle of query I'm trying to recreate : http://sqlfiddle.com/#!17/62529/8

Hope you could help point me in the right direction?

Cheers
