### ISSUE TITLE
Bug: Interrupted streaming query pipe may result in the query stream never being closed and the connection it uses never being freed

### ISSUE THREAD

**Issue by pineapplemachine** [knex/knex#5589]
# Environment

Knex version: 2.4.2 (latest)
Database + version: Tested with `PostgreSQL 13.5 (Ubuntu 13.5-0ubuntu0.21.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, 64-bit`
OS: Tested with Kubuntu 22.04

**Please be aware that although I have used postgres in testing and reproducing this issue, I believe that it is not specific to postgres.**

# Bug

I have run into an issue with Knex query streams. I wrote a script that reproduces this issue along with instructions on how to observe it here: 

**knex-streaming-error-repro:** https://github.com/pineapplemachine/knex-streaming-error-repro

---

The short version:

When using a Knex query stream, if the consumption of that stream is interrupted in any way, then the stream never closes and the connection it uses is never freed up.

For example, when an express server pipes the results of a streaming query to an express response object, if the request is aborted then the query stream may never be closed. This unclosed stream may subsequently block operations that modify the tables being queried, causing subsequent queries executed through Knex to hang forever.

**This is not an issue with express. I am using express as an example.** This issue occurs if _any_ stream that the Knex query stream is piped to exits before it fully consumes the Knex query stream. 

---

In more detail:

I am using Knex to connect to a postgres database, and the repro script also uses postgres. But I think that this same error behavior will occur with other databases as well, due to the way that the `_stream` method is generally implemented for Knex's `Client` subclasses.

See for example the `_stream` method of the `Client_PG` class: https://github.com/knex/knex/blob/b6d04f75b3c1956be8ffa26740dd1e27909dd25d/lib/dialects/postgres/index.js#L187

Note that the `PGQueryStream` instance in this example is not visible outside the `_stream` method that constructs it. It is piped to the stream passed as an argument to the method, without being returned or otherwise exposed. Errors will not be propagated back to the query stream via this pipe. This means that if anything happens to interrupt the streams that the `PGQueryStream` is piped to, then that interruption will not be propagated via stream events, and there is no way (that I am aware of) to handle this and to explicitly close the query stream, or to free the database connection that it's using.

This means that I cannot use Knex's streaming queries in the server that I develop, because if (for example) a client request is aborted before all the streaming data is received, then the server is left with a database connection that is never released back to the pool. Besides taking this connection permanently out of the connection pool, this can also cause operations that modify the tables being streamed from to hang forever, waiting for the abandoned read query to finish (which it never does).

Note the repository linked at the beginning of the issue, which contains instructions and a script for reproducing this issue multiple ways. It can reproduce the issue where a request being handled by express is aborted, and it can also reproduce the issue by simulating an error in an arbitrary transform stream that the query stream is piped to.

**Comment by silenceisgolden** [comment]
I'm seeing random hangs of knex in our prod environment and have been trying to figure it out for months. I'm super eager to see if this next release fixes it!

**Comment by pineapplemachine** [comment]
I'm closing this issue now because it is solved for me as of updating to v2.5.1.
