### ISSUE TITLE
knex migrate

### ISSUE THREAD

**Issue by zanzara** [knex/knex#5591]
# Environment

Knex version:  2.4.2
Database + version:  Postgre  8.10
OS:  Linux

# Bug

if I create a new db migration file `knex migrate:make <newfile>`  (w/o -x ts param)
I got this scaffold made:

```js
/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function(knex) {
}
``` 

but this leads me to that error:

```
exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '........../package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: exports is not defined in ES module scope
``` 
But my migration files, which I just have, looks rather like that:

```js
export async function up(knex) {
  
}
```
which works w/o errors.

# Missing / erroneus documentation

If that would has smt to do with esm...
Regarding this link in the docu is unfortunately dead:  
https://knexjs.org/guide/migrations.html#esm-interop

# Questions about how to use knex

So how should I use `knex cli`  to get my old scaffolds done?
Did smt changed in `knex cli` regarding this?
Do i need a stub file?  And if so , how should it look like?
TIA

**Comment by houldsg** [comment]
You could use the [stub config option](https://knexjs.org/guide/migrations.html#custom-migration)  in the `migrations` part and either reference the internal stub (as below) , or copy it to the root folder (probably a better option than referencing knex internals)
``` javascript
{
  development: {
    client: 'pg',
    connection: {}, //whatever yours already looks like
    migrations: {
      directory: './something',
      stub: './node_modules/knex/lib/migrations/migrate/stub/mjs.stub'
    }
  }
}
```

**Comment by houldsg** [comment]
Sorry @zanzara, I don't know if it used to work differently. I'm still using the old CJS style modules in my knex projects.

**Comment by zanzara** [comment]
> Sorry @zanzara, I don't know if it used to work differently. I'm still using the old CJS style modules in my knex projects.

So, which is newer:  `exports.up`  or `up(knex)` ?

**Comment by houldsg** [comment]
`exports.up = function(knex)` is the older CJS module style used with `require`
`export async function up(knex)` is the newer ESM module style used with `import`
