### ISSUE TITLE
IBM i DB2 custom dialect

### ISSUE THREAD

**Issue by bskimball** [knex/knex#5611]
I don't see anything in the documentation about writing a custom dialect. I would like IBM i DB2 support. There is a custom dialect here https://github.com/henryjw/knex-db2 but it has not been maintained. 

I was going to fork it and update it but I didn't know if you all had any guidance on what that needed to look like. I can of course look at some of the other dialects and go from there. 

Thank you!

**Comment by bskimball** [comment]
I found the page https://github.com/knex/knex/blob/master/CONTRIBUTING.md

**Comment by manuelmolinaf** [comment]
Hello, did you ever get around to updating it?

**Comment by bskimball** [comment]
I did you can find it here https://www.npmjs.com/package/@bdkinc/knex-ibmi

Let me know if you have any issues. Here is the github repo https://github.com/bdkinc/knex-ibmi

**Comment by manuelmolinaf** [comment]
Thanks! ^-^

**Comment by manuelmolinaf** [comment]
Hey! Thanks, got it working👍 Only ran into a minor issue. In the DB2Config interface, in the DB2ConnectionParams the ALLOWPROCCALLS property isn't defined. Didn't really need it but wanted to let you know.
