### ISSUE TITLE
Why is my query extremely slow, only in in seed?

### ISSUE THREAD

**Issue by abcd-ca** [knex/knex#5622]
# Environment

Knex version: 1.0.7
Database + version: Postgres 14
OS: macOS 13.4.1

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I noticed a query is taking between ~120 seconds and 5 minutes to execute from my Knex seed script using Knex. When I do `.toString()` on the query to get the SQL and copy and paste that and run the query in my db client it takes about 2-4 seconds. It takes a similar amount of time if I run the same Knex call in my express server.ts file. So it's something about it running in the seed script. I have tried the higher level Knex api and also knex.raw which are comparable. I am running other queries before and after this query in the same seed script and they are fast.

2. Error message
No error message

4. Reduced test code

I have a custom postgres function. When I run this in my db client (DB is running locally) it takes ~2s:

```SQL
SELECT * FROM get_user_meal_sessions(123) limit 1
```

But if I run it from my seed script like this: 

```Typescript
await knex.raw(`SELECT * FROM get_user_meal_sessions(?) limit 1`, [myUserId])
``` 

it takes ~120s to 5 min. 

Running it in server.ts is fast (~2s), just not in the seed. 

I need to find a way to speed this up

**Comment by abcd-ca** [comment]
Update: If I run this in my server code it's just as fast as it is in the desktop db client so it's just in the seed script that it's slow, apparently.

**Comment by abcd-ca** [comment]
More data. Tried using `explain analyze` and these are the results:

Directly in desktop db client:
 
Limit  (cost=0.25..0.26 rows=1 width=140) (actual time=462.908..462.908 rows=0 loops=1)
  ->  Function Scan on get_user_meal_sessions  (cost=0.25..10.25 rows=1000 width=140) (actual time=462.907..462.907 rows=0 loops=1)
Planning Time: 0.083 ms
Execution Time: 462.980 ms
 
------------------------------------------------
 
in middleware with knex
 
Limit  (cost=0.25..0.26 rows=1 width=140) (actual time=316016.247..316016.247 rows=1 loops=1)
  ->  Function Scan on get_user_meal_sessions  (cost=0.25..10.25 rows=1000 width=140) (actual time=316016.246..316016.246 rows=1 loops=1)
Planning Time: 0.021 ms
Execution Time: 316016.431 ms

That last one is 5 minutes!

**Comment by arbezerra** [comment]
Do you make more than one call of the function in the seed script?
Maybe knex is sending concurrent requests and overloading the postgres or waiting for a lock release.

**Comment by abcd-ca** [comment]
No, just the one callOn Jul 6, 2023, at 23:15, André Ricardo ***@***.***> wrote:﻿
Do you make more than one call of the function in the seed script?
Maybe knex is sending concurrent requests and overloading the postgres or waiting for a lock release.

**Comment by abcd-ca** [comment]
update: so my function (in SQL) is recursive. I created two variants. One that gets all records for all users and another that is a copy of the first but has a userId param that causes it to return only records for that userId. The point was to make a more efficient version when you know you need only records for the one patient (I tried unifying with an optional param it but it was taking too much time to get it right). Again, all this is in the SQL function definition itself, not in the middleware. When testing these two functions both in my expresss server.ts and directly in the desktop DB client, as intended, the one that filters by userId was more performant. Both were acceptably fast. My seed script was using the function that took a userId and was taking ~5 minutes for some weird reason. 

Today out of desperation, I tried switching the seed script to using the one that gets all records for all users and did the userId filter after the function call (`select * from get_all_meal_sessions() where "userId" = ?`). That should be less performant and would be outside of the seed but in the seed that was actually very fast. I just can't understand why the other version would be so slow only in the seed. If anyone has ideas, I'd love to hear them.

**Comment by arbezerra** [comment]
Can you share the function code and the part of the schema that it uses?
