### ISSUE TITLE
Dropping support for old Node versions in favor of Node 20

### ISSUE THREAD

**Issue by stscoundrel** [knex/knex#5631]
# Feature discussion / request

Hello. I tried to add Node 20 to to CI / GH actions version matrix. That quickly leads to some incompatibility issues, as Knex currently supports all Node versions 12 and above.

This makes it a bit tricky to support current Node versions. For example, adding Node 20 means we'd need to update `better-sqlite3` to 8.X.X version. Updating `better-sqlite3` remedies Node 20 situation, but also drops the support for Node 12 & 14. There may be other similar issues, but this was the first one I faced.

As currently only Node versions 16, 18 and 20 are maintained, I'd suggest that Knex also drops support for versions 12 and 14. It would allow us to bump some dependencies to their latest versions and include Node 20 support. There already is some glue-code to make CI run with Node 12 and more will come as other libraries drop support for unmaintained Node versions. 

However, as this is technically breaking change and could require major version bump, I thought I'd open a discussion about it. How are we feeling about dropping the old versions in favor of the new?

**Comment by kibertoad** [comment]
I'm ok with dropping unsupported versions after Node 20 goes LTS

**Comment by stscoundrel** [comment]
That would be 2023-10-24 according to current schedule, which seems fair enough

**Comment by OlivierCavadenti** [comment]
Yes, I agree, I made some dirty fixes because of Node 12... (with mysql for example). OracleDB breaks also with node <14

**Comment by stevefan1999-personal** [comment]
@kibertoad maybe we could at least drop 14 or it will be very long for node-oracledb 6.0 to be merged

**Comment by jpike88** [comment]
AWS is deprecating EB nodev14 now fyi

**Comment by kibertoad** [comment]
Sure, let's drop 12 and 14 already. Can you send a PR?

**Comment by hima2131232** [comment]
This issue has been closed, but Knex still doesn't seem to be compatible with node 20 though. We get the following linter error when trying to bump it up on our own and build:

```
npm run lint:everything
npm WARN using --force Recommended protections disabled.

> knex@3.0.0 lint:everything
> npm run lint && npm run lint:types

npm WARN using --force Recommended protections disabled.

> knex@3.0.0 lint
> eslint --cache

npm WARN using --force Recommended protections disabled.

> knex@3.0.0 lint:types
> tsd && dtslint types

Installing to /home/himanshu/.dts/typescript-installs/5.4...
npm WARN config shrinkwrap Use the --package-lock setting instead.
npm WARN using --force Recommended protections disabled.

Installed!

TypeError: (0 , header_parser_1.parseTypeScriptVersionLine) is not a function
    at getMinimumTypeScriptVersionFromComment (/home/../Desktop/originalKnex/knex/node_modules/dtslint/bin/index.js:244:59)
    at /home/../Desktop/originalKnex/knex/node_modules/dtslint/bin/index.js:157:39
    at Generator.next (<anonymous>)
    at fulfilled (/home/../Desktop/originalKnex/knex/node_modules/dtslint/bin/index.js:6:58)

```

Any ideas why this happens and how it could be resolved?

**Comment by kibertoad** [comment]
@hima2131232 This is related to dtslint being deprecated and not supporting Node 20. In order to resolve this we need to move our dtslint tests to tsd. Any PRs that advance that in that direction would be greatly appreciated.
