### ISSUE TITLE
 database auto model

### ISSUE THREAD

**Issue by akelmj** [knex/knex#5702]
Hi,

how to auto generate model for existing database medel like sequlize-auto?

**Comment by wolfhoundjesse** [comment]
[kanel-knex](https://www.npmjs.com/package/kanel-knex) is an extension for kanel that does this.

**Comment by akelmj** [comment]
> [kanel-knex](https://www.npmjs.com/package/kanel-knex) is an extension for kanel that does this.

This is only for Typescript, i use es module.

**Comment by akelmj** [comment]
I'm searching for extension that create the MODEL automatically fo commonJS or ES module, any Idea?

**Comment by akelmj** [comment]
Ok , the answer is so simple :)

`npx prisma db pull`
