### ISSUE TITLE
Escaping Backslash using Knex.raw for \Copy command in Postgres

### ISSUE THREAD

**Issue by BrandonMcNary** [knex/knex#573]
Hi,

We were trying to use the \COPY command in Knex.raw. We connect via heroku/postgres and the \COPY is the only way to bulk import data as we don't have superuser rights. The backslash before the copy is being removed or multiplied depending on what you try. 

So far we've tried to escape it using 
1. \b
2. \
3. String.fromCharCode(92)
4. concatenation

The full function we're using is...

knex.raw("\COPY tablename (column1, column2, ...columnN) FROM STDIN " + csvValues).then(function(response){
        console.log('the response from the copy', response);
    });

We've tested this exact function within our pg:psql environment and it works perfectly. If you know of a better way of doing this, please let us know!

Regards,
Brandon

**Comment by joshAg** [comment]
Is it still the recommendation to consider not using knex for large insertions?

**Comment by elhigu** [comment]
@joshAg depends completely on your case... I suppose you should be able to do at least something like 10000 rows / second with it. Depends on lot of things. So use it if it works for you.
