### ISSUE TITLE
Increments starting at a high number, DB Migration

### ISSUE THREAD

**Issue by marksark** [knex/knex#5759]
I am using Knex with a postgresql DB. I am trying to use createTable.increments() but start the ID at 10000 or some higher number than 1. Any ideas on this and how to accomplish it? I have checked the docs and see nothing that points me in the right direction.

**Comment by davidKirshbom** [comment]
did you delete the table rows? or is first insert to the table after create initial?
can you paste here this part of code?

**Comment by HonzaMac** [comment]
This should help yout to achieve that: 
`select setval(pg_get_serial_sequence('table_name', 'column_name'), 1000);
`

**Comment by marksark** [comment]
@HonzaMac that worked thanks!
