### ISSUE TITLE
same query builder generate different query on different machine

### ISSUE THREAD

**Issue by HarryC004** [knex/knex#5766]
# Environment

Knex version:2.4.2
Database + version:PostgreSQL 15.5
OS:Mac

# Bug

We have a query trying to do insert().conflict().merge(): 
obj = {
 id: xx,
 name: xxx, 
 address: xxx,
}
knex('sites').insert(obj).onConflict(['id']).merge()

Table sites have four columns: id, name, address, logo.

on my local machine, the query generated is: 
insert into sites
(id, name, address, logo) values 
(xx, xxx, xxxx, default)
......

However, on my colleague's machine, it generates as: 
insert into sites
(id, name, address) values 
(xx, xxx, xxxx)
......

which causing different behaviour when conflict().merge(). 

So questions is: why the same code base with same knex + knex-postgis version produce different query ?

**Comment by kibertoad** [comment]
Have you tried debugging what parameters are passed to knex at that line? There are many reasons why different machines can behave differently, e. g. some versions resolved differently if package-lock is not shared, or some internal dependency not rebuilt. Knex shouldn't be adding or discarding insert parameters on its own, it is likely just passing through what it is receiving. So you should validate that the input to that query is the same in both cases.

**Comment by HarryC004** [comment]
@kibertoad 
Thanks for the response, after debugging I think I figure out the reason. 
Based on the querycomplier.js file, line 1263, _prepInsert function (knex v2.4.2), the construct of the query column is by going through all data object: 
Which means for following data, the columns will generated differently: 
1. 
[
{id: 1, name: 1, address: 1, logo: 1},
{id: 2, name: 2, address: 2}
]
will produce columns of: ['id', 'name', 'address', 'logo']

2. 
[
{id: 1, name: 1, address: 1},
{id: 2, name: 2, address: 2}
]
will produce columns of: ['id', 'name', 'address']

hence causing the issue I mentioned in the question. 

This won't have any problem in inserting data, but it will sometimes raise issue on insert.conflict.merge. 

My question now is: is there a way to force knex to generate full columns based on table schema but not based on data object ?

**Comment by kibertoad** [comment]
No, knex never uses any of the table schema for non-migration related queries. Behaviour that you have described is correct - if you pass the data, it will be inserted. If column is not supposed to be there, remove it from the data you are trying to insert.
