### ISSUE TITLE
Data type limitations and best practices documentation

### ISSUE THREAD

**Issue by ErisDS** [knex/knex#58]
I can start adding some documentation myself, but wanted to raise this as something to think about.

The joy of knex is abstracting away the pain of trying to support multiple databases, but I'm finding there isn't enough documentation around the datatypes to know what I can and cannot store in each one. I'm doing quite a bit of research to figure it out, and I'm thinking I won't be the only person who needs this information - so the basic limitations/expectations should probably be in the knex documentation perhaps with extended info on a wiki page detailing how different dbs will behave with different types.

Specifically, if I store a string, how long can it be? MySQL < 5.0.3 only allows 255 chars. MySQL >= 5.0.3 allows 65,535. SQLite is practically unlimited, PostGres is 1Gb. 

Looking at the code I see:

```
string: function(column, length) {
      return this._addColumn('string', column, {length: (length || 255)});
},
```

So by default knex will limit my string to 255, which makes sense - it's the maximum safe value across the 3 DBs, but it doesn't constrain the length, so if I were to specify a string column with length 300, knex would attempt to create that as far as I can tell.

Equally if I'm working in SQLite, the length will be ignored, and I'll be able to save any length string. Knex doesn't yet do any sort of parsing / validation of data (I know it's in the pipeline, esp around dates) so even though it looks like I've declared a limit, my application actually has to manage this itself.

My main point is that it is not clear what the limitations, restrictions or behavioural differences of the different datatypes are across the DBs and that this would be useful documentation. 

Also, as a future improvement it would be good to be able to rely upon knex to ensure that these datatypes behave reliably across different databases.

**Comment by elhigu** [comment]
There is nowadays recipes book in github wiki. Closing old inactive issue.
