### ISSUE TITLE
Using knex with dotenv

### ISSUE THREAD

**Issue by ghost** [knex/knex#590]
Hi,
is there a simple way to use Knex and the migration/seed CLI with [dotenv](https://github.com/motdotla/dotenv)?

**Comment by mbavio** [comment]
In case anyone comes here looking for a solution, here's what I do (and it works like charm!)

`require('dotenv').config({path: 'path_to_env_file'});

module.exports = {
  client: 'pg',
  connection: {
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASS,
    database: process.env.DB_NAME
  }
};
`

**Comment by Jakobud** [comment]
@mbavio Thanks that fixed it the issue. The problem for me specifically was that I have my knexfile.js is a subdirectory of my project, not at the root directory. So therefore it couldn't find my `.env` without passing the path to it. Thanks again!

**Comment by irakliOrbis** [comment]
I have the problem when I want to run `knex migrate:currentVersion` it is not loading from .env file. what can I do to resolve that?

**Comment by kcheang** [comment]
I had the same problem when I tried to run migrations as npm scripts. It worked when I changed the script to `node -r dotenv/config ./node_modules/knex/bin/cli.js migrate:latest`.

**Comment by marcosilvestroni** [comment]
Hi, everyone It's possibile to run knex in silent mode, so without asking me via prompt the environment , I'm deploying in a different machine via ssh

**Comment by gerbus** [comment]
With Babel (ES6) you can do:

```javascript
import dotenv from 'dotenv'; 
dotenv.config();

export default require('knex')({
  debug: true,
  client: 'mysql',
  connection: {
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PW,
    database: process.env.DB,
    charset: 'utf8',
  }
});

**Comment by IceBroForever** [comment]
> I had the same problem when I tried to run migrations as npm scripts. It worked when I changed the script to `node -r dotenv/config ./node_modules/knex/bin/cli.js migrate:latest`.

You are f*cking genius

**Comment by RaimoJohanson** [comment]
You may find this helpful:
`env $(cat .env) knex migrate:latest`

Please note that in this case Knex is expected to be installed globally

**Comment by Jakobud** [comment]
@RaimoJohanson A more proper way to do that would be

`env $(cat .env) ./node_modules/.bin/knex migrate:latest`

or if you are using an NPM Script:

`env $(cat .env) knex migrate:latest`

**Comment by RaimoJohanson** [comment]
@Jakobud I read up about the .bin directory being used by Node internally in npm scripts - thanks for that!

**Comment by vladinator1000** [comment]
@Jakobud this wouldn't work on Windows

**Comment by vajdagabor** [comment]
With multiple `.env` files it might be a solution to use the `DOTENV_CONFIG_PATH` environment variable. In my `package.json` I created a `test` script that picks up `.env`, and a `test:knex` that works with `.env.test`:

```json
"scripts: {
  "knex": "babel-node -r dotenv/config node_modules/.bin/knex",
  "test:knex": "DOTENV_CONFIG_PATH=.env.test npm run knex"
}
```

**Comment by robertkibet** [comment]
I have this setup, was struggling with same situation also, which is working for me now:
```
    "start": "nodemon -r dotenv/config -r module-alias/register index.ts",
```

**Comment by atefBB** [comment]
> ```js
> {path: 'path_to_env_file'}
> ```
@marbiano  Thank you, you save my day !

**Comment by oldmonad** [comment]
> @RaimoJohanson A more proper way to do that would be
> 
> `env $(cat .env) ./node_modules/.bin/knex migrate:latest`
> 
> or if you are using an NPM Script:
> 
> `env $(cat .env) knex migrate:latest` (the .bin directory is automatically resolved when using npm scripts)

I get an error when I try to read the .env file with this script.

`env: #: No such file or directory`, I am sure I am setting the env file in the correct path.

**Comment by javierguzman** [comment]
If I call "knex migrate:up --env test" the process.env.NODE_ENV within knexfile shows undefined. Is this expected?

**Comment by shane-js** [comment]
> I had the same problem when I tried to run migrations as npm scripts. It worked when I changed the script to `node -r dotenv/config ./node_modules/knex/bin/cli.js migrate:latest`.

Still working in 2024 - thanks!

**Comment by interhub** [comment]
It helps me to replace `export const` to `export default config` in typescript.
