### ISSUE TITLE
Unnamed error when JSON constraint prevents an update/insert

### ISSUE THREAD

**Issue by milimetric** [knex/knex#6090]
# Environment

Knex version: 3.1.0
Database + version: MariaDB 11.3.2
OS: Debian (docker)

# Missing / erroneus documentation

From the error below, `UNKNOWN_CODE_PLEASE_REPORT` comes up, so I'm doing the reporting :)  As far as I can tell, this was just me trying to save a string instead of a JSON object.  Adding a `JSON.parse` before the save allowed it to go through.

`
{"level":"ERROR","time":"2024-06-27T23:12:44.030Z","pid":165052,"hostname":"phoenix","msg":"Error while registering the instrument: Error: Error while registering the instrument: Error: insert into 'instruments' ('compliance_requirements', 'created_at', 'creator', 'description', 'duration_amount', 'duration_description', 'email_address', 'end_date', 'environments', 'name', 'owner', 'purpose', 'sample_rate', 'sample_unit', 'schema_title', 'schema_type', 'security_legal_review', 'slug', 'start_date', 'status', 'stream_name', 'task', 'type', 'updated_at') values ('legal', '2024-06-27 19:12:44.022', 'testuser', 'test', '1', 'weeks', 'dan@dan.net', '2024-07-07 19:12:44.022', '', 'test-duck', 'Android Team', 'WE.5.2', '[object Object]', 'session', 'analytics/product_metrics/app/base', 'app', 'pending', 'test-duck', '2023-12-30 19:00:00.000', 'off', 'app_base', '21354', 'baseline', '2024-06-27 19:12:44.022') - UNKNOWN_CODE_PLEASE_REPORT: CONSTRAINT 'instruments.sample_rate' failed for 'mpic'.'instruments'"}
`

**Comment by KristjanTammekivi** [comment]
I suspect this error comes from mysql package and not from knex https://github.com/search?q=repo%3Aknex%2Fknex++UNKNOWN_CODE_PLEASE_REPORT&type=code

**Comment by milimetric** [comment]
Indeed, I think I'd have to file it here: https://github.com/mysqljs/mysql/issues/new but that's restricted to contributors so... just closing.
