### ISSUE TITLE
Joined tables overwrite columns with the same name

### ISSUE THREAD

**Issue by AntJanus** [knex/knex#61]
Came upon this today and it's causing me quite a headache, I haven't found a good way of resolving this.

Okay, so take for instance that we create a simple OneToMany join:

```
  var posts = Knex('posts')
      .join('comments', 'comments.parent_id', '=', 'posts.id')
      .where({ 'posts.id': 1}).select()
      .then(function(result){
          res.send(result);
      });
```

The results come back as a flat tree. That makes sense, just like a regular SQL return (meaning that if you have 10 comments, you'll have 10 arrays with data from each comment + a copy of post data); however, if the posts table contains the column "name" and the comments table contains the column "name", the joined table (comments in this case) will overwrite the parent table (posts). Same goes for dates and a bunch of others.

For instance, if you just query for the post, you may get:

```
[ {
    "id": 1,
    "name": "My first post",
    "content": "Little johnny went to the woods...",
    "date": "1/29/2013",
    "category_id": 1
}]
```

When querying a single comment, you may get the following:

```
[{
    "id": 3
    "name": "AntJanus"
    "content": "Hi, this is my first comment",
    "date": "1/31/2013",
    "email": "whatever@whatever.com"
    "parent_id": "1"
}]
```

The resulting join will look like so:

```
[
    {
        "id": 3,
        "name": "AntJanus",
        "content": "Hi, this is my first comment",
        "date": "1/31/2013",
        "email": "whatever@whatever.com",
        "category_id": 1,
        "parent_id": 1
    },
    {
        "id": 4,
        "name": "Some Other",
        "content": "Hi, this is my second comment",
        "date": "2/1/2013",
        "email": "whatever@whatever.com",
        "category_id": 1,
        "parent_id": 1
    }
]
```

And it will completely overwrite original name and content of the post. 

I haven't found a way around it with SQL other than using a select statement that aliases each individual column (there's no way to mass alias in SQL). However, on large and variable tables, this is not really an option.

**Comment by kimmobrunfeldt** [comment]
I fixed this issue with help of this [stackoverflow answer](http://stackoverflow.com/questions/29388036/how-can-i-select-specific-columns-from-a-joined-table-in-knex-js)

In code, my knex query looks like this:
```js
knex
    .select([
        'table_a.id',
        'table_b.id as b_id'
    ])
    .from('table_a')
    .leftJoin(
        table_b,
        'table_a.table_b_id',
        'table_b.id'
    );

```

**Comment by AntJanus** [comment]
@kimmobrunfeldt renaming columns is a fine solution but that means you'd have to list out every single column and if your DB changes, you'd have to update your code. It's not a solution.

I think it'd be great if we could rename a column automatically when we get it back to avoid key collision in Javascript but I wonder if that's more of an issue for `node-mysql` or whatever driver than here in Knex.

**Comment by kimmobrunfeldt** [comment]
@AntJanus yeah I know it's not an optimal solution but wanted to list that workaround for others finding this issue. Also, in most of my cases I only need to select a few predefined columns from the join table, while selecting all columns from the other table. That is achievable like this:

````js
knex
    .select([
        // Select all fields from table a
        'table_a.*',
        // Select only id field from table b
        'table_b.id as b_id'
    ])
    .from('table_a')
    .leftJoin(
        'table_b',
        'table_a.table_b_id',
        'table_b.id'
    );
```

**Comment by AntJanus** [comment]
You gave me an idea, this could work:

```js
knex
  .select([
      'table_b.*',  
      'table_a.*', //table_a values override that table_b id
      'table_b.id as b_id' //and we save the collision
    ])
```
It'd be cool if you could do in SQL something like:

```sql
SELECT table_a.* as table_a_*, table_b.* as table_b_* FROM table_a  ...joins...
```
so that each column from a table would be prefixed.

**Comment by ivan-kleshnin** [comment]
@kimmobrunfeldt thanks for the trick. SQL is often lame in most basic things.

**Comment by DerNamenlose** [comment]
I've stumbled upon the same problem and work around it by a) naming each individual column (annoying, but what can you do?) and b) turning each field name into "table.fieldname as table_fieldname" using this little helper function:
```
function unique_names(fields)
{
    if (fields instanceof Array) {
        return fields.map(field_name => field_name+' as '+field_name.replace('.','_'));
    }
    else {
        return Array.prototype.slice.call(arguments).map(field_name => field_name+' as '+field_name.replace('.','_'));
    }
}
```
It's then used like this:
```
knex('table1').select(unique_names('table1.id', 'table1.field1', 'table2.id','table2.field1', 'table2.unrelated_field')).leftJoin('table2', 'table1.id','table2.id');
```
Returns an object with `{ table1_id, table1_field1, table2_id, table2_field1, table2_unrelated_field}`. Not perfect, but at least I get to keep all the fields.

**Comment by damianobarbati** [comment]
Is this still open? Neither of the aforementioned tricks can be called a solution.
How come table prefix are not respected in returned array of objects holding result? Is it really a limitation of postgresql nodejs driver? Because it's pretty embarassing!

**Comment by whitelynx** [comment]
`node-postgres` has a `rowMode` option that can be passed when running a query. (see <https://github.com/brianc/node-postgres/blob/35e5567f86774f808c2a8518dd312b8aa3586693/test/integration/client/results-as-array-tests.js#L22>) If `rowMode` is set to `'array'`, rows come back as arrays instead of objects, and you can use `result.fields` to get information about each column ("field") in the result set. (as documented at <https://github.com/brianc/node-postgres/wiki/FAQ#3-assuming-a-recordset-is-enumerated-using-the-array-accessor-style-used-in-1-can-we-get-the-column-names-in-the-same-fashion-ie-is-there-a-resultrowsicolumnname-property>)

Sadly, I don't think this gives you any information about what table each column comes from; I don't think PostgreSQL gives you that information in the response. At least it would let you get the duplicated columns correctly, though.

The other problem with this is that I don't believe knex has any way of passing the `rowMode` option to `node-postgres`. I would _really_ like to see that support added, though, since I'm trying to make a generic query tool using knex, and it would be nice to support actually showing all of the columns that get returned to the client. (currently, selecting the same column name twice will actually return that data to the client, but we lose one of the values when `node-postgres` translates each row into an object)

**Comment by chrisbroome** [comment]
@whitelynx You should be able to use the `.options` method to pass provider-specific options. Something like thils:

``` JavaScript
knex.from('table')
  .where('id', 1)
  .options({rowMode: 'array'})
```

**Comment by whitelynx** [comment]
@chrisbroome Cool, I didn't realize that. Thanks for the tip! Now, the only change needed is to be able to get the column information for a result set without having to resort to using `.raw()`.

**Comment by arenddeboer** [comment]
I am working with [treeize](https://github.com/kwhitley/treeize)  to parse the result, especially when using joins into a nice json tree structure.
This also requires a joined table to be aliased like "joinedtable.field AS joinedtable:field" in order for the library to remove duplicates and group collections.

Any tips on how to handle this without resorting to alias all fields?

**Comment by AntJanus** [comment]
@arenddeboer I've worked with Treeize since its inception (not the movie kind) before it became public with @kwhitley and subsequently for a long time as well. We found no way of doing it and ended up with data definitions which were basically large JS arrays of selectors. You could be smart and have those arrays compose but you'd always have to store the actual field names.

**Comment by arenddeboer** [comment]
@AntJanus Thanks. It was your blog article that made me look into treeize ;-)
Just out of curiosity, what are you using at the moment ? No longer knex/treeize?

**Comment by AntJanus** [comment]
@arenddeboer ha! I can't believe that! Thank you! :) So, I'm currently just running everything through bookshelf but obviously, that has its downsides: it doesn't use joins and it has to have a model per table (except for join tables).

And to be honest, I'm using Knex to grab the top-level entity via a custom query and then use the results to fetch the data I'll be using through Bookshelf. I'm hoping to get back to using Treeize but Bookshelf has just so many benefits.

**Comment by arenddeboer** [comment]
Thanks, always interesting to see what is used. I'm coming from sequelize and needed something lighter, more powerful.

**Comment by aakrem** [comment]
` .options({ nestTables: true}` solve the issue as the result will be each table in a different object.

**Comment by olalonde** [comment]
One trick would be to use `.options({ rowMode: 'array' })` and add a "separator" column to know when the joined table's fields start.

PS: I haven't tested the following snipped, just putting it here to illustrate idea

```javascript
knex
   .select('posts.*')
   .selectRaw("'MAGIC_SEPARATOR'")
   .select('comments.*')
    .from('posts')
    .leftJoin(
        'comments',
        'comments.post_id',
        'posts.id'
    );
  .options({rowMode: 'array'})
```

PostgreSQL:

```sql
select 
  "posts".*,
  'MAGIC_SEPARATOR', 
  "comments".*
from users
left join comments on comments.post_id = posts.id;
```

You can then tell you are reading columns from the joined table after you pass the `MAGIC_SEPARATOR` column.

**Comment by mrbeskin** [comment]
Hey, I've ended up here a couple times and thought I would post to let people know what I've found. 

The `.options({nestTables:true})` doesn't work in Postgres, but luckily you can get similar functionality using the `to_json` tools. 

This is outline in an issue for `node-postgres` here:

[Nesting Tables in Node Postgres](https://github.com/brianc/node-postgres/issues/733)

Hope this helps if anyone ends up here like I did.

**Comment by halt-hammerzeit** [comment]
@mrbeskin thx, that works:

```js
		console.log(await knex.select(knex.raw('to_json(authentication_token_access_history.*) as a'), knex.raw('to_json(authentication_tokens.*) as b'))
			.from('authentication_token_access_history')
			.join('authentication_tokens', 'authentication_tokens.id', 'authentication_token_access_history.token')
			.where({ 'authentication_token_access_history.token': 169 })
```

Outputs:

```js
[ anonymous {
    a: 
     { id: 184,
       updated_at: '2016-11-08T14:09:00+03:00',
       ip: '127.0.0.1',
       token: 169,
       place: null },
    b: 
     { id: 169,
       created_at: '2016-11-07T23:49:14.979+03:00',
       revoked_at: '2016-11-08T14:09:17.475+03:00',
       user: 3 } },
...]
```

**Comment by halt-hammerzeit** [comment]
By the way, if anyone's interested, I utilized JOINs to implement `withRelated` bookshelf.js functionality.
I'm not using bookshelf because knex satisfies all my needs, except the `withRelated` feature which I now have (I called it `including`)
https://github.com/halt-hammerzeit/webapp/blob/master/backend/code/common/sql.js#L36
I looked at bookshelf.js itself and it seems that it simply sends additional `.whereIn('id', [ids])` queries for "eager fetching" relations.
https://github.com/tgriesser/bookshelf/blob/master/src/eager.js#L58
While simple, bullet-proof and maintainable, this approach is not hardcore, so I went with JOINs.

**Comment by mulchy** [comment]
Shouldn't this behavior at least throw an 'ambiguous column name' error? Overwriting an arbitrary column doesn't seem like what the user would expect.

**Comment by mrbeskin** [comment]
@mulchy I agree this would be nice, but it this functionality is actually passthrough to the DB driver, thus the issue should be raised on the driver repo. Otherwise I think it would be a significant expansion of scope for `knex`. Perhaps it would be prudent to update the `knex` docs to better indicate that there is passthrough to the driver?

**Comment by mulchy** [comment]
@mrbeskin That makes sense, thanks for clarifying. In that case this probably shouldn't be fixed in knex. It might be worth updating the docs, although I found this github issue easily enough once I noticed the behavior.

**Comment by rickyk586** [comment]
I was having issues with bigint/int8 using to_json(). Was able to fix it with this:
```
const JSONbig = require('json-bigint');
const pg = require('pg');
['114', '3802'].forEach(oid => pg.types.setTypeParser(oid, json => JSONbig.parse(json)));
```

**Comment by nitish24p** [comment]
Any solution for the above, if using MySql without prefixing columns?

**Comment by elhigu** [comment]
@nitish24p  In postgresql there is a `pg `driver has option `rowMode`which allows to fetch rows as an array instead of object, where there can be multiple rows with same name. Check mysql driver if it has similar option available.

**Comment by dortzur** [comment]
Here's a more what I came up with based on @halt-hammerzeit life saving answer:

Here we have a "quote" table who has an originator_id foreign key to a "originator" table.
```javascript
const quoteId = 31;
knex('quote').select(['quote.*', knex.raw('to_json(originator.*) as originator')]).where({'quote.id': quoteId}).join('originator', {'originator.id': 'originator_id'})
```
output:
```json
{
  "id": 31,
  "text": "Success is a lousy teacher. It seduces smart people into thinking they cant lose.",
  "tags": [],
  "originator_id": 4,
  "created_at": "2017-07-01T09:23:17.476Z",
  "updated_at": "2017-07-01T09:23:17.476Z",
  "originator": {
    "id": 4,
    "name": "bill gates",
    "tags": [],
    "image": "https://d3rw4n7nhxn1yy.cloudfront.net/originators/bill-gates-opt.jpg",
    "color": "lightseagreen",
    "created_at": "2017-06-30T23:24:38.035007+03:00",
    "updated_at": "2017-06-30T23:24:38.035007+03:00"
  }
}
```
Hope this will helps.

**Comment by AubreyHewes** [comment]
To fix the problem (mysql) you can also, next to nexting the tables, also prefix each column with the table name using the same `nestTables` option. https://github.com/mysqljs/mysql#joins-with-overlapping-column-names

i.e.

    { 
        "nestTables": "_"
    }

would give you

    {
        "table1_column1": "",
        "table2_column1": "",
    }

**Comment by ftaiolivista** [comment]
> For PostgreSQL the solution given by @dortzur works like a charm, thank you so much:
> 
> ```js
> knex('posts')
> 	.select(['posts.*', knex.raw('to_json(comments.*) as comments')])
> 	.leftJoin('comments', {
> 		'comments.resource_type': knex.raw('?', ['posts']),
>         'comments.resource_id': 'posts.id',
> 	})
> ```
> 
> Then you will have to mapReduce the result in order to have only one object per post in my example.
> 
> ```json
> Array[3][
>   {
>     "id": 1,
>     "created_at": "2018-05-18 16:09:52",
>     "updated_at": "2018-05-18 16:09:52",
>     "content": "foobar",
>     "user_id": null,
>     "project_id": null,
>     "comments": {
>       "id": 3,
>       "created_at": "2018-05-18T17:40:36+02:00",
>       "updated_at": "2018-05-18T17:40:36+02:00",
>       "content": "foobar",
>       "user_id": null,
>       "resource_type": "posts",
>       "resource_id": 1
>     }
>   },
>   {
>     "id": 1,
>     "created_at": "2018-05-18 16:09:52",
>     "updated_at": "2018-05-18 16:09:52",
>     "content": "foobar",
>     "user_id": null,
>     "project_id": null,
>     "comments": {
>       "id": 2,
>       "created_at": "2018-05-18T17:40:32+02:00",
>       "updated_at": "2018-05-18T17:40:32+02:00",
>       "content": "bar",
>       "user_id": null,
>       "resource_type": "posts",
>       "resource_id": 1
>     }
>   },
>   {
>     "id": 1,
>     "created_at": "2018-05-18 16:09:52",
>     "updated_at": "2018-05-18 16:09:52",
>     "content": "foobar",
>     "user_id": null,
>     "project_id": null,
>     "comments": {
>       "id": 1,
>       "created_at": "2018-05-18T17:40:26+02:00",
>       "updated_at": "2018-05-18T17:40:26+02:00",
>       "content": "foo",
>       "user_id": null,
>       "resource_type": "posts",
>       "resource_id": 1
>     }
>   }
> ]
> ```

One disavantage os using JSON is that you loose date and time column information. Usually knex convert datetime columns to javascript Date object but this not happen for json returned fields that remains strings.
