### ISSUE TITLE
knex seed:run doesn't seem to populate the database :(

### ISSUE THREAD

**Issue by socketwiz** [knex/knex#612]
I have created a seed file with knex seed:make, populated it, then run it.  It seems to run just fine without any error.  However it doesn't seem to populate the database with any data.  Here is a test case that reproduces the problem against a postgres 9.1 database: 

https://github.com/socketwiz/knex-test

> Replace the entries in knexfile.js with your own
> npm install
> knex migrate:latest
> knex seed:run
> 
> $ knex seed:run
> Ran 1 seed files
> c:\github\knex-test\seeds\roles.js

Any ideas?

**Comment by demisx** [comment]
Huh, got bitten by this just now. Thank you!!!

**Comment by angristan** [comment]
Thaks! 🙏
