### ISSUE TITLE
Intersection

### ISSUE THREAD

**Issue by timeemit** [knex/knex#621]
Greetings!  I see that UNION is implemented but cannot find any support for INTERSECTION?  Am I missing something?  Or, if not, are there any plans to implement this?

**Comment by bendrucker** [comment]
Not implemented and there's no active plan to do so. We'd happily take a PR.

**Comment by OlivierCavadenti** [comment]
Another issue on this subject : https://github.com/knex/knex/issues/2064
Superseded by https://github.com/knex/knex/pull/3023
