### ISSUE TITLE
How to add a complex join (other than INNER)?

### ISSUE THREAD

**Issue by kwhitley** [knex/knex#65]
e.g.

``` sql
a LEFT JOIN b ON b.a_id = a.id AND a.id = 17
```

using:

``` js
.join('publisher', function() {
  this
    .on('publisher.id', '=', 'school_publisher.publisher_id')
    .on('publisher.slug', '=', 'some-publisher-slug')
  ;
})
```

...always yields a default "INNER JOIN" in the query, and injecting "left" in all the usual spots accomplishes no change.  The need for an outer/left join prevents the using of a where clause on this table, so a complex join is necessary.

**Comment by tbuchok** [comment]
in case anyone else is like us and using an ancient version of knex --  we're on 0.5.16 👎  -- i wanted to add that @tgriesser's fix does work, but with one small tweak:

the property was `this.joinType` (not `this.type`) for us.

here's what we have in production:

```js
qb
  .join('a', function() { 
    this.joinType = 'LEFT'; // woo!
    this.on('a.b_id', '=', 'b.id')
  })
// ... more stuff
```
