### ISSUE TITLE
It would be great to be able to run an individual migration up/down

### ISSUE THREAD

**Issue by simonexmachina** [knex/knex#666]
When I'm developing migrations I often want to just run an individual migration. We have a script that resets the database and runs the migrations, but then if I rollback it rolls back all of the migrations, but I want it to just rollback the last migration so that I can run it again (with changes).

It would be good to be able to run `knex migrate:rollback [migration name]`.

**Comment by chrisbroome** [comment]
:+1: Agreed.

I was definitely surprised by the default behavior of the `knex migrate:rollback` command. The batch behavior is not obvious at all. What's the use case for it?

This is the behavior that I was expecting from rollbacks:

* `knex migrate:rollback` without any arguments should roll back only the last migration that was run
* `knex migrate:rollback [migration name]` should roll back everything up to and including the specified migration

And batch support is still desired, I think there should be an explicit command for it:

* `knex migrate:rollback:batch` should roll back the latest batch of migrations &mdash; in other words, it should do exactly what `knex migrate:rollback` currently does
* `knex migrate:rollback:batch [batch number]` should roll bak to the specified batch number

**Comment by sheerun** [comment]
You can find this feature in [knex-migrate](https://github.com/sheerun/knex-migrate) under `--only` flag.

**Comment by mrdulin** [comment]
Need this feature to rollback db to a specific migration version.

The command maybe like: `knex migrate:rollback --version 20190330113112`

**Comment by sheerun** [comment]
@mrdulin It's `knex-migrate down --to 20190330113112 `

**Comment by ivan-kleshnin** [comment]
What's the difference between `rollback` and `down`? Just another API for the same stuff?
Docs are unclear about that.

**Comment by sheerun** [comment]
rollback rollbacks previous action. down migrates down
