### ISSUE TITLE
How to "insert ignore"?

### ISSUE THREAD

**Issue by TehShrike** [knex/knex#738]
MySQL's [insert](http://dev.mysql.com/doc/refman/5.6/en/insert.html) statement supports `INSERT IGNORE`, which is an awesome feature.

How would one turn a Knex INSERT statement into an INSERT IGNORE?

**Comment by bendrucker** [comment]
There's no ability to do that right now. You'd have to do a raw query. This is certainly something we'll consider as we lay the groundwork for more customizable query compilation.

**Comment by acontreras89** [comment]
:+1:

**Comment by evanbattaglia** [comment]
This would be helpful for me too. Right now I am working around by doing something like `knex.raw(knex('table').insert(foo).toString().replace(/^insert/i, 'insert ignore'))`

**Comment by TehShrike** [comment]
I ended up switching to [node-mysql](https://github.com/felixge/node-mysql) + [sql-concat](https://github.com/TehShrike/sql-concat)

**Comment by Xaekai** [comment]
SQLite has these statements too, and as of PostgreSQL 9.5, it supports a similar syntax as well (ON CONFLICT DO NOTHING). This seems to be a glaring omission, given the 3 most common databases in the open source world all have this.

**Comment by awebdeveloper** [comment]
```
  let query = Bookshelf.knex('items').insert(data).toString();
  query += ' on duplicate key update id=id';
```

**Comment by jadslim313** [comment]
this worked for me for inserting more than one statement:

  ```
 var util = require('util');

  let insert = bookshelf.knex('users').insert([{id : 1234},{id : 12345, {id: 1234}}])
    let query = util.format('%s on duplicate key update id=VALUES(id), name=VALUES(name), gender=VALUES(gender)', 
  insert.toString());
    bookshelf.knex.raw(query).then(function() {
    console.log('success');
}).catch(function(err) {
  console.error(err);
});
```

**Comment by tomasikp** [comment]
Bump

**Comment by elhigu** [comment]
There is pretty good spec in one pull request how this should work... I’ll find it and link it here.

**Comment by designalchemy** [comment]
any update?

**Comment by elhigu** [comment]
No. This issue is now tracked in https://github.com/knex/knex/issues/3186

**Comment by jordansoltman** [comment]
> This would be helpful for me too. Right now I am working around by doing something like `knex.raw(knex('table').insert(foo).toString().replace(/^insert/i, 'insert ignore'))`

Just a warning! The .toString() method is for debugging only and **does not handle dates when a timezone is set on the connection correctly.**

**Comment by trevorr** [comment]
Until #3186 is available, this workaround works for me with Knex 0.20.x and Typescript 3.8:

```ts
Knex.QueryBuilder.extend('ignore', function ignore<TRecord, TResult>(
  this: Knex.QueryBuilder<TRecord, TResult>
): Knex.QueryBuilder<TRecord, TResult> {
  const { sql, bindings } = this.toSQL();
  if (!/^insert /i.test(sql)) {
    throw new Error('insert query expected');
  }
  return this.client.raw('insert ignore ' + sql.substring(7), bindings);
});
```

Put this in `@types/knex/index.d.ts` and add `@types` to `compilerOptions`.`typeRoots` in `tsconfig.json`:

```ts
import 'knex';

declare module 'knex' {
  interface QueryBuilder<TRecord, TResult> {
    ignore(): QueryBuilder<TRecord, TResult>;
  }
}
```

**Comment by JulianSoto** [comment]
This works for me

https://knexjs.org/#Builder-onConflict
