### ISSUE TITLE
Knex js union wrap in parentheses

### ISSUE THREAD

**Issue by khalilTN** [knex/knex#739]
I'm trying to generate this query :

```
(select * from `paymentTable` where `customer_id` = ? limit ? offset ?) 
union 
(select * from `paymentTable` where `customer_id` = ? limit ? offset ? )
union 
(select * from `paymentTable` where `customer_id` = ? limit ? offset ? )
```

I tried :

```
knex.select('*').from('paymentTable')
.where('customer_id', '=', 12).limit(5).offset(1)

.union(function() {
  this.select('*').from('paymentTable')
   .where('customer_id', '=', 13).limit(5).offset(1);
})

.union(function() {
  this.select('*').from('paymentTable')
  .where('customer_id', '=', 14).limit(2).offset(1);
})
```

I tried to use the second param of union() witch is **_wrap**_ and -as it's mentioned in documentation wrap queries inside parentheses- but in vain.
Is there a way to generate a such query without using knex.raw() ?

**Comment by bendrucker** [comment]
Try this against #660

**Comment by mitjap** [comment]
I'm having a same problem..

With __wrap__ set to true, call above would result in:

    select * from "paymentTable" where "customer_id" = '12' 
    union 
        (select * from "paymentTable" where "customer_id" = '13' limit '5' offset '1')
    union 
        (select * from "paymentTable" where "customer_id" = '14' limit '2' offset '1') 
    limit '5' offset '1'

That is not desired output. Both __limit__ and __offset__ should be put to first select which should be in parentheses. I dont think #660 addresses this issue.

**Comment by khalilTN** [comment]
@mitjap it' doesn't work for me 
```javascript
select * from `paymentTable` 
where `customer_id` = ? limit ? offset ?
 union  union 
select * from `paymentTable` where `customer_id` = ? limit ? offset ?
 union  union select * from `paymentTable` where `customer_id` = ? limit ? offset ? union '```

**Comment by xiaohanzhang** [comment]
@tgriesser Is there any update on this issue? Seems QueryCompiler only allow single limit/order/offset, it is not an easy task to support this.
I was wondering maybe we could add a separate wrap function or a top level union function: 
```
const q1 = function() {
  return this.select(*).from('table1').where('foo', 1).orderBy('foo').limit(10);
};
const q2 = function() {
  return this.select(*).from('table1').where('bar', 1).orderBy('foo').limit(10);
};
// idea 1: a wrap function that add parentheses around query
knex.wrap(q1).union(q2).limit(10);
// idea 2: a top level union function that will union queries together.
knex.union([q1, q2]).limit(10);
```

**Comment by juliusza** [comment]
The solution from @mitjap works fine.

eg.
`
knex.union(query1, true).union(query2, true).union(query3, true)
`

**Comment by dalvan-bevilaqua** [comment]
how my code 

SELECT 
	id, sum(coalesce(qtdsaida, 0)) as qtdsaida, sum(coalesce(qtdentrada, 0)) as qtdentrada FROM
( 
    
    SELECT tmp.id, qtdsaida, qtdentrada FROM 
    (

        SELECT 
            p.id,
            sum(coalesce(vp.quantidade, 0)) as qtdsaida,
            0 AS qtdentrada
        FROM 
            produto p 
        LEFT JOIN venda_produto vp on (p.id = vp.idproduto) 
        WHERE 
            p.idempresa = 2 and p.id = 193	
        GROUP BY 
            p.id, vp.idproduto
    UNION ALL
        SELECT 
            p.id,
            0 AS qtdsaida,
            sum(coalesce(em.qtdproduto, 0)) as qtdentrada

        FROM 
            produto p
        LEFT JOIN entradamercadoria em on (p.id = em.idproduto) 
        WHERE 
            p.idempresa = 2 and p.id = 193	
        GROUP BY
            p.id, em.idproduto 
    )as tmp
)AS tmp

**Comment by OlivierCavadenti** [comment]
Old issue (discussions + recent issue here https://github.com/knex/knex/issues/5061)
