### ISSUE TITLE
table.timestamps() creates unusable column names with sailsjs

### ISSUE THREAD

**Issue by itsthatguy** [knex/knex#754]
### Issue

`table.timestamps()` creates `created_at` and `updated_at` while sailsjs is expecting `createdAt` and `updatedAt`

More information: https://github.com/BlueHotDog/sails-migrations/issues/59

**Comment by tgriesser** [comment]
IMO sql column names shouldn't be case sensitive, but if you insist, just use timestamp rather than timestamps. It's one extra line:

```js
table.timestamp('createdAt')
table.timestamp('updatedAt')
```

**Comment by tgriesser** [comment]
Also, I'll probably make this configurable at some point but right now I'm refactoring a ton of stuff internally so it's not something I'm going to fix just yet.

**Comment by tkrotoff** [comment]
@tgriesser Even if you are postponing this, it is best to keep the issue open (and tag it 'backlog', 'future', whatever)

**Comment by tgriesser** [comment]
Eh I'll just leave it open.

**Comment by tkrotoff** [comment]
Thx :)

**Comment by KieranHolroyd** [comment]
@tgriesser is this something that could be fixed now, i'm running into similar issues, it just seems like it should have an options object with columnName as an optional attribute or something?

**Comment by kibertoad** [comment]
@KieranHolroyd This will be fixed in 1.0.0 which should be released this week. There is a new option for that.

**Comment by OlivierCavadenti** [comment]
Yes, this function have now useCamelCase option: 

timestamps — table.timestamps([useTimestamps], [defaultToNow], [useCamelCase])

**Comment by LouiseEH** [comment]
Is there anywhere else you need to set useCamelCase? I get this error message on updates:
[28408] ERROR:  column "updated_at" of relation "status" does not exist at character 75
