### ISSUE TITLE
Prevent multiple (identical) joins of the same table

### ISSUE THREAD

**Issue by AntJanus** [knex/knex#79]
I noticed that a new object contains an array for joins, and I was wondering if there was some way to keep track that there would be no duplicate joins. I'm currently building a complicated query builder / api where it's possible I might join the same table the same way multiple times (which results in a SQL error).

Here's the situation:

```
 var db = Knex.initialize({ ..connection stuff ...});  
 var person = db('persons');
 var query = req.query;
 if(typeof query.shoe !== 'undefined') {
    person.join('clothes', 'person.clothes_id', '=', 'clothes.id');
    person.join('shoes', 'clothes.shoe_id', '=', 'shoes.id');
 }
 if(typeof query.shirt !== 'undefined') {
    person.join('clothes', 'person.clothes_id', '=', 'clothes.id');
    person.join('shirts', 'clothes.shirt_id', '=', 'shirts.id');
 }
```

This would result in an error since we're joining "clothes" twice. So, I originally tried to create an internal "joined table" collection + a wrapper for the join:

```
 var person = db('persons');
 person.joinTables = [];
 person.preJoin = function(table, col1, operator, col2){
    if(_.contains(this.joinTables, table)) {
        //make chainable;
        return this;
    }
    else {
        this.joinTables.push(table);
        return this.join(table, col1, operator, col2);
    }
 }
```

However, I found that while I can easily access the "joinTables" array, the function itself is not accessible. I'm guessing due to the response handler or the way Knex is built with its grammar.js or whatever else.

Any ideas on how I could either implement this function and make it work or have a safety on Knex to allow multiple identical joins? perhaps a check against the joins array to see if an identical entry has been made?

**Comment by awesomejerry** [comment]
It's been a while... but the problem hits me recently.
I need to do the conditional join based on the fields needed.
```
  if (fieldNeeded['name']) {
    queryBuilder.select('person.display_name as name');
    queryBuilder.join('person', 'staff.person_id', 'person.id');
  }
  if (fieldNeeded['email']) {
    queryBuilder.select('person.primary_email as email');
    queryBuilder.join('person', 'staff.person_id', 'person.id');
  }
```
How can I escape the identical join? or is there any workaround? 
It produces `ambigous column name: person.display_name` for me.

**Comment by awesomejerry** [comment]
My current workaround is
```
  if (fieldNeeded['name']) {
    queryBuilder.select('person.display_name as name');
    if (!queryBuilder.personJoined) {
      queryBuilder.join('person', 'staff.person_id', 'person.id');
      queryBuilder.personJoined = true;
    }
  }
  if (fieldNeeded['email']) {
    queryBuilder.select('person.primary_email as email');
    if (!queryBuilder.personJoined) {
      queryBuilder.join('person', 'staff.person_id', 'person.id');
      queryBuilder.personJoined = true;
    }
  }
```
which is quite verbose...

**Comment by martinsik** [comment]
I just encountered the same thing. I'm wondering if there's any recommended best practise...

**Comment by rush-levint** [comment]
You may want to utilize and abstract around the `builder.queryContext()` function found [here](https://knexjs.org/#Builder-queryContext)
