### ISSUE TITLE
Case insensitive .unique Schema

### ISSUE THREAD

**Issue by jamesanthonyferguson** [knex/knex#894]
Hi,
I was just wondering if there was any way to make the .unique() constraint on a schema be case insensitive? e.g. not allow 'dog' if 'Dog' is in already an entry.
Thanks for any help

**Comment by chrisbroome** [comment]
I believe the answer is that it depends on the specific database. For example, MySQL uses collations to determine uniqueness as stated in this StackOverflow answer: http://stackoverflow.com/a/6467030/436977.
