### ISSUE TITLE
JSON Data Types are being added to table as text

### ISSUE THREAD

**Issue by badave** [knex/knex#93]
Not sure if this is something up with our pg node module or knex, but we can't seem to create a table with the column type of json.  It's getting set to text within the database.

**Comment by gitamar** [comment]
I'm using ` "knex": "^0.18.3"`  and `postgres 9.6.11` I'm facing the same issue. 

Here, 
```
exports.up = function(knex, Promise) {
  return knex.schema.createTable('property_pricing', function(table) {
    table.increments('pp_id').primary(['pp_id']);
    table.json('pp_service_included');
  });
};
```

In the above snippet, JSON (`table.json('pp_service_included')`) is inserted as text to postgres table, while I downgrade use `"knex": "^0.14.6"`  and `postgres 9.6.11` everything works normally. Am I implementing it wrong or is there a problem with the newer version?

**Comment by alessandrocaprarelli** [comment]
I have the same problem with:
- knex: `"^0.20.7"`
- pg: ` "^7.17.1"`
- postgresql: `11.6`

**Comment by elhigu** [comment]
@alessandrocaprarelli are you saying that your table.jsonb columns are not created as jsonb columns, but text? Sounds like you are having some different problem.

**Comment by PurpleHexagon** [comment]
Putting this comment here for anyone who might experience this issue in latest version of knex. Ensure you have the correct version of Postgres specified in knexfile. I reused an old knexfile I'd been using for MySQL and forgot to change version number to 10 for Postgres this resulted in jsonb and json columns specified in migrations being added as text.
